### ISSUE TITLE
b is undefined

### ISSUE THREAD

**Issue by DaemonGit** [alexanderzobnin/grafana-zabbix#100]
I have two Datasources and both worked perfect. Today all graphs with the Second Datasource have following Stack trace:

![unbenannt](https://cloud.githubusercontent.com/assets/15106627/10600111/5624f5e2-7708-11e5-9f0e-4fec73706a7d.PNG)

![unbenannt](https://cloud.githubusercontent.com/assets/15106627/10606671/ca2cdaa0-7734-11e5-831b-d54221247ad7.PNG)

**Comment by alexanderzobnin** [comment]
@DaemonGit how you resolve this problem?

**Comment by DaemonGit** [comment]
I had to make every Dashboard new and deleted the old ones. Export import didn't work.
Maybe there was something wrong with the JSON-File of the Dashboard...

**Comment by alexanderzobnin** [comment]
Are you update Grafana or Zabbix plugin?

**Comment by DaemonGit** [comment]
No didn't change the version.
