### ISSUE TITLE
Empty Problem List in 3.12.3

### ISSUE THREAD

**Issue by AndreyRuban** [alexanderzobnin/grafana-zabbix#1003]
After updating the plugin to version 3.12.3
According to the link https://github.com/alexanderzobnin/grafana-zabbix/issues/955 the issue with displaying issues still has not been resolved.
I am using Plugin 3.12.3 Grafana v7.0.5 Zabbix V3.4.14
But Plugin 3.12.3 and Grafana v7.0.5 successfully shows the status of problems in Zabbix V5.0.0 and Zabbix V4.4.7
Checked Plugin 3.11.0 it successfully shows problem stouts in Zabbix V5.0.0, Zabbix V4.4.7 and Zabbix V3.4.14
![Screen1](https://user-images.githubusercontent.com/66548973/88320314-156ae600-cd26-11ea-83b4-3f1047b47e11.jpg)

**Comment by alexanderzobnin** [comment]
Zabbix 3.x is not supported anymore https://github.com/alexanderzobnin/grafana-zabbix/blob/master/CHANGELOG.md#changed
