### ISSUE TITLE
Configuration issues: The necessary configuration items are missing

### ISSUE THREAD

**Issue by PAYNE1Z** [alexanderzobnin/grafana-zabbix#1007]
![image](https://user-images.githubusercontent.com/19740486/89059816-746ad380-d394-11ea-8b9f-24e57e7beb40.png)

My Grafana version is v6.0.2
I have tried to reinstall and restart Grafana, but the problem remains
![image](https://user-images.githubusercontent.com/19740486/89059950-b6941500-d394-11ea-8292-a2d2a0ca621b.png)

What is the problem, please

**Comment by alexanderzobnin** [comment]
Hi! Plugin version 3.12 is not compatible with Grafana 6.x.
