### ISSUE TITLE
wrong sorting order to Zabbix Problems

### ISSUE THREAD

**Issue by pliniosampaio** [alexanderzobnin/grafana-zabbix#1008]
Hello,
Grafana v7.0.3
Plugin 3.12.4
Zabbix 5.0

I try to sort by severity, doesn't work, if I try to click in the title of column, not sorting by other column
 
<img width="1175" alt="Capture" src="https://user-images.githubusercontent.com/63920930/88941677-ecc77c80-d24e-11ea-8d7d-996d94568dd7.PNG">

<img width="1235" alt="Capture02" src="https://user-images.githubusercontent.com/63920930/88941676-ecc77c80-d24e-11ea-89fa-89c27f1218e0.PNG">

_Originally posted by @pliniosampaio in https://github.com/alexanderzobnin/grafana-zabbix/issues/921#issuecomment-666481562_

**Comment by alexanderzobnin** [comment]
duplicates #921
