### ISSUE TITLE
Feature Request: Data Source Config File

### ISSUE THREAD

**Issue by c0nfus3d** [alexanderzobnin/grafana-zabbix#1009]
Following this guide, I have been creating data source config files for all of my data sources.

https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

This will allow me to quickly spin up another grafana instance as needed.

I am trying to make one for Zabbix, but I receive this error 

> Plugin module is missing DataSourcePlugin or Datasource constructor export

Which leads me to believe it is not currently supported in this plugin. Can this feature be added?

**Comment by alexanderzobnin** [comment]
@c0nfus3d Please, refer to [Zabbix datasource provisioning docs](https://alexanderzobnin.github.io/grafana-zabbix/configuration/provisioning/) to configure it. Probably plugin is not installed properly.
