### ISSUE TITLE
Grafana sends 50 requests per second to Zabbix when the configured Zabbix username stops being valid

### ISSUE THREAD

**Issue by koide** [alexanderzobnin/grafana-zabbix#101]
I added a Zabbix source, then, for reasons that are not relevant for the problem at hand, that user stopped being valid.

Whenever I accessed Grafana after the change, I started seeing many, on the order of 50 or so, requests per second from each browser running Grafana to the Zabbix server, effectively DDoSing Zabbix (as we had many people running the Grafana dashboard at the same time) 

Fixing the username/password combination on the Data Source fixed the issue.

It would be nice for Grafana to complain instead of going berserk and starting DoSs :-)

**Comment by alexanderzobnin** [comment]
@koide Thanks for report! I think it is due my plugin trying to send auth request until success. I need to limit attempts to reasonable value. It's serious bug, sorry, but not so hard to fix it. I will try to fix it soon.

**Comment by alexanderzobnin** [comment]
@koide This error was fixed. Fix will be included into coming version for Grafana 3.0.
