### ISSUE TITLE
Update plugin for 3.12.4 and Zabbix Problem stop work

### ISSUE THREAD

**Issue by rldalpiaz** [alexanderzobnin/grafana-zabbix#1010]
**Describe the bug**
After update plugin to version 3.12.4 Zabbix Problems stop work.

**Screenshots**
![image](https://user-images.githubusercontent.com/44619248/89565410-ed36b900-d7f4-11ea-9083-9d1bd11201bc.png)
![image](https://user-images.githubusercontent.com/44619248/89565534-19523a00-d7f5-11ea-831f-c8771576119f.png)

**Software versions**
Grafana 6.3.6
Plugin 3.12.4

**Comment by shizy123** [comment]
Describe the bug
After update plugin to version Grafana-Zabbix 4.0.0-alpha1、2、3、4  Zabbix Problems stop work.
Software versions
Grafana 7.1.0
Plugin Grafana-Zabbix 4.0.0-alpha1、2、3、4

**Comment by jsantala** [comment]
Same thing here. No data. Tried latest 7.x and 6.7.x.

**Comment by alexanderzobnin** [comment]
Plugin is not compatible with Grafana 6 and Zabbix 3.x
