### ISSUE TITLE
Trigger state on the panel (heart icon) doesn't work in Grafana 7.0.3

### ISSUE THREAD

**Issue by YaknaNorti** [alexanderzobnin/grafana-zabbix#1014]
**Describe the bug**
It seems that bug #715 and #931 returned. 

After update zabbix from v4.4 to 5.0.1 and grafana from 6.7 to 7.0.3 heart icons don't show.

**Software versions**
| Grafana | Zabbix | Grafana-Zabbix Plugin |
| -------- | ------- | ---------------------- |
|   7.0.3   |   5.0.1  |         3.12.2                 |

**Comment by alexanderzobnin** [comment]
The alerts highlighting feature is removed in 4.0, so I'm not going to support this anymore. It's tricky to keep it up-to-date because of changes in Grafana. Also, this feature can be partially covered by native alerting support in 4.0.
