### ISSUE TITLE
window.panelsRendered not updated with Zabbix Problems panel

### ISSUE THREAD

**Issue by muutech** [alexanderzobnin/grafana-zabbix#1016]
**Description**
Using Zabbix Problems panel should update "panelsRendered" var in order to use it with rendering functions, which uses this variable to check if dashboard if fully loaded or not (https://github.com/grafana/grafana-image-renderer/blob/master/src/browser/browser.ts)
 
**Expected behavior**
window.panelRendered should be incremented once panel has finished loading.

**Screenshots**
Here you can see if the panel is the only present in dashboard, variable is "undefined"
![image](https://user-images.githubusercontent.com/30987258/90513482-04b06300-e160-11ea-898c-181d43dc2fa7.png)

If we add another panel, it is just 1 but should be 2
![image](https://user-images.githubusercontent.com/30987258/90513751-6a045400-e160-11ea-8f19-d9b667e0e8b4.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.4   | 5.0.2  | 3.12.2                 |

**Comment by alexanderzobnin** [comment]
Ok, it looks like I should use `profiler.renderingCompleted()` method to increase this counter.
```ts
// This is only done to increase a counter that is used by backend
    // image rendering to know when to capture image
    const loading = data.state;
    if (loading === LoadingState.Done) {
      profiler.renderingCompleted();
    }
```
