### ISSUE TITLE
Error on Problems Panel

### ISSUE THREAD

**Issue by danielmjmarques** [alexanderzobnin/grafana-zabbix#1021]
![image](https://user-images.githubusercontent.com/33032935/91291072-0a233400-e784-11ea-8d7e-664d29a83138.png)

I Have data on json but panel not show anything.

Issues after i upgrade my grafa for 7.1.5

Zabbix: 3.4
Grafana: 7.1.5
Zabbix Plugin: 4.0.0 and 3.12.4

**Comment by alexanderzobnin** [comment]
Hi! Do you get this issue only after Grafana upgrade? Does it work on 7.0?

**Comment by alexanderzobnin** [comment]
Does it work with Problems or Recent problems options?

**Comment by danielmjmarques** [comment]
Yes, it worked until I updated Grafana. Then I tried updating the plugin but without success. Funny that he shows the data in json, he just doesn't show it on screen, as if it were a treatment of some undefined variable or something

**Comment by alexanderzobnin** [comment]
Could you take a look at the browser JS console and post errors you've got?

**Comment by danielmjmarques** [comment]
This?
![image](https://user-images.githubusercontent.com/33032935/91309449-1fa65700-e7a0-11ea-89b6-8bf6f6b66123.png)

**Comment by alexanderzobnin** [comment]
Yes, this will help.

**Comment by alexanderzobnin** [comment]
Could you also provide data from the panel inspector? Download CSV button should help with that.

**Comment by danielmjmarques** [comment]
i Try, but only showing this!
![image](https://user-images.githubusercontent.com/33032935/91423341-ccc7b080-e82e-11ea-9e51-59a3499a685b.png)

**Comment by danielmjmarques** [comment]
i think this help
[data.zip](https://github.com/alexanderzobnin/grafana-zabbix/files/5135509/data.zip)

**Comment by danielmjmarques** [comment]
i downgraded my plugin and my grafana. But no Success, no more ideas here!

**Comment by xJMV** [comment]
Same here! Flushed Grafana to a fresh start and I am not able to add a Zabbix data source anymore as it do not appears in the possible data source list. Before I fresh restarted Grafana I was not able to edit the Zabbix data source. The GUI was giving a generic error, nothing in the logs.

@danielmjmarques can you confirm the validity of your data source ? Try to edit it and see if it displays an error...

**Comment by xJMV** [comment]
Oh! Might just have found it!

Have found this in the log (prior/after updating the plugin): 
`t=2020-08-30T12:53:43-0400 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/alex`
`t=2020-08-30T13:42:57-0400 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/alexande...
`
So in grafana.conf I made:
`allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`

and I can now add Zabbix as datasource.

**Comment by danielmjmarques** [comment]
Yeah, i can edit datasource. But i added this allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource on my conf.

**Comment by danieltruong892013** [comment]
The same problem with version, can't show problems on grafana
Zabbix 3.4.15 
Grafana 7.0.0
Plugin zabbix 4.0.0

**Comment by mosen** [comment]
seems to be a regression introduced by git commits fixing #921 or similar. affects Zabbix 3.4

**Comment by mosen** [comment]
disregard the previous comment, just had to throw a null coalesce operator on severity because ZBXProblem.severity didnt exist before eg. in joinTriggersWithProblems()
```
severity: p.severity ?? t.priority,
```
can do a PR for this.

**Comment by danielmjmarques** [comment]
i downgrade Plugin for version 3.11.0 and work!

**Comment by alexanderzobnin** [comment]
Starting 3.12, plugin does not support Zabbix 3.x anymore.

**Comment by danielmjmarques** [comment]
> Starting 3.12, plugin does not support Zabbix 3.x anymore.

Wow, if that was in the documentation I didn't really see it, I'm sorry for the inconvenience. Anyway I managed to make it work, as soon as possible I will update my Zabbix and then update the plugin again to test it.

Thanks in advance, and sorry again.

**Comment by alexanderzobnin** [comment]
It's mentioned in the release notes.
