### ISSUE TITLE
FreeBSD plugin binary

### ISSUE THREAD

**Issue by abaluta** [alexanderzobnin/grafana-zabbix#1022]
Is it possible to make support for freebsd?

There is support only:
zabbix-plugin_darwin_amd64
zabbix-plugin_linux_amd64
zabbix-plugin_windows_amd64.exe

But my grafana server requires:
eror msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="fork/exec /var/db/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_freebsd_amd64: no such file or directory"

I'm ready to help with the compilation.

**Comment by isaqueprofeta** [comment]
"No such file or directory" is commonly a permission error. So I advise you to review your permissions of plugins folder because grafana defaults to not run under root, and if you run grafana-cli as root all plugins go to root user ownership.

**Comment by abaluta** [comment]
This file is really not there. 

I will make it myself, according to Makefile. 
But for the future, you need it to be in the distribution, I think so.

**Comment by isaqueprofeta** [comment]
- First, your plugins is in /var/db/grafana/plugins/ so try an 'ls -la'
- Second, did you try installing the plugin using "grafana-cli plugins install alexanderzobnin-zabbix-app"?

**Comment by abaluta** [comment]
I already have a plugin in /var/db/grafana/plugins. I made it myself, according to Makefile:
https://github.com/alexanderzobnin/grafana-zabbix/issues/1022#issuecomment-680919719

But the distribution doesn't have it:
wget https://github.com/alexanderzobnin/grafana-zabbix/releases/download/v4.0.0/grafana-zabbix-4.0.0.zip
unzip grafana-zabbix-4.0.0.zip

ls -la alexanderzobnin-zabbix-app/zabbix-plugin*
-rwxr-xr-x  1 abaluta  wheel  15016728 Aug 26 11:15 alexanderzobnin-zabbix-app/zabbix-plugin_darwin_amd64
-rwxr-xr-x  1 abaluta  wheel  13750272 Aug 26 11:15 alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64
-rwxr-xr-x  1 abaluta  wheel  13372416 Aug 26 11:15 alexanderzobnin-zabbix-app/zabbix-plugin_windows_amd64.exe

It's not funny. Anyone can do it.

**Comment by isaqueprofeta** [comment]
> I already have a plugin in /var/db/grafana/plugins. I made it myself, according to Makefile:
> [#1022 (comment)](https://github.com/alexanderzobnin/grafana-zabbix/issues/1022#issuecomment-680919719)
> 
> But the distribution doesn't have it:
> wget https://github.com/alexanderzobnin/grafana-zabbix/releases/download/v4.0.0/grafana-zabbix-4.0.0.zip
> unzip grafana-zabbix-4.0.0.zip
> 
> ls -la alexanderzobnin-zabbix-app/zabbix-plugin*
> -rwxr-xr-x 1 abaluta wheel 15016728 Aug 26 11:15 alexanderzobnin-zabbix-app/zabbix-plugin_darwin_amd64
> -rwxr-xr-x 1 abaluta wheel 13750272 Aug 26 11:15 alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64
> -rwxr-xr-x 1 abaluta wheel 13372416 Aug 26 11:15 alexanderzobnin-zabbix-app/zabbix-plugin_windows_amd64.exe
> 
> It's not funny. Anyone can do it.

Oh sorry... Now I understood. The problem is the new backend binary in GoLang.

I advise you to download the Git repo in a dev environment, install golang/nodd and compile it.

Then copy the compiled full plug-in folder to your grafana plugins folder and them after restart grafana server it should be good (be careful with the new unsigned config in grafana.ini)

**Comment by alexanderzobnin** [comment]
There's no precompiled binaries for the FreeBSD now. You can try to build plugin from sources.
