### ISSUE TITLE
Plugin 4.0 problem

### ISSUE THREAD

**Issue by gandhh** [alexanderzobnin/grafana-zabbix#1023]
Hello,

After update plugin from 3.12.4 to 4.0.0, my data source doesn't work anymore.

![image](https://user-images.githubusercontent.com/42584235/91303515-8581e700-e77e-11ea-8fd0-1abfe793dde3.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------   | ----------------------- |
| 7.1.5    | 5.0.2   | 4.0.0                             |

**Comment by Berensek** [comment]
Same here grafana 7.1.3

**Comment by gandhh** [comment]
UPDATING:
In this version, need to be allow plugin on grafana config:
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource

After this, got this error on Grafana:

![image](https://user-images.githubusercontent.com/42584235/91306232-a2b8b480-e782-11ea-988f-b6ded9fa0444.png)

**Comment by jefat** [comment]
Та же история

**Comment by mplm17** [comment]
> UPDATING:
> In this version, need to be allow plugin on grafana config:
> allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
> 
> After this, got this error on Grafana:
> 
> ![image](https://user-images.githubusercontent.com/42584235/91306232-a2b8b480-e782-11ea-988f-b6ded9fa0444.png)

same as here: #1004

**Comment by ronaldoedy** [comment]
Hi,

Error datasources...

Grafana 7.1.5
Zabbix 4.2.8
Grafana-Zabbix Plugin 4.0.0

![image](https://user-images.githubusercontent.com/18762141/91320299-bd475980-e793-11ea-94ed-b4e1df0bf7ea.png)

**Comment by ronaldoedy** [comment]
Update...

Solution to correct the error and downgrade to the version 3.12.2 (Plugin)
https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v3.12.2

**Comment by OMSKremer** [comment]
same problem

Grafana 7.1.5
Zabbix 5.0.3
Grafana-Zabbix Plugin 4.0.0

**Comment by estevaocm14** [comment]
same problem

Grafana 7.1.5
Zabbix 5.0.3
Grafana-Zabbix Plugin 4.0.0

UPDATE:
Its works now!!
added at the end of the file  /etc/grafana/grafana.ini on my debian 10.04 
[plugins]
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
thx y'all

**Comment by ronaldoedy** [comment]
Update...

centos

[plugins]
allow_loading_unsigned_plugins = "plugin1, plugin2, plugin3"

https://github.com/grafana/grafana/issues/24027

**Comment by wjuniorbhz** [comment]
Thanks friends, successfully applied!

**Comment by alexanderzobnin** [comment]
Yes, as said above, it's related to the `allow_loading_unsigned_plugins` option. We're working on the ability to sign plugin to avoid this.
