### ISSUE TITLE
Plugin 3.12.3 : Dependencies not resolved

### ISSUE THREAD

**Issue by luvern** [alexanderzobnin/grafana-zabbix#1024]
Hello,

After update plugin to 3.12.3, Zabbix dependancies are not resolved anymore on Problems Panel. I have to downgrade to 3.12.2.

I saw dependancies are disabled since "Empty Problem List in 3.12.x [#955"]". Is there any way to reactive this functionnality ?

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.5  | 4.4.9  | 3.12.2                 |

Thanks

Regards,

**Comment by alexanderzobnin** [comment]
It seems, that wasn't a reason of the bug, so I can enable this again.

**Comment by luvern** [comment]
Thanks a lot !
