### ISSUE TITLE
Plugin v4.0.0: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by AguirreIF** [alexanderzobnin/grafana-zabbix#1025]
**Describe the bug**
Zabbix API cannot be accessed by v4.0.0 plugin, while v3.12.4 and older versions could. When saving config of zabbix datasource, the following message appears:

    Post https://<zabbix_url>/api_jsonrpc.php: x509: certificate signed by unknown authority.

I have a valid Let's encrypt certificate, why is says its signed by unknown authority? Zabbix and Grafana are on the same host,  so they use the same SSL certificate, it's strange.

**Expected behavior**
Correct connection with Zabbix API.

**Screenshots**

![2020-08-27-000951_739x740_scrot](https://user-images.githubusercontent.com/220615/91379893-0c27da00-e7fa-11ea-8072-ddc7f38b9941.png)
![2020-08-27-000959_973x623_scrot](https://user-images.githubusercontent.com/220615/91379897-0df19d80-e7fa-11ea-8efe-4275ef917656.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.5   | 5.0.3  | 4.0.0                 |

**Comment by Prefix** [comment]
On  your zabbix server make sure that public certificate contains root certificates
https://i.imgur.com/5DX97bV.jpg

**Comment by AguirreIF** [comment]
> On your zabbix server make sure that public certificate contains root certificates
> https://i.imgur.com/5DX97bV.jpg

Hi, thanks so much, that resolved the issue.
