### ISSUE TITLE
Parse error Invalid JSON. An error occurred on the server while parsing the JSON text.

### ISSUE THREAD

**Issue by Prefix** [alexanderzobnin/grafana-zabbix#1026]
**Describe the bug**
I have 2 zabbix, one is v4 (it's working fine) and other is v5 (doesn't work), when I configurate v5 says Parse error Invalid JSON

**Expected behavior**
v4 Zabbix works fine and v5 Zabbix doesn't work

**Screenshots**

https://i.imgur.com/MY66QCO.jpg
**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v7.1.5  | 5.0.2  | 4.0.0                 |

**Comment by alexanderzobnin** [comment]
Duplicates #1004, please post your issue there.
