### ISSUE TITLE
ARM version of alexanderzobnin-zabbix-app not available

### ISSUE THREAD

**Issue by mchangsp** [alexanderzobnin/grafana-zabbix#1028]
**Describe the bug**
When the plugin is loading on a Raspberry Pi I get the error:
`t=2020-08-27T15:38:41+0200 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="fork/exec /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_arm: no such file or directory"`

**Expected behavior**
an ARM version of th eplugin must be available.

**Software versions**
Grafana v7.1.5 running inside Home Assistant hass.io
Grafana-Zabbix plugin
- version 4.0.0
- from https://grafana.com/api/plugins/alexanderzobnin-zabbix-app/versions/4.0.0/download
- plugin alexanderzobnin-zabbix-datasource is listed under grafana config plugins_allow_loading_unsigned_plugins
- (otherwise it would not load)

Full log:
```
-----------------------------------------------------------
 Add-on: Grafana
 The open platform for beautiful analytics and monitoring
-----------------------------------------------------------
 Add-on version: 5.2.3
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grafana.sh: executing... 
installing alexanderzobnin-zabbix-app @ 4.0.0
from: https://grafana.com/api/plugins/alexanderzobnin-zabbix-app/versions/4.0.0/download
into: /var/lib/grafana/plugins

✔ Installed alexanderzobnin-zabbix-app successfully 

Restart grafana after installing plugins . <service grafana-server restart>

[cont-init.d] grafana.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:38:39] INFO: Starting Memcached...
[15:38:39] INFO: Starting Grafana...
[15:38:39] INFO: Setting GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS to alexanderzobnin-zabbix-datasource
t=2020-08-27T15:38:39+0200 lvl=info msg="Starting Grafana" logger=server version=7.1.5 commit=9893b8c53d branch=HEAD compiled=2020-08-25T10:27:17+0200
t=2020-08-27T15:38:39+0200 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2020-08-27T15:38:39+0200 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2020-08-27T15:38:39+0200 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource"
t=2020-08-27T15:38:39+0200 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2020-08-27T15:38:39+0200 lvl=info msg="Path Data" logger=settings path=/data
t=2020-08-27T15:38:39+0200 lvl=info msg="Path Logs" logger=settings path=/var/logs/grafana
t=2020-08-27T15:38:39+0200 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2020-08-27T15:38:39+0200 lvl=info msg="Path Provisioning" logger=settings path=/usr/share/grafana/conf/provisioning
t=2020-08-27T15:38:39+0200 lvl=info msg="App mode production" logger=settings
t=2020-08-27T15:38:39+0200 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-08-27T15:38:39+0200 lvl=info msg="Starting DB migration" logger=migrator
t=2020-08-27T15:38:39+0200 lvl=info msg="Starting plugin search" logger=plugins
t=2020-08-27T15:38:39+0200 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-08-27T15:38:39+0200 lvl=warn msg="Running an unsigned backend plugin" logger=plugins pluginID=alexanderzobnin-zabbix-datasource pluginDir=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix
t=2020-08-27T15:38:39+0200 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-08-27T15:38:39+0200 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Problems"
t=2020-08-27T15:38:39+0200 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-08-27T15:38:41+0200 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="fork/exec /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_arm: no such file or directory"
t=2020-08-27T15:38:41+0200 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl=/api/hassio_ingress/aaaaa socket=
[15:38:41] INFO: Starting NGinx...
```

**Comment by alexanderzobnin** [comment]
Yes, ARM build is not included in the bundle. I'll try to add it in the next release.

**Comment by mchangsp** [comment]
thanks Alexander! And thanks for making and maintaining this nice plugin!

**Comment by 12345oo54321** [comment]
great to hear that is on the 'to do list'. Pi4/buster/zabbix carries easy 25 machines
As today 28aug2020, there is any bundle who has it? (zabbix-plugin_linux_arm)

**Comment by mchangsp** [comment]
> 
> 
> Yes, ARM build is not included in the bundle. I'll try to add it in the next release.

When is the next relase?
Where can I find a release schedule?

**Comment by patricegautier** [comment]
+1 -  Thank you..

**Comment by mchangsp** [comment]
And: if there are instructions somewhere perhaps I can help in generating the ARM version?

**Comment by LazyLama** [comment]
+1
would love to have this installed on my pi4

**Comment by milprog** [comment]
+1
could install it on my pi4 using grafana-cli with the " but when trying to configure the plugin I get errors, presumably related to the fact that the arm version is missing.
A then tried "build from source" but I can't get my npm environment right - "yarn build" gives me the error "Cannot find module 'yargs'" - I then gave up.

**Comment by milprog** [comment]
Meanwhile, I could get the yarn build step done successfully on my pi4, after several modifications to the source files - these mainly relate to compatibilty problems with the node module versions available for the pi. I'm now trying to get the golang toolchain running on my pi4 so hopefully I will be able to recreate the final plugin using the makefile.

**Comment by milprog** [comment]
I could now successfully create the plugin for linux_arm for the pi4 using
`make build-frontend
make build-backend
make test-backend`
and then copy dist/zabbix-plugin_linux_arm to /var/lib/grafana/plugins/alaxanderzobnin-zabbix-app
Everything seems to work just fine until now.
Please find attached the files I modified for getting it done. Note that in the .scss files I only removed all double slash comment lines.
[grafana-zabbix.zip](https://github.com/alexanderzobnin/grafana-zabbix/files/5340516/grafana-zabbix.zip)

**Comment by mchangsp** [comment]
Nice work @milprog !
I am using the Zabbix plugin in a Dockerized version of Grafana. I am not sure how to replicate your modifications in this context.
But I will give it a try

**Comment by milprog** [comment]
...for your convenience, find attached the finished plugin - maybe it will suffice to copy that one to the grafana plugin directory without going through the entire pain of building it again.
[zabbix-plugin_linux_arm.zip](https://github.com/alexanderzobnin/grafana-zabbix/files/5340546/zabbix-plugin_linux_arm.zip)

**Comment by mchangsp** [comment]
Thanks a lotfor the complied plugin file! Indeed I can manage to install a plugin manually. Compiling is another thing...

**Comment by LazyLama** [comment]
Hi milprog,
 I'm not really sure how to get this to work. This is what I tried so far.

```
grafana-cli plugins install alexanderzobnin-zabbix-app
wget https://github.com/alexanderzobnin/grafana-zabbix/files/5340546/zabbix-plugin_linux_arm.zip
unzip zabbix-plugin_linux_arm.zip
cp zabbix-plugin_linux_arm /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/
service grafana-server restart
```

Then via the browser I installed the zabbix plugin, then created the datasource and got a plugin not available error.

Grafana logs show this, which I have no clue.

t=2020-10-10T01:57:50-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/1/resources/zabbix-api status=503 remote_addr=10.0.0.190 time_ms=113
size=32 referer=http://10.0.0.250:3000/datasources/edit/1/

I verified the zabbix service is running.

Any help would be much appreciated.

**Comment by milprog** [comment]
Hi LazyLama

Before doing the command line install, I first had to modify /etc/grafana/grafana.ini:

plugins = /var/lib/grafana/plugins

[plugins]
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource


My grafana was installed from /etc/apt/sources.list.d/grafana.list containing

deb https://packages.grafana.com/oss/deb stable main

Then I first installed the plugin. Then the plugin appears in the grafana frontend, but it cannot be configured. During startup of grafana, I got the message that the plugin file is missing (including the path to the missing file "zabbix-plugin_linux_arm").

After copying the compiled plugin to this location, everything now seems to work.

However, I currently do not use the panels provided by the plugin. I merely use the plugin to configure zabbix as data sources for my own grafana panels.

Best regards
Marcel





>>> LazyLama <notifications@github.com> 10.10.2020 08:12 >>>
Hi milprog,
 I'm not really sure how to get this to work. This is what I tried so far.

```
grafana-cli plugins install alexanderzobnin-zabbix-app
wget https://github.com/alexanderzobnin/grafana-zabbix/files/5340546/zabbix-plugin_linux_arm.zip 
unzip zabbix-plugin_linux_arm.zip
cp zabbix-plugin_linux_arm /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/
service grafana-server restart
```

Then via the browser I installed the zabbix plugin, then created the datasource and got a plugin not available error.

Grafana logs show this, which I have no clue.

t=2020-10-10T01:57:50-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/1/resources/zabbix-api status=503 remote_addr=10.0.0.190 time_ms=113
size=32 referer=http://10.0.0.250:3000/datasources/edit/1/ 

I verified the zabbix service is running.

Any help would be much appreciated.

**Comment by LazyLama** [comment]
Hi Milprog,
  Thanks for the reply. I was able to load the plugin after following your instructions as well as setting zabbix-plugin_linux_arm to an executable. My issue now is that grafana does not populate with the zabbix hosts, nor does it load data. I don't think this is an issue with your file tho.

**Comment by derdeagle** [comment]
+1 - I updated from 3.10.5 to 4.0.1 and the plugin stopped working.
Thanks @milprog for providing an interims solution.

**Comment by Zanxamaru** [comment]
Somehow it still not working for me.
If I download the plugin there is no arm version.
If I copy it manually I also get the same error: Plugin unavailable.

I'm not sure what I am doing wrong... :(

**Comment by flashbyte** [comment]
Hi, 
I also don't have the arm build in the plugin directory.

ls and Mainfest file:
`
/var/lib/grafana/plugins/alexanderzobnin-zabbix-app
bash-5.0$ ls
CHANGELOG.md                     css                              module.js                        zabbix-plugin_darwin_amd64
MANIFEST.txt                     dashboards                       module.js.map                    zabbix-plugin_linux_amd64
README.md                        datasource-zabbix                panel-triggers                   zabbix-plugin_windows_amd64.exe
app_config_ctrl                  img                              plugin.json
bash-5.0$ cat MANIFEST.txt 

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

{
  "manifestVersion": "2.0.0",
  "signatureType": "community",
  "signedByOrg": "alexanderzobnin",
  "signedByOrgName": "Alexander Zobnin",
  "plugin": "alexanderzobnin-zabbix-app",
  "version": "4.0.2",
  "time": 1605277453328,
  "keyId": "7e4d0c6a708866e7",
  "files": {
    "plugin.json": "8980ba28cf74412fc6e6f4f58e97c090eacc538a312ff71007a3f96b112fc076",
    "module.js.map": "4dbefdd5b6019a8394180de27e1925cab414d89b8c2dd03a251b44b7ed6f1ad0",
    "panel-triggers/plugin.json": "614a19f021938707b3e3726747c23a8f78668dc578370cc5a3fc0aba95d90a6f",
    "panel-triggers/module.js.map": "9b24271193d32e1915d4e0023afe17676df40aeb6be3f3f424cdde3bf4f65825",
    "panel-triggers/img/icn-zabbix-problems-panel.svg": "e9afa313c485976d9ea4f6735bdc71af271fde5d72963e3c461d9a10144bd229",
    "panel-triggers/partials/options_tab.html": "8780236792cd7ceb9f3670c0452331b396f6bc6890d2f4568d58d53e8556ba09",
    "panel-triggers/partials/module.html": "1a3a844c81f7944398edf0972567e7d446d2a752878af8a720a179d2ee12ae08",
    "panel-triggers/module.js": "c0a8766918d171bcfbe7c436b91e6af861d14a3c18a9dc4a4d03d3d3fe731020",
    "zabbix-plugin_linux_amd64": "9b9e99a5473d2451f2d802b196eec56dfead2987dab6426ef62cf2995025bddb",
    "app_config_ctrl/config.js": "0b2e5869e3f902937ff4b7acc62b17b3798c8ab978e09f7ed4bc4818b68b171f",
    "app_config_ctrl/config.html": "919b3679cd6b1393eb8e38d8437415ba245367018a2068469af281b0287adce5",
    "app_config_ctrl/config.js.map": "ee84920b3683443e438629d60486dc68ea1667018a7135d25a5f476f6c4ee9de",
    "zabbix-plugin_darwin_amd64": "20444e751d8422680995a5cff52017e95d0b1805bce0e206296811e32863e47a",
    "zabbix-plugin_windows_amd64.exe": "59348f003720e36900b839227b3e9836a309b1e502878d2272fe65d7257ab6e6",
    "css/grafana-zabbix.light.css.map": "5c91676707e979e0ad7a32ebf98e80ea7abc155ecf10bde9ea97600a1ea926e8",
    "css/grafana-zabbix.dark.css.map": "a1b4d57c9eae98a225a3784372eeb6bd75f51448b7d9799eed3e9406827286ef",
    "css/grafana-zabbix.light.css": "a7ede4541c60085e7f687e9902afddf73d6da139afa63c476dc20552da2f82bd",
    "css/grafana-zabbix.dark.css": "ee41c317d721b17e8e8aeb08f991feef943c7b2a68e0b320a6f017bbe481642f",
    "img/screenshot-annotations.png": "b698176703e2af787f58c5856574f55918c468ae69635b3b9e76b3fe2611a0d6",
    "img/screenshot-metric_editor.png": "c99dce5cbcc4858bcb4a432e73c051963178e948014b1fb5689dce17a5624f73",
    "img/screenshot-dashboard01.png": "bb465a73a27ab39e02846cfcd1d551da34e2d2367370ba65bc0dd035d879bd81",
    "img/screenshot-showcase.png": "5be71aacb80a513e7838b99bdeeed246b8d518cb6a846905541806e52dc291f8",
    "img/screenshot-triggers.png": "95bba466dbd9e8eefbe488e83a486e2af5621ec2bbf6bc22f49b4d04a5ea300b",
    "img/icn-zabbix-app.svg": "406bfc69249278c8d0f97462fea735639b05328229d887c2e6b10bf97592fbad",
    "README.md": "3ea0978feb3de3979c1d269ec33b901a042f48becced2d50c3240fe391ea8a17",
    "datasource-zabbix/plugin.json": "a1c2acb8a442ebe2f26c6aca44a1f2d5e8ef8c3b84c6fa2aaf93b9fe779643c1",
    "datasource-zabbix/module.js.map": "08f7a2c4cc718a6cd185f80bfaacc132572e64f67a96cceb4a02360fde2d41bf",
    "datasource-zabbix/query_help.md": "77ed4ea817540d043512057915b6387f6ccf910f8efde7d428b9add7f6142e2b",
    "datasource-zabbix/img/icn-zabbix-datasource.svg": "406bfc69249278c8d0f97462fea735639b05328229d887c2e6b10bf97592fbad",
    "datasource-zabbix/partials/query.editor.html": "941658b08f6d9ebcb60ec7a0fb48614d3c30653e1863e56f86196a56a74c499a",
    "datasource-zabbix/partials/annotations.editor.html": "6aaa8d966cea4e9b1dfffd3e75956c6877481df459efaed9913eb2cc81fec182",
    "datasource-zabbix/module.js": "2be47f4b66de688348818c652a708eaaa3336c82a7d191da18dbedd78603be55",
    "CHANGELOG.md": "da4bb9f61f36fa77ac52ee2eb32285e78b09cc9dc8f38a1cd6059a5df796affd",
    "dashboards/template_linux_server.json": "c1df05a5e8f78d3c9e0f9cfb6686e227273e25ac1f7795ef3d401d95d7107fb0",
    "dashboards/zabbix_server_dashboard.json": "7b26d56de5232460dcadeedd0e7947a2d64f365307f97ea588aa6b469ce2a1a0",
    "dashboards/zabbix_system_status.json": "20b65122a9e39b6d0fc5245bd339e37bf46b662eedf5c3d924acc313b5b4b859",
    "module.js": "10cb08ceb5de028eaff13da184b9279675ca308320fa60d1307e92f952ee2f5c"
  }
}
-----BEGIN PGP SIGNATURE-----
Version: OpenPGP.js v4.10.1
Comment: https://openpgpjs.org

wqAEARMKAAYFAl+ulw0ACgkQfk0ManCIZucdMgIHRA3yOXKIZI/lzYnHtcFr
sG0Z3WPYvp+xeAj1mcQ3RGZNfbMJbSKDw7pQpGGQdWfkADFQve/MfWjc6/08
oj52sHgCCNGyp7ga3jXvNPJxoE8X8onemiafPaT0RruHqu8yLWiheexrL8fD
ZJkM77SkpP3r5BYjzSBZ0RQ27bi8+tqmnIYT
=+9ZI
-----END PGP SIGNATURE-----
`


> Somehow it still not working for me.
> If I download the plugin there is no arm version.
> If I copy it manually I also get the same error: Plugin unavailable.
> 
> I'm not sure what I am doing wrong... :(

**Comment by softxiang** [comment]
> Hi,
> I also don't have the arm build in the plugin directory.
> 
> ls and Mainfest file:
> `
> bash-5.0$ pwd
> /var/lib/grafana/plugins/alexanderzobnin-zabbix-app
> bash-5.0$ ls -1
> CHANGELOG.md
> MANIFEST.txt
> README.md
> app_config_ctrl
> css
> dashboards
> datasource-zabbix
> img
> module.js
> module.js.map
> panel-triggers
> plugin.json
> zabbix-plugin_darwin_amd64
> zabbix-plugin_linux_amd64
> zabbix-plugin_windows_amd64.exe
> 
> bash-5.0$ cat MANIFEST.txt
> 
> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA512
> 
> {
> "manifestVersion": "2.0.0",
> "signatureType": "community",
> "signedByOrg": "alexanderzobnin",
> "signedByOrgName": "Alexander Zobnin",
> "plugin": "alexanderzobnin-zabbix-app",
> "version": "4.0.2",
> "time": 1605277453328,
> "keyId": "7e4d0c6a708866e7",
> "files": {
> "plugin.json": "8980ba28cf74412fc6e6f4f58e97c090eacc538a312ff71007a3f96b112fc076",
> "module.js.map": "4dbefdd5b6019a8394180de27e1925cab414d89b8c2dd03a251b44b7ed6f1ad0",
> "panel-triggers/plugin.json": "614a19f021938707b3e3726747c23a8f78668dc578370cc5a3fc0aba95d90a6f",
> "panel-triggers/module.js.map": "9b24271193d32e1915d4e0023afe17676df40aeb6be3f3f424cdde3bf4f65825",
> "panel-triggers/img/icn-zabbix-problems-panel.svg": "e9afa313c485976d9ea4f6735bdc71af271fde5d72963e3c461d9a10144bd229",
> "panel-triggers/partials/options_tab.html": "8780236792cd7ceb9f3670c0452331b396f6bc6890d2f4568d58d53e8556ba09",
> "panel-triggers/partials/module.html": "1a3a844c81f7944398edf0972567e7d446d2a752878af8a720a179d2ee12ae08",
> "panel-triggers/module.js": "c0a8766918d171bcfbe7c436b91e6af861d14a3c18a9dc4a4d03d3d3fe731020",
> "zabbix-plugin_linux_amd64": "9b9e99a5473d2451f2d802b196eec56dfead2987dab6426ef62cf2995025bddb",
> "app_config_ctrl/config.js": "0b2e5869e3f902937ff4b7acc62b17b3798c8ab978e09f7ed4bc4818b68b171f",
> "app_config_ctrl/config.html": "919b3679cd6b1393eb8e38d8437415ba245367018a2068469af281b0287adce5",
> "app_config_ctrl/config.js.map": "ee84920b3683443e438629d60486dc68ea1667018a7135d25a5f476f6c4ee9de",
> "zabbix-plugin_darwin_amd64": "20444e751d8422680995a5cff52017e95d0b1805bce0e206296811e32863e47a",
> "zabbix-plugin_windows_amd64.exe": "59348f003720e36900b839227b3e9836a309b1e502878d2272fe65d7257ab6e6",
> "css/grafana-zabbix.light.css.map": "5c91676707e979e0ad7a32ebf98e80ea7abc155ecf10bde9ea97600a1ea926e8",
> "css/grafana-zabbix.dark.css.map": "a1b4d57c9eae98a225a3784372eeb6bd75f51448b7d9799eed3e9406827286ef",
> "css/grafana-zabbix.light.css": "a7ede4541c60085e7f687e9902afddf73d6da139afa63c476dc20552da2f82bd",
> "css/grafana-zabbix.dark.css": "ee41c317d721b17e8e8aeb08f991feef943c7b2a68e0b320a6f017bbe481642f",
> "img/screenshot-annotations.png": "b698176703e2af787f58c5856574f55918c468ae69635b3b9e76b3fe2611a0d6",
> "img/screenshot-metric_editor.png": "c99dce5cbcc4858bcb4a432e73c051963178e948014b1fb5689dce17a5624f73",
> "img/screenshot-dashboard01.png": "bb465a73a27ab39e02846cfcd1d551da34e2d2367370ba65bc0dd035d879bd81",
> "img/screenshot-showcase.png": "5be71aacb80a513e7838b99bdeeed246b8d518cb6a846905541806e52dc291f8",
> "img/screenshot-triggers.png": "95bba466dbd9e8eefbe488e83a486e2af5621ec2bbf6bc22f49b4d04a5ea300b",
> "img/icn-zabbix-app.svg": "406bfc69249278c8d0f97462fea735639b05328229d887c2e6b10bf97592fbad",
> "README.md": "3ea0978feb3de3979c1d269ec33b901a042f48becced2d50c3240fe391ea8a17",
> "datasource-zabbix/plugin.json": "a1c2acb8a442ebe2f26c6aca44a1f2d5e8ef8c3b84c6fa2aaf93b9fe779643c1",
> "datasource-zabbix/module.js.map": "08f7a2c4cc718a6cd185f80bfaacc132572e64f67a96cceb4a02360fde2d41bf",
> "datasource-zabbix/query_help.md": "77ed4ea817540d043512057915b6387f6ccf910f8efde7d428b9add7f6142e2b",
> "datasource-zabbix/img/icn-zabbix-datasource.svg": "406bfc69249278c8d0f97462fea735639b05328229d887c2e6b10bf97592fbad",
> "datasource-zabbix/partials/query.editor.html": "941658b08f6d9ebcb60ec7a0fb48614d3c30653e1863e56f86196a56a74c499a",
> "datasource-zabbix/partials/annotations.editor.html": "6aaa8d966cea4e9b1dfffd3e75956c6877481df459efaed9913eb2cc81fec182",
> "datasource-zabbix/module.js": "2be47f4b66de688348818c652a708eaaa3336c82a7d191da18dbedd78603be55",
> "CHANGELOG.md": "da4bb9f61f36fa77ac52ee2eb32285e78b09cc9dc8f38a1cd6059a5df796affd",
> "dashboards/template_linux_server.json": "c1df05a5e8f78d3c9e0f9cfb6686e227273e25ac1f7795ef3d401d95d7107fb0",
> "dashboards/zabbix_server_dashboard.json": "7b26d56de5232460dcadeedd0e7947a2d64f365307f97ea588aa6b469ce2a1a0",
> "dashboards/zabbix_system_status.json": "20b65122a9e39b6d0fc5245bd339e37bf46b662eedf5c3d924acc313b5b4b859",
> "module.js": "10cb08ceb5de028eaff13da184b9279675ca308320fa60d1307e92f952ee2f5c"
> }
> }
> -----BEGIN PGP SIGNATURE-----
> Version: OpenPGP.js v4.10.1
> Comment: https://openpgpjs.org
> 
> wqAEARMKAAYFAl+ulw0ACgkQfk0ManCIZucdMgIHRA3yOXKIZI/lzYnHtcFr
> sG0Z3WPYvp+xeAj1mcQ3RGZNfbMJbSKDw7pQpGGQdWfkADFQve/MfWjc6/08
> oj52sHgCCNGyp7ga3jXvNPJxoE8X8onemiafPaT0RruHqu8yLWiheexrL8fD
> ZJkM77SkpP3r5BYjzSBZ0RQ27bi8+tqmnIYT
> =+9ZI
> -----END PGP SIGNATURE-----
> bash-5.0$
> `

@alexanderzobnin

**Comment by milprog** [comment]
@flashbyte @softxiang I put the plugin in a separate file see my post from oct 14 above, the file is https://github.com/alexanderzobnin/grafana-zabbix/files/5340546/zabbix-plugin_linux_arm.zip  mostly because this is still experimental; especially I had to change quite a few things to make it compile.

**Comment by softxiang** [comment]
> @flashbyte @softxiang I put the plugin in a separate file see my post from oct 14 above, the file is https://github.com/alexanderzobnin/grafana-zabbix/files/5340546/zabbix-plugin_linux_arm.zip mostly because this is still experimental; especially I had to change quite a few things to make it compile. The whole thing depends heavily of the versions installed.

can i use it for arm64?
@milprog

**Comment by alexanderzobnin** [comment]
I've just made a build, you can test it out (it contains ARMv6 and ARM64 binaries):

[alexanderzobnin-zabbix-app-4.0.2.zip](https://github.com/alexanderzobnin/grafana-zabbix/files/5623127/alexanderzobnin-zabbix-app-4.0.2.zip)

**Comment by padziu** [comment]
@alexanderzobnin I try but it doesn't work.

`Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Starting Grafana" logger=server version=7.3.4 commit=14c494085e branch=HEAD compiled=2020-11-24T15:17:31+0100
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="App mode production" logger=settings
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=6507
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Starting DB migrations" logger=migrator
Dec 01 22:55:53 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:53+0100 lvl=info msg="Starting plugin search" logger=plugins
Dec 01 22:55:55 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:55+0100 lvl=info msg="Registering plugin" logger=plugins id=input
Dec 01 22:55:57 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:57+0100 lvl=info msg="Registering plugin" logger=plugins id=alexanderzobnin-zabbix-datasource
Dec 01 22:55:57 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:57+0100 lvl=info msg="Registering plugin" logger=plugins id=alexanderzobnin-zabbix-triggers-panel
Dec 01 22:55:57 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:57+0100 lvl=info msg="Registering plugin" logger=plugins id=alexanderzobnin-zabbix-app
Dec 01 22:55:57 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:57+0100 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl=/grafana socket=
Dec 01 22:55:57 raspberrypi grafana-server[6507]: t=2020-12-01T22:55:57+0100 lvl=info msg=Profiler logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource enabled=false
root@raspberrypi:/etc/grafana# uname -m
armv7l
`

**Comment by softxiang** [comment]
> I've just made a build, you can test it out (it contains ARMv6 and ARM64 binaries):
> 
> [alexanderzobnin-zabbix-app-4.0.2.zip](https://github.com/alexanderzobnin/grafana-zabbix/files/5623127/alexanderzobnin-zabbix-app-4.0.2.zip)

thank you very match
