### ISSUE TITLE
Skip TLS Verify button does not work and is missing from browser access option

### ISSUE THREAD

**Issue by niobyte** [alexanderzobnin/grafana-zabbix#1029]
**Describe the bug**
The Skip TLS Verify button no longer works in the latest plugin version.
It is also missing from the Browser access option. When choosing Server, the option when enabled is ignored.
When choosing either browser or server, the same error is experienced 'Post https://[zabbix]/api_jsonrpc.php: x509: certificate signed by unknown authority'.

**Expected behavior**
The Skip TLS Verify is supposed to ignore any certificate errors e.g. 'x509 certificate signed by unknown authority'.

**Screenshots**
![image](https://user-images.githubusercontent.com/20490775/91527419-544d1680-e938-11ea-93dd-9ed2ca8e5e1f.png)
![image](https://user-images.githubusercontent.com/20490775/91527123-b5281f00-e937-11ea-9da1-0eaa0cb67f67.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.4    | 4.4.8  | 4.0.0                        |

**Comment by alexanderzobnin** [comment]
Other HTTP options do not work as well. I'll fix it too.
