### ISSUE TITLE
Cannot show more than 7 days of data

### ISSUE THREAD

**Issue by xing2828** [alexanderzobnin/grafana-zabbix#103]
grafana-2.1.3-1.x86_64 
 grafana-zabbix 2.1.0-rc1
 zabbix-2.4.6.tar.gz of Package installation
![aaa](https://cloud.githubusercontent.com/assets/14847670/10709812/ab087110-7a6e-11e5-95be-c108ed463920.jpg)

**Comment by xing2828** [comment]
Trends has been disable

**Comment by alexanderzobnin** [comment]
See #78 also. Which period you store in Zabbix history?

**Comment by xing2828** [comment]
Zabbix History storage period was set in 7 days.
Trend storage period was set in 365 days.

Differs from  zabbix2.4.4, zabbix 2.4.6 seems not to have a corresponding trends Patch.  [ZBX-9429](https://support.zabbix.com/browse/ZBX-9429 "ZBX-9429")

**Comment by alexanderzobnin** [comment]
By default Zabbix API can return only history data. You need install trend patch for view more than 7d.
