### ISSUE TITLE
Pluggin enabled but doesnt show in data source list

### ISSUE THREAD

**Issue by LuizizM** [alexanderzobnin/grafana-zabbix#1030]
**Describe the bug**
Doesnt show the Zabbix datasource on "Add data source" with the plugin instaled and enabled, i already have restarted the server after the install and nothing.

**Expected behavior**
it should show zabbix datasource to be added in "Add data source"

**Screenshots**
![image](https://user-images.githubusercontent.com/16512914/91670752-ac317c00-eaf6-11ea-9256-8de63f9e8005.png)
![image](https://user-images.githubusercontent.com/16512914/91670788-fdda0680-eaf6-11ea-9631-69ef4c285e57.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 7 | 5.0.2 | 4 |

**Comment by ruchimal** [comment]
Unsigned plugins are not loading by default, so allow it in the Grafana config file:
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
restart Grafana server

**Comment by LuizizM** [comment]
I made that it worked but now i got this error.

****
![image](https://user-images.githubusercontent.com/16512914/91680380-663ddd80-eb21-11ea-9817-e2c787c75cea.png)

**Comment by mbuyukkarakas** [comment]
I have almost the same problem. Upgraded it successfuly, then restarted. 
The plugin looks like grayed out in the plugins list
