### ISSUE TITLE
Unable to load ZABBIX Plugin

### ISSUE THREAD

**Issue by ruchimal** [alexanderzobnin/grafana-zabbix#1031]
Receiving below error while trying to connect to the Zabbix environment.

![image](https://user-images.githubusercontent.com/8912847/91679334-a2932d00-eb65-11ea-8475-20505aee3791.png)

Environment: Grafana 7.0.0
Zabbix Plugin: 4.0.0

Please see below log details
==================
t=2020-08-31T08:18:04+0530 lvl=info msg="Starting Grafana" logger=server version=7.0.0 commit=aee1438ff2 branch=HEAD compiled=2020-05-15T20:00:30+0530
t=2020-08-31T08:18:04+0530 lvl=info msg="Config loaded from" logger=settings file="C:\\Program Files\\GrafanaLabs\\grafana/conf/defaults.ini"
t=2020-08-31T08:18:04+0530 lvl=info msg="Path Home" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana"
t=2020-08-31T08:18:04+0530 lvl=info msg="Path Data" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data"
t=2020-08-31T08:18:04+0530 lvl=info msg="Path Logs" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data\\log"
t=2020-08-31T08:18:04+0530 lvl=info msg="Path Plugins" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins"
t=2020-08-31T08:18:04+0530 lvl=info msg="Path Provisioning" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\conf\\provisioning"
t=2020-08-31T08:18:04+0530 lvl=info msg="App mode production" logger=settings
t=2020-08-31T08:18:04+0530 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-08-31T08:18:04+0530 lvl=info msg="Starting DB migration" logger=migrator
t=2020-08-31T08:18:04+0530 lvl=info msg="Starting plugin search" logger=plugins
t=2020-08-31T08:18:04+0530 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-08-31T08:18:04+0530 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins\\alexanderzobnin-zabbix-app\\datasource-zabbix"
t=2020-08-31T08:18:04+0530 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Problems"
t=2020-08-31T08:18:04+0530 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-08-31T08:18:04+0530 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned]"
t=2020-08-31T08:18:04+0530 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-08-31T08:20:01+0530 lvl=info msg="Shutdown started" logger=server reason="System signal: interrupt"
t=2020-08-31T08:20:01+0530 lvl=info msg="Stopped Stream Manager"
t=2020-08-31T08:20:03+0530 lvl=info msg="Starting Grafana" logger=server version=7.0.0 commit=aee1438ff2 branch=HEAD compiled=2020-05-15T20:00:30+0530
t=2020-08-31T08:20:03+0530 lvl=info msg="Config loaded from" logger=settings file="C:\\Program Files\\GrafanaLabs\\grafana/conf/defaults.ini"
t=2020-08-31T08:20:03+0530 lvl=info msg="Path Home" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana"
t=2020-08-31T08:20:03+0530 lvl=info msg="Path Data" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data"
t=2020-08-31T08:20:03+0530 lvl=info msg="Path Logs" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data\\log"
t=2020-08-31T08:20:03+0530 lvl=info msg="Path Plugins" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins"
t=2020-08-31T08:20:03+0530 lvl=info msg="Path Provisioning" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\conf\\provisioning"
t=2020-08-31T08:20:03+0530 lvl=info msg="App mode production" logger=settings
t=2020-08-31T08:20:03+0530 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-08-31T08:20:03+0530 lvl=info msg="Starting DB migration" logger=migrator
t=2020-08-31T08:20:03+0530 lvl=info msg="Starting plugin search" logger=plugins
t=2020-08-31T08:20:03+0530 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-08-31T08:20:03+0530 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins\\alexanderzobnin-zabbix-app\\datasource-zabbix"
t=2020-08-31T08:20:03+0530 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Problems"
t=2020-08-31T08:20:03+0530 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-08-31T08:20:03+0530 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned]"
t=2020-08-31T08:20:03+0530 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-08-31T08:21:41+0530 lvl=info msg="Shutdown started" logger=server reason="System signal: interrupt"
t=2020-08-31T08:21:41+0530 lvl=info msg="Stopped Stream Manager"
t=2020-08-31T08:30:15+0530 lvl=info msg="Starting Grafana" logger=server version=7.0.0 commit=aee1438ff2 branch=HEAD compiled=2020-05-15T20:00:30+0530
t=2020-08-31T08:30:15+0530 lvl=info msg="Config loaded from" logger=settings file="C:\\Program Files\\GrafanaLabs\\grafana/conf/defaults.ini"
t=2020-08-31T08:30:15+0530 lvl=info msg="Path Home" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana"
t=2020-08-31T08:30:15+0530 lvl=info msg="Path Data" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data"
t=2020-08-31T08:30:15+0530 lvl=info msg="Path Logs" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data\\log"
t=2020-08-31T08:30:15+0530 lvl=info msg="Path Plugins" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins"
t=2020-08-31T08:30:15+0530 lvl=info msg="Path Provisioning" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\conf\\provisioning"
t=2020-08-31T08:30:15+0530 lvl=info msg="App mode production" logger=settings
t=2020-08-31T08:30:15+0530 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-08-31T08:30:15+0530 lvl=info msg="Starting DB migration" logger=migrator
t=2020-08-31T08:30:15+0530 lvl=info msg="Starting plugin search" logger=plugins
t=2020-08-31T08:30:15+0530 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-08-31T08:30:15+0530 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins\\alexanderzobnin-zabbix-app\\datasource-zabbix"
t=2020-08-31T08:30:15+0530 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Problems"
t=2020-08-31T08:30:15+0530 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-08-31T08:30:15+0530 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned]"
t=2020-08-31T08:30:15+0530 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-08-31T08:33:30+0530 lvl=info msg="Shutdown started" logger=server reason="System signal: interrupt"
t=2020-08-31T08:33:30+0530 lvl=info msg="Stopped Stream Manager"
t=2020-08-31T08:33:31+0530 lvl=info msg="Starting Grafana" logger=server version=7.0.0 commit=aee1438ff2 branch=HEAD compiled=2020-05-15T20:00:30+0530
t=2020-08-31T08:33:31+0530 lvl=info msg="Config loaded from" logger=settings file="C:\\Program Files\\GrafanaLabs\\grafana/conf/defaults.ini"
t=2020-08-31T08:33:31+0530 lvl=info msg="Path Home" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana"
t=2020-08-31T08:33:31+0530 lvl=info msg="Path Data" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data"
t=2020-08-31T08:33:31+0530 lvl=info msg="Path Logs" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data\\log"
t=2020-08-31T08:33:31+0530 lvl=info msg="Path Plugins" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins"
t=2020-08-31T08:33:31+0530 lvl=info msg="Path Provisioning" logger=settings path="C:\\Program Files\\GrafanaLabs\\grafana\\conf\\provisioning"
t=2020-08-31T08:33:31+0530 lvl=info msg="App mode production" logger=settings
t=2020-08-31T08:33:31+0530 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-08-31T08:33:31+0530 lvl=info msg="Starting DB migration" logger=migrator
t=2020-08-31T08:33:31+0530 lvl=info msg="Starting plugin search" logger=plugins
t=2020-08-31T08:33:31+0530 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-08-31T08:33:31+0530 lvl=warn msg="Running an unsigned backend plugin" logger=plugins pluginID=alexanderzobnin-zabbix-datasource pluginDir="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins\\alexanderzobnin-zabbix-app\\datasource-zabbix"
t=2020-08-31T08:33:31+0530 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-08-31T08:33:31+0530 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Problems"
t=2020-08-31T08:33:31+0530 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-08-31T08:33:31+0530 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-08-31T08:33:31+0530 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="exec: \"zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%"
t=2020-08-31T08:35:05+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:35:05+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:35:05+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=17 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:35:05+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=4 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:38:23+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:38:23+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:38:23+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=15 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:38:23+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=5 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:38:57+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:38:57+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=25 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:38:57+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:38:57+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=13 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:38:58+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:38:58+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=1 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:38:58+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:38:58+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=11 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:39:26+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:39:26+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:39:26+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=25 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:39:26+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=14 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:39:28+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:39:28+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=1 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:39:28+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:39:28+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=35 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:39:28+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:39:28+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=1 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:39:28+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:39:28+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=0 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:39:29+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:39:29+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=0 size=24 referer=http://localhost:3000/datasources/edit/4/
t=2020-08-31T08:39:29+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"
t=2020-08-31T08:39:29+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=500 remote_addr=[::1] time_ms=21 size=24 referer=http://localhost:3000/datasources/edit/4/

**Comment by koto137** [comment]
please read release/install notes

Installation
Prerequisites: plugin requires Grafana 7.0 to run.

Use the grafana-cli tool to install Zabbix from the commandline:

grafana-cli plugins install alexanderzobnin-zabbix-app
Unsigned plugins are not loading by default, so allow it in the Grafana config file:
`allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`
restart Grafana server
Refer to allow_loading_unsigned_plugins option description for more information.

**Comment by ruchimal** [comment]
Hello koto137,

Thank you for the details

i have followed all the stems mentioned by Alexander & you but unfortunately I am ended with the above error.

**Comment by koto137** [comment]
at first, adding the line to the grafana.ini did not work for me too, but after searching for the value in grafana.ini I found it under [plugin] section

`[plugins]
;enable_alpha = false
;app_tls_skip_verify_insecure = false
# Enter a comma-separated list of plugin identifiers to identify plugins that are allowed to be loaded even if they lack a valid signature.
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`

**Comment by ruchimal** [comment]
I tried above but it did not work.

Can you please let me know your environmental details pls and mine are 
Zabbix: 3.4
Grafana: 7.1.5

Appreciate if you could help me.

**Comment by koto137** [comment]
sorry I misread the log you shared, at first I just noticed the plugin unsigned, and that got fixed, last error is this

`t=2020-08-31T08:33:31+0530 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="exec: "zabbix-plugin_windows_amd64.exe": executable file not found in %PATH%"`

but I am unfamiliar with windows env with Grafana, cannot help you much, unfortunately
in Linux, there can be problems with file permissions, the only thing that comes to my mind

**Comment by ruchimal** [comment]
Thank you for pointing out.

I will log this under  a different issue.

**Comment by ruchimal** [comment]
Raising the issue under a different id
