### ISSUE TITLE
In plugin version 4.0.0, flag 'skip tls verify' in datasource definition is ignored.

### ISSUE THREAD

**Issue by marcinbojko** [alexanderzobnin/grafana-zabbix#1032]
**Describe the bug**
In plugin version 4, flag 'skip tls verify' in datasource definition is ignored.

**Expected behavior**
Allow to skip tls verification in case of selfsigned xertificates

**Screenshots**

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.5   | 4.0.0  |      4.0.0|

![Selection_808](https://user-images.githubusercontent.com/4726723/91723745-88287600-eb9c-11ea-87d6-7d48f9cda94e.png)

**Comment by marcinbojko** [comment]
{"error":"Post https://xxxxxxxxxx/zabbix/api_jsonrpc.php: x509: certificate signed by unknown authority","logger":"plugins.backend","lvl":"eror","msg   │
│   ":"Zabbix API request error","pluginId":"alexanderzobnin-zabbix-datasource","t":"2020-08-31T13:38:41.237357585Z"}

**Comment by alexanderzobnin** [comment]
Duplicates #1029
