### ISSUE TITLE
Panel Problem (table and list) showing alerts with minor and major severity about the same trigger and the same host.

### ISSUE THREAD

**Issue by 1vicente** [alexanderzobnin/grafana-zabbix#1034]
**Describe the bug**
This panel is showing alerts with minor and major severity about the same trigger and the same host.

**Expected behavior**
Show only last result and the most severity of the trigger triggered of host.

**Screenshots**
Using Grafana 7.1.5 and Grafana-Zabbix Plugin 4.0.0.
![image](https://user-images.githubusercontent.com/13755048/91752349-a0989080-eb9c-11ea-8abe-267ba5bd973f.png)

Using Grafana 6.0. and Grafana-Zabbix Plugin 3.10.1
![image](https://user-images.githubusercontent.com/13755048/91752688-1dc40580-eb9d-11ea-9f12-9fee6523e3ad.png)

Both Grafanas are configured to use same Data Source (Zabbix Server).

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.5   | 4.0.6 | 4.0.0                 |

**Comment by danieltruong892013** [comment]
hello,

Can you show the config of this one?

**Comment by 1vicente** [comment]
Hi Daniel,

Follow screenshots.

Using Grafana 6.0. and Grafana-Zabbix Plugin 3.10.1
![image](https://user-images.githubusercontent.com/13755048/91898953-ddcf5200-ec72-11ea-9e92-e8ecbce77997.png)
![image](https://user-images.githubusercontent.com/13755048/91899085-08210f80-ec73-11ea-8ea4-81bd81b21079.png)


Using Grafana 7.1.5 and Grafana-Zabbix Plugin 4.0.0.
![image](https://user-images.githubusercontent.com/13755048/91899615-cba1e380-ec73-11ea-9c09-c72426a0c440.png)
![image](https://user-images.githubusercontent.com/13755048/91899713-ed9b6600-ec73-11ea-998c-058d6bdff863.png)

**Comment by alexanderzobnin** [comment]
Hi! Can you confirm the problem in the 4.0.1 plugin version? It seems, it was fixed in #1024.

**Comment by 1vicente** [comment]
Sr. Zobnin,

I checked it and was solved.

![image](https://user-images.githubusercontent.com/13755048/93084204-15be9800-f66a-11ea-84b3-9213a7af721b.png)

Thanks!
