### ISSUE TITLE
Grafana-Zabbix plugin is still not working after the unsigned plugin config change.

### ISSUE THREAD

**Issue by mbuyukkarakas** [alexanderzobnin/grafana-zabbix#1035]
**The plugin is not loading / working correctly**
My working grafana / zabbix versions are : Zabbix 4.4.4 / Grafana 6.4 / Zabbix-Grafana plugin 3.4

After the complete upgrade to Zabbix v5. / Grafana 7.1.5 / Zabbix-Grafana to 4.0.0 version , the working dashboards are not displaying the correct values. 
Some dashboard have lost their normal aspect. I see some anormal log lines in grafana log.

`t=2020-08-31T20:07:44+0300 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned Plugin with ID \"grafana-worldmap-panel\" already exists]"
t=2020-08-31T20:07:45+0300 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"
t=2020-08-31T20:07:45+0300 lvl=info msg="Syncing plugin dashboards to DB" logger=plugins pluginId=alexanderzobnin-zabbix-app
t=2020-08-31T20:07:45+0300 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-08-31T20:08:03+0300 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
t=2020-08-31T20:10:41+0300 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/plugins/alexanderzobnin-zabbix-datasource/settings status=404 remote_addr=10.212.133.7 time_ms=1 size=64 referer=http://zabbix.horoz:3000/datasources/edit/1/
t=2020-08-31T20:16:30+0300 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
t=2020-08-31T20:16:38+0300 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/plugins/alexanderzobnin-zabbix-datasource/settings status=404 remote_addr=10.212.133.7 time_ms=1 size=64 referer=http://zabbix.horoz:3000/datasources/edit/1/
t=2020-08-31T20:18:35+0300 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
t=2020-08-31T20:18:42+0300 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/plugins/alexanderzobnin-zabbix-datasource/settings status=404 remote_addr=10.212.133.7 time_ms=1 size=64 referer=http://zabbix.horoz:3000/datasources/edit/1/
t=2020-08-31T20:18:47+0300 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/plugins/alexanderzobnin-zabbix-datasource/settings status=404 remote_addr=10.212.133.7 time_ms=1 size=64 referer=http://zabbix.horoz:3000/datasources/edit/1/
t=2020-08-31T20:22:09+0300 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
t=2020-08-31T20:22:45+0300 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
t=2020-08-31T20:30:40+0300 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
t=2020-08-31T20:32:06+0300 lvl=info msg="Plugin state changed" logger=plugins pluginId=alexanderzobnin-zabbix-app enabled=false
t=2020-08-31T20:32:06+0300 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
t=2020-08-31T20:32:09+0300 lvl=info msg="Plugin state changed" logger=plugins pluginId=alexanderzobnin-zabbix-app enabled=true
t=2020-08-31T20:32:09+0300 lvl=info msg="Syncing plugin dashboards to DB" logger=plugins pluginId=alexanderzobnin-zabbix-app
t=2020-08-31T20:32:09+0300 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
t=2020-08-31T20:32:12+0300 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
`
I made the necessary unsigned plugin configuration change. But it didnt changed the situation.
 

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| -------      | ------    | --------------------- |
| 7.1.5      | 5.0.3    |  4.0.0                |

**Comment by mbuyukkarakas** [comment]
One more thing.

After trying to reconnect grafana to zabbix API I had this error message.

t=2020-09-01T09:57:08+0300 lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="Parse error Invalid JSON. An error occurred on the server while parsing the JSON text.

**Comment by matiasba** [comment]
I'm having the same error whit an invalid JSON, had to roll back the plugin to 3.12.2

**Comment by corgan2222** [comment]
same problem here after the latest update

>Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"                                                                                                                                   │
Could not find plugin definition for data source: grafana-simple-json-backend-datasource"                                                                                                                              │
Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix                                │
Some plugins failed to load" logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned plugin \"grafana-simple-json-backend-datasource\" is unsigned Plugin with ID \"geeksrus-mqtt-panel\" alre│
Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"                                                                                                                                   │
Could not find plugin definition for data source: grafana-simple-json-backend-datasource"

**Comment by corgan2222** [comment]
fixed it by adding

`[plugins]
enable_alpha = true
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`

[to /etc/grafana/grafana.ini ](https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins)

is this normal to do so?

**Comment by alexanderzobnin** [comment]
I'm working on signing plugin, so next release will be signed and should be loaded without problems.

**Comment by stlinux** [comment]
Hi, same error.
{code}
t=2020-09-13T01:57:57-0500 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
t=2020-09-13T01:58:02-0500 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/plugins/alexanderzobnin-zabbix-datasource/settings status=404 remote_addr=192.168.146.226 
{code}

**Comment by vandykew** [comment]
Im also getting this error even after upgrading to the signed plugin

**Comment by alexanderzobnin** [comment]
That's fixed in Grafana 7.3. Try to test it against 7.3-beta release.

**Comment by fauust** [comment]
Yes, that seems to be resolved with grafana `7.3.0-beta2` (tested the container setup).

**Comment by HoracioDos** [comment]
> fixed it by adding
> 
> ```
> [plugins]
> enable_alpha = true #you probely dont need this
> allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
> ```
> 
> [to /etc/grafana/grafana.ini ](https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins)

This worked fine for me today - Grafana 7.2.2 Zabbix plugin 4.0.1

**Comment by fauust** [comment]
> > fixed it by adding
> > ```
> > [plugins]
> > enable_alpha = true #you probely dont need this
> > allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
> > ```
> > 
> > 
> > [to /etc/grafana/grafana.ini ](https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins)
> 
> This worked fine for me today - Grafana 7.2.2 Zabbix plugin 4.0.1

Yes, but be sure to remove it when you upgrade grafana to 7.3 as it should be working as https://github.com/alexanderzobnin/grafana-zabbix/issues/1035#issuecomment-715248524 says.

**Comment by JMarioB** [comment]
In docker for windows problem persing  using image "grafana/grafana-oss:7.0.0-beta1-ubuntu", even if plugin configuration was applyed.

docker run --name grafana ^
-e "GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,grafana-clock-panel,grafana-simple-json-datasource" ^
-d grafana/grafana-oss:7.0.0-beta1-ubuntu
