### ISSUE TITLE
Browser access mode not working with 4.0 plugin

### ISSUE THREAD

**Issue by darkblaze69** [alexanderzobnin/grafana-zabbix#1037]
**Describe the bug**
when trying to setup datasource with browser access mode:
"Post https://example.com/api_jsonrpc.php: dial tcp 198.51.100.157:443: connect: connection refused"
Although according to DevTools the browser even doesn't try to connect.

**Software versions**

```
| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.5   | 4.4.10 | 4.0.0                 |
```

**Comment by alexanderzobnin** [comment]
Hi! Yes, browser mode not supported in 4.0. Why can't you use proxy mode?

**Comment by darkblaze69** [comment]
For example we have a grafana published with internal zabbix datasource without internet access (no internet for grafana as well). And the browser mode allows us to add another zabbix instance datasource published in Internet accessible by clients by their browser. Hence we have dashboards with combination of internal zabbix (server mode) and external zabbix (browser mode) accessible by clients.

**Comment by cdaher78** [comment]
I´ve also made the upgrade and lost my db connection to the API.

I'm using server mode and it shows "Parse error Invalid JSON. An error occurred on the server while parsing the JSON text."

Tried to use POSTMAN to check API response, using Zabbix API request recommendadion and it shows the same:

{
    "jsonrpc": "2.0",
    "error": {
        "code": -32700,
        "message": "Parse error",
        "data": "Invalid JSON. An error occurred on the server while parsing the JSON text."
    },
    "id": null
}

Please, what should I do to make it work?

Thanks in advance.

**Comment by alexanderzobnin** [comment]
`Parse error Invalid JSON` bug is fixed and will be released soon.

**Comment by cdaher78** [comment]
Great news Alexander!!

I returned the plugin to the last version it was running. As soon as it is released I will do the update.

**Comment by darkblaze69** [comment]
The explanation makes sense. Maybe it should be mentioned in the interface or even remove this option in the interface?

**Comment by alexanderzobnin** [comment]
@darkblaze69 yes, probably. But HTTP settings is a part of Grafana, so I either can leave it as is or re-implement all options (TLS settings, basic auth, etc). So maybe it makes sense to add information banner about browser mode.
