### ISSUE TITLE
Plugin is not signed

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#1038]
Unsigned plugins cause a problems with loading (not allowed by default in Grafana) and decline user experience. So plugin should be signed to improve overall experience during upgrades.

**Comment by Luckyvb** [comment]
t=2020-10-13T12:34:26+0000 lvl=info msg="App mode production" logger=settings
t=2020-10-13T12:34:26+0000 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=3819
t=2020-10-13T12:34:26+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-10-13T12:34:26+0000 lvl=info msg="Starting DB migrations" logger=migrator
t=2020-10-13T12:34:26+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2020-10-13T12:34:26+0000 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-10-13T12:34:26+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="**plugin \"alexanderzobnin-zabbix-datasource\" is unsigned**" pluginPath=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix
t=2020-10-13T12:34:26+0000 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Problems"
t=2020-10-13T12:34:26+0000 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-10-13T12:34:26+0000 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned]"
t=2020-10-13T12:34:27+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
______________________________________________
    "version": "**4.0.1**",
    "updated": "2020-01-02",
    "build": {
      "time": 1599059176216,
      "repo": "git@github.com:alexanderzobnin/grafana-zabbix.git",
      "branch": "",
      "hash": "89e885b9452d48d15ba83320f88c584cb023a4bd",
      "number": 2035
    }
