### ISSUE TITLE
DataSources Zabbix

### ISSUE THREAD

**Issue by avokado5kg** [alexanderzobnin/grafana-zabbix#104]
В списке подключаемых ресурсов отсутствует Zabbix. На сервер с Zabbix 2.4.5 Установлен grafana-server (после установки конфигурация не изменялась). Плагин grafana-zabbix-2.0.0, содержимое папки скопировано в /usr/share/grafana/public/app/plugins/datasource/zabbix. Пути в  plugin.json прописаны верно. Не очень понял какие необходимо указывать имя пользователя и пароль в plugin.json. 

Заранее благодарю за помощь.

**Comment by alexanderzobnin** [comment]
Если вы используете последнюю версию Grafana, то вся настройка выполняется на странице настройки датасорса.

**Comment by avokado5kg** [comment]
Какой тип подключения выбирать в таком случае? 
http://prntscr.com/8vuwzj

Спасибо за быстрый ответ.

**Comment by nucleusv** [comment]
У вас не обнаружился датасорс. Проверьте в нужную ли папку положили и перезагрузите сервер графаны service grafana-server restart

**Comment by avokado5kg** [comment]
http://prntscr.com/8vv6ve

Перезагружал и не раз. Уже сутки бьюсь с ним и ничего не выходит.

27 октября 2015 г., 14:50 пользователь nucleusv <notifications@github.com>
написал:

**Comment by nucleusv** [comment]
странно конечно, смотрите логи графаны (проверьте права на плагине), смотрите в браузере f12, там должны быть ошибки джаваскрипта.

**Comment by avokado5kg** [comment]
Все дело оказалось в правах, спасибо за помощь.
Тему можно закрывать.

27 октября 2015 г., 15:27 пользователь nucleusv <notifications@github.com>
написал:
