### ISSUE TITLE
No datasource in the datasource list

### ISSUE THREAD

**Issue by andaks** [alexanderzobnin/grafana-zabbix#1043]
**Describe the bug**
No datasource in the list installed after installing and enable plugin.

**Expected behavior**
There shoud be able to add new zabbix datasource.

**Screenshots**
![Annotation 2020-09-03 021445](https://user-images.githubusercontent.com/5965423/92020804-50335580-ed8b-11ea-9637-9f50e0a3c770.png)
![Annotation 2020-09-03 021247](https://user-images.githubusercontent.com/5965423/92020824-545f7300-ed8b-11ea-827e-8a84ad5709d2.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.5   |  4.0.24  | 4.0.1                 |

**Comment by andaks** [comment]
Solved by adding "alexanderzobnin-zabbix-datasource"  to "allow_loading_unsigned_plugins" in grafana configuration

**Comment by jothoma1** [comment]
Same for me, thanks @andaks for the allow_loading tip

**Comment by ruchimal** [comment]
Thank you for your support. now i am receiving the below error.

ror msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="exec: \"zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%"

**Comment by alexanderzobnin** [comment]
Hi! Are you sure you have 4.0.1? It should be signed. Could you list the directory of the installed plugin? There should be `MANIFEST.txt` file with sign:
```sh
# ls /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/
app_config_ctrl  datasource-zabbix  module.js       plugin.json                 zabbix-plugin_linux_amd64
css              img                module.js.map   README.md                   zabbix-plugin_windows_amd64.exe
dashboards       MANIFEST.txt       panel-triggers  zabbix-plugin_darwin_amd64
```

**Comment by Irytacja** [comment]
Same for me, with version 4.0.0 or 4.0.1 (4.0.0 isn't signed, 4.0.1 is) 
Grafana version: Grafana v7.1.5 (9893b8c53d) (Freshly installed 15 minutes ago)

After installing plugin with grafana-cli and enabling it in grafana interface, there's no zabbix datasource. 
I've tried this solution `Temporary solved by adding "alexanderzobnin-zabbix-datasource" to "allow_loading_unsigned_plugins" in grafana configuration.`  with no success.  3.12.2 version works ok.

**Comment by ruchimal** [comment]
Everything is perfectly installed and the plugin is registered correctly but i am receiving below error.

Grafana: 7.0.0
Zabbix Plugin: 4.0.1

![Zabbix1](https://user-images.githubusercontent.com/8912847/92116173-1b69e180-ee11-11ea-875c-b0382c9b52af.PNG)
![Zabbix2](https://user-images.githubusercontent.com/8912847/92116176-1c9b0e80-ee11-11ea-8333-90783f0e7f68.PNG)
![Zabbix3](https://user-images.githubusercontent.com/8912847/92116178-1d33a500-ee11-11ea-9158-f7d14080a645.PNG)

msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="exec: \"zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%"
t=2020-09-03T18:09:20+0530 lvl=eror msg="Failed to " logger=context userId=1 orgId=1 uname=admin error="Failed to call resource: plugin not running, cannot call resource"

**Comment by sanindd** [comment]
@alexanderzobnin Привет, попробовал 2 версии grafana 7.0.1 и 7.1.5. Пробовал устанавливать плагин вручную и с помощью grafana-cli, но datasource также не появляется.

**Comment by coconutservices** [comment]
I am also having this issue, the data source does not appear, howver the plugin does show as signed. Log shows as unsigned

CentOS Linux release 7.8.2003 
plugin version: 4.0.1
verified manifest file as shown above
grafana   x86_64  7.1.5-1 
fresh install of both grafana, zabbix and the plguin
i did also allow the unsigned plugin

;allow_loading_unsigned_plugins =alexanderzobnin-zabbix-datasource


t=2020-09-03T21:42:46-0500 lvl=info msg="Starting Grafana" logger=server version=7.1.5 commit=9893b8c53d branch=HEAD compiled=2020-08-25T03:27:17-0500
t=2020-09-03T21:42:46-0500 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2020-09-03T21:42:46-0500 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2020-09-03T21:42:46-0500 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2020-09-03T21:42:46-0500 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2020-09-03T21:42:46-0500 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2020-09-03T21:42:46-0500 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2020-09-03T21:42:46-0500 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2020-09-03T21:42:46-0500 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2020-09-03T21:42:46-0500 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2020-09-03T21:42:46-0500 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2020-09-03T21:42:46-0500 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2020-09-03T21:42:46-0500 lvl=info msg="App mode production" logger=settings
t=2020-09-03T21:42:46-0500 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=1597
t=2020-09-03T21:42:46-0500 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-09-03T21:42:46-0500 lvl=info msg="Starting DB migration" logger=migrator
t=2020-09-03T21:42:46-0500 lvl=info msg="Starting plugin search" logger=plugins
t=2020-09-03T21:42:46-0500 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-09-03T21:42:46-0500 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix
t=2020-09-03T21:42:46-0500 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Problems"
t=2020-09-03T21:42:46-0500 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-09-03T21:42:46-0500 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned]"
t=2020-09-03T21:42:46-0500 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=

**Comment by kilterbaf** [comment]
@alexanderzobnin аналогичная проблема. установил Grafana 7.1.5 и плагин Zabbix 4.0.1, источника данных в списке нет. при снижении версии Grafana до 7.0.1, проблема остается. при переустановки плагина на более старую версию (3.12.1) источник данных Zabbix появляется. добавил его,настроил и сохранил, тест прошел успешно. но когда обновил плагин до 4.0.1, то источник данных исчез, графана писала,что плагин не установлен, но в списке плагинов он был.

**Comment by IhanaOlli** [comment]
I have same problem. **Fresh** (read:empty) official grafana/grafana docker container started with 
-e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app"
option.  "Plugins / Zabbix" can be enabled but Zabbix does not appear on Add data source list.

**Comment by Wtcheesecakes** [comment]
I experienced the same issue with a fresh install of grafana, Allowing unsigned plugin fixed the issue for me

**Comment by ruchimal** [comment]
> I experienced the same issue with a fresh install of grafana, Allowing unsigned plugin fixed the issue for me

Can you please let me know the steps to fix the issue. it would really help me to come out of this deadlock and are you running Grafana in windows?.

**Comment by charllesamorim** [comment]
![Captura de Tela 2020-09-07 às 09 30 46](https://user-images.githubusercontent.com/70901368/92393981-1a79ce00-f0f7-11ea-863c-0ff83fa40b64.png)

**Comment by charllesamorim** [comment]
![Captura de Tela 2020-09-07 às 09 31 06](https://user-images.githubusercontent.com/70901368/92394030-2feef800-f0f7-11ea-86b6-7bc758359f45.png)

**Comment by charllesamorim** [comment]
The Zabbix data source does not appear.

**Comment by charllesamorim** [comment]
![Captura de Tela 2020-09-07 às 10 46 47](https://user-images.githubusercontent.com/70901368/92394242-88be9080-f0f7-11ea-8ee6-1629a07b0857.png)

**Comment by charllesamorim** [comment]
How do I solve this problem? Thank you!

**Comment by dchicco-giga** [comment]
Hi I already installed the zabbix plugin and when I go to "Add data source" it does not appear...

I installed with the following command:

[root@grafana-test ~]# grafana-cli plugins install alexanderzobnin-zabbix-app
installing alexanderzobnin-zabbix-app @ 4.0.1
from: https://grafana.com/api/plugins/alexanderzobnin-zabbix-app/versions/4.0.1/download
into: /var/lib/grafana/plugins

✔ Installed alexanderzobnin-zabbix-app successfully 

Restart grafana after installing plugins . <service grafana-server restart>

[root@grafana-test ~]# service grafana-server restart
Restarting grafana-server (via systemctl):                 [  OK  ]
[root@grafana-test ~]# 


On plugin section

![Screen Shot 2020-09-07 at 16 39 35](https://user-images.githubusercontent.com/64762590/92413998-d30c3580-f128-11ea-9fdc-b46f3a36d157.png)


![Screen Shot 2020-09-07 at 16 39 45](https://user-images.githubusercontent.com/64762590/92414015-e0292480-f128-11ea-9746-8dbd834c5159.png)


But when I wanted to add data source nothing appeared...

![Screen Shot 2020-09-07 at 16 41 32](https://user-images.githubusercontent.com/64762590/92414077-0ea6ff80-f129-11ea-90ee-e0c69e29d98a.png)

I need some help


OS: Centos 7

My best regards

**Comment by charllesamorim** [comment]
[root@vml0132 alexanderzobnin-zabbix-app]# pwd
/var/lib/grafana/plugins/alexanderzobnin-zabbix-app
[root@vml0132 alexanderzobnin-zabbix-app]# ll
total 40212
drwxr-xr-x. 2 root root     4096 Set  6 18:49 app_config_ctrl
drwxr-xr-x. 2 root root     4096 Set  6 18:49 css
drwxr-xr-x. 2 root root     4096 Set  6 18:49 dashboards
drwxr-xr-x. 4 root root     4096 Set  6 18:49 datasource-zabbix
drwxr-xr-x. 2 root root     4096 Set  6 18:49 img
-rw-r--r--. 1 root root     3516 Set  6 18:49 MANIFEST.txt
-rw-r--r--. 1 root root     1640 Set  6 18:49 module.js
-rw-r--r--. 1 root root     5588 Set  6 18:49 module.js.map
drwxr-xr-x. 4 root root     4096 Set  6 18:49 panel-triggers
-rw-r--r--. 1 root root     1803 Set  6 18:49 plugin.json
-rw-r--r--. 1 root root     4053 Set  6 18:49 README.md
-rwxr-xr-x. 1 root root 14569232 Set  6 18:49 zabbix-plugin_darwin_amd64
-rwxr-xr-x. 1 root root 13328384 Set  6 18:49 zabbix-plugin_linux_amd64
-rwxr-xr-x. 1 root root 13228544 Set  6 18:49 zabbix-plugin_windows_amd64.exe

**Comment by charllesamorim** [comment]
[root@vml0132 alexanderzobnin-zabbix-app]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

**Comment by charllesamorim** [comment]
![Captura de Tela 2020-09-07 às 17 56 50](https://user-images.githubusercontent.com/70901368/92416402-ae698b00-f133-11ea-88d4-5e63aca6f2b1.png)

**Comment by charllesamorim** [comment]
I performed the installation in the cloud and the Zabbix data source does not appear either.

**Comment by charllesamorim** [comment]
How do I fix it? I believe it is a "bug" in the version.

**Comment by jwuorenmaa** [comment]
I was running into the same issue, `Ubuntu 20.04`, `Zabbix 5.0-1`, `Grafana 7.1.5`, `alexanderzobnin-zabbix-app 4.0.1` .  I noticed in /var/log/grafana/grafana.log a few things, 

```
"Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
"Config loaded from" logger=settings file=/etc/grafana/grafana.ini
"Connecting to DB" logger=sqlstore dbtype=sqlite3"
"Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix"
```

I had changed my /etc/grafana/grafana.ini to use my MySQL Grafana database yet it was using sqlite3.  I also had added  "alexanderzobnin-zabbix-datasource" to "allow_loading_unsigned_plugins" in /etc/grafana/grafana.ini .  The Zabbix data source was still not loading.  

So I added my MySQL database settings and "alexanderzobnin-zabbix-datasource" to "allow_loading_unsigned_plugins" to /usr/share/grafana/conf/defaults.ini .  I then reinstalled the plugin using "`sudo grafana-cli plugins install alexanderzobnin-zabbix-app`" .  I checked the log after restarting now Grafana log shows

```
"Connecting to DB" logger=sqlstore dbtype=mysql"
 "Running an unsigned backend plugin" logger=plugins pluginID=alexanderzobnin-zabbix-datasource pluginDir=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix"
```

So Grafana looks like it is ignoring the config file "/etc/grafana/grafana.ini" and only using "/usr/share/grafana/conf/defaults.ini" The permissions on "/etc/grafana/grafana.ini" are 640 and 644 on  "/usr/share/grafana/conf/defaults.ini" . So maybe that is the issue.

**Comment by charllesamorim** [comment]
After removing the ";" now the Zabbix data source appears. And include the line in grafana.ini:

allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource

**Comment by charllesamorim** [comment]
![Captura de Tela 2020-09-08 às 08 18 15](https://user-images.githubusercontent.com/70901368/92470333-a3067600-f1ac-11ea-80b8-8e3da584aa6a.png)

**Comment by charllesamorim** [comment]
Thank you very much, jwuorenmaa!

**Comment by andrekully** [comment]
With this config it works also for me. But setting this as allowed for unsigned loading is just a workaround I think. Why is the plugin signed, but the datasource seems to be not:
![Add_data_source_-_Grafana](https://user-images.githubusercontent.com/17795179/92480605-6c008680-f1e5-11ea-9150-00298089eb48.png)

**Comment by charllesamorim** [comment]
How do I fix this problem in Grafana Cloud?

**Comment by jwuorenmaa** [comment]
charllesamorim, I'm not sure it can be fixed with the free version of [Grafana Cloud](https://grafana.com/docs/grafana-cloud/grafana/).  From that page,
```
"Customizations
Customizing Grafana is available for customers of Grafana Cloud paid plans (pricing information)

To customize any aspect of your Grafana instance, send a support request to support@grafana.com from the email address associated with your Grafana Cloud Account"
```

I created a free instance and couldn't see any way to make the change needed.

It looks like the plugin author(alexanderzobnin) is working on getting the datasource signed, https://github.com/alexanderzobnin/grafana-zabbix/issues/1035.

**Comment by jonathanlo55** [comment]
After I upgraded the plugin to the last version (4.0.1), my Zabbix datasource started to present the error "Plugin not found, no installed plugin with that id".
![image](https://user-images.githubusercontent.com/33928260/92731222-307fcc80-f34b-11ea-933a-2a8de7b5e968.png)

I was able to delete it via API, but then it does'nt reappear to add again.
I could'nt apply the workaround presented by @jwuorenmaa cause we are use using Grafana as a container, and I was'nt able to edit the /etc/grafana/grafana.ini file as our container is running under the "grafana" user, and the file is authorized to root only. To edit it I would have to rebuild the container and I just did'nt have the time yet.
Waiting the new version with the signed Datasource as mentioned in the issue [https://github.com/alexanderzobnin/grafana-zabbix/issues/1035](url)

**Comment by alexanderzobnin** [comment]
This issue duplicates #1042. You can find there that it's a Grafana bug and we're working on fix. Possible solutions: use 3.12 version or allow loading unsigned plugins. For those who have troubles with Windows version of the plugin (`can'f find executable` issue), please, open new issue for this case.
