### ISSUE TITLE
Debian 10  Zabbix 5.0 grafana issue

### ISSUE THREAD

**Issue by lopezvanessa1978** [alexanderzobnin/grafana-zabbix#1044]
Hello Everybody,

I need your help ,i installed grafana on my debian, all is working well, when I install plugin zabbix it's ok but the issue is when I configure data source, I don't find any data source for Zabbix, and when I click on "find more data sources on grafana.com " I don't find any datasource for Zabbix.

Environement:
Debian 10
Zabbix 5.0
Grafana 4.0.1

some screenshot 
![image](https://user-images.githubusercontent.com/70149942/92097230-1fc5d880-edd8-11ea-9190-2868b803470d.png)

![image](https://user-images.githubusercontent.com/70149942/92097336-408e2e00-edd8-11ea-8e72-1c5fb95ee245.png)

**Comment by jedd** [comment]
Hi,

What's your grafana.log report when looking for errors?

 There's a known change involving the [plugins] section and allowing
unsigned plugins - that can manifest similar to what you're seeing.

**Comment by lopezvanessa1978** [comment]
Hello, first thanks for your answer 👍 
about grafana logs:

t=2020-09-03T12:53:52+0200 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=9048
t=2020-09-03T12:53:52+0200 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-09-03T12:53:52+0200 lvl=info msg="Starting DB migration" logger=migrator
t=2020-09-03T12:53:52+0200 lvl=info msg="Starting plugin search" logger=plugins
t=2020-09-03T12:53:52+0200 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
**t=2020-09-03T12:53:52+0200 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix**
t=2020-09-03T12:53:52+0200 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Problems"
t=2020-09-03T12:53:52+0200 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2020-09-03T12:53:52+0200 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"alexanderzobnin-zabbix-datasource\" is unsigned]"
t=2020-09-03T12:53:53+0200 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-09-03T12:54:06+0200 lvl=info msg="Plugin state changed" logger=plugins pluginId=alexanderzobnin-zabbix-app enabled=true
t=2020-09-03T12:54:06+0200 lvl=info msg="Syncing plugin dashboards to DB" logger=plugins pluginId=alexanderzobnin-zabbix-app

In fact, the error seems to come from the signature.

I must put True in front this option on /etc/granafa/grafana.ini file and restart grafana-server ?

![image](https://user-images.githubusercontent.com/70149942/92107239-c2388880-ede5-11ea-9db4-73905a44d473.png)

Thanks for your help
Vanessa

**Comment by lopezvanessa1978** [comment]
Thanks it's reloved I changed the configuration file with that 

![image](https://user-images.githubusercontent.com/70149942/92107780-9e297700-ede6-11ea-8d88-010b1975cbea.png)
Irestarted grafana server and all it's working well 

Thank you very much
