### ISSUE TITLE
Client.Timeout error when querying metrics

### ISSUE THREAD

**Issue by mfarhan28** [alexanderzobnin/grafana-zabbix#1046]
Hi @alexanderzobnin 

**Describe the bug**
An error Post "https://x.x.x.x/api/api_jsonrpc.php": net/http: request canceled (Client.Timeout exceeded while awaiting headers) has been thrown after input metrics query parameter for table type of visualisation panel.

**Expected behavior**
Metrics data preview should appear in the table.

**Screenshots**
<img width="1440" alt="Screenshot 2020-09-04 at 4 22 54 AM" src="https://user-images.githubusercontent.com/41605647/92163504-6530e700-ee66-11ea-9e7c-ffd55616e927.png">

**Network data**
Post "https://x.x.x.x/api/api_jsonrpc.php": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Object
status:500
statusText:"Internal Server Error"
data:Object
error:"Internal Server Error"
message:"Post "https://x.x.x.x/api/api_jsonrpc.php": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
message:"Post "https://x.x.x.x/api/api_jsonrpc.php": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.5   | 4.4.0  | 4.0.1                 |

**Comment by alexanderzobnin** [comment]
Hi! Could you enable debug logging and show logs from the Grafana server?

**Comment by h1tman23** [comment]
Same problem here, if request exeeds 30s I get this error too. How to increase timeout limit?
Debug does not show more info:
lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="Post \"https://x.x.x.x/api_jsonrpc.php\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

**Comment by alexanderzobnin** [comment]
It's not configurable now, but I can add this to the data source config.

**Comment by dilshan5** [comment]
Hi ,

I'm still experience this time out issue in Grafana when I query influxDB.

I'm using Grafana V 7.4.1. Dis the latest version include this fix?

Note : I changed the default timeout (30s) to 300 seconds in /etc/grafana/grafana.ini as well

Thanks,
Dilshan
