### ISSUE TITLE
Zabbix plugin can no longer show problems in 4.0.1

### ISSUE THREAD

**Issue by rburkhall** [alexanderzobnin/grafana-zabbix#1049]
**Describe the bug**
Query mode: Problems
Show: History ==> Works
Show: Problems ==> {
Invalid params. Incorrect API "problem".
Object
status:500
statusText:"Internal Server Error"
data:Object
error:"Internal Server Error"
message:"Invalid params. Incorrect API "problem"."
message:"Invalid params. Incorrect API "problem"."
}

**Expected behavior**
Should show problems

**Screenshots**
![image](https://user-images.githubusercontent.com/42774130/92292666-6ad11000-eeec-11ea-85eb-1283e397ed55.png)

**Network data**
N/A

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|   7.1.5    | 3.0.28 |            4.0.1                 |

**Comment by jedd** [comment]
The official position will be that Zabbix 3.x is NOT supported with the
Grafana-Zabbix plugin 4.x

 We internally forked 4.0.0 to fix this problem - something to do with
severity & priority being handled differently - it involved fixing up a
half dozen front-end files within the plugin, which fixed up Grafana 7.1.3
talking to Zabbix 3.4.5 - and showing us Zabbix Problems panels again.

 We're a few weeks away from upgrading the last of our Zabbix 3 servers to
Zabbix 5 - so a dodgy short-term fix was satisfactory here, for us.



>

**Comment by alexanderzobnin** [comment]
Yes, it's really hard to maintain 3 different Zabbix versions. So since 3.x is not supported by Zabbix, I decided to drop 3.x support in order to focus on plugin improvements possible with latest Zabbix versions.
