### ISSUE TITLE
Gauge support

### ISSUE THREAD

**Issue by saeedek** [alexanderzobnin/grafana-zabbix#105]
Hi,
I want to know if is there a possibility to add a Gauge or speedometer to grafana and zabbix?
Thanks

**Comment by jmaitrehenry** [comment]
Hi,

You have some works on Grafana for that: https://github.com/grafana/grafana/issues/129 <https://github.com/grafana/grafana/issues/129>

Thanks,

**Comment by net592** [comment]
+1

**Comment by alexanderzobnin** [comment]
Folks, this feature was implemented in Grafana (SingleStat panel).
