### ISSUE TITLE
Dashboard variables not working in Annotations

### ISSUE THREAD

**Issue by bpmb82** [alexanderzobnin/grafana-zabbix#1050]
**Describe the bug**
Dashboard variables not working in Annotations

**Expected behavior**
Annotations to show for the currently selected $host

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
Grafana: 7.1.5
Grafana-zabbix: 4.0.1
Zabbix: 5.0.3           

I tried the following in the host field:

```
$host
/$host.*/
/.*$host.*/
/*$host*/
```

But it doesn't work.. Could be me (hopefully it IS me)..?

I can select hosts fine at the top of the dashboard and it also works fine on visualizations.

**Comment by alexanderzobnin** [comment]
Hi! You probably need to specify groups in the query as well (try `/.*/`). Look at this example of using variables in annotations:
https://play.grafana-zabbix.org/d/000000008/annotations?orgId=2

**Comment by bpmb82** [comment]
Hi Alexander,

I tried again and for some reason it now works! I used $group and $host like before but now it works.. A bit stumped but happy enough ;)
