### ISSUE TITLE
Zabbix Plugin Failed

### ISSUE THREAD

**Issue by Daxter1928** [alexanderzobnin/grafana-zabbix#1051]
Hello Everyone, 

I'm kinda new to Grafana, I've started exploring the product mainly due to its Zabbix Plugin that it seems to be just what I need.

I've managed to install Grafana following the official documentation, launched the server and moved the first steps.

When it comes to install the Zabbix Plugin, I've managed to do that via grafana-cli as stated in the official guide ( https://alexanderzobnin.github.io/grafana-zabbix/installation/ ).

I've enabled the plugin and tried to create a Data Source, and there I found my first problem.

There is an error message upon creation that basically prevents me to configure the Data source, the error is the following:

Error: Object prototype may only be an Object or null: undefined Evaluating http://<grafanaipaddress>/public/plugins/alexanderzobnin-zabbix-datasource/module.js Loading plugins/alexanderzobnin-zabbix-datasource/module

I've searched a bit on google and this github but I didn't find anything related to this issue, can someone help me?

**Comment by Dofamin** [comment]
Same here.

**Comment by Dofamin** [comment]
@Daxter1928 Update grafana min ver. 7.0.0

**Comment by catmater** [comment]
Having the same sh...t.
grafana ver 7.1.5
revert to 3.11 - work as usual

**Comment by jadbaz** [comment]
Same here
I managed to work with the latest version by:
- Installing plugin version 3 (3.12.4)
- Adding Zabbix datasource
- Installing plugin latest version

**Comment by Daxter1928** [comment]
> Same here
> I managed get the latest version to work by:
> 
> * Installing plugin version 3 (3.12.4)
> * Adding Zabbix datasource
> * Installing plugin latest version

Hello, 

I tried to do that, everything works fine until the 3.12.4 version is left alone, I installed it via rpm and not via grafana-cli command.

If I try to install the latest version, the datasource and dashboards disappear. 
I noticed that the latest version is called "alexanderzobnin-zabbix-app" while the 3.12 is called "grafana-zabbix-app" so I can't basically update the app since it has a different app id.

**Comment by dry4ng** [comment]
Same issue here. Plugin used to work before. I tried deleting and adding it again. When I add datasource, I can only configure name. It doesn't show any other options. And an error is thrown:
```
zabbix plugin failed
Error: Fetch error: 404 Not Found Instantiating https://example.com/grafana/public/emotion Loading https://example.com/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module
```

**Comment by alexanderzobnin** [comment]
You should allow loading unsigned plugins.

**Comment by jadbaz** [comment]
@alexanderzobnin this happened with me with this option set
docker-compose: `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource`
