### ISSUE TITLE
Max/Min Calculation Issues

### ISSUE THREAD

**Issue by jamesetune** [alexanderzobnin/grafana-zabbix#1052]
**Describe the bug**
When adjusting the time range in Grafana with zabbix datasource the MAX/Min values change - possibly due to less datapoints as the time range expands.  For instance - with a 3 hour window set I have a MAX value for CPU at 100% - expanding that out to 2, 7 and 30 days can cause the MAX value to decrease.   The behaviour in Zabbix is as expected.

**Expected behavior**
MAX/MIN values should be consistent regardless of time range selected.  

**Screenshots**
![image](https://user-images.githubusercontent.com/70948615/92465783-fa194480-f1c6-11ea-88b3-ec28bc80ce79.png)
![image](https://user-images.githubusercontent.com/70948615/92465792-fd143500-f1c6-11ea-958a-f7bd9b2262a1.png)
![image](https://user-images.githubusercontent.com/70948615/92465807-01405280-f1c7-11ea-96fb-f8b1d98da1c1.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|7.1.5  | 3.4  |4.0.1              |

**Comment by jedd** [comment]
Hi,

Have you experimented with the function:

 trendValue(Max)

 It's not easy to tell above, as you've only supplied pictures of graphs,
not your configuration.

**Comment by jamesetune** [comment]
Thanks - no - I hadnt.  I will try that.

I have tried to work around it in several ways.  My configuration is taking the zabbix item and then ticking the MAX/MIN check boxes as below.

![image](https://user-images.githubusercontent.com/70948615/92580991-0369e600-f287-11ea-862e-068769581a2c.png)

I have also found the following settings which allow the increase of data points - which works up to a point but as you increase the date range the MAX/MIN values start drifting away from the MAX/MIN values zabbix reports.
![image](https://user-images.githubusercontent.com/70948615/92581124-27c5c280-f287-11ea-8c26-f26881d5e39f.png)

**Comment by jedd** [comment]
Fair enough -- this has bitten us in the past, in much the same way as it got you.

My email reply earlier didn't include images, and email responses can't be markdown'd retrospectively either.  

Check the images I've added to my last comment on github proper, if you didn't see them already.

**Comment by jamesetune** [comment]
Thanks Jedd - appreciate the responses.  I will try the trendvalue function.

**Comment by alexanderzobnin** [comment]
Hi! As it's mentioned above - you can use both `trendValue(max)` and `groupBy($__interval, max)` to always get maximum value even if the series was downsampled.

**Comment by lombardialess** [comment]
The trendvalue function works but on long time filter there is a problem in the avg calculation.

last 7 days filter on grafana with trendvalue(max):
![image](https://user-images.githubusercontent.com/16349053/93087000-3d2c5980-f698-11ea-87a7-2d295df24bb0.png)

same graph on zabbix:
![image](https://user-images.githubusercontent.com/16349053/93087072-5a612800-f698-11ea-9832-39b5d8ef25aa.png)

This can be a problem when analyzing long time series data.

**Comment by lombardialess** [comment]
any comment on my post?
I don't think that this issue is closed with those results.
first image 18% avg on Grafana, second image 2% avg on Zabbix.

**Comment by jedd** [comment]
Hi  -- can you share both Grafana and Zabbix graphs again, but without the legend cut off -- and also a screen grab of the graph configuration for the Grafana graph?

**Comment by lombardialess** [comment]
Hi Jedd,
thank you for your comment.

Grafana 7 days: (20% avg)
![image](https://user-images.githubusercontent.com/16349053/93315331-3540f680-f80b-11ea-9919-7f1d180d9999.png)


Zabbix 7 days: (2% avg)
![image](https://user-images.githubusercontent.com/16349053/93315507-6a4d4900-f80b-11ea-8d7f-b795ef8be2f7.png)

Also changing the Max data points on grafana the result is the same.

**Comment by jedd** [comment]
Ah, I was going to ask about max data points - I'd stumbled across that a while ago as a cure for a slightly different pain.  : )

Okay, I don't use Zabbix graphs, but I'm looking at the red line in your Zabbix graph, and it looks like it only once or twice dips beneath 10%, never reaches zero, and consequently the (Grafana reported) average for that maxvalue of 20% *feels* much closer to what that Zabbix *graph* is showing.  The Zabbix *legend* just reads wrong in that context.

Was that your judgement too, or did you think the Grafana graph was wrong?

I'd almost be tempted to dive into the DB directly and do some extractions there, at least on a smaller sample set of trend data.

Btw, are you using the DB connection, or just the API, from Grafana into Zabbix?  (Not that we've noticed any difference in results between those.)

**Comment by lombardialess** [comment]
we use the API with the Grafana-Zabbix plugin.
I think that the graphs view is the same between Grafana and Zabbix (also the zabbix graph is configure to show "max" values in the view), the issue is on the values in the table.
When I put Grafana with trendvaluemax setting the graph view is aligned with the Zabbix one but grafana calculate the avg value based on the trend of the max value that the graph view shows and show this "high" avg value in the table, it doesn't show  the real average value that zabbix collects and calculate with the item history.
Zabbix instead show the graph correctly and also the avg value in the table is the real one.
I hope that my explanation was clear, if needed I can post more graph

**Comment by i-ky** [comment]
[Grafana's documentation](https://grafana.com/docs/grafana/latest/panels/visualizations/graph-panel/#values) says:
> **Avg** - Average of all values returned from the metric query.

I'm not sure if datasource plugin can somehow override this by sneaking "the real average value" from a different source.

**Comment by jedd** [comment]
![image](https://user-images.githubusercontent.com/114736/93323230-b1612b80-f857-11ea-9eb8-0284602db59d.png)

Ah, so you want to have the graph (on Zabbix) set to show max - but the legend show averages of *actual* values?

This might be a problem with Zabbix then.  

I've attached a Grafana graph of CPU usage - both from the same host, over 7d, which in my config forces trend data.  It shows what looks to me to be accurate min, max, avg in the legend for the two interpretations of those source data.

If you want a Grafana legend to show you figures that reflect actual (avg), rather than trendMax, say, well I'm not sure how you'd go about that.

**Comment by lombardialess** [comment]
No, wait. I try to explain it better.
On zabbix you can configure the items in the graph to show the lines with the min, max or avg values:

![image](https://user-images.githubusercontent.com/16349053/93328611-3d556200-f81c-11ea-8cdd-698e6d2f3c5e.png)

And in the table below of the graph the values shown are calculated from the history of the collection of the item, so for the average the value shown is the average of all the samples in the time window selected in the graph.

In grafana the average value that is show is the average of the data points of the graph, so if I put the trendvalueMax function, the average value in the table is an average of the Max values shown by the graph. Not the real average based on the zabbix item's history.

**Comment by dMailonG** [comment]
Old thread, but still an ongoing "issue".

Solution:
Disable trends in the query options.

This will obviously impact performance.
