### ISSUE TITLE
Problem to add datasource

### ISSUE THREAD

**Issue by dkcristian** [alexanderzobnin/grafana-zabbix#1053]
I using ubuntu 18.04 on aws and I tested with grafana 7.0 and 7.1.

(restart application was done)

The problem is that a I install and i can activate plugin, but I cant see in datasource.

**Comment by frugnoli** [comment]
I have the same problem. Debian 10!

**Comment by kentnetter** [comment]
Metoo. CentOS 7

**Comment by Viox-LJ** [comment]
Ubuntu 18.04 and have the same problem!! i dont see the Datasoruce after install the plugin...

Have:
Zabbix 5
Grafana 7.1.5
Zabbix in Grafana Plugin 4.01

**Comment by marvinamorim** [comment]
Same problem.
Debian 10
Zabbix 4.4.0
Grafana 7.1.5
grafana-zabbix Plugin 4.0.1
Grafana is running on a docker container.

**Comment by jeanccaires** [comment]
Me too centos 7

**Comment by Viox-LJ** [comment]
I solve that using a old version...

grafana-cli plugins remove alexanderzobnin-zabbix-app
grafana-cli plugins install alexanderzobnin-zabbix-app 3.12.4

**Comment by eirisdg** [comment]
Same problem.
Centos 7
Zabbixi 5.0.3
Grafana 7.1.5
Grafana zabbix plugin 4.0.1

For more info, Zabbix DS was default. When I change the default to another DS, and remove the plugin, the Zabbix Datasource is still there.

**Comment by alexanderzobnin** [comment]
You should allow loading unsigned plugins.
