### ISSUE TITLE
Plugin unavailable grafana 7.0 zabbix 4.0.1

### ISSUE THREAD

**Issue by coolgooseman** [alexanderzobnin/grafana-zabbix#1054]
**Describe the bug**
Whenever i save a datasource using the plugin (version 4.0.1) on grafana 7.0 it gives a "plugin unavailable" error message.

**Expected behavior**
I expected the data source to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/71011796/93099906-d9f6f300-f6a8-11ea-9e6f-c93e94cecf04.png)

![image](https://user-images.githubusercontent.com/71011796/93099843-c9467d00-f6a8-11ea-8cc8-5d6a05c1dd2c.png)

Setting the source to 'Default' didn't help.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|7.0   | x.x.x  | 4.0.1                 |

**Comment by OMSKremer** [comment]
same here

**Comment by elizandropacheco** [comment]
Same

**Comment by alexanderzobnin** [comment]
Hi! Could you post grafana-server logs (it's interesting what happens after pressing save and test button)?

**Comment by ddurieux** [comment]
With Grafana 7.2:

`t=2020-10-09T11:38:34+0000 lvl=eror msg="Plugin unavailable" logger=context userId=1 orgId=9 uname=admin error="Plugin unavailable"`

`t=2020-10-09T11:38:34+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=9 uname=admin method=POST path=/api/datasources/19/resources/zabbix-api status=503 remote_addr=10.0.1.254 time_ms=9 size=32 referer=https://support.dcsit-group.com/grafana/datasources/edit/19/`

`t=2020-10-09T11:38:34+0000 lvl=eror msg="Plugin unavailable" logger=context userId=1 orgId=9 uname=admin error="Plugin unavailable"`

`t=2020-10-09T11:38:34+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=9 uname=admin method=POST path=/api/datasources/19/resources/zabbix-api status=503 remote_addr=10.0.1.254 time_ms=1 size=32 referer=https://support.dcsit-group.com/grafana/datasources/edit/19/`

**Comment by ddurieux** [comment]
I found the problem, it's because my Grafana running under FreeBSD-amd64 and excecutable (backend part of the plugin not exist).
So build with this doc https://github.com/alexanderzobnin/grafana-zabbix/issues/1022#issuecomment-682366412, after put the file `zabbix-plugin_freebsd_amd64` generated into folder `/var/db/grafana/plugins/alexanderzobnin-zabbix-app/` and restart grafana ;)

**Comment by alexanderzobnin** [comment]
Ok, now I need to ask about OS version also to make sure it's supported.

**Comment by coolgooseman** [comment]
Hi, it was on windows 10. Sorry i've decided to give up on this project for the time being so i wont be posting further updates on this.

**Comment by shoro** [comment]
Any solutions? Still getting "Plugin unavailable"

**Comment by alexanderzobnin** [comment]
@shoro what's an OS do you use? Could you provide grafana-server logs?

**Comment by shoro** [comment]
> @shoro what's an OS do you use? Could you provide grafana-server logs?

Hy, I'm using RaspbianOS. Sorry but cannot provide log at this time.

**Comment by jmschaap** [comment]
> @shoro what's an OS do you use? Could you provide grafana-server logs?

Same issue. Grafana 7.3.5, Zabbix 4.2, plugin 4.0.2

Serverlogs:
```
t=2020-12-16T12:18:19+0000 lvl=eror msg="Plugin unavailable" logger=context userId=1 orgId=1 uname=admin error="Plugin unavailable"
t=2020-12-16T12:18:19+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/2/resources/zabbix-api status=503 remote_addr=10.0.10.67 time_ms=152 size=32 referer=http://10.0.10.3:3000/datasources/edit/2/
t=2020-12-16T12:18:19+0000 lvl=eror msg="Plugin unavailable" logger=context userId=1 orgId=1 uname=admin error="Plugin unavailable"
t=2020-12-16T12:18:19+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/2/resources/zabbix-api status=503 remote_addr=10.0.10.67 time_ms=147 size=32 referer=http://10.0.10.3:3000/datasources/edit/2/
```

**Comment by AviPairupuni** [comment]
I'm running redhat7.6 and grafana upgraded to 7.3.7 and I have exact same log errors as @jmschaap. plugin version 4.1.1

**Comment by jmschaap** [comment]
> I'm running redhat7.6 and grafana upgraded to 7.3.7 and I have exact same log errors as @jmschaap. plugin version 4.1.1. Zabbix 5.0.2

Downgrade the plugin to 3.12.4 if you need it. That does work. Would be nice though to be able to use the latest version. @alexanderzobnin

**Comment by AviPairupuni** [comment]
I'm running on 3.10.4 and explorer is not working. does it work on the version you mentioned? 
@alexanderzobnin, will there be any fix any soon?

**Comment by jmschaap** [comment]
What do you mean by explorer?

**Comment by alexanderzobnin** [comment]
@AviPairupuni what's an OS you're running grafana server on?

**Comment by hermithuang** [comment]
@alexanderzobnin hi, I use docker grafana and I can see plugins list have zabbix,  but I cant find it in data source menu. I use the grafana docker version is from https://hub.docker.com/r/grafana/grafana-arm64v8-linux . it a armv8 version.  Is it not supported under this arch ?  Thank YOU .

**Comment by amirhseta** [comment]
i have same promblem on centos 8
CentOS Linux release 8.2.2004 (Core)
@alexanderzobnin

**Comment by amirhseta** [comment]
@alexanderzobnin 
my zabbix version is:
 zabbix_server (Zabbix) 5.0.5

my grafana version is:
Grafana CLI version 8.2.5

**Comment by nmcc1212** [comment]
using ubuntu, getting the same thing

**Comment by nmcc1212** [comment]
anyone know how to fix?
