### ISSUE TITLE
TableTrends

### ISSUE THREAD

**Issue by Tepew** [alexanderzobnin/grafana-zabbix#1055]
**Describe the bug**
For table if set data f.e. 30 days. Data takes as trends but in configuration data set 90d

![image](https://user-images.githubusercontent.com/42611903/93191773-9609f980-f74d-11ea-9ac2-ba21cc2cb763.png)

![image](https://user-images.githubusercontent.com/42611903/93191090-cd2bdb00-f74c-11ea-851c-703c2ae25750.png)

if set 1 day - data looks normal
![image](https://user-images.githubusercontent.com/42611903/93191270-ff3d3d00-f74c-11ea-8c53-80055853f597.png)

this is old table (from 6.X) grafana. In Data take text and numeric.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.3   | 4.0.22  | 3.12.2                 |

**Comment by alexanderzobnin** [comment]
That how it works. If range is wider than 4 days, then trends is using. After (90d) means trends will be using if any of `from` or `to` range bounds is less than `now-90d`.
