### ISSUE TITLE
Regarding the closed issue 989

### ISSUE THREAD

**Issue by ygk12345** [alexanderzobnin/grafana-zabbix#1056]
**Describe the bug**
When we execute that sum() function for all nodes, it shows correct total for the first time. Then for example if we have three computes with vms (1, 5, 7 ) on them, then the total shows as 13 for sometime correctly and then it tries to loop thru the values from the beginning like  ( 1, 1+5, 1+5+7), that is, it shows , 1,6,and 13. it keeps on looping thru 1,6,13 forever. It doesn't show the total value consistently.

**Expected behavior**
The sum() function should show the 'total' consistently all the time. The workaround you suggested in the issue #989 is not working. It still keeps on looping cumulatively  through the values. We are using Grafana for Zabbix  to show reports to our higher management. Please don't ignore this bug. It will improve your product's usability in the future. If required we can connect through zoom or skype for demonstrating this problem live.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7 | 5 |   	3.12.2      |

**Comment by alexanderzobnin** [comment]
Ok, that's probably the same issue as described in #887, so closing this one.
