### ISSUE TITLE
Problem with Zabbix Plugin 4.0.1

### ISSUE THREAD

**Issue by JuriBRT** [alexanderzobnin/grafana-zabbix#1057]
**Describe the bug**
After upgrading to plugin version 4.0.1, the datasource in unavailable/missing (pretty same to #1054)

**Expected behavior**
create o recreate zabbix datasource connection

I've first upgraded the zabbix plugin to version 4.0.1. Since then it start to say plugin unavailable/missing in the datasource page.
So i've uninstalled and reinstalled grafana, as it was a pretty new setup.
I've then installed the plugin 4.0.1, enabled it and rebooted.
Now i cannot see zabbix available in the datasouce type page, so i cannot add it again.
Maybe somewhere it's stored  that the zabbix datasource is already in place, but i cannot see where.

Thanks and best regards
Juri Bertello

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.1.5   | 5.0.3 | 4.0.1                 |

**Comment by coolgooseman** [comment]
Try instaling Zabbix 3.12.4 for the time being, i've heard people fixing it with temporarily downgrading.

Another fix i've seen going around on here is allowing unsigned plugins. I'm not sure how to allow them however.

**Comment by JuriBRT** [comment]
many thanks, i've installed version 3.12.4 and now everything is working as expected!
cheers

**Comment by karl-j** [comment]
I solved this by enabling unsigned plugins:

1. Open `/etc/grafana/grafana.ini`
2. Go to the `[plugins]` section
3. Add `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`

Example:
`[plugins]
;enable_alpha = false
;app_tls_skip_verify_insecure = false
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`

**Comment by karl-j** [comment]
I solved this by enabling the plugin as an unsigned:

1. Open `/etc/grafana/grafana.ini`
2. Go to the `[plugins]` section
3. Add `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`

Example:
```
[plugins]  
;enable_alpha = false
;app_tls_skip_verify_insecure = false
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
````

**Comment by JuriBRT** [comment]
Hello,
i can confirm that adding "allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource" do the job and the plugin start working
wery nice!
thanks

**Comment by Mattz0r** [comment]
Getting this same error - Even with the "allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource" line added to the grafana.ini

(The datasource wasn't even available until I added that line)

**Comment by Kr1shna** [comment]
Last post confirmed,
Plugin version 4.0.1, added "allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource" to config, zabbix datasource is visible, but there is a red "Plugin unavailable" sign when I try to "Save and Test" this datasource

**Comment by mrodrigomana** [comment]
> Last post confirmed,
> Plugin version 4.0.1, added "allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource" to config, zabbix datasource is visible, but there is a red "Plugin unavailable" sign when I try to "Save and Test" this datasource

I need to do:
chmod 777 /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64
And restar grafana server

**Comment by coolgooseman** [comment]
i have the same issue, no luck so far on fixing it.

**Comment by stBlackD** [comment]
> Last post confirmed,
> Plugin version 4.0.1, added "allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource" to config, zabbix datasource is visible, but there is a red "Plugin unavailable" sign when I try to "Save and Test" this datasource

aving the same problem in windows:
```
Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="exec: \"zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%
```

**Comment by Mattz0r** [comment]
I've not changed anything really, but it's started working all of a sudden :S

**Comment by voepix** [comment]
Hi,

I'm installing zabbix an grafana on same server. I have a similar problem, grafana is OK installation of zabbix plugins but when i activate the plugins no config item is appearing..Juste 'disable' an 'update'. I have  added the "allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource line and restart grafana but nothing. Grafana 7.2.0 and zabbix plugins 4.0.1.

**Comment by Mattz0r** [comment]
Not sure why this is closed, as the issue is still present?

**Comment by alexanderzobnin** [comment]
@Mattz0r That's quite messy - original issue creator reported that it's fixed:
>i can confirm that adding "allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource" do the job and the plugin start working

I also see some other issues related to windows build here, but there's a separate issue for this bug #1033

So no new information here, that's why I closed this issue.
