### ISSUE TITLE
Not able to find zabbix data source in grafana After enabling plugin

### ISSUE THREAD

**Issue by kaustubhghode** [alexanderzobnin/grafana-zabbix#1058]
Hi @alexanderzobnin 

i have install zabbix plugin for grafana ,it was successfully install and was present in plugin section ,after enabling it,it doesn't come  under datasource  section.

can you please look into it.

https://community.grafana.com/t/grafana-6-6-doesnt-show-zabbix-plugin/27160/4
facing same issue as above.

**Comment by tritueviet** [comment]
same as isssue

**Comment by FeuerTeufel1995** [comment]
same issues

Version Grafana: 7.1.5
Version Zabbix-Plugin: 4.0.1

**Comment by d2inco** [comment]
same issue.  
Grafana 7.1.5, Zabbix-Plugin 4.0.1.   Clean Grafana setup, from scratch, first plugin :(

**Comment by mira-tech** [comment]
According to the [release notes](https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v4.0.0), it is necessary to write below from 4.0.0.

1. Open in editor `/etc/grafana/grafana.ini` 
2. Rewrite `;Add allow_loading_unsigned_plugins = ` in the [plugins] section to `Add allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource`

(by google translate)

**Comment by d2inco** [comment]
No, 4.0.1 is signed: https://github.com/grafana/grafana-plugin-repository/pull/722

**Comment by mira-tech** [comment]
I was suffering from the same problem but now it's working...(Zabbix 5.0/grafana-zabbix 4.0.1)
(I first learned that it was signed in 4.0.1. Sign problem?)

<img width="923" alt="スクリーンショット 2020-09-20 10 22 57" src="https://user-images.githubusercontent.com/30523995/93692226-5bc4a180-fb2b-11ea-8e4c-56c3038b70ba.png">

**Comment by mira-tech** [comment]
https://github.com/alexanderzobnin/grafana-zabbix/issues/1057#issuecomment-694415693
I learned from this person's comment that it was written in the release notes

**Comment by mira-tech** [comment]
I myself tried the solution I mentioned, but it didn't work ...
(It can be installed, but it was useless because "Plugin unavailable" appeared in the settings)

I'm sorry 🙇🏻

**Comment by 2s5** [comment]
same issues

Version Grafana: 7.1.5
Version Zabbix-Plugin: 4.0.1

**Comment by 2s5** [comment]
> same issues
> 
> Version Grafana: 7.1.5
> Version Zabbix-Plugin: 4.0.1

解决了。。
Open /etc/grafana/grafana.ini
Go to the [plugins] section
Add allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource

**Comment by JuriBRT** [comment]
Hello,
i can confirm that adding "allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource" do the job and the plugin start working
wery nice!
thanks

**Comment by coolgooseman** [comment]
Try instaling Zabbix 3.12.4 for the time being, i've heard people fixing it with downgrading.

**Comment by jonasbar** [comment]
> Hello,
> i can confirm that adding "allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource" do the job and the plugin start working
> wery nice!
> thanks

Yes, it work.

**Comment by jorlandobr** [comment]
Using zabbix plugin 4.01. It appears as **signed** on grafana's plugin panel, but **/etc/grafana/grafana.ini** needs editing.

...
[plugins]
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource

**Comment by d2inco** [comment]
a better guess might be that maybe the overall "plugin" which is
"alexanderzobnin-zabbix-app" plugin is signed, and given that the grafana.ini line that we've added, from earlier in the thread is:

--->  allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource

that indicates another package within the other package, and that it looks like "alexanderzobnin-zabbix-datasource" is not signed as it should be.

Adding the line is a workaround, but it is not, overall a clean solution...

**Comment by jorlandobr** [comment]
@d2inco you seem to be right. Looking at the logs:

Sep 23 18:51:20 urso-zabbix grafana-server[16629]: t=2020-09-23T18:51:20-0300 lvl=eror msg=**"Failed to load plugin"** logg
er=plugins error=**"plugin \"alexanderzobnin-zabbix-datasource\"** is unsigned" **pluginPath=/var/lib/grafana/plugins/alexand
erzobnin-zabbix-app/datasource-zabbix**

**Comment by Andrey-cisco** [comment]
The same issue 
Plugin 4.0.1
Grafana 7.0.3

Zabbix plugin was installed successful and enabled, but there is no data source with zabbix. After I've add  
```
[plugins]
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
```
Nothing changes - it doesn't work anyway

**Comment by voepix** [comment]
Hi,

Plugin 4.0.1
Grafana 7.2.0

I made the change indicated namely commenting the line and adding the plug-in then restarting the service. But no change.

I just commented the line then restart grafana and now I have access to the configuration panel, the only problem is that it is impossible to validate the configuration when the accesses are good.

**Comment by milprog** [comment]
Hi all,

similar problem on grafana 7.2.0 and plugin 4.0.1 with zabbix 4.0.4 here running on a raspberry pi 4. After inserting the plugin stanza in grafana.ini, the config panel opens, but when I press "save and test" I get "Datasource updated" first, then three times "Plugin unavailable".

**Comment by bertalanimre** [comment]
Well, it did work for me.... Interesting issue.
