### ISSUE TITLE
Error while opening Zabbix Data Source

### ISSUE THREAD

**Issue by ziompaul** [alexanderzobnin/grafana-zabbix#1065]
Hi,
I have a problem with entering Zabbix Data Source configuration,

After clicking Zabbix:
![zabbix error 1](https://user-images.githubusercontent.com/26227388/94703863-99050c80-033f-11eb-95c4-3cb21f34e61b.PNG)

I have an error:

![zabbix error 2](https://user-images.githubusercontent.com/26227388/94703866-999da300-033f-11eb-8041-f988fafe4bb6.PNG)

Error: Object.setPrototypeOf: expected an object or null, got undefined Evaluating http://localhost:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module

It is the newest Grafana instllation.

**Comment by alexanderzobnin** [comment]
Hi! What's grafana version? How did you install plugin? Via grafana-cli?

**Comment by ziompaul** [comment]
Alex, thanks for answer.

I was sure that I have installed the newest version on Grafana (7.2), but I was wrong. The 6.3.6 has been intalled, so Zabbix plugin 4.0.1 installed automaticaly by grafana-cli won't work.

So I have installed Zabbix plugin ver. 3.12.2 dedicated to Grafana 6.3.6, and now everything is ok.

**Comment by alexanderzobnin** [comment]
The latest plugin doesn't support Grafana 6.x.

**Comment by fareeckjan** [comment]
I have a problem: 
My zabbix versio - 6.0 LTS
My Grafana version - v7.5.15 (NA)
my plugin version last

У меня проблема с добавлением плагина 
Версия заббикса 6.0
Версия графаны  v7.5.15 (NA)
Версия плагина последняя
