### ISSUE TITLE
Mikrotik Device Not Shwoing Data

### ISSUE THREAD

**Issue by itmendev** [alexanderzobnin/grafana-zabbix#1066]
i have installed zabbix and graphane, intend to integrate into graphane. devices in zabbix can be seen in graphana, but when I want to create a dashboard the values in the tool can't appear. only the words "No Data" in the chart. please help, thanks dude.

![Zabbix](https://user-images.githubusercontent.com/63114833/95014833-c15c7600-0673-11eb-87fb-3a9f43fe5fa9.PNG)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.2.0   | 5.0.4  | 4.0.1                 |

**Comment by adrianomazi** [comment]
I'm having the same issue for metrics and for Text too.

**Comment by itmendev** [comment]
Hey @adrianomazi my issue already solved. Please make new User Group, give read access for your network Group. And make New User and give as User Group you make.
