### ISSUE TITLE
Plugin not working anymore with latest Grafana (2.5.0)

### ISSUE THREAD

**Issue by karma1911** [alexanderzobnin/grafana-zabbix#107]
Hi,

I just upgraded Grafana in my dev environment, and I can't get the zabbix-grafana to work. 
- In the edit datasource, if I hit the test button once my datasource for zabbix is defined, nothing happens (config has not changed and is working if I downgrade to Grafana 2.1.3)
- On the dashboards, I now have an error message (top left corner of the graphs) with the message : kbn.parseDate is not a function

Stack trace : 
```
    TypeError: kbn.parseDate is not a function
    at ZabbixAPIDatasource.query (http://xxxxxx:3000/public/plugins/datasource/zabbix/datasource.js?bust=1446123167034:96:32)
    at issueMetricQuery (http://xxxxxx:3000/app/app.b4b243aa.js:34:8484)
    at n.a.refreshData (http://xxxxxx:3000/app/app.b4b243aa.js:44:8044)
    at http://xxxxxx:3000/app/app.b4b243aa.js:34:5867
    at i (http://xxxxxx:3000/app/app.b4b243aa.js:13:3780)
    at http://xxxxxx:3000/app/app.b4b243aa.js:13:3952
    at n.$eval (http://xxxxxx:3000/app/app.b4b243aa.js:13:11572)
    at n.$digest (http://xxxxxx:3000/app/app.b4b243aa.js:13:10003)
    at http://xxxxxx:3000/app/app.b4b243aa.js:13:11659
    at e (http://xxxxxx:3000/app/app.b4b243aa.js:10:26497)
```
I'm using the latest version of your plugin (v2.1.0-rc1, downloaded the master this morning just to be sure).

**Comment by alexanderzobnin** [comment]
Just try to use [fix-query_editor_in_2.5](https://github.com/alexanderzobnin/grafana-zabbix/tree/fix-query_editor_in_2.5) branch.

**Comment by christianchristensen** [comment]
This branch worked for me with v2.5.0

**Comment by karma1911** [comment]
Hi Alex, thanks. It indeed fix the query editor, but I still have the kbn.parseDate on the dashboards

**Comment by alexanderzobnin** [comment]
@karma1911 Ok, I will test it.

**Comment by alexanderzobnin** [comment]
@karma1911 I have no errors. Looks like your code is not up-to-date. Try to download latest relese or get code directly from master branch. This issue was fixed by 536dc237fba5b1a5f96bb3853324565d88dd0190.

**Comment by karma1911** [comment]
My bad, will give it a try this afternoon

**Comment by karma1911** [comment]
Confirmed, now working, sorry for the mislead !
