### ISSUE TITLE
Getting error while connecting zabbix

### ISSUE THREAD

**Issue by addrian1** [alexanderzobnin/grafana-zabbix#1070]
**invalid character '<' looking for beginning of value**

![image](https://user-images.githubusercontent.com/18485323/95373509-c7598d80-08e5-11eb-911d-bc33b4622347.png)

I've tried both domain name and IP, https and https. With and without backslashes at the end of the hostname. Nothing helps. And yes, I don't use _/zabbix_ after the domain name

Zabbix 5.0.1
Grafana v7.0.0 (aee1438ff2)

Please help me solve the problem.

**Comment by alexanderzobnin** [comment]
Hi! Do you see something interesting in grafana-server logs?

**Comment by adriancuschieri** [comment]
We are also having the same issue and in our case we are using the following versions:

Plugin/Zabbix 4.0.1
Zabbix 4.4.10
Grafana v7.1.5 (9893b8c53d)

When we use url https://domain 

<img width="465" alt="zabbix_plugin_2" src="https://user-images.githubusercontent.com/9918439/96579213-c60d6500-12d6-11eb-942b-858deb65c99d.png">

When we use url https://domain/zabbix/

<img width="457" alt="zabbix_plugin" src="https://user-images.githubusercontent.com/9918439/96579239-ce65a000-12d6-11eb-8064-6f7960361fc0.png">


Nothing interesting on the grafana-server logs.

**Comment by adriancuschieri** [comment]
@addrian1  - We managed to get it working by adding /zabbix/api_jsonrpc.php after the domain in the url.

Url: set Zabbix API url (full path with api_jsonrpc.php).

**Comment by alexanderzobnin** [comment]
@addrian1 you should specify full path to the `/api_jsonrpc.php` endpoint.

**Comment by dorel14** [comment]
hello
I don't think this is the best solution because when i 'm trying this , it tells me that login and password are false

**Comment by HBF1** [comment]
hi,
Getting error while creating new zabbix datasource in garfana v8.2.2 : 
invalid character '<' looking for beginning of value
