### ISSUE TITLE
No data source after upgrading to 4.0.1

### ISSUE THREAD

**Issue by tomglazer89** [alexanderzobnin/grafana-zabbix#1071]
Hi,

The zabbix data source is missing after i upgraded to 4.0.1 ver (with grafana 7.2.0).
![image](https://user-images.githubusercontent.com/5889994/95389226-2fb36980-08fc-11eb-9ac5-5911a9679ef8.png)
![image](https://user-images.githubusercontent.com/5889994/95389326-540f4600-08fc-11eb-8d83-a0a7a2978a2d.png)
![image](https://user-images.githubusercontent.com/5889994/95389356-5f627180-08fc-11eb-8f6e-4b7390313fe4.png)

i also tried to install the 4.00 version, and to delete the data source and re create it (but its not in the list, even when the plugin is enabled)

let me just mention that i'm installing the plugin in offline method, because im using grafana on a network without an internet connection (via Grafana CLI).

i had to remove old grafana version ,upload the zip, and install the new one:
_grafana-cli --pluginUrl /home/user/alexanderzobnin-zabbix-app-4.0.1.zip  plugins install alexanderzobnin-zabbix-app_

i also tried to install version 3.* and everything went OK.

Thank you !

**Comment by gongzitao** [comment]
the data source is not signed. Need to add it in config. See https://community.grafana.com/t/zabbix-plugin-doesnt-appear-at-add-data-source/36241

**Comment by tomglazer89** [comment]
Thanks gongzitao !
the solution was to add:
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
