### ISSUE TITLE
Database unification

### ISSUE THREAD

**Issue by andrefranca08** [alexanderzobnin/grafana-zabbix#1072]
**Describe alternatives you've considered**

Hello, how are you?
It is possible to create something that joins two or more databases into one so that you can use regex to create an aggregate item, even if they are of different bases.
Because I have in different databases and it would be possible to aggregate the items if it were possible to select by regex.

![Databases Unification](https://user-images.githubusercontent.com/11446273/95403850-c591c900-08e9-11eb-8c4b-13dd368b082f.png)

I would like to join BASE1 and BASE2 even though they are different bases.
Would it be possible?

**Comment by isaqueprofeta** [comment]
Try this:
- Use -- Mixed --
- Create two or more queries one or more for each of the zabbix'es
- Use Grafana's own Transform new 7+ functions

**Comment by alexanderzobnin** [comment]
It's not possible on the plugin side, but can be (partially) achieved with tips from @isaqueprofeta
