### ISSUE TITLE
Zabbix datasource doesn't appear on Grafana

### ISSUE THREAD

**Issue by Daly123456** [alexanderzobnin/grafana-zabbix#1073]
I have newly installed zabbix on the same server as Grafana i set app zabbix as ‘‘enabled’’ 
and used that command : grafana-cli plugins install alexanderzobnin-zabbix-app but zabbix is not showing as datasource on the list of Grafana dataources 
some help please !!!

**Comment by tomglazer89** [comment]
https://github.com/alexanderzobnin/grafana-zabbix/issues/1071

**Comment by Daly123456** [comment]
Sorry but I couldn't solve that and your response wasn't clear

**Comment by tomglazer89** [comment]
Ok :)
edit the file  /etc/grafana/grafana.ini

replace:
;allow_loading_unsigned_plugins

with:
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource

(remove the semi colon) 

restart grafana server..

**Comment by Daly123456** [comment]
I already did that but no results

Le sam. 10 oct. 2020 à 02:00, Tom Glazer <notifications@github.com> a
écrit :
