### ISSUE TITLE
Cannot See Dashboard Import Menu into Plugin Setting

### ISSUE THREAD

**Issue by samyscoub** [alexanderzobnin/grafana-zabbix#1074]
**Describe the bug**

With Grafana 7.2.1, can't see dashboards after installing plugin ( upgrade from an older version of the plugin ).

**Expected behavior**

Having the Dashboard Tab to import samples

**Screenshots**

![image](https://user-images.githubusercontent.com/1143119/95674172-ae373200-0bae-11eb-9a53-e53e9d90343b.png)

**Network data**

No error into Browser JS Console

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.2.1   | 4.0.25  | 4.0.1                 |

**Comment by jacksonsystems** [comment]
Hi,

I also have this very same issue, Grafana v7.2.1. Plug install via grafana-cli command.

![2020-10-13_10-32](https://user-images.githubusercontent.com/51890084/95843942-3993fd00-0d40-11eb-9ff1-065d311d1f98.png)

Have I missed something or is there an issue?

Thanks

**Comment by alexanderzobnin** [comment]
Dashboards tab available under data source config page:

![Screenshot from 2020-10-13 15-56-40](https://user-images.githubusercontent.com/4932851/95863357-c0f76580-0d6c-11eb-94bb-e14aafaaa242.png)

![Screenshot from 2020-10-13 15-57-20](https://user-images.githubusercontent.com/4932851/95863398-cbb1fa80-0d6c-11eb-88ab-287781e841fd.png)
