### ISSUE TITLE
Error loading plugin "alexanderzobnin-zabbix-datasource" is unsigned

### ISSUE THREAD

**Issue by mw-solutions** [alexanderzobnin/grafana-zabbix#1075]
After having updated the plugin grafana-zabbix to version 4.0.1 the following error is logged at Grafana startup:

[31mEROR[0m[10-14|07:30:58] Failed to load plugin                    [31mlogger[0m=plugins [31merror[0m="plugin \"alexanderzobnin-zabbix-datasource\" is unsigned" [31mpluginPath[0m=C:\\Users\\Public\\Dev\\grafana-7.2.1\\data\\plugins\\alexanderzobnin-zabbix-app\\datasource-zabbix

Grafana 7.2.1 runs on Windows Server. The error comes with version 7.1.5 too (Windows). Please get the plugin signed correctly.

**Comment by alexanderzobnin** [comment]
Duplicates #1042
