### ISSUE TITLE
Character or Text 'Strings' not returned in Table or Stats Panel

### ISSUE THREAD

**Issue by cawhite6** [alexanderzobnin/grafana-zabbix#1078]
**Describe the bug**
When query mode 'Text' runs for latest value (Table or Stats Panel) in a search- items do not return Zabbix value, returns null/blank.

**Expected behavior**
Expect Latest Data Value returned whether Time Series or Table - (same as Latest Data from Zabbix UI)

**Screenshots**
Grafana Panel:
![Screen Shot 2020-10-14 at 3 47 04 PM](https://user-images.githubusercontent.com/15822207/96038092-a4befb80-0e34-11eb-9b99-d5a5868dca42.png)

Zabbix UI:
![Screen Shot 2020-10-14 at 3 47 29 PM](https://user-images.githubusercontent.com/15822207/96038109-ab4d7300-0e34-11eb-8a9d-bf3d69cbb18c.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.2.1  | 5.0.2  | 4.0.1                |

**Comment by myriad007** [comment]
I am experiencing the same problem with the latest update. **Previously working** disk percentages (text queries displayed in gauges) now display 'no data' though Zabbix has the percentage data correctly displayed. Query inspector just spins...

![Untitled](https://user-images.githubusercontent.com/6136260/96187526-2e40fd00-0f0b-11eb-85ef-04b9e6756560.png)


Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.2.1 | 5.0.4 | 4.0.1

**Comment by BDeakins** [comment]
Likewise.  HTTP-Agent storing TEXT or CHARACTER info (tried both), storage period 90d.  Result shows up nicely in Zabbix.
Move over to Grafana, and I can pull back the Table and see the HOST, ITEM, and KEY, but not LAST VALUE.
Grafana: 7.2.1
Zabbix: 5.0.4
Plugin: 4.0.1

**Comment by jbfranklin** [comment]
I am in the same boat. No text data is coming back from Zabbix to Grafana.

**Comment by juannvalencia** [comment]
Hi,
I have the same problem.

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.3.0 | 5.0.4 | 4.0.1

**Comment by hyrava** [comment]
Same problem here. I checked with tcpdump and I can see textual data coming from Zabbix to Grafana so I think query itself is fine. 

Grafana: 7.2.1
Zabbix: 5.0.3
Plugin: 4.0.1

**Comment by psv-1979** [comment]
Same problem.

Grafana: 7.2.0
Zabbix: 5.0.3
Plugin: 4.0.1

**Comment by Tchris01** [comment]
Hi,

I have the same problem

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.2.1  | 5.0.4 | 4.0.1

**Comment by alexanderzobnin** [comment]
There're a couple of issues in grafana repo related to this bug https://github.com/grafana/grafana/issues/28042 and https://github.com/grafana/grafana/issues/27971

**Comment by cawhite6** [comment]
So confirming - this is an issue with the panels in Grafana's last update, not the Zabbix plugin?

**Comment by Tchris01** [comment]
Thanks for all

**Comment by alexanderzobnin** [comment]
Yes, it's Grafana issue, not related to the plugin.

**Comment by gustavoghpf** [comment]
Same problem here

**Comment by cawhite6** [comment]
[https://github.com/grafana/grafana/issues/27971](url) @alexanderzobnin Any chance this is a plugin issue? When I do a direct mysql query to DB I get returned string values. When looking for same information via zabbix plugin nothing.
![Screen Shot 2020-11-06 at 1 47 49 PM](https://user-images.githubusercontent.com/15822207/98403347-d2afee00-2036-11eb-9a25-f77ad2779ae5.png)

**Comment by alexanderzobnin** [comment]
Duplicates #1062

**Comment by alexanderzobnin** [comment]
https://github.com/alexanderzobnin/grafana-zabbix/issues/1062#issuecomment-723812332
