### ISSUE TITLE
this.username в zabbixAPIWrapper.js

### ISSUE THREAD

**Issue by tonymadbrain** [alexanderzobnin/grafana-zabbix#108]
При установке модуля версии 2.5.0 на grafana 2.5 соответственно, выявил проблему при работе с Zabbix API 2.2.5 с авторизацией через http. В файле https://github.com/alexanderzobnin/grafana-zabbix/blob/v2.5.0/zabbix/zabbixAPIWrapper.js в 92 строке подставляется пустота, согласно базе знаний Zabbix https://www.zabbix.com/documentation/2.2/manual/api/reference/user/login, этот параметр обязателен при http авторизации (а пароль кстати нет). Если в файле `zabbixAPIWrapper.js` после 13 строки поставить `console.log(username);` выдает `undefined`. Не особо владею JS, поэтому не могу пофиксить, надеюсь понятно объяснил, у себя же временно "захардкодил" username. Что скажете?

**Comment by alexanderzobnin** [comment]
А вы можете скрин настроек датасорса сделать? Вообще, `this.username` берется из настроек датасорса, но это не то же самое, что `User` и `Password` в натройках Basic Auth.

**Comment by tonymadbrain** [comment]
![screenshot from 2015-11-09 10 40 48](https://cloud.githubusercontent.com/assets/5266592/11028313/67dfd59c-86ce-11e5-977b-df31a9602456.png)

**Comment by alexanderzobnin** [comment]
Судя по коду метода `performZabbixAPILogin()`, все делается правильно:
```
p.performZabbixAPILogin = function() {
      var options = {
        url : this.url,
        method : 'POST',
        data: {
          jsonrpc: '2.0',
          method: 'user.login',
          params: {
            user: this.username,
            password: this.password
          },
          auth: null,
          id: 1
        }
      };

      if (this.basicAuth || this.withCredentials) {
        options.withCredentials = true;
      }
      if (this.basicAuth) {
        options.headers = options.headers || {};
        options.headers.Authorization = this.basicAuth;
      }

      return backendSrv.datasourceRequest(options).then(function (result) {
        if (!result.data) {
          return null;
        }
        return result.data.result;
      });
    };
```

Но если при инициализации датасорса у вас username не определено, то я думаю, что проблема в странице настроек. Скрин немного странный - на нем нет дополнительных параметров - трендов и т.д. Попробуйте очистить кэш браузера, такое бывает при обновлении - шиблоны html-страниц кэшируются браузером и после обновления выдается устаревшая версия.

**Comment by tonymadbrain** [comment]
Да, проблема была в кеше, спасибо!
