### ISSUE TITLE
Cannot access to datasource menu configuration after update of the grafana plugin

### ISSUE THREAD

**Issue by samyscoub** [alexanderzobnin/grafana-zabbix#1080]
**Describe the bug**
Cannot access to plugin configuration since upgrade to 4.0.1
No Problem with other datasources like Elasticsearch or Prometheus
Rollback to 3.12.2 release seems to fix this

**Expected behavior**
Access to configuration menu of the datasource

**Screenshots**
![image](https://user-images.githubusercontent.com/1143119/96331039-568b4180-105a-11eb-8ee3-31d4692e9055.png)

**Network data**
404 error when access to settings

![image](https://user-images.githubusercontent.com/1143119/96331081-b5e95180-105a-11eb-9259-fa4e291d8f43.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.2.1   | 5.0.4  | 4.0.1                 |

**Comment by garbled1** [comment]
Same issue.  The datasource was marked as missing, couldn't re-add it, downgrade fixed.

**Comment by pizzasuprema** [comment]
Having the same issue

**Comment by vordee** [comment]
Same issue.

**Comment by AAERob** [comment]
Same issue

**Comment by mnlsvrs** [comment]
Same issue here. Downgraded to  3.12.4.

**Comment by IgorOhrimenko** [comment]
Problem:
Plugin not found, no installed plugin with that id

Fix:
in /etc/grafana/grafana.ini , Iine 728 [;allow_loading_unsigned_plugins =] delete ; and type [alexanderzobnin-zabbix-datasource]
like this [allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource]

and restart daemon, you can see zabbix in datasource
(c) ltoqurl499
