### ISSUE TITLE
Use Data Frames format

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#1082]
The new Grafana [Data Frame](https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/) format is much more flexible and provides better UX when changing visualization types. So it makes sense to change old time series format to the data frame.

Work in progress:

- [x] Convert each series to data frame
- [x] Use wide format when it's possible (many series in one data frame)
- [x] Add labels (host name and item name) to each field (time series)
- [x] Align points in each series to prevent stacking graph issues
- [x] Use item units configured in Zabbix if possible (percents, bits, Bytes, b/s, B/s, etc)
- [x] Use value mappings from Zabbix (network interface statuse, host status, ect)

**Comment by isaqueprofeta** [comment]
I'm really looking forward to this. I've been wanting to help you with updating docs, but I think this change will be pretty big if implemented. Gonna wait for it.
