### ISSUE TITLE
Text data is not shown in table and single stat panels

### ISSUE THREAD

**Issue by vryzhevsky** [alexanderzobnin/grafana-zabbix#1083]
**Describe the bug**
I am trying to show text metric in Grafana Stat and Table panels. Data is now shown.

**Expected behavior**
Data should be shown.

**Screenshots**
![screen1](https://user-images.githubusercontent.com/30687522/97228595-34c35480-17e8-11eb-8b94-d5e7c7e69cee.png)
![screen2](https://user-images.githubusercontent.com/30687522/97229306-33def280-17e9-11eb-919b-c201ffcecc4e.png)
![screen3](https://user-images.githubusercontent.com/30687522/97228988-be732200-17e8-11eb-88a9-e10b0836dcce.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.2.2   | 5.0.3  | 4.0.1                 |

**Comment by neothematrix** [comment]
it looks like it's Grafana 7.2 fault: #1078

**Comment by tpramos** [comment]
Grafana 7.3 is released and the issue keeps then!

**Comment by juannvalencia** [comment]
Hi,
I have just updated to Grafana v7.3.1 and the problem remains.
Has anyone been fixed?

**Comment by mbrekhov** [comment]
> 
> 
> Hi,
> I have just updated to Grafana v7.3.1 and the problem remains.
> Has anyone been fixed?

Yes. Just type any symbol in 'Text filter' field (where you usually write regexp) and then delete that symbol. After that you will see the data in the panel

**Comment by juannvalencia** [comment]
> 
> 
> > Hi,
> > I have just updated to Grafana v7.3.1 and the problem remains.
> > Has anyone been fixed?
> 
> Yes. Just type any symbol in 'Text filter' field (where you usually write regexp) and then delete that symbol. After that you will see the data in the panel

It worked,

Thank you very much!

**Comment by vryzhevsky** [comment]
> it looks like it's Grafana 7.2 fault: #1078

It looks like complex bug of Grafana and Zabbix plugin because of this comment - https://github.com/alexanderzobnin/grafana-zabbix/issues/1083#issuecomment-719890044

**Comment by mbrekhov** [comment]
Looks like it has been fixed in v4.0.2
https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v4.0.2

**Comment by alexanderzobnin** [comment]
It's fixed now.
