### ISSUE TITLE
GFX_ZABBIX_DATA_PATH not used but exposed in logs

### ISSUE THREAD

**Issue by tuxmainy** [alexanderzobnin/grafana-zabbix#1085]
**Describe the bug**
While Grafana loads the Zabbix Plugin on startup you can obtain following Debug message:

`
"Could not read environment variable" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource GFX_ZABBIX_DATA_PATH=<unknown>
`

Looks like everything is working fine but I was curious so looked up "GFX_ZABBIX_DATA_PATH" but didn't found anything. Having a look into the source code you can find following in the "Init" function of [plugin.go](https://github.com/alexanderzobnin/grafana-zabbix/blob/master/pkg/plugin.go):

`
func Init(logger log.Logger, mux *http.ServeMux) *datasource.ZabbixDatasource {
	variableName := "GFX_ZABBIX_DATA_PATH"
	path, exist := os.LookupEnv(variableName)
	if !exist {
		logger.Debug("Could not read environment variable", variableName)
	} else {
		logger.Debug("Environment variable for storage found", "variable", variableName, "value", path)
	}

	ds := datasource.NewZabbixDatasource()

	mux.HandleFunc("/", ds.RootHandler)
	mux.HandleFunc("/zabbix-api", ds.ZabbixAPIHandler)
	// mux.Handle("/scenarios", getScenariosHandler(logger))

	return ds
}
`

I'd guess you can safely remove the first 7 lines without any impact. But as I am not familiar with GO I rather open a bug than submitting a pull request.

**Expected behavior**
No log message as this environment variable seems to be unused.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.1 (6668161a88)   | 4.4.6  | 4.0.1 |

**Comment by alexanderzobnin** [comment]
Hi! This variable is reserved for future usage (store some plugin-specific data, like request cache or API tokens). It's not used right now, so I can disable logs until it's used.
