### ISSUE TITLE
Can add Zabbix as Datasource in Grafana

### ISSUE THREAD

**Issue by G0nz0uk** [alexanderzobnin/grafana-zabbix#1092]
Hello,

I've been using Grafana (v7.3.1) for a while now and have many data sources connected to it. I've been asked to add Zabbix as a data source and I am having trouble.

We are using the free Zabbix appliance 5.2.1 in VMware and I've added a few devices to monitor.

I've been trying so many ways to add it as a data source and all fail.

I know the API account works as I can log into it.

If I go to http://x.x.x.215/zabbix/api_jsonrpc.php I get a File Not Found which I think is correct

![image](https://user-images.githubusercontent.com/15994497/99055529-82361480-2591-11eb-8c8f-9dfbd7bdecde.png)

Any ideas where I'm being stupid?

Thanks

**Comment by pkpk9527** [comment]
by   changing    /zabbix/api_jsonrpc.php  into  api_jsonrpc.php .   just  like    http://x.x.x.215/api_jsonrpc.php.        i  got  the problem  solved.


LOL.  i guess   api  has been  updated

**Comment by G0nz0uk** [comment]
Hmm that didn't work for me either, what other settings are you using in your data source please as I must of got something else wrong in there?

**Comment by pkpk9527** [comment]
still 404 file not found?  
your   Zabbix appliance is 5.2.1 ...      you  should  use     http://x.x.x.215:8080/api_jsonrpc.php  instead.    start from zabbix-sever 4.0.X（maybe ，i am not quite  sure ）.   the default 80 has changed to 8080,

**Comment by alexanderzobnin** [comment]
Why do you use Browser mode? It's deprecated, use server instead. Make sure you configured proper URL for the zabbix api.
