### ISSUE TITLE
Filter problems by time range

### ISSUE THREAD

**Issue by Yotouille** [alexanderzobnin/grafana-zabbix#1094]
Hi there,

**Is your feature request related to a problem? Please describe.**
Do you think it would be possible to filter results by date in "Zabbix Problems" ?
For example, we want to have a panel only showing today's problem, and another one with all others.

**Describe the solution you'd like**
In the query options, we could have 2 more fields "start/end", for example for the last 24h:
- start date: -1d
- end date: now

And for all the others (here I do not set the "start", as for "any"):
- start date:
- end date: -1d

**Describe alternatives you've considered**
None...

Thanks for your work.

Bye !

**Comment by isaqueprofeta** [comment]
You should've considered using graphene native Query options with Relative time, FYI:

- Query option: https://grafana.com/docs/grafana/latest/panels/queries/#query-options
- Relative time: https://grafana.com/docs/grafana/latest/dashboards/time-range-controls/

**Comment by Yotouille** [comment]
It seems "Zabbix Problems" do not pay attention to time range, I have tried Absolute and Relative time range, it always shows all _current_ problems. Another clue is when you want to display only yesterday's problems you will also see today's problems, things that did not yet happen at that time range.

**Comment by alexanderzobnin** [comment]
Hi! Now panel shows only current problems, when `Problems` or `Recent problems` selected. In the `History` mode panel uses time range and limit problems by that range. But probably it makes sense to add toggle for time range support for `Problems` and `Recent problems` modes.
