### ISSUE TITLE
connect: connection refused

### ISSUE THREAD

**Issue by estcado** [alexanderzobnin/grafana-zabbix#1095]
Hello, I cannot configure the zabbix data source.
I use Eyes of network which includes Grafana
a connection refused error appears.

**Expected behavior**
I put my address,
I put the user who comes from grafana in basic auth.
but the error comes every time

**Screenshots**
![image](https://user-images.githubusercontent.com/6891474/99399515-0d8f0d00-28e6-11eb-9e7e-cecba9f08a47.png)
![image](https://user-images.githubusercontent.com/6891474/99399992-b6d60300-28e6-11eb-9b1f-f66214b50fc1.png)

*Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.2  | x.x.x  | 4.0.1                |

**Comment by isaqueprofeta** [comment]
Connection refused isn't grafana's plugin error, it's an error sent by your destination machine telling about port 8090 not having any services running on it. Your Zabbix-frontend seems not to be on 8090.

**Comment by alexanderzobnin** [comment]
Yes, make sure host where grafana-server is running, has access to your zabbix frontend. Also, check the address and port, maybe it's not a zabbix frontend port.

**Comment by Rodrigues-Michael** [comment]
estou a 4 dias tentando fazer isso funcionar sem sucesso todos os endereços possivéis eu já tentei porém não consigo autenticar o plugin no zabbix sempre a mesma falha:
Post "http://localhost:80/zabbix/api_jsonrpc.php": dial tcp 127.0.0.1:80: connect: connection refused

**Comment by isaqueprofeta** [comment]
@Rodrigues-Michael o erro de conexão recusada quer dizer que no endereço localhost, ou seja, no seu 127.0.0.1 o servidor web do zabbix não está rodando. Revise sua instalação e se precisar de apoio, tente os canais Grafanabr e ZabbixBrasil no Telegram. Cuidado, pois Issues no github não são o lugar certo para problemas e dúvidas pontuais como essa.
