### ISSUE TITLE
grafana6.7.4 zabbix Serious bug

### ISSUE THREAD

**Issue by uranus829** [alexanderzobnin/grafana-zabbix#1096]
new system:centos7.9
grafana version:6.7.4
The function of table paging in version 7 is removed, I want to return to the old version。
open zabbix plugins error:
Cannot read property 'FormField' of undefined Evaluating http://192.8.29.12:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module
![image](https://user-images.githubusercontent.com/46716344/99534039-bf5f3400-29e1-11eb-869e-ef16f89f2894.png)
![image](https://user-images.githubusercontent.com/46716344/99534048-c4bc7e80-29e1-11eb-9cb8-a71c22ff872c.png)

**Comment by isaqueprofeta** [comment]
Downgrade to plugin version 3.12.2 using grafana-cli.

Plugins 4.0+ **requires** grafana > 7

**Comment by alexanderzobnin** [comment]
Yes, latest version is not compatible with Grafana 6.x.

**Comment by wandersonprs** [comment]
Estou com o mesmo problema, o granafa 6.7.4, e troquei o plugin para 3.12.1.
Quando vou habilitar ficar somente carregando.

![image](https://user-images.githubusercontent.com/84187011/118284359-b76ee100-b4a6-11eb-84fd-668ed6d5215b.png)

**Comment by isaqueprofeta** [comment]
> Estou com o mesmo problema, o granafa 6.7.4, e troquei o plugin para 3.12.1.
> Quando vou habilitar ficar somente carregando.
> 
> ![image](https://user-images.githubusercontent.com/84187011/118284359-b76ee100-b4a6-11eb-84fd-668ed6d5215b.png)

Favor se atentar que o autor do plug-in nao tem conhecimenro de língua portuguesa... 

Revise questões de cache e coisas do tipo, confirme via grafana-cli se o plug-in realmente foi  feito o downgrade e coisas do tipo. Considere estudar o upgrade de todo o seu ambiente.
