### ISSUE TITLE
Query inspector is not working

### ISSUE THREAD

**Issue by sirbavo** [alexanderzobnin/grafana-zabbix#1097]
**Describe the bug**
Open the query inspector from a panel (Panel -> Inspect -> Query -> Refresh) or from the Explore menu. Since 7.2.0 it does not show any result from this plugin.

[Example](https://play.grafana-zabbix.org/d/000000003/grafana-zabbix-demo?inspect=9&inspectTab=query&orgId=2)

**Network data**
The query in the background runs succesfully, the response from the Zabbix API is good.

**Related change in Grafana**
https://github.com/grafana/grafana/commit/a49daf5676bff0ed5651f7a5c419848c807391a1

_./public/app/core/services/backend_srv.ts_

```
if (options.hideFromInspector === undefined) {
  // Hide all local non data query calls
  options.hideFromInspector = isLocalUrl(options.url) && !isDataQuery(options.url);
}
```

In the Zabbix plugin request `hideFromInspector` is `undefined` and the result of the condition body is also `true`, so Grafana hides the query result.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.2.0+ | - | 4.0.2 |

**Comment by alexanderzobnin** [comment]
Good catch, @sirbavo!
