### ISSUE TITLE
Negative filter

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#11]
Invert values for show below null line (for example network in/out traffic)

**Comment by nucleusv** [comment]
Do youm mean that in/out traffic is stored like a delta? Besides value_type there are
https://www.zabbix.com/documentation/2.4/manual/api/reference/item/get
     {
            "itemid": "23299",
            "type": "0",
            "snmp_community": "",
            "snmp_oid": "",
            "hostid": "10084",
            "name": "CPU $2 time",
            "key_": "system.cpu.util[,idle]",
            "delay": "60",
            "history": "7",
            "trends": "365",
            "lastvalue": "86.031879",
            "lastclock": "1351090999",
            "prevvalue": "85.306944",
            "state": "0",
            "status": "0",
            "value_type": "0",
            "trapper_hosts": "",
            "units": "%",
   >>>> "multiplier": "0",
   >>>> "delta": "0", 
            "snmpv3_securityname": "",
            "snmpv3_securitylevel": "0",
            "snmpv3_authpassphrase": "",
            "snmpv3_privpassphrase": "",
            "formula": "1",
            "error": "",
            "lastlogsize": "0",
            "logtimefmt": "",
            "templateid": "17354",
            "valuemapid": "0",
            "delay_flex": "",
            "params": "",
            "ipmi_sensor": "",
            "data_type": "0",
            "authtype": "0",
            "username": "",
            "password": "",
            "publickey": "",
            "privatekey": "",
            "mtime": "0",
            "lastns": "564256864",
            "flags": "0",
            "filter": "",
            "interfaceid": "1",
            "port": "",
            "description": "The time the CPU has spent doing nothing.",
            "inventory_link": "0",
            "lifetime": "0"
        },

**Comment by alexanderzobnin** [comment]
No, like this (just invert all values in timeseries)
![2015-05-15 18-40-08](https://cloud.githubusercontent.com/assets/4932851/7657849/0851926c-fb3e-11e4-9009-ddb06b908751.png)

**Comment by nucleusv** [comment]
It is nice :)

**Comment by alexanderzobnin** [comment]
It very simple but very useful filter. I want to add some other filters like average, min, max (like at influxdb datasource).

**Comment by nucleusv** [comment]
Yeah, it is great idea. 
As plugin for grafana-2 is working? 
We need user restrictions to have there own dashboards? Maybe it is better to focus on version for grafana-2 ?  
So what problem do you have?
Maybe better to ask Torkel to answer questions ?

**Comment by alexanderzobnin** [comment]
If you want I can release alpha version of plugin for grafana-2 for prewiew. It have some problems with configuring via new datasource config page, but in generally, plugin is working.

**Comment by Diwahars** [comment]
Hi,

Release the beta version of 2.0... Let's c how it works.??

**Comment by alexanderzobnin** [comment]
@Diwahars see last changes. I added version of plugin for grafana-2 in master branch. Now it default branch. I will focused on development version for grafana-2.
