### ISSUE TITLE
No datapoints returned from metric query

### ISSUE THREAD

**Issue by ca7dEm0n** [alexanderzobnin/grafana-zabbix#110]
HI,
I configured grafana and grafana-zabbix in the right way, but did not return data.
Grafana version : 2.5.0-1
Grafana-zabbix version: 2.5.1
Zabbix Api version: 2.4.3
I checked the log file, but I didn't find the report..
My heart was almost collapsed...

**Comment by alexanderzobnin** [comment]
Are you see host groups, hosts, metrics in query editor?

**Comment by ca7dEm0n** [comment]
Yes, I saw the host,groups,item. but no data returned.

**Comment by ca7dEm0n** [comment]
![qq 20151111143403](https://cloud.githubusercontent.com/assets/14136093/11085461/9fc26cfe-8881-11e5-9e14-6406bdcd0ec8.png)

**Comment by alexanderzobnin** [comment]
Can you select one item instead All?

**Comment by ca7dEm0n** [comment]
like this? 
![qq 20151112090543](https://cloud.githubusercontent.com/assets/14136093/11107926/2a4ee2a8-891d-11e5-9510-2a8782a50c41.png)

**Comment by ca7dEm0n** [comment]
like this? This item is not in real time
![qq 20151112091347](https://cloud.githubusercontent.com/assets/14136093/11108018/30330270-891e-11e5-80b3-290a668f01a6.png)

**Comment by alexanderzobnin** [comment]
Looks strange. Try to clear browser cache - your editor looks like from previos version.

**Comment by ca7dEm0n** [comment]
I think I might know why，
 My ZABBIX database can't get the data,
 But can use zabbix_api to find out,
 I don't know why..
 Thank you very much for your patience with me.
![qq 20151113174122](https://cloud.githubusercontent.com/assets/14136093/11143162/1f665b70-8a2e-11e5-8bc6-72e331a53d6a.png)
