### ISSUE TITLE
Grafana doesn't prevent from saving alerts with template variables

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#1100]
**Describe the bug**
When saving alerts with template variables, there's no any error that tells it's not possible to do, then alert execution fails (as expected, since alerts with variables are not supported).

**Expected behavior**
Dashboard not saved and error returned.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.3 | x.x.x  | 4.0.2                 |

**Comment by meyerder** [comment]
Be aware on a larger instance this brought the mysql db basically down... the alerts were running and returning 280,000 rows of data every 10 seconds (multiple alerts on the same page)

Honestly, I thought ohhh wow great we can leverage alerting now with templates..   👍
