### ISSUE TITLE
Not able to create variables using zabbix datasource

### ISSUE THREAD

**Issue by hamsjelv** [alexanderzobnin/grafana-zabbix#1103]
Grafana v7.3.3
zabbix plugin 4.0.2

<img width="699" alt="grafana-zabbix-bug" src="https://user-images.githubusercontent.com/20521347/99944238-cfc13700-2d72-11eb-81ea-6d869498f97e.png">

- Adding zabbix as datasource

- Created dashboard

- Beginning to create variables for that dashboard

- When selecting datasource in query options, the page goes blank.

**Get these in console:**
_[Deprecation warning] kbn.ts: kbn.secondsToHms() is deprecated. Use @grafana/data instead deprecationWarning.ts:14:12
[Deprecation warning] kbn.ts: kbn.secondsToHms() is deprecated. Use @grafana/data instead_

**and these:**

_Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings._

Using other datasources like influx or mysql there is no problem.

/Martin

**Comment by hamsjelv** [comment]
works with:
grafana 7.0.0
grafana-zabbix plugin v3.9.1

**Comment by hamsjelv** [comment]
After downgrade to grafana-zabbix plugin v3.9.1 the page is not blank anymore.
So it works with
grafana 7.3.3
grafana-zabbix plugin v3.9.1

**Comment by alexanderzobnin** [comment]
I can't replicate this. Could you confirm that bug exist in Grafana 7.3.4 and plugin 4.0.2?

**Comment by hamsjelv** [comment]
Hi Alexander,
Just installed a fresh new grafana 7.3.6 and zabbix plugin 4.0.2.
I cant replicate it either - guess its solved then :+1: 

Happy holidays.

/Martin
