### ISSUE TITLE
Unable to change severity to Not Classified

### ISSUE THREAD

**Issue by borjasueiro** [alexanderzobnin/grafana-zabbix#1104]
In the Zabbix Problems wigdet cannot change the severity of the problem to **Not Classified**. The error that comes up is the following:
![image](https://user-images.githubusercontent.com/49273030/99983778-92799b00-2dac-11eb-82dc-c588af8b39b3.png)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.3   | 5.0.5  |4.0.2                 |

**Comment by msantpine** [comment]
Same here.
| Grafana | Zabbix | Plugin |
|-------------|----------|----------|
| 7.2.0      | 5.0.4   | 4.0.2 |
