### ISSUE TITLE
Plugin unavailable in Raspbian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by danielgusmao** [alexanderzobnin/grafana-zabbix#1107]
![image](https://user-images.githubusercontent.com/1507436/100494305-47021c80-311f-11eb-8c64-eb5d817926c4.png)

![image](https://user-images.githubusercontent.com/1507436/100494276-13bf8d80-311f-11eb-86c8-e1ef734a04dc.png)
![image](https://user-images.githubusercontent.com/1507436/100494284-1de18c00-311f-11eb-8a5e-22550e74b20a.png)

zabbix_server (Zabbix) 5.0.5
grafana-server Version 7.3.3 (commit: 2489dc4d3a, branch: HEAD)
Raspbian GNU/Linux 10 (buster)

**Comment by perlporter** [comment]
I'm facing the same problem in a different system, see:

zabbix5-server (5.0.4)
grafana-server (7.3.4)
FreeBSD 12.2-RELEASE-p1

I've added that too:

allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource

Waiting for a possible solution :-)

**Comment by HyderKhalil** [comment]
Same for me. New install of Grafana v7.3.4 (14c494085e) on Raspberry Pi 4 running Zabbix 5.2.2

**Comment by HyderKhalil** [comment]
I managed to get this working for me. I found this issue here:

https://github.com/alexanderzobnin/grafana-zabbix/issues/1028

I checked the plugin directory at /var/lib/grafana/plugins/alexanderzobnin-zabbix-app and the arm version of the plugin wasn't there, so I dowloaded the zip file https://github.com/alexanderzobnin/grafana-zabbix/files/5623127/alexanderzobnin-zabbix-app-4.0.2.zip and copied the two arm files into the plugin directory, restart Grafana and all working now.

**Comment by perlporter** [comment]
> I'm facing the same problem in a different system, see:
> 
> zabbix5-server (5.0.4)
> grafana-server (7.3.4)
> FreeBSD 12.2-RELEASE-p1
> 
> I've added that too:
> 
> allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
> 
> Waiting for a possible solution :-)

I think I found something relevant... check the log:

t=2020-12-09T08:32:52-0300 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="fork/exec /var/db/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_freebsd_amd64: no such file or directory"

It seems to me that in this version there is the need of a specific binary for each architecture....


zabbix-plugin_darwin_amd64:      Mach-O 64-bit x86_64 executable
zabbix-plugin_linux_amd64:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=yO6v6WdNLrXQdtF9K7ZL/kIZ-od62bPy7jdIipyLE/xmraMuk0R7m5JiwTu1YP/tf5dOjFJKf6GHNu9GLHc, stripped
zabbix-plugin_windows_amd64.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows

**Comment by HyderKhalil** [comment]
> It seems to me that in this version there is the need of a specific binary for each architecture....

Yes, if you copy the arm files from the link in my previous post and put them in the plugin directory, it solved the problem for me.

**Comment by perlporter** [comment]
> Yes, if you copy the arm files from the link in my previous post and put them in the plugin directory, it solved the problem for me.

I understand... but my problem is that I am running on FreeBSD and not on Raspberry Pi

**Comment by danielgusmao** [comment]
> I managed to get this working for me. I found this issue here:
> 
> #1028
> 
> I checked the plugin directory at /var/lib/grafana/plugins/alexanderzobnin-zabbix-app and the arm version of the plugin wasn't there, so I dowloaded the zip file https://github.com/alexanderzobnin/grafana-zabbix/files/5623127/alexanderzobnin-zabbix-app-4.0.2.zip and copied the two arm files into the plugin directory, restart Grafana and all working now.

Big man, i did it and nothing, check it out

![Captura de Tela 2020-12-10 às 14 18 40](https://user-images.githubusercontent.com/1507436/101806360-9f0f2a80-3af2-11eb-8cef-ec8a47c71bcd.png)

![Captura de Tela 2020-12-10 às 14 19 40](https://user-images.githubusercontent.com/1507436/101806467-c2d27080-3af2-11eb-80f3-9bcc2f87b8f1.png)

**Comment by HyderKhalil** [comment]
Hmmm... The only other thing I did was to change the permissions on the alexanderzobnin-zabbix-app directory to 777 and also. Don't know if that helps?

**Comment by danielgusmao** [comment]
> Hmmm... The only other thing I did was to change the permissions on the alexanderzobnin-zabbix-app directory to 777 and also. Don't know if that helps?

You are the man !!!

![Captura de Tela 2020-12-10 às 14 50 07](https://user-images.githubusercontent.com/1507436/101809986-0202c080-3af7-11eb-9b4c-ff0a361c9c9e.png)

**Comment by alexanderzobnin** [comment]
Duplicates #1028

**Comment by felipebsd** [comment]
> > Yes, if you copy the arm files from the link in my previous post and put them in the plugin directory, it solved the problem for me.
> 
> I understand... but my problem is that I am running on FreeBSD and not on Raspberry Pi

Same problem here. Solved?
