### ISSUE TITLE
Completed /public/app/app/plugins/datasource/zabbix/datasource.js 404 Not Found

### ISSUE THREAD

**Issue by romanponomarev** [alexanderzobnin/grafana-zabbix#111]
Hi, Alexandr

I installed Grafana 2.5 and gtafana-zabbix 2.5.1 to RHEL 6.5
Add new datasource Zabbix. When I push the button Test Connection I can see in the log file:
$ tail /var/log/grafana/grafana.log
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/11/11 09:05:56 [I] Database: postgres, ConnectionString: user=grafana password=XXXXXXX host=10.242.145.144 port=5432 dbname=grafdb1 sslmode=disable
2015/11/11 09:05:56 [I] Migrator: Starting DB migration
2015/11/11 09:05:56 [I] Listen: http://0.0.0.0:3000
2015/11/11 09:06:02 [I] Completed /public/app/app/plugins/datasource/zabbix/datasource.js 404 Not Found in 5.356494ms

How fix it:  /public/app/app/ ?

**Comment by romanponomarev** [comment]
I was install to Win2K8x64 - it's work! But, how fix the plugin grafana-zabbix to RHEL?

**Comment by alexanderzobnin** [comment]
Look at the path in log: `/public/app/app/plugins/datasource/zabbix/datasource.js`
Please post content of your `plugin.json` file.

**Comment by romanponomarev** [comment]
Sorry, I was wrong
I installed Grafana 2.1.3 instead of 2.5
