### ISSUE TITLE
How to add a filter value on the column "Ack"

### ISSUE THREAD

**Issue by Froggy13** [alexanderzobnin/grafana-zabbix#1110]
![image](https://user-images.githubusercontent.com/440428/100629347-74221b00-3329-11eb-9dbc-5905bd5abd79.png)
Hi,

I would like to know if it's possible to add a filter value on the Column "Act". 
I need to display only the Zabbix's alerts who wasn't acknowledged.    ==>  Act = ""

Thank's a lot for your help.

David

**Comment by MatthewSteeves** [comment]
What version of plugin are you running? For me, I can choose whether to show all, unack'd or ack'd via drop down list. In your screenshot, it would be under Query A, then expand Options.

**Comment by Froggy13** [comment]
Hi, I use the 7.1.1. I did test with the Options Acknowledeged drop down list. It works fine !!!
Thank you for your help
![2020-12-07_11-18-21](https://user-images.githubusercontent.com/440428/101339123-4afc1000-387e-11eb-9cbf-dd34fbff62e0.jpg)
