### ISSUE TITLE
Zabbix Problem - No data displayed on the panel

### ISSUE THREAD

**Issue by alahiani** [alexanderzobnin/grafana-zabbix#1112]
I had the same problem as the issue #1077. 

After updating the pluging to the latest version 4.0.2 the problem is still persistent. 
There is no problem showen in the panel.

![image](https://user-images.githubusercontent.com/75360430/100849884-4ea92480-3483-11eb-851b-1fa17577abb2.png)

<b> Software versions </b>

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.2.1 | 3.4.15 | 4.0.2

**Comment by deepseabug** [comment]
Same problem. Using Query inspector you can see:
name:undefined
severity:undefined
acknowledged:undefined

**Comment by deepseabug** [comment]
![Snipaste_2020-12-18_13-24-16](https://user-images.githubusercontent.com/12710297/102578198-9642d800-4134-11eb-9f4a-2fc4fede85cf.png)
![Snipaste_2020-12-18_13-25-09](https://user-images.githubusercontent.com/12710297/102578196-9511ab00-4134-11eb-99ca-853ce6011877.png)

![Snipaste_2020-12-18_13-29-19](https://user-images.githubusercontent.com/12710297/102578424-1c5f1e80-4135-11eb-8959-6f61340bb4e0.png)

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.3.5 | 3.4.15 | 4.0.2

**Comment by alexanderzobnin** [comment]
It doesn't work with Zabbix 3.x anymore. This is mentioned in the release notes (change log).
