### ISSUE TITLE
Upgraded to 4.0.2, now Grafana says Plugin not found, no installed plugin with that id

### ISSUE THREAD

**Issue by havedill** [alexanderzobnin/grafana-zabbix#1114]
**Describe the bug**
I upgraded my plugins using grafana-cli plugins update-all. My zabbix dashboards now all complain the existing datasource is not found. I cannot edit the datasource because of this error:
`Plugin not found, no installed plugin with that id`

The plugin is listed as installed in my plugins panel still. If i go to create a new datasource, Zabbix is not listed.

**Expected behavior**
My datasource exists and should be functional. **Rolling back to 3.12.4 resolved my issue. I tested version 4.0.0, 4.0.1, and 4.0.2 and they all have the above problem.**

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.2.2   | 5.0.3  | 4.0.2                 |

**Comment by nikolaev-rd** [comment]
I have the same issue and the same components version (Zabbix 3.x).

**Comment by nikolaev-rd** [comment]
Workaround from issue #1045 solve the problem:
```ini
[plugins]
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
```

**Comment by alexanderzobnin** [comment]
This bug was fixed in the latest Grafana, so either upgrade it or use workaround above.

**Comment by mircsicz** [comment]
Workaround doesn't work for me. I'm using plging version 41.5. with grafana 7.5.1 on FreeBSD 12.2-RELEASE-p6 in a TrueNAS jail. Also i compiled the freebsd pluging as suggested...

**Comment by nikolaev-rd** [comment]
> Workaround doesn't work for me. I'm using plugin version 4.1.5. with grafana 7.5.1 on FreeBSD 12.2-RELEASE-p6 in a TrueNAS jail. Also i compiled the freebsd pluging as suggested...
> 
> Even after editiing the line in grafana.conf according to the path and MANIFEST.txt:
> `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app`

Worked for me with or without `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app`:
* Grafana: v7.5.4 (615c153b3a)
* alexanderzobnin-zabbix-app: 4.1.5

Plugin exist:
![image](https://user-images.githubusercontent.com/24430718/118879217-1c886380-b8f9-11eb-8c6d-7dae93192358.png)

And I can create datasource:
![image](https://user-images.githubusercontent.com/24430718/118879536-83a61800-b8f9-11eb-8ad7-2e6d73d5b0e4.png)

**Comment by mircsicz** [comment]
@nikolaev-rd what platform are you on?

As I'm on FreeBSD I had to compile a module...

**Comment by nikolaev-rd** [comment]
Ubuntu 18.04.2 LTS (Bionic Beaver)

**Comment by mircsicz** [comment]
@nikolaev-rd  so you don't need to compile a module...

**Comment by nikolaev-rd** [comment]
@mircsicz what error are you getting? Plugin not found or Plugin unavailable (#1054, [workaround](https://github.com/alexanderzobnin/grafana-zabbix/issues/1054#issuecomment-763684385))

**Comment by mircsicz** [comment]
`Plugin not found, no installed plugin with that id
`
pls see #1203
