### ISSUE TITLE
TrojanDropper.Dapato.acbs

### ISSUE THREAD

**Issue by pingufreak** [alexanderzobnin/grafana-zabbix#1116]
VirusTotal shows this up on the latest release. Do you know why?

**Comment by alexanderzobnin** [comment]
Could you explain? I tried to check a zip at VirusTotal and it doesn't show anything:

![Screenshot from 2020-12-22 15-43-12](https://user-images.githubusercontent.com/4932851/102889926-90b6fc00-446c-11eb-8f4d-075267665e4a.png)
