### ISSUE TITLE
Direct DB Connection problem+HTTP API Connection problem

### ISSUE THREAD

**Issue by jetjo** [alexanderzobnin/grafana-zabbix#1121]
request failed, status: 403 Forbidden after press Save&Test

in logs i saw this text:
t=2020-12-22T07:53:32+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/11/resources/zabbix-api status=500 remote_addr=**my_ip** time_ms=261 size=83 referer=https://mygrafanadesk.com/datasources/edit/11/
t=2020-12-22T07:53:32+0000 lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="request failed, status: 403 Forbidden"

Zabbix version is 4.2.8, Grafana version is v7.3.6, plugin version 4.0.2., i tried to reinstall the plugin, same error

**Comment by jetjo** [comment]
![screen](https://user-images.githubusercontent.com/36190843/102899403-e21ab780-447b-11eb-8e4d-e4eae79f744b.PNG)
zgraf is Zabbix Super Administrator, firewall is set correctly on both sides and nothing

P.S. i use my grafana in the K8S and in this log i see this 
t=2020-12-22T14:36:04+0000 lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="request failed, status: 403 Forbidden"
t=2020-12-22T14:36:04+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/11/resources/zabbix-api status=500 remote_addr=**my_ip** time_ms=333 size=83 referer=https://grafana.mydomain.com/datasources/edit/11/

**Comment by jetjo** [comment]
what is mean "Forbidden", which side told this message ?

**Comment by alexanderzobnin** [comment]
Forbidden means you don't have access to the URL. Probably firewall misconfiguration or additional auth required (basic auth or whatever).
