### ISSUE TITLE
Add option to disable zabbix value mapping translation in query.

### ISSUE THREAD

**Issue by serg-ku** [alexanderzobnin/grafana-zabbix#1128]
In 4.1  release Grafana-Zabbix started to use zabbix value mappings, but this breaks old dashboards where mapping are configured in grafana and also in zabbix, because zabbix mappings takes priority.

I think best solution will be an option to disable zabbix value mapping translation on query basis, option to disable it in datasource will also fix this, but It's not flexible enough, also selectable priority (search in grafana and if not found in zabbix mapping) can do the job, but I don't know if it's possible to implement.

Also value mappings in zabbix can be descriptive and long, but in Grafana you want to use simple OK and ALARM mappings, for example for persons on duty, only to indicate problem and long descriptions from zabbix mappings can be unreadable and useless on dashboard.

**Comment by mr-ns** [comment]
+100!!!
This breaks many, many existing dashboards; we definitely need a way to disable this globally (datasource config) with perhaps a per-query setting.

**Comment by serg-ku** [comment]
Totally disabling isn't a good choice. You won't be able to use it in other dashboards, maybe something like "Disable by default" and enable per-query, or disable/enable by default for dashboard and enable/disable per-query

**Comment by mr-ns** [comment]
Agree. There should be a global or "default" setting in the plugin config, which can then be overridden at the query level if so desired.

**Comment by isaqueprofeta** [comment]
@alexanderzobnin this one is pretty high priority. I got myself more than 50 broken dashboards if update.

**Comment by alexanderzobnin** [comment]
I agree, in many cases it breaks user experience. So I'll add switch to the query editor to enable this option, it will be disabled by default.

**Comment by serg-ku** [comment]
@alexanderzobnin will this fix also affect https://github.com/alexanderzobnin/grafana-zabbix/issues/1130 ?

**Comment by alexanderzobnin** [comment]
@serg-ku this only affects value mapping.

**Comment by serg-ku** [comment]
@alexanderzobnin is there any fix planned for https://github.com/alexanderzobnin/grafana-zabbix/issues/1130 or it's not used by anyone?) It's standard grafana functionality)

**Comment by isaqueprofeta** [comment]
Keep issue discussion the the right related issue please
