### ISSUE TITLE
Zabbix Authentication is LDAP

### ISSUE THREAD

**Issue by padilia** [alexanderzobnin/grafana-zabbix#113]
I'm having trouble inherit the group viewing permissions for Zabbix user in Grafana.

When I create the template it shows all groups.

**Comment by alexanderzobnin** [comment]
Can you provide more details, please?

**Comment by padilia** [comment]
I have a Zabbix that has multiple users with different hosts permissions needed inherit these permissions in grafana to view the Dashboards

**Comment by nvtkaszpir** [comment]
Unfortunatelty right now you must set up multiple zabbix users for gafana and then define different data sources in grafana and adjust dashboards to use specific sources to draw data.
