### ISSUE TITLE
Field / Standard options / Display name stopped working in 4.1 release

### ISSUE THREAD

**Issue by serg-ku** [alexanderzobnin/grafana-zabbix#1130]
Field / Standard options / Display name setting is ignored after update to 4.1.1 release and zabbix item name or Transformation name is used as Display name.

Setting:
![image](https://user-images.githubusercontent.com/28900237/103356480-0866d580-4ac2-11eb-96e0-698d5665083c.png)

Item with plugin 4.1.1:
![image](https://user-images.githubusercontent.com/28900237/103356532-26ccd100-4ac2-11eb-9c1f-33fbb846926f.png)

Same item with plugin 4.0.2:
![image](https://user-images.githubusercontent.com/28900237/103356593-49f78080-4ac2-11eb-9f54-b78c2a604938.png)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.6   | 4.4.10  | 4.1.1                 |

**Comment by serg-ku** [comment]
Is there any fix planned for this? This is generic grafana functionality, and it breaks many graphs)

**Comment by alexanderzobnin** [comment]
Got it, caused by `displayName` in field config:
https://github.com/alexanderzobnin/grafana-zabbix/blob/8ef3dc9b9366482728d3bdf0871c15651f29197a/src/datasource-zabbix/responseHandler.ts#L88
