### ISSUE TITLE
Grafana / Maintenance Zabbix

### ISSUE THREAD

**Issue by luedthsa** [alexanderzobnin/grafana-zabbix#1131]
Under normal conditions when referring to maintenance, they are created in zabbix including at least one host or a group of hosts and in the same configuration are set the triggers TAGs that should be omitted in the graphana dashboard, however both in graphana and in zabbix, the host or host group assigned at the beginning of the configuration receives a maintenance tag that is represented by orange pliers, in zabbix when the checkbox for displaying suppressed incidents is not checked, the host alerts that do not have the maintenance tag appear normally, but the host is displayed with the tag of the pliers, when checked it shows all alerts from the host including the alerts of tags under maintenance, however the graphana does not have this same interpretation, and it omits everything that has the pliers or displays everything that has the pliers. Is there a workaround for this?

![image](https://user-images.githubusercontent.com/62388006/103368976-bc0e9c00-4aa7-11eb-9a86-3ea10ad2cbb4.png)
![image](https://user-images.githubusercontent.com/62388006/103368988-c466d700-4aa7-11eb-9f07-c2f2fc3c2826.png)

**Comment by luedthsa** [comment]
![WhatsApp Image 2020-12-29 at 18 36 32](https://user-images.githubusercontent.com/62388006/103359514-d429ef80-4a96-11eb-8e22-32e172620d2f.jpeg)
![WhatsApp Image 2020-12-29 at 18 35 54](https://user-images.githubusercontent.com/62388006/103359519-d55b1c80-4a96-11eb-9f35-61f08890f77e.jpeg)

**Comment by luedthsa** [comment]
![WhatsApp Image 2020-12-29 at 18 36 32](https://user-images.githubusercontent.com/62388006/103359822-5e725380-4a97-11eb-8dbf-dee80a748c80.jpeg)
![WhatsApp Image 2020-12-29 at 18 35 54](https://user-images.githubusercontent.com/62388006/103359824-5fa38080-4a97-11eb-8179-f5e95ecb341b.jpeg)

**Comment by luedthsa** [comment]
![maintenance tag](https://user-images.githubusercontent.com/62388006/103368390-2b838c00-4aa6-11eb-9733-1d92e2d2ff72.png)
![maintenance tag2](https://user-images.githubusercontent.com/62388006/103368393-2c1c2280-4aa6-11eb-9f02-838825469801.png)

**Comment by hudnall-s** [comment]
for anyone else looking for this, I rebuilt the plugin to use the maintenance mode on a problem level instead of a host level.

current as of 2/9/2022 can be found here https://github.com/hudnall-s/Grafana-Zabbix-Plugin

**Comment by alexanderzobnin** [comment]
I think it's a duplicated issue for #830. So closing this.
