### ISSUE TITLE
Unable to init plugin

### ISSUE THREAD

**Issue by cloudybear** [alexanderzobnin/grafana-zabbix#1139]
After installing the plugin via grafana-cli, I can login to grafana ui and enable the plugin. When trying to add zabbix as the datasource. I'm seeing 
![image](https://user-images.githubusercontent.com/28696056/104791077-3e58ba80-574e-11eb-9d83-cb526262ce13.png)

In the logs, I see: 
`t=2021-01-16T00:21:56+0000 lvl=eror msg="Failed to init plugin." logger=plugins error="fork/exec /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64: permission denied" plugin=alexanderzobnin-zabbix-datasource`

I've enabled the plugin logged in as the default admin user and also tried to add `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource` to the grafana.ini and restarted with no resolution.

OS: CentOS 7
Grafana server: v5.4.2
plugin version: 4.0.1

**Comment by alexanderzobnin** [comment]
Latest plugin version only supports Grafana 7.
