### ISSUE TITLE
zabbix plugins won't support zabbix 5.0.3

### ISSUE THREAD

**Issue by Syun91** [alexanderzobnin/grafana-zabbix#1141]
Add data sources ,write url  http://ip/zabbix/api_jsonrpc.php ,and test  Tips：request failed, status: 404 Not Found
this ip's zabbix is 5.0.3
but,use another ip's zabbix ,3.x is ok.

**Comment by binhoul** [comment]
use http://ip/api_jsonrpc.php instead to have a test.
