### ISSUE TITLE
HEATMAP plugin - SLA - Ie.a.round_interval is not a function

### ISSUE THREAD

**Issue by Rudorufu-san** [alexanderzobnin/grafana-zabbix#1144]
Hi, I am using Heatmap plugin for displaying SLA. My settings are Query Mode-IT Services, Property-SLA, also I use Interval-Auto because I need shorter interval than 1h (preferably 5min). Once I set it as AUTO - Interval this error show up: "**Ie.a.round_interval is not a function**". When I use other plugins I get the same error. Data for SLA are collected in Zabbix every 1m. 

Version:
Grafana tested v7.3.7 and 7.3.4
Plugins / Zabbix 4.0.2 and 4.1.1
Heatmap Panel - Native Plugin
Zabbix server 5.0.4 LTE

Ruda

**Comment by alexanderzobnin** [comment]
Duplicated. Fixed in 4.1.2

**Comment by Rudorufu-san** [comment]
Its work. THX.
