### ISSUE TITLE
Triggers panel Item.lastvalue truncated text

### ISSUE THREAD

**Issue by Luckyvb** [alexanderzobnin/grafana-zabbix#1145]
**Is your feature request related to a problem? Please describe.**
Zabbix Problem with triggers truncate text data, look at attachment 1.

**Describe the solution you'd like**
Can add it to **ToolTip** (screenshot 2), or info button to open addition panel with full text. As sample at screenshot, i copy text to title attribute..
As quick, maybe some like: 
At _panel-triggers/components/Problems/ProblemDetails.tsx_
`222: <Tooltip placement="top-start" content={itemName}+"<br/>"+{item.lastvalue}>`
or 
`223: <span className="problem-item-value" title={item.lastvalue}>{item.lastvalue}</span>`

**Alternative solution**
screenshot 3

**Screenshots**
1.![изображение](https://user-images.githubusercontent.com/5268904/105344880-954e0c00-5bf4-11eb-9561-7982d9d440db.png)
2. ![изображение](https://user-images.githubusercontent.com/5268904/105343196-5cad3300-5bf2-11eb-9e02-a27bd75b4742.png).
3. ![изображение](https://user-images.githubusercontent.com/5268904/105344688-561fbb00-5bf4-11eb-9f8b-c382319491d8.png)

**Comment by alexanderzobnin** [comment]
Yes, sounds reasonable, I did the same for the description text.
