### ISSUE TITLE
Plugin unavailable issue

### ISSUE THREAD

**Issue by Galadhar** [alexanderzobnin/grafana-zabbix#1147]
Hello,

I am using:
Grafana 7.3.7 (Windows)
Plugin grafana-zabbix 4.1.1
Zabbix 5.0.4 (CentOS VM)

I have installed the grafana-zabbix plugin on grafana, but when I want to save and test the data source, I have the error message "Plugin unavailable".

I can't find where is the issue in this error message:

Object
status:503
statusText:"Service Unavailable"
data:Object
message:"Plugin unavailable"
config:Object
url:"api/datasources/5/resources/zabbix-api"
method:"POST"
headers:Object
hideFromInspector:false
data:Object
retry:0
message:"Plugin unavailable"

Thanks for your help.

**Comment by alexanderzobnin** [comment]
This is probably duplicates #1033
