### ISSUE TITLE
Panel Zabbix Problems UI problem in v4 

### ISSUE THREAD

**Issue by guliangsi** [alexanderzobnin/grafana-zabbix#1149]
**Describe the bug**
We have noticed a difference in the display of the Zabbix Problems panel.

In Grafana v6.7.4 + Zabbix Plugin 3.12.4, the display is OK

![grafanav674_zabbix_plugins](https://user-images.githubusercontent.com/43655090/106478989-17b6b580-64aa-11eb-8fa9-c1bd74155f04.PNG)

In Grafana v7.3.7 + Zabbix Plugin 4.1.2, the display is OK, however the "previous & next page" part is displayed over the panel when this is minimized.

![grafanav737_zabbix_plugin](https://user-images.githubusercontent.com/43655090/106479030-2604d180-64aa-11eb-8760-9409205f418c.PNG)

I don't know if it's a Grafana v7 bug or Zabbix Plugin v4. Is it possible to have the same behavior as before (in Grafana v6 + Zabbix Plugin v3)?

Thank you
Coridally 

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.7   | 4.0.3  | 4.1.2                 |

**Comment by alexanderzobnin** [comment]
Yes, confirmed. Looks like `overflow: hidden;` on class `ReactTable` fixes this issue.

**Comment by guliangsi** [comment]
Ok, thanks @alexanderzobnin !
