### ISSUE TITLE
Zabbix 2.4.7 / Failed to load resource: the server responded with a status of 412 (Precondition Failed)

### ISSUE THREAD

**Issue by mbuyukkarakas** [alexanderzobnin/grafana-zabbix#115]
Hello Alexander

I have installed a fresh one with ;

Centos 6.7 ; Grafana (latest version) - Grafana zabbix 2.5.1
and Zabbix 2.4.7 on another server.

I cant pass the connection test even I fill the account / pswd information.

I just see a blank page when I try to call the api and after controlling with F12 I just see "Failed to load resource: the server responded with a status of 412 (Precondition Failed)"

But according to your document zabbix version greater than 2.0.x shouldnt have this problem.

Could you help me please ?

Best regards.

**Comment by mbuyukkarakas** [comment]
I made some changes.

First, I dont have a common DNS thats why I edited both servers /etc/hosts files and gave a suffix for each server like ; 192.168.100.110 zabbix01.local 

After restarting grafana server I got new things.

Any idea ?


![capture](https://cloud.githubusercontent.com/assets/15248990/11444878/3e9afcd2-9530-11e5-8df6-386f35011231.JPG)

**Comment by mbuyukkarakas** [comment]
I solved it. After changing from hostname to IP address and removing basic auth it was successfull. I dont understand but its fine.

thank you anyway.

**Comment by alexanderzobnin** [comment]
Are you use Basic auth on Zabbix server?
