### ISSUE TITLE
Explorer Error "Unexpected field length" only with more than one host

### ISSUE THREAD

**Issue by mjtrangoni** [alexanderzobnin/grafana-zabbix#1150]
Hi @alexanderzobnin,

I was using the Grafana explorer and I am facing this issue when querying more than one Host (Regex: `/.*/`). 
With only one host this does not happened at all! And also trying it many times has a rare one time successful response after many tries.

On a successful response I see this warning on explore too,

```
The keyword 'inner-spin-button' specified to an 'appearance' property is not standardized. It will be removed in the future.
```

Let me know if you need more information.

**Expected behavior**
To return Zabbix Data without crashing for more than one host

**Screenshots**
Not applicable.

**Network data**
Explorer query:

```json
{"datasourceId":2,"method":"history.get","params":{"output":"extend","history":"3","itemids":["162257","40721","40651","40686","40756","162352","162387"],"sortfield":"clock","sortorder":"ASC","time_from":1612276691,"time_till":1612280291}}
```

Console Error:
```
datasource.ts:175 Converting response to the wide format
responseHandler.ts:189 Data frames: adding missing points
datasource.ts:175 Converting response to the wide format
actions.ts:524 Error: Unexpected field length
    at a (flotPairs.ts:19)
    at l (getGraphSeriesModel.ts:60)
    at t.T [as project] (decorators.ts:89)
    at t._next (map.js:35)
    at t.next (Subscriber.js:53)
    at t._next (map.js:41)
    at t.next (Subscriber.js:53)
    at t._next (map.js:41)
    at t.next (Subscriber.js:53)
    at t.notifyNext (mergeMap.js:85)
```

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.7   | 4.2.8  | 4.1.2                 |

**Comment by alexanderzobnin** [comment]
Yes, confirmed.

**Comment by EnochTheWise** [comment]
Default Template Module ICMP Ping
Make panel with ICMP response time, add some hosts
Periodically: "Unexpected field length" :o(

Page refresh temporarily helps but... ;o(

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.3.7 | 5.0.8 | 4.1.4
