### ISSUE TITLE
Can't change query mode in Zabbix Problems panel

### ISSUE THREAD

**Issue by timyllym** [alexanderzobnin/grafana-zabbix#1151]
When I edit Zabbix problems panel and try to change the query mode it stays always in "Problems". Is this intended behavior? The selection seems to be overriden in init-function of query.controller.ts

See e.g. https://play.grafana-zabbix.org/d/000000024/problems?orgId=2

![select_query_mode](https://user-images.githubusercontent.com/13029109/106754851-20d48d80-6636-11eb-8b57-2604e833f4b9.gif)

**Comment by alexanderzobnin** [comment]
Hi! This is how this feature supposed to work. Problems panel designed to work only with `Problems` query mode. But you can change visualization and then select another mode.
