### ISSUE TITLE
Date time display issue

### ISSUE THREAD

**Issue by Arkhipov-Oleg** [alexanderzobnin/grafana-zabbix#1152]
In version 4.1.2 I observe bug when date from zabbix value is displaying like: "5.66 day" while should be "5d 15h 43m".
Changing of value units has no effect.

**Comment by alexanderzobnin** [comment]
Hi! Could you explain where exactly you see this? Is it item value? Some screenshots with query editor would be helpful.

**Comment by Arkhipov-Oleg** [comment]
Hi!

Found that it's not a Zabbix Plugin issue.
To convert seconds to duration in Grafana Stat visualization correctly, I choose Reduce" in Transform tab, Mode "Series to row" and Calculation "Last (not null).
Then in Fields tab i choose "duration (d: hh:mm:ss) and now it's all is ok.

Thank you.
