### ISSUE TITLE
Datasource doesn't contain alerting parameters

### ISSUE THREAD

**Issue by kanlas-net** [alexanderzobnin/grafana-zabbix#1158]
**Describe the bug**
Datasource configuration page doesn't have "Alerting" section

**Expected behavior**
"Alerting" section should be presented as [docs said](https://alexanderzobnin.github.io/grafana-zabbix/configuration/)

**Screenshot**
![2021-02-16_15:25:36](https://user-images.githubusercontent.com/16520060/108062856-6c8e2a80-706b-11eb-8e22-17c39fba61ad.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|   7.4.1   |  5.0.8  |      4.1.2                       |

**Comment by pnmice** [comment]
The same problem
on 

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.3.7 | 5.2 | 4.1.2

**Comment by kanlas-net** [comment]
Author answered that this feature was disabled because it conflicts with supporting of grafana alert system
