### ISSUE TITLE
Can't filter Annotation host

### ISSUE THREAD

**Issue by aistiszen** [alexanderzobnin/grafana-zabbix#116]
Hi Alex

I'm having trouble filtering annotations based on the selected host. Works well with $group definition, however nothing works when filtering for host. Any tips or tricks?

![image](https://cloud.githubusercontent.com/assets/2846475/11472860/0da15be0-9778-11e5-8aac-24a0fc83258c.png)

Thanks

**Comment by alexanderzobnin** [comment]
Hi! It looks like a bug. I need to check it.

**Comment by alexanderzobnin** [comment]
Fixed.
