### ISSUE TITLE
Graphs Visualizations Showing Gaps After Update from 4.0.2 to 4.1.2

### ISSUE THREAD

**Issue by n406c** [alexanderzobnin/grafana-zabbix#1161]
**Describe the bug**
After updating both my cloud and on prem zabbix plugin from 4.0.2 to 4.1.2, a one minute random gap is now appearing on the graphs.  Inspecting the data shows random data missing.

**Expected behavior**
Pre update, all graphs were rendering all data points.

**Screenshots**
![Screen Shot 2021-02-18 at 9 15 31 AM](https://user-images.githubusercontent.com/44477185/108387043-74b0ac00-71ca-11eb-8af3-5ff8a50e1548.png)

**Network data**

Object
request:Object
url:"api/tsdb/query"
method:"POST"
data:Object
queries:Array[1]
0:Object
refId:"A"
format:"time_series"
datasourceId:7
rawSql:"SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (183598) AND clock > 1613663901 AND clock < 1613664801 GROUP BY (clock-1613663901) DIV 1, metric ORDER BY time_sec ASC"
maxDataPoints:10000
hideFromInspector:false
response:Object
results:Object
A:Object
refId:"A"
meta:Object
executedQueryString:"SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (183598) AND clock > 1613663901 AND clock < 1613664801 GROUP BY (clock-1613663901) DIV 1, metric ORDER BY time_sec ASC"
rowCount:0
series:Array[1]
0:Object
name:"183598"
points:Array[30]
0:Array[3141696,1613663910000]
1:Array[8338872,1613663940000]
2:Array[2046104,1613663970000]
3:Array[2539488,1613664001000]
4:Array[3455688,1613664030000]
5:Array[3115808,1613664060000]
6:Array[4677304,1613664090000]
7:Array[3283224,1613664120000]
8:Array[3623080,1613664150000]
9:Array[3527784,1613664181000]
10:Array[2732392,1613664210000]
11:Array[10731920,1613664240000]
12:Array[3688488,1613664270000]
13:Array[4051048,1613664300000]
14:Array[3925448,1613664330000]
15:Array[7162408,1613664361000]
16:Array[4936280,1613664390000]
17:Array[6617008,1613664421000]
18:Array[11618008,1613664450000]
19:Array[3599640,1613664480000]
20:Array[3490800,1613664510000]
21:Array[6085904,1613664541000]
22:Array[3649960,1613664570000]
23:Array[3254600,1613664601000]
24:Array[5698512,1613664630000]
25:Array[3037088,1613664660000]
26:Array[3365144,1613664690000]
27:Array[2300376,1613664720000]
28:Array[3317320,1613664750000]
29:Array[4180984,1613664780000]
tables:null
dataframes:null

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.4.1-7.4.2  | 5.0.8  | 4.1.2 |

**Comment by superguillen** [comment]
Same problem when upgrade plugin to 4.1.2, downgrade to 4.0.1 is workarround

**Comment by borjasueiro** [comment]
+1

**Comment by atelleira** [comment]
+1

**Comment by msantpine** [comment]
+1

**Comment by fcollado** [comment]
Same problem here, and the change also generated the same log errors as those described in  #1157

**Comment by alexanderzobnin** [comment]
This behaviour now enabled by default in order to keep compatibility with changes in Grafana stacking graphs. Howewer, you can disable it in query options or globally in data source config by switching `Disable data alignment` option:

![Screenshot from 2021-03-05 11-31-53](https://user-images.githubusercontent.com/4932851/110089037-ad45ad80-7da6-11eb-9771-15f3afb5f27e.png)

**Comment by iprok** [comment]
Hello @alexanderzobnin . I have just met the issue and turning on "Disable data alignment" helped. But I'm totally confused trying to get how the only few affected graphs in our grafana differ from plenty of others (all from zabbix). Can you provide a little bit more details on what graphs it may happen and why and what problems with stacking graphs can we get if we turn on this option globally?
