### ISSUE TITLE
Unable to change units

### ISSUE THREAD

**Issue by zeppmg** [alexanderzobnin/grafana-zabbix#1165]
Hi,

**Describe the bug**
I'm retreiving existing stats on Zabbix server in order to display them in Grafana (download speed for web scenario). Given item is expressed in Bytes/seconds in Zabbix. Default unit in Grafana is Bytes/sec (IEC). I'd like to see it in bits/sec (SI).  But when I change the units, it doesn't show on the graph.

**Expected behavior**
When i change from Bytes/sec (IEC) to Bytes/sec (SI), then either Save or Apply or both, the graph remains the same.
When i change from Bytes/sec (IEC) to Bits/sec (IEC) or (SI), the graph still remains the same.
If i apply an 8-scale, values are correctly multiplied by 8. But unit still remains the same.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| -------- | ------- | ---------------------- |
| 7.3.7     | 4.0.3    | 4.1.2                           |

Thanks in advance.

**Comment by k-korn** [comment]
+1 on this.
in Zabbix, I have a metric with with unit set to "m" meaning distance, meters.
However, Grafana Zabbix Plugin treats them as "Minutes" and does not let change it.

**Comment by alexanderzobnin** [comment]
Since now units provided through the data frames, it can be changed by overrides:

![Screenshot from 2021-03-05 11-40-27](https://user-images.githubusercontent.com/4932851/110089914-bc792b00-7da7-11eb-8eb1-c2c87f0ad47d.png)
