### ISSUE TITLE
Use of variables + own text in queries

### ISSUE THREAD

**Issue by MAGICCC** [alexanderzobnin/grafana-zabbix#1166]
Hello,

I am facing some problem, not sure if and how I can get it working.

Let's suppose I have a variable called '$item' which returns '1' + '3' and my items are called like following:
```
server1_vm1
server1_vm2
server1_vm3
server3_vm1
server3_vm2
server3_vm3
```

Is it possible to use in a query in the item field something like `server$item_vm1`, so I can use the dropdown of the variable to switch between server1 and server3?
Everytime I add something to $item the text will turn to white instead of blue indicating a wrong entry

**Comment by kanlas-net** [comment]
/server$item_vm1/ should work

**Comment by MAGICCC** [comment]
> 
> 
> /server$item_vm1/ should work

No doesn't work, only returns 'No data' using Stat visualization

**Comment by MAGICCC** [comment]
Ah it's `/server($item)_vm1/`
