### ISSUE TITLE
invalid language tag: "en;q=0.5"

### ISSUE THREAD

**Issue by rostwald** [alexanderzobnin/grafana-zabbix#1175]
**Describe the bug**
Installed grafana7 on FreeBSD 12.2-RELEASE from packages, configured the bare basics (domain, database), installed grafana-zabbix via grafana-cli and enabled it as described in the documentation.

Upon adding the zabbix datasource I get an error message on top of the page:

`invalid language tag: "en;q=0.5" Evaluating https://grafana.thu.de.rostwald.de/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module`
`Data Source Error`

The datasource is still added but can't be configured (same error when clicking on the Datasource) or deleted (Error: Missing valid datasource id)

Trying to set "rendering_language" in grafana.conf and/or setting the HTTP Accept Language Header (proxy_set_header Accept-Language) via the Nginx reverse-proxy running in front of grafana doesn't affect the error. (it gets overridden somewhere else?)

**Expected behavior**
The configuration for the zabbix datasource is shown

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.4 | 5.0.9  | 4.1.4                 |

**Comment by alexanderzobnin** [comment]
Hi! Unfortunately, FreeBSD is [not supported](https://grafana.com/docs/grafana/latest/installation/requirements/) by Grafana, so I have no idea why that error may happen.
