### ISSUE TITLE
Zabbix API request error

### ISSUE THREAD

**Issue by nlgnathan** [alexanderzobnin/grafana-zabbix#1179]
Hi im experiencing issue when i add zabbix as datastore in grafana.

I tried in 3 different PCs but still no idea whats wrong

I use grafana in windows.

Thanks

t=2021-03-18T18:45:34+0700 lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="Post \"http://127.0.0.1/zabbix/api_jsonrpc.php\": dial tcp 127.0.0.1:80: connectex: No connection could be made because the target machine actively refused it."
t=2021-03-18T18:45:34+0700 lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="Post \"http://127.0.0.1/zabbix/api_jsonrpc.php\": dial tcp 127.0.0.1:80: connectex: No connection could be made because the target machine actively refused it."
t=2021-03-18T18:45:34+0700 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
t=2021-03-18T18:45:34+0700 lvl=warn msg="Failed to close stream" logger=plugins.backend err="cannot close a closed stream"
t=2021-03-18T18:45:34+0700 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/1/resources/zabbix-api status=500 remote_addr=[::1] time_ms=2129 size=205 referer=http://localhost:3000/datasources/edit/1/
t=2021-03-18T18:45:34+0700 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/1/resources/zabbix-api status=500 remote_addr=[::1] time_ms=2140 size=205 referer=http://localhost:3000/datasources/edit/1/

**Comment by alexanderzobnin** [comment]
I guess the API URL is wrong.
