### ISSUE TITLE
Multiple hosts on one panel: Error "Unexpected field length"

### ISSUE THREAD

**Issue by EnochTheWise** [alexanderzobnin/grafana-zabbix#1180]
Problem
Zabbix: i'm use default Template Module ICMP Ping with some hosts
Grafana:
Make new panel
Add hosts:

1. Query Mode: Metrics
2. Group: some group
3. Host: some host
4. Application: Status
5. Item: ICMP response time
6. Function: setAlias(<hostname>)

After adding some number(ex. 3-5) of hosts, I get the error: "Unexpected field length"

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.7   | 5.0.8  | 4.1.4                 |

**Comment by alexanderzobnin** [comment]
@EnochTheWise could you check it against the latest version and close if it's fixed?

**Comment by EnochTheWise** [comment]
When testing for an hour, there were no problems!
Thx!

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.3   | 5.0.8  | 4.2.3                 |
