### ISSUE TITLE
Panel Zabbix Problems: duplicate problem names

### ISSUE THREAD

**Issue by aquamanrus** [alexanderzobnin/grafana-zabbix#1181]
**Describe the bug**
When in trigger configuration is used the multiple event generation mode the "Zabbix Problems" panel displays all problems with the same (latest event) names

**Expected behavior**
All problems displays with original names

**Screenshots**
zabbix:
trigger configuration
![trigger_config_001](https://user-images.githubusercontent.com/81362526/112467961-c07de480-8d78-11eb-8822-b4fd3af6c5fb.jpg)

problems dashboard
![zabbix_events_001](https://user-images.githubusercontent.com/81362526/112466283-bce95e00-8d76-11eb-865a-ce3bc944cdcc.jpg)

grafana:
![grafana_panel_001](https://user-images.githubusercontent.com/81362526/112466277-bbb83100-8d76-11eb-9f46-d5242f33804f.jpg)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.4.5   | 4.0.29  | 4.1.4                 |

**Comment by alexanderzobnin** [comment]
Probably, the same as #1041
