### ISSUE TITLE
The datasource does not support alerting queries

### ISSUE THREAD

**Issue by nyukers** [alexanderzobnin/grafana-zabbix#1186]
Настроил канал уведомлений в Grafana. Использую плагин Zabbix для получения данных.
При попытке создания алерта на графике получаю "The datasource does not support alerting queries".
Где может быть проблема?

I set up a notification channel in Grafana. I am using the Zabbix plugin to get data.
When I try to create an alert on the any chart, I get "The datasource does not support alerting queries".
Where could the problem be?

**Comment by nyukers** [comment]
Плагин не имеет обратной связи?

**Comment by alexanderzobnin** [comment]
Hi! Probably, you use old plugin version, alerting is only supported since 4.0.
https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v4.0.0
