### ISSUE TITLE
Zabbix 5.4: method not found. Incorrect API "application"

### ISSUE THREAD

**Issue by mglennon** [alexanderzobnin/grafana-zabbix#1188]
**Describe the bug**
I began rebuilding my Zabbix/Grafana monitoring again from scratch (I wanted to start over) using Docker containers.
I had everything functional and suddenly Grafana won't display some values on a Dashboard with error `Incorrect API "application".` I haven't been able to narrow down exactly why some values will display and some wont.
I went so far as to start over with Grafana in case I I'd caused the issue but a fresh installation of Grafana and the plugin result in the same issue.

**Expected behavior**
Grafana should show all widgets.

**Screenshots**
Non-functional default Zabbix Dashboard
![Screen Shot 2021-04-15 at 14 27 27](https://user-images.githubusercontent.com/5652065/114920236-395fe180-9df7-11eb-99a4-020545db3239.png)
Error from non-functional default Zabbix Dashboard
![Screen Shot 2021-04-15 at 14 33 31](https://user-images.githubusercontent.com/5652065/114920596-98255b00-9df7-11eb-8dc5-e6621a0658d7.png)
Other default dashboard still functional: (Github won't let me upload it for some reason)
https://imgur.com/a/llyY3Kp

**Network data**
`{"datasourceId":1,"method":"application.get","params":{"output":"extend","hostids":[]}}`

`{"error":"Internal Server Error","message":"Method not found. Incorrect API \"application\"."}`

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.5.4   | 5.4.0rc1  | 4.1.4                 |

**Comment by mglennon** [comment]
To be clear, I'd spent all day yesterday building a dashboard with various data on it and everything functioned fine. Near the end of that work while I was editing a widget I started receiving this error and I haven't been able to figure out what is causing it.

**Comment by alexanderzobnin** [comment]
I checked the latest Zabbix API docs and `application.get` seems to be there. So I guess it's Zabbix bug (rc1 is not a stable version, so this is more than probable).

**Comment by i-ky** [comment]
@alexanderzobnin, it's not a bug, it's a feature: [ZBXNEXT-2976](https://support.zabbix.com/browse/ZBXNEXT-2976). Likely [changes](https://git.zabbix.com/projects/ZBX/repos/zabbix/commits/c655ede26163dc587dd124449ec4061b5b3066b8) have not been documented yet. But it's clear that [applications are gone](https://support.zabbix.com/browse/ZBXNEXT-2976?focusedCommentId=480269&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-480269).

**Comment by catmater** [comment]
Confirm, critical implementing from Zabbix, breaking this plugin completely.

**Comment by TheCoolOne123** [comment]
Anyone got any pointers how to downgrade zabbix? Through apt or something

**Comment by i-ky** [comment]
@TheCoolOne123, it is not possible if you don't have DB backup. During major upgrades Zabbix server and proxies apply database upgrade patches which are irreversible. You can downgrade Zabbix server binary through package manager like you usually do, but it will likely complain about DB version mismatch.

**Comment by TheCoolOne123** [comment]
Any pointers on that, i've not been sucessfull going back to 5.3-beta2

**Comment by alexanderzobnin** [comment]
It looks like `application` API was deleted in 5.4 https://support.zabbix.com/browse/ZBXNEXT-2976

**Comment by catmater** [comment]
Yes, and long time ago. Now Zabbix 5.4.0 Beta 3 are so-so stable build, but this "improvement" completely break you great plugin functionality. And no way to downgrade Zabbix (only revert to backup dump of mysql base). 
 
<img width="525" alt="image" src="https://user-images.githubusercontent.com/48475912/116787079-bf904f00-aaaa-11eb-9f67-ba0b24eb6072.png">

**Comment by i-ky** [comment]
> Yes, and long time ago.

..and in 100% secrecy. Zabbix does not share design documents and still has not updated documentation ([proof](https://www.zabbix.com/documentation/5.4/manual/api/reference/application)). Please understand that @alexanderzobnin  can't start working on the fix before new API is documented. I encourage you to contact Zabbix and share your opinion on their policies.

**Comment by mglennon** [comment]
Thanks for the replies, everyone - I'm sort of glad it isn't just me - I thought I was going crazy.
I appreciate your work, @alexanderzobnin - I eagerly but patiently await your fix [for Zabbix's trash fire.]

cheers!

**Comment by catmater** [comment]
Zabbix 5.4.0-0.7rc1 - the same error.

**Comment by catmater** [comment]
Grafana 8.0.0 beta1  and Zabbix 5.4.0 0.8rc2 - Error still exist.

**Comment by GregoryOrciuch** [comment]
Hi, now the stuff it's gonna explode. I stepped into this bug because my automatic docker script upgraded today to zabbix to 5.4 .
Shame on zabbix to release undocumented changed which brakes backward compatibility.

**Comment by mglennon** [comment]
Welcome to the party, everyone. Have some popcorn while we wait for Zabbix.

**Comment by i-ky** [comment]
Well, at least changes are documented now:
* [Upgrade Notes](https://www.zabbix.com/documentation/current/manual/installation/upgrade_notes_540#item_tags_have_replaced_applications)
* [API Changes](https://www.zabbix.com/documentation/current/manual/api/changes_5.2_-_5.4#application)
* [Item Tag](https://www.zabbix.com/documentation/current/manual/api/reference/item/object#item_tag)

**Comment by roysbike** [comment]
Zabbix 5.4.0 Error still exist.(

**Comment by GregoryOrciuch** [comment]
Not sure if known, but I discovered a hack in Grafa  to resurrect broken graphs. You edit your graph and then remove the content of "Application" field, leaving the item and the rest of them untouched, then it started to present graph. Discovered accidentialy because one of graphs had the application field empty and that one worked well after zbx 5.4.0 kicked in yesterday.
[Link to evidence.](https://imgur.com/a/Vz1YKey)

**Comment by mfitzgerald2** [comment]
I can confirm this workaround works, I am running zabbix 5.4.0 and Grafana v7.4.2. You still get the "Method not found. Incorrect API "application"." error but at least you can see the data!

**Comment by StefanSa** [comment]
privjet @alexanderzobnin 
thanks for the quick fix, but the error has not yet been completely resolved (please reopen this Ticket).
Now i get all values again, but i get this error message when I refresh.
![Ohne Titel 6](https://user-images.githubusercontent.com/6105075/118772438-09877c00-b884-11eb-8328-49f41bfc8e71.png)
![Ohne Titel 6](https://user-images.githubusercontent.com/6105075/118773128-cb3e8c80-b884-11eb-8531-684bcaa5be57.png)

**Comment by alexanderzobnin** [comment]
@StefanSa you obviously cannot use Applications since it were removed in Zabbix. This is only compatibility fix, Applications will be replaced by tags in next plugin release.

**Comment by StefanSa** [comment]
Spasibo @alexanderzobnin
thank you for the clarification

**Comment by brunoscota** [comment]
Thank you @alexanderzobnin. I'm also waiting for this.

**Comment by tomukasteris** [comment]
I did update plugin to the latest version but still doesn't work.

**Comment by tomukasteris** [comment]
I have managed to fix by deleting data source and adding again with the same name.

**Comment by muhammadanees83** [comment]
> Not sure if known, but I discovered a hack in Grafana to resurrect broken graphs. You edit your graph and then remove the content of "Application" field, leaving the item and the rest of them untouched, then it started to present graph. Discovered accidentialy because one of graphs had the application field empty and that one worked well after zbx 5.4.0 kicked in yesterday.
> [Link to evidence.](https://imgur.com/a/Vz1YKey)

thanks bro..... this trick is  working

**Comment by joachim-vertommen** [comment]
> 
> 
> @StefanSa you obviously cannot use Applications since it were removed in Zabbix. This is only compatibility fix, Applications will be replaced by tags in next plugin release.

Hello, do you have an estimate when the next plugin release will arrive?
For us this is a blocking factor at the moment to upgrade Zabbix because it will break our Grafana graphs completely.

Thanks.

**Comment by akibukis** [comment]
Zabbix 5.4.2 on Ubuntu 20.10, Grafana v8.0.5 (cbb2aa5001.

Same problem: 
Method not found. Incorrect API "application".

Are there any plans to finally fix this? It breaks many Grafana dashboards. :/

**Comment by akibukis** [comment]
UPDATE: 

Upgraded alexanderzobnin-zabbix-app to v4.1.5 in Grafana and everything works without any problems!
Thank you, guys!

**Comment by akibukis** [comment]
UPDATE #2

Although all of my Grafana panels/graphs work, I am unable to query 'Application' items:

![image](https://user-images.githubusercontent.com/1809502/126034175-6f0b922b-1722-4250-a339-2afb9ec5b6bb.png)

**Comment by i-ky** [comment]
@akibukis, see https://github.com/alexanderzobnin/grafana-zabbix/issues/1188#issuecomment-844095602
