### ISSUE TITLE
Proxy mode is malfunction

### ISSUE THREAD

**Issue by ethinx** [alexanderzobnin/grafana-zabbix#119]
Hi,

Just download the latest version and setup well. However, when I want to use proxy mode, get error message:

```
Connection failed
Could not connect to /api/datasources/proxy/2
```

In console, see the `error.config.url` is `/api/datasources/proxy/2` not the HTTP API I set on the panel. 

and `error.data` is the Nginx 404 page:

```
"<html>
 <head><title>404 Not Found</title></head>
 <body bgcolor="white">
 <center><h1>404 Not Found</h1></center>
 <hr><center>nginx</center>
 </body>
 </html>
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 "
```

what I thought is the request is sent to the real zabbix server, but the request URL is incorrect.

So I hard code the real API addr into `datasource.js`, then the connection test pass:

```
 23     function ZabbixAPIDatasource(datasource) {
 24       this.name             = datasource.name;
 25       this.url              = datasource.url;
 26       //this.url              = 'http://192.168.1.8/api_jsonrpc.php';
```

Not sure where problem is.

**Comment by alexanderzobnin** [comment]
Hi! Is Direct mode works properly?

**Comment by ethinx** [comment]
Yes, the Direct mode works properly.

More specific:

The zabbix and grafana are built with official docker, and I can access them with IP, e.g. `10.0.0.3` and `10.0.0.4` respectively, also they can communicate with each other through the internal docker network, `172.17.0.0/16`.

So in direct mode, it works with the api address` http://10.0.0.3/api_jsonrpc.php`. But in proxy mode, use `http://172.17.0.3/api_jsonrpc.php` instead, it failed.

**Comment by alexanderzobnin** [comment]
You can leave http://10.0.0.3/api_jsonrpc.php in proxy mode and try again.   
Proxy mode just sends API requests via grafana-server.

```
-----------
| Grafana | ------------------------
-----------                        |
     |                             |
    proxy                        direct 
    mode                         mode
     |                             |
     V                             V
------------------            ----------
| grafana-server | --proxy--> | zabbix |
------------------   mode     ----------
```

**Comment by endzyme** [comment]
Same problem: 

I get the following when "test"ing the connection. 
```Connection failed
Could not connect to /api/datasources/proxy/2
```

**Comment by ethinx** [comment]
```
                                            +-----------------+
                                            |                 |
                                            |  +-----------+  |
+-------------+     +------------------+    |  |  zabbix   |  |
|             |     |                  |    |  +-----------+  |
| Workstation +---->+ VPN/Reverse Proxy+---->                 |
|             |     |                  |    |                 |
+-------------+     +------------------+    |  +-----------+  |
                                            |  |  Grafana  |  |
                                            |  +-----------+  |
                                            |                 |
                                            +-----------------+

```

The topology like this, the `10.0.0.0/8` network is assigned by VPN, it's not owned by the grafana or zabbix container/server/network, so neither grafana not zabbix don't know anything about the network `10.0.0.0/8`. Grafana can't proxy/access the VPN network.

In conclusion, it would be failed definitely if I leave `http://10.0.0.3/api_jsonrpc.php` in proxy mode.
