### ISSUE TITLE
grafana zabbix data source error

### ISSUE THREAD

**Issue by chajinkwnag** [alexanderzobnin/grafana-zabbix#1195]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![캡처](https://user-images.githubusercontent.com/83193156/116016809-b81b1100-a678-11eb-84d7-1fa90ab9d6c0.JPG)

Hi

A data source error occurred while interworking with zabbix and grafana. Is it possible to solve it?

grafana ver - 6.7.3-1

**Comment by alexanderzobnin** [comment]
That's compatibility issue - upgrade your grafana or try older plugin version.

**Comment by chajinkwnag** [comment]
> That's compatibility issue - upgrade your grafana or try older plugin version.

How do I install older plugin versions?
