### ISSUE TITLE
Zabbix 5.4.0 Support with new tag "Application".

### ISSUE THREAD

**Issue by catmater** [alexanderzobnin/grafana-zabbix#1197]
After upgrade Zabbix server from 5.2.4 to 5.4.0 beta3, got error (Method not found. Incorrect API "application") on all dashboard with datasource Zabbix server: 

t=2021-04-28T10:14:58+0300 lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="Method not found. Incorrect API \"application\"."
t=2021-04-28T10:14:58+0300 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=api method=POST path=/api/datasources/5/resources/zabbix-api status=500 remote_addr=xxx.xxx.xxx.xxx time_ms=40 size=94 referer="https://grafana.xxxxxxxxxxxxx.xx/d/FMVPlvuZz/right-panel?orgId=1&refresh=1m

I think, because new tag in Zabbix 5.4.0 : application 
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/48475912/116364745-314b6d00-a80d-11eb-9bb6-d32cd5e03959.png">

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|  7.5.4  |  5.4.0beta3  | 4.1.4                 |

**Comment by TheCoolOne123** [comment]
I can confirm this is happening!

**Comment by i-ky** [comment]
Duplicates #1188.

**Comment by TheCoolOne123** [comment]
Even though it's a duplicate, it's a plugin breaking change. It's better if there is a change made as soon as possible

**Comment by alexanderzobnin** [comment]
Closed in favor of #1188
