### ISSUE TITLE
Forward Grafana Authentication to DataSource?

### ISSUE THREAD

**Issue by JSuenram** [alexanderzobnin/grafana-zabbix#1198]
Is it possible to user the same credentials which are used to logon to Grafana-Webfrontend as "pass-through"-Authentication to Zabbix Datasource-Plugin? 
Reason is, to use the same datasource and Grafana-web for multiple Customers without having to copy the Dashboards over and over again to different Companys in Grafana itself.

**Comment by alexanderzobnin** [comment]
Hi! This is not possible now.
