### ISSUE TITLE
Timeseries downsampling

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#12]
Downsample series for better graph displaying.

**Comment by nucleusv** [comment]
What does it mean ?

**Comment by alexanderzobnin** [comment]
From InfluxDB datasource help:
> **Group by time**
>    Group by time is important, otherwise the query could return many thousands of datapoints that will slow down Grafana
>   * Leave the group by time field empty for each query and it will be calculated based on time range and pixel width of the graph
>   * If you use fill(0) or fill(null) set a low limit for the auto group by time interval
>   * The low limit can only be set in the group by time option below your queries
>   * You set a low limit by adding a greater sign before the interval
>   * Example: >60s if you write metrics to InfluxDB every 60 seconds
