### ISSUE TITLE
Show disabled hosts

### ISSUE THREAD

**Issue by galindro** [alexanderzobnin/grafana-zabbix#120]
@alexanderzobnin is it possible to show graphs for disabled hosts? I've build a script (called as_zabbix) that auto-registers amazon autoscaling hosts in zabbix (https://github.com/galindro/galintools). I'm providing an update to it until the end of the current week. This update will change the script's behaviour: instead of deleting the hosts from Zabbix that isn't found on AWS Autoscaling Groups, it will disable all of them. It will only delete them based on an autoscaling tag which contains the number of days to keep the hosts in zabbix. For doing this, the number of days will be compared with a host macro called CREATION_DATE that is assigned to each recently created host.

But, when the hosts are disabled in zabbix, grafana doesn't shows the graphs of their items. Is it possible to add an option to grafana that, when it is checked, it shows the disabled hosts information?

**Comment by alexanderzobnin** [comment]
Yes, it's possible.

**Comment by galindro** [comment]
Nice @alexanderzobnin. Thank you very much. I'll wait for updates about this feature request

**Comment by volter** [comment]
Isn't this pretty much the same as #97?
