### ISSUE TITLE
ZABBIX PLUGIN - GRAFANA RUNNING ON FREEBSD

### ISSUE THREAD

**Issue by juaromu** [alexanderzobnin/grafana-zabbix#1203]
**Describe the bug**
Plugin signature is invalid after compiling plugin for FreeBSD and including file in Zabbix plugin folder and Manifest.
Zabbix plugin, if installed via Ggrafana CLI, doesn't include binary for BSD.
I complied the plugin and placed it in Grafana's plugin folder + modified manifest to include the new file and its checksum but that makes the manifest itself invalid and the Zabbix plugin is flagged as "Invalid signature" in Grafana 

**Expected behavior**
Zabbix plugin available for FreeBSD systems.

**Screenshots**

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.5.1   | 5.0  | 4.1.4                 |

**Comment by denisgolius** [comment]
> **Describe the bug**
> Plugin signature is invalid after compiling plugin for FreeBSD and including file in Zabbix plugin folder and Manifest.
> Zabbix plugin, if installed via Ggrafana CLI, doesn't include binary for BSD.
> I complied the plugin and placed it in Grafana's plugin folder + modified manifest to include the new file and its checksum but that makes the manifest itself invalid and the Zabbix plugin is flagged as "Invalid signature" in Grafana
> 
> **Expected behavior**
> Zabbix plugin available for FreeBSD systems.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Network data**
> If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)
> 
> **Software versions**
> Grafana 	Zabbix 	Grafana-Zabbix Plugin
> 7.5.1 	5.0 	4.1.4

I have the same issue on ubuntu 20.04 LXC, but I think that the problem is issued by Grafana version and not with plugin version.

**Comment by mircsicz** [comment]
Same here, on a TrueNAS Jail, compiled it myself but getting the

`Plugin not found, no installed plugin with that id
`
Error
