### ISSUE TITLE
Different collection intervals compatibility in Grafana 7.5.5

### ISSUE THREAD

**Issue by bojankezele** [alexanderzobnin/grafana-zabbix#1211]
**Describe the bug**
With Grafana 7.5.5 version, stacking option with Graph visualization is not working properly with different metric collection intervals.

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/79632099/117978669-6b9b2b00-b332-11eb-9a8b-8191aa0cec2c.png)

Screenshot of expected behavior
![image](https://user-images.githubusercontent.com/79632099/117978735-7a81dd80-b332-11eb-97af-414595579451.png)

There's a workaround to use `groupBy(5m, avg)` to group all metrics with 5 minutes interval.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.5.5  | x.x.x  | 4.1.4                 |

**Comment by alexanderzobnin** [comment]
Unfortunately, there's no easy solution for this problem, so moving the next release. The best way top fix it - add interpolation, but it's a bit tricky, and this release contains lots of changes, so dont want to add more complexity right now.

**Comment by k-korn** [comment]
I also have a use case affected by this issue: data is sent to Zabbix by external hardware sensors, at flexible intervals not controllable by Zabbix (but by these sensors).  
If sensor value does not change, they send it to Zabbix every 15 minutes. But once the value starts to change, that interval can go down  to 5 seconds, or be an arbitrary value in between 5 seconds and 15 minutes. So trying to align all values to some set interval will not work, as there is no common update interval.

**Comment by alexanderzobnin** [comment]
@k-korn yes, in this case I decided to perform it in a bit different way. I use interpolation (which original stacking algorithm used in Grafana) to find all common points and prepare series for proper stacking. This is an example of how it works:

Original Zabbix data:
![Screenshot from 2021-09-15 13-51-53](https://user-images.githubusercontent.com/4932851/133442616-e68cd5e8-d0cc-464d-92b9-6dc4a862cd6a.png)

Prepared for stacking:
![Screenshot from 2021-09-15 13-52-01](https://user-images.githubusercontent.com/4932851/133442743-c37021fa-5552-44b5-b237-ac02184bf2ce.png)

**Comment by alexanderzobnin** [comment]
Closing this again since it's fixed by fcef21b0fbea411e574c4193405b05f7aa8b4710
