### ISSUE TITLE
Zabbix upgrade 5.4 breaks grafana

### ISSUE THREAD

**Issue by ablecable** [alexanderzobnin/grafana-zabbix#1213]
In the default dashboards there is an error: "Method not found. Incorrect API "application".

**Comment by i-ky** [comment]
Duplicates #1188.

**Comment by StefanSa** [comment]
privjet @alexanderzobnin
same problem here, please for a quick fix.

**Comment by Scorplionn** [comment]
+
Please fix

**Comment by alexanderzobnin** [comment]
Closed in favor of #1188
