### ISSUE TITLE
Unit doesn't match with Zabbix

### ISSUE THREAD

**Issue by carlosleoliveira** [alexanderzobnin/grafana-zabbix#1215]
I was looking on the issue #1165 and I have a similar problem. My Zabbix is showing the unit values in MB and matching with the Grafana unit values in MiB. When I do the override in Grafana to bytes(SI) the value change and is different from Zabbix. Sometimes is higher sometimes is lower. There is a way to fix this? 

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 7.5.6  | 5.0.1  | 4.1.5 |

**Comment by alexanderzobnin** [comment]
This can be done in the _Overrides_:

![Screenshot from 2021-05-20 09-43-17](https://user-images.githubusercontent.com/4932851/118931555-dad6d780-b94f-11eb-83ab-eae73fc72165.png)

**Comment by carlosleoliveira** [comment]
Even with Overrides is still wrong:

![image](https://user-images.githubusercontent.com/60003832/118976152-16bb6e00-b94b-11eb-85c3-3dcdbc4a278c.png)

After the Override the value change. In Zabbix is 12TB and not TiB but the Override change the value for more. That is my question, why I can't get the same value that I am seeing in Zabbix?

![image](https://user-images.githubusercontent.com/60003832/118976679-a6f9b300-b94b-11eb-92ea-4085a8273166.png)

![image](https://user-images.githubusercontent.com/60003832/118976245-3357a600-b94b-11eb-9c9b-1ee7b7bff912.png)

**Comment by i-ky** [comment]
@carlosleoliveira,  I guess Zabbix'es `TB` are normal person's `TiB`, see [ZBXNEXT-954](https://support.zabbix.com/browse/ZBXNEXT-954).
