### ISSUE TITLE
Triggers panel showing wrong date and time.

### ISSUE THREAD

**Issue by galindro** [alexanderzobnin/grafana-zabbix#122]
@alexanderzobnin is it possible to add a checkbox to the triggers panel to show only the most recent event of each trigger? This is necessary when there are many events from the same trigger because each event consumes one line from the table. If there are 6 events from one trigger, for example, and we set a limit to 10 events, the table could hide important trigger events.

**Comment by alexanderzobnin** [comment]
Hm... I implemented trigger panel like Zabbix "last 20 issues" panel - it must show only last event for each trigger. Which Zabbix version you use?

**Comment by galindro** [comment]
Zabbix server version: 2.4.6
Grafana version: 2.5.1-zbx.pre.9

This is a print from grafana:

![image](https://cloud.githubusercontent.com/assets/4622097/11742021/dfeb91ba-9fe3-11e5-9599-98365ece9763.png)


These are the events from Zabbix:
![image](https://cloud.githubusercontent.com/assets/4622097/11741999/bea0c926-9fe3-11e5-8c77-8c6bbb1879ff.png)


You could see a bug with the date too...

**Comment by alexanderzobnin** [comment]
Why triggers have different names? Can you provide raw trigger description?

**Comment by galindro** [comment]
Hmmmm You are right! Those are really differents. Each one corresponds to a php-fpm process. I'm using my template to monitor in detail all php-fpm processes from my web servers: https://github.com/galindro/zabbix-enhanced-templates

I'm sorry. That went unnoticed...

But some dates are wrong. Could you fix that? Is it better to open another issue for that?

**Comment by alexanderzobnin** [comment]
Yes, dates look horrible. Can you provide more info about it - timezones on Zabbix server and your local machine (where grafana frontend running).

**Comment by galindro** [comment]
Booth are running on the same machine. The timezone is UTC and the locale is en_US.UTF-8

```bash
root@SV-ZABBIX:~# date
Fri Dec 11 11:04:18 UTC 2015

root@SV-ZABBIX:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

root@SV-ZABBIX:~# uname -a
Linux SV-ZABBIX 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

root@SV-ZABBIX:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

root@SV-ZABBIX:~# dpkg -l | egrep 'zabbix-server|grafana'
ii  zabbix-server-mysql              1:2.4.6-1+trusty                        amd64        network monitoring solution - server (using MySQL)
ii  grafana                          2.5.1-zbx.pre.9                         amd64        Grafana
```

**Comment by alexanderzobnin** [comment]
Looks like Age have an 1 hour difference from Last change...

**Comment by galindro** [comment]
My browser is UTC-2 (BRST). Here in Brazil is summer, so we are under daily saving time.
The grafana and zabbix server is UTC
The monitored server is UTC too

```bash
root@SV-V3-API-i-1d46c3ff:~# date
Fri Dec 11 11:41:30 UTC 2015
```

**Comment by jeftedelima** [comment]
Fala Galindro , estou querendo extrair relatorios das triggers ( identico a imagem que vc postou pelo filtro de triggers ) para saber por dia/semana quais equipamentos acionaram mais triggers , com grafana eh possivel isso ? se sim como faço ?

Sou novo no github , como faço pra lhe enviar msg privada ?

**Comment by galindro** [comment]
@jeftedelima use o menu Reports do Zabbix. Veja se nele vc tem o que precisa. Com o grafana isso só seria possível por meio de annotations: https://github.com/alexanderzobnin/grafana-zabbix/wiki/Usage#annotations, mas não sei se serviria para o seu propósito. Sugiro avaliar tb o zabbix-extras: http://spinola.net.br/blog/

Qqr dúvida, mande um e-mail pra mim: bruno.galindro@gmail.com. Não responda mais neste post por favor.

**Comment by jeftedelima** [comment]
Já instalei zabbix extra , e o grafana , pensei que algum tivesse o que 
eu preciso ...

No momento eu possuo 400 equipamentos ( de radio  , provedor de internet )
Gostaria de fazer relatorios com equipamentos que mais ( acionam 
triggers , incidentes ) com isso saberiamos onde temos mais problemas de 
RESTART ( uptime ) PING ( perda de respostas ) LATENCIA ( demorando mt a 
responder ) pra por fim começar a monitorar clientes finais atraves de 
interfaces pppoe !

De momento queria mesmo era gerar relatorios como no exemplo TOP 100 
triggers , pegar por exemplo : SEMANAL o TOP TRIGGERS UPTIME ou PING que 
seja !

Em 14-12-2015 07:08, Bruno Galindro da Costa escreveu:

**Comment by alexanderzobnin** [comment]
Date and time now handled by moment.js library.
