### ISSUE TITLE
Direct DB connection - No data in Grafana 8.0

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#1221]
**Describe the bug**
No data returned for queries when Direct DB connection enabled. This bug appears in Grafana 8.0.

Probably, something was changed in the SQL data sources response format, because SQL query copied from panel inspector returns data as expected.

Not sure does it make sense to fix it since queries are moving to the backend and there's no ability to use SQL data sources for querying data anymore. Maybe it will be possible in future, but backend queries solve most of problems that Direct DB connection is trying to address.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.x   | x.x.x  | 4.1.5                 |

**Comment by fauust** [comment]
So should we simply disable "Direct DB connection" ?

**Comment by isaqueprofeta** [comment]
> So should we simply disable "Direct DB connection" ?

If it's work for you, you can do it. But understand that without Direct DB you can have some problem with Zabbix API query limits that just throws you a 500 error if you request too much from it.

**Comment by fauust** [comment]
Well I have some bigger instance where this could be a problem (and I can not test it at the moment).

Thing is I do not understand what this means (do you have any pointer to grafana 8.0 documentation/changes?):

> Not sure does it make sense to fix it since queries are moving to the backend and there's no ability to use SQL data sources for querying data anymore. Maybe it will be possible in future, but backend queries solve most of problems that Direct DB connection is trying to address.

So I don't see what alternative to not load the Zabbix API from grafana do we have.

**Comment by alexanderzobnin** [comment]
@fauust I mean with the backend load for the backend will be reduced (but not so much as with direct db connection). Also, implementing direct db connection on the backend is tricky since I cannot use existing data source (maybe, I can, but I have to investigate). So my tip:
1. Disable direct db connection if it's not critical for you (your Zabbix server can handle amount of queries you usually invoke).
2. Downgrade to Grafana 7.5 and wait for the fix (will be in 4.2 release).

**Comment by fauust** [comment]
Great, don't hesitate to ping me if you need help in testing.

**Comment by denis-argentin** [comment]
Same problem here. :/

**Comment by logiserv** [comment]
Same problem here
I disable direct db connection and wait 4.2 release

**Comment by jcoliveira-dotcom** [comment]
I have the same problem "no data"

**Comment by isaqueprofeta** [comment]
@jcoliveira-dotcom do not use for now the DB connection.

**Comment by viniropke99** [comment]
+1

**Comment by alexanderzobnin** [comment]
Closed by #1256
