### ISSUE TITLE
zabbix->functions->sort:error

### ISSUE THREAD

**Issue by xiaotianlu** [alexanderzobnin/grafana-zabbix#1223]
**Describe the bug**
functions -> sortSeries(des)  
Only effective for monitoring items
Instead of value

**Screenshots**
![image](https://user-images.githubusercontent.com/28923973/121457795-d778be00-c9da-11eb-88ae-194a25937b20.png)

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.3.10-8.0.0 | 5.4 | 4.1.5

**Comment by alexanderzobnin** [comment]
Hi! The `sortSeries()` function works with series names and treats it as strings. So numbers are sorted in the lexicographic order.

**Comment by alexanderzobnin** [comment]
Ref #1274
