### ISSUE TITLE
Unable to edit Application option

### ISSUE THREAD

**Issue by AugustoRubio** [alexanderzobnin/grafana-zabbix#1227]
I'm having a problem when I try to change the Application option in the dashboard.

[https://drive.google.com/file/d/1VtNg6yzDRfbP9TGU_0TKPtDbsBrN1yfG/view?usp=sharing](https://drive.google.com/file/d/1VtNg6yzDRfbP9TGU_0TKPtDbsBrN1yfG/view?usp=sharing)

It looks normal, but when I select some option in the group field the Application field is disabled.
[https://drive.google.com/file/d/1QITD0Tu-gfQcnIXROWq78lLcb90wW-27/view?usp=sharing](https://drive.google.com/file/d/1QITD0Tu-gfQcnIXROWq78lLcb90wW-27/view?usp=sharing)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v8.0.2  | 5.4.1  | 4.1.5 |

**Comment by MAGICCC** [comment]
Yep indeed, same for me

**Comment by mattmill98** [comment]
Same here. Running same versions as well.

**Comment by AugustoRubio** [comment]
The problem continues after the updated grafana v8.0.3 (cae5c5e46b)

**Comment by AugustoRubio** [comment]
The problem continues after the updated Zabbix 5.4.2.

**Comment by isaqueprofeta** [comment]
THERE'S NO SUPPORT FOR APPLICATIONS IN ZABBIX 5.4, then there's no support for applications in grafana-plugin

For Christ sake... Nobody here reads the docs and release notes before upgrade?

**Comment by AugustoRubio** [comment]
> THERE'S NO SUPPORT FOR APPLICATIONS IN ZABBIX 5.4, then there's no support for applications in grafana-plugin
> 
> For Christ sake... Nobody here reads the docs and release notes before upgrade?

Wow how arrogant you are! Ou melhor, tinha que ser brasileiro! Custa falar com educação ?

**Comment by danielpereira-gub** [comment]
Como vc quer que ele diga? As pessoas nao podem simplesmente ler? Para que atualizar o plugin entao?
