### ISSUE TITLE
Trailing no-data is graphed as zero and has mouse-over values

### ISSUE THREAD

**Issue by volter** [alexanderzobnin/grafana-zabbix#123]
If I select "This week" from the time menu, missing trailing data is graphed as zero.
![nodata](https://cloud.githubusercontent.com/assets/1042313/11779318/8cbc4254-a25a-11e5-9f79-558e21f0c1fd.png)

So far, I was only able to reproduce this with "This week". It doesn't happen for "Today". Apparently it doesn't matter whether you are using a notation like "now/w" or explicit timestamps. It doesn't seem to happen with the Elasticsearch data source. I tried in Firefox and Chromium with the build from the 11th of December.

This may as well be a bug in Grafana or the JS library used for graphing.

**Comment by alexanderzobnin** [comment]
@volter Just see to dates on panel :smile:  This is time from Sunday to Saturday on current week.

**Comment by volter** [comment]
Sorry, what?

**Comment by xiaoping378** [comment]
@volter 
On date panel,  ["Laster 7 days", "This week", "Week to date"] are different.

**Comment by alexanderzobnin** [comment]
If today is Monday, this time interval will show all current week. Of course, you haven't data from future.

**Comment by volter** [comment]
I don't expect it to project into the future. I also realize that different time settings are semantically different. However 0 in not Null and I wonder how comes that, depending on the temporal settings somehow, this, more appropriate rendering comes into existence
![better_graph](https://cloud.githubusercontent.com/assets/1042313/11824015/9c239f3a-a377-11e5-9377-24c13a36a9eb.png)
