### ISSUE TITLE
Unable to see ACK if exist tags

### ISSUE THREAD

**Issue by borjasueiro** [alexanderzobnin/grafana-zabbix#1233]
**Describe the bug**
When we have a "Zabbix Problems" panel that does not occupy the whole screen (it occupies half of it), if the "Problem timeline" is enable and the host has tags, the ACK part moves down and becomes invisible to the user.

**Expected behavior**
To be able to see the acks together with "Problem timeline" and the tags.

**Screenshots**
![2021-06-23_12-41](https://user-images.githubusercontent.com/49273030/123083554-70b6c400-d420-11eb-81f6-efbccfee388c.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.7   | 5.0.10  | 4.0.2                 |
| 7.3.7   | 5.0.10  | 4.1.5                 |

**Comment by atelleira** [comment]
+1

**Comment by dvaltmoli** [comment]
+1

**Comment by renatoborges78** [comment]
Same happens with Grafana 8 all plugin releases from 4.02 to 4.1.5 what I tested here

**Comment by alexanderzobnin** [comment]
Hi! Can someone explain what the actual issue - on the screenshot the ack button is presented.

**Comment by borjasueiro** [comment]
Yes, the ack button appears, but not the ack message below the "Problem timeline" zone.

**Comment by alexanderzobnin** [comment]
Ok, got it.
