### ISSUE TITLE
Modified signature on FreeBSD

### ISSUE THREAD

**Issue by kokarl** [alexanderzobnin/grafana-zabbix#1237]
**Describe the bug**
I'm running grafana 7.5.6 on FreeBSD 12.2, grafana-zabbix plugin 4.1.5
The plugin installs fine. I followed the issue 1022 (https://github.com/alexanderzobnin/grafana-zabbix/issues/1022) and compiled the zabbix-plugin_freebsd_amd64 with success.
I added allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource in my grafana.conf
The Zabbix plugin appears in my plugin list as "Modified signature", but I'm unable to add the datasource since Grafana refuse to add a datasource with a modified signature.
You can use a datasource with a unverified signature but not with a modified signature. I actuallly have no solution to resolve this issue, could you help me ? May be you could re-sign your plugin with the zabbix-plugin_freebsd_amd64 file ?

Regards,
Karl

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.5.6   | 5.0.12  | 4.1.5                 |

**Comment by cardosocristian** [comment]
Same problem here.

**Comment by licheng-xd** [comment]
same

**Comment by eduwutzl** [comment]
Same!

**Comment by akhudushin** [comment]
Same. Modifying manifest also doesn't work in my case.
Tested with Grafana 8.0.2 & Plugin 4.2.1

**Comment by akhudushin** [comment]
I found the following workaround:

1. Delete MANIFEST.txt (located in plugin root dir)
2. Add `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app, alexanderzobnin-zabbix-datasource, alexanderzobnin-zabbix-triggers-panel` to grafana.conf

After MANIFEST.txt deletion plugin becomes "Unsigned" (not "Invalid signature", not "Modified signature"). After that Grafana correctly applies `allow_loading_unsigned_plugins` parameter value to this plugin.
