### ISSUE TITLE
No graphs are displayed - "no data"

### ISSUE THREAD

**Issue by p0wertiger** [alexanderzobnin/grafana-zabbix#1238]
**Describe the bug**
After upgrading Grafana to 8.0.4 and plugin to 4.1.5 there are no graphs from Zabbix data source, all the graphs display "no data" despite proper data frame coming in.

Zabbix version or service configuration didn't change. Requests are reaching Zabbix, replies are properly generated, they're reaching Grafana. I tried changing graph type fom "Graph (old)" to "Time series", tried creating a new graph, a new dashboard, even added a second copy of data source. Cleaned all the browser caches, logged out and back in. Nothing.
Other data sources like Prometheus, Elastic, MSSQL are working fine and bringing proper data, although not data frame but tabular data.

**Expected behavior**
Things were working fine with Grafana 7.5 and plugin 4.1.0. The expected result is proper data and graphs displaying.

**Screenshots**

![2021-07-05 11_20_53-Elasticsearch overview - Grafana](https://user-images.githubusercontent.com/2510748/124448947-400d4d80-dd83-11eb-927e-68576c0e4c96.png)

![2021-07-05 11_17_51-Explore - Grafana](https://user-images.githubusercontent.com/2510748/124448473-c8d7b980-dd82-11eb-8617-d507ddecb7f0.png)

![2021-07-05 11_18_09-Logger_ Custom graphs](https://user-images.githubusercontent.com/2510748/124448488-cc6b4080-dd82-11eb-9f45-1c49b022c467.png)

**Network data**

Request:
`{"queries":[{"refId":"A","format":"time_series","datasourceId":2,"rawSql":"SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (29644, 29647, 29649, 29650) AND clock > 1625302639 AND clock < 1625475439 GROUP BY (clock-1625302639) DIV 120, metric ORDER BY time_sec ASC","maxDataPoints":10000}]}`

Response:
`{"results":{"A":{"refId":"A","meta":{},"series":null,"tables":null,"dataframes":["QVJST1cxAAD/////6AMAABAAAAAAAAoADgAMAAsABAAKAAAAFAAAAAAAAAEDAAoADAAAAAgABAAKAAAACAAAAJwBAAADAAAAUAAAACgAAAAEAAAAsPz//wgAAAAMAAAAAAAAAAAAAAAFAAAAcmVmSWQAAADQ/P//CAAAABAAAAAHAAAAcmVzdWx0cwAEAAAAbmFtZQAAAAD0/P//CAAAADABAAAlAQAAeyJleGVjdXRlZFF1ZXJ5U3RyaW5nIjoiU0VMRUNUIENBU1QoaXRlbWlkIEFTIENIQVIpIEFTIG1ldHJpYywgTUlOKGNsb2NrKSBBUyB0aW1lX3NlYywgQVZHKHZhbHVlKSBBUyB2YWx1ZSBGUk9NIGhpc3RvcnlfdWludCBXSEVSRSBpdGVtaWQgSU4gKDI5NjQ0LCAyOTY0NywgMjk2NDksIDI5NjUwKSBBTkQgY2xvY2sgXHUwMDNlIDE2MjUzMDI2MzkgQU5EIGNsb2NrIFx1MDAzYyAxNjI1NDc1NDM5IEdST1VQIEJZIChjbG9jay0xNjI1MzAyNjM5KSBESVYgMTIwLCBtZXRyaWMgT1JERVIgQlkgdGltZV9zZWMgQVNDIn0AAAAEAAAAbWV0YQAAAAAFAAAApAEAADQBAADEAAAAZAAAAAQAAADu/v//FAAAADwAAAA8AAAAAAADATwAAAABAAAABAAAAHD+//8IAAAAEAAAAAUAAAAyOTY1MAAAAAQAAABuYW1lAAAAAAAAAABi/v//AAACAAUAAAAyOTY1MAAAAEr///8UAAAAPAAAADwAAAAAAAMBPAAAAAEAAAAEAAAAzP7//wgAAAAQAAAABQAAADI5NjQ5AAAABAAAAG5hbWUAAAAAAAAAAL7+//8AAAIABQAAADI5NjQ5AAAApv///xQAAAA8AAAAPAAAAAAAAwE8AAAAAQAAAAQAAAAo////CAAAABAAAAAFAAAAMjk2NDcAAAAEAAAAbmFtZQAAAAAAAAAAGv///wAAAgAFAAAAMjk2NDcAEgAYABQAEwASAAwAAAAIAAQAEgAAABQAAAA8AAAAPAAAAAAAAwE8AAAAAQAAAAQAAACU////CAAAABAAAAAFAAAAMjk2NDQAAAAEAAAAbmFtZQAAAAAAAAAAhv///wAAAgAFAAAAMjk2NDQAEgAYABQAAAATAAwAAAAIAAQAEgAAABQAAABIAAAAUAAAAAAAAApQAAAAAQAAAAwAAAAIAAwACAAEAAgAAAAIAAAAFAAAAAgAAAB0aW1lX3NlYwAAAAAEAAAAbmFtZQAAAAAAAAAAAAAGAAgABgAGAAAAAAADAAgAAAB0aW1lX3NlYwAAAAD/////SAEAABQAAAAAAAAADAAWABQAEwAMAAQADAAAAGABAAAAAAAAFAAAAAAAAAMDAAoAGAAMAAgABAAKAAAAFAAAALgAAAAIAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAgAAAAAAAAASAAAAAAAAABAAAAAAAAAAIgAAAAAAAAACAAAAAAAAACQAAAAAAAAAEAAAAAAAAAA0AAAAAAAAAAIAAAAAAAAANgAAAAAAAAAQAAAAAAAAAAYAQAAAAAAAAgAAAAAAAAAIAEAAAAAAABAAAAAAAAAAAAAAAAFAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAABgAAAAAAAAAIAAAAAAAAAAYAAAAAAAAACAAAAAAAAAAGAAAAAAAAAAgAAAAAAAAABgAAAAAAAAAAEBdGLdmOFgBu5/gt2Y4WAAIdcC7ZjhYAzLerLtmOFgBoXj472Y4WAMYu8TvZjhYAWmRoPNmOFgAk/6M82Y4WEQAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgAAAAAAAAAAAAAAAAAAAAAAAAAAADFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOEAAAAAAAAAAAAAAAAAAAAAARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlQAAAAAAAAAAAiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAwAFAASAAwACAAEAAwAAAAQAAAALAAAADwAAAAAAAMAAQAAAPgDAAAAAAAAUAEAAAAAAABgAQAAAAAAAAAAAAAAAAAAAAAAAAAACgAMAAAACAAEAAoAAAAIAAAAnAEAAAMAAABQAAAAKAAAAAQAAACw/P//CAAAAAwAAAAAAAAAAAAAAAUAAAByZWZJZAAAAND8//8IAAAAEAAAAAcAAAByZXN1bHRzAAQAAABuYW1lAAAAAPT8//8IAAAAMAEAACUBAAB7ImV4ZWN1dGVkUXVlcnlTdHJpbmciOiJTRUxFQ1QgQ0FTVChpdGVtaWQgQVMgQ0hBUikgQVMgbWV0cmljLCBNSU4oY2xvY2spIEFTIHRpbWVfc2VjLCBBVkcodmFsdWUpIEFTIHZhbHVlIEZST00gaGlzdG9yeV91aW50IFdIRVJFIGl0ZW1pZCBJTiAoMjk2NDQsIDI5NjQ3LCAyOTY0OSwgMjk2NTApIEFORCBjbG9jayBcdTAwM2UgMTYyNTMwMjYzOSBBTkQgY2xvY2sgXHUwMDNjIDE2MjU0NzU0MzkgR1JPVVAgQlkgKGNsb2NrLTE2MjUzMDI2MzkpIERJViAxMjAsIG1ldHJpYyBPUkRFUiBCWSB0aW1lX3NlYyBBU0MifQAAAAQAAABtZXRhAAAAAAUAAACkAQAANAEAAMQAAABkAAAABAAAAO7+//8UAAAAPAAAADwAAAAAAAMBPAAAAAEAAAAEAAAAcP7//wgAAAAQAAAABQAAADI5NjUwAAAABAAAAG5hbWUAAAAAAAAAAGL+//8AAAIABQAAADI5NjUwAAAASv///xQAAAA8AAAAPAAAAAAAAwE8AAAAAQAAAAQAAADM/v//CAAAABAAAAAFAAAAMjk2NDkAAAAEAAAAbmFtZQAAAAAAAAAAvv7//wAAAgAFAAAAMjk2NDkAAACm////FAAAADwAAAA8AAAAAAADATwAAAABAAAABAAAACj///8IAAAAEAAAAAUAAAAyOTY0NwAAAAQAAABuYW1lAAAAAAAAAAAa////AAACAAUAAAAyOTY0NwASABgAFAATABIADAAAAAgABAASAAAAFAAAADwAAAA8AAAAAAADATwAAAABAAAABAAAAJT///8IAAAAEAAAAAUAAAAyOTY0NAAAAAQAAABuYW1lAAAAAAAAAACG////AAACAAUAAAAyOTY0NAASABgAFAAAABMADAAAAAgABAASAAAAFAAAAEgAAABQAAAAAAAAClAAAAABAAAADAAAAAgADAAIAAQACAAAAAgAAAAUAAAACAAAAHRpbWVfc2VjAAAAAAQAAABuYW1lAAAAAAAAAAAAAAYACAAGAAYAAAAAAAMACAAAAHRpbWVfc2VjAAAAABgEAABBUlJPVzE="]}}}`

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.4   | 5.0.13  | 4.1.5                 |

**Comment by p0wertiger** [comment]
I tried enabling "direct DB connection" (was disabled due to past bugs) and exactly the same thing.

**Comment by CLU91** [comment]
Cheers, i encounter a similar problem. I set up two brand new Ubuntu Servers (internal) and installed Zabbix 5.0.13 on the first machine and Grafana 8.0.4 with Grafana-Zabbix Plugin 4.1.5 (literally the same configuration) on the second machine.

I could make it work to receive data but i have sporadically "NO DATA" to the fields. After a few seconds it's grabbing values again and everything turns back. I have 40 machines with 6 different pages and propably around 70 values that gets grabbed. 

Now you can imagine... my dashboards look like enlightened christmas tree throughout the day :S

Hope you can help

regards CLU

**Comment by robby-dermody** [comment]
Getting the same issue here after a plugin update. For me, disabling `Direct DB connection` 'fixed' it, but of course dashboarding rendering is much slower with that off.

**Comment by CLU91** [comment]
> Getting the same issue here after a plugin update. For me, disabling `Direct DB connection` 'fixed' it, but of course dashboarding rendering is much slower with that off.
> 
> Edit: looks like I am running into #1221

Direct DB Connection is turned off for me. I realized when i play with the "Time Range" it is changing. There are some values where i want to have instant change like ON/OFFLINE Status of Hosts. Unfortunately i couldn't figure out how to set it up properly for it to work without any problems.

**Comment by fernandogobah** [comment]
+1

**Comment by p0wertiger** [comment]
Any updates on this? This requires me to downgrade Grafana to 7.5 to get the graphs back again

**Comment by neothematrix** [comment]
I'm having a very similar issue, still trying to analyze, can you try playing with the "max data points" option? try putting a very high number so that the calculated "interval" is not too big, in my case it seems to fix the issue, but I'm still doing some tests:

![image](https://user-images.githubusercontent.com/2066602/130356647-be82b5bd-2746-466c-b407-5338ba9c68ab.png)

**Comment by p0wertiger** [comment]
After upgrading the plugin to 4.2.2 the problem went away.
