### ISSUE TITLE
Error when attempting to acknowledge problems in Grafana 8.0.4

### ISSUE THREAD

**Issue by devpak755** [alexanderzobnin/grafana-zabbix#1239]
**Describe the bug**
When click "Acknowledge problem" in the Zabbix Problem (Grafana) plugin, all information in the window is erased.

**Screenshots**
1. Click
![image](https://user-images.githubusercontent.com/83913978/124607401-7a0b4c00-de76-11eb-8709-b4ae0883e04c.png)

2. After Click
![image](https://user-images.githubusercontent.com/83913978/124607480-90b1a300-de76-11eb-92c1-96de82fcd27a.png)

**Network data**
![image](https://user-images.githubusercontent.com/83913978/124607899-f140e000-de76-11eb-87de-c77b4a685791.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.4   | 4.2.0  | 4.1.5                 |

**Comment by EHRETic** [comment]
Hi there,

I can confirm the issue too, whenever I click on the acknowledge button, everything disappear:

![image](https://user-images.githubusercontent.com/28634810/124709859-496df580-defc-11eb-832e-d0076d90e7c6.png)

![image](https://user-images.githubusercontent.com/28634810/124709877-4d9a1300-defc-11eb-99d0-de47bfe2ec65.png)

But in my case, I can confirm it stopped working after Grafana 8 update, it was working fine before (used daily).
Right after I migrated from Zabbix 5.2 to 5.4, it didn't change anything.

<html>
<body>
<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Software versions</strong></p>

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
8.0.4 | 5.4.2 | 4.1.5


</body>
</html>

**Comment by devpak755** [comment]
> Всем привет,
> 
> Я тоже могу подтвердить проблему, всякий раз, когда я нажимаю кнопку подтверждения, все исчезает:
> 
> ![изображение](https://user-images.githubusercontent.com/28634810/124709859-496df580-defc-11eb-832e-d0076d90e7c6.png)
> 
> ![изображение](https://user-images.githubusercontent.com/28634810/124709877-4d9a1300-defc-11eb-99d0-de47bfe2ec65.png)
> 
> Но в моем случае я могу подтвердить, что он перестал работать после обновления Grafana 8, раньше он работал нормально (использовался ежедневно).
> Сразу после того, как я перешел с Zabbix 5.2 на 5.4, ничего не изменилось.
> 
> **Версии программного обеспечения**
> 
> Графана	Zabbix	Плагин Grafana-Zabbix
> 8.0.4	5.4.2	4.1.5

I also got this after updating to Grafana 8

**Comment by markoetie** [comment]
Same problem as described in #1231

**Comment by fernandogobah** [comment]
+1

**Comment by alissonash** [comment]
+1

**Comment by SinHazzard** [comment]
Same issue, same message

![image](https://user-images.githubusercontent.com/74702556/125813107-ec75bfa8-6950-4e21-9252-b9f1487bf2c3.png)

**Comment by loliveira1080** [comment]
Same problem!

**Comment by EHRETic** [comment]
@alexanderzobnin don't hesitate to reach out David Parrott @ Grafana if you need any help! 😉
He offered his in this topic that I created: https://community.grafana.com/t/zabbix-acknowledgement-not-working-since-8-x-migration/50015/4

His profile:
https://community.grafana.com/u/davidparrott

**Comment by cisco82** [comment]
+1

**Comment by alexanderzobnin** [comment]
Confirmed.

**Comment by alexanderzobnin** [comment]
Closed by #1256
