### ISSUE TITLE
grafana 2.6.0

### ISSUE THREAD

**Issue by logicall** [alexanderzobnin/grafana-zabbix#124]
Александр, день добрый!
Возможно ли твой плагин добавить в grafana 2.6.0, чтобы получить панель триггеров?
Или надо ставить тобой собранную grafana?

**Comment by alexanderzobnin** [comment]
Добрый день. Панель с триггерами, к сожалению, можно использовать только в скомпилированной версии. Чуть позже я постараюсь обновить сборку - сделаю для новой версии Grafana.

**Comment by logicall** [comment]
Спасибо!
Буду ждать....
