### ISSUE TITLE
Explore button in Problems view giving 404

### ISSUE THREAD

**Issue by krisavi** [alexanderzobnin/grafana-zabbix#1240]
**Describe the bug**
When I click the explore button I get Grafana 404 problem

**Expected behavior**
Goes to explore view as implemented in here: #948

**Screenshots**
![image](https://user-images.githubusercontent.com/1912568/124920474-039a5580-e000-11eb-95c0-6354b05f9e9a.png)

**Extra info why problem appears** 
I checked the URL when manually going to explore page and it includes org_id, like so `explore?orgId=1&left=` the URL from explore button does not and when I add the org_id info to it, then it works fine. It seems to just miss that part. I guess it is change since Grafana 8.0.0 to require org_id in URL, even when only 1 org is used. 

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.4   | 5.0.11  | 4.1.5                 |

**Comment by memphisraines87** [comment]
Подтверждаю, та же проблема
