### ISSUE TITLE
Plugin Datasource not working with Grafana 8.0.5

### ISSUE THREAD

**Issue by Cobra1978** [alexanderzobnin/grafana-zabbix#1242]
Upgrading to grafana 8.0.5 causes the plugin to stop working

Error on the Frontend:
`Error: Failed to fetch Instantiating https://dashboards.diennea.lan/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module`

Grafana logs dosen't show any error

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.5   | 5.2/5.4  | latest installed by cli                 |

**Comment by JBlandHV** [comment]
I second this, have the same issue also

**Comment by Cobra1978** [comment]
It works now with grafna 8.0.6
