### ISSUE TITLE
zabbix plugin is not support grafana 8.0

### ISSUE THREAD

**Issue by mfkdfjhh** [alexanderzobnin/grafana-zabbix#1244]
After upgrading my grafana server from 6.6 to 8.0, I found that ZABBIX plugin could not be used normally. I manually installed zabbixplugin using grafana cli, checked in grafala -- configuration -- plugins, and not found  Alexander zobnin ZABBIX app。The error log is as follows：

t=2021-07-13T19:26:02+0800 lvl=warn msg="Some plugin scanning errors were found" logger=plugins errors="plugin with ID 'stackdriver' already exists in '/usr/local/grafana/public/app/plugins/datasource/stackdriver'"
t=2021-07-13T19:26:02+0800 lvl=warn msg="Some plugin scanning errors were found" logger=plugins errors="plugin 'grafana-clock-panel' is unsigned, plugin 'grafana-worldmap-panel' is unsigned, plugin 'worldping-cta' is unsigned, plugin 'raintank-worldping-app' is unsigned, plugin 'alexanderzobnin-zabbix-datasource' is unsigned, plugin 'alexanderzobnin-zabbix-app' is unsigned, plugin 'worldping-endpoint-list' is unsigned, plugin 'worldping-endpoint-nav' is unsigned, plugin 'alexanderzobnin-zabbix-triggers-panel' is unsigned"

**Comment by alexanderzobnin** [comment]
Hi! Plugin 4.2.1 should work with Grafana 8.
