### ISSUE TITLE
does not work with grafana 8.0.5

### ISSUE THREAD

**Issue by seligor** [alexanderzobnin/grafana-zabbix#1247]
**Describe the bug**
does not work with the latest version of grafana

**Expected behavior**
Expected behavior: Works with grafana 8.0.5

**Screenshots**
![2021-07-14_08-56-08](https://user-images.githubusercontent.com/3991246/125559462-00601fe9-779d-4fbb-849b-92e891ffb478.png)
![2021-07-14_08-56-23](https://user-images.githubusercontent.com/3991246/125559480-bf5191d5-aa95-4ee0-b691-1d0ecba331d4.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.5  | 5.4.2 | 4.1.5                 |

**Comment by borisbbtest** [comment]
+1

**Comment by romainsi** [comment]
Seem to be resolve with Grafana 8.0.6

**Comment by d1nd141** [comment]
Does not work here on grafana 8.0.6 and latest 5.4 zabbix. (with enabled mysql access in zabbix plugin. When disabling mysql access, it works fine.)

rawSql:"SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (34532) AND clock > 1626337601 AND clock < 1626359201 GROUP BY (clock-1626337601) DIV 15, metric ORDER BY time_sec ASC"

![image](https://user-images.githubusercontent.com/13020602/125805388-e2bbc151-d781-405c-b7c5-f4df13d00df0.png)

**Comment by Cobra1978** [comment]
For me it works with Grafana 8.0.6

**Comment by crazyaaron97** [comment]
Hi all
I've also the same issue useing Grafana v8.0.6 (68fe9e3431) and Zabbix v5.0.14. I use the plugin version 4.1.5. I've first updated Grafana and Zabbix via apt on Ubuntu 20.04 Servers and afterwords the plugin via grafana-cli.
For testing i turned off the "Direct DB Connection", than it all works. But as expected it feels slower than the DB connection.
I've also copied a rawSql Query from the Inspector as described in the comment of @d1nd141. I can execute this query sucessfully in the Explore section of grafana as well as in the mysql cli directly.

If i can send some logs or you need a non working example to debugging something, feel free to contact me. With turning off the DB Connection i've found a workaround. It would be great if this is a little problem which can be fixed soon. This plugin is a really wunderful peace of software, it combines the best of zabbix with the best of grafana.

**Comment by ihard** [comment]
Same problem, Grafana 8.0.6, plugin 4.1.5 Zabbix 5.0.7
disable Direct DB Connection - helped

**Comment by betaxab** [comment]
Same problem, Grafana v8.0.6, plugin 4.1.5, Zabbix 5.4.3.

**Comment by trevormac789** [comment]
I guess I'll try the disable direct DB connection. Hopefully it doesn't impact performance too much as we have a lot of zabbix data feeding into grafana. Hopefully will soon be resolved!

**Comment by vryzhevsky** [comment]
> all

Same for me with Grafana 8.0.6, Plugin 4.1.5, TSDB

**Comment by alexanderzobnin** [comment]
The original error seems to be a Zabbix issue (frontend doesn't match DB). Other issues should be fixed in latest release, so closing this one.
