### ISSUE TITLE
XHR error

### ISSUE THREAD

**Issue by Ericcccca** [alexanderzobnin/grafana-zabbix#1248]
When I added the data source, this error message appears，

Found）加载 http://10.1.12.125:3000/public/@grafana/ui?bust=1626327210815 错误：XHR 错误（404 Not Found）加载 http://10.1.12.125 :3000/public/@grafana/ui?bust=1626327210815 从 http://10.1.12.125:3000/public/@grafana/ui 加载为“@grafana/ui”时出错：http://10.1.12.125:3000/public /plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js
插件错误
(SystemJS) XHR 错误 (404 Not Found) loading http://10.1.12.125:3000/public/react?bust=1626327210815 Error: XHR error (404 Not Found) loading http://10.1.12.125:3000/public/ react?bust=1626327210815 从 http://10.1.12.125:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module 加载 http://10.1.12.125:3000/public/react 为“react”时出错.js

and how it came into being？

**Comment by alexanderzobnin** [comment]
Probably, you're using incompatible Grafana version.
