### ISSUE TITLE
"Show disabled items" option is not working

### ISSUE THREAD

**Issue by restorepoint1** [alexanderzobnin/grafana-zabbix#1249]
Disabled items are not shown when "show disabled items" is enabled.

Zabbix API is returning all items with different status.
Grafana's (or something deeper) response always contains only enabled items.

Zabbix 5.4, Grafana 7.5.7, grafana-zabbix 4.1.5, PSQL 12, TSDB, Direct DB connection

**Comment by alexanderzobnin** [comment]
Hi! Can you confirm that bug persists in the 4.2.1?

**Comment by restorepoint1** [comment]
> Hi! Can you confirm that bug persists in the 4.2.1?

Cant say about 4.2.1, but 4.2.2 with Grafana 8 still has the issue

**Comment by alexanderzobnin** [comment]
I guess your disabled items just do not have data for the selected period. But anyway, there's a bug, this toggle only affects suggested metrics, not the really displayed, so I'm fixing it.
