### ISSUE TITLE
Running custom queries to Zabbix (external scripts?)

### ISSUE THREAD

**Issue by jackalsh** [alexanderzobnin/grafana-zabbix#125]
There are any way I can make custom queries to Zabbix API for making custom stats panels?
For example I want count Zabbix triggers. I know trigger functionality was previously discussed, but I still wonder if there are some way to connect external scripts to get data directly to dashboards. 
I also know there are many data source engines providing this functionality, but I don't want use aditional database engine+daemon, because it is exactly what Zabbix is.

**Comment by alexanderzobnin** [comment]
Are you want to use custom scripts or you need to make just custom API queries?

**Comment by jackalsh** [comment]
Custom API queries must be enough.

**Comment by alexanderzobnin** [comment]
I think it's good idea for SingleStat panel.

**Comment by nucleusv** [comment]
@alexanderzobnin , and what you gonna show, pure json? or you will make dynamic field, first make pre query and looks what fields it has returned and than go to select fields?

**Comment by nucleusv** [comment]
@jackalsh, can you give exactly example what you what and also reference api method.
