### ISSUE TITLE
Update plugin to fit zabbix 5.4

### ISSUE THREAD

**Issue by elekgeek** [alexanderzobnin/grafana-zabbix#1250]
Hello,

Thank you for the great work done in this plugin.

I have a lot of dashboards that were application dependent and are no longer working now. Unfortunately, I could not find any alternative workaround to make these dashboards work as long as the query type is ```Application```. The error message shows ```Error updating options: Unsupported data format```. 

Hopefully the plugin will be updated soon.

Anyway, is there any workaround to make it work for Application queries?

thanks a ton!

**Comment by alexanderzobnin** [comment]
Item tags support added in recent release, so you can upgrade now and fix the issue.

**Comment by alexanderzobnin** [comment]
Duplicates #1258
