### ISSUE TITLE
Cannot unmarshal number into Go struct field ZabbixDatasourceSettingsDTO.timeout of type string

### ISSUE THREAD

**Issue by along0101** [alexanderzobnin/grafana-zabbix#1254]
when i use grafana and set zabbix datasource，notice that：
**json: cannot unmarshal number into Go struct field ZabbixDatasourceSettingsDTO.timeout of type string**

Isn't it a bug?

zabbix5.4，grafana8+

**Comment by alexanderzobnin** [comment]
Hi! Can you check it against plugin 4.2.1? Can't replicate this.

**Comment by alexanderzobnin** [comment]
Confirmed
