### ISSUE TITLE
Trigger panel: show acknowledged triggers in different color

### ISSUE THREAD

**Issue by galindro** [alexanderzobnin/grafana-zabbix#126]
@alexanderzobnin one of the features of my dashboard is to display a blue color on acknowledged triggers. Is it possible for you to add a checkbox that offers to the user the possibility to choose which color he wants to display on events that has acknowledeged? This way the team could be warned about an event acknowledgment.

**Comment by volter** [comment]
Somewhat connected to https://github.com/volter/grafana-zabbix/commit/46d656d49ea2b4fa4878f696d4666a9facb9ce2f

If it was implemented differently ("ack, non-ack, both" instead of "non-ack, both"), one could use two annotation queries.

**Comment by galindro** [comment]
@volter Your change makes an acknowledged event to be highlighted in relation to others like a different collor for the acknowledged event row?

**Comment by volter** [comment]
No, but it basically allows to show or not show acknowledged events.
![annotation](https://cloud.githubusercontent.com/assets/1042313/11825618/654dddc8-a380-11e5-9fb4-ebdd7aa60615.png)
