### ISSUE TITLE
Add Operation data in fields in Zabbix Problems

### ISSUE THREAD

**Issue by korvinys095** [alexanderzobnin/grafana-zabbix#1260]
In zabbix dashboard we can see operation data. 
In case where we use monitor for displaying data from zabbix, it's important to understand real situation.
For example, i have trigger "Errors on port". And i have big different between value 30 and 200 000 in age 1day)

**Comment by korvinys095** [comment]
And it's better if zabbix value mapping work in last value, for example
Down (0)
Up (1)

**Comment by xcdr** [comment]
This should be very useful functionality, I using in ZABBIX dashboard every day and can't do the same in grafana.

**Comment by fcollado** [comment]
+1

**Comment by remote24** [comment]
I am not getting this to work, have upgraded to latest versions
grafana version 9.4.7
plugin version 4.3.1
zabbix version 6.4.1

In zabbix: 
![image](https://user-images.githubusercontent.com/122528187/234001762-be5368bc-950c-4149-b291-57893890eaba.png)
name and operational data is shown but in Grafana only name is visible and there is no difference on any trigger when I enable Operational data in fields.
Grafana:
![image](https://user-images.githubusercontent.com/122528187/234002284-6fdba599-029c-448a-87d5-68cb1f5e67b5.png)
Query inspector seem to have the data:
![image](https://user-images.githubusercontent.com/122528187/234002570-a5aaba0d-0803-4c30-8d19-26d6033c881c.png)
