### ISSUE TITLE
Replace "Application" with "Tag"

### ISSUE THREAD

**Issue by nmocean** [alexanderzobnin/grafana-zabbix#1261]
**Is your feature request related to a problem? Please describe.**
We have updated to Zabbix 5.4 using Agent Version 5.4.3 and Grafana Version 7.5.10 and with the new version of Zabbix they have changed from using "Applications" to "Tags". Because of that the Application Value on the Grafana panel creation no longer works and is locked. We are starting to monitor Docker and its containers and the way in which the Zabbix Agent 2 collects the container information it uses tags for each of the containers discovered. And example of a Tag would be, "Application: Docker: Container /grafana". So when we try an create Variables we can't create one for "Tags", what use to be "Applications". 

**Describe the solution you'd like**
The feature would replace the Application Selection Box and allow for Tag Selections. Also it would allow for a Variable to be created called "Tags" so those Tags could be filtered and added to the dashboard variable list
![Screenshot 2021-08-11 104339](https://user-images.githubusercontent.com/41126494/129061180-57a0e835-617c-4e6f-9930-8d99a44d7b7e.png)

![Screenshot 2021-08-11 104821](https://user-images.githubusercontent.com/41126494/129061535-b82996b4-98d7-466f-b7b1-6792aebff83d.png)

**Describe alternatives you've considered**
I have not been able to find a work around yet for this. I have tried regex and individual items but still haven't gotten it to work right. 

**Additional context**

**Comment by alexanderzobnin** [comment]
This fixed in the 4.2.1. But this version of plugin is only compatible with Grafana 8.x. So I suggest you consider an upgrade.
