### ISSUE TITLE
Ability to show a host name for one host in graph

### ISSUE THREAD

**Issue by ssantrosyan** [alexanderzobnin/grafana-zabbix#1263]
Hi, Alexander,

I have an issue in my Grafana after upgrading it to a new 8.1.1 version. How can I solve the issue without updating the all dashboards with the setAlias($__zbx_host_name: $__zbx_item) solution ?

It's the same issue that was opened earlier.
https://github.com/alexanderzobnin/grafana-zabbix/issues/575# 

Thanks.

**Comment by alexanderzobnin** [comment]
Hi! It looks like it fixed in #1265. Now all queries should return `host: metric` as a series name.
