### ISSUE TITLE
Hostnames are not displayed on multiple selection  (regular expression)

### ISSUE THREAD

**Issue by Andorash** [alexanderzobnin/grafana-zabbix#1265]
**Describe the bug**
When selecting nodes with a regular pattern, hostnames are not displayed, when using any visualization

**Expected behavior**
Previously, host names were displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/35136951/129182524-bc922ff8-de3b-4eb7-8fe6-5228be6c4bc0.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|  v8.1.1 (90c87a52f7)  |5,2  |4,2,1   |

**Comment by crazyaaron97** [comment]
I've the same issue since the last update.
I use the following versions at the moment: Grafana 8.1.2, Zabbix 5.0.14 and Zabbix Grafana Plugin 4.2.1

**Comment by prague34** [comment]
i have also same issue
zabbix_server (Zabbix) 5.4.0beta2
Grafana v8.1.1 (90c87a52f7)
Zabbix plugin version  4.2.1

Does anyone know the working version?

**Comment by prague34** [comment]
> **Describe the bug**
> When selecting nodes with a regular pattern, hostnames are not displayed, when using any visualization
> 
> **Expected behavior**
> Previously, host names were displayed
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/35136951/129182524-bc922ff8-de3b-4eb7-8fe6-5228be6c4bc0.png)
> 
> **Software versions**
> 
> Grafana	Zabbix	Grafana-Zabbix Plugin
> v8.1.1 (90c87a52f7)	5,2	4,2,1

setAlias ($__zbx_host_name: $__zbx_item)  add this to function fix my problem!

**Comment by alexanderzobnin** [comment]
Guess, direct db connection is enabled, I can replicate this bug only with this option.
