### ISSUE TITLE
Top function does not work if number of series less than provided N

### ISSUE THREAD

**Issue by giovanny07** [alexanderzobnin/grafana-zabbix#1267]
**Describe the bug**
Top function does not work with bar indicator

**Expected behavior**
When the top function is assigned to a panel with x values, it will stop displaying if the top value is greater than the one obtained by the plugin.

For example: Image 1 has top 5 and gives nodata while image 2 has top 2 and gives data.

**Screenshots**
![image](https://user-images.githubusercontent.com/69469456/129386199-9f497866-c67c-4bc3-a0ee-63f2fec71265.png)
![image](https://user-images.githubusercontent.com/69469456/129386259-21a309b3-0ddf-47f9-8296-e7d94cac545b.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| -------   | ------   | ---------------------       |
| 8.1.1      | 5.4.3    | 4.2.1                              |

**Comment by mjtrangoni** [comment]
I can confirm the same for,

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.1.1   | 5.0.11  | 4.2.1                 |

The Query Inspector says, 
```
response:Object
message:"Metric request error"
```
