### ISSUE TITLE
: net/http: invalid header field name ""

### ISSUE THREAD

**Issue by uguronduc** [alexanderzobnin/grafana-zabbix#1268]
Hi ,
zabbix plugins updated (4.2.1).... Grafana v8.1.1 version is installed and zabbix 5.4.3 version is installed. The error it shows when I want to test the datasource is ": net/http: invalid header field name "" ... is there a solution?

**Comment by Kendzione** [comment]
I have the same issue

**Comment by uguronduc** [comment]
> 
> 
> I have faced the same issue
> 
> found solution here: https://community.grafana.com/t/panels-not-loading-after-updating-to-8-1-0/51491
> 
> There is need to remove (empty) custom headers entries.

Thank you Kendzione ... Remove custom http headers in zabbix data source and solved...

**Comment by sphtd** [comment]
Hi, where exactly to remove it? can you show the screen?
