### ISSUE TITLE
Random "Failed to call resource" errors and plugin restarts

### ISSUE THREAD

**Issue by Mksmpm** [alexanderzobnin/grafana-zabbix#1269]
The bug occurs when dashbords are opened or refreshed, totally random. 
"Failed to call resource" and "Plugin unavailable" errors appear. 
Not a timeout issue, errors come out immediately.
Refreshing a page helps most of the time.

Dbug logs attached.  [zabbixlog.txt](https://github.com/alexanderzobnin/grafana-zabbix/files/6997579/zabbixlog.txt)

![image](https://user-images.githubusercontent.com/89062585/129673997-dc812bbd-8ca6-4c3f-8a07-695a14f8b542.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.4.5   | 5.2.1  | 4.1.5                 |

**Comment by imbonobow** [comment]
Same problem here

**Comment by alexanderzobnin** [comment]
Is it happening in 4.2.1 as well?

**Comment by alexanderzobnin** [comment]
Confirmed. Caused by the Unicode characters in the item key.

**Comment by restorepoint1** [comment]
The issue still present on 4.2.2. Disabling data alignment solves the problem

**Comment by victortamotsu** [comment]
@restorepoint1 

Same here. Disabling data alignment did it.



Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
8.1.1 | 5.4.0 | 4.2.2
