### ISSUE TITLE
Invalid user name or password

### ISSUE THREAD

**Issue by ne0trace** [alexanderzobnin/grafana-zabbix#127]
Hello,
No matter which username/password combo I use, I can't seem to pass the connection test.
For API access I use the same username/pass combo as the admin logon to Zabbix.

Do I need to enable the API for my user somewhere else?
Grafana 2.5.1 and Zabbix 2.2.1, API

Thank you

**Comment by alexanderzobnin** [comment]
Hello! What kind of error you got? Invalid password or Connection failed?

**Comment by ne0trace** [comment]
Invalid password.
I confirmed the Admin password on the Zabbix side.
Here is a screenshot.
http://imgur.com/Rzrv4ZD

**Comment by alexanderzobnin** [comment]
Can you try another user? Are you installed plugin first time or updated it from previous version?

**Comment by ne0trace** [comment]
I created a user api/api with full admin permissions and it's being denied.
Plugin install is a first time install.
Here is the screenshot showing all settings.
http://imgur.com/IPmn0Ax

**Comment by alexanderzobnin** [comment]
Strange. What plugin version are you use?
Page should look like this:

![](https://cloud.githubusercontent.com/assets/4932851/11003517/fe46c746-84c3-11e5-9662-152a71b6f922.png)

**Comment by ne0trace** [comment]
I deleted the zabbix folder, downloaded everything again and it's working now. Not sure what happened. Probably user error on my end.

Thank you very much.

**Comment by alexanderzobnin** [comment]
Ok.
