### ISSUE TITLE
zabbix plugin downloaded but not installed

### ISSUE THREAD

**Issue by vomus** [alexanderzobnin/grafana-zabbix#1270]
Hi!
I just tried to install zabbix plugin (4.2.1) for grafana 8.1 and 8.0. Following the instruction, I did it from a command line
``
[serge@veles grafana-8.0.6]$ ./bin/grafana-cli plugins install alexanderzobnin-zabbix-app
✔ Downloaded alexanderzobnin-zabbix-app v4.2.1 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

[serge@veles grafana-8.0.6]$ 
``
However, the manual says the installation has to tell me that the plugin is installed. Why isn't it installed?

**Comment by alexanderzobnin** [comment]
Hi! Did you restart grafana-server? Do you see Zabbix in the list of plugins in the Grafana? Is there anything related to the zabbix plugin in the logs?

**Comment by alexanderzobnin** [comment]
Ok, looks like misconfiguration issue, so closing.
