### ISSUE TITLE
n.option is undefined

### ISSUE THREAD

**Issue by sphtd** [alexanderzobnin/grafana-zabbix#1271]
**Describe the bug**
When adding some items there is 

**Expected behavior**

Adding an item that displays new data 

**Screenshots**
![n option](https://user-images.githubusercontent.com/22845822/130585132-37cdbcaa-c662-4340-8333-d714609bb5bf.png)

**Network data**
![graff2](https://user-images.githubusercontent.com/22845822/130585607-cd7aa441-c071-4c33-9c63-b2a2de650b84.png)
https://pastebin.com/zPHQwvXS

json: https://pastebin.com/Qxy4GyB7
query: https://pastebin.com/LFze5vfN
data: https://pastebin.com/T3G0d847

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v8.1.2  | Zabbix 5.4.3. | 4.1.1           |

**Comment by alexanderzobnin** [comment]
Hi! Unfortunately, 4.1 plugin is not compatible with the Grafana 8. Try to upgrade to the latest plugin version, this problem was fixed.
