### ISSUE TITLE
No high in zabbix problems

### ISSUE THREAD

**Issue by sphtd** [alexanderzobnin/grafana-zabbix#1272]
**Describe the bug**

Zabbix plugins do not display problems with "HIGH" priority.

**Expected behavior**

View all problems 

**Screenshots**

![problm2](https://user-images.githubusercontent.com/22845822/130596562-bdea604c-1f7b-4efe-9a8f-b225173316ad.png)
![probl](https://user-images.githubusercontent.com/22845822/130596564-a2dec08a-5b92-4032-a57b-75b55a7a5308.png)

**Network data**
query: https://pastebin.com/mKen3k2P
json: https://pastebin.com/vGsuCe3W
data: https://pastebin.com/M76TWdtn
error from inspect: https://pastebin.com/4c9UNsLx

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v8.1.2  | Zabbix 5.4.3. | 4.1.1           |

**Comment by alexanderzobnin** [comment]
But it looks like your response does not contain problems with high severity.

**Comment by sphtd** [comment]
@alexanderzobnin  It just contains, I have such a HIGH. They are displayed in ZAbbix 
![image](https://user-images.githubusercontent.com/22845822/130793285-353b1038-a5cc-4c3e-afd4-fb5fc5d53430.png)

![image](https://user-images.githubusercontent.com/22845822/130793420-5e7f81f2-5d29-4fb5-af91-7d1efe20be1a.png)


I dont see  Unavailable by ICMP ping with high
