### ISSUE TITLE
New 4.2.2 version is unusable

### ISSUE THREAD

**Issue by fauust** [alexanderzobnin/grafana-zabbix#1279]
**Describe the bug**
Randomly (and always on some panel), I have the following errors:

Failed to call resource
Plugin unavailable

**Screenshots**
![screenshot_20210825_214139](https://user-images.githubusercontent.com/2197555/130854933-3678cc9d-6ffe-4475-bbf5-0e0e4cfb12b0.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.1.2  | 5.4.3  | 4.2.2                 |

Workaround: rollback to 4.2.1

**Comment by wangxin688** [comment]
same issue happen after update to 4.2.2. and also working if I select to disable  data alignment

**Comment by alexanderzobnin** [comment]
Closing this in prior of #1262 (the same bug basically).
