### ISSUE TITLE
 Supports zabbix single key shift function

### ISSUE THREAD

**Issue by bxeldor** [alexanderzobnin/grafana-zabbix#128]
![qq 20151217180428](https://cloud.githubusercontent.com/assets/2646582/11867227/9dd47c40-a4ea-11e5-88ed-18dd1dc59b86.png)

Once the value of "rangeFrom" has been changed, the value of  "options.range.from" would change accordingly. How to make the value of  "options.range.from"  is not impacted by the change of "rangeFrom" ?

**Comment by tgavriltg** [comment]
The same question.

**Comment by alexanderzobnin** [comment]
What type of `options.range.from` ? Is it primitive or object? In generall, primitives are passed "by value", but objects are passed by reference.
