### ISSUE TITLE
Post "https://localhost/zabbix/api_jsonrpc.php": dial tcp 127.0.0.1:443: connect: connection refused

### ISSUE THREAD

**Issue by cradud** [alexanderzobnin/grafana-zabbix#1280]
i am geting this error when i try to configure zabbix as datasource in grafana
Post "https://localhost/zabbix/api_jsonrpc.php": dial tcp 127.0.0.1:443: connect: connection refused

in netstat i have this 
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      637/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      714/sshd: /usr/sbin 
tcp6       0      0 :::9100                 :::*                    LISTEN      663/node_exporter   
tcp6       0      0 :::22                   :::*                    LISTEN      714/sshd: /usr/sbin 
tcp6       0      0 :::3000                 :::*                    LISTEN      1173/grafana-server 
tcp6       0      0 :::9090                 :::*                    LISTEN      664/prometheus      
udp        0      0 127.0.0.53:53           0.0.0.0:*                           637/systemd-resolve 
udp        0      0 192.168.134.82:68       0.0.0.0:*                           635/systemd-network 
raw6       0      0 :::58                   :::*                    7           635/systemd-network 
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     SEQPACKET  LISTENING     15747    1/init               /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     25678    896/systemd          /run/user/1000/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     25683    896/systemd          /run/user/1000/bus
unix  2      [ ACC ]     STREAM     LISTENING     25684    896/systemd          /run/user/1000/gnupg/S.dirmngr
unix  2      [ ACC ]     STREAM     LISTENING     25685    896/systemd          /run/user/1000/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     25686    896/systemd          /run/user/1000/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     15731    1/init               @/org/kernel/linux/storage/multipathd
unix  2      [ ACC ]     STREAM     LISTENING     25687    896/systemd          /run/user/1000/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     25688    896/systemd          /run/user/1000/gnupg/S.gpg-agent
unix  2      [ ACC ]     STREAM     LISTENING     25689    896/systemd          /run/user/1000/pk-debconf-socket
unix  2      [ ACC ]     STREAM     LISTENING     25690    896/systemd          /run/user/1000/snapd-session-agent.socket
unix  2      [ ACC ]     STREAM     LISTENING     15718    1/init               /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     15720    1/init               /run/systemd/userdb/io.systemd.DynamicUser
unix  2      [ ACC ]     STREAM     LISTENING     15729    1/init               /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     15742    1/init               /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     21581    1/init               /var/snap/lxd/common/lxd/unix.socket
unix  2      [ ACC ]     STREAM     LISTENING     15835    367/systemd-journal  /run/systemd/journal/io.systemd.journal
unix  2      [ ACC ]     STREAM     LISTENING     21568    1/init               /run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     21583    1/init               /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     21585    1/init               /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     21587    1/init               /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     27999    1195/zabbix-plugin_  /tmp/plugin989756186
unix  2      [ ACC ]     STREAM     LISTENING     21994    661/irqbalance       /run/irqbalance//irqbalance661.sock
unix  2      [ ACC ]     STREAM     LISTENING     21580    1/init               @ISCSIADM_ABSTRACT_NAMESPACE

i don have any active firewal enabled 

also i have this when i curl

 curl --ipv4 -v "http://localhost/zabbix/api_jsonrpc.php";
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to localhost port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 80: Connection refused

curl --ipv4 -v "http://localhost:3000";
*   Trying 127.0.0.1:3000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Cache-Control: no-cache
< Content-Type: text/html; charset=utf-8
< Expires: -1
< Location: /login
< Pragma: no-cache
< Set-Cookie: redirect_to=%2F; Path=/; HttpOnly; SameSite=Lax
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Xss-Protection: 1; mode=block
< Date: Mon, 30 Aug 2021 09:38:35 GMT
< Content-Length: 29
< 
<a href="/login">Found</a>.

* Connection #0 to host localhost left intact
i tryit both protocol port 80 or 443 (http and https)

**Comment by atelleira** [comment]
Hi cradud,

 ¿have you a local Zabbix Frontend running in the same server?  The plugin connects to zabbix api and this seems that you dont have any webserver running in localhost.

Greetings.

**Comment by alexanderzobnin** [comment]
Can you open Zabbix frontend? Maybe it's on the url different than localhost?

**Comment by cradud** [comment]
i can open zabbix frontend, i folowed the install steps for grafana after that i instaled zabbix from grafana cli..i can acces grafana on port 3000 but i can't acces zabbix frontend, where i can search for this. Thank you

**Comment by cradud** [comment]
is ok now, i instaled zabbix server too.... seems i don't maked this. thx

**Comment by cradud** [comment]
is ok now, i instaled zabbix server too.... seems i don't maked this. thx
