### ISSUE TITLE
Acknowledge author not showing in message

### ISSUE THREAD

**Issue by GOID1989** [alexanderzobnin/grafana-zabbix#1281]
**Describe the bug**
If user set ACK and write message via Zabbix WEB-GUI - Grafana dashboard not showing author of ACK, only message.
When view ACK from zabbix all authors listed

Tested behavior on two versions Grafana and plugins

**Expected behavior**
Showing author of ACK when viewing via Grafana.

**Screenshots**
![zabbix_dash](https://user-images.githubusercontent.com/14764726/131322413-8f33a37b-a5f2-4a34-8392-eee7a8679aff.png)
![grafana_dash](https://user-images.githubusercontent.com/14764726/131322430-f30d1f28-c3b9-469d-b945-df7538195a22.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.5   | 5.0.10  | 4.2.2                 |
| 7.5.7   | 5.0.10  | 4.1.2                 |

**Comment by alexanderzobnin** [comment]
Yes, this is expected. But I think it makes sense to add user from zabbix (in case of Grafana it always user set in the data source config, so I put user name in the text of message).
