### ISSUE TITLE
Item tag does not accept variables

### ISSUE THREAD

**Issue by ablecable** [alexanderzobnin/grafana-zabbix#1283]
Grafana 8.1.2
Zabbix 5.4.3
Grafana-Zabbix Plugin 4.2.2

![image](https://user-images.githubusercontent.com/6873012/131383984-4e22ec98-15ca-44fd-9103-dc53c02b64e8.png)

Item tag does not accept variables as input, in the Query inspector it looks like the correct value is passed:

![image](https://user-images.githubusercontent.com/6873012/131384436-a9fdcf7c-8b64-4d17-82e5-f7b35c576e84.png)

But the Item field is not filled if an variable is used.

**Comment by vmenabde22** [comment]
I have same problem

**Comment by hexicans** [comment]
I'have error too

**Comment by serrrios** [comment]
I'have error too

**Comment by Justmfree** [comment]
hello when will be fix of this issue ?

**Comment by eertul** [comment]
When I try to use variable as a part of item tag, it adds it to the query with brackets. And it ruins regex.

![image](https://user-images.githubusercontent.com/44103488/132106668-31ff0d8a-251b-4df5-90df-be7f989c9f5a.png)
