### ISSUE TITLE
{undefined} value for regex

### ISSUE THREAD

**Issue by galindro** [alexanderzobnin/grafana-zabbix#129]
@alexanderzobnin , I'm trying to make a host regex (in template) that match these strings: SV-V3-API(i-4568afd8) or SV-API-API-LOAD(i-uuuhty45). But, the interface gives me the {undefined result} when I use the following regex:

```bash
SV-V3-API(-LOAD)?\(i-[a-z0-9]{8}\)
```

It works fine if I test it on https://regex101.com/#javascript with the following values:

```bash
{SV-V3-API(i-0a0b8de8),SV-V3-API(i-3373cae2)}
{SV-V3-API-LOAD(i-1b4d6da9),SV-V3-API-LOAD(i-5386a7e1),SV-V3-API-LOAD(i-55e20b96),SV-V3-API-LOAD(i-c5ec0506),SV-V3-APIMANAGER-LOAD(i-b3b75e70)}
```

![image](https://cloud.githubusercontent.com/assets/4622097/11908082/69eb1c96-a5c0-11e5-8050-770dc4c816ae.png)

Is it a bug with templating regex? Does it supports regex groups?

**Comment by alexanderzobnin** [comment]
Can you attach screenshot of grafana?
`SV-V3-API(-LOAD)?\(i-[a-z0-9]{8}\)` - in this regex `(-LOAD)` is a capture group - your regex will return only `-LOAD` (as you can see at MATCH INFORMATION panel).

**Comment by galindro** [comment]
@alexanderzobnin the "MATCH INFORMATION" is intended only for group matching. When a regex matches, the site will colorize the matched string with a blue background. 

See the print bellow:

![image](https://cloud.githubusercontent.com/assets/4622097/11912990/89d4c56c-a63c-11e5-8113-42cc7d9a88b0.png)


I think that you are not considering the entire regex matching, only the group matching. When I put each regex part in a group, the interface will select the first one and ignores all the others. See the prints bellow:

```bash
# This is only for show that I have hosts enabled
Regex: SV-V3-API-LOAD.*
```
![image](https://cloud.githubusercontent.com/assets/4622097/11913007/2ddc6246-a63d-11e5-9184-d496bafc902c.png)


```bash
# This will only match "SV-V3-API"
Regex: (SV-V3-API)(-LOAD)?(\(i-[a-z0-9]{8}\))
```
![image](https://cloud.githubusercontent.com/assets/4622097/11913011/52857efc-a63d-11e5-8b14-2ea4e1a1c76e.png)

```bash
# This is the print showing the {undefined}
Regex: SV-V3-API(-LOAD)?\(i-[a-z0-9]{8}\)
```
![image](https://cloud.githubusercontent.com/assets/4622097/11912985/40df9bde-a63c-11e5-8746-348341a708bb.png)

**Comment by alexanderzobnin** [comment]
In templates regex returns only first capture group matching.
`SV-V3-API(-LOAD)?\(i-[a-z0-9]{8}\)` can returns only `-LOAD`. Try to use *non-capturing parentheses*:
`SV-V3-API(?:-LOAD)?\(i-[a-z0-9]{8}\)`

**Comment by galindro** [comment]
Worked:

SV-V3-API(?:-LOAD)?\(i-[a-z0-9]{8}\)

Thank you very much @alexanderzobnin

**Comment by alexanderzobnin** [comment]
Ok, nice!
