### ISSUE TITLE
Missing signature on Grafana 8.1.2

### ISSUE THREAD

**Issue by simoscon** [alexanderzobnin/grafana-zabbix#1290]
Hello, i have upgrade my Grafana and lost the connection between my Zabbix and grafana and got the following error. 

Unsigned plugins were found during plugin initialization. Grafana Labs cannot guarantee the integrity of these plugins. We recommend only using signed plugins.

The following plugins are disabled and not shown in the list below:
alexanderzobnin-zabbix-app
Missing signature
alexanderzobnin-zabbix-datasource
Missing signature
alexanderzobnin-zabbix-triggers-panel
Missing signature

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.1.2   | 4.0.33  | x.x.x                 |

**Comment by alexanderzobnin** [comment]
Hi! What's a plugin version? How it was installed?

**Comment by simoscon** [comment]
Hello, i found the solution, i had to run grafana-cli plugins install alexanderzobnin-zabbix-app from cli and then restart grafana to update the plugin. Sorry for this, thank you for your support
