### ISSUE TITLE
Failed to call resource - Plugin unavailable

### ISSUE THREAD

**Issue by omega949** [alexanderzobnin/grafana-zabbix#1292]
**Describe the bug**
During navigation some panels fail to load when changing from 1 host to another through the dropdown variables.. Same dashboard just variable change i get "Failed to call resource" &|or "Plugin unavailable" on some of the panels.. 1 could have 1 error and another panel on the same load would have the other error.

These dashboards were working fine grafana 7.5.4 and an older plugin version pre 4.1.X 

**Expected behavior**
Panel load with dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/40457866/132534180-45906e8b-1bbc-4443-8f55-58f185e6f4aa.png)

**Network data**
Plugin unavailable
Object
status:503
statusText:"Service Unavailable"
data:Object
message:"Plugin unavailable"
config:Object
url:"api/datasources/5/resources/db-connection-post"
method:"POST"
headers:Object
hideFromInspector:false
data:Object
retry:0
message:"Plugin unavailable"

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.3   | 5.4.2  | 4.2.2                 |

**Comment by omega949** [comment]
attaching more information from the same error

![image](https://user-images.githubusercontent.com/40457866/132534671-49130484-fe6e-43bb-87c6-eb458aa33b6a.png)

**Comment by omega949** [comment]
After looking at the dashboard it seems to be related to my "Disk Utilization Panel" Below is the query, but what is in the backend is 2 disks sda & sdb, if i manually choose 1 the panel loads, but when i use the wildcard to read them all its when i get the problem. 

![image](https://user-images.githubusercontent.com/40457866/132535310-04d4dfe1-1f7d-4502-a3dc-a828f4a38e37.png)

**Comment by omega949** [comment]
Sorry for all the updates, but as i saw the error was related to the db-connection-post  i tested it by disabling the directDB for the plugin and the same dashboard and all panels load fine, so this seems to be linked to the directDB section

**Comment by alexanderzobnin** [comment]
Hi! Could you provide a debug logs when error is happening? There should be an error with extended trace.

**Comment by omega949** [comment]
Hey Alex.
   Yeah attached is the debug logs on the system just as i select the server that contains the 2 disk attached to it.

t=2021-09-16T05:35:22-0400 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=3 orgId=2
t=2021-09-16T05:35:22-0400 lvl=dbug msg="Zabbix request" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource method=history.get
t=2021-09-16T05:35:22-0400 lvl=dbug msg="Zabbix request" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource method=problem.get
t=2021-09-16T05:35:22-0400 lvl=dbug msg="Zabbix request" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource method=history.get
t=2021-09-16T05:35:22-0400 lvl=dbug msg="Zabbix request" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource method=history.get
t=2021-09-16T05:35:22-0400 lvl=dbug msg="Zabbix request" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource method=history.get
t=2021-09-16T05:35:22-0400 lvl=dbug msg="Zabbix request" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource method=history.get
t=2021-09-16T05:35:22-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (36349) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 20, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:22-0400 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=4 orgId=2
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (36362) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 20, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (36361) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 20, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Zabbix request" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource method=trigger.get
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (36391) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 20, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (36390) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 20, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (36350) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 20, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (36351) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 20, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (36368) AND clock > 1631698522 AND clock < 1631784922 GROUP BY (clock-1631698522) DIV 600, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (36373) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 5, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (36371, 36370, 36372, 36374, 36375, 36376, 36377, 36378, 36379, 36380) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 5, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (36412) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 5, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:23-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (36478, 36480, 36487, 36481, 36482, 36479, 36484, 36485, 36486, 36483) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 5, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:24-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (36458, 36465) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 5, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:24-0400 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasourceId:4 format:time_series maxDataPoints:10000 rawSql:SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (36417, 36420) AND clock > 1631781322 AND clock < 1631784922 GROUP BY (clock-1631781322) DIV 5, metric ORDER BY time_sec ASC refId:A]}"
t=2021-09-16T05:35:24-0400 lvl=dbug msg="panic: runtime error: invalid memory address or nil pointer dereference" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac62fa]" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg= logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="goroutine 112 [running]:" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/alexanderzobnin/grafana-zabbix/pkg/timeseries.AlignSeriesIntervals(0xc00030c080, 0x2, 0x4, 0x11c1d00, 0x0, 0xed8d506da)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/alexanderzobnin/grafana-zabbix/pkg/timeseries/align.go:90 +0x5a" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/alexanderzobnin/grafana-zabbix/pkg/datasource.(*ZabbixDatasourceInstance).applyDataProcessing(0xc00042ac00, 0xd63e38, 0xc000303200, 0xc0002c06c0, 0xc00030c080, 0x2, 0x4, 0xc145c0, 0xc00042ac00, 0x0, ...)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/alexanderzobnin/grafana-zabbix/pkg/datasource/zabbix.go:129 +0x705" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/alexanderzobnin/grafana-zabbix/pkg/datasource.(*ZabbixDatasource).DBConnectionPostProcessingHandler(0xc0000a04c0, 0xd61a80, 0xc0003032f0, 0xc00027a000)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/alexanderzobnin/grafana-zabbix/pkg/datasource/resource_handler.go:95 +0x479" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="net/http.HandlerFunc.ServeHTTP(0xc00009e7c0, 0xd61a80, 0xc0003032f0, 0xc00027a000)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/usr/local/go/src/net/http/server.go:2069 +0x44" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="net/http.(*ServeMux).ServeHTTP(0xc0000ba700, 0xd61a80, 0xc0003032f0, 0xc00027a000)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/usr/local/go/src/net/http/server.go:2448 +0x1ad" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/grafana/grafana-plugin-sdk-go/backend/resource/httpadapter.(*httpResourceHandler).CallResource(0xc00009e7d0, 0xd63e38, 0xc000303200, 0xc00045a480, 0xd562a0, 0xc0004a00f0, 0x10, 0x7f10e97b3a68)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.98.1/backend/resource/httpadapter/handler.go:58 +0x451" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/grafana/grafana-plugin-sdk-go/backend.(*resourceSDKAdapter).CallResource(0xc00009e8b0, 0xc00045a400, 0xd68bd8, 0xc000480590, 0x1, 0xc000480590)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.98.1/backend/resource_adapter.go:37 +0xf6" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/grafana/grafana-plugin-sdk-go/backend/grpcplugin.(*resourceGRPCServer).CallResource(0xc00009eb00, 0xc00045a400, 0xd68bd8, 0xc000480590, 0xc00009eb00, 0x18)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.98.1/backend/grpcplugin/grpc_resource.go:47 +0x51" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/grafana/grafana-plugin-sdk-go/genproto/pluginv2._Resource_CallResource_Handler(0xb71640, 0xc00009eb00, 0xd66c68, 0xc0004a00d8, 0x1f, 0xc00047e0a0)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.98.1/genproto/pluginv2/backend_grpc.pb.go:95 +0x113" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1(0xb71640, 0xc00009eb00, 0xd66d88, 0xc0001b6300, 0xc0004a00c0, 0xca9e80, 0xc00030c060, 0xc0004a00c0)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121 +0xef" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0xb71640, 0xc00009eb00, 0xd66d88, 0xc0001b6300, 0xc000016c70, 0x40fdb8)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x5f" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1(0xb71640, 0xc00009eb00, 0xd66d88, 0xc0001b6300, 0xc0004a00c0, 0xca9e80, 0xd63e38, 0xc000302f30)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58 +0xd1" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="google.golang.org/grpc.(*Server).processStreamingRPC(0xc0000fc000, 0xd6adb8, 0xc00008b080, 0xc0002c0120, 0xc0000a54d0, 0x11abbc0, 0x0, 0x0, 0x0)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1471 +0x535" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="google.golang.org/grpc.(*Server).handleStream(0xc0000fc000, 0xd6adb8, 0xc00008b080, 0xc0002c0120, 0x0)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1544 +0xca5" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000b8950, 0xc0000fc000, 0xd6adb8, 0xc00008b080, 0xc0002c0120)" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:878 +0xab" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="created by google.golang.org/grpc.(*Server).serveStreams.func1" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="\t/root/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:876 +0x1fd" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:24-0400 lvl=dbug msg="plugin process exited" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource path=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64 pid=78181 error="exit status 2"
t=2021-09-16T05:35:24-0400 lvl=eror msg="Failed to call resource" logger=context userId=3 orgId=2 uname=cxf3244 error="failed to receive call resource response: rpc error: code = Unavailable desc = transport is closing"
t=2021-09-16T05:35:24-0400 lvl=eror msg="Request Completed" logger=context userId=3 orgId=2 uname=cxf3244 method=POST path=/api/datasources/3/resources/db-connection-post status=500 remote_addr=10.29.68.47 time_ms=6 size=37 referer="https://monitoring-dev.global.iff.com/d/J5YCa-jMk/01-server-stats?orgId=2&refresh=1m&var-Env=Development&var-Proj=Monitoring&var-Application=Zabbix&var-Component=Database&var-Group=All&var-Host=Zabbix%20Database%20Server&var-OS=Linux"
t=2021-09-16T05:35:25-0400 lvl=dbug msg="Restarting plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:25-0400 lvl=dbug msg="starting plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource path=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64 args=[/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64]
t=2021-09-16T05:35:25-0400 lvl=dbug msg="plugin started" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource path=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64 pid=78192
t=2021-09-16T05:35:25-0400 lvl=dbug msg="waiting for RPC address" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource path=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64
t=2021-09-16T05:35:25-0400 lvl=info msg=Profiler logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource enabled=false
t=2021-09-16T05:35:25-0400 lvl=dbug msg="Could not read environment variable" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource EXTRA_VALUE_AT_END=GFX_ZABBIX_DATA_PATH
t=2021-09-16T05:35:25-0400 lvl=dbug msg="Starting Zabbix datasource" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:25-0400 lvl=dbug msg="Serving plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource plugins="[diagnostics resource data]"
t=2021-09-16T05:35:25-0400 lvl=dbug msg="using plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource version=2
t=2021-09-16T05:35:25-0400 lvl=dbug msg="plugin address" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource address=/tmp/plugin317816990 network=unix
t=2021-09-16T05:35:25-0400 lvl=dbug msg="Plugin restarted" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource
t=2021-09-16T05:35:26-0400 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0

**Comment by omega949** [comment]
I am wondering if this is the issue, i noticed this panic in the logs

t=2021-09-16T05:35:24-0400 lvl=dbug msg="panic: runtime error: invalid memory address or nil pointer dereference" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource

**Comment by deepaksharma17** [comment]
Similar issue, getting below message in grafana log after upgrading to latest grafana (8.1.5) and Zabbix plugin (4.2.3)

`t=2021-09-22T08:03:48+0000 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource" t=2021-09-22T08:03:48+0000 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource" t=2021-09-22T08:03:48+0000 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource" t=2021-09-22T08:03:48+0000 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"`

Any idea, how this can be fixed, the plugin is no more visible in Grafana GUI.

**Comment by Andorash** [comment]
@deepaksharma17 

Try in console
chmod 777 /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64
sudo systemctl stop grafana-server
sudo systemctl start grafana-server

**Comment by deepaksharma17** [comment]
Hi @Andorash, it didn't work

**Comment by alexanderzobnin** [comment]
This issue is fixed in 4.2.3

**Comment by deepaksharma17** [comment]
Hi @alexanderzobnin, I am using the latest version only
`[root@rhel7-test1:<rhel7-test> ~]# grafana-cli plugins ls
installed plugins:
alexanderzobnin-zabbix-app @ 4.2.3
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
`
