### ISSUE TITLE
Flowchart alias not working on 4.2.2 plugin

### ISSUE THREAD

**Issue by omega949** [alexanderzobnin/grafana-zabbix#1294]
**Describe the bug**
Pre 4.2.2 plugin when creating flowchart in the mapping section it was possible to set "Apply to metrics" to the setAlias value in the query builder, but after upgrade that is not possible anymore and you must specify the host.

Example:
4.2.1 =  Apply to metrics=grafana_web
4.2.2 = Apply to metrics=Host: Response code for step "01 - Index Page" of scenario "Web Availability".

**Expected behavior**
Ability to use the setAlias within the Apply to metric input field in the mapping section of the flowchart

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/40457866/132668269-70dd3a63-933e-4acf-8004-c49f846df67f.png)

now:
![image](https://user-images.githubusercontent.com/40457866/132668343-2da8f012-ef16-4c33-9a9e-7ccaad5affd5.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|8.0.3 | 5.4.2 | 4.2.2              |

**Comment by alexanderzobnin** [comment]
Hi! Unfortunately, I have no idea how flowchart works, so it's tricky to fix.
