### ISSUE TITLE
Zabbix API request ERROR "EOF"

### ISSUE THREAD

**Issue by CLU91** [alexanderzobnin/grafana-zabbix#1295]
**Describe the bug**

Throughout the day it happens multiple times that the Grafana Dashboard will crash for a few seconds with the message:
Post \"https://zabbix.domain-name.de/api_jsonrpc.php\": EOF
After that we need to refresh the webpage. Sometimes it's not happening at all, sometimes it's happening quite a lot throughout the day. 

**Expected behavior**

The Zabbix Plugin not to crash sporadically

**Screenshots**

No Screenshot, but the ERROR MSG from the Grafana.log:
t=2021-09-09T01:31:34+0200 lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="Post \"https://zabbix.domain-name.de/api_jsonrpc.php\": EOF"
t=2021-09-09T01:31:34+0200 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=monitoring method=POST path=/api/datasources/1/resources/zabbix-api status=500 remote_addr=192.168.42.105 time_ms=3 size=119 referer="https://grafana.domain-name.de/d/WwCQTgm7z/druckerserver?kiosk&orgId=1&refresh=5s"

**Network data**

/

**Software versions**

|               Grafana       |    Zabbix    | Grafana-Zabbix Plugin |
| ---------------------- | ------------ | ------------------------ |
| v8.0.4 (81fef5b4b4)   |    5.0.15     |                4.1.5              |

**Comment by alexanderzobnin** [comment]
Hm, probably, it's golang-related issue, I have to set `req.Close = true` in order to avoid it.

**Comment by CLU91** [comment]
UPDATE: I updated the Plugin Version to 4.2.2 and now i have one more issue in addition. I want to monitor the Zabbix Agent Availability. The value from Zabbix is 1 (UP). I also tried Zabbix Agent Ping which is also the value 1 for the status "up".

Both sporadically jumping to the value 0.500. Since i set value 1 to green and 0 to red, i have several servers jumping from green to red all the time and back.

**Comment by alexanderzobnin** [comment]
@CLU91 could you open this as a separate issue, this is another problem (or just panel misconfiguration)?

**Comment by alexanderzobnin** [comment]
I added fix for this, let me know if it works or not (after 4.2.3 release).

**Comment by CLU91** [comment]
Hi Alexander,

where to get the release 4.2.3? The error is appearing every minute now...
