### ISSUE TITLE
When update to 4.2.2 some dashboard cant get value

### ISSUE THREAD

**Issue by quangphan1602** [alexanderzobnin/grafana-zabbix#1297]
![image](https://user-images.githubusercontent.com/49912141/132854498-1da41b6a-f99a-47f5-846d-08730c1039a3.png)
With Item like this in version 4.2.1, can show good. Item in / ... / failed to get.

**Comment by JSylvia007** [comment]
I'm also having this issue.  If you refresh the page, sometimes random items will work.  I have very zabbix-heavy dashboards, and they're basically useless now.  It's been rock solid for me for a while now.

If I refresh too many times, then I get a Grafana error, "plugin unavailable", which obviously isn't true.

**Comment by quangphan1602** [comment]
Manual downgrade to 4.2.1 or 4.2.0 and always "plugin unavailable" :( Cant restore last good T.T

**Comment by alexanderzobnin** [comment]
@JSylvia007 could you please post debug logs when error happens?

**Comment by alexanderzobnin** [comment]
@quangphan1602 could you also try to change a regex? Now it's parsed on the backend and JS regex is not fully compatible with a go engine, so that might cause troubles in case of using `(?=)` and `(?!)`.

**Comment by jinucompute** [comment]
I am facing similar issues. After the upgrade to 4.2.2. A lot of my panel say No data. Did some basic check and found in a lot of places where i select the item as /Interface .*/ fails
I see error "message:"Metric request error" in the query inspector . I then checked the grafana logs for this and found the following warning "Request Origin is not authorized"  and status 403

**Comment by deepaksharma17** [comment]
Similar issue, getting below message in grafana log after upgrading to latest grafana (8.1.5) and Zabbix plugin (4.2.3)

`t=2021-09-22T08:03:48+0000 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource" 
t=2021-09-22T08:03:48+0000 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource" 
t=2021-09-22T08:03:48+0000 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource" 
t=2021-09-22T08:03:48+0000 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"`

Any idea, how this can be fixed, the plugin is no more visible in Grafana GUI.

**Comment by crazyaaron97** [comment]
I've the same Problem. I attached a debug logfile from a request that won't work and a screenshot of the non working and the working example. It works if i remove the regex from the host and display only one host. The regex match all 6 hosts in the group and won't work.
[grafana_debug.log](https://github.com/alexanderzobnin/grafana-zabbix/files/7208962/grafana_debug.log)
![grafana_Screenshot_20210922_101610](https://user-images.githubusercontent.com/16166545/134308204-0ffebc4f-3ed5-4b93-9b9c-c628490180d6.png)
![grafana_Screenshot_20210922_101918](https://user-images.githubusercontent.com/16166545/134308208-d20df2b1-b695-4a08-89a2-e76e477b43a2.png)

I hope this information can help fixing the issue.

**Comment by alexanderzobnin** [comment]
This should be fixed in 4.2.3.

**Comment by quangphan1602** [comment]
Thank you, It’s now working like a charm. Good job man.
