### ISSUE TITLE
Zabbix 2.2.11, G 2.6 and G-Z 2.5.1 graph from Zabbix trends is not working

### ISSUE THREAD

**Issue by joriws** [alexanderzobnin/grafana-zabbix#130]
I've data source for 7 days trends - all my graph work under 7d but if I select 30d I get "b is undefined" error in orange triangle at graph's top left corner.

Is it incompatibility with Zabbix 2.2.x and it's API? Or is it some kind of a bug?

I am running
grafana_2.6.0_amd64.deb
grafana-zabbix-v2.5.1.tar.gz

**Comment by karpath** [comment]
hello, you need to patch zabbix to get trend graph working
https://support.zabbix.com/browse/ZBXNEXT-1193

**Comment by nucleusv** [comment]
@joriws or wait for zabbix 3.0
http://www.zabbix.com/rn3.0.0alpha5.php

**Comment by clems94** [comment]
Hello

I patched my zabbix 2.2.8 but i can not see the trend in my grafana dashboard.

I've got this error 

Cannot read property 'itemid' of undefined

			TypeError: Cannot read property 'itemid' of undefined
    at http://euisats894:3000/public/app/app.ca0ab6f9.js:16:20428
    at Function.groupBy (http://euisats894:3000/public/app/app.ca0ab6f9.js:16:6552)
    at handleTrendResponse (http://euisats894:3000/public/app/plugins/datasource/zabbix/helperFunctions.js?bust=1451399778916:88:30)
    at b (http://euisats894:3000/public/app/app.ca0ab6f9.js:16:2529)
    at i (http://euisats894:3000/public/app/app.ca0ab6f9.js:13:5845)
    at http://euisats894:3000/public/app/app.ca0ab6f9.js:13:6017
    at n.$eval (http://euisats894:3000/public/app/app.ca0ab6f9.js:13:13637)
    at n.$digest (http://euisats894:3000/public/app/app.ca0ab6f9.js:13:12068)
    at n.$apply (http://euisats894:3000/public/app/app.ca0ab6f9.js:13:13904)
    at f (http://euisats894:3000/public/app/app.ca0ab6f9.js:11:20602)

**Comment by clems94** [comment]
Hi

I modified the file zabbixAPIWrapper.js line 209 and 226.

209 trend: value_type,
226 return this.performZabbixAPIRequest('trends.get', params);

and the trend worked with zabbix 2.2.8 grafana 2.5.0 and 2.6.0

**Comment by joriws** [comment]
Thanks, I did read the installation but I understood that trends-section was optional. After applying the patch for Zabbix API and fixing type in ZabbixAPIWrapper.json (trend => trends) my error changed. So no more "b is undefined" but now I get "no datapoints" with "no datapoints returned from metric query". I used Firefox's web developer to check and I get big JSON file back from server with trend data.

**Comment by clems94** [comment]
can you test the trend.get method with curl exemple 

get your auth strin

curl -i -X POST -H 'Content-Type:application/json' -d'{"jsonrpc": "2.0","method":"user.authenticate","params":{"user":"admin","password":"password"},"auth": null,"id":0}' http://zabbix/api_jsonrpc.php

trend get

curl -i -n -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"trends.get","params":{"output":"extend","itemids":"id u wanna get on zabbix db","history":0},"auth":"auth string","id": 1}' http://zabbix/api_jsonrpc.php

**Comment by joriws** [comment]
Thanks for the curl -tip..

I think my problem now is that I've patch for 2.2.8 zabbix aka plural (trends). Then my grafana-zabbix-plugin is for newer zabbix 2.4.4 which is singular (trend). I tried to fix it by changing API names to singular but still using 2.2.8 patch. So my firefox debugger showed that grafana & grafana zabbix is fetchind data with itemids and getting reply back with itemids (I did not cross reference). But Grafana displays error message "no datapoints". On JSON-level it shows that JSON table/array is transferred.

**Comment by clems94** [comment]
can you get trends with the curl ?

**Comment by joriws** [comment]
Yes I do the CURL reply for trends like already stated that firefox debugger shows the data

$ curl -i -n -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"item.get","params":{"output":["name","key_","value_type","delay"],"sortfield":"name","webitems":true,"filter":{"value_type":[0,3]},"monitored":true,"searchByAny":true,"hostids":["10621"],"applicationids":["1651","1739"]},"auth":"edc7f0c34534536457556b388a99c0a3b4a6c9","id":1}' http://127.0.0.1/zabbix/api_jsonrpc.php | less

Date: Tue, 05 Jan 2016 16:05:39 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.11
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000
Transfer-Encoding: chunked
Content-Type: application/json

{"jsonrpc":"2.0","result":[{"itemid":"161017","name":"....

860kB of trends data...

**Comment by clems94** [comment]
no it reply for the history because you call the method item.get, use the method trends.get to get the trends.

**Comment by joriws** [comment]
Sorry my bad, trends.get is working as well

curl -i -n -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"trends.get","params":{"output":"extend","itemids":"127833","history":0},"auth":"edc7f0ca73454776e4388a99c0a3b4a6c9","id":1}' http://127.0.0.1/zabbix/api_jsonrpc.php | less

{"jsonrpc":"2.0","result":[{"itemid":"127833","clock":"1422748800","num":"1","value_min":"0.0006","value_avg":"0.0006","value_max":"0.0006"},{"itemid":"127833","clock":"1422752400","num":"2","value_min":"0.0006","value_avg":"0.0008","value_max":"0.0011"},{"itemid":"127833","clock":"1422756000","num":"2","value_min":"0.0000","value_avg":"0.0000","value_max":"0.0000"},{"itemid":"127833","clock":"1422759600","num":"2","value_min":"0.0000","value_avg":"0.0000","value_max":"0.0000"},{"itemid":"127833","clock":"1422763200","num":"2","value_min":"0.0000","value_avg":"0.0000","value_max":"0.0000"}

**Comment by clems94** [comment]
great so like me you have to modfy the line 209 of file zabbixAPIWrapper.js with :+1: 

history: value_type, instead of trend: value_type,

i have just see thate i made an error on my comment of 8 hours ago

**Comment by joriws** [comment]
Thanks for support, making line 209 change "trend: value_type" to "history: value_type" indeed fixed it for me as well.

I starter realizing from "items.get" API-call (JSON bit was capture from firefox debugger) that Grafana-Zabbix is querying wrong with item.get instead of trends.get.

**Comment by clems94** [comment]
fine i think my modification have to be put on the code

**Comment by alexanderzobnin** [comment]
@clems94 , @joriws Are you use [ZBXNEXT-1193](https://support.zabbix.com/browse/ZBXNEXT-1193) patch? Strange, because method called `trend.get`.

**Comment by clems94** [comment]
I use ZBXNEXT-1193 patch

**Comment by alexanderzobnin** [comment]
Can you provide content of `CApiServiceFactory.php` file?

**Comment by joriws** [comment]
Alex, yes I also installed ZBXNEXT-1193 patch after you notified about it on this issue.. 

# less /usr/src/grafana-zabbix/frontend/include/classes/api/CApiServiceFactory.php
                        'application' => 'CApplication',
                        'configuration' => 'CConfiguration',
                        'dcheck' => 'CDCheck',
                        'dhost' => 'CDHost',
                        'discoveryrule' => 'CDiscoveryRule',
                        'drule' => 'CDRule',
                        'dservice' => 'CDService',
                        'event' => 'CEvent',
                        'graph' => 'CGraph',
                        'graphitem' => 'CGraphItem',
                        'graphprototype' => 'CGraphPrototype',
                        'host' => 'CHost',
                        'hostgroup' => 'CHostGroup',
                        'hostprototype' => 'CHostPrototype',
                        'history' => 'CHistory',
                        'hostinterface' => 'CHostInterface',
                        'image' => 'CImage',
                        'iconmap' => 'CIconMap',
                        'item' => 'CItem',
                        'itemprototype' => 'CItemPrototype',
                        'maintenance' => 'CMaintenance',
                        'map' => 'CMap',
                        'mediatype' => 'CMediatype',
                        'proxy' => 'CProxy',
                        'service' => 'CService',
                        'screen' => 'CScreen',
                        'screenitem' => 'CScreenItem',
                        'script' => 'CScript',
                        'template' => 'CTemplate',
                        'templatescreen' => 'CTemplateScreen',
                        'templatescreenitem' => 'CTemplateScreenItem',
                        'trend' => 'CTrend',
                        'trigger' => 'CTrigger',
                        'triggerprototype' => 'CTriggerPrototype',
                        'user' => 'CUser',
                        'usergroup' => 'CUserGroup',
                        'usermacro' => 'CUserMacro',
                        'usermedia' => 'CUserMedia',
                        'httptest' => 'CHttpTest'
                ), $objects));
        }
}

**Comment by joriws** [comment]
This is the fix in patch format

# diff -Naur zabbixAPIWrapper.js~ zabbixAPIWrapper.js
--- zabbixAPIWrapper.js~        2016-01-05 12:41:06.000000000 +0000
+++ zabbixAPIWrapper.js 2016-01-05 16:29:19.516238065 +0000
@@ -206,7 +206,7 @@
         var itemids = _.map(items, 'itemid');
         var params = {
           output: 'extend',
-          trend: value_type,
+          history: value_type,
           itemids: itemids,
           sortfield: 'clock',
           sortorder: 'ASC',

**Comment by alexanderzobnin** [comment]
@joriws it's a Zabbix frontend part.

**Comment by alexanderzobnin** [comment]
May be there are different Trend patch versions? This feature isn't part of official Zabbix api and this is a problem. Wait for stable Zabbix 3.0 release...

**Comment by little7777** [comment]
I patched my zabbix 2.2.8 but i can not see the trend in my grafana dashboard.
I've got this error  “Timeseries data request error”

I am running ：
 zabbix-server  2.2.3  ,
 grafana-zabbix-2.5.1 
grafana-2.5.0 

and i alter the file   zabbixAPIWrapper.js according to 
![image](https://cloud.githubusercontent.com/assets/11831750/12386627/c9b02b04-be01-11e5-8082-73592710fcfe.png)

I don‘t know how to fix it ,
Did I use wrong Zabbix patch for my zabbix of  2.2.3 version？
can you help me？

**Comment by clems94** [comment]
hi little7777

Can u test these request on your zabbix api ?

curl -i -X POST -H 'Content-Type:application/json' -d'{"jsonrpc": "2.0","method":"user.authenticate","params":{"user":"admin","password":"password"},"auth": null,"id":0}' http://zabbix/api_jsonrpc.php

trend get

curl -i -n -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"trends.get","params":{"output":"extend","itemids":"id u wanna get on zabbix db","history":0},"auth":"auth string","id": 1}' http://zabbix/api_jsonrpc.php

**Comment by little7777** [comment]
thanks you repay so soon！
I find the problem ，because I have patched  my zabbix two times，so that the
 file /usr/share/zabbix/api/classes/CTrends.php appear error。
I saw the apache error log  and find the tips。。。

[Mon Jan 18 17:00:42 2016] [error] [client 210.78.137.37] PHP Parse error:  syntax error, unexpected '<' in /usr/share/zabbix/api/classes/CTrends.php on line 281

I am so  stupid！

now the trend data can get ok。

thanks you so much！
