### ISSUE TITLE
Plugin 4.2.2 and 4.2.1 - broken time series, broken graph

### ISSUE THREAD

**Issue by splitek** [alexanderzobnin/grafana-zabbix#1300]
**Describe the bug**
With plugin v4.2.2 and v4.2.1 graphs are broken. It looks like some time series data is not drawn in proper point on X axis. I observed that this effect is visible when longer time period is selected (7 days and more). Perhaps it has to do with the amount of data to be drawn.  

**Screenshots**
![plugin-bug](https://user-images.githubusercontent.com/70855830/133085591-13ca845b-5d1c-4fcf-a5b2-7a16fc98889f.png)

We returned to the plugin 4.1.5, which works correctly

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.1.2. | 5.0.14 | 4.2.2                 |
| 8.1.2. | 5.0.14 | 4.2.1                 |
Option "Direct DB Connection" - disabled

**Comment by alexanderzobnin** [comment]
Interesting. Looks like points are unsorted. This
>this effect is visible when longer time period is selected (7 days and more)

means it happens only when trend is using. So I'll fix it.
