### ISSUE TITLE
Alert rule rpc error

### ISSUE THREAD

**Issue by lazarm28** [alexanderzobnin/grafana-zabbix#1302]
Hi!
I wanted to set an alert to CPU Utilization graph in my dashboard. The datas comes from zabbix server perfectly. When I want to setup the alert rule this error message come up. 
`"tsdb.HandleRequest() error rpc error: code = Unavailable desc = transport is closing"`

![Képkivágás](https://user-images.githubusercontent.com/55584774/133608746-09e72945-0509-48a7-8759-a3e4c4ce538a.PNG)

![Képkivágás1 1](https://user-images.githubusercontent.com/55584774/133608791-7f917970-c3aa-4e14-90c4-d5ce5a642d72.PNG)

I tried to set up another graph with another pc in the same network. But that works perfectly fine, when I tried to set up an alert.
The RPC Services are running in both pc. 
Have anyone has a solution for this? Thanks for the help!

Grafana version: 7.5.7
Plugin version: 4.1.5

**Comment by alexanderzobnin** [comment]
Hi! try to update plugin, I fixed some similar errors.
