### ISSUE TITLE
An unexpected error happened while variable creating

### ISSUE THREAD

**Issue by someconservator** [alexanderzobnin/grafana-zabbix#1304]
**Describe the bug**
If when creating a variable there is a Zabbix in the data source, then "an unexpected error happened" occurs upon attempt to change the data source.

The details:
TypeError: this.props.datasource.zabbix is undefined

t@http://grafana.local:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js:1:122078
div
div
div
u@http://grafana.local:3000/public/build/app.843e85298b12060ea650.js:4687:232647
h@http://grafana.local:3000/public/build/app.843e85298b12060ea650.js:4687:233220
div

and so on

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|  Grafana v8.1.1 (90c87a52f7)  | zabbix_server (Zabbix) 5.4.1  |  Grafana-Zabbix Plugin 4.2.1  |

**Comment by alexanderzobnin** [comment]
Duplicated, fixed in 4.2.3
