### ISSUE TITLE
Grafana Stable Version to use this plugin

### ISSUE THREAD

**Issue by zeduperes** [alexanderzobnin/grafana-zabbix#1305]
@alexanderzobnin what is the best stable version to use this plugin?

Grafana 8.0.6 or Grafana 8.1.4 ?

Plugin Version: 4.2.2

Thanks

**Comment by alexanderzobnin** [comment]
8.1.4 should work pretty good.

**Comment by zeduperes** [comment]
> 8.1.4 should work pretty good.

Thanks,

What about 8.1.5 + Plugin Version: 4.2.3 (release yesterday) ? 
Are both stable for production and large environment ?
