### ISSUE TITLE
Don't get TEXT values in the Drop-down item list.

### ISSUE THREAD

**Issue by yerrysherry** [alexanderzobnin/grafana-zabbix#131]
Hallo,

grafana: 2.6.0-beta1
grafana-zabbix-plugin: latest
zabbix: 2.2.1

After selecting Group,Host,Application, I only can select number variables in the item Drop-down list, no text values.

So, with the "Application: Zabbix agent". I can only select "All", and "Agent ping". 

In Zabbix, I see the text variables:
-  "Host name of zabbix_agentd running" 
- "Version of zabbix_agent(d) running"

Any ideas wgy text values are not displayed?

Regards,
Gerrit

![grafana_item](https://cloud.githubusercontent.com/assets/2222462/11978236/2e63a918-a98a-11e5-8f80-4c2235256b53.png)

![zabbix_agent](https://cloud.githubusercontent.com/assets/2222462/11978484/373c7f90-a98c-11e5-913c-3a7f22c3a3ff.png)

**Comment by alexanderzobnin** [comment]
Hi, @yerrysherry ! Just change editor mode to "Text metrics". Sorry, need to add this feature to docs.
![kazam_screenshot_00000](https://cloud.githubusercontent.com/assets/4932851/11979100/92290c88-a9a1-11e5-824a-b83704ac3001.png)

**Comment by yerrysherry** [comment]
Thank you very much!!! So easy.

 Pity that there is no filter option.

**Comment by alexanderzobnin** [comment]
@yerrysherry Yes, I just don't added in master branch. Need to fix it.
