### ISSUE TITLE
groupBy/aggregateBy handles interval improperly

### ISSUE THREAD

**Issue by proton-ab** [alexanderzobnin/grafana-zabbix#1310]
**Describe the bug**
Attempting to use full intervals (such as 1h) in groupBy/aggregateBy will result in improper aggregation producing bogus data. The cause of the issue is in `GetTimeFrame` using `time.Round` function which rounds values UP when halfway. That is, for interval of 1h, every group will perform aggregation function on data points -30m and +29m apart.

**Expected behavior**
Given time-series with data points every 1m, applying `groupBy(1h, sum)` will provide same result for group `02:00` as manually summing all 60 data points between 02:00 and 03:00.

**Comment by alexanderzobnin** [comment]
@proton-ab good catch, I changed `time.Truncate()` to `time.Round()` to make data more accurate in some cases, but looks like it causes more problems than solves.
