### ISSUE TITLE
Expression math to calculate new values

### ISSUE THREAD

**Issue by giovanny07** [alexanderzobnin/grafana-zabbix#1314]
**Is your feature request related to a problem? Please describe.**
use the math expression function to calculate new values ​​obtained from zabbix to display
![image](https://user-images.githubusercontent.com/69469456/134578060-3c0b6dc5-66c8-44d6-9e48-3c93dc117f13.png)

**Comment by framegrace** [comment]
Sorry to reply on a seems closed ticket. But this is not working
Adding any expression turns the graphs blank. no matter if hidden or not.
Tried on grafana 8.x and 9.x.
