### ISSUE TITLE
Templating with Text metrics

### ISSUE THREAD

**Issue by yerrysherry** [alexanderzobnin/grafana-zabbix#132]
Hallo,

I try to use templates with text metrics but I only get non text metrics back. I think there is no way saying that this variable is a text value.

Regards,
Gerrit

**Comment by alexanderzobnin** [comment]
Hello! Yes, now templated variables returns only numeric metrics.

**Comment by onallion** [comment]
Would be very helpful for templating the alias of network interfaces on switches. Right now the only solution is to copy them down manually :(
