### ISSUE TITLE
Parameter "/user" is deprecated - empty graphs

### ISSUE THREAD

**Issue by sebruant** [alexanderzobnin/grafana-zabbix#1322]
Hello, 

after adding zabbix source looks everything fine, "Save & Test" button shows "Zabbix API version: 5.4.5"

But there is an error in my nginx error.log and graphs on dashboards are empty.

2021/10/02 02:32:07 [error] 983#983: *15318 FastCGI sent in stderr: "PHP message: PHP Notice:  Parameter "/user" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 993" while reading response header from upstream, client: 127.0.0.1, server: mon.server.org, request: "POST /api_jsonrpc.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "127.0.0.1:8080"

Thank you for your great work.

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.1.4  | 5.4.5  |    4.2.4              |

**Comment by zeebos** [comment]
Hi, 

I have the same error:

[error] 21#21: *1568 FastCGI sent in stderr: "PHP message: PHP Notice:  Parameter "/user" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 993" while reading response header from upstream, client: 192.168.127.131, server: zabbix, request: "POST /api_jsonrpc.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "192.168.127.128:8080"

Running grafana 8.3.6, zabbix 5.4.10, grafana-zabbix plugin 4.2.4

Would be much appriciated with some light on this issue.
Thank you for your awsome work.

**Comment by zeebos** [comment]
Found out I had entered "admin" when it should have been "Admin" after changing that it worked fine

**Comment by sebruant** [comment]
It works, thank you.
