### ISSUE TITLE
request failed, status: 401 Unauthorized

### ISSUE THREAD

**Issue by rodrigorega** [alexanderzobnin/grafana-zabbix#1327]
**Describe the bug**
I updated to Grafana 8.1.6 + grafana-zabbix 4.2.4. After that I am getting the message "request failed, status: 401 Unauthorized" both in the dashboard and in datasource settings.

**Expected behavior**
Instedad of error "request failed, status: 401 Unauthorized" I expect to get Zabbix alerts in my dashboard and no error in datasource settings when I do "Save & Test".

**Screenshots**

![image](https://user-images.githubusercontent.com/3441785/136227389-826b94aa-28b1-47bd-ad3b-1f0d01318618.png)

![image](https://user-images.githubusercontent.com/3441785/136227498-08a2d5d0-a21a-4fd1-b511-939d72942d1a.png)

**Log data**
grafana.log:
```
t=2021-10-06T16:39:58 lvl=eror msg="Error querying Zabbix version" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="request failed, status: 401 Unauthorized"
t=2021-10-06T16:39:58 lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="request failed, status: 401 Unauthorized"
t=2021-10-06T16:39:58 lvl=eror msg="Request Completed" logger=context userId=3 orgId=1 uname=<REDACTED> method=POST path=/api/datasources/26/resources/zabbix-api status=500 remote_addr=<REDACTED> time_ms=142 size=86 referer=https://<REDACTED>:<REDACTED>/datasources/edit/000000026/
```

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.1.6   | 4.0.34 |   4.2.4               |

**Comment by rodrigorega** [comment]
I updated to grafana-8.0.7 and the issue is still present.

I am using basic http auth in Zabbix server, could this be related?

**Comment by dbuconn** [comment]
I think this is basic auth related. I'm also using basic auth. I upgraded to 4.2.4 today and started getting the same error as you. I restored my VM (I hadn't kept track of what version I was on) and 4.1.5 is working again. 

So something must have gone awry with basic auth and 4.2.0 onward..

**Comment by soymgomez** [comment]
Hi @alexanderzobnin , can you take a look at this issue? It takes a long time in the new versions.

**Comment by kuPyxa** [comment]
+1

**Comment by kuPyxa** [comment]
I generated the Authorization header by myself and added it to the Custom HTTP Headers in the Datasource. But it's kind of a crutch.

**Comment by alexanderzobnin** [comment]
Looks like it was bug in SDK and when http client created, basic auth settings was ignored. [This PR](https://github.com/grafana/grafana-plugin-sdk-go/pull/379) solves the issue, so I just updated dependency and checked out that basic auth should be enabled.

**Comment by Perlovka** [comment]
Same here for 4.6.1. Basic auth completely broken.
Grafrana 11.4.0
