### ISSUE TITLE
Random Connecting to Database Errors

### ISSUE THREAD

**Issue by wacheung** [alexanderzobnin/grafana-zabbix#1337]
Hi. I am receiving random "Error connecting to database" messages in Grafana, but eventually all the dashboards seem to load. Has anyone else experienced this? I usually get the error if I select a wider date range to load in Grafana.

Here is my current environment:

Zabbix Server: 5.0.16
DB: Postgresql 13.4 with TimescaleDB
Grafana: 7.5.9
Zabbix Plugin: 4.1.5

This happened after upgrade Postgresql from 10 to 13.4 and migrating to TimescaleDB.

Thanks in advance!

Grafana Logs:
`t=2021-10-26T21:18:31+0000 lvl=eror msg="Zabbix API request error" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="Error connecting to database. "`

**Comment by alexanderzobnin** [comment]
Hi! Can you upgrade plugin and check if error gone?

**Comment by wacheung** [comment]
Hi. It looks good so far after upgrading. I also had to upgrade Grafana to 8.2.2 for it to work with the newest version of the plugin.
