### ISSUE TITLE
Getting error while creating new zabbix datasource in garfana v8.2.2

### ISSUE THREAD

**Issue by HBF1** [alexanderzobnin/grafana-zabbix#1339]
hi,
Getting error while creating new zabbix datasource in garfana v8.2.2 : **_invalid character '<' looking for beginning of value_**

**Comment by alexanderzobnin** [comment]
Probably, the returned response is a HTML page (starting with `<html` tag), so it might indicate configuration error (wrong zabbix URL or another problem).

I think it makes sense to handle this and provide better error description.

**Comment by alexanderzobnin** [comment]
Maybe it should be just `http://ip.address/api_jsonrpc.php` or `https://`.
