### ISSUE TITLE
json: cannot unmarshal number into Go struct field QueryModel.queryType of type string

### ISSUE THREAD

**Issue by alecxvs** [alexanderzobnin/grafana-zabbix#1342]
**Describe the bug**
We recently upgraded from 4.1.2 to 4.2.4, and one of our users noticed that Zabbix panel alerts were not firing correctly. It's producing an error from the plugin:
`request handler response error {could not read query: json: cannot unmarshal number into Go struct field QueryModel.queryType of type string  A <nil> [] [] 0xc004b53740}`

**Expected behavior**
No Go error to be thrown from the plugin

**Screenshots**

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.2.3   | 4.0.30  | 4.2.4                 |

It seems like the related difference between these versions is that query types (or modes) used to be numbers, but were converted to strings.

If I check the dashboard json, indeed the panels still have numbers in queryType. The panel json inspector shows a string type, though. If the expectation is that we edit each panel to apply the migration, I suppose there's no issue here. But maybe there's an improvement here if the backend is supposed to handle the change passively, or if it should throw a better error that explains that a migration edit is necessary

**Comment by alexanderzobnin** [comment]
Hi! Yes, looks like the panel format is outdated. But I agree, it's might be handled on the backend (by using `interface{}` type and doing type cast).

**Comment by gustavo-godoy** [comment]
Any known workaround?
