### ISSUE TITLE
/.*/ (All) Expression is no longer working

### ISSUE THREAD

**Issue by middilebeast** [alexanderzobnin/grafana-zabbix#1345]
The Expression /.*/ is no longer working 
when i query a single host with single item it works normally,
but replacing the host field with /.*/ which suppose to show item data from all hosts
it fails and return the error message below

"request failed, status: 500 Internal Server Error"

Zabbix   ver 5.4.7
Grafana ver 8.2.4
Plugin    ver  4.2.4

Note: it was working before with zabbix 4.4.4

**Comment by alexanderzobnin** [comment]
Could you search for the error in the grafana-server logs? Regex `/.*/` should work correctly, maybe there's another reason for the error?

**Comment by middilebeast** [comment]
i have the same log shown in this issue #1356
