### ISSUE TITLE
new items not showing in grafana

### ISSUE THREAD

**Issue by AlekseiSaff** [alexanderzobnin/grafana-zabbix#1348]
**Describe the bug**
The newly created item on the host is not showing in grafana. Let's say I have my custom item app_status. On host1 and host2 everything works well and I can see it in zabbix dashboard and grafana. Now let's add the same item to host3 and it's available in zabbix dashboard, but not in grafana.
What I found it's comes to the grafana after grafana restart or if I go to the zabbix datasource and click test & save on connection

Item is a text.

**Expected behavior**
New items should be available in grafana

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.2.3   | 5.4.7  | 4.2.4                 |

**Comment by simoon78** [comment]
Please try to play a bit with "Cache TTL"  parameter.

"Cache TTL: plugin caches some api requests for increasing performance. Set this value to desired cache lifetime (this option affect data like items list)."

https://alexanderzobnin.github.io/grafana-zabbix/configuration/

**Comment by alexanderzobnin** [comment]
Hi! Yes, this is due to cache on the backend. If it's important, you can reduce cache TTL to find new items quicker.
