### ISSUE TITLE
Query Page only showing 'All' but no errors anywhere that I can find

### ISSUE THREAD

**Issue by samburney** [alexanderzobnin/grafana-zabbix#135]
zabbix: 2.4.7
grafana: 2.5.0
grafana-zabbix: 2.5.1

The API is connecting as expected:
![image](https://cloud.githubusercontent.com/assets/33766/12074546/2a92a280-b1aa-11e5-8c6b-94e8bba01163.png)

But all the drop-down lists have nothing in them:
![image](https://cloud.githubusercontent.com/assets/33766/12074572/61c26690-b1ab-11e5-8dbb-b8320d06910b.png)

Any ideas how I can troubleshoot this?

Thanks!

**Comment by alexanderzobnin** [comment]
Hi, @samburney ! Try to check permissions for `api` user in zabbix.

**Comment by samburney** [comment]
Yep, the problem was with permissions, thanks!

Sam.
