### ISSUE TITLE
Zabbix alerts are disapearing with Grafana 8.3.0 

### ISSUE THREAD

**Issue by EHRETic** [alexanderzobnin/grafana-zabbix#1354]
**Describe the bug**
When I click on an alert to open it (information button), the alert disappear and reappear a few moment later (or by refreshing the page), the table fields are also disapering at the same time.

I'ts probably since last Grafana update because everything was working fine before. Update the plugin to 4.2.4 didn't help.

It's probably the same issue as before when 8.0 came out 😉

**Expected behavior**
Being able to open it and acknoledge it if required.

**Screenshots**
I clicked on the "I" in my alerts, you can see the alert & fileds completely disappeared above compared to the unaknowledge table below:
![image](https://user-images.githubusercontent.com/28634810/144481160-b0dc0797-b077-4cfd-b330-f910ecd36253.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.3.0   | 5.4.8  | 4.2.2 & 4.2.4 |

**Comment by OCrylic** [comment]
Hi,

I have the same issue.
Grafana - 8.3.3
Zabbix - 5.2.7
Grafana-Zabbix Plugin - 4.2.4

An other issue has been opened more recently on this matter: Error when attempting to click on info button in problem panel when in table mode.  #1357

**Comment by atelleira** [comment]
+1

Grafana - 8.3.2 and 8.3.4
Grafana-Zabbix Plugin - 4.2.4 and 4.2.3

**Comment by dvaltmoli** [comment]
+1

**Comment by EHRETic** [comment]
Fixed by updating to version 4.2.5, thanks! 😉
(Sorry, didn't notice it before today)
