### ISSUE TITLE
Error when attempting to click on info button in problem panel when in table mode.

### ISSUE THREAD

**Issue by majoros** [alexanderzobnin/grafana-zabbix#1357]
**Describe the bug**
This is very simaler to issue https://github.com/alexanderzobnin/grafana-zabbix/issues/1239 accept it happens when i hit the info button when in table mode, List mode is working fine.

**Expected behavior**
To display the management row or whatever it called.

**Screenshots**

![image](https://user-images.githubusercontent.com/56639/145261699-3df00413-ad7c-4eec-87f8-ed32dbed123e.png)
when clicked give me....
![image](https://user-images.githubusercontent.com/56639/145261771-960da803-35cc-4ab1-bd83-44aa277b4c49.png)

**Network data**
No data requests are made an exception is thrown before it even attempt to make a request.

`Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20uid%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ja (http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:757387)
    at http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:762208
    at Di (http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:773194)
    at Zs (http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:819033)
    at Su (http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:804500)
    at ku (http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:804428)
    at wu (http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:804291)
    at mu (http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:801278)
    at http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:751065
    at t.unstable_runWithPriority (http://10.1.202.14:30852/public/build/633.fab5d6bbd438adca1160.js:2:3042374)`

The none minified error is....

Objects are not valid as a React child (found: object with keys {type, uid}). If you meant to render a collection of children, use an array instead.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|  8.3.1 | 5.4.5  | 2.4.2                 |

**Comment by majoros** [comment]
Let me know any other info you would like to see, and thanks in advanced.

**Comment by tolstiyman** [comment]
I have the same issue.
Grafana - 8.3.1
Zabbix - 5.4.8
Grafana-Zabbix Plugin - 4.2.4

**Comment by juaromu** [comment]
Same issue with Grafana 8.3.0 and Plugin version 4.2.4

**Comment by OCrylic** [comment]
Hi,

I have the same issue.
Grafana - 8.3.3
Zabbix - 5.2.7
Grafana-Zabbix Plugin - 4.2.4

An older issue has already been opened on the same subject: #1354

**Comment by giovanny07** [comment]
Same problem

Grafana - 8.3.3
Zabbix - 5.4.9
Grafana-Zabbix Plugin - 4.2.4

**Comment by pm091** [comment]
Had this issue when upgrading to Grafana 8.3.x, as a temporary work around downgraded to 8.2.7 in order to acknowledge problems from the Grafana dashboard
