### ISSUE TITLE
Can't use a query with data source Zabbix

### ISSUE THREAD

**Issue by iRomanyshyn** [alexanderzobnin/grafana-zabbix#1358]
**Describe the bug**
Can't use a query with data source Zabbix because there is no field to create the query.

**Expected behavior**
Create a new empty panel at any dashboard with data source Zabbix. Expected to add and edit the query for the data source but there are no input fields to edit the query. Also, I see multiple errors in the browser console. It happened after the Zabbix server update probably.

**Screenshots**
![image](https://user-images.githubusercontent.com/11888301/145374968-f0e387f6-432b-4980-ae2b-aab5a485b718.png)
![image](https://user-images.githubusercontent.com/11888301/145375015-726945a6-7fac-419a-99d9-9ad97a0c411e.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.3.1   | 5.4.8  | 4.2.4                 |

**Important update**
I'm using Apache as reverse proxy, so I tried to access the Grafana directly (http:// and port 3000) but it doesn't resolve the problem and I see the same errors so it's not in Apache. I'm getting errors like `Error: [$templateRequest:tpload] Failed to load template: public/plugins/alexanderzobnin-zabbix-datasource/datasource-zabbix/partials/query.editor.html (HTTP status: 404 Not Found) https://errors.angularjs.org/1.8.2/$templateRequest/tpload?p…-zabbix%2Fpartials%2Fquery.editor.html&p1=404&p2=Not%20Found`.

**Comment by fauust** [comment]
same here

**Comment by Acutiator** [comment]
Fix is https://github.com/alexanderzobnin/grafana-zabbix/issues/1355#issuecomment-986716887

**Comment by crackfisk** [comment]
Same issue. Doesn't help reinstalling datasource. This issue occured after the security update of Grafana. Currently running 8.3.1

**Comment by zatoufly** [comment]
I have same issue.

**Comment by tiagoalmeida10** [comment]
Same issue.

**Comment by ugoleleux** [comment]
Same issue for me.

Regards

**Comment by iRomanyshyn** [comment]
To resolve the issue in easiest way, just remove the datasource plugin and install it again. Then restart the Grafana service.

```sudo grafana-cli plugins remove alexanderzobnin-zabbix-app
sudo grafana-cli plugins install alexanderzobnin-zabbix-app
sudo systemctl restart grafana-server```

**Comment by ugoleleux** [comment]
Thanks @iRomanyshyn
This actually solved the issue for me. but I already did these steps before.
I had to do it once again and the problem was solved.

Regards
Ugo

**Comment by den-schmitz** [comment]
8.3.1/8.3.2 и 4.2.4 та же проблема. После sudo systemctl restart grafana-server плагин может начать нормально работать, а может нет. По желанию. Что с этим делать пока не понятно. Более ранние версии плагина решают проблему?

**Comment by yurayko** [comment]
Works for me:
cd /var/lib/grafana/plugins
mv grafana-zabbix alexanderzobnin-zabbix-app
systemctl restart grafana-server

grafana-cli -v
Grafana CLI version 8.3.2
grafana-cli plugins ls
installed plugins:
alexanderzobnin-zabbix-app @ 4.2.4

**Comment by den-schmitz** [comment]
> У меня работает: cd / var / lib / grafana / plugins mv grafana-zabbix alexanderzobnin-zabbix-app systemctl restart grafana-server
> 
> grafana-cli -v Grafana CLI версии 8.3.2 плагины grafana-cli Установленные плагины: alexanderzobnin-zabbix-app @ 4.2.4

unfortunately, all the workarounds work for me before restarting the application. after restarting grafana-server, the problem repeats. have you tried restarting grafana several times in a row?

**Comment by yurayko** [comment]
Yes, I did it right now and all continues to work.
After rename you still see "not found" message like (after trying to see query in the web):

$grep 'not found' /var/log/grafana/grafana.log
t=2021-12-14T09:41:28+0300 lvl=eror msg="Plugin file not found" logger=context userId=1 orgId=1 uname=usser error="open /var/lib/grafana/plugins/grafana-zabbix/datasource-zabbix/datasource-zabbix/partials/query.editor.html: no such file or directory"

?

**Comment by NBSOD** [comment]
sadly all the way doesn't work for me .... 
restart grafana-server/reinstall plugins/or edit the /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js
all doesn's work , even worse

**Comment by Henry78** [comment]
How I fixed it:

```
# grafana.ini
[plugins]
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app, alexanderzobnin-zabbix-datasource, alexanderzobnin-zabbix-triggers-panel
```
```
# Fix bug (grafana-zabbix/issues/1355)
# after changing the plugin, the checksum doesn't match anymore
# So we have to remove the Manifest and allow loading of unsigned plugins (see grafana.ini)
sed -i 's/datasource-zabbix\///g' /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js
rm /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/MANIFEST.txt
```

**Comment by m4rr0c0s** [comment]
> rm /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/MANIFEST.txt

It worked for me! Thank you very much!

**Comment by lpossamai** [comment]
I'm having the same issue. [This](https://github.com/alexanderzobnin/grafana-zabbix/issues/1358#issuecomment-993578167) fixed it for me.

**Comment by m4rr0c0s** [comment]
> > rm /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/MANIFEST.txt
> 
> It worked for me! Thank you very much!

It worked at the beginning, but unfortunately stopped suddenly. But checking grafana logs, I've found this error:

_t=2021-12-14T23:25:55-0300 lvl=eror msg="Plugin file not found" logger=context userId=1 orgId=1 uname=admin error="open /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/partials/query.editor.html: no such file or directory"_

So in order to fix this, in my case on linux, I just created a symbolic link as shown bellow:

#_ln -s /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/partials/ /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/partials_

Since then I'm using without problems. I hope my fix can help you guys!

**Comment by jorlandobr** [comment]
> #_ln -s /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/partials/ /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/partials_
> 
> Since then I'm using without problems. I hope my fix can help you guys!

Helped a lot! Almost the same:

t=2021-12-20T02:21:27-0300 lvl=eror msg="Plugin file not found" logger=context userId=1 orgId=2 uname=admin error="open /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/partials/query.editor.html: no such file or directory"

Solution:

$ sudo ln -s /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix

**Comment by rrickardt** [comment]
I am on plugin version 4.2.4, this was introduced in grafana 8.3.2, present on 8.3.3 as well. So either downgrade to 8.3.1 or symlink solution in https://github.com/alexanderzobnin/grafana-zabbix/issues/1358#issuecomment-997619459 works

**Comment by alexanderzobnin** [comment]
I noticed this issue in one of the 8.3.x versions. But after a while it was fixed, so I thoughts that's it. But looks like the fix is only in main branch now, but it's not backported into 8.3. I ask grafana team about this, probably, fix is not complicated.

**Comment by alexanderzobnin** [comment]
Ok, confirmed. This is Grafana 8.3.2-8.3.3 bug. The fix will be available in both 8.4 and 8.3.4, so next Grafana release will fix the issue. I will let this open for a while until I we are sure that's fixed.

**Comment by matttb** [comment]
> Ok, confirmed. This is Grafana 8.3.2-8.3.3 bug. The fix will be available in both 8.4 and 8.3.4, so next Grafana release will fix the issue. I will let this open for a while until I we are sure that's fixed.

Any idea when this will be?

**Comment by rau-alvin** [comment]
@alexanderzobnin Hello! Unfortunately, it still does not work in the latest version of Grafana v8.3.4.

**Comment by giovanny07** [comment]
@alexanderzobnin Doesn't work in 8.3.4

**Comment by giovanny07** [comment]
The best solution is downgrade to 8.2.7. Works proppertly

**Comment by lombardialess** [comment]
I can confirm that with version 8.3.4 the problem is not solved, updated this morning :(

**Comment by mirchl** [comment]
Solution in my case:
- Update Grafana to 8.3.4 > plugin not work
- Uninstall plugin in CLI
- Restart Grafana server service
- Install plugin in CLI (and solve problem with premissions) 
- Restart Grana server service > plugin still not work
- Install plugin in Grafana GUI

Now it seems plugin work propertly.

**Comment by neothematrix** [comment]
hello,
pitching in, I'm using grafana on docker, updating the container to 8.3.4 didn't fix the plugin, I just followed @mirchl suggestion and removed and re-installed the plugin using grafana-cli, it fixed the issue for me, I didn't have to install the plugin via GUI as also suggested.

**Comment by den-schmitz** [comment]
I also confirm. 8.3.4 + 4.2.4 does not work. after each restart, the service may stop working or start. none of the above options solves the problem, errors still occur in the logs

**Comment by mjtrangoni** [comment]
@alexanderzobnin Is there any ETA on fixing this? Do you have a Grafana issue we can follow about this issue?

**Comment by fauust** [comment]
Hi @rau-alvin. Unfortunately, it's still broken here after upgrade to 8.3.6...
![screenshot_20220210_125123](https://user-images.githubusercontent.com/2197555/153403584-b0bd0ede-eba5-444d-9d1c-bfe82d9fda6c.png)

**Comment by marcelgsteiger** [comment]
I had the same issue after adding a new organization to grafana and then installing the zabbix plugin in this second organization. Then in this second organization this problem, which then also showed up on the first organization suddenly. Then I deleted the second organization again with all its users (and the corresponding dashboards and data sources, of course). In my first organization the problem persisted. Uninstalling and reinstalling the plugin made it work again.
I will check later which step caused the problem and try to reproduce it. For now I suspect the problem shows up when grafana is configured with multiple organizations with at least two trying to use the zabbix plugin.

**Comment by fauust** [comment]
Version 4.2.5 seems to resolve the issue for me.

**Comment by rau-alvin** [comment]
Unfortunatelly problem came back in Plugin v 4.2.5 for me.

It's woked in Plugin v 4.2.4.

**Comment by alecxvs** [comment]
Has anyone reproduced the issue on 8.4.x?

**Comment by Henry78** [comment]
Works here with 8.4.1 and 4.2.5. Just installed from scratch to verify. :thinking:

**Comment by lpossamai** [comment]
> I'm having the same issue. [This](https://github.com/alexanderzobnin/grafana-zabbix/issues/1358#issuecomment-993578167) fixed it for me.

I'm still facing this issue with `Grafana v8.3.2 (afb9e8e5f)` and the Zabbix Plugin `4.2.5`.

```
t=2022-02-28T22:52:35+0000 lvl=eror msg="Plugin file not found" logger=context userId=1 orgId=1 uname=admin error="open /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/partials/query.editor.html: no such file or directory"
```

Manually changing the `/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js` file and removing the extra `datasource-zabbix/datasource-zabbix` fixes it.

**Comment by philippebraxmeier** [comment]
same here with grafana 8.3.4 and 4.2.5.

**Comment by rnalrd** [comment]
just upgraded from grafana 8.2.7->8.4.5 and everything is working

**Comment by MajesticFalcon** [comment]
Upgrading to 8.4.5 fixed the issue for me

**Comment by EHRETic** [comment]
I missed 4.2.5 publication for 2 weeks but this version also works for me! 😊

**Comment by jameskirsop** [comment]
I'm on plugin version 4.2.6 and Grafana 8.4.6 and I'm still seeing issues with the `/api/ds/query` path reported in my Grafana logs.

I've checked to ensure that `/api_jsonrpc.php` is returning 200 results OK:
`172.28.16.14 - - [20/Apr/2022:12:36:38 +1000] "POST /api_jsonrpc.php HTTP/1.1" 200 11554 "-" "Grafana/grafana-zabbix"`
