### ISSUE TITLE
Datasource filter for multi-tenant Zabbix

### ISSUE THREAD

**Issue by joriws** [alexanderzobnin/grafana-zabbix#136]
I want to limit via datasource that one organization can only see it's data so data source filtering is required which could be set master admin only, not organization admin.

The filter should apply to item names (or optional host group or template or application..). Now the problem is that organization admin can make new dashboards/items and they can query all items including the ones not belonging to their organization.

Two orgs: A and B
A's admin can create new dashboard graphs with B's data

I want to limit that A can only see devices/nodes if it has string like "A.hostname" or "A.itemname" in it. And filter should be opt_in meaning everything is prohibited except matching strings.

Unfortunately I am new with Grafana so I don't know it it can already be done with Grafana somehow? I've done templated variables which I can use to limit/filter data but it does not prevent "data" to be "stolen" at multi-tenant operation.

**Comment by joriws** [comment]
The filter could even be "s///" regexp so only required portion of data could be captured and displayed on dashboard configuration. I find my items with Zabbix LDD so item names are a bit cryptic for dashboard users because they are automatically compiled on discovery.

**Comment by alexanderzobnin** [comment]
Can you do that via datasources with differen credentials in Zabbix? You need configure access rights in Zabbix, Grafana only connects to Zabbix with given login.

**Comment by joriws** [comment]
That is a good idea for some usage where you can have host groups per organization. But if we consider server data everything is coming from single server with low level discovery via template meaning all Zabbix item-data is at single host group, single host and single template.

I am not aware that Zabbix has API-restrictions to implement such filters that this API only returns data if certain string is in item name.
