### ISSUE TITLE
When i zoom in some pannel,sometimes will get a error can't show any data.

### ISSUE THREAD

**Issue by NBSOD** [alexanderzobnin/grafana-zabbix#1362]
**Describe the bug**
When i zoom in some pannel,sometimes will get a error can't show any data.
And it is not appear everytime.

**Expected behavior**
Pannel can't show data and reeport a error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41575001/147179904-b7a21f83-a15c-4df0-be44-1ab294b03cb7.png)
![image](https://user-images.githubusercontent.com/41575001/147179979-7f4e2b92-46e5-4fc2-9b74-4f00f73895aa.png)

**Network data**

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|8.3.1 | 5.2.7  | 4.3.4 |
And i use db connect for mysql  Ver 14.14 Distrib 5.7.25

**Comment by Ryuras2012** [comment]
+1 I also have this

**Comment by drajv-y** [comment]
Посмотрите временное решение в посте ниже.

Check out the temporary solution in the post below.

https://github.com/alexanderzobnin/grafana-zabbix/issues/1320

**Comment by NBSOD** [comment]
> Посмотрите временное решение в посте ниже.
> 
> Check out the temporary solution in the post below.
> 
> #1320

After i turn off Direct DB Connection, looks work allright,thanks~

**Comment by NBSOD** [comment]
https://github.com/alexanderzobnin/grafana-zabbix/issues/1320#issuecomment-961807828
Solved form this

**Comment by B3DTech** [comment]
Should not be closed!  I have Direct DV connection disabled in the datasource configuration and I still have the issue.
