### ISSUE TITLE
Can't see detail problem info

### ISSUE THREAD

**Issue by rau-alvin** [alexanderzobnin/grafana-zabbix#1363]
Hello! Thank you for great plugin!

**Describe the bug**
When i click to detail button nothing happens.

**Expected behavior**
Earlier i got start time of problem and problem information.

**Screenshots**
![image](https://user-images.githubusercontent.com/62691026/147450173-f643023d-2662-4135-a4db-d81abedaabf0.png)

**Network data**
In console of browser i see:
![image](https://user-images.githubusercontent.com/62691026/147450743-1aab3fb6-794c-47b6-984a-ba402aa3e485.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v8.3.3   | 5.0.19 + 5.4.9 | 4.2.4               |

**Comment by Punchflower** [comment]
Hi,

We have the same issue, not being able to see the detail problem info. So then we cannot "ack" Zabbix issues in Grafana anymore.

Grafana version : 8.3.1

**Comment by alves-alisson** [comment]
Same issue here! 

Grafana | Zabbix | Plugin Grafana-Zabbix
-- | -- | --
v8.3.3 | 5.4.9 | 4.2.4

**Comment by hudnall-s** [comment]
Same issue here aswell

Grafana: 8.3.3
Zabbix 5.4.7
Plugin 4.2.4

**Comment by tcsi-github** [comment]
Thought I was losing my mind.... Good, it's not just me. :-)

**Comment by rau-alvin** [comment]
Unfortunately, it still does not work in the latest version of Grafana v8.3.4.

**Comment by hudnall-s** [comment]
I tried to build the latest code and up the plugins to latest go versions, still did not help. 

imo this is one of the bigger issues with this plugin that needs to be fixed.

**Comment by alinex** [comment]
Also waiting for a fix, please.

**Comment by alexanderzobnin** [comment]
Duplicates #1357
