### ISSUE TITLE
ETA on fix for empty Query?

### ISSUE THREAD

**Issue by matttb** [alexanderzobnin/grafana-zabbix#1367]
Ive tried nightly and beta builds of Grafana but they all still effectively kill the Zabbix plugin. Is there and ETA on a fix?

**Comment by hudnall-s** [comment]
if you look at the logs it is showing that the files can not be found. Simple solution is to just copy the folder one layer deep in itself. That is how I got around it anyways

**Comment by brunoscota** [comment]
I have the same issue after updating my grafana to the last version (Grafana v8.3.6 (bf8766bbf2))

**Comment by alexanderzobnin** [comment]
Hi! It looks like issue is fixed in latest Grafana builds, so I'm closing this.
