### ISSUE TITLE
Filter on text metrics

### ISSUE THREAD

**Issue by clems94** [alexanderzobnin/grafana-zabbix#137]
I would like to know if it is possible to filter text metrics.

**Comment by alexanderzobnin** [comment]
@clems94 I implemented this feature, but don't merge it yet. I will merge it soon.

**Comment by clems94** [comment]
very good news.

On wich branch could i find it ?

**Comment by alexanderzobnin** [comment]
This code on [feature-text_metrics](https://github.com/alexanderzobnin/grafana-zabbix/tree/feature-text_metrics) branch, but I need to merge it to master.
