### ISSUE TITLE
Failed to query data: rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by YannMCX** [alexanderzobnin/grafana-zabbix#1370]
**Describe the bug**
Unable to access Zabbix data through the API, connection of the plugin was successful, but no data can be fetched

Error message in grafana.log "Failed to query data: rpc error: code = Canceled desc = context canceled"

**Expected behavior**
Abillity to fetch data from Zabbix API

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.3.3   | 5.4.8  | 4.2.4                 |

Note: I was able to fix my problem by downgrading to version 4.2.2 of the plugin

**Comment by przytular** [comment]
Why this issue is closed? I still have problems (version 4.2.10), my grafana suddenly stopped showing any data (only "No data") and in logs same error "Failed to query data: rpc error: code = Canceled desc = context canceled"

I don't think downgrading plugin is proper way of fixing this...
