### ISSUE TITLE
Unable to install on servers which are not connected to internet

### ISSUE THREAD

**Issue by AviPairupuni** [alexanderzobnin/grafana-zabbix#1371]
I tried to install on server which is in DMZ and do not connect to internet and while trying to install this plugin with grafana cli it tries to connect to the internet and installation fails.  How can this be fixed?

Regards, 
Avi

**Comment by YannMCX** [comment]
Download plugin from github release and transfer it to you grafana server, then place it in /var/lib/grafana/plugins

Btw, you can't download thing remotely without internet.
