### ISSUE TITLE
Incorrect work of the filter in Application

### ISSUE THREAD

**Issue by DynamitM** [alexanderzobnin/grafana-zabbix#1373]
If the regular expression does not find anything in the Application, then the search goes on Item, although it should show no data. 
 
 
Software versions 
| Grafana | Zabbix | Grafana-Zabbix Plugin | 
| ------- | ------ | --------------------- | 
| 8.2.1   | 5.0.11  | 4.2.4                |

**Comment by alexanderzobnin** [comment]
Hi! I think it's the same as #1427
