### ISSUE TITLE
Disabled ACK, Empty Information Icon.

### ISSUE THREAD

**Issue by lamentia** [alexanderzobnin/grafana-zabbix#1376]
**Describe the bug**
Can't click/change/see ACK in Zabbix problems. Also if I click to information icon, next to problem, receiving empty query.

**Expected behavior**
After clicking ACK expecting that I can write information about problem or change severity. 

**Screenshots**

![1](https://user-images.githubusercontent.com/53076000/151336662-1881ab62-c23d-4778-9674-45deff0d1a6f.png)

Cursor is over ACK nothing pops up.

After clicking information icon 

![2](https://user-images.githubusercontent.com/53076000/151336746-d09bc564-5b22-4a1d-b568-28a601350485.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v8.3.4   | 4.2  | 4.2.4                 |

**Comment by alexanderzobnin** [comment]
Duplicates #1357
