### ISSUE TITLE
negative lookbehind regex stopped working in queries since zabbix plugin 4.2.0 

### ISSUE THREAD

**Issue by herraa1** [alexanderzobnin/grafana-zabbix#1383]
**Describe the bug**
Up to zabbix-plugin 4.1.5 a query with an item selection using a negative lookbehind regular expression [syntax (?<!foo)] works without problems.
Upgrading the zabbix-plugin to 4.2.0 or later (tested up to 4.2.4) makes the query non-functional (and no matching results are returned).

**Expected behavior**
The query should be working as before 4.2.0.
Sample item selection json with regex matching items with a specific part of text not ending in _root nor _excl:

"item": {
            "filter": "/Volume \\[VAULT_.*(?<!_root|_excl)\\] \\[XYZ-.*\\] Used/"
          },

This works up to 4.1.5 and stops working once zabbix plugin is upgraded to 4.2.0 or later.
Downgrading the zabbix plugin to 4.1.5 fixes the issue.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.3.4   | 5.0.8  | 4.2.0 up to 4.2.4                 |

**Comment by i-ky** [comment]
Duplicates #1264.

**Comment by vldbel** [comment]
![image](https://user-images.githubusercontent.com/13711403/164110290-e4dbe8b0-4e70-45b0-ae4e-7d62498b43f0.png)
@alexanderzobnin . Seems actual on 4.2.6. Could you please  take a look?
