### ISSUE TITLE
Error "json: invalid use of ,string struct tag, trying to unmarshal unquoted value into int64"

### ISSUE THREAD

**Issue by Ethan0451** [alexanderzobnin/grafana-zabbix#1386]
Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
8.3.1 | 5.4.9 | 4.2.4

A few days ago , I updated the zabbix from 5.2.2 to 5.4.9
At the same time , I reinstall the grafana and grafana-zabbix plugin , but when I create the panel , I got this error
By the way , my zabbix use Elasticsearch to store history data

Thanks for helping

[grafana.log](https://github.com/alexanderzobnin/grafana-zabbix/files/8020338/grafana.log)
[request_details.txt](https://github.com/alexanderzobnin/grafana-zabbix/files/8020379/request_details.txt)

**Comment by nikossss** [comment]
solved the problem? please help me

**Comment by nikossss** [comment]
yes, i m use elastic. thank you, i replace a few line, how to compiled?

**Comment by nikossss** [comment]
please tell me how to compiled?

**Comment by Ethan0451** [comment]
> please tell me how to compiled?

https://alexanderzobnin.github.io/grafana-zabbix/installation/run_from_master/

**Comment by nikossss** [comment]
ansible@ansible:~/grafana-zabbix-4.2.9$ make dist
yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
make: *** [Makefile:42: dist-frontend] Error 1
ansible@ansible:~/grafana-zabbix-4.2.9$ sudo make dist
yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
make: *** [Makefile:42: dist-frontend] Error 1
don't work

**Comment by nikossss** [comment]
don,t work(

    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [../node_modules/css-loader/dist/cjs.js!../node_modules/sass-loader/dist/cjs.js!./sass/grafana-zabbix.dark.scss] 41.1 KiB {0} [built]
        + 2 hidden modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/dist/cjs.js!../node_modules/sass-loader/dist/cjs.js!sass/grafana-zabbix.light.scss:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [../node_modules/css-loader/dist/cjs.js!../node_modules/sass-loader/dist/cjs.js!./sass/grafana-zabbix.light.scss] 41.1 KiB {0} [built]
        + 2 hidden modules
Infinitely performs
problem signed plugin

could you build for me 4.2.9 ver ?
