### ISSUE TITLE
Examples of host queries?

### ISSUE THREAD

**Issue by Bonn93** [alexanderzobnin/grafana-zabbix#139]
I've been playing around with this and would be great if I can make single stats against a host filter, for example;

single stat > filter hosts test-server-01,test-server-02 and have it display the total number of vCPUs assigned, but other metrics too? 

I've no idea how I can use the host filters so I only get a few hosts, not all?

**Comment by alexanderzobnin** [comment]
For instance: host01 have 2 vCPU and host02 have 4 vCPU. And you want to show 6 vCPU at Singlestat, right?

**Comment by Bonn93** [comment]
that's correct.

**Comment by alexanderzobnin** [comment]
It's related to #60. I'm going to implement aggregations in version 3.0.

**Comment by Bonn93** [comment]
Great, it would be really handy for us, being able to to give a dashboard per project and team resource usage. any idea on ETA?
