### ISSUE TITLE
New Zabbix hostgroups not syncing on Grafana

### ISSUE THREAD

**Issue by deepaksharma17** [alexanderzobnin/grafana-zabbix#1392]
Hi All,
After creating new Zabbix hostgroups and giving read permission to the Grafana user (used on Grafana Zabbix datasource), the new hostgroups are not visible on the Grafana? 
Other than default datasource settings (like URL, credentials, etc), I have these settings
![image](https://user-images.githubusercontent.com/38524614/153558185-42f8db3c-5627-48ef-b5ed-fc1472571f17.png)
Does someone else also see the same issue?
Looks like hostgroups will be visible only when they have hosts with assigned monitors (templates), is that true?

**Comment by deepaksharma17** [comment]
I had waited for the whole day, still, it didn't come, that's the issue?

**Comment by Sam-H101** [comment]
are there any servers in these host groups?

**Comment by deepaksharma17** [comment]
Hi Sam, there are no servers in the hostgroups, That's the same I had mentioned above, the hosts are only visible when there is a host in the hostgroup with some monitors, but want to confirm is it an issue or by design?

**Comment by eertul** [comment]
Check the rights of the user that you are using while connecting to zabbix. New added host groups may not be authenticated by default.

**Comment by alexanderzobnin** [comment]
Hi! Yes, as mentioned above, only host groups which contain hosts are returning (this made by `real_hosts` flag in API call). If your group doesn't contain any hosts, then you cannot select any item from it, so it does not make sense to show it. Let me know if you have any use case for it.
