### ISSUE TITLE
Panel of problems sorted by severity

### ISSUE THREAD

**Issue by giovanny07** [alexanderzobnin/grafana-zabbix#1395]
**Describe the bug**
The severity tab in the issues panel sorts by host grouping and not overall severity.

**Expected behavior**
View in order of severity (date or host does not matter) from disaster, high, average, warning, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/69469456/154076089-6d9038b9-8536-43d5-b75b-ce3d0bb03289.png)
![image](https://user-images.githubusercontent.com/69469456/154076220-5f0943b1-2bc2-45f5-812b-854c0dceec7f.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.2.7   | 5.4.9  | 4.2.4                |

**Comment by Sam-H101** [comment]
@giovanny07 what is your options value for Sort By?

![image](https://user-images.githubusercontent.com/25128322/154151995-47e48f3d-e272-46f2-b2e8-2d9bbb95b527.png)

**Comment by giovanny07** [comment]
Yes! Thanks for the answer
