### ISSUE TITLE
zabbix 6

### ISSUE THREAD

**Issue by hellmany** [alexanderzobnin/grafana-zabbix#1396]
I think something wrong with zabbix 6 API, could you check it.

**Comment by alexanderzobnin** [comment]
Ok, will do.

**Comment by i-ky** [comment]
Some investigation done by @Sam-H101 in https://github.com/alexanderzobnin/grafana-zabbix/issues/1398#issuecomment-1048238231

**Comment by mbuyukkarakas** [comment]
Same problem. Needs fixing.

**Comment by isaqueprofeta** [comment]
As @1vicente said on #1408 (https://github.com/alexanderzobnin/grafana-zabbix/issues/1408#issuecomment-1068338898):

> Hi Dears,
> 
> The method "[service.getsla](https://www.zabbix.com/documentation/5.0/en/manual/api/reference/service/getsla)" was changed to "[sla.getsli](https://www.zabbix.com/documentation/current/en/manual/api/reference/sla/getsli)".
> 
> With this change, some fields changed in response result, such as sla to sli.
> 
> I think that criticals informations in both method are:
> 
> **service.getsla**.....->....**sla.getsli** sla .....................->...sli okTime...............->...uptime problemTime......->...error_budget downtimeTime...->...downtime
> 
> May these pieces of information help you to fix it.
> 
> Through fix, we'll can to create beautiful dashboards again.
> 
> Thanks to keep development!

**Comment by alexanderzobnin** [comment]
Closing this in favor of #1408 (that issue has better description, so it's easier to search).
