### ISSUE TITLE
Trend error when connecting to Zabbix 2.4 (with plugin installed)

### ISSUE THREAD

**Issue by slangloisde** [alexanderzobnin/grafana-zabbix#1406]
**Describe the bug**
After migrating to latest version, when using Trends with Zabbix 2.4.8 (Plugin is installed), query results in an error

"response": {
    "results": {
      "A": {
        "error": "Invalid params. Incorrect API \"trend\".",
        "frames": [],
        "refId": "A"

We have another Zabbix ver. 5 server and we don't see the problem with that one, specific to the 2.4 one.

**Expected behavior**
The exact same graph displays correctly on previous Grafana with no errors on version we had before (Grafana 7.5.11, Grafana-zabbix 4.0.2).

**Screenshots**
![image](https://user-images.githubusercontent.com/43825188/156847684-88f0d8df-0a63-404d-900e-1c3f436e900e.png)

**Network data**
`{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "refId": "A",
          "key": "Q-35baba11-bee6-4c54-a8b1-36c7c4613659-0",
          "resultFormat": "time_series",
          "itemTag": {
            "filter": ""
          },
          "queryType": "0",
          "group": {
            "filter": "Zabbix servers"
          },
          "host": {
            "filter": "Zabbixserver"
          },
          "application": {
            "filter": ""
          },
          "item": {
            "filter": "Available memory in %"
          },
          "functions": [],
          "triggers": {
            "count": true,
            "minSeverity": 3,
            "acknowledged": 2
          },
          "trigger": {
            "filter": ""
          },
          "tags": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "options": {
            "showDisabledItems": false,
            "skipEmptyValues": false,
            "disableDataAlignment": false,
            "useZabbixValueMapping": false
          },
          "table": {
            "skipEmptyValues": false
          },
          "datasource": {
            "type": "alexanderzobnin-zabbix-datasource",
            "uid": "000000001"
          },
          "datasourceId": 1,
          "intervalMs": 300000,
          "maxDataPoints": 1488
        }
      ],
      "range": {
        "from": "2022-02-25T21:31:58.987Z",
        "to": "2022-03-04T21:31:58.987Z",
        "raw": {
          "from": "now-7d",
          "to": "now"
        }
      },
      "from": "1645824718987",
      "to": "1646429518987"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "error": "Invalid params. Incorrect API \"trend\".",
        "frames": [],
        "refId": "A"
      }
    }
  }
}`

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.3.4  | 2.4.8  | 4.2.5                |

**Comment by jameskirsop** [comment]
@slangloisde, Zabbix versions older than 4.0 are [not supported](https://alexanderzobnin.github.io/grafana-zabbix/installation/) by this plugin.

**Comment by alexanderzobnin** [comment]
Hi! Zabbix 2.4 does not support trend api, so it won't work.
