### ISSUE TITLE
dashboard not included in plugin

### ISSUE THREAD

**Issue by skala-vl** [alexanderzobnin/grafana-zabbix#1407]
**Describe the bug**
New installation on Centos8
I installed Zabbix, Grafana and I want to connect zabbix and grafana

**Expected behavior**
I try to install olde versions alexanderzobnin-zabbix-app like 
4.2.4
4.2.3
4.2.1
4.1.5
4.1.1
4.1.0
4.0.2
4.0.0
3.12.4
3.12.3
they all have the same error

 

**Screenshots**
![image](https://user-images.githubusercontent.com/10527381/156874553-701a603b-2e6d-4ad4-9472-292585c3fac0.png)
LOG:
logger=context t=2022-03-05T18:04:00.21+1000 lvl=eror msg="Failed to get plugin dashboards" error="**dashboard not included in plugin**" remote_addr=__.__.__.__
logger=context t=2022-03-05T18:04:00.22+1000 lvl=eror msg="Request Completed" method=GET path=/api/plugins/alexanderzobnin-zabbix-datasource/dashboards status=500 remote_addr=__.__.__.__ time_ms=1 size=45 referer=http://__.__.__.__:3000/datasources/edit/QTSvzNLnk/dashboards

When select New Dashboard
![image](https://user-images.githubusercontent.com/10527381/156874655-410b3f16-0c33-42e2-92b5-1a33dc3f4eab.png)
in log this errors: 
logger=context t=2022-03-05T18:06:33.43+1000 lvl=eror msg="Query data error" error="**failed to query data: Failed to query data**: rpc error: code = Canceled desc = context canceled" remote_addr=__.__.__.__
logger=context t=2022-03-05T18:06:33.43+1000 lvl=eror msg="Request Completed" method=POST path=/api/ds/query status=500 remote_addr=__.__.__.__ time_ms=93 size=30 referer="http://__.__.__.__:3000/dashboard/new?utm_source=grafana_gettingstarted&orgId=1&editPanel=2"

**Software versions**
[alexey@main grafana]$ sudo grafana-cli plugins ls
installed plugins:
alexanderzobnin-zabbix-app @ **4.2.5**
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.

[alexey@main grafana]$ rpm -qa | grep -e zabbix
zabbix-web-mysql-5.0.21-1.el8.noarch
zabbix-agent-5.0.21-1.el8.x86_64
zabbix-web-5.0.21-1.el8.noarch
zabbix-web-deps-5.0.21-1.el8.x86_64
zabbix-server-mysql-**5.0.21**-1.el8.x86_64
zabbix-release-5.0-1.el8.noarch
[alexey@main grafana]$ rpm -qa | grep -e grafana
grafana-**8.4.3**-1.x86_64
[alexey@main grafana]$ uname -r
4.18.0-365.el8.x86_64
[alexey@main grafana]$ 

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.4.3   | 5.0.21  | 4.2.5                 |

Similar requests
https://community.grafana.com/t/failed-to-call-resource-error-when-fetching-data-from-a-specific-host/52054

Please help me figure out what the issue is.

**Comment by JayEkin** [comment]
Similarly, I also see the issue occurs after upgraded to Grafana 8.4.0 and Zabbix plugin 4.2.5.

In additional to the above, 400 & 404 errors reported in devtool

```
POST https://URL/api/ds/query 400 (Bad Request)
Failed to load resource: the server responded with a status of 404 (Not Found) for: https://URL/api/recording-rules/writer
GET https://URL/api/recording-rules/writer 404 (Not Found)
```

**Comment by pmalinge** [comment]
**Failed to get plugin dashboard**
We use Zabbix 6.0 and grafana-enterprise-8.4.3-1 on Rocky Linux 8.5
Same problem in /var/log/grafana/grafana.log  : logger=context t=2022-03-08T16:24:02.89+0100 lvl=eror msg="**Failed to get plugin dashboards**" error="**dashboard not included in plugin**" remote_addr=127.0.0.1

**Comment by skala-vl** [comment]
```
 dnf downgrade grafana:
 Downgraded:
  **grafana-8.3.7**-1.x86_64
```
  
  Resolved issue.

**Comment by mehdiMj-ir** [comment]
Same problem with:

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
8.4.3 | 5.4.11 | 4.2.5

![Screenshot_20220311_154140](https://user-images.githubusercontent.com/20270329/157865395-2beeea98-14d7-44c8-8a97-08cc649b0990.png)

```log
logger=http.server t=2022-03-11T15:27:23.95+0330 lvl=info msg="Successful Login" User=admin@localhost
logger=context t=2022-03-11T15:27:25.27+0330 lvl=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=151.233.11.111 time_ms=3 size=0 referer=
logger=live t=2022-03-11T15:27:31.06+0330 lvl=info msg="Initialized channel handler" channel=grafana/dashboard/uid/zbx-test address=grafana/dashboard/uid/zbx-test
logger=context t=2022-03-11T15:28:47.04+0330 lvl=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=49.12.51.111 time_ms=6 size=0 referer=
logger=context t=2022-03-11T15:34:19.87+0330 lvl=eror msg="Failed to get plugin dashboards" error="dashboard not included in plugin" remote_addr=49.12.51.111
logger=context t=2022-03-11T15:34:19.87+0330 lvl=eror msg="Request Completed" method=GET path=/api/plugins/alexanderzobnin-zabbix-datasource/dashboards status=500 remote_addr=49.12.51.111 time_ms=2 size=45 referer=https://stats.xxxxxxxxxxx.yyy:3000/datasources/edit/pvT3ZUbnk/dashboards
logger=context t=2022-03-11T15:34:42.7+0330 lvl=info msg="Request Completed" method=GET path=/ status=302 remote_addr=49.12.51.111 time_ms=0 size=29 referer=
logger=context t=2022-03-11T15:35:13.63+0330 lvl=eror msg="Failed to get plugin dashboards" error="dashboard not included in plugin" remote_addr=49.12.51.111
logger=context t=2022-03-11T15:35:13.63+0330 lvl=eror msg="Request Completed" method=GET path=/api/plugins/alexanderzobnin-zabbix-datasource/dashboards status=500 remote_addr=49.12.51.111 time_ms=2 size=45 referer=https://stats.xxxxxxxxxxx.yyy:3000/datasources/edit/pvT3ZUbnk/dashboards
logger=context t=2022-03-11T15:35:13.71+0330 lvl=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=49.12.51.141 time_ms=2 size=0 referer=
```
---- 
#### Should I start migration to Zabbix V6?

**Comment by cristanxu** [comment]
> ```
>  dnf downgrade grafana:
>  Downgraded:
>   grafana-8.3.7-1.x86_64
> ```
> 
> Resolved issue.
> 
> But in 8.3.7 #1358

Finally!
8.4.4 made me frustrated

**Comment by andrew-landsverk-win** [comment]
I'm on Grafana 8.4.2 and Zabbix 6.0.3 and this is still an issue. Does anyone know of a workaround? Thanks!

**Comment by daftu** [comment]
Grafana 8.5.0, Zabbix 6.0.3 - same issue. Any fix or workaround?

**Comment by daftu** [comment]
Workaround:
cd /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/
cp -rp dashboards datasource-zabbix/

**Comment by Raaveni** [comment]
The workaround doesn't work for me. Grafana refuses to connect the datasource and its name changed to alexanderzonin-zabbix-datasource. Any edit to any of the files in the directory above result in the same thing:

"Plugin not found, no installed plugin with that id"

**Comment by alexanderzobnin** [comment]
Probably, this is Grafana issue, but I fixed it by moving dashboards into data source directory.

**Comment by 9018** [comment]
> 解决方法：
> 
> ```
> cd /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/
> cp -rp dashboards datasource-zabbix/
> ```

But even the plug-ins can't be used after restarting

The prompt is as follows: plugin disabled

Grafana Labs checks each plugin to verify that it has a valid digital signature.

**Comment by alexanderzobnin** [comment]
@9018 Yes, if you change anything, then signature isn't valid anymore and you have to allow unsigned plugins in the Grafana config (but it's a security risk).
