### ISSUE TITLE
Zabbix 6.0 Services

### ISSUE THREAD

**Issue by Midas1989** [alexanderzobnin/grafana-zabbix#1408]
Hello,

zabbix 6.0 have big changes in services.

In the API are new methods for this.

```
[Object]()
[status:500]()
[statusText:"Internal Server Error"]()
[data:Object]()
[error:"Internal Server Error"]()
[message:"Method not found. Incorrect method \"service.getsla\"."]()
[config:Object]()
[url:"api/datasources/1/resources/zabbix-api"]()
[method:"POST"]()
[headers:Object]()
[hideFromInspector:false]()
[data:Object]()
[retry:0]()
[message:"Method not found. Incorrect method \"service.getsla\"."]()
```

Can you check this for the next version?

Thank you for this Grafana Plugin :)

**Comment by jbew81** [comment]
Hello,

This extension will be a must have !

Thank you!

**Comment by i-ky** [comment]
Duplicates #1396 and #1398.

**Comment by mbuyukkarakas** [comment]
Same problem. Needs fixing.

**Comment by 1vicente** [comment]
Hi Dears,

The method "[service.getsla](https://www.zabbix.com/documentation/5.0/en/manual/api/reference/service/getsla)" was changed to "[sla.getsli](https://www.zabbix.com/documentation/current/en/manual/api/reference/sla/getsli)".

With this change, some fields changed in response result, such as sla to sli.

I think that criticals informations in both method are:

**service.getsla**.....->....**sla.getsli**
sla .....................->...sli
okTime...............->...uptime
problemTime......->...error_budget
downtimeTime...->...downtime

May these pieces of information help you to fix it.

Through fix, we'll can to create beautiful dashboards again.

Thanks to keep development!

**Comment by isaqueprofeta** [comment]
@alexanderzobnin breaking changes in 6.0

**Comment by br-andremello** [comment]
@alexanderzobnin Por favor, ajude-nos

**Comment by isaqueprofeta** [comment]
@br-andremello Tente estudar e se acostumar com a estrutura de banco de dados do zabbix e faça as consultas direto via banco. Mesmo a versão anterior do SLA era bem simples e faltava bastante coisa para ilustrar os dados.

**Comment by br-andremello** [comment]
@isaqueprofeta 
Eu preciso de algo muito simples para esse projeto.
Quando vc falar de via banco, eu criaria outro datasource apontando para o banco MYSQL do Zabbix?

Qual query eu usaria para pegar essa informação do SLA:
![image](https://user-images.githubusercontent.com/104314012/164987531-4a86806f-3f81-4e8b-bf62-44b4b3921871.png)

Consegue me ajudar?

**Comment by isaqueprofeta** [comment]
@br-andremello "muito simples" não existe. Sim, falo de criar uma conexão pelo mysql, e a query você mesmo deve estudar. Use o schema.sql do zabbix para entender as ligações entre as tabelas e vá fazendo seus testes. Infelizmente não tenho como te ajudar mais. Bons estudos!

**Comment by isaqueprofeta** [comment]
I think it's better close this one and keep it on older one #1396
