### ISSUE TITLE
last version of plugin supporting Zabbix 3.4

### ISSUE THREAD

**Issue by kaska** [alexanderzobnin/grafana-zabbix#1409]
I found info about new version of plugin not supporting zabbix 3.4:

Ah, sorry, just noticed you're using Zabbix 3.4. It's not supported anymore, so either upgrade Zabbix or roll back to previous plugin version.

_Originally posted by @alexanderzobnin in https://github.com/alexanderzobnin/grafana-zabbix/issues/976#issuecomment-639320087_

What is the newest version of plugin supporting zabbix 3.4 and what is the newest version of grafana which works with that version of plugin? I tried plugin's version 3.X but it's look like is not working with grafana 8.4

**Comment by alexanderzobnin** [comment]
Hi! Regarding to change log, it looks like 3.11.0 is the last version that works with Zabbix 3.x

**Comment by alexanderzobnin** [comment]
Use Grafana 6.x (6.7, probably) for compatibility.
