### ISSUE TITLE
Displaying open alert count

### ISSUE THREAD

**Issue by bobtatus** [alexanderzobnin/grafana-zabbix#141]
Hi, from my research there is currently no way to display the number of total active alerts in Zabbix in Grafana, is this something that could be added?

When viewing Monitoring > Dashboard in Zabbix we can see counts of all alerts for various host groups.

Could we please have a way of displaying any open alerts in Grafana? The data is there in Zabbix but I can't see any way of showing the count of open alerts in Grafana via the grafana-zabbix plugin. The closest I can get is showing the zabbix queue but that isn't the same as open issues.

Thanks for your time.

**Comment by alexanderzobnin** [comment]
Hi, @bobtatus ! Really, this is not able now. But with new Table panel in Grafana it would be nice to have this metrics. I will try to implement it in version 3.0.

**Comment by bobtatus** [comment]
Thanks :) any ETA for when version 3.0 may be released?

**Comment by xiaoping378** [comment]
singlestat + alertCount
:+1:

**Comment by Sutrannu** [comment]
You can collect the number of alerts with an external check, e.g. from the zabbix api, store it in a "meta" host and display the metric with Grafana. This also allows you to graph alerts over time.

**Comment by sebbe54** [comment]
When can we expect this to be solved?

**Comment by alexanderzobnin** [comment]
@sebbe54 Not sure, sorry - have a lot of tasks.

**Comment by cooperspencer** [comment]
@alexanderzobnin the zabbix plugin is awesome as hell. How is it going with the alerting? It would be a great feature.

**Comment by alexanderzobnin** [comment]
@cooperspencer work is in progress, see #304, you can test latest changes with alerting from master branch.

**Comment by cooperspencer** [comment]
@alexanderzobnin Thank you. I will try it asap.

**Comment by alexanderzobnin** [comment]
There're two modes for triggers. First - alert count, filtered by group, host, app and severity. Second - table like system status in Zabbix.

![screenshot from 2017-10-22 18 59 04](https://user-images.githubusercontent.com/4932851/31863770-36c73350-b75b-11e7-804a-022ac271c4a6.png)

**Comment by fpaternot** [comment]
Can we filter with and without acknowledgement, and last event as well?

**Comment by alexanderzobnin** [comment]
@fpaternot I think yes, it's a good idea. I'll try to implement this before release. Can you describe _last event_ case?

**Comment by fpaternot** [comment]
Sure @alexanderzobnin, the last event i believe is called "Age less than" in  Monitoring => Triggers page. In trigger.get api method, the params are lastChangeSince and lastChangeTill.

Our use cases:
- performance: limiting the lastChangeSince for two days gives us 2-5 seconds, way better than 60-70seconds if parameter not used
- we use the unit of time as days
- we only use one of them in each call: either lastChangeSince or lastChangeTill params. We didnt need (yet?) to mix them in the same call.

**Comment by alexanderzobnin** [comment]
@fpaternot I use dashboard time range for filtering by last change time, so you can set either dashboard or panel time range.

**Comment by alexanderzobnin** [comment]
Closed by 1f5e261d4acdc66e442ad5fc9c9ceed93d0f3b36 but we still can discuss some details here.

**Comment by pronichev** [comment]
Hi, thank you for the feature. 
In 3.7.0, active triggers are filtered by the time range.
Can you add an option to show all active triggers without limiting their time of occurrence?

**Comment by alexanderzobnin** [comment]
@pronichev you can increase time range by using panel's override:
![screenshot from 2017-10-27 13 56 52](https://user-images.githubusercontent.com/4932851/32100990-d6ef4590-bb1e-11e7-97ea-8fb8223c7305.png)
Set it, for example to 1 year.

**Comment by pronichev** [comment]
Thanks for hint

**Comment by paalmiso** [comment]
I would like to ask if I can somehow filter triggers not only using min_severity:# but also using max_serverity:#
Our usecase is to have big single stat for each of top 3 severities.

**Comment by rafaelmendonca** [comment]
+1 

"I would like to ask if I can somehow filter triggers not only using min_severity:# but also using max_serverity:#
Our usecase is to have big single stat for each of top 3 severities." 

This will be very useful, its my requirement to delivery the project as well. 

Thank you

**Comment by eugene1-github** [comment]
+1

> I would like to ask if I can somehow filter triggers not only using min_severity:# but also using max_serverity:#
> Our usecase is to have big single stat for each of top 3 severities.

**Comment by alexanderzobnin** [comment]
@paalmiso @rafaelmendonca @eugene1-github please, open a new issue for this feature request.
