### ISSUE TITLE
Error on filter when not exist a value 

### ISSUE THREAD

**Issue by miyagidaniel** [alexanderzobnin/grafana-zabbix#1410]
![OK](https://user-images.githubusercontent.com/101415889/157902933-fb8e5f38-ef93-4cc0-8b0d-79792c50cc01.png)
when applying a filter from a host that exists, only the selected host is returned.

![Problem](https://user-images.githubusercontent.com/101415889/157902941-ad9d104c-350d-48e5-be09-a1e948ec1fc8.png)
when applying a filter from a host that doesn't exist, all metrics for the hosts are returned.

this problem happens in the combinations below

grafana 8.4.0
plugin 4.2.5

grafana  8.2.6
plugin 4.2.1

**Comment by miyagidaniel** [comment]
this problem happens in the combinations below

grafana 8.4.0
plugin 4.2.5

grafana  8.2.6
plugin 4.2.1

**Comment by thiagotkt** [comment]
When the host does not exist, the Group filter is being ignored... Palliatively if set the Application filter to null and Host that does not exist return No data...

**Comment by stvolinko** [comment]
I was able to reproduce this in my instalation:
Grafana: v8.2.6
zabbix-plugin 4.2.5
zabbix: v5.0.19

**Comment by GauthierSgds** [comment]
Same problem on grafana 8.3.7, zabbix 5.2.7 and plugin 4.2.5

**Comment by alexanderzobnin** [comment]
Hi! Looks like the same issue as #1427. So it's fixed and will be included in next patch release.
