### ISSUE TITLE
Failed to query data (context canceled error)

### ISSUE THREAD

**Issue by giovanny07** [alexanderzobnin/grafana-zabbix#1411]
**Describe the bug**
Hello
We upgrade from zabbix 5.2 to 6.0.2 with grafana 7.3 and plugin 4.1.1.

At the moment of updating everything, we obtained no data in all the queries.

lvl=eror msg="Query data error" error="failed to query data: Failed to query data: rpc error: code = Canceled desc = context canceled"

**Screenshots**

![image](https://user-images.githubusercontent.com/69469456/158420789-1e31ef7f-da84-48da-8dc1-6eda00afce38.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.4.3 o 8.2.7   | 6.0.2  | 4.2.5                |

**Comment by alexanderzobnin** [comment]
Could you confirm that you can get data in plugin 4.1.1 and cannot in 4.2.5?

**Comment by giovanny07** [comment]
@alexanderzobnin Of course. It happens because the variables $1 $2 $3 etc are no longer supported. It is worth clarifying and the incident can now be closed. Alternatively, direct database connection solves if they can't make such a change

**Comment by vdobychkin** [comment]
I have this problem in 4.2.10 but dont have in  4.1.1
