### ISSUE TITLE
when grafana use the zabbix data source ,the chart with data has null values on the hours

### ISSUE THREAD

**Issue by zzyun10** [alexanderzobnin/grafana-zabbix#1413]
![image](https://user-images.githubusercontent.com/21127868/159194966-e58b5680-6324-40c9-8d02-182f3a270c40.png)
The graph of the icon will have breakpoints around the hour
All zabbix charts in grafana have the same problem, the breakpoints are random, but they all appear on the hour。it is lost value about 2-3 minutes.
The charts on zabbix server have not the problems
Version:
Grafana: Grafana v8.1.6 (4a4083716c)
zabbix server: 5.2
Database: mysql: 8.0

**Comment by Sam-H101** [comment]
hmm no issues here on grafana 8.4.2 + zabbix 5.4.11 
curious @zzyun10 do you have Direct DB Connection enabled?

**Comment by alexanderzobnin** [comment]
@zzyun10 If you do not use stacking series grahp, you can disable data alignment in the query options. I think it should help.
