### ISSUE TITLE
Case sen

### ISSUE THREAD

**Issue by FlanniganColum** [alexanderzobnin/grafana-zabbix#1414]
**Is your feature request related to a problem? Please describe.**
When pulling metrics from multiple sources like VRTX devices for HW information and wanting to combine a dashboard with the OS information i find that the SNMP value could be in upper case where the Zabbix host entry is in lower case or visa versa. 

**Describe the solution you'd like**
Somehow be able to convert 1 case to another (upper <-> lower).  (This might be a more Grafana thing then the plugin as zabbix api filter for host looks for the exact string)

**Additional context**
SNMP from VRTX
.1.3.6.1.4.1.674.10892.2.5.1.1.4.1 = STRING: "SERVER1"
Zabbix/OS
System hostname "server1" and using the key to get the hostname from the system (HostnameItem=system.hostname)

So now when trying to build a unified dashboard to show hardware from a VRTX and the OS, i cannot get the data because the case sensitivity

**Comment by alexanderzobnin** [comment]
Hi! Since there's a regexp support, you can use regexp flags, so put in the host field something like
```
/server1/i
```
