### ISSUE TITLE
no data for any dashboard (zabbix datasource fine all test including directly connect to DB)

### ISSUE THREAD

**Issue by AndreyMariyko** [alexanderzobnin/grafana-zabbix#1418]
Добрый день. Новая установка. заббикс и графана mysql все на одном сервере
Подключение прохоит все хорошо(тестирвал с различными праметрами)
Но данных в grafana не шлет. 
была полема с подклчением по этому откатил графана на немного позднюю версию.

| Grafana | Zabbix | Grafana-Zabbix Plugin |
|     8.3.7  | -6.0.2-  |           4.2.5                   |

**Comment by AndreyMariyko** [comment]
зашел на забикс под Admin(ранее создавал админскую учетку конкретно дл графана ), данные пошли.

**Comment by alexanderzobnin** [comment]
Добрый день! Возможно, не назначены права на вновь созданного пользователя в Zabbix.
