### ISSUE TITLE
Cannot see Zabbix query

### ISSUE THREAD

**Issue by jinucompute** [alexanderzobnin/grafana-zabbix#1419]
Hi 
My zabbix plugin version is 4.2.5
Grafana version is 8.3.6
Zaabix version is 5.4.5

When i create a panel and choose zabbix as  a datasource i do not see any of the query fields. Its just shows a blank query screen,  If it is an existing panel i can see the data but can see the fields or source details. Please see screenshot of the same.
![Grafana_Error](https://user-images.githubusercontent.com/65276842/161672344-3607b1ce-b79b-4125-810e-72d70a1500be.jpg)

Any idea how to fix this

**Comment by Sam-H101** [comment]
is your install dockerized or how is it installed?
is there any files here? /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/partials/

**Comment by jinucompute** [comment]
Yes it is dockerized

The following files are present in /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/partials/
annotations.editor.html
query.editor.html

![image](https://user-images.githubusercontent.com/65276842/162096542-07b24493-f4dd-46f9-b017-0e758ddc5655.png)

**Comment by Dark-ZBX** [comment]
same problem

![image](https://user-images.githubusercontent.com/74934252/162138651-300c7e98-2a26-4e42-96b1-a51f2669bbcb.png)

**Comment by wilamu** [comment]
I'm having the same issue!

**Comment by Sam-H101** [comment]
@jinucompute try copying those file from /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/partials/ to
/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/partials/ then restart the container.
note the double datasource-zabbix/datasource-zabbix/

**Comment by Sam-H101** [comment]
@Dark-ZBX same question to you, linux or windows? and dockerized or standalone?
if linux I would suggest trying the above.

**Comment by jinucompute** [comment]
> @jinucompute try copying those file from /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/partials/ to /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/partials/ then restart the container. note the double datasource-zabbix/datasource-zabbix/

I did this, but it did not work. When i restart the container the folder /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/  gets deleted

**Comment by Sam-H101** [comment]
add this to the dockerfile at the end. 
then rebuild and bring back up. 

RUN mkdir -p /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/
CP /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/* /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/

**Comment by Dark-ZBX** [comment]
> @Dark-ZBX same question to you, linux or windows? and dockerized or standalone? if linux I would suggest trying the above.

@Sam-H101 it is running on windows server 2016

**Comment by jinucompute** [comment]
> add this to the dockerfile at the end. then rebuild and bring back up.
> 
> RUN mkdir -p /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/ CP /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/* /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/

Apologies but i dont work with the docker file. I use the following command to create the container

```
docker run -d \
	--name=grafana \
	--restart unless-stopped \
	-p 3000:3000 \
	-e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app,marcusolsson-dynamictext-panel" \
	-e "GF_LOG_MODE=console file" \
	-v grafana-data:/var/lib/grafana \
	-v grafana-config:/etc/grafana \
	-v grafana-def-config:/usr/share/grafana/conf \
	grafana/grafana:latest
```

Is there another way to achieve what you have said.

Thanks

**Comment by Sam-H101** [comment]
@jinucompute 
you can git pull the master branch 
confirm permissions to src/datasource-zabbix/partials is 644 and user/group should be the container user (1010 in my case)
then add 
`
    -v <master_location>/src/datasource-zabbix/partials: /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/partials
`
I do not think this will invalidate the plugin hash, but if it does you will need to remove the manifest file, and load it unsigned. 

Let me know if that works, I am not too up to date without using dockerfiles & docker-compose 

for windows let me build an environment.

**Comment by Sam-H101** [comment]
@Dark-ZBX @wilamu 
I just tested on windows 

Below steps assume you are using the default plugins directory in data\plugins. if not replace with the directory you are using.

1. goto `<grafana install dir>\data\plugins\alexanderzobnin-zabbix-app\datasource-zabbix`
2. Make new folder datasource-zabbix inside the above directory
3. Copy the partials folder to inside that directory you just made
4. final path will look like  `<grafana install dir>\data\plugins\alexanderzobnin-zabbix-app\datasource-zabbix\datasource-zabbix\partials`
in my case I did not need to bounce grafana, but you may.

**Comment by jinucompute** [comment]
> RUN mkdir -p /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/
> CP /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/* /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource-zabbix/

I spent a lot of time trying to build the container with the RUN and CP command in dockerfile. It does not accept the CP command as a recognizable command and the build fails. I then went back to your original suggestion and created the folder and copied the files there, but i did not bounce the container. This worked. 

only thing is everything the container is restarted I will have to do these steps. 

Thanks a lot for your help. Things are back to normal. Will there be a permanent fix for this in a future release ?

**Comment by Dark-ZBX** [comment]
Thanks for your support, it's working!  but I have another problem with the zabbix problems panel, is not working, 
 any fix for this?
![IMG-20220412-WA0044](https://user-images.githubusercontent.com/74934252/163111328-0f40299a-ee07-4067-83ad-7076520f483d.jpg)
![IMG-20220412-WA0045](https://user-images.githubusercontent.com/74934252/163111333-175a4626-998e-4db7-9616-5ccff7744f2f.jpg)



> > > @Dark-ZBX same question to you, linux or windows? and dockerized or standalone? if linux I would suggest trying the above.
> > 
> > 
> > @Sam-H101 it is running on windows server 2016
> 
> @Dark-ZBX @wilamu I just tested on windows
> 
> Below steps assume you are using the default plugins directory in data\plugins. if not replace with the directory you are using.
> 
> 1. goto `<grafana install dir>\data\plugins\alexanderzobnin-zabbix-app\datasource-zabbix`
> 2. Make new folder datasource-zabbix inside the above directory
> 3. Copy the partials folder to inside that directory you just made
> 4. final path will look like  `<grafana install dir>\data\plugins\alexanderzobnin-zabbix-app\datasource-zabbix\datasource-zabbix\partials`
>    in my case I did not need to bounce grafana, but you may.

**Comment by alexanderzobnin** [comment]
Hi! Try to upgrade Grafana, this issue is happening in some 8.3.x versions. I haven't noticed it in 8.4.

**Comment by Dark-ZBX** [comment]
Thanks to everyone for your support, its Working!

Performed the following steps:

-Install grafana 8.5 on Windows Server 2019
-Install Plugin 2.4.6 via CMD (C:\Program Files\GrafanaLabs\grafana\bin grafana-cli plugins install alexanderzobnin-zabbix-app)
-Go to C:\Program Files\GrafanaLabs\grafana\data\plugins\alexanderzobnin-zabbix-app\datasource-zabbix and create new folder with name , "datasource-zabbix"  by @Sam-H101 
-copy the "partials" folder and copy inside the created folder "datasource-zabbix"
-Delete MANIFEST  file on C:\Program Files\GrafanaLabs\grafana\data\plugins\alexanderzobnin-zabbix-app
-add:   allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app, alexanderzobnin-zabbix-datasource, alexanderzobnin-zabbix-triggers-panel in the configuration file (config.ini for Windows Version)
-Restart Grafana Service

Regards!

**Comment by mzromadhoni** [comment]
> Hi! Try to upgrade Grafana, this issue is happening in some 8.3.x versions. I haven't noticed it in 8.4.

same problem does not appear in add source

Grafana 8.5.2 
Zabbix Plugin 4.2.8
