### ISSUE TITLE
Not compatible with newer versions?

### ISSUE THREAD

**Issue by kadern0** [alexanderzobnin/grafana-zabbix#142]
Hi,

I've been trying to install this plugin in a manual installation of grafana and I got this error:

plugins.go:117 walker()] [E] Failed to load plugin json file: public/app/plugins/datasource/zabbix/plugin.json,  err: Did not find type and id property in plugin.json

I had to update some fields in the plugin.json file:
 "type": "datasource",
  "name": "Zabbix",
  "id": "zabbix",

With this change it loaded fine but I'm still getting this error:
 admin "GET /public/app/plugins/datasource/zabbix/datasource.js HTTP/1.1" 404 Not Found

**Comment by alexanderzobnin** [comment]
Hi, @kadern0 ! Which Grafana version are you use?

**Comment by kadern0** [comment]
Hi @alexanderzobnin and thanks for your reply. 

This is the version I'm trying to use:
./grafana-server -v
Version 3.0.0-pre1 (commit: v2.6.0+336-ge38e8c7)

**Comment by alexanderzobnin** [comment]
@kadern0 I use [grafana-3.0](https://github.com/alexanderzobnin/grafana-zabbix/tree/grafana-3.0) branch for developing version for Grafana 3.0. You can read installation docs at http://docs.grafana-zabbix.org/installation/
This version in development now and some changes are made in future, but it works and you can use it.

**Comment by evandro-portugal** [comment]
Hi, I can't get the plugin to work, neither the trigger panel from branch grafana-3.0 

I get this message on console
Failed to load plugin json file: /root/work/src/github.com/grafana/grafana/public_gen/app/plugins/datasource/datasource-zabbix/plugin.json,  err: Did not find type and id property in plugin.json

Looks like theres a lot of changes on modules, can't find the use of 'angular' anymore, it seems to have changed to './controller'

there's some changes on plugins .json tags too....

I'm missing something? It seems to be a lot of changes

I'm using Grafana
version=3.0.0-pre1  commit=v2.6.0+178-g311624b

**Comment by kadern0** [comment]
Hi @evandro-portugal, to 'fix' this error I've updated the following field names in the plugin.json file:
"type": "datasource",
"name": "Zabbix",
"id": "zabbix",

But after this I'm getting other errors :S

**Comment by evandro-portugal** [comment]
Right, about the controller I think I got the idea, they are not necessary, about the json, I had just tried the same think here, and got these errors too
[plugins.go:118 walker()] [E] Failed to load plugin json file: /root/work/src/github.com/grafana/grafana/public_gen/app/plugins/datasource/datasource-zabbix/plugin.json,  err: json: cannot unmarshal object into Go value of type string
2016/01/15 10:55:39 [plugins.go:118 walker()] [E] Failed to load plugin json file: /root/work/src/github.com/grafana/grafana/public_gen/app/plugins/panel/panel-triggers/plugin.json,  err: json: cannot unmarshal object into Go value of type string

**Comment by alexanderzobnin** [comment]
@evandro-portugal Are you read [installation documentation](http://docs.grafana-zabbix.org/installation/)?

**Comment by alexanderzobnin** [comment]
Try to install at the proper directory.

**Comment by evandro-portugal** [comment]
Hi @alexanderzobnin , I have read, but I'm doing some modifications to grafana in a development environment, so /var/lib/grafana/plugins doesn't exists for me, I have included in /grafana/public_gen/app/plugins/ , where I have used the previous version of you panel trigger and datasource (I had added one feature to the trigger panel too, the ability to show triggers with value=0 {OK status} )
so, for grafana 3.0 do I really must have grafana installed on my system first, to use on it on /var/lib/grafana/plugins?

**Comment by evandro-portugal** [comment]
Btw, I just got the Grafana master branch some hours ago, and the file plugins_api.md show this change now (it was uploaded 23 hours ago)

3.0 changes to plugin api changes

There has been big changes to both data source and plugin schema (plugin.json) and how you write the plugin main module.

Datasource plugin

Now data source plugins AMD/SystemJS module should return:

return {
  Datasource: ElasticDatasource,
  configView: editView.default,
  annotationsQueryEditor: annotationsQueryEditor,
  metricsQueryEditor: metricsQueryEditor,
  metricsQueryOptions: metricsQueryOptions,
};
Where ElasticDatasource is a constructor function to a javascript. The constructor function can take angular services and instanceSettings as parameters.

Example:

function ElasticDatasource(instanceSettings, templateSrv) {
  this.instanceSettings = this.instanceSettings;
  ///...
};
A datasource module can optionally return a configView directive function, metricsQueryEditor directive function, etc.

Example:

function metricsQueryEditor() {
  return {controller: 'ElasticQueryCtrl', templateUrl: 'app/plugins/datasource/elasticsearch/partials/query.editor.html'};
}

I can see that this really changed on all other panels in plugins folder

**Comment by alexanderzobnin** [comment]
I'm using prebuilded version (Grafana version: 3.0.0-pre1, commit: v2.6.0+70-gf355f36, build date: 2015-12-15 16:23:37) and have no problem. Can you try it with my plugin without any modifications?
You can specify path to plugins in `grafana.ini` or `custom.ini`:
```
[plugin.zabbix]
path = /home/your/clone/dir/plugins/datasource-zabbix

[plugin.triggers]
path = /home/your/clone/dir/plugins/panel-triggers
```

**Comment by alexanderzobnin** [comment]
Or may be newest Grafana version has broken changes.

**Comment by evandro-portugal** [comment]
I will try to build a grafana package, install to create the directorys, and use your plugin in /var/lib/grafana/plugin directory, if I still get a error I'll update here

**Comment by alexanderzobnin** [comment]
Ok! Please, report anyway, even if all right.

**Comment by volter** [comment]
I tried to adapt it to the new interface, but I failed somewhere.

**Comment by alexanderzobnin** [comment]
@volter What a problem?

**Comment by volter** [comment]
I tried to do the same kind of changes as they did for public/app/plugins/datasource/influxdb between 3bb20dbf2e63514369daf3a271b4427cbe622de0 and 6fae264222650651a33c307defe6006371124a1c. The eventual error appears to be in the routing.

**Comment by alexanderzobnin** [comment]
Hm... I've tried latest 3.0 build and get the same error:
```
2016/01/15 22:34:13 [I] Starting Grafana
2016/01/15 22:34:13 [I] Version: 3.0.0-pre1, Commit: v2.6.0+366-g842a595, Build date: 2016-01-15 15:20:32 +0300 MSK
2016/01/15 22:34:13 [I] Configuration Info
Config files:
  [0]: /home/alexander/development/grafana-zabbix/grafana-builds/grafana-3.0.0-pre1.2/conf/defaults.ini
  [1]: /home/alexander/development/grafana-zabbix/grafana-builds/grafana-3.0.0-pre1.2/conf/custom.ini
Paths:
  home: /home/alexander/development/grafana-zabbix/grafana-builds/grafana-3.0.0-pre1.2
  data: /home/alexander/development/grafana-zabbix/grafana-builds/grafana-3.0.0-pre1.2/data
  logs: /home/alexander/development/grafana-zabbix/grafana-builds/grafana-3.0.0-pre1.2/data/log
  plugins: /home/alexander/development/grafana-zabbix/grafana-zabbix/plugins

2016/01/15 22:34:13 [I] Database: sqlite3
2016/01/15 22:34:13 [I] Migrator: Starting DB migration
2016/01/15 22:34:13 [plugins.go:118 walker()] [E] Failed to load plugin json file: /home/alexander/development/grafana-zabbix/grafana-zabbix/plugins/datasource-zabbix/plugin.json,  err: Did not find type and id property in plugin.json
2016/01/15 22:34:13 [plugins.go:118 walker()] [E] Failed to load plugin json file: /home/alexander/development/grafana-zabbix/grafana-zabbix/plugins/panel-triggers/plugin.json,  err: Did not find type and id property in plugin.json
2016/01/15 22:34:13 [I] Listen: http://0.0.0.0:3000
```

**Comment by alexanderzobnin** [comment]
It seems, the newest version contains some broken changes.

**Comment by evandro-portugal** [comment]
those errors in the json seems to be easy to fix, actually already fixed them, but next you will get this
[E] Failed to load plugin json file:
/root/work/src/github.com/grafana/grafana/public_gen/app/plugins/datasource/datasource-zabbix/plugin.json, err: json: cannot unmarshal object into Go value of type string
[E] Failed to load plugin json file: /root/work/src/github.com/grafana/grafana/public_gen/app/plugins/panel/panel-triggers/plugin.json, err: json: cannot unmarshal object into Go value of type string



This "cannot unmarshal object into Go value of type string" seems a bit more complicated

**Comment by volter** [comment]
The whole interface changed a lot, see my last comment. It's not as easy as changing two things. I'll get you the diff of what I did.

**Comment by volter** [comment]
http://geofrogger.net/review/gz3.patch

**Comment by alexanderzobnin** [comment]
I fixed this issue:
```
{
  "type": "datasource",
  "name": "Zabbix",
  "id": "zabbix",

  "module": "plugins/zabbix/datasource",

  "staticRoot": ".",

  "metrics": true,
  "annotations": true
}
```
But get another - datasource.js format changed and current version still not working. And I have issues with side bar even without zabbix plugin.

**Comment by alexanderzobnin** [comment]
@volter Thanks! I also did similar changes. But as you said right, so many changes in api. I need more time to fix it.

**Comment by volter** [comment]
Are you on IRC, by the way?

**Comment by evandro-portugal** [comment]
About the side bat, mine was working some hours ago, I have just updated and got the same issue with it now... they will prob fix it asap

**Comment by alexanderzobnin** [comment]
@volter No, I haven't IRC. Need to fix it :smile:

**Comment by volter** [comment]
I think many people will love to see you on #zabbix on Freenode.

**Comment by alexanderzobnin** [comment]
@kadern0 @evandro-portugal @volter Now fixed and merged to grafana-3.0 branch.

**Comment by volter** [comment]
Sweet, thanks! I wonder what I had missed, let's have a look!

**Comment by evandro-portugal** [comment]
@alexanderzobnin thanks!!

**Comment by evandro-portugal** [comment]
@alexanderzobnin How can I contribute with the project? I would like to share my added option to you trigger panel, which gives the ability to have an alert history, like the one we are able to see on zabbix.
Also, I will be using this project for a long time, and it would be great to share whatever I do to improve your great and needed plugin.
Thanks again.

**Comment by alexanderzobnin** [comment]
@evandro-portugal Contribution would be great! You can see latest changes in [grafana-3.0](https://github.com/alexanderzobnin/grafana-zabbix/tree/grafana-3.0) branch and newest. If you want to contribute, create new branch from `grafana-3.0`, make changes and open pull request.

**Comment by evandro-portugal** [comment]
tried to, but it says that I'm not autorized to create a branch

**Comment by alexanderzobnin** [comment]
Do you forked repo?

**Comment by alexanderzobnin** [comment]
@evandro-portugal read more about contributing on GitHub at https://help.github.com/categories/collaborating-on-projects-using-pull-requests/
