### ISSUE TITLE
Text Type dont work with Stat vistualization

### ISSUE THREAD

**Issue by gdeleon23** [alexanderzobnin/grafana-zabbix#1424]
I had dashboards with some "Text" data from Zabbix that is present in "Stat" mode visualization on the Grafana Dashboard.
In the last version of Grafana 7.0.1, this work OK, but with new versions of zabbix plugin and grafana is not working any more. We received a text with "No Data"

**Expected behavior**
I need to present a last Text data item in dashboard. I tried with suggestions, that is "logs" or "table" and data is showing, but with more information that i need, and i cant hide.

I need only the last data of the item text.

**Screenshots**
how i need, with Stat visualization
![imagen](https://user-images.githubusercontent.com/75126791/162740614-fd5bf804-8efc-4a8d-ae26-c5095a64159d.png)

With table visualization data is present but with more information that i need

![imagen](https://user-images.githubusercontent.com/75126791/162739101-e1348a73-0822-4ada-946c-f157ff9a38c5.png)

With logs visualization data is present but with more information that i need

![imagen](https://user-images.githubusercontent.com/75126791/162739566-d015c10e-c384-4232-a1da-a4fda66c5f11.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.0.1 and 8.4.5  | 5.0 and 5.4  | 4.2.5                |

**Comment by alexanderzobnin** [comment]
Hi! Due to changes in Stat panel, now you should choose a field name in panel config to display in order to show text data correctly:

![Screenshot from 2022-04-18 14-30-47](https://user-images.githubusercontent.com/4932851/163802311-b17fb24b-d165-4861-ac6a-f9f31163cc96.png)
