### ISSUE TITLE
Query returns all application data when host not found

### ISSUE THREAD

**Issue by maikel-09** [alexanderzobnin/grafana-zabbix#1427]
Plugin version: 4.2.1
Zabbix version: 5.0.17

When group, host application and item are filled in and the host cannot befound. De plugin will query for host like /.*/ and select all items for that application and item from all hosts. 

Expected behaviour would be a "No data" in this situation
![Expected NO data response](https://user-images.githubusercontent.com/58327038/163343466-1b0c38f0-22c7-41ec-904c-97b06a4657bf.png)
![Unexpected data from all hosts in group](https://user-images.githubusercontent.com/58327038/163343472-86b47484-0ff2-4126-adc0-bfe741836095.png)

**Comment by alexanderzobnin** [comment]
I will check it out, I think if host field is empty, then no data should be fetched.
