### ISSUE TITLE
Plugin file not found" error="open C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins\\alexanderzobnin-zabbix-app\\datasource-zabbix\\datasource-zabbix\\partials\\query.editor.html: The system cannot find the path specified."

### ISSUE THREAD

**Issue by FearlessJYN** [alexanderzobnin/grafana-zabbix#1428]
I am getting this error when trying to load the plugin to Grafana. I can get the issue to resolve by creating the "C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins\\alexanderzobnin-zabbix-app\\datasource-zabbix\\datasource-zabbix" folder but if I restart the Grafana service it recurses and starts looking for a datasource-zabbix\datasource-zabbix\datasource-zabbix\partials\\query.editor.html. Does anyone know how I can stop it from looking in the wrong directory? I have tried uninstalling the plugin multiple times and the only thing that seems to work is to add the directory and copy the files its looking for into the new folder.

**Comment by alexanderzobnin** [comment]
That's a bug in Grafana. Try to use latest Grafana version, this bug was fixed.
