### ISSUE TITLE
metric request error

### ISSUE THREAD

**Issue by ZhongMingsheng** [alexanderzobnin/grafana-zabbix#1429]
when i create a new panel,option the zabbix datasource and metric,brower query request has not response ,but sometime has response.grafana log show "msg=metric request error"

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.3.x   | 5.x.x  | 4.2.x                 |

**Comment by ZhongMingsheng** [comment]
![微信图片编辑_20220422091414](https://user-images.githubusercontent.com/30831651/164577660-56a799f5-d8a0-421f-bd08-ed97d989c909.jpg)
![企业微信截图_16505904519691](https://user-images.githubusercontent.com/30831651/164577977-b8d85c54-25f3-40ec-9535-681360a918d2.png)

**Comment by alexanderzobnin** [comment]
Looks like the same issue #1411
