### ISSUE TITLE
test connection but no respose

### ISSUE THREAD

**Issue by hattaagung** [alexanderzobnin/grafana-zabbix#143]
Hi,

I am new for zabbix and grafana. Need to try to use this nice application. 
Having test connection during adding data source with below

![image](https://cloud.githubusercontent.com/assets/16734452/12373089/9e1b4fc6-bca0-11e5-96a8-3d457892a0c7.png)

No response from testing result.

Need your help.

Br,

hatta

**Comment by alexanderzobnin** [comment]
Hi! It mean that grafana can't connects to Zabbix server due some reasons.

**Comment by hattaagung** [comment]
Hi alex,

How to solve it n debug it. No error  in zabbix server and grafana server.

Thx and Br,

Hatta

**Comment by hattaagung** [comment]
Hi Alex,

i got 421 response with below

192.168.56.3 - - [17/Jan/2016:07:09:01 +0700] "GET /zabbix/api_jsonrpc.php HTTP/1.1" 412 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.56.3 - - [17/Jan/2016:07:10:23 +0700] "GET /zabbix/api_jsonrpc.php HTTP/1.1" 412 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"

[root@simulator /usr/share/zabbix]# zabbix_server -V
Zabbix server v2.4.7 (revision 56694) (12 November 2015)
Compilation time: Nov 13 2015 05:31:52

[root@simulator /usr/share/zabbix]# grafana-server -v
Version 2.6.0 (commit: v2.6.0)

api_jsonrpc.php already checked and same with installation procedure.

Br,

hatta

**Comment by alexanderzobnin** [comment]
@hattaagung see https://github.com/alexanderzobnin/grafana-zabbix/wiki/Installation#note-for-zabbix-22-or-less

**Comment by hattaagung** [comment]
Hi alex,

Yes. I already checked it and it is same. I installed zabbix with versin 2.4.7.

Do you have another ideas ?

Br,

Hatta

**Comment by alexanderzobnin** [comment]
@hattaagung it's a CORS issue. Check your web server configuration.

**Comment by hattaagung** [comment]
Hi Alex,

now come with new error like below

![image](https://cloud.githubusercontent.com/assets/16734452/12382867/9500e00e-bdd1-11e5-9d66-bf612304e00f.png)

web server log is ok now

192.168.56.3 - - [18/Jan/2016:10:51:42 +0700] "OPTIONS /zabbix/api_jsonrpc.php HTTP/1.1" 200 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"

what is the cause error.config is undefined.

Br,

hatta

**Comment by alexanderzobnin** [comment]
@hattaagung Can you check server response in browser dev tools?

**Comment by hattaagung** [comment]
![image](https://cloud.githubusercontent.com/assets/16734452/12383698/ada48408-bddb-11e5-8040-79702e663af1.png)

![image](https://cloud.githubusercontent.com/assets/16734452/12383704/ba3770f4-bddb-11e5-92f3-8cd8526661e4.png)

**Comment by hattaagung** [comment]
Hi alex,

Could you please inform me whts the issue ? Why no request to zabbix ?

Br,
Hatta

**Comment by alexanderzobnin** [comment]
@hattaagung Can you please show `Response` tab instead `Headers` in dev tools?

**Comment by hattaagung** [comment]
Hi alex,

Response Tab is blank, but i found log in console

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.56.3/zabbix/api_jsonrpc.php. (Reason: CORS header 'Access-Control-Allow-Origin' does not match '*, *').

what is means :( ? i already adding enable-cors in httpd config.

**Comment by hattaagung** [comment]
![image](https://cloud.githubusercontent.com/assets/16734452/12414943/6141a744-becb-11e5-9d2b-94e5a95399dc.png)

thnx god...it solved now :(.

you can close this issue.

**Comment by alexanderzobnin** [comment]
OK, good!
