### ISSUE TITLE
Zabbix 6 + Grafana IT Services 

### ISSUE THREAD

**Issue by br-andremello** [alexanderzobnin/grafana-zabbix#1430]
IT Services não funciona na versão 6 do Zabbix 

![image](https://user-images.githubusercontent.com/104314012/164983952-a79b74db-8b8a-4670-bf9a-00b8c4c59b1c.png)

Method not found. Incorrect method "service.getsla"

**Comment by br-andremello** [comment]
@alexanderzobnin por favor me ajude nesse erro.

**Comment by i-ky** [comment]
Duplicates #1396, #1398 and #1408.

**Comment by isaqueprofeta** [comment]
I think it's better close this one and keep it on older one https://github.com/alexanderzobnin/grafana-zabbix/issues/1396

**Comment by alexanderzobnin** [comment]
Closing this in favor of #1408
