### ISSUE TITLE
RegEXP on Item exclusion do not take effect

### ISSUE THREAD

**Issue by xiaoxue999** [alexanderzobnin/grafana-zabbix#1431]
| Grafana | Zabbix | Grafana-Zabbix Plugin |
  8.4.6        6.0.3        4.2.6
![1](https://user-images.githubusercontent.com/22721577/165016211-008354de-e850-45ae-960c-7989eef09db1.png)
![2](https://user-images.githubusercontent.com/22721577/165016215-fb425a33-27d1-405a-9dc9-67648ccd52d1.png)
![3](https://user-images.githubusercontent.com/22721577/165016217-4b15b51b-41b0-4108-b542-e7ea38c33e54.png)

RegEXP exclusion syntax can not take effect in items query,but General of the Variables query was ok.

**Comment by i-ky** [comment]
Duplicates #1264.

**Comment by alexanderzobnin** [comment]
Closing since it's duplicating issue
