### ISSUE TITLE
SLA support in Zabbix 6.0

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#1437]
I pushed a quick fix for IT services mode in Zabbix 6.0, but new SLA feature is not 100% compatible with IT services since there might be multiple SLAs for each service and SLI object contains a bit different set of properties. So for the full support, there should be a new query mode. Ref #1408

**Comment by jbew81** [comment]
We need this functionality :-)

**Comment by alexanderzobnin** [comment]
@reiverjohn It's because status was moved to service object. With the latest changes, it will be available for querying.

**Comment by heyrod** [comment]
Hi @alexanderzobnin, when this fix will be released?
Thanks

**Comment by elinxs** [comment]
Hi! Same question here.

Thanks @alexanderzobnin !
