### ISSUE TITLE
Error 500 while trying to import zabbix dashboards.

### ISSUE THREAD

**Issue by mehdiMj-ir** [alexanderzobnin/grafana-zabbix#1438]
**Describe the bug**
I couldn't import zabbix dashboards.
when I try to import them from **Data Sources** -> **Dashboards** I get an error.

**Expected behavior**
I expected import the Dashboards

**Screenshots**
![Screenshot_20220430_005542](https://user-images.githubusercontent.com/20270329/166068449-b9821c19-e0e4-4537-a619-54510e425321.png)

**Network data** || **Grafana log**
![Screenshot_20220430_005207](https://user-images.githubusercontent.com/20270329/166068515-78e2ccc4-b743-4b94-80b2-a91c182aec11.png)

**Solution**
I manage to solve the problem by creating a `dashboards` directory under `/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix` path and copy `template_linux_server.json, zabbix_server_dashboard.json, zabbix_system_status.json` files in it.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v8.5.1 (61fe4a1859)  | 6.0.3 | 4.2.6 |

**Comment by alexanderzobnin** [comment]
Duplicates #1407
