### ISSUE TITLE
Triggers query - acknowledged setting does not appear to have any impact

### ISSUE THREAD

**Issue by mjducharme** [alexanderzobnin/grafana-zabbix#1440]
The acknowledge setting for the Triggers query does not appear to have any impact at all. Even if it is set to only count unacknowledged triggers it still counts everything.

**Comment by alexanderzobnin** [comment]
Hi! Unfortunately, after migration to the problems API, I consider triggers query mode as legacy and not going to support it in future. But there's a workaround, use can use Problems mode with transformation, here's an example:

<img width="1009" alt="Screenshot 2022-05-06 at 12 48 37" src="https://user-images.githubusercontent.com/4932851/167109265-e9bf92a7-1280-40f4-9fa3-722bd9891021.png">

<img width="999" alt="Screenshot 2022-05-06 at 12 48 45" src="https://user-images.githubusercontent.com/4932851/167109290-bdd6662c-f11f-4139-a9d1-e154292ba1a1.png">

**Comment by mjducharme** [comment]
Hi,

This is a workaround for some cases but what if I want more details? As you can see here I have adjusted your example dashboard:

![image](https://user-images.githubusercontent.com/1851874/167229045-33020e8d-35d7-45b5-8bd3-9dfca0235ade.png)

How can I recreate this using "Problems" instead of "Triggers"?

**Comment by mjducharme** [comment]
@alexanderzobnin I tried to get the table shown at the top of my screenshot above reproduced. Unfortunately it seems like it is not possible.  If I use the transformation "Extract Fields", I get most fields I need, but "groups" is a JSON field. If I extract fields again on that, then I get fields for group 1, group 2, and group 3, which again have JSON. I'm able to extract fields for group 1, but when I do the same for group 2, all data disappears. I'm not sure where the issue is. The thing is that I don't want all of the groups - we have a group used to keep track of the location of the device, and those either start with BCN/ or Enterprise/, anything that starts with anything else I remove. There doesn't seem to be a way of doing this in Grafana, making it really hard if not impossible to create this same type of table without the "Triggers" functionality.

**Comment by mjducharme** [comment]
@alexanderzobnin bumping this - do you have any way of getting such a dashboard to work with the Problems API instead of the Triggers API? If not, would you at least consider fixing the "Acknowledged" functionality so that I can hide the Acknowledged problems?
