### ISSUE TITLE
Return change in query name in "TRIGGERS" mode

### ISSUE THREAD

**Issue by daniloaacb** [alexanderzobnin/grafana-zabbix#1441]
You could somehow change the json response structure for Grafana in “TRIGGERS” mode. If possible, match the structure mode that is returned in the “Metrics” query model
In the example below I create 2 queries, for demonstration purposes:
As you can see, in “Metrics” mode, 1 “OBJECT” and 3 “Fields” are returned, 1 being time and 2 from the respective queries

![image](https://user-images.githubusercontent.com/81991101/166225730-8e1118c1-a96a-43f7-954c-d818ae38ac1b.png)

The return of the 3 columns, both of which can think about using the “time” masses, then turning to the transformation of GRAFANA into objects. And the query name is established by the host and item name.
 
![image](https://user-images.githubusercontent.com/81991101/166225755-5e7c77ad-28c6-4f35-8f6b-1f21d8d64cdc.png)

![image](https://user-images.githubusercontent.com/81991101/166225798-ff17c8b7-99f2-4ead-8b9f-0434d3fc4083.png)

![image](https://user-images.githubusercontent.com/81991101/166225808-c0d00f62-fde3-4fe3-bb55-429f4d17aab0.png)

The “TRIGGERS” query mode already returns 2 objects and 2 fields each query. Since the name returned is “triggers count” for both queries, making it impossible for me to disassociate the two in a specific view panel.

![image](https://user-images.githubusercontent.com/81991101/166225833-a12aaa45-8393-48ac-b1ce-946cf652b64f.png)

I ask first for the possibility of being able to set the query return name in “triggers” mode as “$hostname_application”, and if possible change the structure as it is in “METRICS” mode.

**Comment by alexanderzobnin** [comment]
Hi! Could you describe your use case? I consider triggers mode as legacy and going to completely switch to the Problems mode.

**Comment by daniloaacb** [comment]
So, I'm using your plugin together with the "FLOWCHARTING" visualization plugin, and within this there is the option to map this query in a graph, but I am unable to do more than one mapping because the queries use the same title name, with no possibility of differentiation.

Example: In the "METRICS" query mode I can use the queries normally after setting only one transformation(multi-frame-time-series), which basically transforms 3 "FIEDS" (time, and the two queries) into two "OBJECT" (each object with time and a query) and turns one table into two.

![image](https://user-images.githubusercontent.com/81991101/167121475-8cc9ff3a-2d6f-4020-9af4-402a6a79b561.png)

![image](https://user-images.githubusercontent.com/81991101/167121553-55af389f-d1d1-4885-aa3e-ed7fe327285b.png)

Unlike the "TRIGGERS" query mode option that generates the same names, making it impossible to use the plugin. since I need to differentiate each count query, as the idea is that each one has its mapping

![image](https://user-images.githubusercontent.com/81991101/167122328-7e66651b-7a04-4f4d-8bcc-4de513d5d5a6.png)

**Comment by alexanderzobnin** [comment]
Ok, got it!

**Comment by daniloaacb** [comment]
It would be interesting if the return had the same structure as the "METRICS" mode, in this case "$host : $application  "

**Comment by alexanderzobnin** [comment]
I'm not sure how exactly flowcharting plugin handles data frames, but I anyway want to refactor all returning data to data frames since it's a new standard in Grafana. Hopefully it will work.

**Comment by alexanderzobnin** [comment]
I added simple "Count <refId>" name, that should be enough.
