### ISSUE TITLE
Use Trends by graph 

### ISSUE THREAD

**Issue by luuuuuh** [alexanderzobnin/grafana-zabbix#1442]
Sorry my poor English :(

Sometimes i need to use real value of items but "Use trends" is set to global.

I Would like if it's possible to set a flag or function to force real data instead trends peer graph.

Thanks !!! :)

**Comment by alexanderzobnin** [comment]
Hi! Yes, sounds reasonable. I can add function like `useTrends(false)` to make it possible to configure each query individually.

**Comment by alexanderzobnin** [comment]
I decided to use query option instead of function, it's easier to implement and use I think.

**Comment by luuuuuh** [comment]
Alexander thanks a lot for help!!!
But i don´t see the configuration, she should here?

![image](https://user-images.githubusercontent.com/23240536/219480490-144a76da-40f2-4308-b665-8acbb0b658fc.png)
