### ISSUE TITLE
setAlias function show request instead of Alias set

### ISSUE THREAD

**Issue by fredprod** [alexanderzobnin/grafana-zabbix#1444]
**Describe the bug**
When setAlias is used, it is used as name in Stat Panel. But since new release it shows request instead.

**Expected behavior**
Alias value is shown as name in Stat panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/10994072/166958222-2965c781-0d39-41d5-8488-9b3f841c10a2.png)

**Network data**
N/A

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.3.7   | 6.0.4  | 4.2.7                 |

**Comment by miyagidaniel** [comment]
same problem on 
grafana:8.4.0 
zabbix: 6.04
Plugin: 4.2.7

**Comment by derdeagle** [comment]
I experience the same issue.
![screenshot_2022-05-05_20-39-02](https://user-images.githubusercontent.com/11424540/166998532-7ba41e11-cf42-4c76-84ca-f305cc75dd07.png)

Even when settings the alias to an explicit value the rest is still shown.

Zabbix: 6.0.4
Grafana: 8.5.2
Plugin: 4.2.7

**Comment by alexanderzobnin** [comment]
Yes, it seems, there's some messiness with labels, field names and how Grafana use it in last update. Going to fix it up.

**Comment by ykhair** [comment]
Hello,

I just upgraded my Grafana to 8.5 version and grafana-zabbix plugin to 4.2.8 but the function "setAlias" don't work anymore.

Regards,
