### ISSUE TITLE
Trend data displayed incorrectly when direct DB connection enabled

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#1445]
Original issue created in Grafana repo:
https://github.com/grafana/grafana/issues/48716

**Comment by leeoniya** [comment]
hey @alexanderzobnin thanks for the fix.

btw, we have a generic mechanism now for null-filling in the TimeSeries, State Timeline, and CandleStick panels. you can set `field.config.interval` on the Time field. we do this in Prometheus now.

see https://github.com/grafana/grafana/pull/44622
