### ISSUE TITLE
Grafana-zabbix api

### ISSUE THREAD

**Issue by kotviphp** [alexanderzobnin/grafana-zabbix#1453]
Hi/Добрый день!

problem with api data request
no choice items
Previously created dashboards work via API
also no item selection
how to fix?
![api](https://user-images.githubusercontent.com/25497579/168979238-1880b70f-c07d-43a5-884c-48b089e5d997.PNG)
![api1](https://user-images.githubusercontent.com/25497579/168979273-195fac71-90b5-4abf-b7e8-7fe58f4804ae.PNG)

**Comment by kotviphp** [comment]
connection and test is OK


![api2](https://user-images.githubusercontent.com/25497579/168981580-1f41b44d-1b67-45c0-855a-85d3de5200ed.PNG)

**Comment by Sam-H101** [comment]
what version of grafana and zabbix plugin are you using? This is a grafana bug that was fixed in a later version,

**Comment by kotviphp** [comment]
![api3](https://user-images.githubusercontent.com/25497579/169459973-8d5460fc-7db4-4635-be91-552fb38d0a47.PNG)

**Comment by kotviphp** [comment]
![api4](https://user-images.githubusercontent.com/25497579/169460166-95bc6533-208b-4d0d-b144-fce935eea296.PNG)

**Comment by kotviphp** [comment]
installed version 4.2.8 
all OK
Thank you
all OK
Thank you

**Comment by kotviphp** [comment]
Done
