### ISSUE TITLE
Grafana query mode Metrics not auto-populating groups, hosts, or any zabbix names

### ISSUE THREAD

**Issue by czech12** [alexanderzobnin/grafana-zabbix#1457]
I really didn't want to create a new issue, but I'm not finding any help with my searches.

First, I had this all working perfectly.  I'm running all the components in unraid docker and there was an update available.  I blindly applied the update and of course it broke something between Zabbix and Mariadb.  The install was only a couple weeks old, so I decided to rebuild zabbix and mariadb.

I have everything reconfigured and my 'old' grafana reports are working using this plugin, but for some reason when I try to use "Explore" or "Dashboards" to create a new query, the names of my Zabbix Host Groups, Hosts, or any of the searchable fields populate with data like they did before.

I'm using the Direct DB Connection with the plugin.  Again, everything works except searching those hosts groups from the query.  If I manually put the name there, it works.

Please help.  Thanks.

**Comment by mateus123soares** [comment]
I'm facing this same problem. Could anyone help please.

**Comment by czech12** [comment]
> I think I have the same problem.
> 
> I had set up dashboard with couple of identical panels, each of them had Query mode Metrics taken from defined host of particular Host Group. Host is defined by Dashboard variable.
> 
> At first I had only one Host in the Host Group in Zabbix (e.g., Host1). Then I created another one host in the same Group (e.g., Host2), and tried to create new Query mode Metrics in Grafana to show data from this new host. However, when I was setting up Metric, after I stated Host Group, it didn't suggest Host2, only already existed Host1. None of following methods helped: copying dashboard, creating a new dashboard, creating Query in Explorer.
> 
> Grafana v8.5.1 Zabbix v5.2.7 Zabbix plugin v4.2.6

I experienced some of the when I had things working, where new items would not show up right away.  Restarting my docker containers seemed to fix that issue for me.  I think Grafana was the one that really needed a restart to pick up the data, but I also restarted the Zabbix server and web interface, as well as the DB.  See if that helps for you.

**Comment by czech12** [comment]
I haven't bothered looking at this since I posted and just came back to it, and the auto populating is suddenly working for me.  I did not change anything in zabbix, mariadb, or grafana, but....    yaaaay?!?!

Glad it's working, but it would be nice to know how it's pulling this data and why it wasn't working at first.

**Comment by letBulochkin** [comment]
It worked for me after some time as well. It seems for me that there is some time delay, after which plugin polls Zabbix for new hosts or items created. 

So, no issue here, as it turns out. However, it would be nice to state this kind of details in documentation.
