### ISSUE TITLE
Item names show the zabbix key/request instead of just the hostname.

### ISSUE THREAD

**Issue by Mattz0r** [alexanderzobnin/grafana-zabbix#1458]
**Describe the bug**
The data in the legends now show something like:

(HOST-NAME-HERE) {host="HOST-NAME-HERE", item="Interface vmxnet3 Ethernet Adapter(Ethernet0): Bits received", item_key="net.if.in["vmxnet3 Ethernet Adapter"]"} Min: 4.72 Mb/s Max: 92.8 Mb/s Current: 73.0 Mb/s

This is when using: SetAlias(($__zbx_host_name))

**Expected behavior**
Usually, this would just display: (HOST-NAME-HERE) Min: 4.72 Mb/s Max: 92.8 Mb/s Current: 73.0 Mb/s

**Screenshots**

![zabbix-grafana](https://user-images.githubusercontent.com/2264823/172353756-8127e27a-d945-429e-9fec-588bbc458cd8.png)

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.4.4   | 6.0.4  | 4.2.7                 |

**Comment by Mattz0r** [comment]
I've found out that for some reason I've got to faff around with Overrides, to get it to display how I want, rather than it being by default before....

Is this a change in Grafana's default behaviour? 

Thanks,

Matt

**Comment by alexanderzobnin** [comment]
I think it's fixed in latest version of plugin, so try to upgrade.
