### ISSUE TITLE
Slash is appended to data source url

### ISSUE THREAD

**Issue by Sutrannu** [alexanderzobnin/grafana-zabbix#146]
Grafana 2.5.0 with nginx reverse proxy
Grafana-Zabbix 2.5.1
Data source Zabbix 2.2 (https). nginx

Grafana is configured with 2 nearly identical zabbix instances as data sources. One on the same host, one remote. Both are configured with fqdns, e.g., `http://fqdn/api_jsonrpc.php`. The request made to the local zabbix instance is `http://fqdn/api_jsonrpc.php`. The request to the remote instance is `http://fqdn/api_jsonrpc.php/`. note the invalid trailing slash.
From the successful nginx logs:
`"POST /api_jsonrpc.php HTTP/1.1" 200`
From the failed nginx logs:
`"POST /api_jsonrpc.php/ HTTP/1.1" 403`
From the Grafana log:
`2016/01/20 15:09:39 [I] Completed /api_jsonrpc.php/ 403 Forbidden in 2.61934ms`

If this is more likely a grafana bug, any help tracking it down is appreciated.

**Comment by alexanderzobnin** [comment]
I faced same bug earlier. Can you check it in last Grafana version?

**Comment by Sutrannu** [comment]
Last meaning <2.5.0, or latest, being 2.6.0?
Is 2.6 supported? If so, I will update and reply.

**Comment by alexanderzobnin** [comment]
Try latest - 2.6.0.

**Comment by Sutrannu** [comment]
I notice now that I mistyped the url in the original post. The api urls are all `https`

I updated to 2.6.0 with he latest deb package, confirmed the version and restarted grafana and nginx. The issue above still occurs, though the log line is a bit more verbose.
`2016/01/25 10:51:09 [I] Completed 127.0.0.1 - "POST /api_jsonrpc.php/ HTTP/1.0" 403 Forbidden 564 bytes in 20941us`
The localhost ip seems spurious. Otherwise, it's the same issue.

**Workaround**
I have implemented a workaround on the target that is rather commonplace and may be hiding the issue for some users. In nginx, you can rewrite all urls to eliminate trailing slashes. This is touted as a good practice to eliminate the possibility of duplicate locations. I.e., a directory index and file accessible with the same url apart from the trailing slash. `rewrite ^/(.*)/$ /$1 last;` This eliminates the erroneous slash and allows the query to work, but it's a dirty, dirty hack.

**Comment by alexanderzobnin** [comment]
@Sutrannu Can you open ussue in Grafana repo? Looks like grafana bug.
