### ISSUE TITLE
Grafana doesn't display drop-down menu for hosts or groups at Zabbix in Explore

### ISSUE THREAD

**Issue by RowanWally** [alexanderzobnin/grafana-zabbix#1462]
**Describe the bug**
Grafana can't find hosts or groups for Zabbix At Explore or any query can't display drop-down menu for our data at Zabbix in any query or  Explore.t

<img width="543" alt="grafana issue 1" src="https://user-images.githubusercontent.com/86344612/173531453-6a66eee1-b4d8-412e-9c02-8d849784198d.png">

**Expected behavior**
We need to make the data appear as shown in the picture.
Note that the drop-down menu working on Grafana 8.4.

<img width="510" alt="Grafana issue" src="https://user-images.githubusercontent.com/86344612/173528978-1b7f9a02-bf38-4383-a918-af6feb3a5ac2.png">

**Network data**
Error message
`logger=plugin.alexanderzobnin-zabbix-datasource t=2022-06-13T16:23:04.784420547Z level=debug msg="DS query" query="unsupported value type"`

**Software versions**

| Grafana           | Grafana-Zabbix Plugin | Zabbix    |
| -------             |  ---------------------     | -------     | 
| v9.0.0-beta2   | 4.2.8                             | 6.0.1         |

**Comment by michaeleino** [comment]
This issue with grafana v9.0.0-beta2
Upgrading to grafana v9 stable fixes the issue.
