### ISSUE TITLE
Some marketing needs :)

### ISSUE THREAD

**Issue by nucleusv** [alexanderzobnin/grafana-zabbix#15]
Alex, 

I think it is better to publish the project to share.zabbix.com
And I will try to ask Zabbix SIA to publish link to this repo on its facebook, it will add some new contributors to the project 
Also habr will be nice too

**Comment by alexanderzobnin** [comment]
Yes, I'll try to do it on this weekend )))

**Comment by alexanderzobnin** [comment]
I added grafana-zabbix plugin on zabbix share website.
https://share.zabbix.com/cat-app/grafana-zabbix-datasource

**Comment by nucleusv** [comment]
Cool, added to https://www.linkedin.com/grp/post/161448-6005783988575232002

Will see feedback

**Comment by alexanderzobnin** [comment]
Great! Thanks!

**Comment by alexanderzobnin** [comment]
i added version for grafana-2 in master branch.

**Comment by nucleusv** [comment]
Alex, great but I don't see recomendtions from Torkel https://github.com/alexanderzobnin/grafana-zabbix/blob/master/zabbix/partials/config.html

current.user in html template
and in datasource to take params from current.jsonData ?
Have you not tested this yet ?

**Comment by alexanderzobnin** [comment]
I asked him in grafana mailing list. I'll test recommendation soon.

**Comment by alexanderzobnin** [comment]
See more in https://groups.io/org/groupsio/grafana/thread/69779
