### ISSUE TITLE
Filtering by Text Metrics

### ISSUE THREAD

**Issue by dan-cytexone** [alexanderzobnin/grafana-zabbix#151]
Hello

Is there a reason it's not possible to filter by Text Metrics?

Thanks so much!

Dan

**Comment by alexanderzobnin** [comment]
@dan-cytexone Hello! It will be possible in 3.0. Try here: http://alpha.grafana-zabbix.org/

**Comment by dan-cytexone** [comment]
Awesome!!!

**Comment by dan-cytexone** [comment]
So this will require Zabbix 3.0 or will you make it compatible with 2.4?

**Comment by alexanderzobnin** [comment]
All features compatible with 2.4. I mean Grafana 3.0, not Zabbix.

**Comment by dan-cytexone** [comment]
Do you mean this branch?  https://github.com/alexanderzobnin/grafana-zabbix/tree/grafana-3.0

If so I tried to download it and install it but can't seem to get it to register.  Does this work with Grafana 2.6 or does it require a beta version?

**Comment by alexanderzobnin** [comment]
Try https://github.com/alexanderzobnin/grafana-zabbix/tree/develop branch with Grafana 3.0 pre-builds.

**Comment by dan-cytexone** [comment]
No luck unfortunately.  I copied the datasource-zabbix folder from the zip into the plugins folder.  The plugin.json file looks different than all of the other ones.  Is there something I need to be doing to that file?  Do I need a beta version of grafana for this?

**Comment by alexanderzobnin** [comment]
@dan-cytexone new version only for Grafana beta release. Read about installation for Grafana 3.0 here: http://docs.grafana-zabbix.org/installation/

**Comment by cytexone** [comment]
I'm sorry I don't understand.  Will this version work with Grafana 2.6 - Grafana v2.6.0 (2015-12-14)?

If not which version of Grafana does this worth with, and can you please provide the URL to download it?

**Comment by alexanderzobnin** [comment]
You can use latest version from master. Builds are here http://grafana.org/download/builds.html
