### ISSUE TITLE
Plugin unavailable Grafana (docker) > 9.1.6 and Zabbix 6.2

### ISSUE THREAD

**Issue by Yukics** [alexanderzobnin/grafana-zabbix#1510]
**Bug description**
When installing zabbix plugin using cli or gui. It is not able to retrieve information from the zabbix API I tried on a development environment and it worked fine, but on """"production"""" environment  (cant say its production if its not working 🙆‍♂️) simply doesn't.

1. It prompts the following output on docker logs
```
grafana_1  | logger=plugin.installer t=2022-10-06T12:18:48.065876136Z level=info msg="Downloaded alexanderzobnin-zabbix-app v4.2.10 zip successfully"
grafana_1  | logger=plugin.manager t=2022-10-06T12:18:48.583979244Z level=info msg="Plugin registered" pluginId=alexanderzobnin-zabbix-datasource
grafana_1  | logger=plugin.manager t=2022-10-06T12:18:48.780037682Z level=error msg="Could not start plugin" pluginId=alexanderzobnin-zabbix-datasource err="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
grafana_1  | logger=plugin.manager t=2022-10-06T12:18:48.780114381Z level=info msg="Plugin registered" pluginId=alexanderzobnin-zabbix-triggers-panel
grafana_1  | logger=plugin.manager t=2022-10-06T12:18:48.780131589Z level=info msg="Plugin registered" pluginId=alexanderzobnin-zabbix-app
```

2. When adding data source it says there is no plugin available
![image](https://user-images.githubusercontent.com/34201397/194311951-09afbfe4-773a-46ce-b077-cbb6b95b35a6.png)

3. 503 error when updating data source
![image](https://user-images.githubusercontent.com/34201397/194312243-be20f6b0-b980-4ae9-8a95-40fef9d80db1.png)

**Expected behavior**
It should simply connect to the zabbix api and be able to scrap data

**Things i tried**
1. Installing the plugin directly with a folder mapping and the enabling it
2. Edit the grafana.ini like:
```
allow_loading_unsigned_plugins = <all plugins that are supposed to be enabled from zabbix-plugin>
```
3. Update even to beta grafana (9.2.0)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| >9.1.6   | 6.2  | 4.2.10                 |

Thank you for your amazing work!

**Comment by SanderDelden** [comment]
As noted in #1507 this is related to the Docker version that you are running. After upgrading to `Docker version 20.10.18, build b40c2f6` we are no longer facing this issue.

**Comment by Yukics** [comment]
Updated to `Docker version 20.10.19`. The problem has been solved. 

Thanks for your help @SanderDelden. 👍
