### ISSUE TITLE
Problem after reboot

### ISSUE THREAD

**Issue by johnk3r** [alexanderzobnin/grafana-zabbix#153]
Hello.
After restarting the server or grafana-server service, it displays error messages attached. I lose all access the web console. To get the access I do snapshot.
![error_grafana](https://cloud.githubusercontent.com/assets/6247648/12978657/75fa6bb2-d0b9-11e5-8039-1c0776e2ca6e.JPG)

**Comment by alexanderzobnin** [comment]
Hello! Seems like Grafana bug. May be better to open issue in Grafana repo?
