### ISSUE TITLE
Add compression to data returned by API

### ISSUE THREAD

**Issue by xcdr** [alexanderzobnin/grafana-zabbix#1548]
**Is your feature request related to a problem? Please describe.**
Slow loading large dashboards when api returns huge data amount.

**Describe the solution you'd like**
ZABBIX plugin returns uncompressed data:
```
https://grafana.example.com/api/datasources/3/resources/zabbix-api
transfer-encoding: chunked

https://grafana.example.com/api/datasources/3/resources/db-connection-post
transfer-encoding: chunked
```
Grafana API returns compressed data:
```
https://grafana.example.com/api/ds/query
content-encoding: gzip
transfer-encoding: chunked
```
Data returned by ZABBIX plugin should be gzipped.

**Comment by alexanderzobnin** [comment]
Hi! Yes, makes sense, I'll check http client config.

**Comment by alexanderzobnin** [comment]
Unfortunately, plugin endpoints do not support gzip encoding now (ignored by grafana)
https://github.com/grafana/grafana/blob/d4e0e75c0cb046910c66e4d194d4a250f586ef8a/pkg/middleware/gziper.go#L51

**Comment by LivingLegendcz** [comment]
still can't turn this feature on? After all, we're a year away...
