### ISSUE TITLE
Zabbix 3.0 Support?

### ISSUE THREAD

**Issue by ne0trace** [alexanderzobnin/grafana-zabbix#155]
Hello,
Does your plugin support Zabbix 3.0 yet?
I don't want to upgrade before it hasn't been officially cleared.

Thank you

**Comment by alexanderzobnin** [comment]
Zabbix 3.0 will be supported in coming version. But now this is still in development.

**Comment by rlex** [comment]
works fine with 3.0 for me.

**Comment by hattaagung** [comment]
work fine with 3.0 for me also

**Comment by ne0trace** [comment]
Thanks guys. Appreciate the help.

**Comment by alexanderzobnin** [comment]
I saw some issues with Trigger panel, but graphs works good.

**Comment by cloudtrends** [comment]
we should add a section about: grafana-zabbix and zabbix version match on readme.md .

**Comment by evandro-portugal** [comment]
it's been some time since I last checked things up here, where is the grafana-zabbix 3.0 branch? has it been merged on another?

**Comment by alexanderzobnin** [comment]
It has been merged into develop.
