### ISSUE TITLE
Can't creat new alert rule

### ISSUE THREAD

**Issue by R1os228** [alexanderzobnin/grafana-zabbix#1562]
Hi!!!

I migrated grafana to docker and updated to version 9.3.2. I started having problems with creating alert rules. I can't fill in the fields: "Group, Host, Item, etc." The only thing I could find by errors is "TypeError: Cannot assign to read only property 'filter' of object '#<Object>'" I'll attach the screenshot. It is likely that the problem is not in Zabbix Plugin. Who met or knows about this problem?

P.S. At the same time, requests go to zabbix and I can build graphs in the same explorer.

![image](https://user-images.githubusercontent.com/123562290/214577499-257665cf-9032-4bb1-ac64-78bda6fd4d6f.png)

**Comment by rilpires** [comment]
Same here. Found this same issue on grafana repo grafana/grafana#60432

**Comment by sfragata** [comment]
I've downgraded to grafana 9.2.10 and it worked

**Comment by sfragata** [comment]
So, grafana has closed the issue because only zabbix plugin has the problem.

**Comment by R1os228** [comment]
@alexanderzobnin plz, can u fix this issue?

**Comment by monika-mikhaiel** [comment]
Hello Team , 
Thanks to support , it is very important

**Comment by alexanderzobnin** [comment]
Hi! Can you try it with latest plugin version 4.3? I cannot reproduce this, maybe it was fixed.

**Comment by R1os228** [comment]
> Hi! Can you try it with latest plugin version 4.3? I cannot reproduce this, maybe it was fixed.

**Comment by R1os228** [comment]
i'm sorry. Yep, in plugin 4.3 this issue is fixed/ But now, We have a big problem with this issue #1583

**Comment by R1os228** [comment]
@alexanderzobnin How I can downgrade version of plugin in docker?
