### ISSUE TITLE
Google-Sheet plugin error installing

### ISSUE THREAD

**Issue by BrunoPi** [alexanderzobnin/grafana-zabbix#1566]
Google-Sheet plugin error installing

log
error installing google sheet plugin in grafana: logger=context userId=1 orgId=1 uname=admin t=2023-01-26T16:16:57.509108317-03:00 level=info msg="Request Completed" method=GET path= /api/plugins/grafana-googlesheets-datasource/markdown/help status=404 remote_addr=10.18.194.19 time_ms=0 duration=790.634μs size=72 referer=http://10.18.194.40:3000/plugins/grafana-googlesheets- datasource handler=/api/plugins/:pluginId/markdown/:name.

This error appears when I try to install google-sheet in grafana. Is there a specific problem that causes this error?

![image](https://user-images.githubusercontent.com/45941021/215850781-dac576f9-d6b6-435a-b9e9-f2de8d3394ab.png)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| x.x.x   | x.x.x  | x.x.x                 |

**Comment by alexanderzobnin** [comment]
This is not related to zabbix plugin.
