### ISSUE TITLE
Triggers panel add Visible name

### ISSUE THREAD

**Issue by roysbike** [alexanderzobnin/grafana-zabbix#157]
Please add a mapping Visible name.

**Comment by alexanderzobnin** [comment]
What you mean? Can you explain?

**Comment by roysbike** [comment]
Если можно, я на русском напишу.  В zabbix в узел сети есть поле Visible name и Host name . Возможно ли  отобразить еще поле  Visible name.

**Comment by alexanderzobnin** [comment]
Да, это возможно будет сделать. А нужно отображать оба имени или только одно по выбору?

**Comment by roysbike** [comment]
Желательно оба, обычно в одном адрес хоста в другом описание .

**Comment by alexanderzobnin** [comment]
Implemented
![screenshot from 2017-12-14 19-50-05](https://user-images.githubusercontent.com/4932851/34004079-004e2802-e108-11e7-8b47-ecb96c805d15.png)
