### ISSUE TITLE
Item scroll missing

### ISSUE THREAD

**Issue by gonzalo-** [alexanderzobnin/grafana-zabbix#1570]
**Describe the bug**
For example on the explore window ( [explore](https://play.grafana-zabbix.org/explore?orgId=2&left=%7B%22datasource%22%3A%22000000005%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22resultFormat%22%3A%22time_series%22%2C%22itemTag%22%3A%7B%22filter%22%3A%22Application%3A+Network+interfaces%22%7D%2C%22queryType%22%3A%220%22%2C%22group%22%3A%7B%22filter%22%3A%22Backend%22%7D%2C%22host%22%3A%7B%22filter%22%3A%22backend03%22%7D%2C%22application%22%3A%7B%22filter%22%3A%22%22%7D%2C%22item%22%3A%7B%22filter%22%3A%22%22%7D%2C%22functions%22%3A%5B%5D%2C%22triggers%22%3A%7B%22count%22%3Atrue%2C%22minSeverity%22%3A3%2C%22acknowledged%22%3A2%7D%2C%22trigger%22%3A%7B%22filter%22%3A%22%22%7D%2C%22tags%22%3A%7B%22filter%22%3A%22%22%7D%2C%22proxy%22%3A%7B%22filter%22%3A%22%22%7D%2C%22options%22%3A%7B%22showDisabledItems%22%3Afalse%2C%22skipEmptyValues%22%3Afalse%2C%22disableDataAlignment%22%3Afalse%2C%22useZabbixValueMapping%22%3Afalse%7D%2C%22table%22%3A%7B%22skipEmptyValues%22%3Afalse%7D%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D) ) in the "item" seccion I have a lot of items that doesn't show completly, if I search for them from the top of my mind, they are there, but I don't have them all in a list with an scroll bar on the side to manually look for them.

**Expected behavior**
When I want to search for an Item it should have an scrollbar to look all of them instead of just guessing names.

**Screenshots**
-

**Network data**

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 9.3.6   | 6.2.3  |  4.2.10               |

**Comment by AbrilJara** [comment]
Hi, i'm having a similar problem with this plugin as well. When I tried to retrive de host for a group it only show 7. Same with all the other drop down menus, it always just show 7 items.

However, when I use the regex expretion "/.*/" fot the hosts for example and select some item all the host are shown in the graph, so they are being retrive by the query but they don't appear in the drow down menu.

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
9.4.3 | 6.0.7 | 4.2.10
