### ISSUE TITLE
Error - "r[e.serviceid] is undefined"

### ISSUE THREAD

**Issue by AlexFrankenstein** [alexanderzobnin/grafana-zabbix#1575]
Same situation as in [issue #1490](https://github.com/alexanderzobnin/grafana-zabbix/issues/1490)

Trying with different versions of zabbix, grafana and plugin

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 9.3.6   | 6.0.2  | 4.2.9                 |
| 8.3.0   | 6.0.2  | 4.2.10               |
| 8.3.0   | 6.2.6  | 4.2.10               |

![01](https://user-images.githubusercontent.com/32343895/220859939-bc585cc7-d76d-47c4-bb9f-2dde8b53f6be.png)
![02](https://user-images.githubusercontent.com/32343895/220859944-1b283744-61bf-4655-a964-7a6fe08ef8e9.png)

**Comment by alexanderzobnin** [comment]
Please, do not open duplicated issue. Closing this in favor of #1490
