### ISSUE TITLE
Historical value of hosts

### ISSUE THREAD

**Issue by avinashasharma-st** [alexanderzobnin/grafana-zabbix#158]
Hi,

I'm totally new to grafana! But this is really cool plugin. very helpful for me to have graphs.  I'm using zabbix to monitor the AWS autoscaling instances. I want to know may I be able to keep the data of an instance after it is deleted. I needed to have metric-vice graphs of autoscaling groups of AWS. But once the load comes down AWS (and zabbix) deletes them. Please let me know whether this can be done. 

Thank you 
Avi

**Comment by nucleusv** [comment]
@avinashasharma-st, the plugin shows only data what you have in your zabbix databases, if there is no data in database you will get nothing. So you need to set up zabbix to don't delete hosts if they were deleted in AWS.

**Comment by avinashasharma-st** [comment]
@nucleusv Thank you for your quick response. But, I can't keep the server in zabbix console. Probably I should make some arrangements in zabbix to detain the details in database but to remove from the web console only. Not sure whether I can do it. 

Best regards,
Avi
