### ISSUE TITLE
Invalid params. Invalid parameter "/": unexpected parameter "user". (with Zabbix 6.4.0)

### ISSUE THREAD

**Issue by javivu** [alexanderzobnin/grafana-zabbix#1583]
**Describe the bug**
Updated Zabbix to 6.4.0 and the Zabbix plugin no work anymore

**Screenshots**
![image](https://user-images.githubusercontent.com/10366008/223490091-b0265cee-682e-4439-a69d-81dde5f6d7a4.png)

**Software versions**
| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 9.4.3   | 6.4.0  |  4.2.10                |

**Comment by evertonpaiva** [comment]
Same issue here. I'm using exactly the same versions.

**Comment by javivu** [comment]
I know what the problem is, in Zabbix 6.4 the "user" param has changed to "username", but I don't know how to solve it.

**Comment by alexdu828** [comment]
I also encountered the same problem

Zabbix Version:6.4.0
Grafana oss version:9.4.3
plugins version:alexanderzobnin-zabbix-app @ 4.2.10

<img width="581" alt="image" src="https://user-images.githubusercontent.com/13128500/223717171-8209d7c3-d76c-4efa-a940-ba2afbc85029.png">

**Comment by marioandrepereira** [comment]
Estou com o mesmo problema, achei um repo que ele mandou um .zip mas quando instalado o grafana não reconhecia.

**Comment by marioandrepereira** [comment]
https://github.com/alexanderzobnin/grafana-zabbix/issues/1544

**Comment by bpress** [comment]
The current official release 4.2.10 still uses "user" instead of "username" when talking to Zabbix and requesting a "user.login" api call.

I have not been able to recompile the plugin with a proper fix.

However I managed to patch an **ugly** but effective workaround in Zabbix 6.4 php frontend rather than the plugin itself.

I know, this sounds orrible and any apt update will break it and require a new patching, but right now I have zero time to think to anything better.

I patched the file 

`/usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php`

like this:

```Diff
--- /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php.orig	2023-03-08 16:23:26.555055621 +0100
+++ /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php	2023-03-08 16:22:46.378217849 +0100
@@ -128,6 +128,13 @@
 				$newTransaction = true;
 			}

+			// UGLY GRAFANA DATASOURCE HACK
+			// rename "user" param to "username" when present
+			if ($params['user'] ?? null) {
+				$params['username'] = $params['user'];
+				unset($params['user']);
+			}
+
 			$result = call_user_func_array([$this->serviceFactory->getObject($api), $method], [$params]);

 			// if the method was called successfully - commit the transaction
```
 
 maybe this helps

**Comment by javivu** [comment]
> The current official release 4.2.10 still uses "user" instead of "username" when talking to Zabbix and requesting a "user.login" api call.
> 
> I have not been able to recompile the plugin with the proper fix which seems to be included in the master branch.
> 
> However I managed to patch an **ugly** but effective workaround in Zabbix 6.4 php frontend rather than the plugin itself.
> 
> I know, this sounds orrible and any apt update will break it and require a new patching, but right now I have zero time to think to anything better.
> 
> I patched the file
> 
> `/usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php`
> 
> like this:
> 
> ```diff
> --- /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php.orig	2023-03-08 16:23:26.555055621 +0100
> +++ /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php	2023-03-08 16:22:46.378217849 +0100
> @@ -128,6 +128,13 @@
>  				$newTransaction = true;
>  			}
> 
> +			// UGLY GRAFANA DATASOURCE HACK
> +			// rename "user" param to "username" when present
> +			if ($params['user'] ?? null) {
> +				$params['username'] = $params['user'];
> +				unset($params['user']);
> +			}
> +
>  			$result = call_user_func_array([$this->serviceFactory->getObject($api), $method], [$params]);
> 
>  			// if the method was called successfully - commit the transaction
> ```
> 
> maybe this helps

For my case, is a "acceptable" temporal workaround!! Thanks!

**Comment by cafetera** [comment]
Wow, I've been breaking my head for last couple of days, tons of issues trying recompile the source for Alexanders...

You are a genius!

**Comment by marioandrepereira** [comment]
> ```diff
> /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php	2023-03-08 16:22:46.378217849 +0100
> ```

Tu é um mestre

**Comment by mfsirilo** [comment]
Thankyou!!! @bpress

**Comment by pqvindesland** [comment]
i´m on Zabbix 6.0.13 and I think that I am seeing the same issue in error_log I have 
AH01071: Got error 'PHP message: PHP Notice:  Parameter "/user" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1324

Also I am not seeing any data but it pulls in groups and hostnames but no actual data, is that expected with this issue?

The company that I work for doesn't allow me to run the patch command, can I add the modifications manually to CLocalApiClient.php ?

**Comment by bpress** [comment]
> i´m on Zabbix 6.0.13 and I think that I am seeing the same issue in Apache's error_log I have AH01071: Got error 'PHP message: PHP Notice: Parameter "/user" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1324
> 
> Also I am not seeing any data but it pulls in groups and hostnames but no actual data, is that expected with this issue?
> 
> The company that I work for doesn't allow me to run the patch command, can I add the modifications manually to CLocalApiClient.php ?

@pqvindesland I don't think your lack of data is related to this issue. AFAIK Zabbix 6.0 gives only a deprecation warning but still accepts "user"; the change I made is only for 6.4. I have no idea on why you don't get actual data.
[Offtopic] I had a similar problem: I upgraded grafana from 8.x to 9.4 and Zabbix from 5.4 to 6.4. During this process I got almost all panels in dashboards with "no data" and the infamous corner red triangle: this seems to be related to the way each panel was linked to the zabbix datasource. I had to export the json for all the dashboards, manually edit it by removing all "uid" references for each panel or metric query, then reimport the json. UIDs got regenerated and the dashboard were restored.

**Comment by EHRETic** [comment]
Same for me on my test instance.
Grafana  9.3.6
Plugin 4.2.10
Zabbix 6.4.0

**Comment by globaluk** [comment]
Same for me, with Grafana and a ZabbixAPI for C# that we use too.  Thank you Javivu, your 'hack' has fixed both issuesfor now !

**Comment by isaqueprofeta** [comment]
@alexanderzobnin seems like a new version compatibility issue.

**Comment by bpress** [comment]
> @alexanderzobnin seems like a new version compatibility issue.

The issue was fixed in the master branch on Dec 27, however the master branch has not been published as a new release binary, and I am struggling to build it from sources. No matter what, I keep getting errors either from Node or Go. That's why I went for a patch in Zabbix. Quick and dirty.

**Comment by salarsp** [comment]
This file _/usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php_ and its path aren't available on my os. Do you know how I can create this file? I found a way to install it by installing php-zabbix-api but the package has been removed from GitHub.
my ubuntu version is 22.04, my zabbix version is 6.4.0 and my grafana version is 9.4.3

**Comment by Xileck** [comment]
> > The current official release 4.2.10 still uses "user" instead of "username" when talking to Zabbix and requesting a "user.login" api call.
> > I have not been able to recompile the plugin with the proper fix which seems to be included in the master branch.
> > However I managed to patch an **ugly** but effective workaround in Zabbix 6.4 php frontend rather than the plugin itself.
> > I know, this sounds orrible and any apt update will break it and require a new patching, but right now I have zero time to think to anything better.
> > I patched the file
> > `/usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php`
> > like this:
> > ```diff
> > --- /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php.orig	2023-03-08 16:23:26.555055621 +0100
> > +++ /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php	2023-03-08 16:22:46.378217849 +0100
> > @@ -128,6 +128,13 @@
> >  				$newTransaction = true;
> >  			}
> > 
> > +			// UGLY GRAFANA DATASOURCE HACK
> > +			// rename "user" param to "username" when present
> > +			if ($params['user'] ?? null) {
> > +				$params['username'] = $params['user'];
> > +				unset($params['user']);
> > +			}
> > +
> >  			$result = call_user_func_array([$this->serviceFactory->getObject($api), $method], [$params]);
> > 
> >  			// if the method was called successfully - commit the transaction
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > maybe this helps
> 
> For my case, is a "acceptable" temporal workaround!! Thanks!

i made this change and added it to my docker compose:

`
 zabbix-web-apache-mysql:
  image: zabbix/zabbix-web-apache-mysql:alpine-6.4-latest
  profiles:
   - all
  ports:
   - "8081:8080"
   - "8443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
   - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
   **- ./zbx_env/CLocalApiClient.php:/usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php**
  deploy:
`

i verified the container and the file does exist there, however i still get the same rror even tho i made the changes like you.

What could be wrong?

**Comment by dassump** [comment]
Hello folks,

According to [ZBXNEXT-8085](https://support.zabbix.com/browse/ZBXNEXT-8085), this was responsible for removing API features marked as deprecated. These were the changes in the [CUser.php](https://git.zabbix.com/projects/ZBX/repos/zabbix/commits/d5b7651f6e7dd22bd1b6131de82cd78740a743ed#ui/include/classes/api/services/CUser.php) file.

```diff
public function login(array $user) {
	$api_input_rules = ['type' => API_OBJECT, 'fields' => [
-		'user' =>	['type' => API_STRING_UTF8, 'flags' => API_DEPRECATED, 'replacement' => 'username', 'length' => 255],
		'username' =>	['type' => API_STRING_UTF8, 'flags' => API_REQUIRED, 'length' => 255],
		'password' =>	['type' => API_STRING_UTF8, 'flags' => API_REQUIRED, 'length' => 255],
		'userData' =>	['type' => API_FLAG]
	]];
```

Reverting red line changes (file /usr/share/zabbix/include/classes/api/services/CUser.php) in the login function on line 1472 the authentication worked again.
Remember, this is just a workaround while we wait for a new release of this wonderful plugin :rocket:

**Comment by vinisvolinski** [comment]
@dassump thanks dude!!! this works for me

**Comment by brunozanon** [comment]
@dassump Thanks my friend, very useful!

**Comment by erasedhammer99** [comment]
Is there any ETA for a plugin update to support Zabbix 6.4 API?

**Comment by paulogcrio** [comment]
> The current official release 4.2.10 still uses "user" instead of "username" when talking to Zabbix and requesting a "user.login" api call.
> 
> I have not been able to recompile the plugin with the proper fix which seems to be included in the master branch.
> 
> However I managed to patch an **ugly** but effective workaround in Zabbix 6.4 php frontend rather than the plugin itself.
> 
> I know, this sounds orrible and any apt update will break it and require a new patching, but right now I have zero time to think to anything better.
> 
> I patched the file
> 
> `/usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php`
> 
> like this:
> 
> ```diff
> --- /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php.orig	2023-03-08 16:23:26.555055621 +0100
> +++ /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php	2023-03-08 16:22:46.378217849 +0100
> @@ -128,6 +128,13 @@
>  				$newTransaction = true;
>  			}
> 
> +			// UGLY GRAFANA DATASOURCE HACK
> +			// rename "user" param to "username" when present
> +			if ($params['user'] ?? null) {
> +				$params['username'] = $params['user'];
> +				unset($params['user']);
> +			}
> +
>  			$result = call_user_func_array([$this->serviceFactory->getObject($api), $method], [$params]);
> 
>  			// if the method was called successfully - commit the transaction
> ```
> 
> maybe this helps

you are a genius!!!!!!

**Comment by erasedhammer99** [comment]
> > The current official release 4.2.10 still uses "user" instead of "username" when talking to Zabbix and requesting a "user.login" api call.
> > I have not been able to recompile the plugin with the proper fix which seems to be included in the master branch.
> > However I managed to patch an **ugly** but effective workaround in Zabbix 6.4 php frontend rather than the plugin itself.
> > I know, this sounds orrible and any apt update will break it and require a new patching, but right now I have zero time to think to anything better.
> > I patched the file
> > `/usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php`
> > like this:
> > ```diff
> > --- /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php.orig	2023-03-08 16:23:26.555055621 +0100
> > +++ /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php	2023-03-08 16:22:46.378217849 +0100
> > @@ -128,6 +128,13 @@
> >  				$newTransaction = true;
> >  			}
> > 
> > +			// UGLY GRAFANA DATASOURCE HACK
> > +			// rename "user" param to "username" when present
> > +			if ($params['user'] ?? null) {
> > +				$params['username'] = $params['user'];
> > +				unset($params['user']);
> > +			}
> > +
> >  			$result = call_user_func_array([$this->serviceFactory->getObject($api), $method], [$params]);
> > 
> >  			// if the method was called successfully - commit the transaction
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > maybe this helps
> 
> you are a genius!!!!!!

That does indeed suck. I guess we can't expect an update to this plugin in the future?

**Comment by danielbastosbr** [comment]
> The current official release 4.2.10 still uses "user" instead of "username" when talking to Zabbix and requesting a "user.login" api call.
> 
> I have not been able to recompile the plugin with the proper fix which seems to be included in the master branch.
> 
> However I managed to patch an **ugly** but effective workaround in Zabbix 6.4 php frontend rather than the plugin itself.
> 
> I know, this sounds orrible and any apt update will break it and require a new patching, but right now I have zero time to think to anything better.
> 
> I patched the file
> 
> `/usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php`
> 
> like this:
> 
> ```diff
> --- /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php.orig	2023-03-08 16:23:26.555055621 +0100
> +++ /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php	2023-03-08 16:22:46.378217849 +0100
> @@ -128,6 +128,13 @@
>  				$newTransaction = true;
>  			}
> 
> +			// UGLY GRAFANA DATASOURCE HACK
> +			// rename "user" param to "username" when present
> +			if ($params['user'] ?? null) {
> +				$params['username'] = $params['user'];
> +				unset($params['user']);
> +			}
> +
>  			$result = call_user_func_array([$this->serviceFactory->getObject($api), $method], [$params]);
> 
>  			// if the method was called successfully - commit the transaction
> ```
> 
> maybe this helps

Esse Hack funcionou. It´s worked.

**Comment by alexanderzobnin** [comment]
Duplicated. Fixed in 4.3 release.

**Comment by marioandrepereira** [comment]
Alguém pode compartilhar a versão antiga do diretorio /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php

**Comment by bpress** [comment]
> Alguém pode compartilhar a versão antiga do diretorio /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php

@marioandrepereira you can simply delete the lines marked in green from the file, to revert to the original version

**Comment by DiegoRiopae** [comment]
> A versão oficial atual 4.2.10 ainda usa "usuário" em vez de "nome de usuário" ao falar com o Zabbix e solicitar uma chamada de API "user.login".
> 
> Não consegui recompilar o plug-in com a correção adequada que parece estar incluída na ramificação principal.
> 
> No entanto, consegui corrigir uma solução **feia** , mas eficaz, no front-end php do Zabbix 6.4, em vez do próprio plug-in.
> 
> Eu sei, isso parece horrível e qualquer atualização do apt irá quebrá-lo e exigir um novo patch, mas agora não tenho tempo para pensar em algo melhor.
> 
> Eu corrigi o arquivo
> 
> `/usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php`
> 
> assim:
> 
> ```diff
> --- /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php.orig	2023-03-08 16:23:26.555055621 +0100
> +++ /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php	2023-03-08 16:22:46.378217849 +0100
> @@ -128,6 +128,13 @@
>  				$newTransaction = true;
>  			}
> 
> +			// UGLY GRAFANA DATASOURCE HACK
> +			// rename "user" param to "username" when present
> +			if ($params['user'] ?? null) {
> +				$params['username'] = $params['user'];
> +				unset($params['user']);
> +			}
> +
>  			$result = call_user_func_array([$this->serviceFactory->getObject($api), $method], [$params]);
> 
>  			// if the method was called successfully - commit the transaction
> ```
> 
> talvez isso ajude

I have the same problem. In that case, in which part of that file can I insert this code?

**Comment by bpress** [comment]
> I have the same problem. In that case, in which part of that file can I insert this code?
@DiegoRiopae that piece of code I posted can be copied and paste as a .patch file, anyway it's around line 130.

BTW, I tried to upgrade to version 4.3.0 of the plugin but it messes around even more, so I reverted to 4.2.10 with the ugly patch.

**Comment by w0ox** [comment]
@dassump, thank you, your decision helped me)

**Comment by TimEuphoria** [comment]
Thank you @bpress

**Comment by sani080301** [comment]
@dassump, it's working, thank you

**Comment by Vanieltk** [comment]
Hello, has this problem not yet been officially resolved?
