### ISSUE TITLE
When will the new release 4.2.11 be released?

### ISSUE THREAD

**Issue by aoberest** [alexanderzobnin/grafana-zabbix#1586]
Hi. Thank you for the great work!
@alexanderzobnin 
We need a fix [SLA support in Zabbix 6.0](https://github.com/alexanderzobnin/grafana-zabbix/pull/1547)
Please release a new version of the plugin.

**Comment by Xileck** [comment]
Also this is happening with 6.4.0:

https://github.com/alexanderzobnin/grafana-zabbix/issues/1583

**Comment by cdiamantis** [comment]
There are some workarounds for 6.4.0. 
The easiest and most straightforward is to edit CLocalApiClient.php of Zabbix.
However, the official release of 4.2.11 would be great.

**Comment by alexanderzobnin** [comment]
4.3 Released
