### ISSUE TITLE
Zabbix hosts not showing up in Grafana

### ISSUE THREAD

**Issue by BrunoRobertoSales** [alexanderzobnin/grafana-zabbix#1588]
**Describe the bug**
Zabbix hosts not showing up in Grafana

**Expected behavior**
Show Zabbix host in Grafana

**Screenshots**
![1](https://user-images.githubusercontent.com/47142683/224514523-4134068c-57bf-419a-9736-c2ff43677640.JPG)
![2](https://user-images.githubusercontent.com/47142683/224514954-65ebb5ed-ca88-4c38-a947-841f24739497.JPG)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.5.15   | 6.2.7  | 4.1.5                 |

Hello everyone.

Start a new Zabbix Server and a new Grafana Server, however, as seen in the image, the hosts do not appear. I did several tests.
** I started a Zabbix Server and a Grafana Server on different servers = It didn't work.
** I installed Grafana Server on the same server as Zabbix Server = it didn't work.
** I created a Grafana user in Zabbix as Admin role, it didn't work. I tried to integrate Zabbix Server and Grafana Server with Zabbix Admin user, it didn't work either.

** As can be seen in the image above, Zabbix Server is collecting information normally.

In case anyone has been through this and can help me. Thank you all for your help.

**Comment by roonaldoch** [comment]
Hello @BrunoRobertoSales, how did you solve this problem? I'm having the same one

**Comment by BrunoRobertoSales** [comment]
Hi roonaldoch

This was almost 2 years ago, I don't remember the resolution itself, but I did solve it... I remember that at the time, I was installing a very old version of Grafana (due to inexperience).

When I installed the current version of Grafana, the problem was solved.

**Comment by roonaldoch** [comment]
Thanks @BrunoRobertoSales , I'm currently experiencing the same issue when my Grafana, zabbix and zabbix plugin updated.

**Comment by BrunoRobertoSales** [comment]
> Thanks [@BrunoRobertoSales](https://github.com/BrunoRobertoSales) , I'm currently experiencing the same issue when my Grafana, zabbix and zabbix plugin are updated to latest versions.

Have you checked if the grafana user in Zabbix has the necessary permissions? If the grafana user does not have the read permissions to read the hosts in Zabbix, monitoring does not work...
