### ISSUE TITLE
Grafana 3.0 Cannot get working :(

### ISSUE THREAD

**Issue by dan-cytexone** [alexanderzobnin/grafana-zabbix#159]
Hi :)

With the latest git download of the 3.0 grafana-zabbix branch after extensive adjustment I cannot get the plugin working.  

The plugin registers in Grafana, and I've narrowed the issue to the module.js file.  A previous download did quasi work, but the latest version did not.

The Error when trying to add a datasource (in little widget window)
Plugin Error
Failed to find exported plugin component for ds-config-zabbix

In the grafana.log file (I x'd out IP address)
2016/02/29 02:31:27 [I] Database: sqlite3
2016/02/29 02:31:27 [I] Migrator: Starting DB migration
2016/02/29 02:31:27 [I] Plugins: Scan starting
2016/02/29 02:31:27 [I] Plugins: Scaning dir /usr/share/grafana/public/app/plugins
2016/02/29 02:31:27 [I] Plugins: Scaning dir /var/lib/grafana/plugins
2016/02/29 02:31:27 [I] Plugins: Adding route /public/plugins/triggers -> /usr/share/grafana/public/app/plugins/panel/panel-triggers
2016/02/29 02:31:27 [I] Plugins: Adding route /public/plugins/zabbix -> /usr/share/grafana/public/app/plugins/datasource/datasource-zabbix
2016/02/29 02:31:27 [I] Listen: http://0.0.0.0:3000
2016/02/29 02:32:31 [I] Completed XXX.XXX.XXX.XX admin "GET /datasources/new HTTP/1.1" 404 Not Found 5497 bytes in 1148us

The extracted files are located in 
/usr/share/grafana/public/app/plugins/datasource/datasource-zabbix

I've tried
/usr/share/grafana/public/app/plugins/datasource/zabbix

Any help would be truly appreciated as I'm very excited about the new speed increase.

Dan

**Comment by dan-cytexone** [comment]
FYI the last line in the grafana.log was when I tried to add a new connection.

**Comment by dan-cytexone** [comment]
I think i got it working by downloading the develop branch vs the grafana-3.0.  Is this correct?

If so how do I select all hosts now from the dropdown, as the All option is no longer listed.

Thanks so much!

Dan

**Comment by alexanderzobnin** [comment]
Hello! Now latest code in develop branch, you right. In query editor you can set regex for all values: `/.*/`

**Comment by dan-cytexone** [comment]
Thanks!  That worked for all values.  FYI Application selection dropdown is not populating, and it seems the Items when a host are selected are not completely displayed.  It's only showing the first 50 or so.

**Comment by alexanderzobnin** [comment]
Elements in dropdown list are limited. You can start typing and see result.

**Comment by dan-cytexone** [comment]
Yes you are correct, typing you do see result.  However in Grafana 2.6 it shows all items in a long list, is this a new limitation of the integration or Grafana?

Do your applications work, as mine are always blank no matter what I select? 

Also the scale multiplier seems to be missing.  Is this on your end or grafana?

Thanks so much for your hard work!

**Comment by alexanderzobnin** [comment]
The limitation is in my plugin. I can add option to data source config for this. Only host and item are required for request. About multiplier - I can add function if you need it - it's quickly.

**Comment by dan-cytexone** [comment]
This sounds amazing!  So to clarify, you will be revising the interface with the following

1. Fixing the Application Selection Box so it works
2. Adding the scale multiplier back into the query section
3. Adding the alias field back into the query section
4. Changing the database connection settings so you can specify the amount of items in dropdown
5. This one wasn't discussed but is it your plugin or grafana 3 that removed the ability to use Templating variables?

Thank you so much!!

**Comment by alexanderzobnin** [comment]
See examle of variables usage:
http://alpha.grafana-zabbix.org/dashboard/db/template-linux-server?panelId=1&fullscreen&edit
And also see alias function:
http://alpha.grafana-zabbix.org/dashboard/db/aggregations?panelId=6&fullscreen&edit

**Comment by dan-cytexone** [comment]
Awesome!  The variable usage I just wasn't using proper case sensitivity.

In your sample the Applications are working.  In mine they do not.  Do you know what I can do to troubleshoot?

Regarding Alias I do not see a place to specify an alias for the query.

**Comment by alexanderzobnin** [comment]
You need to add options -> alias -> setAlias function and specify alias as function argument.

**Comment by dan-cytexone** [comment]
Ok awesome.  I will give that a shot. 

Can you let me know about getting the application drop down working, the scale multiplier, and the ability to specify / increase the amount of items in drop down.  (The first two are the most critical)

**Comment by alexanderzobnin** [comment]
Ok, shure. I will update this issue.

**Comment by alexanderzobnin** [comment]
About applications. Can you provide more info - JS console log?

**Comment by dan-cytexone** [comment]
Ok after looking at my console vs looking at your console, I couldn't find any errors but I do see the problem.  (Not the cause just the problem)

Here is a screenshot from your applications

![image](https://cloud.githubusercontent.com/assets/17113202/13547781/566cc244-e2ad-11e5-86ae-4b10d22fe425.png)

Here is a screenshot from my applications

![image](https://cloud.githubusercontent.com/assets/17113202/13547785/60c5dd70-e2ad-11e5-8927-7044dcaffe1e.png)

Notice how none of my applications reference hosts?

WHere should I look to dig deeper?

**Comment by dan-cytexone** [comment]
Anything else you need from my end?

**Comment by alexanderzobnin** [comment]
I need time to deal with it. I'll write you if I need something else.

**Comment by cytexone** [comment]
Hi :)

Any update on these items?

Thanks so much.

**Comment by alexanderzobnin** [comment]
Hi, I've removed hosts, apps and items caching due performance problem. See develop branch. I going to release beta at this week.

**Comment by cytexone** [comment]
Thanks that sounds great

Can you confirm these items have been resolved?

Fixing the Application Selection Box so it works
Adding the scale multiplier back into the query section
