### ISSUE TITLE
Cannot create or edit variables (unexpected error happened)

### ISSUE THREAD

**Issue by IlefMEDINI** [alexanderzobnin/grafana-zabbix#1590]
Hello,

After updating the plugin to the 4.3.0 version, We have an unexpected error while accessing variables (to create or even to modify variables) 

![image](https://user-images.githubusercontent.com/105661456/226677647-3a5e3d69-1d45-46f3-8928-2c9943a05643.png)
 
Also another bug with the data source when we enable the Direct DB Connection, we have an undefined DB connector type instead of finding the right one ( we had to find as a result : DB connector type: PostgreSQL )

![image](https://user-images.githubusercontent.com/105661456/226680498-bb50a1a0-dd06-4c09-ba94-ef22b2da5de1.png)
 
**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 9.4.3   | 6.4.0  | 4.3.0                 |

**Comment by gcsprojects** [comment]
Yep getting the same error as well with latest plugin on Grafana 9.4.3 - again when trying to create or edit a variable
