### ISSUE TITLE
Top host 

### ISSUE THREAD

**Issue by Yhaja10** [alexanderzobnin/grafana-zabbix#1591]
Is there a way to show the top host that have more problems?

I show the data of zabbix problems using table and transform to get columns, but in the column of hosts (that have host, hostid, etc) don’t let me group by, when I choose the columns of severity or description works fine I can group by and have the top of problems

**Comment by alexanderzobnin** [comment]
It's can be done using transformations, but it's tricky I would say. Here you can find an example I build
https://play.grafana-zabbix.org/d/1nHK64BVk/showcase?orgId=2&from=1679568633314&to=1679590233314&viewPanel=10

**Comment by Yhaja10** [comment]
Thanks so much!!!

**Comment by andreaszaia** [comment]
this link not working anymore and i have just that same question!!
