### ISSUE TITLE
Can not get network interfaces bits send/received after upgrade 4.3.0

### ISSUE THREAD

**Issue by leonanu** [alexanderzobnin/grafana-zabbix#1594]
Can not get network interfaces bits send/received metrics after upgrade 4.3.0

Zabbix Ver: 6.2.7
Grafana Ver: 9.3.8/9.3.11

**Comment by alexanderzobnin** [comment]
Could you explain it a bit? What's a query you have? What do you mean cannot get metric? In the list of metrics or the time series data?

**Comment by alexanderzobnin** [comment]
Are you sure item tag is right? You can delete tag and see if you can get interface names in the items.

**Comment by alexanderzobnin** [comment]
@Angrik 
https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
>Note: If you need to specify the version of a plugin, then you can add it to the GF_INSTALL_PLUGINS environment variable. Otherwise, the latest is used. For example: -e "GF_INSTALL_PLUGINS=grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5".

**Comment by Angrik** [comment]
Both not working - metrics list is empty thus 'no data' in graphs. Everything is fine and same in Zabbix, as it was 2 days ago.

**Comment by alexanderzobnin** [comment]
Ok, got it, will try to investigate.

**Comment by alexanderzobnin** [comment]
Confirmed, I have the same issue.

**Comment by alexanderzobnin** [comment]
I think the problem is in the wrong regex for tags. It does not handle properly spaces in tag value.

**Comment by alexanderzobnin** [comment]
@Angrik Can you check it again and tell me if issue is only related to the tags with spaces in the value, like `Application: Network interfaces`? I fixed it, but want to double check if I found root cause correctly.

**Comment by Angrik** [comment]
Yeah, seems about right.  NO spaces:
![image](https://user-images.githubusercontent.com/70021128/227226982-de18b7cb-6de0-41f0-a40e-957cf6165c3b.png)
With spaces empty list:
![image](https://user-images.githubusercontent.com/70021128/227227063-22a5c7b7-9242-486a-a656-ddfee78d32e3.png)
