### ISSUE TITLE
Misplaced graphs in bar mode?

### ISSUE THREAD

**Issue by rlex** [alexanderzobnin/grafana-zabbix#160]
Not sure how to describe it but here it is

<img width="1667" alt="screen shot 2016-03-01 at 21 08 14" src="https://cloud.githubusercontent.com/assets/84462/13436822/257773c2-dff2-11e5-95f8-85053e300713.png">
<img width="1662" alt="screen shot 2016-03-01 at 21 10 03" src="https://cloud.githubusercontent.com/assets/84462/13436823/2578c984-dff2-11e5-8c0d-6d042aa6632a.png">

As you can see, sometimes one bar overlaps another and make it practically useless.

**Comment by alexanderzobnin** [comment]
@rlex Do you use stacked graph mode? Looks like not.

**Comment by rlex** [comment]
Yes, this happens with stacked as well.

**Comment by alexanderzobnin** [comment]
This issue may be due different metric timestamps in Zabbix. Try to use groupBy function in version 3.0 or set max data points value.
