### ISSUE TITLE
Add datasource and test connection just hangs at testing 3.0

### ISSUE THREAD

**Issue by steven792** [alexanderzobnin/grafana-zabbix#163]
I get no errors after installing and restarting Grafana. I have 3.0 Zabbix develop installed (also tried the 3.0 branch with same results) I have checked and there are no errors logged in grafana. the login is setup in zabbix for the api, no errors in zabbix logs either.  After I add the zabbix datasource whether using direct or proxy, click on test -> I get a "datasource saved" upper right box and the testing progress bar just appears and does nothing. Also if I attempt to add Zabbix dashboard, there is only a blank panel and no query options.

**Comment by alexanderzobnin** [comment]
Try to use direct mode instead proxy in data source config.

**Comment by steven792** [comment]
I actually tried that with the same result. I verified the zabbix server is reachable from the griffin box and tried every variation of settings I could think of and was unable to get testing to complete.

**Comment by alexanderzobnin** [comment]
Any errors in apache log on zabbix server?

**Comment by steven792** [comment]
no errors in the log  and I've verified connectivity to the api 

curl -i -X POST -H 'Content-Type: application/json-rpc' -d '{"params": {"password": "*******", "user": "******"}, "jsonrpc": "2.0", "JSON-rpc": "3.0", "method": "user.login", "id": 0}' http://***.*********.com/zabbix/api_jsonrpc.php
HTTP/1.1 200 OK
Date: Fri, 04 Mar 2016 16:46:23 GMT
Server: Apache/2.4.6 (CentOS) PHP/5.4.16
X-Powered-By: PHP/5.4.16
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000
Content-Length: 68
Content-Type: application/json

{"jsonrpc":"2.0","result":"b107b1741a320cb12a412afe6e3ec70e","id":0}

**Comment by steven792** [comment]
side note This is on Zabbix 3.0 LTS / Grafana v2.6.0

**Comment by alexanderzobnin** [comment]
Can you check network requests in browser dev tools?

**Comment by steven792** [comment]
Sure I'll check that. Also as a note. the 3.0 plugin as downloaded causes errors unless the plugin.son is edited because items are missing in them as downloaded:

comes like this:
{
  "type": "datasource",
  "name": "Zabbix",
  "id": "zabbix",

  "module": "plugins/zabbix/module",

  "staticRoot": ".",

  "metrics": true,
  "annotations": true
}


but should look like: ??? when I add the "pluginType" grafana will load the plugin otherwise it errors that pluginType is missing ( and without the partials section, there is config options missing for the plugin datasource page.
{
  "pluginType": "datasource",
  "type": "datasource",
  "name": "Zabbix",
  "id": "zabbix",

  "module": "plugins/zabbix/module",
  "partials": {
    "config": "plugins/zabbix/partials/config.html",
    "query": "plugins/zabbix/partials/query.editor.html",
    "annotations": "plugins/zabbix/partials/annotations.editor.html"
  },

  "staticRoot": ".",

  "metrics": true,
  "annotations": true
}

**Comment by steven792** [comment]
So all the network calls ran when selecting test and returned 200:
<img width="1336" alt="network_zabbix_test" src="https://cloud.githubusercontent.com/assets/17636451/13537695/ba1896a8-e20b-11e5-8ccf-59017c6881e6.png">

**Comment by alexanderzobnin** [comment]
Version 3.0 only compatible with Grafana 3.0. Requests in proxy mode are going to Grafana backend first. Better to use direct mode for debugging.

**Comment by steven792** [comment]
Where is there a Grafana 3.0, I've not seen that anywhere available.  Otherwise will previous 2.5 version work with zabbix 3.x api?

**Comment by alexanderzobnin** [comment]
Grafana 3.0 still is in development and only nightly builds are available.

**Comment by alexanderzobnin** [comment]
I'm not sure about zabbix 3.0 in plugin version 2.5. When I builded it, Zabbix 3.0 wasn't released. I planned full zabbix 3.0 support in new version, but I need some time to finish it.

**Comment by steven792** [comment]
I have Grafana 3.0 installed now and latest build grafan-zabbix 3.0  but as soon as I go to add datasource "Zabbix" no config options appear and get this error in upper right corner: Plugin Error
Failed to find exported plugin component for ds-config-zabbix

**Comment by steven792** [comment]
nevermind/ I fixed it.

**Comment by stephenh1991** [comment]
Hi, 

I'm having the same problem, what was your solution?

Thanks,
Steve

**Comment by alexanderzobnin** [comment]
Hi, folks! Do you still have this problem?

**Comment by stephenh1991** [comment]
Hi Alexander,

I was .2 of a revision out on Grafana, after we did the upgrade to that
package everything worked perfectly.

Thanks for checking! :)
Steve
