### ISSUE TITLE
how to reduce ajax request numbers of api_jsonrpc.php

### ISSUE THREAD

**Issue by wanglf** [alexanderzobnin/grafana-zabbix#164]
i  am trying to put all rack switches uplink port traffic into a single dashboard. after do that, i found too many(about 1022) ajax request to zabbix page **api_jsonrpc.php**  produced.  as a result, it takes nearly 30s to load whole page. 

now this dashboard has 36 switches , every switch two ports, and every port get in and out traffic direction.

Is there a way to reduce ajax request?

**Comment by alexanderzobnin** [comment]
I'm working on this problem in version 3.0.
