### ISSUE TITLE
Failed to get plugin dashboards

### ISSUE THREAD

**Issue by ninidas** [alexanderzobnin/grafana-zabbix#1644]
I connected the Plugin to Zabbix and tested it, but when I select dashboard, I got the error "Failed to get plugin dashboards"

Do you know how to fix it ?

Grafana v9.5.2
Zabbix 6.4.3
Grafana-Zabbix Plugin 4.3.1

![image](https://github.com/alexanderzobnin/grafana-zabbix/assets/51442132/7b27e79d-9202-4d0e-ad51-da4d05aab891)

**Comment by saeednaimi** [comment]
i have same issue too.

**Comment by sitoplex** [comment]
Same issue

**Comment by Jimiwho** [comment]
Same issue too

Grafana v9.5.3
Grafana-Zabbix Plugin 4.3.1
Zabbix 6.0.18 (LTS)

**Comment by ninidas** [comment]
Found my issue.
I just added manually a new dashboard and select the Zabbix the Data source to add new dashboard.
