### ISSUE TITLE
Problem getting annotations to work with  2.5.1 under 2.6.0  -> zabbix 2.4 & 3.0

### ISSUE THREAD

**Issue by svdasein** [alexanderzobnin/grafana-zabbix#165]
I strongly suspect this is a user (me) problem rather than a bug, but:

I've been unable to get annotations to work against either Zabbix versions 2.4 or 3.0.  Everything else (so far) looks great - I just can't seem to figure out what magic I need to do to get events showing up on the graphs.  I did follow the video tutorial - the user interface in 2.6.0 is a bit different from what's shown there.  I've tried numerous combinations of leaving group/host blank, with wildcards, with fully spelled out names,etc, and I've tried many permutations of wildcards in the trigger field. To date I've not been able to get anything to show up on the graphs. Am I missing something?

**Comment by svdasein** [comment]
I guess it's not me - I found volter's patches and manually patched datasource.js.  It's working now.

Do you have an eta as to when that stuff will be merged?

**Comment by alexanderzobnin** [comment]
Hi! I fixed it in new plugin version. But it still in development.

**Comment by svdasein** [comment]
Thanks - I actually was just talking w/ volter on #zabbix.  Sounds like I should really move everything to the dev version both with grafana and grafana-zabbix.

This is a beautiful piece of work by the way - THANK YOU!

**Comment by tomcsi** [comment]
Hi! I try this latest beta plugin on zabbix 3.0.1 server, but annotations not working.

**Comment by alexanderzobnin** [comment]
Hi, @tomcsi ! Try to download latest releas (I've updated package). Seems, it's due large amount of triggers. Now I filtrer triggers by dashboard time.
