### ISSUE TITLE
slow display on big dashboard

### ISSUE THREAD

**Issue by clems94** [alexanderzobnin/grafana-zabbix#166]
Hello 

i use Grafana 2.6.0 plugin grafana-zabbix 2.5.1 and api zabbix 2.2.8.

I meet slow display on big dashboard it can reach ten minutes.

**Comment by alexanderzobnin** [comment]
Hello! Which time period are you use?

**Comment by clems94** [comment]
7 days

**Comment by alexanderzobnin** [comment]
If you need only last value, try to set _Override relative time_ option in _Time range_ tab. For example, for `1h` (1 hour).

**Comment by clems94** [comment]
Hello @alexanderzobnin 

I now use grafana 2.6 with zabbix 3.0.1.

I steel meet slow display of big dashboard on long period of tim with lot of data from zabbix history table like 7 days.

I installe grafana 3.0 beta with zabbix plugin to test the performance, and i saw great upgrade on cache but not on the frst time i get lot of data.

**Comment by alexanderzobnin** [comment]
Unfortunately, Zabbix can't reduce time series on server side. So if you need to show long periods like 7 days may be better to use trends (set trends period in datasource config).

**Comment by slick666** [comment]
Looking into my own performance I noticed that for each data series in each graph of each page the plugin is going through the authentication process to pull data from the Zabbix server. Is it possible to share sessions and authenticate once per page load? This should affect pages with lots of graphs and/or data series. I'm not sure if this breaks the way grafana is set up but it seems like it would help a lot in some cases

**Comment by alexanderzobnin** [comment]
@slick666 strange. Do you use grafana-zabbix 3.0?
