### ISSUE TITLE
Annotations variable for trigger panel

### ISSUE THREAD

**Issue by roysbike** [alexanderzobnin/grafana-zabbix#169]
Добрый день , Александр. Возможно ли добавить в панель триггеров переменную с annotations. ЧТобы поставлялась переменная , например $host ?

**Comment by alexanderzobnin** [comment]
Здравствуйте. Не совсем понял, где нужно отображать переменную. Можете объяснить на примере?

**Comment by volter** [comment]
Is this about template variables maybe? I didn't get that working today.

**Comment by roysbike** [comment]
Аналогично как с  Templating variables. Чтобы поиск триггеров работал по выбранному хосту или группы.

**Comment by alexanderzobnin** [comment]
Да, это будет в новой версии.
