### ISSUE TITLE
Zabbix list is not displayed

### ISSUE THREAD

**Issue by Diwahars** [alexanderzobnin/grafana-zabbix#17]
Hi,

I have configured zabbix data source in grafana, but i couldn't see the hostgroup, host and item in the drop down list.

![grafana](https://cloud.githubusercontent.com/assets/5858395/7696315/7ad3309c-fe19-11e4-987b-ea65cd0c67e3.png)

**Comment by nucleusv** [comment]
Have you specified user and password in json config? Press F12 (Developer Tools) to analyze problem.

**Comment by Diwahars** [comment]
yea i have specified user name n pwd in json config file.

**Comment by alexanderzobnin** [comment]
Please, show screenshot of datasource configuration menu

![2015-05-19 19-06-49 grafana - home - mozilla firefox](https://cloud.githubusercontent.com/assets/4932851/7707793/4adcea04-fe5a-11e4-8be5-35cb2eba11df.png)

**Comment by alexanderzobnin** [comment]
Are there any errors in the browser's console? (F12 for development tools and then console tab)

**Comment by Diwahars** [comment]
Please find the screenshot of datasource config and the console tab (F12 )
![grafana1](https://cloud.githubusercontent.com/assets/5858395/7708221/eee40e5e-fe71-11e4-8b69-cc4bb7139ae7.png)
![grafana2](https://cloud.githubusercontent.com/assets/5858395/7708222/eeed087e-fe71-11e4-84a0-6a8cd6758250.png)

**Comment by alexanderzobnin** [comment]
Does your web server require authorization?

**Comment by Diwahars** [comment]
no... i use the same URL and username n pwd to get the zabbix data using api...

**Comment by alexanderzobnin** [comment]
Look like your web server (zabbix.isus.emc.com) don't allow cross-domain requests from localhost:3000

**Comment by alexanderzobnin** [comment]
What web server are you using?

**Comment by nucleusv** [comment]
Alex, no problem in zabbix api page. Diwahars, what version of zabbix do you have?

**Comment by Diwahars** [comment]
Zabbix 2.2

**Comment by nucleusv** [comment]
Look at api_jsonrpc.php 

You need to looks like 
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Max-Age: 1000');

/* THIS ALLOW OPTIONS TEST QUERY ADD THIS LINE */
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
  return;
}

**Comment by alexanderzobnin** [comment]
@nucleusv zabbix api blocks cross-origin resource sharing (cross-domain requests)?

**Comment by nucleusv** [comment]
Yes, in old version. In 2.4 it seems OK, download zabbix sources, and check this, if in old versions no such line  
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
return;
}

I think it should be added ti install instructios

**Comment by Diwahars** [comment]
i have a test server with zabbix2.4.. i tried using that to... but still i get error..

![grafanna3](https://cloud.githubusercontent.com/assets/5858395/7709932/02f7ce92-fe7e-11e4-8579-b6f453f11e8e.png)

**Comment by alexanderzobnin** [comment]
Can you test http instead https? May be problem in grafana.

**Comment by Diwahars** [comment]
it works with http for zabbix2.4, but still same prob exists for zabbix 2.2...

**Comment by nucleusv** [comment]
Show screenshot with zabbix 2.2 where grafana do OPTIONS request OR request with errors, have you changed api_jsonrpc.php page ?

**Comment by nucleusv** [comment]
Have added headers output 

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Max-Age: 1000'); 

?

**Comment by Diwahars** [comment]
I have not yet changed api_jsonrpc page..., but changed https to http.. It
worked for zabbix2.4... Likewise I tried for zabbix 2.2... It didn't
work... Will check by changing the api page...

There is no other way to rectify this error... Rather than changing the api
page??

**Comment by nucleusv** [comment]
> There is no other way to rectify this error... Rather than changing the api
page??

Yes, it is problem in this page

**Comment by nucleusv** [comment]
https://support.zabbix.com/browse/ZBXNEXT-1377

**Comment by Diwahars** [comment]
ok...

so i should add these headers is it?
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Max-Age: 1000');

**Comment by alexanderzobnin** [comment]
@nucleusv Is this error in zabbix 2.2 only or all version less than 2.4?

**Comment by nucleusv** [comment]
less than 2.4

**Comment by alexanderzobnin** [comment]
Ok, I describe this in docs.

**Comment by Diwahars** [comment]
@nucleusv  should i add these headers is it?
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Max-Age: 1000');

or this one
/* THIS STRING ALLOWS OPTIONS TEST QUERY - ADD THIS LINE */
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
return;
}
?

**Comment by nucleusv** [comment]
headers and OPTIONS check, replace if there some of these headers

**Comment by alexanderzobnin** [comment]
Added fix instructions.
