### ISSUE TITLE
 Event acknowledgment

### ISSUE THREAD

**Issue by zensqlmonitor** [alexanderzobnin/grafana-zabbix#170]
Hi Alexander,
have you planned to implement triggers acknowledgment in the new version or events are only viewable ?
Thanks

**Comment by alexanderzobnin** [comment]
There is a problem with this case - datasourse works under the same zabbix user for different grafana users. I will think how to sort out with this problem.

**Comment by alexanderzobnin** [comment]
Closed by 7842f468d4ba89f7a444989e3bbb91bf790f3986
