### ISSUE TITLE
Error: XHR error (404 Not Found)

### ISSUE THREAD

**Issue by burhankose** [alexanderzobnin/grafana-zabbix#177]
When adding or updating zabbix datasource, with the latest grafana build and you latest datasource plugin, i get

zabbix plugin failed
Error: Error: XHR error (404 Not Found) loading http://XXX/public/traceur?bust=1459318453264 
Error loading http://XXX/public/traceur
Error loading http://XXX/public/plugins/zabbix/module.js

Also, I can only see the fields "Name" and "Type"

**Comment by alexanderzobnin** [comment]
Hi! I moved codebase to ES6 and now you need to build it first with Grunt. I'll write instructions soon. Or short answer:
``cd grafana-zabbix
npm install
grunt
```
And then copy dist directory to your Grafana plugins dir.

**Comment by burhankose** [comment]
Thanks, worked like a charm
