### ISSUE TITLE
grafana-cli plugins list-remote

### ISSUE THREAD

**Issue by roysbike** [alexanderzobnin/grafana-zabbix#179]
Обновил grafana до 3.0 , пытаюсь поставить grafana-zabbix . Но при выполнении grafana-cli plugins list-remote в списке нет grafana-zabbix

**Comment by alexanderzobnin** [comment]
Да, плагин еще не добавили в репозиторий. Этот способ будет доступен через несколько дней.

**Comment by roysbike** [comment]
Возможно просто перенести в папку plugins?

**Comment by roysbike** [comment]
Перетащил, вроде заработало. Но значения не реальные , в чем может быть проблема?

**Comment by roysbike** [comment]
Разобрался, спасибо! Заново  просто указал datasource
