### ISSUE TITLE
error with zabbix 7 - cannot query problems or triggers

### ISSUE THREAD

**Issue by ksx11** [alexanderzobnin/grafana-zabbix#1790]
**Describe the bug**
This is the error when trying to query problems or triggers
Invalid params. Invalid parameter "/output/2": value must be one of "proxyid", "name", "operating_mode", "description", "allowed_addresses", "address", "port", "tls_connect", "tls_accept", "tls_issuer", "tls_subject", "custom_timeouts", "timeout_zabbix_agent", "timeout_simple_check", "timeout_snmp_agent", "timeout_external_check", "timeout_db_monitor", "timeout_http_agent", "timeout_ssh_agent", "timeout_telnet_agent", "timeout_script", "lastaccess", "version", "compatibility".

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.3.1   | 7.0.0b1  | 4.4.5        |

**Comment by zoltanbedi** [comment]
zabbix 7 is not supported yet.
