### ISSUE TITLE
Pick item based on group and not based on host

### ISSUE THREAD

**Issue by oovoo** [alexanderzobnin/grafana-zabbix#18]
Great job gentlemen
Please let an ability choose a counter which is exists in specific group and automatically populate it on the graphs from all servers that are exists in chosen group.
thank you

**Comment by Diwahars** [comment]
@oovoo in zabbix all items will be mapped based on host and not the hostgroups... Also, the items varies from host to host.
it will not be good, if it automatically populate from the graphs once u select the group. 

Are you familiar with zabbix?

**Comment by alexanderzobnin** [comment]
Something like cpu load for all servers in hostgroup in one panel for example?

**Comment by nucleusv** [comment]
Oovoo, it is something crazy, have you implemented your idea in other grafana plugins? 

Alex I think he wants templated screens, if so we need to work with key_ field and not itemid and hostid

**Comment by alexanderzobnin** [comment]
@oovoo need example for more clarity.

**Comment by oovoo** [comment]
nucleus/Diwahars dear friends I am personally working with Zabbix for last 10 years so I am pretty familiar with internals and capabilities of the product. 

let's me try to rephrase and give u an example what I am asking u to create:

Let's assume we have a group of servers <Important Servers> I want to pick this group and populate list of counters that are shared between all hosts that are exists in the group. 

When I pick specific counter which is shared across all hosts in the group, It will populate all hosts where is the counter exists on the relevant graph automatically.

It is very time series approach when u pick Time Series metric based on reg. expressions like in Graphite/InfluxDB etc. 

if its still not clear I'll try to find some time and provide this capability and contribute into your project. 

Its very simple when u go to Zabbix to latest data pick specific counter in the group and then click to combine values on one graph. 

![capture](https://cloud.githubusercontent.com/assets/2486064/7801040/5297ae88-0327-11e5-811e-785a75a24b05.PNG)

**Comment by oovoo** [comment]
I would do something like that:
1.  hostgroup.get with specific group name
2.  host.get based on groupid (found in step 1)
3.  item.get based on groupid (found in step 1) and creating unique list of counters

when I pick the group and counter its simply populates latest data from chosen counter  across all hosts in the group.

The point here if I add a new host to the group, a new host will appears automatically on the graph. 

Make sense?

**Comment by nucleusv** [comment]
it is already done with templated graphs try to test in https://github.com/alexanderzobnin/grafana-zabbix/tree/feature-templated

you need to go to settings to templated and see how it works

**Comment by alexanderzobnin** [comment]
@oovoo Yes, this feature will be availiable in 2.0.0 release (see [milestone 2.0.0](https://github.com/alexanderzobnin/grafana-zabbix/milestones/grafana-zabbix%202.0.0)). Now I develop templating in [feature-templated](https://github.com/alexanderzobnin/grafana-zabbix/tree/feature-templated) branch.

**Comment by oovoo** [comment]
Great thanks

**Comment by oovoo** [comment]
Can u give me a use case of using templates with zabbix data? You already have clear separation between host / metric / value

**Comment by alexanderzobnin** [comment]
@oovoo see example at http://play.grafana.org/dashboard/db/templated-graphs-nested. In zabbix datasource you may add templated variables and choose them in metric editor. And then you just change templated variable value to view, for example, all items in selected application:
![2015-05-26 22-55-52 grafana - templated values query - mozilla firefox](https://cloud.githubusercontent.com/assets/4932851/7828410/ae153856-043b-11e5-9240-6e5f4873adb7.png)
![2015-05-26 22-57-14 grafana - templated values query - mozilla firefox](https://cloud.githubusercontent.com/assets/4932851/7828412/afb97348-043b-11e5-9587-cfb298fe1a1a.png)

**Comment by oovoo** [comment]
Alexander,
Template is just mechanism to achieve what I am looking for I checked the proposed version and I was unable to generate the graph that will be populating specific item from all hosts from group I pick.
Follow you link this is exact example I am looking for to achieve:
![capture](https://cloud.githubusercontent.com/assets/2486064/8023827/2b563e9a-0d25-11e5-8c75-39730d7f58a1.PNG)

**Comment by oovoo** [comment]
in my case it looks like following:
![capture](https://cloud.githubusercontent.com/assets/2486064/8023879/821abaa6-0d27-11e5-99ec-8a4c5f52928b.PNG)
![capture1](https://cloud.githubusercontent.com/assets/2486064/8023880/8548206a-0d27-11e5-8820-24a0e46aea76.PNG)

**Comment by nucleusv** [comment]
@oovoo you need to select your $item_key in metric editor under graph
and in templating menu you should select host group and all hosts, in templating editor check All option and set it to glob

**Comment by alexanderzobnin** [comment]
@oovoo Wait for about 1 week - this functional will be added soon. I'm working on it.

**Comment by oovoo** [comment]
Great thanks, looking forward

**Comment by alexanderzobnin** [comment]
@oovoo see [develop](https://github.com/alexanderzobnin/grafana-zabbix/tree/develop) branch and try to use this functional.

**Comment by alexanderzobnin** [comment]
Closed by cb7d08c1d6a499f843facb9713e7ca663b0cc721. See [develop](https://github.com/alexanderzobnin/grafana-zabbix/tree/develop) branch.

**Comment by oovoo** [comment]
Alexander super cool feature, works good.

The only thing which is lack now is an ability to search for item which is based on  regex/wildcard pattern.

Use case:

I want to see all items that belongs to group of servers that match to defined filter.

**Comment by alexanderzobnin** [comment]
@oovoo yes, this feature is planned for the future.

**Comment by halcyonone** [comment]
I want to see a hostgroup cpu load item graph, when i create a dashboard, select group, all host cpu load graph view on a  graph, how can i create many graphs and every host have a self graph？thanks.

**Comment by nucleusv** [comment]
@halcyonone 
Look at http://docs.grafana.org/guides/whats-new-in-v2-1/ - Repeating Rows and Panels
https://github.com/alexanderzobnin/grafana-zabbix/wiki/Usage#templates - Templates

**Comment by halcyonone** [comment]
@nucleusv 
I see it, but i dont know how to do it, i not found method, please help me.

**Comment by nucleusv** [comment]
1. create 2 viarbles in new dashboard:
group - Variable values query: *
host - Variable values query: $group.* ( host depends group, you will see only hosts in selected group)

2. create a new graph in group, host fields select $group, $host 
than item(what you need)

try to change selections in variables on top of dashboard

than look here http://play.grafana.org/dashboard/db/new-features-in-v2-1
edit graph http://play.grafana.org/dashboard/db/new-features-in-v2-1?panelId=11&fullscreen&edit

General Tab

Templating options
Repeat Panel

**Comment by alexanderzobnin** [comment]
@halcyonone look at http://play.grafana-zabbix.org/dashboard/db/scripted-dashboard - scripted dashboard example.

**Comment by halcyonone** [comment]
@nucleusv @alexanderzobnin 
thanks very much, i did it, beacause my grafana version is too low, i update it, it works well.
i hava other question, grafana-zabbix can get a zabbix host all graphs without manual create every graph? because my servers run different app and have diff zabbix graphs, thanks.
