### ISSUE TITLE
Grafana slow performance / API username password returns error after period of time

### ISSUE THREAD

**Issue by Bonn93** [alexanderzobnin/grafana-zabbix#181]
Just installed Grafana 3 and the latest zabbix-grafana and created the datasource and made a few test graphs, however performance is very slow. 

* Creating graphs, objects like virtual machines, hypervisors take a long time to show up
* Filtering by hosts takes a long time
* Pulling the data for the graph is extremely slow
* After sometime, I get an red error reporting a problem with the API credentials

Note: some improvement, clicking outside of the box to another area, and back in does help populate selectable options ( ie, Hypervisors ) but the data returned on the graphs is still very slow.  

I understand this is a Beta, so only reporting problems.

**Comment by alexanderzobnin** [comment]
Hi! How big your Zabbix instance? Can you also check api requests timing in browser dev tools? It may be problem with zabbix performance, but we need to chrck it.
Thanks for report - it's important.

**Comment by Bonn93** [comment]
I'd assume rather large. 
Number of hosts (enabled/disabled/templates)	805	760 / 0 / 45
Number of items (enabled/disabled/not supported)	29953	29847 / 0 / 106
Number of triggers (enabled/disabled [problem/ok])	3573	3573 / 0 [261 / 3312]

There are tons of (pending) API requests. See below, that's the start of them, but there are a lot. 

![image](https://cloud.githubusercontent.com/assets/6925963/14306486/e9ac9e6e-fc0a-11e5-8313-e1327d38d74f.png)

**Comment by alexanderzobnin** [comment]
Do you have this problem in previous versions?

**Comment by alexanderzobnin** [comment]
Can you please provide more details aboul these slow requests?

**Comment by Bonn93** [comment]
Can't answer on previous versions, we have another instance but that's production with a much smaller vCenter and setup. This is a brand new test instance we're setting up.

Datasource is https://FQDN/api_jsonrpc.php with direct access and auth on the username/password. Trends are enabled with 7d.

As for the API method, can you expand a little further? It's setup as per the doco. I've actually enabled a few extra tweaks in Apache to attempt help the performance with no luck.

A JSON export with hostnames masked;

{
  "aliasColors": {},
  "bars": false,
  "datasource": "Zabbix",
  "editable": true,
  "error": false,
  "fill": 1,
  "grid": {
    "threshold1": null,
    "threshold1Color": "rgba(216, 200, 27, 0.27)",
    "threshold2": null,
    "threshold2Color": "rgba(234, 112, 112, 0.22)"
  },
  "id": 1,
  "isNew": true,
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "max": true,
    "min": true,
    "rightSide": true,
    "show": true,
    "total": false,
    "values": true
  },
  "lines": true,
  "linewidth": 2,
  "links": [],
  "nullPointMode": "connected",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "span": 12,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "application": {
        "filter": "CPU"
      },
      "functions": [],
      "group": {
        "filter": "Hypervisors"
      },
      "host": {
        "filter": "hypervisor-01"
      },
      "item": {
        "filter": "CPU Utilization (Percentage)"
      },
      "mode": 0,
      "refId": "A",
      "showDisabledItems": false
    },
    {
      "application": {
        "filter": "CPU"
      },
      "functions": [],
      "group": {
        "filter": "Hypervisors"
      },
      "host": {
        "filter": "hypervisor-02"
      },
      "item": {
        "filter": "CPU Utilization (Percentage)"
      },
      "mode": 0,
      "refId": "B",
      "showDisabledItems": false
    },
    {
      "application": {
        "filter": "CPU"
      },
      "functions": [],
      "group": {
        "filter": "Hypervisors"
      },
      "host": {
        "filter": "hypervisor-03"
      },
      "item": {
        "filter": "CPU Utilization (Percentage)"
      },
      "mode": 0,
      "refId": "C",
      "showDisabledItems": false
    },
    {
      "application": {
        "filter": "CPU"
      },
      "functions": [],
      "group": {
        "filter": "Hypervisors"
      },
      "host": {
        "filter": "hypervisor-04"
      },
      "item": {
        "filter": "CPU Utilization (Percentage)"
      },
      "mode": 0,
      "refId": "D",
      "showDisabledItems": false
    },
    {
      "application": {
        "filter": "CPU"
      },
      "functions": [],
      "group": {
        "filter": "Hypervisors"
      },
      "host": {
        "filter": "hypervisor-05"
      },
      "item": {
        "filter": "CPU Utilization (Percentage)"
      },
      "mode": 0,
      "refId": "E",
      "showDisabledItems": false
    },
    {
      "application": {
        "filter": "CPU"
      },
      "functions": [],
      "group": {
        "filter": "Hypervisors"
      },
      "host": {
        "filter": "hypervisor-06"
      },
      "item": {
        "filter": "CPU Utilization (Percentage)"
      },
      "mode": 0,
      "refId": "F",
      "showDisabledItems": false
    },
    {
      "application": {
        "filter": "CPU"
      },
      "functions": [],
      "group": {
        "filter": "Hypervisors"
      },
      "host": {
        "filter": "hypervisor-07"
      },
      "item": {
        "filter": "CPU Utilization (Percentage)"
      },
      "mode": 0,
      "refId": "G",
      "showDisabledItems": false
    },
    {
      "application": {
        "filter": "CPU"
      },
      "functions": [],
      "group": {
        "filter": "Hypervisors"
      },
      "host": {
        "filter": "hypervisor-08"
      },
      "item": {
        "filter": "CPU Utilization (Percentage)"
      },
      "mode": 0,
      "refId": "H",
      "showDisabledItems": false
    }
  ],
  "timeFrom": "72h",
  "timeShift": null,
  "title": "Hypervisor CPU Usage",
  "tooltip": {
    "msResolution": true,
    "shared": true,
    "value_type": "cumulative"
  },
  "type": "graph",
  "xaxis": {
    "show": true
  },
  "yaxes": [
    {
      "format": "percent",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ]
}

**Comment by Bonn93** [comment]
So, the server im testing this on is based in another country and accessed via an MPLS network. After looking at configs for apache, mariadb and the lot, I thought I'd see if it was somehow related to where I'm accessing this from. A remote host and firefox loads the graphs instantly!

So... Does the client somehow request via proxy to the zabbix API? Can't Grafana do these requests on behalf of the client? We could be having issues with TCP connection limits / linux conntrack tables etc.

**Comment by alexanderzobnin** [comment]
Read more about different request modes here: http://docs.grafana-zabbix.org/installation/configuration/#http-settings

**Comment by alexanderzobnin** [comment]
Check also #196 . May be you have the same problem.

**Comment by Bonn93** [comment]
Proxy access method has helped a lot! But still have issues with the query boxes, where they now "pop" the data, instead of harder drop down menus. I still need to click and and out to get data to appear.

I can also report that Web Scenarios are not working or available from the list of items.

**Comment by Bonn93** [comment]
I will push an update to the beta5 version too.

**Comment by alexanderzobnin** [comment]
I fixed Web Scenarios in one of previous updates (see bd25815ba9d26e16be83a058a1f511bca1a4e4d1). Latest version is beta6 (available via grafana-cli).

**Comment by Bonn93** [comment]
Seems happier now on Beta7. Web scenarios are working now too!

Case closed!
