### ISSUE TITLE
Templates feature fails

### ISSUE THREAD

**Issue by szhimin** [alexanderzobnin/grafana-zabbix#182]
When adding a template parameter ‘$ Groups’ success,‘ $ Groups. $ Hosts. * ’failure

**Comment by alexanderzobnin** [comment]
Can you show your template editor? And where are you use this variables?
See also dashboard example with template variables for groups and hosts:
http://play.grafana-zabbix.org/dashboard/db/template-linux-server

**Comment by szhimin** [comment]
- template editor, the var APPs  is none ....
http://imglf.nosdn0.126.net/img/d2MrSVhyNXpnb3lEWWdBK3FCeFgyRGpzbGw4NEZoMjhiV0ZhYTNVWmx6SmVCQjhLekVwajFBPT0.png?imageView&thumbnail=500x0&quality=96&stripmeta=0&type=jpg

**Comment by xiaoping378** [comment]
met the same issue.
>
Groups: *
Hosts: $Groups.*
Apps: $Groups.$Hosts.*

the result of Apps is none .....

**Comment by alexanderzobnin** [comment]
Seems a problem with All value... I'll check it.

**Comment by krisbai** [comment]
![qq 20160407192255](https://cloud.githubusercontent.com/assets/10414888/14349508/2a44a5b6-fcf6-11e5-858f-04883ef5578a.png)

**Comment by alexanderzobnin** [comment]
Does it works without multivalue enabled?

**Comment by xiaoping378** [comment]
Disable Mutil-value/include All option, it works well.

**Comment by krisbai** [comment]
![qq 20160408104537](https://cloud.githubusercontent.com/assets/10414888/14372854/1d1210f0-fd77-11e5-8214-4608358fb819.png)
![qq 20160408104455](https://cloud.githubusercontent.com/assets/10414888/14372858/232e8d74-fd77-11e5-94f6-f9b0d2f9c073.png)

**Comment by krisbai** [comment]
![qq 20160408104537](https://cloud.githubusercontent.com/assets/10414888/14372900/67d7c9cc-fd77-11e5-9e9d-113238f5fdab.png)
![qq 20160408104809](https://cloud.githubusercontent.com/assets/10414888/14372902/6bc88530-fd77-11e5-992a-02dea6a6d9c7.png)

**Comment by krisbai** [comment]
Individually selected hosts template has no value ？

**Comment by alexanderzobnin** [comment]
If you use multi-value, even one value produce a bug. I'll merge fix for templates today and this will work.

**Comment by LaurentCognet** [comment]
Thank You Alexander, we are waiting for this fix !

**Comment by alexanderzobnin** [comment]
Check it out from https://github.com/alexanderzobnin/grafana-zabbix-app

**Comment by andrewmcgilvray** [comment]
I think there is still a problem here. I have a template variable called $nodes and when I use it in the Item field as part of a regex like /$nodes.*outgoing/ it works correctly only when $nodes is a single-value. When it is a multi-value like $nodes = "node1,node2" the Item regex above seems to ignore the ".*outgoing" part and expands to everything that matches /$nodes/

**Comment by alexanderzobnin** [comment]
Ok, I understand. Will check it.

**Comment by alexanderzobnin** [comment]
Yes, it's really bug. Regex `/$nodes.*outgoing/` will expand to `/node1|node2.*outgoing/`, but it must look like `/(node1|node2).*outgoing/`, right?
