### ISSUE TITLE
3.0.0beta2 Cannot add or configure datasource

### ISSUE THREAD

**Issue by Sutrannu** [alexanderzobnin/grafana-zabbix#183]
When adding or trying to reconfigure existing zabbix datasources I get this error in the web interface.
```
Plugin Error
Error: XHR error (404 Not Found) loading https://HOSTNAME.com/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js?bust=1459953190787 Error loading https://HOSTNAME.com/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js
```

```
tail /var/log/grafana/grafana.log
2016/04/06 10:51:25 [I] Listen: http://0.0.0.0:3000/grafana
2016/04/06 10:51:41 [I] Completed 127.0.0.1 User Name "GET /public/traceur HTTP/1.0" 404 Not Found 19 bytes in 601588us
2016/04/06 10:51:48 [I] Completed 127.0.0.1 User Name "GET /public/traceur HTTP/1.0" 404 Not Found 19 bytes in 1363us
2016/04/06 10:51:53 [plugins.go:157 ImportDashboard()] [E] Failed to install dashboard: A dashboard with the same name already exists
2016/04/06 10:51:53 [I] Completed 127.0.0.1 User Name "POST /api/dashboards/import HTTP/1.0" 500 Internal Server Error 41 bytes in 4721us
2016/04/06 10:52:33 [I] Completed 127.0.0.1 User Name "GET /public/traceur HTTP/1.0" 404 Not Found 19 bytes in 178349us
2016/04/06 10:52:43 [plugins.go:157 ImportDashboard()] [E] Failed to install dashboard: A dashboard with the same name already exists
2016/04/06 10:52:43 [I] Completed 127.0.0.1 User Name "POST /api/dashboards/import HTTP/1.0" 500 Internal Server Error 41 bytes in 16777us
2016/04/06 10:53:00 [I] Completed 127.0.0.1 User Name "GET /public/traceur HTTP/1.0" 404 Not Found 19 bytes in 1050us
```

```
grafana-server -v
Version 3.0.0-beta2 (commit: v3.0-beta2)
grep version /var/lib/grafana/plugins/grafana-zabbix/plugin.json
    "version": "3.0.0-beta2",
```

**Comment by juanfernandovillahernandez** [comment]
The system can´t find module.js
![capture](https://cloud.githubusercontent.com/assets/16026041/14330101/89a5cf00-fc04-11e5-8110-08d1fdbc44b3.PNG)

 2016/04/06 14:14:40 [I] Completed 192.168.10.40 admin "GET /public/app/plugins/app/zabbix/module.js HTTP/1.1" 404 Not Found 19 bytes in 2566us

**Comment by alexanderzobnin** [comment]
Please, try to update plugin from special [grafana-zabbix-app repo](https://github.com/alexanderzobnin/grafana-zabbix-app)
http://docs.grafana-zabbix.org/installation/

**Comment by Sutrannu** [comment]
Thank you for the response.
Can you clarify the action to take?
The repo url you provide is not mentioned in the documentation url you provide
The repo you provide does not seem to work with ```grafana-cli --repo```
Are you recommending a git clone of the repo you provide?

**Comment by alexanderzobnin** [comment]
Yes use first way (from special repo)
## From special repo
You can use [grafana-zabbix-app](https://github.com/alexanderzobnin/grafana-zabbix-app) repo,
which contains latest builded version of plugin.

```sh
cd /var/lib/grafana/plugins
git clone https://github.com/alexanderzobnin/grafana-zabbix-app
```

Then restart grafana server.

Using this way you can easy upgrade plugin just running
```sh
cd /var/lib/grafana/plugins/grafana-zabbix-app
git pull
service grafana-server restart
```

**Comment by Sutrannu** [comment]
That does seem to work. Thank you.
I'd like to add that changing permissions _should_ be part of this install/update method. But some configurations might obviate that.

**Comment by alexanderzobnin** [comment]
Breaking news - plugin now available on grafana.net and via grafana-cli.

**Comment by Jobmyname** [comment]
This problem also turned up in my zabbix , system can't find module.js , but it can't be solved after I did as you said, please tell me how should I do ? Thank y[
<img width="641" alt="2016-10-09 10 02 22" src="https://cloud.githubusercontent.com/assets/22725546/19220007/8fd3e27a-8e55-11e6-9331-e0e04f1e07e2.png">
](url)

**Comment by alexanderzobnin** [comment]
@Jobmyname just read about installation options here: http://docs.grafana-zabbix.org/installation/
