### ISSUE TITLE
3.0.0beta2 : No options in Zabbix-Triggers panel

### ISSUE THREAD

**Issue by aldevar** [alexanderzobnin/grafana-zabbix#185]
When trying to set a zabbix-triggers panel, the option page does not load.
![2016-04-07 17_45_54-grafana - ceph cluster](https://cloud.githubusercontent.com/assets/18332562/14357377/c06de25e-fce8-11e5-9bcc-f8954f03643f.png)

In the logs, I can see : 
`admin "GET /public/plugins/zabbix-app/panel-triggers/editor.html HTTP/1.1" 404 Not Found 19 bytes in 3520us`
I don"t understant why it can't load the page. File editor.html is present in the folder

```
# ls -l /var/lib/grafana/plugins/grafana-zabbix/panel-triggers/
total 80
drwxrwxr-x 2 grafana grafana    60  7 avril 14:10 css
-rw-rw-r-- 1 grafana grafana 11369 31 mars  23:05 editor.html
-rw-rw-r-- 1 grafana grafana  8370  4 avril 23:05 editor.js
-rw-rw-r-- 1 grafana grafana 10835  4 avril 23:05 editor.js.map
-rw-rw-r-- 1 grafana grafana  4985 31 mars  23:05 module.html
-rw-rw-r-- 1 grafana grafana 12124  4 avril 23:05 module.js
-rw-rw-r-- 1 grafana grafana 14716  4 avril 23:05 module.js.map
-rw-rw-r-- 1 grafana grafana   239  4 avril 22:29 plugin.json
drwxrwxr-x 2 grafana grafana     6  4 avril 23:05 sass
-rw-rw-r-- 1 grafana grafana   398 31 mars  23:05 trigger.colorpicker.html`
```

Really love the plugin by the way. Great work!

**Comment by alexanderzobnin** [comment]
Thanks! This problem was fixed. Try latest version (beta3). http://docs.grafana-zabbix.org/installation/

**Comment by alexanderzobnin** [comment]
You can try it by grafana-cli plugins install alexanderzobnin-zabbix-app

**Comment by aldevar** [comment]
Did the upgrade using grafana-cli, works very well, thank you!

**Comment by alexanderzobnin** [comment]
Is it fixed for you?

**Comment by aldevar** [comment]
Yes, I close the issue
