### ISSUE TITLE
Not all groups showing in template variable

### ISSUE THREAD

**Issue by mdiorio** [alexanderzobnin/grafana-zabbix#189]
I have around 15 groups in Zabbix, however when I create a group template using just *, no regex filtering, it is only showing 6 groups.  If I try to filter for a group name, it shows None.

Doing a *.* shows all hosts however.

**Comment by alexanderzobnin** [comment]
May be you have empty groups?

**Comment by mdiorio** [comment]
Some are empty.  But the ones I'm expecting to show up aren't.

I have the following Groups in Zabbix that don't show up in Grafana

Web Site	Hosts 8
IT Infrastructure	Hosts 8
SQL Servers	Hosts 1
IIS Servers	Hosts 1
SharePoint	Hosts 2

**Comment by mdiorio** [comment]
It's me and my newbie status to Zabbix.  Sorry.  I added the host groups, but for some reason, they don't automatically get added to the admin user group for permissions.  I'd think at least Admins would automatically be granted access to all host groups created without manually adding them.

**Comment by alexanderzobnin** [comment]
Yes, permissions not will added for new users.

**Comment by caihua1215** [comment]
I meet this issue too，I check the hosts group are in  admin user group.But it still does not exist in grafana groups.I use the admin login grafana.
