### ISSUE TITLE
IT Services Metrics

### ISSUE THREAD

**Issue by nucleusv** [alexanderzobnin/grafana-zabbix#19]
![IT Services](http://www.1cloudroad.com/wp-content/uploads/2013/12/HP-SiteScope-MultiView.jpg)

Many managers want to see services availability like HP and VMware, see image above.
In grafana it will be very easy 

Box with drilldowns, SLA percents on it 
https://www.zabbix.com/documentation/2.4/manual/api/reference/service/getsla
drill down just link you  want, i.e. sublevel services

**Comment by alexanderzobnin** [comment]
You read my mind! ))) I was thinking about this today.

**Comment by nucleusv** [comment]
Just sleeping after early morning, testing will be on weekend. So any roadmap? 'cause a lot of users will just push their wishes :)

**Comment by nucleusv** [comment]
Guys from Badoo want trends very much :)

**Comment by alexanderzobnin** [comment]
And templated dashboards. Working for this now.

**Comment by darrynv** [comment]
Hi! Thank's for much for this awesome plugin. 

Am I missing something with the IT Services option? I can't seem to figure out how to get IT Services available in the Metrics Tab?

**Comment by alexanderzobnin** [comment]
@darrynv Hello! Now IT Services available only at develop branch. Also try to [clear browser cache](https://github.com/alexanderzobnin/grafana-zabbix/wiki/Installation#note-about-browser-cache) after plugin update.

**Comment by darrynv** [comment]
@alexanderzobnin Cheers mate! I'll pull and check it out! ;)
