### ISSUE TITLE
Trigger Panel Info Column URL with Macros not resolving

### ISSUE THREAD

**Issue by mdiorio** [alexanderzobnin/grafana-zabbix#190]
This seems to be a Zabbix issue but wanted to make you aware of it.

So my Triggers for website monitoring are all templated and working properly.  I have a URL on the trigger with a Macro in it and it works fine within Zabbix.  I can view the trigger and open the URL and it processes the macro

http://{HOST.HOST}/content-check/checknow.cfm?mode=all

The Trigger Panel is not getting the macro converted.  I'm getting an URL encoded, un-converted macro

http://%7Bhost.host%7D/content-check/checknow.cfm?mode=all

In the API, there are flags for:
expandComment   flag    Expand macros in the trigger comment.
expandDescription   flag    Expand macros in the name of the trigger.
expandExpression    flag    Expand functions and macros in the trigger expression.

But there is no equivalent for expandURL, so as you can see, macros don't get expanded when requested through the API.

I cross posted in the Zabbix forum as well:
[https://www.zabbix.com/forum/showthread.php?p=181416#post181416](url)

Hope this gets implemented on the Zabbix side quickly.

Thanks.

Max

**Comment by volter** [comment]
Which version of Zabbix is that?

**Comment by mchihi** [comment]
any update please regarding this issue. using Macros instead of host name.
http://{HOST.HOST}/content-check/checknow.cfm?mode=all

**Comment by alexanderzobnin** [comment]
This is Zabbix API limitations.

**Comment by timyllym** [comment]
I have the same problem. I think there won't be any fixes to Zabbix API in near future. I fixed this by utilizing existing code and made a PR #759.

**Comment by alexanderzobnin** [comment]
@timyllym Thank! I'll take a look.
