### ISSUE TITLE
Host name in Zabbix Triggers

### ISSUE THREAD

**Issue by roysbike** [alexanderzobnin/grafana-zabbix#192]
Возможно ли отобразить в триггерах IP адрес хоста, а точнее host name. 
<img width="1680" alt="2016-04-11 9 21 49" src="https://cloud.githubusercontent.com/assets/2388223/14419290/81851868-ffcd-11e5-9c32-f80ee4127a3a.png">

**Comment by roysbike** [comment]
Александр, подскажите пожалуйста, получится ли добавить в Trigger panel  поле "Visible name". 
<img width="643" alt="2016-07-18 23 12 18" src="https://cloud.githubusercontent.com/assets/2388223/16928786/3561ac86-4d3d-11e6-8fb4-a85c377e6c0f.png">

**Comment by alexanderzobnin** [comment]
Да, это не сложно, постараюсь добавить в следующем релизе.
