### ISSUE TITLE
Panel does not show host or port descriptions

### ISSUE THREAD

**Issue by Igor-Lopes** [alexanderzobnin/grafana-zabbix#193]
I've been trying to show the port or host descriptions on the panels and it always returns "NaN". I'm sure that the template is working, since it's possible to see the descriptions on Zabbix. 

I took two screenshots: The red circle is the port description showing on Zabbix, while Grafana only shows NaN for the same host and port.

![zabbix](https://cloud.githubusercontent.com/assets/11265789/14435402/1545ea9e-ffee-11e5-9873-01c6ee1ef403.png)

![grafana](https://cloud.githubusercontent.com/assets/11265789/14435406/1b73ba72-ffee-11e5-8503-c6f8bc2fcbc4.png)

Thank you !

**Comment by alexanderzobnin** [comment]
Does it works on graph panel? Singlestat can't show two metrics, try to use one.

**Comment by Igor-Lopes** [comment]
No it doesn't. Neither with table, singlestat or graph.I was just querying on item on the singlestat. I checked it again.
![error](https://cloud.githubusercontent.com/assets/11265789/14436392/d8ad79b2-fff2-11e5-8ec9-4c69d3f267a3.png)

**Comment by alexanderzobnin** [comment]
Try to use text mode in singlestat panel. Because it's a text metric.

**Comment by Igor-Lopes** [comment]
I don't see where I can set this as text mode. I've selected none for Unit.

**Comment by alexanderzobnin** [comment]
![kazam_screenshot_00016](https://cloud.githubusercontent.com/assets/4932851/14438430/d9cd3580-002e-11e6-8ee6-7abbff5b86b9.png)

**Comment by Igor-Lopes** [comment]
Yes, I changed it to Text metrics and it still shows Nan,

**Comment by alexanderzobnin** [comment]
Can you take screenshot?

**Comment by Igor-Lopes** [comment]
Sorry, I refreshed the panel and it worked just fine. The problem was only the metrics. 
I'm still having other issues though. Can I report them here or do I have to report them separetely? 
Thank you so much for your help, Alexander !

**Comment by alexanderzobnin** [comment]
It's better to open new issue for another problem.
