### ISSUE TITLE
Not possible to query and filter all items by selecting 'All'

### ISSUE THREAD

**Issue by Igor-Lopes** [alexanderzobnin/grafana-zabbix#194]
I'm trying to query all items from an application, but it doesn't work. On previous versions of Grafana there was the 'All' option on the dropdown menu. Now on Grafana 3.0, that you have to type the item name and/or select it, the 'All' option is not available and if I type it, it does not work. Also, I can't find the filter regex input for items, as you can see below:

On a previous version of Grafana( I got this from the usage page):

![grafana-usage](https://cloud.githubusercontent.com/assets/11265789/14467953/0d626886-00b4-11e6-911a-9fc2f7f00483.gif)

On Grafana 3.0:

![grafana-3](https://cloud.githubusercontent.com/assets/11265789/14468447/0a964ca6-00b6-11e6-8ea5-b73995c2f209.png)

**Comment by alexanderzobnin** [comment]
You must use regex `/.*/` instead All value.

**Comment by Igor-Lopes** [comment]
I've created variables and set the regex for them.

The variable item brings incoming traffic on any interface:

![items](https://cloud.githubusercontent.com/assets/11265789/14471356/93520a86-00c4-11e6-850c-e610d5203d43.png)

When I put the $item variable on the item field it doesn't bring all items when selecting all.
![dashboard](https://cloud.githubusercontent.com/assets/11265789/14471373/a4f57070-00c4-11e6-8586-aceedecd3fb1.png)

**Comment by alexanderzobnin** [comment]
Do you have latest plugin version? Looks like issue with multi-value selection in template variables.

**Comment by Igor-Lopes** [comment]
On the plugin overview It says 1.0.0-beta1. How can I check for updates without reinstalling the plugin?

**Comment by alexanderzobnin** [comment]
Try remove it and install using grafana-cli.

**Comment by Igor-Lopes** [comment]
I've updated the plugin to the newest version, but I haven't downloaded it from grafana-cli. The issue persists.

**Template Variables:**
![grafana-1](https://cloud.githubusercontent.com/assets/11265789/14481773/92b4faaa-010c-11e6-9827-222777d4e18c.png)

**Details of the item variable** (With multi-value box selected)
![grafana-2](https://cloud.githubusercontent.com/assets/11265789/14481771/92a8dcd4-010c-11e6-9aad-eccccac61ea7.png)

**Graph works when multi-value box is not selected**
![grafana-3](https://cloud.githubusercontent.com/assets/11265789/14481772/92aa3db8-010c-11e6-8da6-f1b81f38e6be.png)

**Versions of grafana and grafana-zabbix:**

![grafana-4](https://cloud.githubusercontent.com/assets/11265789/14481770/92a5d048-010c-11e6-8a65-10b3509d920f.png)

As far as I know, this is supposed to work, right? A multi-value variable should be seen on the graph.

One improvement I noticed was the one I mentioned on #195. It seems that on the 3.0.0 version, it the graphs are not updating all the time and the front-end is not lagging and glitchy. I will perform a test on the server, that has several hosts and items.

**Comment by alexanderzobnin** [comment]
Current version is beta5. Look at https://grafana.net/plugins/alexanderzobnin-zabbix-app. You can install it by `grafana-cli plugins install alexanderzobnin-zabbix-app`. Remove old version first.

**Comment by Igor-Lopes** [comment]
Sorry, I was looking at the documentation available here, which is outdated. I've installed with graphana-cli and it worked just fine. Thank you very much , Alexander.
