### ISSUE TITLE
Glitchy metric fields 

### ISSUE THREAD

**Issue by Igor-Lopes** [alexanderzobnin/grafana-zabbix#195]
When typing in the fields under the Metrics section, the text field and other components of the page freeze or get really slow, making the page glitchy. This happens because the graph is trying to refresh and query data after the user filled a field and while the user is still typing in the information. I believe grafana would promote a better user experience by disabling the text input, putting drop down selectors back and leaving the graph to update and query data after saving or clicking on a refresh button.

![grafana-glitchy](https://cloud.githubusercontent.com/assets/11265789/14469221/fdc4c774-00b9-11e6-9af4-7065b6abb724.png)

**Comment by alexanderzobnin** [comment]
Ok, I need to check it. Graph must not being updated if item field not filled.

**Comment by Igor-Lopes** [comment]
I got the latest version through grafana-cli (3.0.0-beta7 )and this issue is gone. Thanks !
