### ISSUE TITLE
Exponential lag on auto-updating dashboards

### ISSUE THREAD

**Issue by mcbeenb** [alexanderzobnin/grafana-zabbix#196]
Starting with the 3.x releases of grafana and zabbix-grafana plugin, running zabbix continuously has become impossible for me. Setting up simple charts monitoring a couple interfaces is enough to crash the browser after a few minutes.

The setup is simple. setup a chart watching a couple network interfaces. Set the auto refresh to 1 minute. The first few refreshes are fine, but after 10 minutes things start to slow down. After 15 minutes, the reload time for the page can exceed a full minute. The browser pegs the CPU, and the fan kick in.

I have tested this on safari, chrome, and firefox on both OS X and windows. Same results.

running grafana beta 3, plugin b5, zabbix 3.0.1
[New dashboard-1460490084828.txt](https://github.com/alexanderzobnin/grafana-zabbix/files/215799/New.dashboard-1460490084828.txt)

**Comment by alexanderzobnin** [comment]
I'll try to reproduce this bug, but would be great if you provide some info like performance profiling results from browser.

**Comment by vpuech** [comment]
Hi, i have the same issue, that is preventing me from moving to Grafana 3.

Zabbix 2.4.3
grafana-zabbix beta 3
Grafana 3.0.0-beta1

Here is some profiling, i hope it helps. if not please contact me 

[CPU-20160413T112130.zip](https://github.com/alexanderzobnin/grafana-zabbix/files/217410/CPU-20160413T112130.zip)

**Comment by alexanderzobnin** [comment]
Thanks!

**Comment by alexanderzobnin** [comment]
@vpuech Do you see graph from Zabbix or dashboard can't load?

**Comment by alexanderzobnin** [comment]
I see that v.onload function take most of time. Strange, it's Grafana function. Can you try another datasource (not Zabbix)?

![screenshot from 2016-04-13 19 17 13](https://cloud.githubusercontent.com/assets/4932851/14500879/7965e2a8-01ac-11e6-9a37-81a7052f8c4a.png)
![screenshot from 2016-04-13 19 17 22](https://cloud.githubusercontent.com/assets/4932851/14500853/67ec5214-01ac-11e6-9367-fd0410c61b6b.png)

**Comment by vpuech** [comment]
@alexanderzobnin Yes, everything seams to work just fine except the lag.
i will try to test without zabbix datasource. i'll keep you posted

**Comment by vpuech** [comment]
Added multiple graph from Elasticsearch and no issue so far

![grafana debug lag issue](https://cloud.githubusercontent.com/assets/4442507/14503839/cd0f5a42-017f-11e6-8ef7-4a090c9217b3.png)

**Comment by alexanderzobnin** [comment]
Ok, I see the same problem. Now I trying to collect CPU and memory profiles for detailed analyzing.

**Comment by vpuech** [comment]
It's a great news, if you can reproduce the issue. Thanks you for you're great work. poke me if you need any help.

**Comment by alexanderzobnin** [comment]
Can you get your full Grafana version (with commit hash - it's available at login page)?

**Comment by vpuech** [comment]
@alexanderzobnin : Grafana version: 3.0.0-beta2, commit: v3.0-beta2, build date: 2016-04-04 13:52:41

**Comment by alexanderzobnin** [comment]
Ok, thanks.

**Comment by alexanderzobnin** [comment]
Seems, I found a reason... API response caching - cache grows and insert time also grows. I will try to fix it.

**Comment by vpuech** [comment]
Thank you very much Alexander

**Comment by alexanderzobnin** [comment]
Fix available in version 3.0.0-beta6. I've sent PR to grafana plugin repo so it will be available via grafana-cli soon. Or check out it from https://github.com/alexanderzobnin/grafana-zabbix-app

**Comment by alexanderzobnin** [comment]
Now CPU profiles looks much better :+1: 
![screenshot from 2016-04-13 23 58 00](https://cloud.githubusercontent.com/assets/4932851/14509168/a0aef422-01d3-11e6-8c6a-f48235a8a30a.png)
![screenshot from 2016-04-13 23 57 52](https://cloud.githubusercontent.com/assets/4932851/14509172/a34e0c54-01d3-11e6-8583-e520a7b27b27.png)

**Comment by mcbeenb** [comment]
Awesome! Thanks a ton!
