### ISSUE TITLE
Use Zabbix Groups - and count triggers

### ISSUE THREAD

**Issue by djgarethm** [alexanderzobnin/grafana-zabbix#197]
Hi, 
Feature request for you which would make this app absolutely core for my use - is it possible to address Zabbix groups as well as what's already available? Main reason I'd like this is to be able to count current triggers per group - and display these as a single stat (which means I can then colour the block per office). 

Would this be something you'd consider adding? 

Thanks!

**Comment by golak** [comment]
@djgarethm I release this functionality via IT services

**Comment by zhangcandrew** [comment]
Has there been any leeway in this yet? And @golak could you elaborate on what you mean with being able to do this with IT services? It'd be really helpful for me to count the amount of triggers in a certain state per group also, so anything helps!

**Comment by golak** [comment]
Firstly, configure IT Services with group of triggers in zabbix server:

https://www.zabbix.com/documentation/3.0/manual/it_services

Next, you configure grafana metric as IT Service

**Comment by m-crutchfield** [comment]
i'd really like to see this functionality also - just a simple trigger count per host group, and also total triggers per severity classification would also be really handy.

doing it by IT Services is not the best way to do this - if you have hundreds of hosts per host group and each one has 50 triggers, you're not going to be able to achieve this with IT services.

**Comment by leniserodrigues** [comment]
Hey there Alexander,
Do you think this feature will be available for 3.4.0?
I need to create panels with the number of triggers as a query mode, so I'm thinking of work on this and do a pull-request later...
Is that okay for you?

**Comment by alexanderzobnin** [comment]
Duplicated by #141
