### ISSUE TITLE
left data error！

### ISSUE THREAD

**Issue by krisbai** [alexanderzobnin/grafana-zabbix#198]
![bug](https://cloud.githubusercontent.com/assets/10414888/14540167/41a57814-02b6-11e6-9ca4-58db94b4c072.png)

**Comment by alexanderzobnin** [comment]
Looks like you use Humidity units instead percents. Check Axes tab in panel editor.

**Comment by krisbai** [comment]
sorry . Unit can not be set individually indicators , they seem to use the same standard will be unified .

**Comment by alexanderzobnin** [comment]
Strange. May be it's grafana bug.

**Comment by krisbai** [comment]
Possible, thank you!
