### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by mholttech** [alexanderzobnin/grafana-zabbix#200]
Hi,

I'm seeing an issue with Caching and SingleStat Panels in Grafana 3.0.  I have the same metric showing as a singlestat and as a graph, in this example it's memory usage in bytes.... Zabbix is currently reporting memory usage at 57.87GB, Grafana SingleStat is reporting 87.6 GiB, Grafana Graph is reporting 57.9GiB.  I'm not sure if this is a grafana-zabbix issue or a grafana issue

**Comment by alexanderzobnin** [comment]
Hi! Check value type in singlestat panel. By default it's average instead current.
