### ISSUE TITLE
Add Scale() Function

### ISSUE THREAD

**Issue by mdorenkamp** [alexanderzobnin/grafana-zabbix#201]
It would be nice to have a scale() function, for example scale(-1) that inverts all values.

**Comment by alexanderzobnin** [comment]
This function implemented in Grafana so I removed it.

**Comment by mdorenkamp** [comment]
The scale-feature isnt available at all Graph Types, for example Single-Stat

For example try to graph a ICMP response time with Single-Stat. Zabbix serves the value in seconds (ie 0.018s)

With the old version i was able to scale it by the factor 1000 so i get "18" as result.
With grafana3 im stuck with 0.018

**Comment by alexanderzobnin** [comment]
Yes, it makes sense. Right now you can try to change units for your metric. I think, Singlestat panel can display your **0.018** seconds as **18 ms** if you change time units.

**Comment by mdorenkamp** [comment]
unfortunately this doesnt work :| either it gets displayed as 0.018s or 0.018ms

**Comment by alexanderzobnin** [comment]
Ok, I'll try implement _scale()_ function.

**Comment by cknight-carekinesis** [comment]
I'd like to see this implemented as well. I'd like to be able to convert my ICMP response times to ms. Right now it shows like 0.007s, I'd like to scale it show it shows 7ms.

**Comment by joriws** [comment]
My requirement for scale would be on metric / options / transform to multiply by 86400 to get daily figure. So there is groupBy but I hope there would be math or something to have all values multiplied/divided/power/root by free figure.

**Comment by alexanderzobnin** [comment]
@joriws This commit still is in develop branch. You can build it from sources: http://docs.grafana-zabbix.org/installation/#building-from-sources

**Comment by net592** [comment]
Thank you for @alexanderzobnin I also encountered this problem
