### ISSUE TITLE
Grafana Zabbix Dashboard does not get any data

### ISSUE THREAD

**Issue by Wicaeed** [alexanderzobnin/grafana-zabbix#206]
Greetings,

I'm trying out the plugin on docker using the 3.0 tag for the docker image to get the latest revision. I have added the Zabbix Plugin, as well as configured it successfully, getting back a return `Success
Zabbix API version: 2.4.7` from the plugin.

Once I go to the Zabbix Dashboard though, it never populates with any information.

How can I check that it's polling my Zabbix server correctly and getting data?

Zabbix Server Version: 2.4.7
Browser: Chrome 50.0.2661.86 (64-bit)
OS: Mac OS X 10.11.4

**Comment by alexanderzobnin** [comment]
Check permissions for your zabbix user.

**Comment by Wicaeed** [comment]
Woops, found my problem! By default the Zabbix Server Dashboard uses a hostname of `Zabbix Server`. My Zabbix Server hostname actually uses a different value (a fqdn). I was able to edit the default value to reflect my current systems hostname and things looked great!

**Comment by jaipsharma** [comment]
Could you help locate where did you change the Zabbix Server hostname? I'm having similar issue not able to fetch dashboard data even after data source successfully tested

**Comment by jaipsharma** [comment]
if I go and edit the hostname, I'm able to see hostnames, items, etc but nothing getting ploted on the dashboard

**Comment by zulcar9** [comment]
I'm also have the same problem. Grafana cannot display graph from zabbix. I'm using zabbix v3.0.12 and zabbix plugin 3.7.

![image](https://user-images.githubusercontent.com/33407939/32423590-2997d706-c2e2-11e7-9c54-f5e1a4b526e3.png)

Kindly help.

**Comment by fengerzh** [comment]
I got it! You have to change the host name to "display name", not "host name" on Zabbix server.

**Comment by mainamaish** [comment]
Having same issue with Zabbix 2.4.7 **"You have to change the host name to "display name", not "host name" on Zabbix server."**, where is the done please?
