### ISSUE TITLE
Upgrade or backup  issue

### ISSUE THREAD

**Issue by gouki777** [alexanderzobnin/grafana-zabbix#209]
How to make a smooth upgrade
My grafana version is 2.5
The method is of the original upgrade
1. The home - dashboards - manage dashboard - export
2. The upgrade...3.0
3. Dashboards - > Import
Is there a better way?Upgrade or backup
Is there a wiki ?

**Comment by chancerollins** [comment]
I performed the same upgrade last night with relatively no issues.  The steps below detail what I did to upgrade on Centos 7 from Zabbix 2.4.8 and Grafana 2.5 to Grafana 3.0.1.  These steps were combinations of reading the guides offered by both the Grafana Authors and Alexander Zobnin.  Of course perform a backup first and your mileage my vary.

My steps:
1. Read / understand the breaking changes for grafana - http://grafana.org/download/
2. Follow the guide from Grafana to install the latest version - http://docs.grafana.org/installation/rpm/
3. At this point you should be able to get to grafana however your zabbix dashboards will not work.
4. Follow the install guide for the new Grafana Zabbix App.  I did my install by the cli option - http://docs.grafana-zabbix.org/installation/
5. Perform the config/upgrade steps - http://docs.grafana-zabbix.org/installation/configuration/ and http://docs.grafana-zabbix.org/installation/upgrade/

**Comment by gouki777** [comment]
Thank you very much~
