### ISSUE TITLE
Sort metrics in multiple requests.

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#21]
Metrics in multiple requests returns in random order.

**Comment by nucleusv** [comment]
Needed sort by metric name if you request only one host
And if you request several hosts, sort by hostname and metric name

**Comment by alexanderzobnin** [comment]
Fixed by 8eb9c582f31229efea0e8dc90a9c25cb5b23de89

**Comment by RandomReaper** [comment]
sort by hostname not working, tested in version 3.9.1

**Comment by alexanderzobnin** [comment]
@RandomReaper could you post a screenshot of your query?

**Comment by RandomReaper** [comment]
Here you go:

![grafana-zabbix-host-order](https://user-images.githubusercontent.com/1963170/41759914-344b0b9c-75f1-11e8-99a0-02a6da935060.png)

Host is "/.*/" and order is the order in the hosts have been added to zabbix.

**Comment by alexanderzobnin** [comment]
I think it's due to sorting by name before setAliasByRegex(). I should check.

**Comment by RandomReaper** [comment]
without setting alias, the order is still wrong : 030 is still after 037, still the order in which the machines were added into zabbix.
![screenshot_2018-07-04_09-37-57](https://user-images.githubusercontent.com/1963170/42266389-8a5bd12c-7f76-11e8-978e-186e3a31a6c2.png)

**Comment by alexanderzobnin** [comment]
@RandomReaper Could you please open a new issue for this bug?
