### ISSUE TITLE
Templating Host Issue 

### ISSUE THREAD

**Issue by chancerollins** [alexanderzobnin/grafana-zabbix#210]
I use templating for hosts with two seperate dashboards.  As you can see the filtering at the host level isn't working properly.  Prior to upgrading grafana I would see only the specific host selected.  If I select "HyperV1" from the template I also see data for "HyperV11" and "HyperV12".  I have another dashboard with the same issue which is the second image.  I would assume that the servername is possibly using a substring to match instead of a literal string comparrison.  I will look at the code some as soon as I can and see if I can find the issue.  I am running Zabbix 2.4.8 and Grafana 3.0.1 with zabbix-app version 3.0.0-beta8

![image](https://cloud.githubusercontent.com/assets/17365605/15230686/f223056c-1864-11e6-95c0-c382778c1ce8.png)

![image](https://cloud.githubusercontent.com/assets/17365605/15230785/7f81a544-1865-11e6-98cb-5e27da81304f.png)

**Comment by alexanderzobnin** [comment]
Try to use `/$Server$/` regex instead `$Server`. I'll fix this issue later, thanks for report!

**Comment by chancerollins** [comment]
Thank you for the quick response alexander.  I have updated my dashboards and they look good now.  Is there any documentation on the /'s or additional $ sign?

**Comment by alexanderzobnin** [comment]
When you use $Server variable it converted to regex `/$Server/` for proper multi-selection work.
For example, when you select HyperV1, it will be expanded to `/HyperV1/` regex, and if you select HyperV1 and HyperV2, it will be expanded to `/(HyperV1|HyperV2)/` regex. So `$/` is just a special regex symbol (matches end of input) and it's not related to $Server variable. When you select HyperV1 you need to expand variable to regex `/HyperV1$/`.

**Comment by chancerollins** [comment]
I should have caught it was just a regex expression.  Thanks again!
