### ISSUE TITLE
no data output in graph or pie panel 

### ISSUE THREAD

**Issue by triviman** [alexanderzobnin/grafana-zabbix#211]
hi, good night,
i try to configure grafana-zabbix in my lab environment.
here my settings:
zabbix version: Zabbix 3.0.2
grafana version: grafana-3.0.1-1.x86_64 yum repository.
grafana-zabbix: 3.0.0-beta8
datasource settings: http://i65.tinypic.com/1rspz4.png

i was trying to configure a graph fow example cpu o memory de zabbix server, no data results however if I configure a Singlestat works.
http://i64.tinypic.com/23ljza.png

i activate developer tolls in chrome and firefox and nothing bug appear.

i hope that you can help me.

best regards.

**Comment by triviman** [comment]
this is Embarrassing,I didn't select correctly the date in the last tries.

work correctly with grafana-zabbix: 3.0.0-beta8.

**Comment by alexanderzobnin** [comment]
@triviman No problem!
