### ISSUE TITLE
[Question]  The Grafana can not identify the macro variables of ZABBIX

### ISSUE THREAD

**Issue by zhuleiandy888** [alexanderzobnin/grafana-zabbix#212]
Hi,

When I created Metrics in Graph , the macro variable {$IP}, {$HOSTNAME} defined in ZABBIX can not be identified. see image below：

![image](https://cloud.githubusercontent.com/assets/13164631/15282537/82a5496a-1b76-11e6-9577-ff71ae17e4fc.png)

Grafana version: 3.0.1
Datasource: ZABBIX 2.4.7 - MYSQL Server version: 5.6.30 MySQL Community Server
OS: CentOS Linux release 7.2.1511 (Core) 3.10.0-327.13.1.el7.x86_64
If there is no this function, can be added in the future version?
Kind regards,
andy

**Comment by alexanderzobnin** [comment]
Yes, I'll try to implement it in next version.

**Comment by lauer** [comment]
@alexanderzobnin Do you have a timeframe for when this is going to get implemented?

**Comment by alexanderzobnin** [comment]
@lauer Not sure, I'll try to include it in next version (3.2.x).
