### ISSUE TITLE
Host filtering in Single stat & sumseries

### ISSUE THREAD

**Issue by Bonn93** [alexanderzobnin/grafana-zabbix#213]
Trying to make a dashboard to report usage by project/customer from our zabbix instance. The hosts for some are straight forward such as qa-project-01, qa-project-02 and I can filter those with /qa-project/ and it works fine.

We have one project/customer however the naming scheme of the hosts are a bit all over the place, how can I filter more hosts into the single query? I've tried comma separation, spaces etc but get a N/A result.

**Comment by alexanderzobnin** [comment]
You can use any valid javascript regex. Try to use groups () and | for more complex expressions.

**Comment by Bonn93** [comment]
Ahh yes, no spaces so /HOSTString|HOSTString2/ Did the trick. Might be nice to include a few little examples in the doco for new users coming along?

Case closed!
