### ISSUE TITLE
Performance issue - MySQL query not using correct data type

### ISSUE THREAD

**Issue by dabest1** [alexanderzobnin/grafana-zabbix#214]
We are seeing very high CPU utilization on MySQL server when Grafana queries run. Also it takes half a minute to get charts back for a large number of items. CPU sometimes reaches 100% utilization on all 8 cores. After some investigation, I see that incorrect data types are used in MySQL query coming from Grafana. Based on prior experience, this could be the cause of high CPU utilization.

For example:
groupid is bigint(20) unsigned in rights table, but in the query strings are passed: r.groupid IN ('24','28','36','38').
So far it seems like every single quoted value in the query needs to be left unquoted.

Definition of table:
**************************\* 1. row ***************************
       Table: rights
Create Table: CREATE TABLE `rights` (
  `rightid` bigint(20) unsigned NOT NULL,
  `groupid` bigint(20) unsigned NOT NULL,
  `permission` int(11) NOT NULL DEFAULT '0',
  `id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`rightid`),
  KEY `rights_1` (`groupid`),
  KEY `rights_2` (`id`),
  CONSTRAINT `c_rights_1` FOREIGN KEY (`groupid`) REFERENCES `usrgrp` (`usrgrpid`) ON DELETE CASCADE,
  CONSTRAINT `c_rights_2` FOREIGN KEY (`id`) REFERENCES `groups` (`groupid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8

Sample query:
SELECT  DISTINCT
    i.itemid,
    i.name,
    i.key_,
    i.value_type,
    i.delay,
    i.hostid
FROM
    items i,
    hosts_groups hg,
    items_applications ia,
    hosts h
WHERE
    i.flags IN (0,4) 
    AND EXISTS (
        SELECT
            NULL 
        FROM 
            hosts_groups hgg  
            JOIN rights r 
            ON r.id=hgg.groupid 
            AND r.groupid IN ('24','28','36','38') 
        WHERE
            i.hostid=hgg.hostid 
        GROUP BY
            hgg.hostid 
        HAVING
            MIN(r.permission)>0 
            AND MAX(r.permission)>=2
    ) 
    AND (
        hg.groupid BETWEEN '91' AND '95' 
        OR hg.groupid BETWEEN '101' AND '107' 
        OR hg.groupid IN (
            '1','4','5','8','12','13','14','16','17','19','21','35','37','41','42','46','48','49','53','54','58','59','60','65','66','67','71','72','73','74','87','89','97','98','109','110','111','112','166','184','190'
        )
    ) 
    AND hg.hostid=i.hostid 
    AND (
        ia.applicationid IN (
            '5','347','561','777','817','847','887','907','957','1007','1037','1077','1269','1309','1377','1388','1682','1692','1702','1792','1802','1812','1832','1852','1882','1912','1952','1972','2318','2368','2378','2388','2418','2428','2438','2448','2458','2478','2488','2498','2538','2548','2558','2568','2588','2608','2638','2648','2658','2668','2678','2708','2728','2788','2798','2828','2858','2878','2908','2968','2978','2998','3028','3048','3068','3078','3252','3262','3502','3652','3809','3819','3849','3859','3869','3879','3899','3909','3919','3934','3944','3954','3964','3989','3999','4009','4019','4039','4049','4059','4079','4109','4119','4129','4139','4149','4159','4169','4179','4189','4199','4209','4219','4239','4249','4259','4279','4289','4299','4309','4319','4329','4339','4349','4359','4369','4419','4429','4439','4449','4459','4469','4479','4489','4499','4509','4519','4529','4539','4549','4559','4569','4579','4589','4599','4609','4754','4804','4824','4864','4874','4884','4904','4914','4944','4994','5034','5054','5064','5084','5094','5114','5124','5134','5164','5214','5224','5234','5254','5264','5294','5314','5334','5344','5364','5394','5414','5444','5454','5464','5484','5504','5584','5614','5624','5634','5644','5674','5704','5754','5774','5804','5844','5874','5884','5894','5914','5944','5964','6034','6044','6064','6084','6094','6124','6154','6164','6184','6194','6224','6234','6294','6334','6344','6354','6364','6374','6384','6394','6404','6444','6454','6574','6594','6604','6624','6654','6674','6704','6714','6734','6744','6774','6794','6814','6844','6854','6884','6964','6994','7004','7014','7054','7084','7094','7104','7114','7124','7134','7144','7154','7224','7244','7264','7274','7294','7344','7374','7384','7394','7434','7464','7474','7494','7524','7554','7584','7604','7614','7674','7694','7704','7714','7724','7734','7744','7754','7804','7824','7834','7844','7854','7864','7894','7914','7944','7954','7994','8004','8024','8044','8054','8064','8074','8114','8134','8164','8174','8214','8254','8376','8416','9176','9246','9256','9276','9316','9396','9416','9426','9446','9476','9540','9560','9590','9898','9908','9918','10124','10144','10174','11186','11622','11632','11642','11952','11962','12022','12032','12042','12052','12062','12072','12082','12092','12102','12112','12122','12132','12142','12152','12162','12172','12182','12192','12345','12355','12365','12442','12452','12462','12472','12482','12492','12502','12512','12522','12532','12542','12692','12792','12813','12823','12833','12843','12853','12863','12873','12883','12893','12903','12923','12943','12953','12963','12973','12993','13003','13013','13023','13033','13043','13053','13063','13073','13083','13093','13103','13113','13123','13133','13143','13153','13163','13173','13183','13193','13203','13213','13223','13233','13243','13253','13263','13273','13283','13293','13303','13313','13323','13333','13343','13353','13363','13373','13383','13393','13403','13413','13423','13433','13443','13453','13463','13473','13483','13493','13503','13513','13523','13533','13543','13553','13563','13573','13583','13593','13603','13613','13623','13633','13643','13653','13663','13673','13683','13693','13713','13733','13743','13783','13813','13823','13833','13863','13873','13953','13963','13973','13983','13993','14003','14013','14023','14033','14043','14053','14063','14073','14083','14093','14103','14113','14123','14133','14143','14173','14183','14193','14203','14213','14223','14273','14303','14313','14323','14333','14343','14353','14363','14373','14393','14403','14413','14433','14443','14453','14463','14473','14483','14493','14533','14543','14553','14563','14573','14763','14773','14783','14793','14803','14813','14833','14853','14883','14893','15053','15063','15073','15083','15153','15393','15643','15713','15733','15823','16413','16433','16443','16467','16477','16487','16783','16793','16803','16813','16823','17203','17213','17223','17613','17703','17713','17723','17733','17743','17753','17783','17793','17803','17873','17883','17893','17903','17913','17923','17933','17943','18043','18313','18323','18443','18453','18463','18473','18483','18574','18584','18594','18604','18765','18838','18848','18858','18868','18880','18891','18901','18916','18926','18936','19104','19114','19124','19154','19164','19174','19194','19205','19215','19225','19235','19263','19273','19283','19389','19399','19418','19521','19531','19553','19565','19576','19586','19596','19608','19618','19638','19658','19668','19688','19707','19718','19810','19820','20002','20012','20022','20032','20072','20082','20122','20132','20146','20256','20266','20286','20306','20326','20346','20356','20366','20376','20386','20396','20406','20416','20426','20436','20446','20456','20479','20489','20808','20818','20838','20848','20868','21665','21675','21685','21695','21705','21715','21725','21735','21745','21755','21765','21775','22065','22095','22115','22295','22315','22335','22345','22365','22659','22691','22761','22771','22791','22811','22821','22831','23014','23101','23298','23308','23729','23743','23753','23763','23773','23783','23863','23873','23883','23968','23978','23988','23998','24008','24018','24028','24043','24053','24063','24073','24083','24093','24103','24113','24123','24133','24143','24153','24163','24173','24183','24193','24203','24213','24223','24233','24243','24253','24263','24273','24283','24429','24439','24449','24459','24469','24479','24489','24499','24599','24649','24659','24669','24679','24689','24699','24709','24719','24729','24846','24906','24976','25361','25371','25381','25391','25401','25412','25422','25432','25445','25455','25465','25475','25493','25503','25513','25523','25537','25547','25557','25567','25593','25653','25663','25673','25683','25693','25703','25713','25723','25733','25743','25837','25847','25857','25867','25877','25887','25987','25997','26017','26027','26037','26047','26057','26067','26077','26087','26097','26217','26404','26540','26550','26560','26570','26580','26590','26600','26610','26620','28532','28542','28562','28572','28582','28592','28602','28612','28622','28632','28652','28662','28672','28682','28692','28712','28722','28742','28772','28782','28792','28802','28837','28847','28872','28884','28895','28905','28915','28925','28935','28945','28955','28965','28975','28985','28995','29005','29015','29025','29035','29045','29055','29065','29075','29085','29095','29105','29115','29125','29135','29145','29155','29165','29175','29185','29195','29205','29215','29225','29235','29245','29255','29265','29275','29285','29295','29305','29315','29325','29335','29345','29355','29365','29375','29425','29435','29445','29455','29465','29475','29485','29495','29505','29515','29525','29535','29545','29555','29565','29575','29585','29595','29605','29615','29625','29635','29645','29655','29665','29675','29685','29695','29705','29715','29725','29735','29745','29755','29765','29775','29785','29795','29805','29815','29825','29835','29845','29855','29865','29875','29885','29895','29905','29915','29925','29935','29945','29955','29965','29975','29985','29995','30005','30015','30025','30035','30045','30055','30065','30075','30085','30095','30105','30115','30125','30135','30145','30155','30165','30175','30185','30195','30205','30215','30225','30235','30245','30255'
        ) OR ia.applicationid IN (
            '30265','30275','30285','30295','30305','30315','30325','30335','30345','30355','30365','30375','30385','30395','30405','30415','30425','30435','30445','30455','30465','30475','30485','30495','30505','30515','30659','30679','30729','30749','30769','30799','30829','30839','30849','30869','30879','31115','31135','31255','31265','31275','31305','31315','31345','31406','31428','31438','31602','31612','31622','31632','31682','31692','31702','32117','32149','32160','32182','32203','32214','32395','32416','32446','32466','32496','32506','32526','32536','32566','32626','32686','32696','32706','32716','32726','32736','32766','32776','32786','32796','32806','32838','32849','32926','33030','33040','33150','33554','33584','33594','33624','33644','33654','33728','33739','33835','33910','33943','34071','34115','34148','34656','34891','34913','35308','35486','35496','35506','35534','35554','35564','35574','35584','35594','35604','35614','35624','35634','35644','35654','35664','35674','35684','35694','35704','35714','35724','35734','35744','35754','35764','35774','35784','35794','35804','35814','35824','35834','35844','35854','35864','35874','35884','35894','35904','35914','35924','35934','35944','35954','35964','35974','35984','35994','36004','36014','36024','36034','36044','36054','36064','36074','36084','36094','36104','36114','36124','36134','36144','36154','36164','36174','36184','36194','36204','36214','36224','36234','36244','36254','36264','36274','36284','36294','36304','36314','36324','36334','36344','36354','36364','36374','36384','36394','36404','36414','36424','36434','36444','36454','36464','36474','36484','36494','36504','36514','36524','36534','36544','36554','36564','36574','36584','36594','36604','36614','36624','36634','36644','36659','36669','36679','36689','36699','36709','36787','36797','36807','36817','36827','36837','36847','36860','36870','36880','36890','36900','36910','36920','36930','36990','37000','37011','37021','37031','37044','37054','37064','37224','37245','37255','37276','37286','37296','37364','37374','37384','37394','37404','37414','37430','37440','37450','37460','37470','37480','37493','37507','37517','37527','37537','37548','37562','37572','37582','37592','37602','37612','37622','37632','37642','37652','37662','37672','37682','37692','37702','37712','37722','37732','37743','37753','37763','37773','37783','37793','37803','37813','37823','37833','37843','37853','37863','37873','37883','37898','37908','37918','37938','37948','37968','37978','37988','37998','38008','38019','38030','38040','38050','38060','38070','38080','38090','38100','38110','38120','38130','38140','38150','38160','38170','38180','38190','38201','38212','38223','38234','38245','38256','38267','38278','38289','38300','38310','38320','38330','38340','38350','38360','38370','38380','38811','38821','38831','38841','38851','38861','38871','38881','38891','38901','38911','38921','38931','38941','38951','39626','39636','39646','39656','39666','39676','39686','39696','39706','39716','39726','39746','39756','39766','39776','39786','39796','39807','39817','39828','39838','39848','39858','39868','39878','39888','39898','39908','39918','39928','39938','39949','39959','39969','39979','39989','40000','40010','40020','40030','40040','40051','40061','40071','40082','40092','40102','40112','40122','40132','40143','40153','40164','40174','40184','40194','40205','40215','40225','40235','40245','40256','40266','40277','40287','40297','40307','40317','40327','40337','40348','40358','40368','40378','40388','40398','40408','40418','40428','40866','40876','40886','40896','40906','40916','40926','40936','40946','40956','40967','40978','40988','40998','41008','41018','41029','41040','41050','41060','41071','41082','41093','41103','41113','41123','41133','41143','41153','41163','41173','41183','41343','41363','41393','41403','41413','41483','41493','41513','41533','41543','41563','41573','41603','41613','41931','41941','42130','42140','42150','42160','42170','42180','42210','42300','42320','42410','42430','42450','42470','42480','42500','42665','42675','42685','42695','42725','42765','42775','42835','42925','42951','43998','44008','44588','44598','44814','45160','45170','45180','45797','45807','45817','45827','45837','45847','46798','46808','46818','46828','46838','46848','46858','46872','47554','47564','49363','49373','49539','50433','50446','50456','50466','50476','52945','52955','52976','55428','55438','55448','55458','55468','55478','55619','55629','55854','62474','62484','62494','62505','62515','62525','62536','62546','63387','63397','63418','63428','63438','63448','63458','63468','63479','63489','63499','63509','63519','63529','63539','63549','63560','63633','63654','63664','63674','63684','63694','63704','63714','63724','63734','63774','63784','63794','63804','63815','63825','63878','63888','63898','63909','63920','63930','63940','63950','63960','63970','63980','63990','64028','64219','64953','64964','64986','64996','65006','65016','65026','65036','65046','65056','65066','65076','65086','65096','65146','65156','65167','65177','65187','65197','65207','65217','65227','65247','65257','65267','65278','65288','65298','65308','65318','65328','65371','65382','65393','65404','65421','65431','65441','65451','65461','65471','65481','65491','65501','65512','65522','65550','65561','65571','65581','66071','66081','68012','68023','68034','68045','68056','68067','68144','68155','68166','68177','68188','68199','68210','68221','68232','68442','68453','68464','68475','68486','68497','68508','68519','68530','68541','68552','68563','68574','68585','68596','68607','68618','68761','68820','68831','68842','68853','68864','68973','68997','69014','69025','69036','69051','69062','69073','69084','69106','69117','69128','69139','69150','69161','69172','69183','69194','69205','69216','69227','69253','69264','69275','69286','69297','69308','69319','69330','69341','69352','69363','69374','69385','69396','69407','69418','69429','69440','69451','69462','69473','69484','69496','69508','69520','69537','69548','69559','69570','69581','69592','69603','69614','69625','69636','69647','69658','69669','69680','69691','69702','69713','69724','69735','69746','69757','69768','69779','69790','69801','69812','69823','69834','69845','69856','69867','69878','69889','69900','69911','69922','69933','69944','69955','69966','69977','69988','69999','70010','70021','70032','70043','70054','70065','70076','70087','70098','70109','70120','70131','70142','70153','70164','70175','70186','70197','70208','70219','70230','70241'
        )
    ) 
    AND ia.itemid=i.itemid 
    AND h.hostid=i.hostid 
    AND h.status=0 
    AND i.status=0 
    AND i.value_type IN ('0','3') 
ORDER BY i.name;

**Comment by alexanderzobnin** [comment]
Hi! I just use Zabbix API for making requests. Seems, it's known problem with api performance - history requests generates hard queries for user rights.

**Comment by dabest1** [comment]
Hi Alex,
Thanks for looking at the issue. Could you clarify if you think this is an issue with Grafana or Zabbix plug-in? And this issue is with all fields passed in the sample query provided, they should all be numeric, not string.

**Comment by dabest1** [comment]
Hello Alex,
Could you confirm that all integers are not being converted to strings by grafana-zabbix plugin? That way I can file a bug report with Zabbix.

**Comment by alexanderzobnin** [comment]
Zabbix API uses `string/array` type for IDs in request: https://www.zabbix.com/documentation/2.2/manual/api/reference/host/get. So I think it's a problem on zabbix side. But I can try to convert IDs into numbers and see result.
