### ISSUE TITLE
Allow template variables in setAlias() in order to address feature regression re. the use of query labels with template variables

### ISSUE THREAD

**Issue by 2ion** [alexanderzobnin/grafana-zabbix#217]
I am in the process of migrating a Grafana 2.6 dashboard using grafana-zabbix to 3.x and am noticing a loss of flexibility in the handling of query aliases which is useful in particular when it comes to Zabbix items that have very long names and using template variables to select Zabbix hosts.

While when using a template variable and a query alias in 2.6 the resulting item name was a concatenation of the "$hostname: $itemname" and only $itemname was replaced with the query alias, in Grafana 3 and latest grafana-zabbix when using the function setAlias($alias) to set an alias instead, the resulting item name is just $alias.

This makes the feature less useful when used in conjunction with template variables: Previously, you could go and have i.e. a load average graph for 50 hosts with data series labels reading "$hostname:$itemname" where $itemname was empty because we replaced it by setting an alias. After all, it doesn't make sense to repeat 50 times "$hostname: Processor load (5 min average per core)" in the graph legend - putting that into the graph title does. Because of the new behaviour of the setAlias() function, in Grafana 3, we can't have $hostname in the legend anymore when using the same hostname templating technique.

In order to be able to do the same in Grafana 3 with grafana-zabbix, please expand template variables used as the function argument to setAlias(). As of this moment, the variables are not expanded but printed literally to the UI.

**Comment by andrewmcgilvray** [comment]
This is a good description of why the feature is important .. I also submitted this issue in #205

**Comment by 2ion** [comment]
@andrewmcgilvray Oh dear, I must have had overlooked that. Leaving this open for now; please feel free to close this if its too much of an duplicate. I do not see a way to move my submission to another issue thread.

**Comment by alexanderzobnin** [comment]
@2ion Can you please copy your post into #205?
