### ISSUE TITLE
No option for All in any of the metric fields on v3.0.0-beta8

### ISSUE THREAD

**Issue by trevorx** [alexanderzobnin/grafana-zabbix#218]
Hi, I've upgraded to v3 of the both Grafana(v3.0.4) and your plugin(v3.0.0-beta8) but now I have no option to use 'All' to any of the metric fields.  Therefore if I have a host with many items I need to add each one as a seperate query.  I could do this in your earlier v2.  Is this by design ?

**Comment by pmelse** [comment]
Hi Trevor,

I’m pretty sure this is by design, Have you tried using a regular expression as the query?

Example: /^CPU/
Bad example:  /.*/

**Comment by trevorx** [comment]
I've tried regexp with no luck.  I managed to get a graph of all items within a host using templating but I cant even get regexp to work on that to limit it.

**Comment by alexanderzobnin** [comment]
@trevorx take a look at this [dashboard example](http://play.grafana-zabbix.org/dashboard/db/regex-tutorial?panelId=2&fullscreen&edit). You can use `/.*/` regex for all given items.

**Comment by trevorx** [comment]
That works a treat, thanks.
