### ISSUE TITLE
question: where to download 3.0.0-beta8

### ISSUE THREAD

**Issue by dizzzz** [alexanderzobnin/grafana-zabbix#219]
Hi,

is it possible to (manually) download a ('compiled') release of version 3.0.0-beta8 ?

due to firewall restrictions we can't use the cli, and https://grafana.net/plugins/alexanderzobnin-zabbix-app/installation does not have a direct download link (and: on github the release does not contain a targz on https://github.com/alexanderzobnin/grafana-zabbix/releases )

regards

Dannes

**Comment by 2ion** [comment]
Review the [installation instructions](https://github.com/alexanderzobnin/grafana-zabbix-app), esp. the *From special repo* section.

**Comment by dizzzz** [comment]
ok thnx, I did not see/fully understand it before; thnx for pointing to [the doc](http://docs.grafana-zabbix.org/installation/#from-special-repo)
