### ISSUE TITLE
No value from time to time

### ISSUE THREAD

**Issue by sander1988** [alexanderzobnin/grafana-zabbix#220]
Hi,

We are displaying some Zabbix graphs and values on a Grafana dashboard. From time to time (between once a day and every few minutes) we are getting a 'no value' in the Grafana blocks.

The JSON request (history.get) and response look ok. No network work timeouts or errors in the server logs (I check both the Zabbix Apache 2 logs and the Grafana logs). But we get 2 Javascript errors when the no value appears:

Error: b is undefined
bc/<@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:40:22539
fa/<@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:40:8678
convertHistory@http://mygrafanaserver:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/queryProcessor.service.js?bust=1464773230824:311:37
handleTrends@http://mygrafanaserver:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/queryProcessor.service.js?bust=1464773230824:336:22
queryNumericData/</getHistory<@http://mygrafanaserver:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1464773230824:247:26
h@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:37:234
i/<@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:37:406
vc/this.$get</n.prototype.$eval@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:37:7919
vc/this.$get</n.prototype.$digest@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:37:6423
vc/this.$get</n.prototype.$apply@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:37:8204
f@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:36:15064
q@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:36:16914
Ib/</v.onload@http://mygrafanaserver:3000/public/app/boot.86dbb949.js:36:17457

...paramSerializer)?n.get(a.paramSerializer):a.paramSerialoizer;var y=[];return f(g,...

What can cause this issue?

**Some info on my Grafana environment:**
Browser: Firefox 46.0
OS: Ubuntu 16.04
Grafana version: 3.0.0-beta5
Grafana Zabbix version: v3.0.0-beta7

Regards,
Sander

**Comment by alexanderzobnin** [comment]
Hi! Thanks for report, I'll try to fix it.

**Comment by alexanderzobnin** [comment]
@sander1988 can you give me more info about this issue?

**Comment by sander1988** [comment]
What do you need exactly?

I can probably reproduce the issue and give you similar errors and their stack traces. Will that help?

**Comment by sander1988** [comment]
@alexanderzobnin - Do you need more information on this issue? Please let me know how I can help.

**Comment by alexanderzobnin** [comment]
Is this no value error in all panels on dashboard?

**Comment by sander1988** [comment]
Yes, all panels have this issue but not (always) at same time. This also happens to the graphs (then it shows an  exclamation mark in the corner of the graph).

**Comment by alexanderzobnin** [comment]
Can you update plugin (to latest 3.0.0 version) and report result? May be this is some kind of bug which was fixed.

**Comment by sander1988** [comment]
Ok, I have updated grafana-zabbix to version 3.0.0 . I will keep you updated on the results regarding this issue.
