### ISSUE TITLE
Can't share dashboard with Zabbix Triggers included

### ISSUE THREAD

**Issue by ambernetas** [alexanderzobnin/grafana-zabbix#221]
When I'm  sharing dashboard (local snaphsot), which includes Zabbix Triggers, I'm receiving this error:

`boot.16792590.js:35 TypeError: datasource.replaceTemplateVars is not a function`

 And Zabbix Triggers panel is empty.

grafana - v3.0.4.

**Comment by alexanderzobnin** [comment]
Which plugin version do yo use?

**Comment by alexanderzobnin** [comment]
@ambernetas May be it's due missing datasource. Do you use Zabbix as default datasource?
