### ISSUE TITLE
[BUG] Cannot remove a metric once it's setted

### ISSUE THREAD

**Issue by sebbourgeois** [alexanderzobnin/grafana-zabbix#222]
Hi,

I'm posting this bug report here, and not on the Grafana repo, as it seems (to me) that it is related to the plugin. 
I'm currently using Grafana 3.0.4 on RHEL 5.6, with the Zabbix plugin installed through grafana-cli (current version installed : alexanderzobnin-zabbix-app v3.0.0-beta8)

Here's my issue : when I create a graph, I can add as many metrics as I want, but I can not delete one, whatever the one I want to delete. When I click on the trash icon, nothing happens. 

I think this is related to the plugin, because if I try to do this with another datasource, it works like a charm.

**Comment by alexanderzobnin** [comment]
Ok, I'll check it.

**Comment by alexanderzobnin** [comment]
Hm, I can't reproduce this issue. Can you show me JS logs when it happens?

**Comment by sebbourgeois** [comment]
Sure, will post tomorrow the logs, no access from home

**Comment by alexanderzobnin** [comment]
Ok, thanks.

**Comment by sebbourgeois** [comment]
Zero message, nothing when I click on the trash icon, no error in the zabbix_server.log file.. 

I'm wondering if I don't have an old version of the plugin installed, that may be colliding with the one installed with the grafana-cli. 

```
[zabbix@xxxx grafana]# find . -iname zabbix
./public/app/plugins/datasource/zabbix
```

Should I have this directory ?

**Comment by alexanderzobnin** [comment]
New version of plugin (since 3.x) must be installed in special grafana plugin dir (`/var/lib/grafana/plugins` or `./data/plugins`). So you need to remove old plugin from `./public/app/plugins/datasource/zabbix`.

**Comment by sebbourgeois** [comment]
I'll make the change this weekend, will keep you up to date.

**Comment by sebbourgeois** [comment]
Sorry for the very late reply.
There was indeed a conflict with an old version of the plugin that I was using on Grafana 2.x and the new one installed through grafana-cli

Once cleaned up, it's working like a charm.
