### ISSUE TITLE
Zabbix plugin is not working wth Grafana 3.0.4.

### ISSUE THREAD

**Issue by saeedkm** [alexanderzobnin/grafana-zabbix#223]
Hi,

I have configured zabbix plugin in Grafana 3.0.4 but it is not working.

<img width="1138" alt="screen shot 2016-06-08 at 2 35 09 pm" src="https://cloud.githubusercontent.com/assets/5578038/15888871/505b0310-2d86-11e6-8bc0-fa56aee07586.png">

Thanks,
Saeedkm

**Comment by saeedkm** [comment]
@alexanderzobnin : Can you please help me to fix this

**Comment by alexanderzobnin** [comment]
Hi! You must provide full zabbix api address with api_jsonrpc.php in url field.

**Comment by saeedkm** [comment]
Hi,

Where i can find this? it is in zabbix server or grafana ?

Thanks,
Saeedkm

**Comment by saeedkm** [comment]
Hi Alexander,
I can see only this after configuring zabbix.

<img width="1909" alt="screen shot 2016-06-10 at 5 47 26 am" src="https://cloud.githubusercontent.com/assets/5578038/15950706/dce254a2-2ece-11e6-8163-32badc7e305e.png">

Thanks,
Saeedkm

**Comment by saeedkm** [comment]
How this plugin works. only i can see zabbix server or all the servers from zabbix monitoring.

**Comment by alexanderzobnin** [comment]
Check permissions for zabbix user.

**Comment by saeedkm** [comment]
I have given admin user only.

**Comment by saeedkm** [comment]
<img width="902" alt="screen shot 2016-06-14 at 5 12 33 pm" src="https://cloud.githubusercontent.com/assets/5578038/16041489/4062a342-3253-11e6-8136-1e1738b6b05a.png">

**Comment by alexanderzobnin** [comment]
Do you really need http basic auth?

**Comment by saeedkm** [comment]
Even if 
<img width="1915" alt="screen shot 2016-06-16 at 6 14 38 pm" src="https://cloud.githubusercontent.com/assets/5578038/16117358/53e129b4-33ef-11e6-9852-1a833766b50b.png">
<img width="885" alt="screen shot 2016-06-16 at 6 15 47 pm" src="https://cloud.githubusercontent.com/assets/5578038/16117357/53d8ca4e-33ef-11e6-91e7-18ff22ca3b3b.png">

 i remove that it is not coming.

**Comment by saeedkm** [comment]
It is not coming after removing that also.

**Comment by alexanderzobnin** [comment]
Try to set checkbox `Default`.
