### ISSUE TITLE
No item values and no application list available

### ISSUE THREAD

**Issue by steph-ben** [alexanderzobnin/grafana-zabbix#225]
Hello,

I'm having the following issues when trying to add a new graph:
- No zabbix "Application" are listed
- No zabbix history is shown on the graph

It's working perfectly while using Grafana/zabbix-grafana v2.6.
I'm now trying to use:

```
Zabbix 3.0.1
grafana-3.0.4-1464167696.x86_64
grafana-zabbix-app 3.0.0-beta8
```

The new trigger panel is working though ...
Any help would be greatly appreciated !

Stéphane

---

For more details:
- No zabbix "Application" are listed

I can see my zabbix "Groups", "Hosts" and "Items", but no "Application" are showed.

![image](https://cloud.githubusercontent.com/assets/549513/16122195/81577334-33e6-11e6-9af8-e02b6880bfb9.png)

By looking at the network request, it seems that no host id is passed as argument. 
![image](https://cloud.githubusercontent.com/assets/549513/16122150/573ac330-33e6-11e6-9462-c61904016e68.png)

Note that if no hosts is selected, by removing "hostids: []" parameter, we got all "Application".
- No zabbix history is shown on the graph

While selecting an item, I don't see any data value on the graph.
I don't see any "history" request to Zabbix server as well.

![image](https://cloud.githubusercontent.com/assets/549513/16122470/84971936-33e7-11e6-83cc-c030b5bd8e44.png)

**Comment by steph-ben** [comment]
Ok both issues come from a trailing space at the end of Zabbix Visible name.

The Zabbix Host selected from Grafana schrimped the trailing space. Then hostid cannot be matched.
I got that by looking around https://github.com/alexanderzobnin/grafana-zabbix/blob/master/src/datasource-zabbix/query.controller.js#L137


I guess we can fix this two ways:
* Around this part of the code, `this.target.host.filter` should *have* a trailing space, matching exactly what is entered into the web interface
* Host name trailing space into `self.metric.hostList` should be removed

**Comment by alexanderzobnin** [comment]
Hi, Stéphane! I'll check `templateSrv.replace()` function. Looks like this func trims trailing spaces.
