### ISSUE TITLE
Refresh Intervals

### ISSUE THREAD

**Issue by YoussF** [alexanderzobnin/grafana-zabbix#226]
Hello,

I checked in the documentation, but i can't find what i'm looking for.... how to set the refresh interval ?

Thanks a lot,
Youssef.

**Comment by alexanderzobnin** [comment]
Hi, Youssef! Do you mean dashboard refresh interval?

**Comment by YoussF** [comment]
Yes, exactly

**Comment by alexanderzobnin** [comment]
See it here: http://docs.grafana.org/reference/timerange/

**Comment by YoussF** [comment]
Thanks a lot !, that's exactly what i was looking for :)
