### ISSUE TITLE
change the type of graphs

### ISSUE THREAD

**Issue by DonatoLopes** [alexanderzobnin/grafana-zabbix#227]
Personal am new with the use of grafana with zabbix. I would like to know how to change the way of presentation of graphics, switch to pizza type, gauge ...

**Comment by volter** [comment]
There are plug-ins for Grafana that allow pie charts and I think gauges were recently implemented as an option of singlestats.

**Comment by alexanderzobnin** [comment]
@DonatoLopes I'll try to add more examples for dashboards with different panels and graphs types.
