### ISSUE TITLE
Zabbix Trigger Shows "Unknown"

### ISSUE THREAD

**Issue by Sententiosus** [alexanderzobnin/grafana-zabbix#228]
Hello,

we have a little problem with the zabbix trigger panel.
When a logfile based event is older than 3 or 4 days it became "unknown" in Grafana.

![image](https://cloud.githubusercontent.com/assets/13555355/16224990/db1b4bfe-37a4-11e6-958e-09db82aee89d.png)

Here are the setting from the Zabbix server(v.3.0.3):
![image](https://cloud.githubusercontent.com/assets/13555355/16225014/fa72d210-37a4-11e6-8b24-3c6a880376d3.png)

the panel settings:

![image](https://cloud.githubusercontent.com/assets/13555355/16225059/1f2ae11a-37a5-11e6-835f-85a0803b3e45.png)

and the datasource settings:

![image](https://cloud.githubusercontent.com/assets/13555355/16225091/41aa9b04-37a5-11e6-94c3-5aeccf2729c5.png)

Grafana version: 3.0.0-beta5
Plugin version: 3.0.0-beta8

Thanks

André Lauer

**Comment by alexanderzobnin** [comment]
Hi! Can you show Zabbix API response for trigger panel (Network tab in browser dev tools)?

**Comment by Sententiosus** [comment]
![image](https://cloud.githubusercontent.com/assets/13555355/16256141/2b8725e4-3850-11e6-89be-f970cfa036ec.png)
![image](https://cloud.githubusercontent.com/assets/13555355/16256156/3d0c5190-3850-11e6-8ce1-6d869b18ac43.png)

**Comment by w-HA** [comment]
alexander ,

Hello and congratulations for your job . 
I think we have the same problem
zabbix server 3.2.5
grafana Version 3.1.1
grafana-zabbix app 3.3.0
Linux 2.6.32-696.el6.x86_64 #1 SMP Tue Feb 21 00:53:17 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

after 24 heures the trigger is always fired in dashbord zabbix but unknown in grafana

![known_zabbix](https://cloud.githubusercontent.com/assets/18736461/25696040/ef22b96a-30b5-11e7-8313-e86f62c52645.jpg)
![unknown_grafana](https://cloud.githubusercontent.com/assets/18736461/25696045/f41f92d0-30b5-11e7-82b5-2040f4e7257b.jpg)

For information side zabbix  , if i want to see event for thois trigger in latest data i must select "show items without data"

Thanks for your help
Benoit

**Comment by alexanderzobnin** [comment]
Ok, I will check it again.

**Comment by w-HA** [comment]
Hi,
i find this about lastest data in documentation

Only values that fall within the last 24 hours are displayed by default. This limit has been introduced with the aim of improving initial loading times for large pages of latest data. It is also possible to change this limitation by changing the value of ZBX_HISTORY_PERIOD constant in include/defines.inc.php. 

So i modifie ZBX_HISTORY_PERIOD to 3  days and it works fine
![known_zabbix_ok](https://cloud.githubusercontent.com/assets/18736461/25703968/064d9912-30d8-11e7-8e7e-6bd849a8f7f9.jpg)

Benoit

**Comment by alexanderzobnin** [comment]
Great!

**Comment by alexanderzobnin** [comment]
Closing this since it's not a plugin bug.
