### ISSUE TITLE
Pagination triggers

### ISSUE THREAD

**Issue by neodani** [alexanderzobnin/grafana-zabbix#229]
Hi Alexander,

The triggers plugins its awesome (thanks a lot!, however I would like can show all triggers with a pagination. Could be possible?

Thank you so much!

**Comment by alexanderzobnin** [comment]
Hello! Yes, it's possible (like in Grafana Table panel). I just need more time 😄

**Comment by neodani** [comment]
I look forward to that pagination to be happy :)

Thank you very much!

**Comment by neodani** [comment]
Something new o any date? ;)

Thank you very much!

**Comment by alexanderzobnin** [comment]
@neodani still have no time, sorry.
