### ISSUE TITLE
Zabbix Plugin Module.js fails 

### ISSUE THREAD

**Issue by hubby2004** [alexanderzobnin/grafana-zabbix#231]
This issue is kind of unique since I am running Grafana on a windows server machine. From time to time, the Zabbix plugin fails and show the following message: 
Zabbix plugin failed
Error: Error loading http://grafana.test.local/public/plugins/alexanderzobnin-zabbix-app/\datasource-zabbix/module.js
For some reason, on machines other than mine the URL adds a backslash between -app and datasource which results in this error being displayed and no data. Is there a way to fix this issue?
Thanks!
Mike

**Comment by hubby2004** [comment]
Additional Information: The issue seems to happen with Firefox. When trying with Google Chrome, it works fine.

**Comment by alexanderzobnin** [comment]
How did you installed plugin? Via `grafana-cli`?

**Comment by hubby2004** [comment]
grafana-cli in powershell (running as admin) did not work for me. It says the Zabbix plugin is installed it but it does not show up in grafana nor there is any new folder created. So i copied the app into the plugin folder and restart the grafana server.

**Comment by alexanderzobnin** [comment]
If grafana-cli not works for you, try to use this option: http://docs.grafana-zabbix.org/installation/#from-special-repo. If you use grafana on Windows, clone plugin into `grafana/data/plugins` folder.

**Comment by hubby2004** [comment]
That's what I did to work around the grafana-cli not working. I got the Zabbix-app and placed it in the plugin folder. Then, restart grafana server. It worked well but for firefox in other machines, it gives that problem. Also, the update button doesn't work. It just flashes the screen but stays on.

**Comment by cdtv0833** [comment]
I have the same problem.
I use repo to install.
My grafana version is 3.04

**Comment by alexanderzobnin** [comment]
@cdtv0833 Windows + firefox?
