### ISSUE TITLE
Is zabbix plugin supported for Win7 x64? 

### ISSUE THREAD

**Issue by chaminator** [alexanderzobnin/grafana-zabbix#232]
Hi Alexander!

I've installed zabbix plugin and it's present in the list through command prompt.
![image](https://cloud.githubusercontent.com/assets/10546044/16268662/ef05bf16-3897-11e6-8a21-86d6e0552a9c.png)

After grafana service restart I checked plugins list:
![image](https://cloud.githubusercontent.com/assets/10546044/16268704/083b69fe-3898-11e6-9a74-e519d2ccc6d6.png)

Then I try to look for plugin in the web interface but it's absent:
![image](https://cloud.githubusercontent.com/assets/10546044/16268733/249e5ee4-3898-11e6-9379-6c6384e1ca9f.png)

One detail: I use plugin path= /grafana installation folder/data/plugins

Thanks for your time,
Best regards,
Artyom

**Comment by alexanderzobnin** [comment]
Hi, Artyom! Can you please show grafana startup log?

**Comment by hubby2004** [comment]
I have the same issue Alexander (except in Windows Server 2012 R2). My workaround was to download the zabbix app (https://github.com/alexanderzobnin/grafana-zabbix-app), unzip and place it in the plugins folder, then restart the grafana server.

Alexander, do you want to merge both issue in one if you decide they are similar? My issue is #231

**Comment by alexanderzobnin** [comment]
@hubby2004 Does it works for you (download from grafana-zabbix-app)?

**Comment by chaminator** [comment]
Hi Alexander,

[image: Встроенное изображение 1]

is it ok or do you need smth. else?

thanks,
Kind regards,
Artyom

2016-06-23 9:11 GMT+03:00 Alexander Zobnin <notifications@github.com>:

> Hi, Artyom! Can you please show grafana startup log?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alexanderzobnin/grafana-zabbix/issues/232#issuecomment-227958957>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKDrfKCvxorJBOOW3-I3SwEtkxBEUUdpks5qOiN-gaJpZM4I7yz_>
> .
>



-- 
Best regards
Artyom Cheremisin
--
C наилучшими пожеланиями
Артём Черемисин

**Comment by alexanderzobnin** [comment]
You should clone grafana-zabbix app into data/plugins dir:
```shell
cd c:\grafana-3.0.4\data\plugins
git clone https://github.com/alexanderzobnin/grafana-zabbix-app.git
```
Then restart grafana-server. You should see plugin registration in startup log:
```
2016/06/27 12:16:29 [I] Database: sqlite3
2016/06/27 12:16:29 [I] Migrator: Starting DB migration
2016/06/27 12:16:29 [I] Plugins: Scan starting
2016/06/27 12:16:29 [I] Plugins: Registering plugin Zabbix
2016/06/27 12:16:29 [I] Plugins: Registering plugin Zabbix Triggers
2016/06/27 12:16:29 [I] Plugins: Registering plugin Zabbix
```

**Comment by hubby2004** [comment]
@alexanderzobnin 
What I did was to run the grafana-cli to install Zabbix App (even though there is no folder being imported using that method). Then, copy the zabbix app into the plugin folder and restart grafana server. Now I don't see any issues accessing grafana with zabbix from other browsers.
The only odd behaviour is the update button in the plugin config page. When I click on it, the page flashes but nothing happens. Not sure if that's how the behaviour should be or not.

**Comment by chaminator** [comment]
@alexanderzobnin 

Thanks, Alexander, though seems issue was in disabled plugins folder in custom.ini file.
I enabled it and set as "plugins = /grafana-3.0.4/data/plugins"

Now I see plugin successfully installed, however there is another error:
![image](https://cloud.githubusercontent.com/assets/10546044/16383084/4d5af03e-3c8c-11e6-8c36-5be8818e8815.png)

**Comment by alexanderzobnin** [comment]
Hm... Which browser do you use?

**Comment by chaminator** [comment]
I tried both Chrome and FF.
FF has the same issue, but message is just shorter
![image](https://cloud.githubusercontent.com/assets/10546044/16406948/afd1bf76-3d19-11e6-99e7-c1eeef0d4a1e.png)

**Comment by alexanderzobnin** [comment]
Ok, I'll try to check it on Windows.
