### ISSUE TITLE
SumSeries Function results in an error

### ISSUE THREAD

**Issue by bsmatt** [alexanderzobnin/grafana-zabbix#234]
When trying to run the SumSeries Function on a series of results I get the following error.

Cannot read property '1' of undefined.

This only happens when I use a regular expression that returns multiple values i.e

/server.*.value.count

We are running 3.0.0beta8

**Comment by bsmatt** [comment]
Another note.... it appears this only throws this error when one of the returned metrics doesn't have a value within the time range.

**Comment by alexanderzobnin** [comment]
Yes, I've fixed this issue in e436479a961802c1e4e89fd417cee8f6b5949e26. But it is in develop branch.

**Comment by bsmatt** [comment]
Great thanks!
