### ISSUE TITLE
Wrong Item in Graph Panel selection

### ISSUE THREAD

**Issue by RedHat93** [alexanderzobnin/grafana-zabbix#235]
Hi all,

i'm using Grafana Server v.3.0 with grafana-zabbix plugin v. 3.0.0-beta8

I've got a problem with Item selection in Graph Panel using grafana-zabbix plugin.

When i select my SWITCH (item type SNMPv2) i see in "Item" menu, interface belong to other switch.

Little details Debug:
- grafana-zabbix User used for DataSource has R.O. permission for all of my Host.
- Access mode is set as Proxy

Thanks in advance,

Andrea

**Comment by alexanderzobnin** [comment]
Hi, @RedHat93 ! Can you provide more details? May be screenshot of graph config?

**Comment by RedHat93** [comment]
Hi, @alexanderzobnin,

i attached you what item i see in GRAFANA compared to what item i've got on Zabbix.

GRAFANA:
![image](https://cloud.githubusercontent.com/assets/19625683/16444818/3f9919d0-3de0-11e6-8938-6d6374400ee3.png)

ZABBIX:
Filter Item using "Name" parameter (pattern "Connessione ad INTERNET")

![image](https://cloud.githubusercontent.com/assets/19625683/16444801/255fc474-3de0-11e6-88f1-ad9ed70364cb.png)
