### ISSUE TITLE
Grafana not pulling older data for all items

### ISSUE THREAD

**Issue by mvlahovic** [alexanderzobnin/grafana-zabbix#237]
Here is example picture...

30 days
![image](https://cloud.githubusercontent.com/assets/20338268/16652740/dd5403fc-444c-11e6-8800-f1d5ed9fdd0b.png)

60 days
![image](https://cloud.githubusercontent.com/assets/20338268/16652960/3f2801d6-444e-11e6-8f6d-809f38f1d08c.png)

grafana-server -v
Version 3.0.4 (commit: v3.0.4) (Updated today, so the update didn't break this...)

 zabbix_server --version
zabbix_server (Zabbix) 3.0.3

Grafana plugin installed with
grafana-cli plugins install alexanderzobnin-zabbix-app
version 3.0.0

Anyone have a clue what could have caused this? It was working fine couple of days ago... It was reported by one of our users.

P.S.

We can see all the items and graphs in zabbix just fine.

**Comment by alexanderzobnin** [comment]
Did you updated Zabbix? Seems, you just need to enable `Trends` options in datasource config.

<img width="1280" alt="screen shot 2016-07-07 at 18 48 04" src="https://cloud.githubusercontent.com/assets/4932851/16659611/eca4a116-447b-11e6-83a5-d2f4aaa5363a.png">

**Comment by mvlahovic** [comment]
Here is my datasource configuration...

![image](https://cloud.githubusercontent.com/assets/20338268/16707501/b4ace718-45d0-11e6-9dc1-3f6b7cdcf364.png)

**Comment by joriws** [comment]
Use from 365d so older than 1 year - trends will be used. How long accurate
history you got?

**Comment by mvlahovic** [comment]
@joriws you are right! I use history for the most items for 7 days, When I set the trends to 7d it displays graphs as it should. Thank you!
