### ISSUE TITLE
plugin not appearing in Apps tab in 3.0.4

### ISSUE THREAD

**Issue by brianburton** [alexanderzobnin/grafana-zabbix#239]
I have been trying to install the plugin in grafana 3.0.4 running inside a docker container based on CentOS 7.  I followed the first step:

> grafana-cli plugins install alexanderzobnin-zabbix-app

This indicated that the plugin had been installed.  I restarted the container so the change could take effect.  When I log into grafana and click Plugins->Apps though I don't see any apps installed at all so I can't enable the plugin.

I don't see anything in the /var/log/grafana/grafana.log file that looks promising.  No obvious errors or exceptions.

When I run "grafana-cli plugins ls" I see the plugin is installed:

> installed plugins:
> alexanderzobnin-zabbix-app @ 3.0.0 

I can see the plugin in the plugins directory:

> ls -l /var/lib/grafana/plugins/
> total 4
> drwxr-xr-x 7 root root 4096 Jul 14 20:11 alexanderzobnin-zabbix-app

Is there anything else I should be looking for to diagnose this?

Thanks!

**Comment by alexanderzobnin** [comment]
Hi, @brianburton . Not sure about containers, can you restart grafana inside docker? You should see `msg="Registering plugin" logger=plugins name=Zabbix` in logs:
```
t=2016-07-15T12:58:07+0000 lvl=info msg="Starting Grafana" logger=main version=3.1.0 commit=v3.1.0 compiled=2016-07-12T06:42:28+0000
t=2016-07-15T12:58:07+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2016-07-15T12:58:07+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2016-07-15T12:58:07+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2016-07-15T12:58:07+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2016-07-15T12:58:07+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2016-07-15T12:58:07+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2016-07-15T12:58:07+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2016-07-15T12:58:07+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2016-07-15T12:58:07+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2016-07-15T12:58:07+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2016-07-15T12:58:07+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2016-07-15T12:58:07+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name="Zabbix Triggers"
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name=Zabbix
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name=Clock
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name=Histogram
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name="worldPing CTA"
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name="worldPing Endpoint List"
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name="worldPing Endpoint Nav"
t=2016-07-15T12:58:07+0000 lvl=info msg="Registering plugin" logger=plugins name=worldPing
t=2016-07-15T12:58:07+0000 lvl=info msg="Server Listening" logger=server address=0.0.0.0:3000 protocol=http subUrl=
```

**Comment by satheesh111** [comment]
Hi..Could you share the manual steps equivalent to below commend for zabbix-grafana plugin installation ?
"grafana-cli plugins install alexanderzobnin-zabbix-app"

My installation is failed due to a restriction in network for direct download. Tried copying files from "https://github.com/alexanderzobnin/grafana-zabbix" and placed in '/var/lib/grafana/plugins' and given permissions for grafana user & group , but that didn't help. Any suggestions ?

**Comment by alexanderzobnin** [comment]
@satheesh111 Just read this http://docs.grafana-zabbix.org/installation/#from-special-repo

**Comment by satheesh111** [comment]
@alexanderzobnin thanks very much for your quick response on this. I'll try those steps.

**Comment by brianburton** [comment]
@alexanderzobnin thanks for your help.  I found the problem.

Even though grafana-cli reported that the plugins should live in /var/lib/grafana/plugins the grafana-server process actually wanted them to be located in /usr/share/grafana/data/plugins.  Once I moved the plugin there and restarted the docker container the log reported that the plugin loaded.

**Comment by alexanderzobnin** [comment]
@brianburton  Yes, it's strange default behaviour of grafana-cli. Try to set `$GF_PLUGIN_DIR` env variable to `/var/lib/grafana/plugins/` explicitly.
