### ISSUE TITLE
[Feature Request] Sort and limit the results of a query

### ISSUE THREAD

**Issue by evandro-portugal** [alexanderzobnin/grafana-zabbix#241]
Hi @alexanderzobnin ,

One feature that I have been missing for a long time by now is the ability to limit the number of results from a query by some metric (e.g.:  return TOP 15 devices)

This is very useful when creating a graph that will query all the items in a application that have too many, like for example, all the devices of a host. Things usually get messy in the graph with many lines and legends..... it would be very nice if it was possible to bring just a part of this, like the ones with the most utilization, or the fewer.
This feature would be certainly heavy used by everyone.
If it's not possible to "filter" in the query, then maybe doing this at client-side (sort and limit), before renderizing it.

Keep up the good work! Cheers!

**Comment by alexanderzobnin** [comment]
Hi, @evandro-portugal ,
yes, good idea! I can write function for this like `highestAverage(N)` in Graphite.
