### ISSUE TITLE
Annotations are displayed only when the scaling is set to 24 hours or more

### ISSUE THREAD

**Issue by phroton** [alexanderzobnin/grafana-zabbix#244]
We have traffic triggers on switch ports. This annotations will only be displayed if the scaling is 24h or more. If i zoom in, the annotations will not displayed.

![auswahl_697](https://cloud.githubusercontent.com/assets/11589696/16909444/172ca046-4cd3-11e6-80bd-5ec335745723.png)
![auswahl_698](https://cloud.githubusercontent.com/assets/11589696/16909448/1d245160-4cd3-11e6-8e71-f02d345c93c3.png)

I dont know if it is a bug or a feature :-)

**Comment by alexanderzobnin** [comment]
Yes, this is a bug. I have the same issue. Looks like a bug in triggers filtering.
