### ISSUE TITLE
Dashboard init failed Template variables could not be initialized: b.metricFindQuery is not a function

### ISSUE THREAD

**Issue by SoNiC-PL** [alexanderzobnin/grafana-zabbix#245]
I have installed latest Grafana 3.1 getting me error:

Dashboard init failed
Template variables could not be initialized: b.metricFindQuery is not a function

![image](https://cloud.githubusercontent.com/assets/2166110/16922602/8eaab96c-4d16-11e6-9671-ad93571794e8.png)

I cannot import any of Zabbix related templates, even Zabbix server template is not showing anything other like random generated data.

Zabbix API version:
![image](https://cloud.githubusercontent.com/assets/2166110/16922663/dc5c8384-4d16-11e6-8f8a-ae3019bcb301.png)

**Comment by alexanderzobnin** [comment]
Try to make zabbix datasource default.

**Comment by SoNiC-PL** [comment]
Datasource was created before

![image](https://cloud.githubusercontent.com/assets/2166110/16924147/195c22c4-4d1e-11e6-86f6-c41a02d133fa.png)
![image](https://cloud.githubusercontent.com/assets/2166110/16924151/1e364126-4d1e-11e6-82d5-784878b90686.png)
![image](https://cloud.githubusercontent.com/assets/2166110/16924156/27a3032a-4d1e-11e6-8487-90d808b1e8d6.png)

**Comment by alexanderzobnin** [comment]
Yes, but you need to set `default` checkbox for proper working with imported dashboards. Or just edit panels and set your datasource.
