### ISSUE TITLE
Grafana not showing unit properly from Zabbix

### ISSUE THREAD

**Issue by josephlobianco** [alexanderzobnin/grafana-zabbix#247]
Hi,

Running:
Ubuntu trusty on EC2 instance
Grafana cli version 3.1.0
Zabbix server version 3.0.3a
Zabbix agentd (daemon) version 3.0.3

Issue is that under Grafana, the "unit" values under Axes under Graphs is not displaying the actual chosen value.

For example, when pulling a metric of Total Memory from the Template OS Linux on Zabbix, it shows values in EiB rather than the chosen unit of gigabyte.  Specifically, it shows my instance's memory of 8gb (approximately) as 15 EiB.

I feel like the Zabbix datasource plugin is interfering with this.

**Comment by alexanderzobnin** [comment]
Hi, @josephlobianco ! I faced the same problem and it looks like Zabbix API bug. You can check api response in browser dev tools. Or use scale() function to fix it.

**Comment by josephlobianco** [comment]
Thanks for the swift response, and thanks for building this plug-in!  Unfortunately I am not a dev in any way (linux/network guy here) <- can you point me in the right direction on the fix?  I have zero experience in that domain....

**Comment by nycnewman** [comment]
Looks like Zabbix is returning data as bytes. Setting the Axes value to Gb make Grafana see the returned data in GB and thus displays as EiB (exa-bytes) 100,0000,000Gb => 1Eib. Setting data type to bytes shows correct values. Thus axes setting appears to make Grafana assume that underlying data in units specified in setting.

**Comment by jovanmal** [comment]
Worked for me, units are displayed correctly when I set Unit parameter to bytes or bits (showing GiB and TiB instead of EiB and ZiB).

Thank you very much!
