### ISSUE TITLE
[Bug] TimeSeries not working for table panels with text metric

### ISSUE THREAD

**Issue by evandro-portugal** [alexanderzobnin/grafana-zabbix#250]
Hi,

I've found a problem regarding table panels and text metrics. Whenever I select one of those metrics, the only value that I receive is the last value which is stored at zabbix, whatever is the time interval that is selected, and the time column always show the current system time, not the actual timeseries for that registry.
To reproduce this issue, simply create a table panel with a text metric and keep refreshing, you will see that the time is the current one and probably you will have just one result, the last one.

**Comment by alexanderzobnin** [comment]
Yes, I use item.lastValue() zabbix function for getting text metrics instead history.get().

**Comment by evandro-portugal** [comment]
Hi @alexanderzobnin , I was able to see that, but should this be the default? I mean, in previous version we would get another results here, We used to get all the error messages that were shown in databases errorlogs here in the last 24 hours, but now we can only have the last result, and the timestamp is not showing the actual our the registry came in, it's showing the current system time of grafana-server.

**Comment by evandro-portugal** [comment]
The image below is the result expected (and what I get in older version of the plugin, grafana v2.5)
![antes](https://cloud.githubusercontent.com/assets/16374689/17156795/fecc8742-5361-11e6-8afd-1ab1cf404fea.png)

The image below is the same filters in the new version, grafana v.3.1.0, it shouldn't show only one register here.
![depois](https://cloud.githubusercontent.com/assets/16374689/17156794/fecc62ee-5361-11e6-8b63-5c2f0f2a3008.png)

**Comment by evandro-portugal** [comment]
Hi again @alexanderzobnin , I was searching in the repository and finally see that it was a deliberate change in this here, but I can't see a specific reason for that. Sorry to be disburting you with this, but I was using a older version from the last year for grafana 2.5 and it was a surprise for me...
With this change, how can I have all the data collected for a text metric to be show in a table panel? If you could give me a hint I would be very appreciated! We are migrating for Grafana v3.0, and this is the last issue, but being not be able to see all the error that occured during the day is a big problem!

Thanks

**Comment by alexanderzobnin** [comment]
It's a optimisation for singlestat panel. But seems, I need to revert it.

**Comment by evandro-portugal** [comment]
Hi @alexanderzobnin ,
I've been trying to revert this by myself.
With the code below I was able to get it right when I select just one item, but when using a regex to select multiple items it's just doing wrong, could you help me improve this?

{
          key: 'queryTextData',
          value: function queryTextData(target, groupFilter, hostFilter, appFilter, itemFilter, timeFrom, timeTo, options, self) {
            return self.queryProcessor.build(groupFilter, hostFilter, appFilter, itemFilter, 'text').then(function (items) {
              return self.zabbixCache.getHistory(items, timeFrom, timeTo).then(function(history) {
                  return {
                    target: target.item.name,
                    datapoints: _.map(history, function (p) {
                      var val = p.value;
                      if (target.textFilter) {
                        var text_extract_pattern = new RegExp(templateSrv.replace(target.textFilter, options.scopedVars));
                        //var text_extract_pattern = new RegExp(target.textFilter);
                        var result = text_extract_pattern.exec(val);
                        if (result) {
                          if (target.useCaptureGroups) {
                            val = result[1];
                          } else {
                            val = result[0];
                          }
                        } else {
                          val = null;
                        }
                      }
                      return [val, p.clock * 1000];
                    })
                  };
                });
            });
          }
        }

**Comment by alexanderzobnin** [comment]
@evandro-portugal I'll try to fix it at this weekend.

**Comment by alexanderzobnin** [comment]
It should be like this:
```js
  queryTextData(target, groupFilter, hostFilter, appFilter, itemFilter, timeFrom, timeTo, options, self) {
    return self.queryProcessor
      .build(groupFilter, hostFilter, appFilter, itemFilter, 'text')
      .then(items => {
        if (items.length) {
          return self.zabbixAPI.getHistory(items, timeFrom, timeTo)
            .then(history => {
              return self.queryProcessor.convertHistory(history, items, false, (point) => {
                var extractedValue;
                if (target.textFilter) {
                  var text_extract_pattern = new RegExp(self.replaceTemplateVars(target.textFilter, options.scopedVars));
                  extractedValue = text_extract_pattern.exec(point.value);
                  if (extractedValue) {
                    if (target.useCaptureGroups) {
                      extractedValue = extractedValue[1];
                    } else {
                      extractedValue = extractedValue[0];
                    }
                  }
                } else {
                  extractedValue = point.value;
                }
                return [
                  extractedValue,
                  point.clock * 1000
                ];
              });
            });
        } else {
          return self.q.when([]);
        }
      });
  }
```

**Comment by evandro-portugal** [comment]
@alexanderzobnin Thanks for having a look at it! Tried to use all the code that is in the develop branch but it seems that something is missing.
I'm getting this error, not a clarifying one (I've wiped my folder and used only the files in develop branch)

falcon plugin failed
Error: Error loading http://192.168.1.218:3000/public/traceur Error loading http://192.168.1.218:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js

**Comment by alexanderzobnin** [comment]
@evandro-portugal you need to build it first http://docs.grafana-zabbix.org/installation/#building-from-sources

**Comment by evandro-portugal** [comment]
Got it to work, thanks again!
