### ISSUE TITLE
[bug] trigger panel not displayed correctly in IE11

### ISSUE THREAD

**Issue by technimad** [alexanderzobnin/grafana-zabbix#252]
Browser IE11.0.9600
Grafana 3.1
grafana-zabbix 3.0.0-final

When a zabbix trigger panel is placed on a dashboard, and viewd using this version of IE, the triggerlist is unreadable as the background-color for the td's in the issue column is not set.
![issue background](https://cloud.githubusercontent.com/assets/15761/17103553/1b6d711a-527f-11e6-8ae4-f8135eaa9fa2.PNG)

The developer tools show for this td:
![background-color-error](https://cloud.githubusercontent.com/assets/15761/17103496/d7daed06-527e-11e6-89b4-73c8d7b9d987.PNG)

**Comment by alexanderzobnin** [comment]
Can you check also Table Panel?

**Comment by technimad** [comment]
I've created a table panel, with datasource zabbix, displaing SSH performance statistics. I've added coloring to cell's, making all my performance values red. This looks ok in IE11
![table](https://cloud.githubusercontent.com/assets/15761/17243195/924642ea-557b-11e6-86a7-2d997250945a.PNG)

**Comment by alexanderzobnin** [comment]
Hm, looks like mistake in `{{trigger.color}` (no last bracket).

**Comment by alexanderzobnin** [comment]
Is it still actual?

**Comment by technimad** [comment]
I can't verify. I don't have access to a grafana installation anymore.

**Comment by alexanderzobnin** [comment]
Ok, I'm closing this.
