### ISSUE TITLE
Upgraded 2.6 to 3.1 Zabbix not showing as a datasource

### ISSUE THREAD

**Issue by jon2100** [alexanderzobnin/grafana-zabbix#253]
After the upgrade the zabbix data source was showing there was an error loading plugin.
the logs had this error 
"Failed to load plugin json file: [/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/plugin.json Plugin with same id already exists],  err: %!v(MISSING)" and a few others along this line.
I was able to resolve so at least now I can view the existing data source but Zabbix is not list as a source, and it does not show on creating new. 
Update was done by Yum, I also did the manual update and that did not change anything.

**Comment by alexanderzobnin** [comment]
Do you removed old plugin? Because it uses different path (located in `grafana/public/app/plugins/...`, but new in `/var/lib/grafana/plugins/` or `./data/plugins/`).

**Comment by jon2100** [comment]
Actually it was my fault I had a type-o :( have not had a chance to get back to the page update.  thanks for the follow up.
