### ISSUE TITLE
Entities starting with a period don't work in Templating

### ISSUE THREAD

**Issue by volter** [alexanderzobnin/grafana-zabbix#254]
I have a couple of "logical" host groups that I prefix with a period.

Apparently, ".Gearman.*" and ".Gearman" will not return hosts from the ".Gearman" group.

**Comment by alexanderzobnin** [comment]
Hi, @volter I use a dot like a query part separator. But this approach may cause a bugs like is in your case. So I need to choose another separator. I think about symbols which not allowed to use in zabbix host names and keys.

**Comment by volter** [comment]
Meh, Github ate my backslash in that second quote. Is escaping the character not an option to solve this? I never thought about it: Are you using the technical or the display name there? If you allow for the latter, a magic character won't do, I think. If it's the technical name: "Alphanumerics, spaces, dots, dashes and underscores are allowed."

While we are speaking about it: I sometimes find it difficult to remember the order of the 4 entities. Maybe some kind of mouse-over help would be great.

Eventually, the same problem exists on all 4 levels.
