### ISSUE TITLE
Automatic(auto populate graph) values from a group

### ISSUE THREAD

**Issue by edgdelgado** [alexanderzobnin/grafana-zabbix#257]
Hi.

On an older version of grafana/zabbix plugin I could select a host-group and a item that was common on this group and the graph auto-populate with this information from every host in the group.

This can no longer be done? Am I missing something?

Ty
Edgar

**Comment by alexanderzobnin** [comment]
It's still possible of course. Just look at http://docs.grafana-zabbix.org/guides/gettingstarted/
