### ISSUE TITLE
template is not working

### ISSUE THREAD

**Issue by travka** [alexanderzobnin/grafana-zabbix#258]
Zabbix API version: 3.0.3

http://prntscr.com/c5l84u

all values are correct.
what can be a problem ?

**Comment by alexanderzobnin** [comment]
Do you set zabbix datasource as default? See also #206.

**Comment by travka** [comment]
http://prntscr.com/c5njhx
i've checked also all stuff on zabbix, and seems it's ok.  So for me is strange.

**Comment by alexanderzobnin** [comment]
May be you have another Zabbix server name?

**Comment by travka** [comment]
i think that too before.
"Zabbix server" is same server name

**Comment by alexanderzobnin** [comment]
Can you create dashboard with same metrics by hand?

**Comment by travka** [comment]
Same result, tried to import alot of different metrics, they're empty. maybe i can check somewhere debug log or something like this ?

**Comment by alexanderzobnin** [comment]
You can check api requests in browser developer tools (network tab).
