### ISSUE TITLE
Metrics are not added to graph

### ISSUE THREAD

**Issue by aingvarf** [alexanderzobnin/grafana-zabbix#26]
After selecting metric in query it is not added to graph. I don't see any requests to get items history data. After selecting another item in query also no request are initiated.
I use Grafana 2.0.2-1.
In web console there is only one warning: "The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.". It is related to https://github.com/grafana/grafana/issues/1932

I made one change in plugin to make retrieving data (host groups, hosts, applications, items) from zabbix (2.2.1) working - changed "search" method in api requests to "filter", otherwise I always got empty results.

**Comment by aingvarf** [comment]
Got it! It is appeared that ALL filters - host group, host and application have to be selected. I didn't select application previously. I think that application should not be mandatory here because item is unique for host.

**Comment by himanhimao** [comment]
I was so
