### ISSUE TITLE
Multi-Selector Dashboards Break After Upgrade

### ISSUE THREAD

**Issue by Kporter6053** [alexanderzobnin/grafana-zabbix#260]
After upgrading to Zabbix 3.0.0 most of my Multi-Selector dashboards broke.  
Also, after needing to switch the $netif item to a regex, I get a separate window for each interface (say eth0 and eth1) --  with each window having the same data --  rather than it all showing in one window.  

The Multi-Selector functionality still works as it finds the proper hosts and selects the proper hosts – but the data is empty.  -- until I had went in and changed the string

It appears that I’ve had to change the format of some fields in the Metrics panel as follows.. 

So --    the bottom line appears to be --    

Where previously I could get away with 

$pfservice

I had to go to 

/$pfservice/     (to use the Templating Variable in the “Application” field)  

Yes, I changed some of the application fields to the following:  (using two variables) 

/$pfgroup \/ $pfservice/ 

But I found out later that really wasn’t necessary.    

Thus, I don’t know what changed.   

Also, in the Network Interface field --  some of those fields I had to change from  
$netif

To
/$netif/  

However, by using /$netif/   -- rather than the old way of --  $netif – it now gives me a window for EVERY interface – with the same data in each window --  when previously, all interfaces were depicted in one graph.

**Comment by alexanderzobnin** [comment]
@Kporter6053 can you confirm this for Grafana-Zabbix 3.1.1?

**Comment by Kporter6053** [comment]
Alex,

Let me look into this and let you know.    I may need a week to get back to
you.

Thanks.
