### ISSUE TITLE
Trend missing in Zabbix 3.0 Grafana 3.1.1 and Zabbix Plugin 3.0.0

### ISSUE THREAD

**Issue by sperr0w** [alexanderzobnin/grafana-zabbix#264]
Hello!

We have Zabbix 2.2 with grafana 2.6 and zabbix plugin. After patch, we successfully get trends for all metrics.
Now we upgrade Zabbix to version 3.0.3 and Grafana to version 3.1.1 and Zabbix grafana plugin to version 3.0.0
After upgrade, we cant get trend for metrics. 
We can only get statistic for 7 days (7d declared in Zabbix datasource). If I try to get statistic for 30 days, all graphs become empty at the same moment.

Could you please give us solution of how to solve this problem?

Sergey.

**Comment by alexanderzobnin** [comment]
Hello! Can you look at network requests at Network tab in dev tools? Does grafana send proper `trend.get` request? And what does zabbix return?

**Comment by sperr0w** [comment]
what exactly dev tool are you mean?

**Comment by alexanderzobnin** [comment]
Browser's developer tools.

**Comment by sperr0w** [comment]
For test metric:

When I ask to get date for last 15 minutes, it return this:

{"jsonrpc":"2.0","method":"history.get","params":{"output":"extend","history":"0","itemids":["1098308"],"sortfield":"clock","sortorder":"ASC","time_from":1472123908,"time_till":1472124808},"id":1,"auth":"6c2c72e7b534a8e7ff9b96153ea5e6de"}

I see graph

When I ask to get data for last 30 days, it return this:

{"jsonrpc":"2.0","method":"trend.get","params":{"output":"extend","trend":"0","itemids":["1098308"],"sortfield":"clock","sortorder":"ASC","time_from":1469532803,"time_till":1472124803},"id":1,"auth":"6c2c72e7b534a8e7ff9b96153ea5e6de"}

And I dont see anything.

It looks like plugin use trend.get ( right method).

**Comment by sperr0w** [comment]
for the second POST request it returns responce with empty array.

**Comment by alexanderzobnin** [comment]
Can you show response for trend.get?

**Comment by alexanderzobnin** [comment]
Ok

**Comment by sperr0w** [comment]
Request:

{jsonrpc: "2.0", method: "trend.get",…}
auth:"9e81dbe53e538f63829e143fbb6c70a8"
id:1
jsonrpc:"2.0"
method:"trend.get"
params:{output: "extend", trend: "0", itemids: ["73899"], sortfield: "clock", sortorder: "ASC",…}
itemids:["73899"]
0:"73899"
output:"extend"
sortfield:"clock"
sortorder:"ASC"
time_from:1469533497
time_till:1472125497
trend:"0"

Response:

{"jsonrpc":"2.0","result":[],"id":1}

**Comment by sperr0w** [comment]
also in console output I see that getTrend function it is actially use 
getTrend_ZBXNEXT1193(items, time_from, time_till)
May be I still need to use ZBXNEXT1193 patch with new zabbix?

**Comment by alexanderzobnin** [comment]
No, this method works right with zabbix 3.0 also.

**Comment by alexanderzobnin** [comment]
Did this problem appeared after update from zabbix 2.x?

**Comment by sperr0w** [comment]
I dont know exactly.
In the start of this activity it was Zabbix 2.2 with ZBXNEXT1193 applied and Grafana 2.6 and trends worked perfectly.
We start from upgrading zabbix from 2.2 to 3.0.3. After upgrade, zabbix-grafana plugin was not bee able to show trends. 
After we upgrade grafana to 3.1.1 and we find that we have also old version of zabbix plugin, so, we upgrade plugin also.

Finally we get Zabbix 3.0.3 Grafana 3.1.1 and Zabbix Plugin 3.0.0 and we still not able to see trends graphs.

**Comment by alexanderzobnin** [comment]
Strange, I use zabbix 3.0.4 and have no problems with `getTrend_ZBXNEXT1193()` method. Try to change it to `getTrend_30()` in zabbixAPI.service.js:
```js
this.getTrend = this.getTrend_ZBXNEXT1193;
this.getTrend = this. getTrend_30;
```

**Comment by sperr0w** [comment]
After this update:
//this.getTrend = this.getTrend_ZBXNEXT1193;
this.getTrend = this.getTrend_30;

I get error:

Zabix plugin failed
ReferenceError: getTrend_30 is not defined

**Comment by alexanderzobnin** [comment]
@sperr0w looks like a problem on Zabbix side. Any ideas? Can you see trends in Zabbix (on graph, when you choose time interval more then few days, 7 days for example)? Any errors in zabbix logs?

**Comment by sperr0w** [comment]
Today I will try to play in my zabbix with zabbix API  and trend.get method and will check, if it work properly or not on my zabbix. I will inform you.

**Comment by sperr0w** [comment]
I find error on Zabbix side: in CTrend.php of Zabbix API we have:

					$res = DBselect(
						'SELECT '.implode(',', $sql_fields).
						' FROM '.$sql_from.' AS t'.
						' WHERE '.implode(' AND ', $sql_where),
						$sql_limit
					);

but for ORacle DB this query is noc correct, because of "AS". Correct will be this:

					$res = DBselect(
						'SELECT '.implode(',', $sql_fields).
						' FROM '.$sql_from.' t'.
						' WHERE '.implode(' AND ', $sql_where),
						$sql_limit
					);

After I fix this issue, in Grafana in trend.get Response I can get  metric value array, But I still cant see the graph.

One important moment:

In response ARRAY I can see only itemid and clock for each metric value, but there is no value_min, value_max or value_avg in this array.

Lets continue?

**Comment by alexanderzobnin** [comment]
@sperr0w yes, looks interesting. Did you had Oracle DB before upgrading? Can you build graph in Zabbix like this:
![chart2 php](https://cloud.githubusercontent.com/assets/4932851/18211210/3715381e-7145-11e6-8f0f-2defcb59663b.png)
Look at right bottom corner (_Data from trends_)

**Comment by alexanderzobnin** [comment]
@sperr0w is it still actual?

**Comment by xiaoxue999** [comment]
me too. 

 Enable Trends button from source menu,but does not work,no data can be display more than  7day ago.
if disable Thends button,then chose the 7days ago ,the graph was always refreshing......

**Comment by alexanderzobnin** [comment]
@xiaoxue999 can you check api call from browser developer tools? Does Grafana call `history.get` instead `trend.get` zabbix api function?

**Comment by sperr0w** [comment]
Hello, Александр!

First of all, I can commite that xabbix API have SQL query error for trend.get method. After I fix it, Everythind is ok for me. I didnt start RFC on zabbix site yet because a lot of work. But I hope to find some time.

**Comment by sperr0w** [comment]
Sorry tor late responce

**Comment by xiaoxue999** [comment]
@sperr0w  your problom is the same as me ,  I used zabbix 3.1.2 with Oracle DB on 11.2.0.4 version, or maybe it's a zabbixAPI bug or zabbix can not support with Oracle DB very nice.

**Comment by xiaoxue999** [comment]
@alexanderzobnin yes,  i checked in  my browser DEV tools, the jsonrpc has responsed a empty array....

**Comment by sperr0w** [comment]
in CTrend.php:

    $res = DBselect(
                    'SELECT '.implode(',', $sql_fields).
                    ' FROM '.$sql_from.' AS t'.
                    ' WHERE '.implode(' AND ', $sql_where),
                    $sql_limit
                );

change to:

                $res = DBselect(
                    'SELECT '.implode(',', $sql_fields).
                    ' FROM '.$sql_from.' t'.
                    ' WHERE '.implode(' AND ', $sql_where),
                    $sql_limit
                );

it will fix this problem.

**Comment by xiaoxue999** [comment]
@sperr0w great! it works,thank you very so much. would you please feedback this problem to zabbix official?

**Comment by alexanderzobnin** [comment]
@sperr0w hm, looks really like a bug in zabbix api. Thanks for report! Did you apply any patches to zabbix or this is original code? Which version did you use?

**Comment by neogan74** [comment]
Related  Zabbix bug https://support.zabbix.com/browse/ZBX-13325
