### ISSUE TITLE
Item with short update interval doesn't get reflected fast enough on Grafana

### ISSUE THREAD

**Issue by mrdanielmor** [alexanderzobnin/grafana-zabbix#265]
Hello all, how are you?

First of all, I want to say big thanks for your wonderful piece of work. It's really appreciated! ;-)

Secondly, I have a "little" issue, that unfortunately, I can found to answer via the various web data-sources:

I have an item that being updates each 3 seconds on the Zabbix side. On Grafana, the update result get's only after two or more minutes. Configuring lower auto-refresh on the dashboard doesn't help. It's seems like the API call is not happening as fast as I need. Any clue? detail? idea? 

Any lead will be really appreciated!

Big thanks again - for your time, efforts and good will!

+Daniel.

**Comment by alexanderzobnin** [comment]
Hi, @mrdanielmor ! Thanks! I think it may caused by time mismatch in browser and zabbix server. Check also time range in Grafana. In latest version default looks like this: `now-1m`. It mean _to one minute before_.

**Comment by mrdanielmor** [comment]
Hi @alexanderzobnin, how are you?
* Big thanks for your response and even bigger thanks for the effort! ;-)
* Please note that the Zabbix and the Grafana services installed on the same server. The "Time picker" definitions on the dashboard configured as follows:
** Auto-refresh = 1s,5s,30s,1m,5m,15m,30m,1h,3h,2h,1d
** Now delay now- = 0m (that if I'm understanding right, should say that "now" is really "now" ;-))
* Any other idea? can you please elaborate on the "mismatch in browser and zabbix server" part? I've didn't get it ;-)

Good day!

+Daniel.

**Comment by alexanderzobnin** [comment]
Ok, if time is synced, may be problem on Zabbix side? Do you know, does Zabbix cache data before write it to database? I'm not sure - Zabbix has history cache, but I don't know how it uses this cache.

**Comment by mrdanielmor** [comment]
Hi @alexanderzobnin, thanks again.

I think that I've succeeded to narrow down the issue! I'm facing this issue using Singlestat, so, I've tried to use Graph, and while using Graph - the results are updated on real-time! So - it's something that's relevant to Singlestat. Is there any lead? something that could be checked, etc.?

BTW, just in-order to get aligned - Zabbix do cache data, BUT, I've done a database check, using the following command (when item 23816 is the relevant item):

```
use zabbix;
select * from history_uint where itemid="23816" ORDER BY clock DESC LIMIT 1;
```

And saw that the DB record is updated as expected.

Will appreciate your response.

+Daniel.

**Comment by mrdanielmor** [comment]
Hi, it's me again!

I found the issue. For some reason - which I'm still trying to understand, although I've changed the Singlestat to current value, apparently, this configuration didn't came up and because of it, the average was outputted and that was the reason for the "not reasonable" number that I've seen.

Sorry for nagging and thanks for the help!

+Daniel.

**Comment by alexanderzobnin** [comment]
@mrdanielmor yes, SingleStat default behaviour is a bit obvious sometimes.
