### ISSUE TITLE
Problem in Certificate

### ISSUE THREAD

**Issue by Filipe-Mariano** [alexanderzobnin/grafana-zabbix#266]
With OpenSuse Apliance 2.4, i tried --no-check-certificate ...not working =/..i can download in wget only
![screen shot 08-25-16 at 11 55 am](https://cloud.githubusercontent.com/assets/11853709/17974098/18eb1344-6abb-11e6-9be6-0b2e5f2b797c.PNG)

**Comment by alexanderzobnin** [comment]
@Filipe-Mariano looks like grafana.net issue. I will ask grafana guys.

**Comment by alexanderzobnin** [comment]
>Dan Cech [22:10]
you may need to update your cacert.pem
might need a new ca-certificates package

**Comment by Filipe-Mariano** [comment]
...solved...in yast2 i reinstall ca-cert mozila
