### ISSUE TITLE
Units in Grafana - GB and TB showing as EiB and ZiB

### ISSUE THREAD

**Issue by jovanmal** [alexanderzobnin/grafana-zabbix#269]
Hi people,

I am measuring Vmware datastore size and data units are set to gigabytes (using Zabbix plugin for Grafana). Please, can somebody explain how to tell Grafana to show me GB and TB units instead of EiB and ZiB?

Thank you in advance

**Comment by volter** [comment]
What are the raw numbers?

**Comment by jovanmal** [comment]
Thank you very much for your response.

As **nycnewman** commented in #247, units are displayed correctly when I set Unit parameter to bytes or bits (showing GiB and TiB instead of EiB and ZiB).

My problem resolved. Thank you once again :)
