### ISSUE TITLE
Problem with Grafana 3.1.1 and Zabbix 3.0.4

### ISSUE THREAD

**Issue by noonedeadpunk** [alexanderzobnin/grafana-zabbix#275]
Hello,

I've added zabbix instance to grafana, and connection has established correctly (I've received the message "Zabbix API version: 3.0.4"). However I still couldn't get how to retrieve host groups and hosts from zabbix server. I've created the dashboard with templates like in example, however I don't see any hosts and don't see an option how to add some of them into grafana. Meanwhile zabbix shows the user as online and updates it's "Last time seen" correctly.
Could you kindly explain how hosts, host groups and items should be added or retrieved from zabbix server in order to be able to use query editor like https://github.com/alexanderzobnin/grafana-zabbix/wiki/Usage#query-editor

Thanks in advance.

**Comment by alexanderzobnin** [comment]
Do you checked user's permissions?

**Comment by noonedeadpunk** [comment]
Yep. Firstly I gaveuser  read only permissions, however changing it to the administartor hasn't resolved the problem.

**Comment by noonedeadpunk** [comment]
Ok, seems that only superadmin works as for new. Thanks for your time

**Comment by alexanderzobnin** [comment]
@noonedeadpunk  May be you need check Zabbix API usage permissions?
