### ISSUE TITLE
Problem refresh data hostgroup

### ISSUE THREAD

**Issue by neodani** [alexanderzobnin/grafana-zabbix#276]
Hi,

I try restart grafana, remove plugin, add plugin again but doesn't refresh list of hostgroups in "select triggers" panel.

I created new hostgroups and I can't see them!

Any suggestion?

Thanks

**Comment by neodani** [comment]
Hi,

I could finally solve the problem, the user was connecting to the api had read only permissions, and by default zabbix doesn't put new hostgroups as allowed for this profile "read only"

Once I check user permissions in zabbix I could see the new hostgroups ;)

Regards!

**Comment by SP-SuperPoney** [comment]
6 years after this post saved me form hours of research !
