### ISSUE TITLE
Can't get values as text out of templating variables

### ISSUE THREAD

**Issue by ifallani** [alexanderzobnin/grafana-zabbix#277]
Hi.
Not sure if it's about grafana or Zabbix datasource handling, anyway...
I'm trying to get a value (interface description, text string) from a SNMP device monitored on Zabbix via templating variable using a query. Apparently, the variable returns the name of the instance and not the value of said instance. I've tried several queries but they either not working or they works as described. Using "text" instead of "query" in graph or table settings returns the value as expected.
Any ideas or anywere I could look at to provide you more infos?
Plugin version is 3.0.0 , Zabbix version is 3.0.3, Grafana is 3.1.1.

Thanks,
Iacopo.

**Comment by alexanderzobnin** [comment]
Can you provide screenshots?

**Comment by ifallani** [comment]
Hi.
Attached you will find 2 screenshots, "template.png" is the template
configuration while "table.png" is an example of the value correctly
retrieved.
As I've said, in the "template" scenario I would expect to retrieve the
value of any "Description of Interface..." instance that you can see in the
bottom of the screenshot but it's not working. In the "table" configuration
you can see as using "text" as Query Mode retrieves the value correctly.
I've also tested the same scenario with different instances (interface
alias, SNMP platform description) but the result is the same. It seems that
the problem arise whenever the value you want to retrieve is text/character
via query in template.

Thanks a lot,
Iacopo.



On Tue, Sep 13, 2016 at 10:14 PM, Alexander Zobnin <notifications@github.com

**Comment by alexanderzobnin** [comment]
@ifallani can't see any screenshots, try attach it via GitHub, not email.

**Comment by ifallani** [comment]
![table](https://cloud.githubusercontent.com/assets/22169394/18579466/04e51f74-7bf6-11e6-8d19-330eccdb6c63.png)
![template](https://cloud.githubusercontent.com/assets/22169394/18579469/0872cb00-7bf6-11e6-8141-879c796f8e46.png)

Here they are.

Thanks!

**Comment by alexanderzobnin** [comment]
Hm... Seems, all works properly. Description is _GigabitEthernet1/0/1_. What do you expect to get?

**Comment by alexanderzobnin** [comment]
Check also this value in Zabbix latest data.

**Comment by ifallani** [comment]
Maybe this other screenshot will help me to explain.
![graf](https://cloud.githubusercontent.com/assets/22169394/18587242/36621824-7c21-11e6-9675-b5245fb008af.png)
$intf_pref is a constant (text), $port_descr is the variable we're talking about. If you look at the graph title you can see how $port_descr value has not been retrieved, pulling the instance's name instead of its value. This is what I get wherever I'm trying to use this variable using something different from "text" metrics options (panel title as no option). I've also check that using $intf_descr alone, without any other variables concatenated with it, has the same result.
I'm sorry for my bad english, I would like to be more precise but I'm trying hard, believe me! :)

**Comment by ifallani** [comment]
Thanks but I'm not sure to understand what you're meaning when you say "._..template query can returns group, host, app and item's name only, not value". Look at this screenshot:
![traffic_in](https://cloud.githubusercontent.com/assets/22169394/18629628/2284924e-7e67-11e6-88be-2b3c82384ca8.png)
This is a templating variable, referring to an item named "traffic IN on XXX" where XXX is the name of an interface. Using this variable in a graphs or tables returns values, as you can see in the screenshot here:
![traffic_in_graf](https://cloud.githubusercontent.com/assets/22169394/18629695/9f88cc1a-7e67-11e6-8763-fd3446f4aaf6.png)

It seems to me that some items returning values while some other returns only their names but I'm almost sure I did not get your point.

**Comment by alexanderzobnin** [comment]
I mean you can't get interface description using variable like `$port_descr` because port description is a value of item `Description of interface GigabitEthernet...`. Template variable query can only return item name, not item's value. See more here https://github.com/alexanderzobnin/grafana-zabbix/wiki/Usage#templated-variable-editor

**Comment by ifallani** [comment]
Yes,  but at the same time I can get the value of an item (like "$traffic_in" in my last the screeenshot), therefore it seems I can't get the values if the values are of a certain type. For example, $traffic_in value si datatype "decimal", while $port_descr is "character". Could it be the scenario?

**Comment by alexanderzobnin** [comment]
You get values of item on graph. For the _character_ type you should use _Text_  Query Mode. This mode suitable for Singlestat panel and Table panel.

**Comment by ifallani** [comment]
Ok, thanks for your prompt responses.
