### ISSUE TITLE
_.includes is not a function

### ISSUE THREAD

**Issue by dreik** [alexanderzobnin/grafana-zabbix#279]
#### I'm submitting a ...
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- Grafana Version 3.1.1 (commit: a4d2708)
- Zabbix version 3.0.4
- zabbix plugin version 3.1.0
- OS Ubuntu
- What did you do? Trying to open previously saved graphs and dashboards
- What was the expected result? Graphs should works as well as on previous version
- What happened instead? Graphs are empty. Browser console full of following errors:

boot.1649cbaa.js:36 TypeError: _.includes is not a function
    at eval (datasource.js:427)
    at Function.Va (boot.1649cbaa.js:41)
    at bindFunctionDefs (datasource.js:426)
    at eval (datasource.js:186)
    at h (boot.1649cbaa.js:36)
    at boot.1649cbaa.js:36
    at n.$eval (boot.1649cbaa.js:36)
    at n.$digest (boot.1649cbaa.js:36)
    at n.$apply (boot.1649cbaa.js:36)
    at boot.1649cbaa.js:36

**Comment by alexraddas** [comment]
I am experiencing the same, I believe this is related to Functions in general, if all functions are removed, graph loads fine.

Ubuntu: 14.04
Grafana: 3.1.0/3.1.1
Zabbix plugin version 3.1.0
![screen shot 2016-09-26 at 6 10 33 pm](https://cloud.githubusercontent.com/assets/4071226/18857178/9aa89a86-8416-11e6-9ca9-823411d880e0.png)

**Comment by alexanderzobnin** [comment]
Seems, it works only in grafana 4.0.0-pre builds. Lodash version was upgraded from 2.4 to 4.x so seems, this function has't backward compatibility.

**Comment by michelmarinho** [comment]
Hi, so for use, we need do downgrade?

**Comment by alexanderzobnin** [comment]
I've pushed fix to grafana.net, so upgrade to `3.1.1`.

**Comment by michelmarinho** [comment]
Work 100% , tks!!! ;)
