### ISSUE TITLE
bug average function()

### ISSUE THREAD

**Issue by pedrohrf** [alexanderzobnin/grafana-zabbix#281]
#### I'm submitting a ...
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
3.1.1
- What Zabbix version are you using?
3.0.4
- What zabbix plugin version are you using?
3.1.1
- What OS are you running grafana on?
Ubuntu
- What did you do?
Trying to create a table using average function, using the same collection time and interval function.
- What was the expected result?
1 result  
- What happened instead?
2 results

![selecao_049](https://cloud.githubusercontent.com/assets/22482875/18891300/09fdff38-84db-11e6-888e-65c2fb802ee7.png)

**Comment by alexanderzobnin** [comment]
This is not a bug. You should choose _Time Series Aggregation_ mode for Table Transform. Consider these examples:

<img width="1280" alt="screen shot 2016-09-28 at 16 05 42" src="https://cloud.githubusercontent.com/assets/4932851/18914398/a8a2bb32-8595-11e6-9171-1ff0353b7098.png">

<img width="1280" alt="screen shot 2016-09-28 at 16 05 50" src="https://cloud.githubusercontent.com/assets/4932851/18914399/a8b92020-8595-11e6-8dd9-2ec770058c7b.png">
