### ISSUE TITLE
Regex not working properly in templating

### ISSUE THREAD

**Issue by Cbryndum** [alexanderzobnin/grafana-zabbix#283]
Possible bug, Zabbix plugin 3.1.1, Zabbix 3.0.4 and Grafana 3.1.1. Both Zabbix plugin and Grafana was just upgraded from previous version which also had the issue.

I create a templating variable to pull certain servers based on server name by using a regex expression. Sometimes it pulls all the servers but will not use all the servers in the actual panel.

![image](https://cloud.githubusercontent.com/assets/22503329/18923840/b89f272e-8562-11e6-8046-a3312d920093.png)

Here is the template, which is only showing 4 of the 11 servers. I did verify in Zabbix that i have data from all servers.

![image](https://cloud.githubusercontent.com/assets/22503329/18924631/c181759c-8565-11e6-94fd-280920558a55.png)

This example shows 0 servers in templating (which is correct)

![image](https://cloud.githubusercontent.com/assets/22503329/18924821/70d2ecba-8566-11e6-8cf3-d2c95fc4cb9a.png)

Yet in the panel graph i see the following two servers

![image](https://cloud.githubusercontent.com/assets/22503329/18924947/d5f0fcc2-8566-11e6-8a0d-8f75ea4d31af.png)

**Comment by alexanderzobnin** [comment]
Try to put regex into variable editor in `/ /` - `/mule-speech.*.dc12.*/`

**Comment by Cbryndum** [comment]
That helped, changed the regex statement too.
