### ISSUE TITLE
sumSeries() function not working as expected

### ISSUE THREAD

**Issue by potchin** [alexanderzobnin/grafana-zabbix#286]
This is an odd one. I have a graph which shows traffic to a wildcard number of webservers (currenly 2) and aggregate them using the sumSeries() function to give me total number of hits across all servers.The servers are currently active/backup so only one server will handle traffic at a time. This morning we failed the servers over so traffic moved from the primary to the secondary node.

The traffic for the system is around 11-12k requests/min but if the sumSeries() function is active the traffic shows as double before the failover...

![with_sum](https://cloud.githubusercontent.com/assets/2634163/19072219/ed8c8198-8a2b-11e6-88b4-8f8268d6b0b8.png)

If I remove the sumSeries() function the data points look correct...

![no_sum](https://cloud.githubusercontent.com/assets/2634163/19072231/ff5a0c10-8a2b-11e6-8668-f3fc528714c4.png)

Whats stranger still is that if I zoom into a time before the failover but _with_ the sumSeries() function active I see the correct traffic level (12k, not ~24k).

Is this a bug or am I missing something?

**Comment by alexanderzobnin** [comment]
Looks like a bug in `sumSeries()` function.

**Comment by Cbryndum** [comment]
Not to highjack the thread but if you are using stacked graphs with sumSeries() and one of the metrics doesnt return a value the stacked graph goes eschew.

![image](https://cloud.githubusercontent.com/assets/22503329/19158532/f3343b5e-8b9d-11e6-8fbf-9975716413ee.png)

If i disable the "bad" metric it works

![image](https://cloud.githubusercontent.com/assets/22503329/19158596/3054b658-8b9e-11e6-824b-246b2da8a73e.png)
