### ISSUE TITLE
Allow regex usage for setAlias function

### ISSUE THREAD

**Issue by hans-d** [alexanderzobnin/grafana-zabbix#287]
#### I'm submitting a ...
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

Would be nice if a regex could be used to set the alias, eg when a regex is used to select the items.

**Comment by evandro-portugal** [comment]
+1
This is very useful and missing feature!

**Comment by evandro-portugal** [comment]
Hey, last week I was in need of this and then found this out as a feature request... works out that I have made a change of my own to include this, I will be pushing the changes from my branch, hope you can have a fast look at it @alexanderzobnin , it's pretty simple and straight forwards, I have added one more option on Alias menu, "setAliasByRegex", that let you "cut" or do whatever you need with the original item name.

**Comment by sesom42** [comment]
Thanks for the very useful feature! A replacement similar to your example works perfect. But how does this "beast" work? Matching groups? Perl regex? A simple substitution is easier to understand: `s/foo (.+) bar/$1/`.

**Comment by evandro-portugal** [comment]
Hmm... I'm not sure if I got your question. Are you asking for a "search and replace" function? If so, this will not do it, since it uses a simple Go Regex, where it do a search using a regular expression and will replace the item.name with the result of the search (the same way any online regex tester will do, where you use a test string and it shows you the 'ouput' of you search).
To search for a pattern and replace it with another string, it would be necessary to create another function that expands this one.

**Comment by sesom42** [comment]
I'm not sure, which regex engine is used. The regex shown in your screenshot is not golang, it is pcre. Even it is not Go re2. Lookahead and lookbehind are not supported in re2 ([re2 Syntax](https://github.com/google/re2/wiki/Syntax)). It is strange that positive lookahead works, but positive lookbehind does not. `(?<=DFP ).+` (like your example) triggers an error. Which regex engine is used? Confused.

**Comment by evandro-portugal** [comment]
hmm, strange, I was almost sure that it was golang regex, since I used the same function that is invoked by the text filter on text metrics. Maybe @alexanderzobnin could answer this.

**Comment by alexanderzobnin** [comment]
This code executes on client side. So it should be JavaScript regex.

**Comment by landergate** [comment]
With current implementation it's quite problematic to cut text between two words (e.g.: "steal" from "CPU steal time"), as JS don't support positive lookbehind like this: `(?<=CPU ).*?(?= time)`

Matching group would be much simpler approach:
`CPU (.*) time`

So let's make the match group number configurable?
https://github.com/alexanderzobnin/grafana-zabbix/blob/dcbc67d26cb9e54d9a661e99953cf8e79286d02e/src/datasource-zabbix/dataProcessor.js#L179

**Comment by alexanderzobnin** [comment]
Yea, I should make alias functions more flexible.

**Comment by alexanderzobnin** [comment]
see http://docs.grafana-zabbix.org/reference/functions/#replacealias
