### ISSUE TITLE
Error loading module.js

### ISSUE THREAD

**Issue by DuboisJeremy** [alexanderzobnin/grafana-zabbix#288]
Hi everyone,

I have an issue when I try to upgrade my plugin from 3.0.0 Beta 2 to 3.1.1. When I load the Plugin page I have the following error :
"Plugin Error
Error: XHR error (404 Not Found) loading https://***********/public/traceur?bust=1475659939058 Error loading https://***********/public/traceur Error loading https://***********v/public/plugins/alexanderzobnin-zabbix-app/module.js"

So I checked the difference between the module.js file from the two versions and they are different.
Version 3.0.0 Beta 2 :
'use strict';
System.register(['./components/config'], function (_export, _context) {
  var ZabbixAppConfigCtrl;
  return {
    setters: [function (_componentsConfig) {
      ZabbixAppConfigCtrl = _componentsConfig.ZabbixAppConfigCtrl;
    }],
    execute: function () {
      _export('ConfigCtrl', ZabbixAppConfigCtrl);
    }
  };
});
//# sourceMappingURL=module.js.map

Version 3.1.1 :
import {ZabbixAppConfigCtrl} from './components/config';
export {
  ZabbixAppConfigCtrl as ConfigCtrl
};

As you can see, module.js from 3.1.1 is lighter than the older one. Im not good on Javascript so i don't know if the file is wrong. I tried to paste the old file in the 3.1.1 folder and the next error I got on Plugin page is that he has an issue with config.js.

So I changed with old one and it worked... It seems that all my JS files (even in folder "datasource-zabbix") are really lighter than the ones in version 3.0.0 Beta2...

To finish, I can't use gragana-cli because our server are not allowed to get web access. All our sources are files tar.gz from downloaded on grafana.net.

Thanks for your help.

Regards,

Jeremy

**Comment by alexanderzobnin** [comment]
Hi, Jeremy! Just try to use this installation case: http://docs.grafana-zabbix.org/installation/#from-special-repo. Seems, You're trying to use not transpiled source code. Now plugin is written by ES6 JavaScript, so you can't use it without transpiling into ES5 which browsers supports.

**Comment by DuboisJeremy** [comment]
Hi Alexander,

I followed your advice and use the download from special repo ("grafana-zabbix-app-master") and it works way better cause there are all the JS files and JS.MAP !

Thanks for your answer. Closing the issue.

**Comment by Jovanez** [comment]
Update grafana cli 
https://grafana.com/grafana/download
