### ISSUE TITLE
Delta speed per second?

### ISSUE THREAD

**Issue by ntlord** [alexanderzobnin/grafana-zabbix#289]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [X ] Question / Support request

I'm wondering if there is a way to calculate bandwidth from ifnOctets retrieved from Zabbix? In Zabbix I can store a value as (delta (speed per second)). But, those values, when retreived in Grafana, are just the raw octets values from ifnOctets. I know there is a delta function in Grafana, but that only (of course) gives the delta between the last two values, and not the delta divided by the time between each of the last values.

Thanks,

Dan

**Comment by alexanderzobnin** [comment]
May be, this is idea for feature request - add period as parameter to delta() function.

**Comment by ntlord** [comment]
This would be pretty nice. I'm guessing, in the mean time, I can get close by using calculated values in Zabbix (e.g. (ifnOctets.current - ifnOctets.last)/60), but, unfortunately, when the counters roll over it will get all messed up. I'm not sure there is a way to deal with that.

**Comment by alexanderzobnin** [comment]
Just idea - you can use `delta()` after `groupBy(1m, avg)` and then scale by 0.1666 (1/60). This is workaround, but may be it helps you.

<img width="1280" alt="screen shot 2016-10-06 at 18 08 57" src="https://cloud.githubusercontent.com/assets/4932851/19158069/11038d7c-8bf0-11e6-917a-7c1737b2d157.png">

**Comment by volter** [comment]
> In Zabbix I can store a value as (delta (speed per second)). But, those values, when retrieved in Grafana, are just the raw octets values from ifnOctets.

This sounds wrong.

**Comment by ntlord** [comment]
> This sounds wrong.

That's what I'm hoping. But, I can tell you for sure that the interfaces are displaying the statistics in Zabbix correctly (e.g. in Mbit/s). And the "store as" delta (speed per second) is correctly set. In grafana, though I'm definetly seeing the raw octet numbers too. I'd also add that even within Zabbix when I do a "calculated item" and use the ifnOctets item as a source, the data is the raw octets. So if I'm doing something wrong, I'm not sure what it is.

**Comment by volter** [comment]
I can't confirm that. Works for me! The API can't possible return the raw values, because "Store value as" instructs the server to store the rate to the database.

**Comment by ntlord** [comment]
Ok well that is potentially good news--since it means I'm doing something wrong. I wonder what value it's spitting out then? It definitely not the same rate. Maybe its a divide by 8 issue.

**Comment by ntlord** [comment]
Well, I'm officially and idiot! I had it set to show the average instead of the current,

**Comment by fxfitz** [comment]
@ntlord I definitely don't think you're an idiot because I'm having the same problem [I think] and I don't consider myself an idiot! Not on weekends, anyways.

Can you please explain what you did to fix it? Thanks!

(PS: New to grafana and this plugin)

**Comment by fxfitz** [comment]
Landed up figuring it out! I needed to change my units. Derp. :-P
