### ISSUE TITLE
Zabbix Items group by timestamp

### ISSUE THREAD

**Issue by oovoo** [alexanderzobnin/grafana-zabbix#29]
If we try to make a new graph that will be build based on bars type, we get following result:

![capture](https://cloud.githubusercontent.com/assets/2486064/8272855/026f7710-185d-11e5-826c-fd27650be1c0.PNG)

**Comment by oovoo** [comment]
![capture](https://cloud.githubusercontent.com/assets/2486064/8272869/50d74a72-185d-11e5-95dd-75086109f371.PNG)

vs on graphs that you present it looks much better 

can u please explain what I miss here?

**Comment by alexanderzobnin** [comment]
This graph based on zabbix trends. Trends are calculates as one point for each hour for every item. For this reason points on all graphs have same timestamp. Data from history may be written in database in different time. For this reason points displayed a little chaotic. I'm trying to resolve this problem in [feature-downsample](https://github.com/alexanderzobnin/grafana-zabbix/tree/feature-downsample) branch.

**Comment by alexanderzobnin** [comment]
Also my graph is stacked and all bars displayed on top of each other. You can try to activate stack and looked at result.

**Comment by alexanderzobnin** [comment]
Look at my history data at large zoom (5 min, metrics collected every minute).
![2015-06-21 22-30-51 grafana - query editor - google chrome](https://cloud.githubusercontent.com/assets/4932851/8273056/8a1b742c-1865-11e5-84f8-a9943000293f.png)
For proper stacking all points in marked groups must have same timestamp. This is Zabbix specificity, not Grafana's.

**Comment by alexanderzobnin** [comment]
Resolved by #12.
