### ISSUE TITLE
Grafana 3.0.2 & Zabbix 3.0.5 - Short History 

### ISSUE THREAD

**Issue by frankie7** [alexanderzobnin/grafana-zabbix#290]
- **I'm submitting a ...**
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Grafana 3.0.2 & Zabbix 3.0.5 
- What datasource are you using? Grafana Zabbix Plugin 
- What OS are you running grafana on? Debian 8.1
- What did you do? I installed the Grafana Zabbix Plugin to test my zabbix graphs under Grafana.
  Trends aren't enabled. Using http://x.x.x.x/zabbix/api_jsonrpc.php, direct access.
- What was the expected result? All graphs displayed.
- What happened instead? All graphs displayed but only 2 days history. 

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
How long have you stored history in Zabbix?

**Comment by frankie7** [comment]
About a month of history in Zabbix. The strange thing is that i created two organizations on Grafana. The Main.org organization takes all the Zabbix History. The other organization takes only two days. Very strange. Thanks for your help!

**Comment by alexanderzobnin** [comment]
Does other Org use the same datasource?

**Comment by frankie7** [comment]
Yes the same datasource, i performed a reconfiguration, restarted grafana and it works now! But there's another issue, i'm unable to delete a dashboard. It just doesn't delete :) ... is there a "command line" way to delete dashboards?

**Comment by alexanderzobnin** [comment]
@frankie7 May be you're not an admin in Grafana? What dashboard did you try to delete?

**Comment by frankie7** [comment]
Alexander, i am admin and i tried to delete a testing dashboard created by me. I didn't even get a generic error, just silence and no deletion. But i managed to delete the dashboard in another way: by using the settings menu->row editor->trashcan.
