### ISSUE TITLE
Data interval in a long period

### ISSUE THREAD

**Issue by DuboisJeremy** [alexanderzobnin/grafana-zabbix#292]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request
#### For bug report please include this information:
- What Grafana version are you using? 3.1
- What Zabbix version are you using? 3.0.1
- What zabbix plugin version are you using? 3.1
- What OS are you running grafana on? CentOS
- What did you do? Metrics on 7 days
- What was the expected result? Data interval pretty short
- What happened instead? 1 hour between each data

Hi,

When I want to get metrics on 7 days, it appears that data have an interval of one hour. This happens on our Dev platform. In our Prod platform, where Grafana version is 2.6 and plugin is 3.0, on a 7 days period metrics got downsampled but interval between each data is ~15 minutes.

I suppose that I miss a configuration somewhere but in Plugin 3.1 downsampling disepear and I tried to use function like groupBy but this doesn't affect the graph.

I apologize if the issue is not due to the plugin but Grafana settings.

Regards,

Jeremy

**Comment by alexanderzobnin** [comment]
Seems, you [enabled trends](http://docs.grafana-zabbix.org/installation/configuration/#zabbix-api-details), so if you select data by more than 7 days, it's being got from trends which has 1 hour resolution.
