### ISSUE TITLE
Annotation: Include triggername

### ISSUE THREAD

**Issue by hans-d** [alexanderzobnin/grafana-zabbix#294]
#### I'm submitting a ...
- [x] Feature request

Right now showing in the hover menu:
- hostname (optional)
- problem/ok
- ack message
- date/time

Would be nice to have also the triggername there

**Comment by alexanderzobnin** [comment]
![screenshot from 2017-02-11 17 10 07](https://cloud.githubusercontent.com/assets/4932851/22854321/f55791b2-f07c-11e6-83a0-b708a8d8ccb8.png)
