### ISSUE TITLE
Trends: max/min

### ISSUE THREAD

**Issue by hans-d** [alexanderzobnin/grafana-zabbix#295]
#### I'm submitting a ...
- [x] Feature request

For trends, zabbix itself shows min,max and avg.
Would be nice if this could be selected/controlled in garafana as well

**Comment by alexanderzobnin** [comment]
You can use `trendValue()` function like here: http://play.grafana-zabbix.org/dashboard/db/trends

**Comment by hans-d** [comment]
Thanks. Does seem to have some issues when using together with stacked values
