### ISSUE TITLE
Best way to Monitor Switch Ports in a Single Graph

### ISSUE THREAD

**Issue by kushalraha** [alexanderzobnin/grafana-zabbix#296]
#### I'm submitting a ...
- [x] Question / Support request

Trying to create a graph that shows the incoming traffic for each port and the outgoing traffic for each port on a 48 port switch. What is the best way to do this, without having to add the metrics one at a time for each and every port?

Also, is there a way to use "Switch Port Name" Instead of "Incoming Traffic on Port x"?

**Comment by alexanderzobnin** [comment]
Read getting started guide - there are some examples for your case.
Quick answer: use `/Incoming Traffic on Port .*/` regex for item.
>Also, is there a way to use "Switch Port Name" Instead of "Incoming Traffic on Port x"?

No, right now no way.

**Comment by kushalraha** [comment]
Thanks @alexanderzobnin got that sorted.

> No, right now no way.

This might be a good feature to consider, if you have quite a number of network devices, it becomes difficult to remember port goes where.

**Comment by alexanderzobnin** [comment]
@kushalraha  Also, try to play with regex in templating (use catch groups for selecting part of metric name)
For example, in regex field use
```
/Incoming Traffic on Port (.*)/
```
to get only port number as template variable. Then, use this variable in request and aliases.
