### ISSUE TITLE
http 412 error code

### ISSUE THREAD

**Issue by igroykt** [alexanderzobnin/grafana-zabbix#298]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [ x] Question / Support request
#### For bug report please include this information:
- What Grafana version are you using? grafana-3.1.1-1470047149.x86_64
- What Zabbix version are you using? zabbix-server-mysql-3.0.5-1.el7.x86_64
- What zabbix plugin version are you using? 3.1.1
- What OS are you running grafana on? 3.10.0-327.36.1.el7.x86_64
- What did you do? I installed and configured zabbix server from zabbix repository then installed grafana from grafana repository and installed zabbix plugin via grafana-cli. I'm using admin login and password for api access.
- What was the expected result? Add data source
- What happened instead? Http error code 412

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
  ![grafana](https://cloud.githubusercontent.com/assets/8286508/19509659/c850d618-961a-11e6-8b2d-7e3e820d06b8.jpg)
  [grafana.txt](https://github.com/alexanderzobnin/grafana-zabbix/files/538225/grafana.txt)

**Comment by igroykt** [comment]
Replaced domain by 'mydomain'.

**Comment by alexanderzobnin** [comment]
Try to use _proxy_ connection mode.

**Comment by igroykt** [comment]
@alexanderzobnin тоже самое

**Comment by metanovii** [comment]
i have this ploblem too. i use freebsd 10.1, zabbix 3.0.5, grafana 3.1.1 and plugin latest version.

**Comment by alexanderzobnin** [comment]
Try to enable _With CA Cert_ in data source config. Is it still actual?
