### ISSUE TITLE
Zabbix dashboard does not show icon 'host in maintenance'

### ISSUE THREAD

**Issue by opokhvalit** [alexanderzobnin/grafana-zabbix#299]
I'm testing grafana-zabbix, and found that zabbix dashboard doesn't show 'host in maintenance' mark.
Is it possible add that feature? It very useful.

And second question. I cannot select anything on dashboard by mouse cursor. This is nessesary for copy-paste some info from dashboard, for ex. hostname or issue.

Thank you

**Comment by andreioss** [comment]
Joining to this request, very useful features!

**Comment by alexanderzobnin** [comment]
@opokhvalit @andreioss do you need exactly icon? I've added option for trigger panel which can hide hosts in maintenance?

**Comment by alexanderzobnin** [comment]
![screenshot from 2017-12-14 12-46-30](https://user-images.githubusercontent.com/4932851/33985866-d60bd3ea-e0cc-11e7-8d66-c8b69e2c3350.png)
