### ISSUE TITLE
host list doesn't work

### ISSUE THREAD

**Issue by protheusfr** [alexanderzobnin/grafana-zabbix#30]
Hello,

I've try to use the plugin with a Zabbix server version : 2.2.9 and the last version of Grafana.
After setup Zabbix part and apply the patch on api_jsonrpc.php I success to get the group list when adding a metric.
But Host lists, Application list and Item list remain empty (I.E. only with "All" value).
Nothing in log file and no datapoints.

I've I doing something wrong ?

**Comment by alexanderzobnin** [comment]
Hello! I'll try to do more tests for Zabbix 2.2 - some users have the same problems. Perhaps the program has errors in  Zabbix API calls. Will be very helpfull if you send me network log:
![troubleshooting_network_1](https://cloud.githubusercontent.com/assets/4932851/8286676/9988854a-1913-11e5-9e88-9ee0444710c5.gif)
Select any group, copy log and past here.

**Comment by protheusfr** [comment]
Impressive reactivity, thank you alexander.
Will this fix included in the next release ?

**Comment by protheusfr** [comment]
Tested new commit, it's work !
Really thank's.
