### ISSUE TITLE
Use template hostname as groupname

### ISSUE THREAD

**Issue by hans-d** [alexanderzobnin/grafana-zabbix#300]
#### I'm submitting a ...
- [?] Bug report
- [?] Feature request
- [?] Question / Support request

Not sure if it is a bug, a FR, or ...

Using Grafana 3.1.0, Zabbix plugin 3.1.1, Zabbix 2.4.3. Grafana + plugin are running from docker.

Having a template variables with zabbix as source:
- group, to select zabbix host group, query \* - works fine
- host, to select zabbix host, query $group.\* - works fine

Trying to create a new variable, eg host2, with query $host.*
Here no results are presented.

Eg this is for a template to be used for a MySql database running on multiple hosts (either a normal cluster, or with drbd standby).
Group: <whatever>
Host: db.hostname.com

The related hosts I wan to be easy selectable, so I've created a host group
db.hostname.com
containing the various hosts

**Comment by alexanderzobnin** [comment]
You should `group.host.app.item` structure for every template query (https://github.com/alexanderzobnin/grafana-zabbix/wiki/Usage#templated-variable-editor). So you may use `*.*` to select all hosts or, for instance, `mysql.*` to select all hosts in `mysql` group.

**Comment by hans-d** [comment]
issue was caused by the group not being readable by the api user, now it works fine.
