### ISSUE TITLE
Annotations showing "undefined" 

### ISSUE THREAD

**Issue by svdasein** [alexanderzobnin/grafana-zabbix#301]
#### I'm submitting a ...
- [ x] Bug report
- [ ] Feature request
- [ ] Question / Support request
#### For bug report please include this information:
- What Grafana version are you using? 3.1.1
- What Zabbix version are you using? 3.0.4
- What zabbix plugin version are you using? 3.1.1
- What OS are you running grafana on? Ubuntu 14.04.1 LTS
- What did you do? upgraded grafana and grafana zabbix to latest
- What was the expected result?  annotations would still show trigger description etc
- What happened instead?  annotations show 3 lines "PROBLEM|OK", "undefined", "[timestamp]"

**Comment by alexanderzobnin** [comment]
Fixed by ca97d392e9e43dd9ab5cbf0435869d7402a7aa62
