### ISSUE TITLE
Support for Alerting in grafana 4.x

### ISSUE THREAD

**Issue by andreioss** [alexanderzobnin/grafana-zabbix#304]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request

Hello,
Tell us please, do you planning to update your plugin for support grafana 4.0? There are plenty awesome features in it, and it would be great if zabbix could work with them.
Thanks!

**Comment by alexanderzobnin** [comment]
@andreioss Hi! Of course. But there are no breaking changes in Grafana 4.0, so you can use version of plugin since `3.1.1` (in this version I fixed bug introduced by lodash upgrade from 2.x to 4.x). I'm developing plugin using latests code from master branch of Grafana and now it works without any problems. You can try latests version from grafana.net with grafana 4.0 beta release right now.

**Comment by andreioss** [comment]
Alexander, it's great!
And is there any chance, that new features like alerting/notification and alert list panel will be work with zabbix data?

**Comment by alexanderzobnin** [comment]
@andreioss It's a good question. Grafana introduced great alerting feature in 4.0, but Zabbix has its own trigger mechanism. So I don't want to duplicate it. Ideal approach for showing zabbix alerts in grafana is just ask zabbix for active alerts and show it in Grafana, but current alerting implementation don't allow to do it (grafana requests alerts from its backend). So I need to make some changes in grafana backend for it (or wait for Torkel do that). It takes a time, unfortunately...

**Comment by andreioss** [comment]
Yep, I understand that. 
My point is - it would be cool, if grafana could show pop up alerts and play some sound for example in browser, when new triggers in zabbix is show up.
Why I'm wondering of it - it's simple usability of zabbix, it's awful as you know, and I completely go off from its dashboard to grafana, but with out alerting system, I have to open two tabs in browser, one with grafana for common work and one with zabbix just for to be aware of triggering new alerts. That's it :)

**Comment by pichichi91** [comment]
Actually the Alerting feature would be interesting, as it would be nice to have alerting features with beautiful graphes :)

**Comment by aptoff** [comment]
Hi @alexanderzobnin,
first thank you for your work, it's a real pleasure to get some great dashbord for Zabbix !
Did we have a chance to see this feature working in some weeks or months ?

**Comment by neodani** [comment]
Yes! pleaseee it would be very cool if you can! We would be very grateful!

**Comment by xiaoxue999** [comment]
Yes ,come on! i don't want to use the zabbix Screen,Alerting again,because it looks like very pool and not friendly.

**Comment by andreioss** [comment]
Wow, Alexander! We're all waiting for this feature with impatience!
Thanks for your work!

**Comment by alexanderzobnin** [comment]
Before we should add support in Grafana, but I'm working on that.

**Comment by Pbants** [comment]
Glad to see this is being worked on.  I setup an Alert for a graph from zabbix and keep getting The datasource does not support alerting queries.

Can't wait!

**Comment by nevermore424** [comment]
Glad to see this is being worked on .Can‘t wait！ too~~

**Comment by shlomihorev** [comment]
Thanks for the hard work, Can't wait to see it in our prod environment.

**Comment by Roman-Lo** [comment]
Alerting is super important in monitoring! Can't wait +1! Great job Alex!

**Comment by mouimet12** [comment]
Looking forward to the Alerting. We are trying to move all dashboards to grafana

**Comment by eth0h4ckr** [comment]
Grafana is the best. This feature would make it even better. Thanks for the awesome software @alexanderzobnin !

**Comment by AndrewwHummer** [comment]
Cannot wait to finally use alerting with Zabbix in Grafana. Thanks so much!

**Comment by alexanderzobnin** [comment]
Implemented in 3.4. See https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v3.4.0
