### ISSUE TITLE
No Show Data.

### ISSUE THREAD

**Issue by felipesbs** [alexanderzobnin/grafana-zabbix#305]
I can not visualize some data, where should I look?

They are displayed "N/A" and "CPU Graf"

![image](https://cloud.githubusercontent.com/assets/23387404/20191209/54ddc916-a763-11e6-861d-78f235bbcb15.png)

**Comment by alexanderzobnin** [comment]
Does your Zabbix server has queried metrics?

**Comment by alexanderzobnin** [comment]
See #347
