### ISSUE TITLE
Offline installation fail

### ISSUE THREAD

**Issue by MethyleneBlu** [alexanderzobnin/grafana-zabbix#306]
#### I'm submitting a ...
- [X] Bug report
- [ ] Feature request
- [X] Question / Support request

Hello,

For a migration project from 2.1.0 I'm currently trying to install zabbix-grafana 3.1.0 on grafana 3.1.1 in completely offline mode on a server with on access on the web. According to the documentation : 
- I downloaded a zip file of the github project and copied/paste it in /var/lib/grafana/plugins/
- I changed the owner to grafana:grafana
- I restarted grafana-server

Now I have three problems :
- The zabbix plugin is not listed in "grafana-cli plugins ls" but is known through the GUI
- The zabbix plugin is listed in the graphical interface but is not enabled
- I have an error when I try to access to the screen of the zabbix plugin to enable it through the GUI

![capture](https://cloud.githubusercontent.com/assets/23459199/20302486/cacfab86-ab27-11e6-8e43-ebd8ce8387ca.PNG)

Could you help me solve my problem ?

Thank you by advance

**Comment by alexanderzobnin** [comment]
Did you read installation docs?

**Comment by MethyleneBlu** [comment]
Yes, but it imply to use the grafana-cli which needs an access online.
I've made a new try with your project grafana-zabbix-app-master copied/paste in the plugins directory (v 3.1.2) and it seems much better.

The "admin" user can enable it, but not all the other users for whom I get a "permission denied" error and I cannot enable it.

Maybe there is a possibility to enable it for everyone ?

**Comment by alexanderzobnin** [comment]
Only user with Admin permission can manage plugins in Grafana. But you should enable it just once and then all users from the same org can use it.

**Comment by MethyleneBlu** [comment]
Aaaaah it explains everything. However I've created orgs to map each group based on LDAP... mmmh OK, I'll see directly with the grafana team now. Thank you very much.
