### ISSUE TITLE
Two metrics on one graph with timeshift

### ISSUE THREAD

**Issue by pavelnemirovsky** [alexanderzobnin/grafana-zabbix#307]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [X] Question / Support request

First of all i want to admit u really crated a great professional product, well done. 

Can u please advise how i can achieve using grafana capability cooperated with zabbix plugin when i can have two metrics where 1st one will be based on current time and second one will be looking 24h behind.

Just an example:
![image](https://cloud.githubusercontent.com/assets/19474975/20366465/eddb626e-ac53-11e6-8a04-567cd8ca2373.png)

Thanks again,

P

**Comment by alexanderzobnin** [comment]
Hi! Thanks! About your question - now it's not impossible. But it one of feature which I want to add (with new `timeShift()` function for target), because it's very useful case for detecting correlation and deviations.

**Comment by alexanderzobnin** [comment]
Now you can use `timeShift()` function for shifting graph in time.

<img width="1280" alt="screen shot 2016-11-17 at 21 44 38" src="https://cloud.githubusercontent.com/assets/4932851/20402783/3180fa72-ad0f-11e6-9ad9-d596a84e56dd.png">

**Comment by pavelnemirovsky** [comment]
You are simple amazing, thank you

**Comment by pavelnemirovsky** [comment]
Do u plan to release a version with this change?

**Comment by alexanderzobnin** [comment]
Yes, but don't know when. You can [build it from sources](http://docs.grafana-zabbix.org/installation/#building-from-sources).

**Comment by nubigtree** [comment]
I build this plugin from source for the timeshift new feature. But i got a error message "_.uniqBy is not a function".
![image](https://cloud.githubusercontent.com/assets/11755555/20563011/849c4728-b1c1-11e6-957c-72d459494e0a.png)

![image](https://cloud.githubusercontent.com/assets/11755555/20562970/5b200b78-b1c1-11e6-96f2-d7e54f032b7b.png)

Can you please advise anything i can do.

Thanks a lot.

**Comment by alexanderzobnin** [comment]
@nubigtree You should use latest grafana (4.0 pre). This is due lodash upgrade from 2.x to 4.x in Grafana, so some methods aren't have backward compatibility. Seems, I missed this method. Will try to fix, but in Grafana 4.x it works.

**Comment by nubigtree** [comment]
Hi Alex, 
After upgrade to grafana4.x, it works well.thank you very much!
