### ISSUE TITLE
[Bug] -  Problems with the values presented in grafana in singlestat

### ISSUE THREAD

**Issue by conexaoinfraestrutura** [alexanderzobnin/grafana-zabbix#309]
- What Grafana version are you using?
grafana-3.1.1-1470047149.x86_64

- What datasource are you using?
zabbix server 2.4 - alexanderzobnin-zabbix-app @ 3.1.2
![screenshot from 2016-11-22 11-35-16](https://cloud.githubusercontent.com/assets/19329445/20525792/369f9472-b0a8-11e6-9e2c-8ce06d0d924f.png)

- What OS are you running grafana on?
https://aws.amazon.com/amazon-linux-ami/2016.09-release-notes/
with epel centos 6.8 packages

- What did you do?
Get pfree disk space - vfs.fs.size[/,pused] - https://www.zabbix.com/documentation/2.4/manual/config/items/itemtypes/zabbix_agent

- What was the expected result?
    zabbix_get -s xxx.xxx.xxx.xxx -k vfs.fs.size[/,pused] = 61.421483
    zabbix_get -s xxx.xxx.xxx.xxx -k vfs.fs.size[/,pfree]  = 38.579115

- What happened instead?
The data collected by zabbix are correct but at the time of presenting them in grafana singlestat the value is incorrect.

![screenshot from 2016-11-22 11-30-53](https://cloud.githubusercontent.com/assets/19329445/20525586/4f4b3a90-b0a7-11e6-84a8-3a971187fc3e.png)

**Comment by alexanderzobnin** [comment]
@conexaoinfraestrutura Can you check api response, please?

<img width="1280" alt="screen shot 2016-11-22 at 20 27 48" src="https://cloud.githubusercontent.com/assets/4932851/20534435/49670028-b0f2-11e6-8b80-1e41359549d7.png">

**Comment by conexaoinfraestrutura** [comment]
![screenshot from 2016-11-23 14-11-42](https://cloud.githubusercontent.com/assets/19329445/20569538/925c13be-b187-11e6-8e1b-828edcdc0d3a.png)
![screenshot from 2016-11-23 14-11-05](https://cloud.githubusercontent.com/assets/19329445/20569541/9473b148-b187-11e6-9521-478d46d17ac6.png)

**Comment by conexaoinfraestrutura** [comment]
![screenshot from 2016-11-23 14-21-46](https://cloud.githubusercontent.com/assets/19329445/20569760/5e7b2ee4-b188-11e6-9238-f270a59a15c6.png)

**Comment by alexanderzobnin** [comment]
But wthat's wrong? Server returns the same value as Grafana shows.

**Comment by conexaoinfraestrutura** [comment]
The zabbix server is returning the percentage of free space on the disks correctly for api.

    zabbix_get -s xxx.xxx.xxx.xxx -k vfs.fs.size[/,pused] = 61.421483

But I do not know why api is presented with the value "11" instead of the value being sent by zabbix. What should be 61.421483
In the grafana singlestat should appear the value 61%
I believe that the problem is not in singlestat but in api that is related to some transformation in the value that is collecting in zabbix.
I have already tried to change the value treatment in the "Unit" option but none of the options therein present the value correctly in singlestat

**Comment by alexanderzobnin** [comment]
Can you check is that proper `itemid` for `vfs.fs.size[/,pused]` ?

**Comment by conexaoinfraestrutura** [comment]
Dude. Sorry. 
I looked for item so much times than i don't saw who i was using wrong key.
I used  vfs.fs.inode[/,pused] over than vfs.fs.size[/,pfree]
after i realized this problem all things they passed to work fine.
Sorry by my mistake. 
Thanks by attention.
Close this issue. There's no bug
