### ISSUE TITLE
Add template variables to dropdown metric list

### ISSUE THREAD

**Issue by manhdinh** [alexanderzobnin/grafana-zabbix#310]
#### I'm submitting a ...
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request

Hello, i using Grafana v3.1.1 and Zabbix v3.0.4. When i create a templating for $group and $host, everything seem to be ok : http://prntscr.com/dao4qw . However when i configure query from zabbix source, no template variables appear @@. I don't know why :| http://prntscr.com/dao596 
And when i using another source ( graphite source ), the template varibale will appear. Pls answer me. Thanks !

**Comment by andreioss** [comment]
Hi, you should write variable name from template to the appropriate field manually, i.e. it shouldn't appear in the list of Groups or Hosts.
Just like that - http://storage4.static.itmages.ru/i/16/1201/h_1480596657_5478298_fe63af0c73.png
