### ISSUE TITLE
Unable to apply template variables to Triggers Panel query

### ISSUE THREAD

**Issue by louzadod** [alexanderzobnin/grafana-zabbix#311]
#### I'm submitting a ...
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
3.1.1
- What Zabbix version are you using?
Zabbix 3.0.5 LTS
- What zabbix plugin version are you using?
3.1.2
- What OS are you running grafana on?
Ubuntu Server 14.04 LTS + Docker 1.12.3
- What did you do?
 I tried to apply template variables into Trigger Panel Query editor
- What was the expected result?
Filtered triggers
- What happened instead?
Query never returns - it blocks

**Comment by alexanderzobnin** [comment]
Closed in 3.2.1
