### ISSUE TITLE
Interaction with active triggers

### ISSUE THREAD

**Issue by andreioss** [alexanderzobnin/grafana-zabbix#313]
#### I'm submitting a ...
- [ ] Bug report
- [x ] Feature request
- [ ] Question / Support request

It would be great to be able to set acknowledges to triggers from your trigger panel. 
There is zabbix api function exactly for that:
https://www.zabbix.com/documentation/3.0/manual/api/reference/event/acknowledge

**Comment by alexanderzobnin** [comment]
@andreioss It's possible now. Click to icon inside _Info_ section and add acknowledge.

<img width="1280" alt="screen shot 2016-12-01 at 17 33 39" src="https://cloud.githubusercontent.com/assets/4932851/20797567/61cc659e-b7ec-11e6-9915-5a596cf89485.png">
