### ISSUE TITLE
Zabbix Plugin is not listed in the installed apps.

### ISSUE THREAD

**Issue by PragnaMohapatra** [alexanderzobnin/grafana-zabbix#314]
#### I'm submitting a ...
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
   3.1.1
- What Zabbix version are you using?
- What zabbix plugin version are you using?
  alexanderzobnin-zabbix-app @ 3.1.2
- What OS are you running grafana on?
   rhel 7
- What did you do?
  I have installed the zabbix plug in using the CLI command and got the success message. After that I have restarted the grafana server. But under apps I am not seeing the zabbix to be listed as a new app.
- What was the expected result?
Expected to see the new zabbix app under app section.
- What happened instead?
Nothing is listed under the app 

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Check grafana log end ensure that Zabbix plugin has been registered. If not, try to install with explicit `--pluginsDir "/var/lib/grafana/plugins"` option (check your plugin dir path before). Sometimes `grafana-cli` uses wrong path for plugin dir.

**Comment by PragnaMohapatra** [comment]
Thanks Alex ,
Let me try that. I do see that the plug has been downloaded to the plug in
directory.

Kind Regards
Pragna

**Comment by PragnaMohapatra** [comment]
Hello Alex,
I tried to follow your suggestion. I am in the plugins directory and trying to run the following command but getting an error that --pluginsDir is not a valid parameter. Kindly let me know if I am doing it right.

[root@ip-10-205-210-45 alexanderzobnin-zabbix-app]# pwd
/var/lib/grafana/plugins/alexanderzobnin-zabbix-app
[root@ip-10-205-210-45 alexanderzobnin-zabbix-app]# grafana-cli plugins install --pluginsDir /var/lib/grafana/plugins/alexanderzobnin-zabbix-app
Incorrect Usage.

NAME:
   Grafana cli plugins install - install <plugin id>

USAGE:
   Grafana cli plugins install [arguments...]
flag provided but not defined: -pluginsDir[root@ip-10-205-210-45 alexanderzobnin-zabbix-app]# 


Kind Regards
Pragna

**Comment by alexanderzobnin** [comment]
Read `grafana-cli` help.
