### ISSUE TITLE
Error: XHR error (404 Not Found)

### ISSUE THREAD

**Issue by murilosaez** [alexanderzobnin/grafana-zabbix#315]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [X] Question / Support request

Plugin Error
Error: XHR error (404 Not Found) loading http://10.0.1.142:3000/public/app/plugins/app/alexanderzobnin-zabbix-app/datasource-zabbix/module.js?bust=1481116529790 Error loading http://10.0.1.142:3000/public/app/plugins/app/alexanderzobnin-zabbix-app/datasource-zabbix/module.js

Can someone help me?

**Comment by alexanderzobnin** [comment]
Read this http://docs.grafana-zabbix.org/installation/
