### ISSUE TITLE
Missing Groups in group templating

### ISSUE THREAD

**Issue by menardorama** [alexanderzobnin/grafana-zabbix#316]
#### I'm submitting a ...
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?  4.02
- What Zabbix version are you using? 3.0.4
- What zabbix plugin version are you using? 3.1.2
- What OS are you running grafana on? Centos 6
- What did you do? Create a template variable and just put a (*) in the query field
- What was the expected result? It should disply all the groups in the drop down list
- What happened instead? I'm only having a few groups displayed

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Try to check access rights for your Zabbix api account (set in datasource config).
