### ISSUE TITLE
function "Time"

### ISSUE THREAD

**Issue by zfbfoxlly123** [alexanderzobnin/grafana-zabbix#319]
hi,I looked at http://docs.grafana-zabbix.org/reference/functions/, there is a function named "Time"
I'm using zabbix plugin with version 3.1.2，but there is no function "Time".
![func](https://cloud.githubusercontent.com/assets/17916697/21304095/dfde9636-c5fd-11e6-8b62-cf12bf1e45ea.png)

I would like to put the same item in different time periods of data placed in the same panel, how to do it?

**Comment by alexanderzobnin** [comment]
This function is in the master branch, but still not published on grafana.net. Will do that in few days.
