### ISSUE TITLE
no datapoints returned from metric query

### ISSUE THREAD

**Issue by yanzywang** [alexanderzobnin/grafana-zabbix#321]
I configured grafana and grafana-zabbix in the right way, but did not return data.

Grafana version : Version 4.0.2 (commit: v4.0.2)
Grafana-zabbix version: 3.1.2
Zabbix API version: 2.4.5

no datapoints returned from metric query

thank you

**Comment by alexanderzobnin** [comment]
Do you see any errors? Or just empty panel?

**Comment by rlljorge** [comment]
Hi, 

I have the same problem ...
In the default dashboard "Zabbix Server Dashboard" I don't receive any data only the message "No datapoints".
In the dashboard "Template Linux Server" I see my groups/hosts and the all graphs WORK PERFECTLY !

When I try add new graph I receive the error message:


target[p] is undefined

replaceTargetVariables/<@http://172.16.104.88:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1484000737476:563:15
replaceTargetVariables@http://172.16.104.88:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1484000737476:562:13
query/promises<@http://172.16.104.88:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1484000737476:234:15
l@http://172.16.104.88:3000/public/app/boot.85c49108.js:48:28969
Sg@http://172.16.104.88:3000/public/app/boot.85c49108.js:49:29676
query@http://172.16.104.88:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1484000737476:231:28
.execute/i</f.prototype.issueQueries@http://172.16.104.88:3000/public/app/boot.85c49108.js:42:19493
.execute/h</h.prototype.issueQueries@http://172.16.104.88:3000/public/app/boot.85c49108.js:18:27235
g@http://172.16.104.88:3000/public/app/boot.85c49108.js:38:29545
h/<@http://172.16.104.88:3000/public/app/boot.85c49108.js:38:29717
xc/this.$get</o.prototype.$eval@http://172.16.104.88:3000/public/app/boot.85c49108.js:39:5353
xc/this.$get</o.prototype.$digest@http://172.16.104.88:3000/public/app/boot.85c49108.js:39:3835
xc/this.$get</o.prototype.$apply@http://172.16.104.88:3000/public/app/boot.85c49108.js:39:5638
x/i<@http://172.16.104.88:3000/public/app/boot.85c49108.js:39:1804
f@http://172.16.104.88:3000/public/app/boot.85c49108.js:37:15602
jb/k.defer/c<@http://172.16.104.88:3000/public/app/boot.85c49108.js:37:17066

My versions are:

Zabbix 3.2.3
grafana-4.0.2
Granafa-zabbix 3.2.0

**Comment by alexanderzobnin** [comment]
@rlljorge can you show your query?

**Comment by alexanderzobnin** [comment]
@rlljorge @yanzywang see #329
