### ISSUE TITLE
API Request hangs forever if zabbix server is unavailable for a while

### ISSUE THREAD

**Issue by v-zhuravlev** [alexanderzobnin/grafana-zabbix#322]
#### I'm submitting a ...
- [x] Bug report
- [ ] Feature request
- [x] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
3.1.1
- What Zabbix version are you using?
2.4.6
- What zabbix plugin version are you using?
3.0.0
- What OS are you running grafana on?
Centos 7
- What did you do?
I'm using grafana dashboard with multiple singlestat panels in 'kiosk mode' that query zabbix datasource. Dashboard is set to be automatically updated every 5 mins using Grafana controls.
- What was the expected result?
Dashboard singlestat panels on dashboard shall be updated automatically. If zabbix server is currently unavailable - some kind of timeout shall be issued and stats shall switch to show `N/A` value. New update retry shall be according to schedule (ie. next 5 mins)
- What happened instead?
If zabbix server is unavailable then panels update just hangs. Rotating circle is shown for each single stat and never goes away. No update is possible even if zabbix server is back online. Only full page refresh `F5` solves the problem.

P.S. Thanks for this REALLY AWESOME integration that you have made

**Comment by alexanderzobnin** [comment]
Thanks! Try to update to latest version. This problem was fixed.

**Comment by v-zhuravlev** [comment]
Upgraded to grafana-zabbix 3.2.0 and yes that solves the issue.
Thanks
