### ISSUE TITLE
Datapoints outside time range

### ISSUE THREAD

**Issue by zfbfoxlly123** [alexanderzobnin/grafana-zabbix#323]
when I used Time function in one query metrics,it looks normal。but when I add another metrics and used time function,An “Datapoints outside time range” prompt appears。
Can the time function be used only once in the same graph?
I am using the latest version，3.2.0

![image](https://cloud.githubusercontent.com/assets/17916697/21383429/b1a2c96e-c7a0-11e6-96ca-2254b98b8bff.png)

**Comment by zfbfoxlly123** [comment]
I am using the latest version，3.2.0

**Comment by alexanderzobnin** [comment]
Yes, this is current limitation of timeShift() function. You can shift whole panel using Grafana _Time range_ tab.

**Comment by zfbfoxlly123** [comment]
I see,thanks
