### ISSUE TITLE
Host can not choose more than one

### ISSUE THREAD

**Issue by krisbai** [alexanderzobnin/grafana-zabbix#324]
#### I'm submitting a ...
- [√ ] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- Grafana version : v4.0.2
- Zabbix version : v3.2.1
- Zabbix plugin version :  v3.1.2 
- OS : Centos 6.5
- What did you do? :  choose host view
- What was the expected result? ：We can also select multiple hosts
- What happened instead? ：Host can not choose more than one

![qq 20161222121219](https://cloud.githubusercontent.com/assets/10414888/21414996/031fa9c0-c840-11e6-959a-b5be221be64b.png)

**Comment by alexanderzobnin** [comment]
You should use *Multi-value* variable, http://docs.grafana-zabbix.org/guides/templating/#creating-variable

**Comment by krisbai** [comment]
ok ,ths!
