### ISSUE TITLE
Grafana 4.0 issue with singlestat text not showing a text metric from Zabbix

### ISSUE THREAD

**Issue by jmaitrehenry** [alexanderzobnin/grafana-zabbix#325]
#### I'm submitting a ...
- [x] Bug report

Grafana version : Version 4.0.2 (commit: v4.0.2)
Grafana-zabbix version: 3.2.0
Zabbix version: 3.2.1 

I add a SingleSat Panel with a text metric on Zabbix, if I use the General - Host Name metric, it works as expected, if I use some other text metric, it show no result.

I made a Table panel with the same metric as the SingleStat and with the same "aggregation" (current):
<img width="716" alt="screen shot 2016-12-27 at 4 54 49 pm" src="https://cloud.githubusercontent.com/assets/593562/21509326/d6afe778-cc55-11e6-9407-0c20e318d991.png">
  The table works but not the singlestat, I don't know if it's a bug with the Zabbix plugin or the Singlestat plugin.

One item from the chrome console: `{itemid: "25528", clock: "1482875218", value: "petalmd", ns: "734248728"}`

Thanks!

**Comment by alexanderzobnin** [comment]
Looks strange, it works on my public instance: http://play.grafana-zabbix.org/dashboard/db/text-metrics (Grafana 4.0.2)

**Comment by alexanderzobnin** [comment]
Can you show your SingleStat query?

**Comment by jmaitrehenry** [comment]
Request payload:
```
{"jsonrpc":"2.0","method":"history.get","params":{"output":"extend","history":"4","itemids":["25528"],"sortfield":"clock","sortorder":"ASC","time_from":1483465926,"time_till":1483469526},"id":1,"auth":"xxxxx"}
```

The singlestats json:
```
{
  "cacheTimeout": null,
  "colorBackground": false,
  "colorValue": false,
  "colors": [
    "rgba(245, 54, 54, 0.9)",
    "rgba(237, 129, 40, 0.89)",
    "rgba(50, 172, 45, 0.97)"
  ],
  "datasource": "Zabbix",
  "editable": true,
  "error": false,
  "format": "none",
  "gauge": {
    "maxValue": 100,
    "minValue": 0,
    "show": false,
    "thresholdLabels": false,
    "thresholdMarkers": true
  },
  "id": 8,
  "interval": null,
  "links": [],
  "mappingType": 1,
  "mappingTypes": [
    {
      "name": "value to text",
      "value": 1
    },
    {
      "name": "range to text",
      "value": 2
    }
  ],
  "maxDataPoints": 100,
  "nullPointMode": "connected",
  "nullText": null,
  "postfix": "",
  "postfixFontSize": "50%",
  "prefix": "",
  "prefixFontSize": "50%",
  "rangeMaps": [
    {
      "from": "null",
      "text": "N/A",
      "to": "null"
    }
  ],
  "span": 2,
  "sparkline": {
    "fillColor": "rgba(31, 118, 189, 0.18)",
    "full": false,
    "lineColor": "rgb(31, 120, 193)",
    "show": false
  },
  "targets": [
    {
      "alias": "Cluster name",
      "application": {
        "filter": "Elasticsearch",
        "name": "Elasticsearch"
      },
      "downsampleFunction": {
        "name": "avg",
        "value": "avg"
      },
      "errors": {},
      "functions": [],
      "group": {
        "filter": "ElasticSearch",
        "groupid": "11",
        "name": "ElasticSearch"
      },
      "hide": false,
      "host": {
        "filter": "$Server",
        "name": "$Server",
        "templated": true
      },
      "item": {
        "filter": "Cluster name",
        "name": "Cluster name"
      },
      "mode": 2,
      "options": {
        "showDisabledItems": false
      },
      "refId": "A",
      "useCaptureGroups": false
    }
  ],
  "thresholds": "",
  "title": "Cluster name",
  "type": "singlestat",
  "valueFontSize": "80%",
  "valueMaps": [],
  "valueName": "current"
}
```

**Comment by alexanderzobnin** [comment]
Hm, have no ideas...

**Comment by jars99** [comment]
I am having this issue as well.  I even upgraded grafana from 4.0.2 to 4.2, and am still seeing it.  Just like the original poster, it works with a table, but not on a singlestat.  The zabbix plugin version is 3.3.0.

**Comment by jars99** [comment]
Ah - I just found a workaround.  I had "max data points" set to 1.  If I delete that, then the text shows up correctly.  
I discovered this when I set my "max data points" for the table to 5, and suddenly it started saying "NaN" as the result.

**Comment by alexanderzobnin** [comment]
That's really strange. I'll try to find a reason.

**Comment by tatianab85** [comment]
Hi, 
I had the same exact problem, if I make a Table panel with the same metric (text) as the SingleStat it shows the system name and description but it wasn't working with single stats, it showed NaN, after trying differents values for "max data points" I found a solution setting it up to 1000, leave it in auto didn't work.

**Comment by fabio-santos-movile** [comment]
Same here... some items works as well, but other not.
the item type is character, but result return null.

**Comment by alexanderzobnin** [comment]
I should remove post processing (max data points - related) from text metrics. Because if number of points > max data points, plugin tries to reduce it using average and for strings, it returns NaN, of course.

**Comment by zakthan** [comment]
Hi I have the exact problem for plugin 3.8.1.
zabbix 2.4 and grafana 4.3.0
I have an item which returns a string at zabbix.
When I create a singlestat at grafana I get N/A

**Comment by alexanderzobnin** [comment]
@zakthan N/A isn't the same as NaN. So I think, it's a different issue.

**Comment by zakthan** [comment]
Hi Alexander,
upgraded to grafana 5.3.4 and now works fine.
Thanks.
