### ISSUE TITLE
Zabbix Trigger Panel - Unable to filter only by application (eg "CPU")

### ISSUE THREAD

**Issue by c3c0st4** [alexanderzobnin/grafana-zabbix#327]
#### I'm submitting a ...
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
**4.0.2**
- What Zabbix version are you using?
**3.2.1**
- What zabbix plugin version are you using?
**3.2.0**
- What OS are you running grafana on?
**CENTOS 7.0 64bits**
- What did you do?
**Tried to create zabbix trigger panel to show only incidents from a given "application" (eg "CPU")**
- What was the expected result?
**The panel should show incidents from a given "application" (eg "CPU")**
- What happened instead?
**The panel shows nothing but in Zabbix I can see the incidents with the same filter**

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Fixed in 3.2.1
