### ISSUE TITLE
Question about data gathering from zabbix server

### ISSUE THREAD

**Issue by mappsys** [alexanderzobnin/grafana-zabbix#328]
Hi, i've a grafana and zabbix servers on the same high speed network, when a grafana dashboard is loaded on client's browser, all the zabbix data is transferred direct from zabbix to the browser to render the dashboard! Is there any chance to process the data on grafana server and them push the dashboard to the browser? Frequently we've to access the data from low speed connections and the zabbix api returns 2 to 3 MB of data to be processed and because of the delay/speed the dashboards loads very slowly.

the solution is very good and helps a lot for sharing.

Thanks in advance!

**Comment by alexanderzobnin** [comment]
@mappsys It's by-design problem - plugin works on client side. Backend plugins is one of the most helpful feature which allow to fix this problem. But I don't sure when it will done.
