### ISSUE TITLE
No data is displayed

### ISSUE THREAD

**Issue by bentzys** [alexanderzobnin/grafana-zabbix#329]
#### I'm submitting a ...
- [ ] Question / Support request

Information:
- Grafana version: 4.0.2-1481203731
- Zabbix version: zabbix-frontend-php 1:3.0.6-1+xenial
- zabbix plugin version: 3.2.0
- OS: Ubuntu 16.04.1 LTS - Xenial

I've configured a new DS as following:

![ds](https://cloud.githubusercontent.com/assets/1905243/21748991/78eb0dd4-d59c-11e6-80a6-5cc07d70d993.jpeg)

Connection test passed.
At zabbix server everything seems OK.

No log errors:

ubuntu@ip-10-150-1-29:~$ sudo systemctl status grafana-server
● grafana-server.service - Grafana instance
   Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-01-08 10:12:45 UTC; 33s ago
     Docs: http://docs.grafana.org
 Main PID: 8270 (grafana-server)
    Tasks: 7
   Memory: 8.6M
      CPU: 102ms
   CGroup: /system.slice/grafana-server.service
           └─8270 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile= cfg:default.paths.logs=/var/log/grafana

Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Skipping migration condition not 
Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Executing migration" logger=migra
Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Skipping migration condition not 
Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Starting plugin search" logger=pl
Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Registering plugin" logger=plugin
Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Registering plugin" logger=plugin
Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Registering plugin" logger=plugin
Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Initializing Alerting" logger=ale
Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Initializing CleanUpService" logg
Jan 08 10:12:45 ip-10-150-1-29 grafana-server[8270]: t=2017-01-08T10:12:45+0000 lvl=info msg="Initializing HTTP Server" logger=
lines 1-21/21 (END)

![nodata](https://cloud.githubusercontent.com/assets/1905243/21748992/81f34c48-d59c-11e6-9b20-97dc359bbb65.jpeg)

*NO DATA IS DISPLAYED*

Did I something wrong?

Thanks in advance,
--bentzy

**Comment by alexanderzobnin** [comment]
@bentzys try to use `proxy` mode instead direct.

**Comment by bentzys** [comment]
Thank you, but same result. Test passed but no data displayed.
How can I debug the issue? where to look for?

**Comment by bentzys** [comment]
So it seems is the same bug as #321. "Template Linux Server" works OK.

**Comment by alexanderzobnin** [comment]
Try to edit this dashboard. May be your Zabbix server have another name.

**Comment by bentzys** [comment]
Please explain. I only see at Settings -> General -> Details -> name the name of the dashboard, not the server name.  I tried now changing at the data source the url by using (fqdn || ip || hostname) *  ( proxy || direct ).
Same issue. Thanks.

**Comment by alexanderzobnin** [comment]
I mean host name in panel config. For example, click on CPU panel, choose edit and try to change Host name.

**Comment by bentzys** [comment]
Great. It works. Thank you!
Good job.
