### ISSUE TITLE
Table query mode by text dosn't display host name

### ISSUE THREAD

**Issue by xiaoxue999** [alexanderzobnin/grafana-zabbix#330]
I used the text query to see the OSver item by muti hosts,Is the first col can displayed the host name like the metrics query ?
![1](https://cloud.githubusercontent.com/assets/22721577/21794207/2ff0c0b8-d733-11e6-8e23-383181bb30d5.png)
![2](https://cloud.githubusercontent.com/assets/22721577/21794453/63d0d97a-d735-11e6-9c8d-4a75ac151a76.png)

**Comment by xiaoxue999** [comment]
metrics query mode was good by uptime item.

![3](https://cloud.githubusercontent.com/assets/22721577/21794623/d3fbeaa4-d736-11e6-812a-d9dd05c79245.png)

**Comment by alexanderzobnin** [comment]
Now it isn't possible, but I want to add table mode support, which allows to choose columns to view.
