### ISSUE TITLE
Templating: template variables could not be initialized: metrics is undefined

### ISSUE THREAD

**Issue by billbatista** [alexanderzobnin/grafana-zabbix#331]
#### I'm submitting a ...
- [x] Bug report

#### For bug report please include this information:
- What Grafana version are you using? **4.1.1**
- What Zabbix version are you using? **2.4.7**
- What zabbix plugin version are you using? **3.2.0**
- What OS are you running grafana on? **CentOS 6.8**
- What did you do? **Updated Grafana and every plugin I had installed**
- What was the expected result? 
- What happened in stead?

After installing a few updates, I can't do templating with Zabbix anymore. If I try to create a new templating, I get this error message:
![image](https://cloud.githubusercontent.com/assets/6979278/21927613/26c11964-d965-11e6-8e9e-c459fb54a1c9.png)

I have Zabbix as my default source: 
![image](https://cloud.githubusercontent.com/assets/6979278/21927655/4f518210-d965-11e6-912d-c4addaf8e67a.png)

This is the templating screen:
![image](https://cloud.githubusercontent.com/assets/6979278/21927738/c9bfd858-d965-11e6-9608-7bf2ba769cdd.png)

Previous configured templatings are still working, but if I try to chage something I will show this error too.

**Comment by alexanderzobnin** [comment]
Try to use `*` wildcard: `Servers.*`

**Comment by wmbzz** [comment]
@alexanderzobnin yep, it's working using the wildcard. Was this changed in someway? Nonetheless, thanks!
