### ISSUE TITLE
Can tables displayed  group by host ?

### ISSUE THREAD

**Issue by xiaoxue999** [alexanderzobnin/grafana-zabbix#332]
Metrics Example ：
A Query mode = cpu user time
B Query mode =  uptime
C query mode = ......and more items.
Can Tables displayed  group by host like this ?

hostA   30%    20days
hostB   10%    60days
......more and more

I choice the Table Transform to the Annotations or Table ,but can't set the Columns.

**Comment by alexanderzobnin** [comment]
Duplicated by #282
