### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by evandro-portugal** [alexanderzobnin/grafana-zabbix#334]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [X] Question / Support request

Ok, so... @alexanderzobnin  I see that now the plugin have 2 repositories, this one and one called grafana-zabbix-app, which one should I use to pull a change? I ask this because I got confused, I can see it clearly that this one is not being updated, and I have done some owkr on the code that was on my machine, the one that I download directly from grafana.net, and for my surprise when trying to pull the changes, the code is a LOT different from this repository. So, how should I proceed to commit a change?

**Comment by alexanderzobnin** [comment]
This repo contains only source code. `grafana-zabbix-app` contains builded plugin for publishing. So all contributions must be here, in main repo.
