### ISSUE TITLE
Bulk add metric queries into table panel

### ISSUE THREAD

**Issue by petercelentano** [alexanderzobnin/grafana-zabbix#335]
I'm submitting a question pertaining to adding many metric queries into a table panel (without needing to manually add them all individually).  Specifically, I am using zabbix/pg_monz to monitor several postgresql databases, and I'm making a panel that contains table size information for all tables across multiple databases.  All of this information is available as individual data points in zabbix, but is there a way that I can add all of these tables into grafana without manually adding them individually (using templating/variables)?

Thank you for your ideas!

**Comment by alexanderzobnin** [comment]
Try to use regex: http://docs.grafana-zabbix.org/guides/gettingstarted/
