### ISSUE TITLE
Using 2 timeshift graphs (24d and 7d) gives Datapoints outside time range

### ISSUE THREAD

**Issue by gschaden** [alexanderzobnin/grafana-zabbix#338]
#### I'm submitting a ...
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
 Grafana v4.1.0-beta1
- What Zabbix version are you using?
2.2.14
- What zabbix plugin version are you using?
3.2.0
- What OS are you running grafana on?
Linux Centos 6.8
- What did you do?
- What was the expected result?
Having 3 graphs (todays stats, yesterday and a week ago)
- What happened instead?
Datapoints outside time range
![2017-01-22 13_17_14-skype 3 - gerhard schaden](https://cloud.githubusercontent.com/assets/203599/22182409/310865de-e0a5-11e6-8011-66e942691f1d.png)

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Yes, it's known bug. Thanks for report.

**Comment by hugo-cisneiros-movile** [comment]
Hi there, I'm getting this bug too. Is there anything I can do to help with this issue? :)
