### ISSUE TITLE
Submitting Acknowledges from Zabbix trigger panel

### ISSUE THREAD

**Issue by cod3poet** [alexanderzobnin/grafana-zabbix#340]
#### I'm submitting a ...
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using? v4.1.1
- What Zabbix version are you using? Zabbix 3.2.3
- What zabbix plugin version are you using? 3.2.0
- What OS are you running grafana on? Centos 7.2
- What did you do? Click the Ack speech bubble, then the Plus sign entered text and clicked the acknowledge button
- What was the expected result? Dialog closes and ack gets forwarded to zabbix ui updates and shows acknowledged status for alert.
- What happened instead? 
UI does nothing error in console for IE, FF, and Chrome

![image](https://cloud.githubusercontent.com/assets/9358716/22302338/4648f310-e2fc-11e6-90b7-595f50b3492b.png)

![image](https://cloud.githubusercontent.com/assets/9358716/22302363/7513cf4e-e2fc-11e6-9aa6-8895073b80a6.png)

![image](https://cloud.githubusercontent.com/assets/9358716/22302367/77f86706-e2fc-11e6-86b8-e5b0923482d8.png)

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by losintox** [comment]
Same config, same issue.

Thx

**Comment by alexanderzobnin** [comment]
@cod3poet @losintox can you show your Trigger Panel editor? Try to choose _Data source_ (not default).

**Comment by cod3poet** [comment]
Certainly Mon1 is currently our Zabbix 3.2.3 server
![image](https://cloud.githubusercontent.com/assets/9358716/22534882/428ab168-e8c5-11e6-88c5-c90721a3b6f4.png)

**Comment by alexanderzobnin** [comment]
Seems, I fixed this here 8f565ac730eac1cb6134c33c832b13e104793978 I will publish new version in next few days.
