### ISSUE TITLE
Log Item

### ISSUE THREAD

**Issue by Samvine** [alexanderzobnin/grafana-zabbix#341]
Question / Support request

I would like to set up a table with log data from a monitored windows host.

I get the data in Zabbix, no problem. I got something like this : 

In grafana, I found them when I set the querry in "Text" mode.
[zabbix view](http://imgur.com/a/ECyk8)
The bad thing is that I can't retrieve all the column, like EventID. 
[grafana view](http://imgur.com/a/eSpVo)

Is it a limitation of Zabbix API ?

Thanks 
Samvine

**Comment by alexanderzobnin** [comment]
It's plugin limitation. I should add table mode support.
