### ISSUE TITLE
Problem with configuring Zabbix Data Source

### ISSUE THREAD

**Issue by elkoralish** [alexanderzobnin/grafana-zabbix#343]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [x ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using? 
   grafana-4.1.1-1484211277.x86_64
- What Zabbix version are you using? 
   Zabbix 3.2.3
- What zabbix plugin version are you using?
   3.2.1
- What OS are you running grafana on?
   CentOS release 6.8 (Final)
- What did you do?
   Datasource Setup
- What was the expected result?
   Login
- What happened instead?
   Error

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

Problem connecting zabbix data source.
I'm sorry to bother you with something that seems trivial, but I'm having an issue here and have nearly exhausted all my avenues of local troubleshooting.  
I'm pretty sure the url is correct with:  _http://ipaddress/zabbix/api_jsonrpc.php_ 
If I change it I do get a cannot connect message
I'm simply unable to connect with the api and get "Login name or password is incorrect." when I hit Save & Test.  User is LDAP through zabbix, works for the fronted, and is a zabbix-super-admin

Dev-Tools reports:

**Request payload:**
_{"jsonrpc":"2.0","method":"user.login","params":{"user":"YYYYY.XXXXXXX@ZZZZZZZZZ.com","password":"PPPP####"},"id":1}_
**Response:**
_{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params.","data":"Login name or password is incorrect."},"id":1}_

zabbix/grafana are on the same machine, I've tried both direct and proxy connections to no avail
any help troubleshooting would be GREATLY appreciated, I've tried all permutations here and I don't seem to be getting anywhere

-C

**Comment by elkoralish** [comment]
the only thing I see wrong with that request is the lack of an Auth: null per the zabbix docs:

{
    "jsonrpc": "2.0",
    "method": "user.login",
    "params": {
        "user": "Admin",
        "password": "zabbix"
    },
    "id": 1,
    "auth": null
}

if that matters

**Comment by elkoralish** [comment]
Scratch this issue, it's resolved.  My fault (a miscommunication between a coworker and I about which zabbix instance was live).
sigh
nothing to see here, thanks for the time I'm sure you would have given.

-C

**Comment by alexanderzobnin** [comment]
Hi, @elkoralish 
Just found this on zabbix forum:

 > Just to clarify, the AD format for the user name:
> user => "cn=zabbixusr,cn=Users,dc=domain,dc=com" ,
> 
> is not needed and this works fine when using LDAP
> user => "zabbixusr" ,
https://www.zabbix.com/forum/showthread.php?t=46588

So try to use
```
{"user":"YYYYY.XXXXXXX","password":"PPPP####"},"id":1}
```

**Comment by alexanderzobnin** [comment]
@elkoralish no problem
