### ISSUE TITLE
Annotation feature request: Allow items as well as triggers 

### ISSUE THREAD

**Issue by thechile** [alexanderzobnin/grafana-zabbix#344]
Hi

From what i can tell, only triggers are currently usable for annotations. Are there any plans to allow item values to be used as well ? 

For example if i have metric that tracks disk usage, web server connection count etc.. and i have a line graph in Grafana to visualize this data for 24 hour period. I would like to have an annotation that identifies when the peak usage during the last 24 hours occurred. So in zabbix i can have a calculated item to track this value such as `item.key.max(24h)` but currently I can't plot it in grafana. 

Also, on side note.. can the annotation popup show the value as well as datestamp. Saves having to hover over annotation for when, and then over the graph at corresponding time stamp for exact value. 

many thanks

**Comment by alexanderzobnin** [comment]
@thechile Hi! I don't sure about calculated item - which time stamp will be returned? And about annotations from triggers - it shows trigger's message, so you can add {ITEM.VALUE} to trigger text if you want to see value.

**Comment by thechile** [comment]
OK, time stamp is a problem since it doesn't reflect when the max() occurred, just the time of query. 

Can you think of another way to add this feature ? I believe the only way to add a vertical line is via the annotation feature in Grafana. Can't think of a simple way to get a peak value during specified time period other than API call for timespan and sort by result and take highest result.

**Comment by alexanderzobnin** [comment]
Have no ideas how to implement this.
