### ISSUE TITLE
no data points

### ISSUE THREAD

**Issue by sungy2014** [alexanderzobnin/grafana-zabbix#347]
zabbix-server 3.0.7
grafana latest
grafana-zabbix latest

![image](https://cloud.githubusercontent.com/assets/13880412/22746593/407ccd94-ee5f-11e6-9c10-dae96bcfa773.png)
![image](https://cloud.githubusercontent.com/assets/13880412/22746629/6171100a-ee5f-11e6-97d9-2e3613a26fc1.png)

but this dashboard can see cpu, network
![image](https://cloud.githubusercontent.com/assets/13880412/22746738/d335800e-ee5f-11e6-9edb-88a832261264.png)

**Comment by alexanderzobnin** [comment]
In Zabbix Server Dashboard check zabbix server name. I use default (Zabbix server), but you may have another.

**Comment by sungy2014** [comment]
![image](https://cloud.githubusercontent.com/assets/13880412/22786592/182da4fc-ef14-11e6-813b-b056fed469ab.png)
do you mean i should change this name to my hostname?

**Comment by sungy2014** [comment]
![image](https://cloud.githubusercontent.com/assets/13880412/22787294/bdb48aba-ef16-11e6-84fd-4ccd52b9b495.png)
click on the cpu panel to edit
i got it!

**Comment by fengerzh** [comment]
I got it! You have to change the host name to "display name", not "host name" on Zabbix server.
