### ISSUE TITLE
Cannot get data from zabbix

### ISSUE THREAD

**Issue by askretov** [alexanderzobnin/grafana-zabbix#350]
- [x] Bug report
- grafana 4.1.1
- zabbix 3.2.3
- zabbix plugin 3.2.1
- CentOS 7

Trying to get metrics from zabbix, but getting an error on every value change in Group/Host/App...etc
![ice_screenshot_20170209-201031](https://cloud.githubusercontent.com/assets/14355362/22778991/b4458720-ef04-11e6-899c-c750e9dc524a.png)
![ice_screenshot_20170209-201042](https://cloud.githubusercontent.com/assets/14355362/22778992/b4481b5c-ef04-11e6-9419-df8db3df5b71.png)

**Comment by askretov** [comment]
@alexanderzobnin Hi, Alex! Are there any news on this bug?

**Comment by alexanderzobnin** [comment]
@askretov This bug should be fixed in master, but haven't released yet. You can try to upgrade from mater branch if that's critical issue for you.
