### ISSUE TITLE
Macro(variable) was not supported?

### ISSUE THREAD

**Issue by xiaoxue999** [alexanderzobnin/grafana-zabbix#353]
![1](https://cloud.githubusercontent.com/assets/22721577/22814066/7e5b4fe6-ef8b-11e6-85ad-b24eedb27d7c.jpg)

![2](https://cloud.githubusercontent.com/assets/22721577/22814080/8f3ed13e-ef8b-11e6-853c-180619959e67.jpg)

**Comment by xiaoxue999** [comment]
In the zabbix setting like this:
Template:
![5](https://cloud.githubusercontent.com/assets/22721577/22814275/1fbdc246-ef8d-11e6-8fb9-8234540230ad.jpg)

Host Macros 
![3](https://cloud.githubusercontent.com/assets/22721577/22814227/b843ef64-ef8c-11e6-953f-44145a12cbb1.jpg)

Last data display was ok:
![4](https://cloud.githubusercontent.com/assets/22721577/22814228/b8c71d80-ef8c-11e6-85c9-c1888a3cbcf0.jpg)

**Comment by alexanderzobnin** [comment]
Duplicated, #212 , closed by 48018744bddbf5d644b0bfcb5c144119e5697ec5
