### ISSUE TITLE
Templating Init Failed - Cannot Read Property 'map' of undefined

### ISSUE THREAD

**Issue by chancerollins** [alexanderzobnin/grafana-zabbix#354]
#### I'm submitting a ...
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using? 4.1.1
- What Zabbix version are you using? 3.2.3
- What zabbix plugin version are you using? 3.3.0
- What OS are you running grafana on? Centos 7
- What did you do? Open multiple Dashboards that have templates
- What was the expected result? I expected to see my dashboard with the ability to utilize templates to switch between servers.
- What happened instead? Templating error was displayed.

I wasn't sure if it was a grafana or plugin issue but if I roll back to plugin 3.1.2 I do not receive errors with the dashboards and templates I have.  It is not just with 3.3.0 either.  The last release before today did it as well.  Additionally if I use the "Template Linux Server" dashboard you provide I don't have issues with templating.  If there is anything I can provide for information to help just let me know.

![grafanaerror](https://cloud.githubusercontent.com/assets/17365605/22841504/dfcf3a4e-ef9f-11e6-8c06-e26827180192.png)

**Comment by alexanderzobnin** [comment]
Can you confirm that only 3.3 and 3.2 versions are affected?

**Comment by chancerollins** [comment]
Just confirmed the issue with 3.2, 3.2.1 and 3.3.  I noticed it back with 3.2.1 and thought the next release might fix it.  Anything else you need let me know.

**Comment by alexanderzobnin** [comment]
@chancerollins no, I've just fixed it. That will be in next release.

**Comment by chancerollins** [comment]
Thanks for the quick fix.  Looking forward to the next release.
