### ISSUE TITLE
Toggle header on trigger list - Feature request

### ISSUE THREAD

**Issue by Emusp** [alexanderzobnin/grafana-zabbix#356]
Would be nice to get the possibility to toggle the table header on/off on the trigger list, to get a cleaner look.

Thanks for a great plugin.

**Comment by alexanderzobnin** [comment]
Closed due to panel redesign

![screenshot from 2017-12-14 19-42-09](https://user-images.githubusercontent.com/4932851/34003649-e5620b40-e106-11e7-9dd0-3d5689c1423e.png)
