### ISSUE TITLE
Ability to use Variables in Filters (regex)

### ISSUE THREAD

**Issue by endzyme** [alexanderzobnin/grafana-zabbix#36]
Would be nice to be able to use custom template variables in the search filter section so you can graph multiple items and not just have to select one item from a dropdown.

**Comment by alexanderzobnin** [comment]
Yes, this is a good idea. Can you describe your case in detail?

**Comment by endzyme** [comment]
Sure thing! Here's the use case: 

Today: We currently have a template dashboard that shows information about VPN servers. We'd like to be able to select multiple hosts instead of just a single host. [1]

This could be achieved by setting up a custom variable [2] and then selecting `All` on hosts and using the regexp filters [3].

Firstly there are obvious escaping problems (to avoid using `$` as `EOL`) so that would have to be considered. 

As an aside: this is a great plugin and truly augments visual data where zabbix's UI falls short - huge thank you and I owe you :beers:. 

Image Ref [1]
![screen shot 2015-07-01 at 2 51 05 pm](https://cloud.githubusercontent.com/assets/1903525/8464766/e83beca0-2001-11e5-8367-00e38386bab0.png)

Image Ref [2]
![screen shot 2015-07-01 at 2 51 39 pm](https://cloud.githubusercontent.com/assets/1903525/8464804/439f495c-2002-11e5-834d-3c9732c51f5b.png)

Image Ref [3]
![screen shot 2015-07-01 at 2 52 03 pm](https://cloud.githubusercontent.com/assets/1903525/8464808/493db84e-2002-11e5-88a8-248941a56818.png)

**Comment by alexanderzobnin** [comment]
I will add this feature in 2.1 plugin release. I need some consideration about how to use variables in regex. May be global option for the panel to enable this feature.

**Comment by alexanderzobnin** [comment]
Thanks for gratitude! Grafana is a really cool dashboard! Hope, this helps Zabbix became better.

**Comment by jbfavre** [comment]
can't wait for this feature too :)

Got many supervisord workers to monitor.
I got one Zabbix item per worker status (STOPPED, RUNNING, STARTING, FATAL, EXITED, ..).
I would like to automatically filter items to keep only those concerning a specific worker.

**Comment by alexanderzobnin** [comment]
@endzyme, @jbfavre Ok, I will add this feature very soon.

**Comment by alexanderzobnin** [comment]
Resolved. Now in [develop](https://github.com/alexanderzobnin/grafana-zabbix/tree/develop) branch.

**Comment by jbfavre** [comment]
Just pushed it on my server.... just works :)
Many thanks :+1: :+1:

**Comment by mingmings** [comment]
cool feature，like it~

**Comment by endzyme** [comment]
+1 thanks!
