### ISSUE TITLE
Hide/show panels based  on host?

### ISSUE THREAD

**Issue by exwizzard** [alexanderzobnin/grafana-zabbix#360]
#### I'm submitting a ...
- [x ] Question / Support request

The default dashboard that comes with this plugin includes groups and host which I can select. 
My problem is that I want to hide certain panels depending on which host I select. 
For example when I select my web server host I want to show my apache and email stats panel but when I select any other host I don't want to show these panels.

**Comment by alexanderzobnin** [comment]
That's not impossible now.
