### ISSUE TITLE
Add text color controls to Trigger Panels

### ISSUE THREAD

**Issue by eraffaelli** [alexanderzobnin/grafana-zabbix#361]
#### I'm submitting a ...
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

Hello,
First, a big thanks for your work on this plugin ;)

I'm using latest grafana-zabbix plugin and following #351 I would like to ask if you could add the possibility to change de color of the trigger text that is on the background colored rows (issue). Eventually to be able to "bold" it too would be nice.

This text :
![zabbix](https://cloud.githubusercontent.com/assets/16799390/23217922/0d6f3cd6-f91b-11e6-9f75-e7739ff7712b.PNG)

Thanks again,

Cheer.
E.R

**Comment by Gmatoy** [comment]
I found the line in CSS code on the page, but i can't find the css code on the aplication machine to alter this.
If i change the color #f4f5f8 to #000000 it stays black, but i can't save on css web browser editor, do you know where is the grafana primal css file?
We need this so much, our screen is hard to see the letters in white from far away (the room is big)
```
.triggers-panel-table {
  width: 100%;
  border-collapse: collapse; }
  .triggers-panel-table th {
    padding: 0; }
    .triggers-panel-table th:first-child .triggers-panel-table-header-inner {
      padding-left: 15px; }
  .triggers-panel-table td {
    padding: 0.45em 0 0.45em 1.1em;
    border-bottom: 2px solid #141414;
    border-right: 2px solid #141414; }
    .triggers-panel-table td:first-child {
      padding-left: 15px; }
    .triggers-panel-table td:last-child {
      border-right: none; }
  .triggers-panel-table .zbx-field-colored {
    color: **#f4f5f8;** }
  .triggers-panel-table .zbx-description-icon {
    float: right;
    padding-right: 8px;
    color: #f4f5f8; }
```
http://******:3000/public/plugins/alexanderzobnin-zabbix-app/css/grafana-zabbix.dark.css?bust=1503337556616

where is this css file?

**Comment by alexanderzobnin** [comment]
@Gmatoy compiled CSS are here: https://github.com/alexanderzobnin/grafana-zabbix/blob/master/dist/css/grafana-zabbix.dark.css

**Comment by Gmatoy** [comment]
in the beggining of the month, you was planning to implement this, right?

**Comment by alexanderzobnin** [comment]
This was implemented, but triggers panel is redesigned absolutely, so this doesn't make sense now

![screenshot from 2017-12-20 17-48-27](https://user-images.githubusercontent.com/4932851/34212653-0399699a-e5ae-11e7-99fd-ab1aaf78adfc.png)
![screenshot from 2017-12-20 17-48-01](https://user-images.githubusercontent.com/4932851/34212654-03b89568-e5ae-11e7-8eff-6b5c858938d5.png)
