### ISSUE TITLE
Trends time period  

### ISSUE THREAD

**Issue by yurilaaziz** [alexanderzobnin/grafana-zabbix#364]
#### I'm submitting a ...
- [ x ] Feature request

I am using grafana-Zabbix 3.3 and when the Trends is activated, It's impossible to Zoom in to get history before the trend period (7d by default)
I think it's better to add a feature that use trends only if the selected period is greater than a Trend Window. 

I changed directly he dist/datasource-zabbix/datasource.js : 229, 
```
            var useTrendsFrom = Math.ceil(dateMath.parse('now-' + this.trendsFrom) / 1000);
            var windowTrends = Math.abs(Math.ceil(dateMath.parse('now') / 1000) - useTrendsFrom);
            var useTrends = (Math.abs(timeTo - timeFrom ) > windowTrends) && this.trends;

```
More than that
it's better to have this feature by dashboard/Metric, 
for example, Per Metric, enable Trend or history and choose the time period .   

Thanks

**Comment by alexanderzobnin** [comment]
Yes, you're right, datasource should use trends only for range wider than trend period. I can add option like _trend range_, and allow to control trend usage more flexibly.

**Comment by yurilaaziz** [comment]
@alexanderzobnin  Do you want to fix it and send a PR  ?
