### ISSUE TITLE
Huge data graph display crashed..

### ISSUE THREAD

**Issue by xiaoxue999** [alexanderzobnin/grafana-zabbix#365]
#### I'm submitting a ...
- [*] Bug report
#### For bug report please include this information:
- What Grafana version are you using?
4.1.2
- What Zabbix version are you using?
3.2.1
- What zabbix plugin version are you using?
none
- What OS are you running grafana on?
RHEL6.2 x64

Zabbix has collected a hug data with 'cpu process %', although the data may be wrong, but the zabbix display is normal.
testing:
I selected the time range: 'now-6h to now'. the graph display was crashed.  
In time range: 'now-8h to now-3h' was ok, no more than 6hours...

![1](https://cloud.githubusercontent.com/assets/22721577/23780356/56c2dcae-0581-11e7-9f93-75a4e8c7f06f.jpg)
![0](https://cloud.githubusercontent.com/assets/22721577/23780362/7174a99c-0581-11e7-9204-b046001c9202.jpg)
![4](https://cloud.githubusercontent.com/assets/22721577/23780379/9093a6e8-0581-11e7-86a6-7c54cc550601.jpg)
![2](https://cloud.githubusercontent.com/assets/22721577/23780388/a5dbb4dc-0581-11e7-8e95-fcb51b861504.jpg)
![3](https://cloud.githubusercontent.com/assets/22721577/23780416/c9aa162e-0581-11e7-84e7-321f29a40af3.jpg)

**Comment by xiaoxue999** [comment]
Another error code by 50 hosts and last 6 hours....
![1](https://cloud.githubusercontent.com/assets/22721577/24693194/fb870048-1a0e-11e7-859e-5b1b6920b7d5.png)

**Comment by alexanderzobnin** [comment]
@xiaoxue999 can you try to reproduce this bug with a latest version of plugin?

**Comment by xiaoxue999** [comment]
@alexanderzobnin yes,it have been fixed in the 3.4.0,but there was occasional connection errors ,i think it may be a php plantform problem.
![1](https://user-images.githubusercontent.com/22721577/27523501-20c03bcc-5a60-11e7-86f8-9633323c64cf.jpg)

**Comment by alexanderzobnin** [comment]
@xiaoxue999 yes, try to check PHP logs and increase PHP memory.
