### ISSUE TITLE
Trigger panel "sort by" function

### ISSUE THREAD

**Issue by zalums** [alexanderzobnin/grafana-zabbix#367]
#### I'm submitting a ...
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using? - Version 4.1.1 (commit: v4.1.1)
- What Zabbix version are you using? - zabbix_server (Zabbix) 3.2.3
- What zabbix plugin version are you using? - 3.3.0
- What OS are you running grafana on? - Oracle Linux Server release 7.3
- What did you do? - I want to sort triggers in "trigger panel"
- What was the expected result? - option to sort (for example by trigger name or latest change)
- What happened instead? - not able to

**Comment by alexanderzobnin** [comment]
Was implemented  - sort by severity or last change.
