### ISSUE TITLE
Graph and data issue

### ISSUE THREAD

**Issue by koto137** [alexanderzobnin/grafana-zabbix#37]
Dear Alex,

first of all thank you for bringing zabbix to grafana, it is a great way for me to show managers monitoring dashboard which is cleaner and nicer then zabbix.

I write you because today I've upgraded to newest version after a month or so. And when I try to display IN and OUT traffic on one of my WIFI AP, the legend on the right say some other data then it really shows.. and IN and OUT traffic almost match. I've cleared cache in my browser just in case but still the same issue. Any idea please what could be wrong ? If needed more details, let me know I will provide it to you.

![grafana_problem_01](https://cloud.githubusercontent.com/assets/11044793/8404603/8eba7a66-1e4e-11e5-8a38-8c2efcdfc999.png)

Thanks for your time and effort :+1:

**Comment by koto137** [comment]
Oh crap, my mistake.. after 10 minutes of searching what went wrong... I found out immediately after I posted this that I've checked "STACK" option by mistake. Sorry :)

**Comment by alexanderzobnin** [comment]
@koto137 Thanks for feedback! Some comments about your case. You can use `All` options in hosts and items and use Regex `Incoming` to filter needed items and display all graphs by one query. Read more in wiki (https://github.com/alexanderzobnin/grafana-zabbix/wiki/Usage#filters).
P.S. Some defaults in Grafana can confuse, be careful.
