### ISSUE TITLE
Request to add Zabbix Proxy Database as datasource

### ISSUE THREAD

**Issue by EricVdB** [alexanderzobnin/grafana-zabbix#372]
#### I'm submitting a ...
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

Hi,

would it be possible to make the Zabbix Proxy Database (when using MySql) a datasource?
That way, we can create dashboards at the customer site (where the proxy is running) for the customer to view.

Kind regards,
Eric

**Comment by alexanderzobnin** [comment]
@EricVdB what exactly do you want to display? Or you want to connect to proxy, not to zabbix server?

**Comment by EricVdB** [comment]
@alexanderzobnin yes, i want to connect to the database of the proxy.

We would like to provide grafana dashboards to our customers but due to their and our security policies, it is not possible to host the dashboards on our company server. 

In Zabbix proxy you have the possibility to store the data locally for x hours/days in a sqlite or mysql database. I would like to install on the proxy (that is located at the customer) also grafana, and connect it to the zabbix proxy db so i can create dashboards at the customers place.

Is this more clear?

Kind regards,
Eric

**Comment by alexanderzobnin** [comment]
It's impossible now to connect directly to SQL DB in grafana. We're working on SQL datasource, but anyway, it's too tricky to use DB instead Zabbix API.
