### ISSUE TITLE
No datapoints for trends

### ISSUE THREAD

**Issue by ruslan-k** [alexanderzobnin/grafana-zabbix#373]
#### I'm submitting a ...
- [ x] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
4.1.2
- What Zabbix version are you using?
3.0.7
- What zabbix plugin version are you using?
3.3.0
- What OS are you running grafana on?
RHEL 6.5

When I set 7d for trends in zabbix plugin settings and use 7 days zoom and more it shows "no datapoints" on graphs, for <7 days graphs are viewing normally, without setting trends option everything shows normal, but grafana renders graphs slower this way.

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by MossmannInc** [comment]
I have two Zabbix/Grafana servers, one at work and the other at home.
On both servers I have more than 7 days worth of data, but can retrieve only the last 7 days on Grafana.
The datasources are configured to use Trends from "2M".

**Work server:**
Zabbix v3.2.4
Grafana v4.1.2
Zabbix Plugin v3.3.0
CentOS 7.3.1611

**Home server:**
Zabbix v3.2.4
Grafana v4.2.0
Zabbix Plugin v3.3.0
CentOS 7.3.1611

**Comment by alexanderzobnin** [comment]
@ruslan-k @MossmannInc can you check API requests in browser?
- Is it `trend.get` request?
- Which params have been used?
- What does Zabbix API return?

**Comment by MossmannInc** [comment]
I've identified a `history.get` request, but none `trend.get`.
Here is the Request payload:
```
{
	"jsonrpc":"2.0",
	"method":"history.get",
	"params": {
		"output":"extend",
		"history":"3",
		"itemids":["25505"],
		"sortfield":"clock",
		"sortorder":"ASC",
		"time_from":1490022000,
		"time_till":1490043600
		},
		"id":1,
		"auth":"3caa2215b5c7174b5529730aa1bb56da"
}
```

This is the response:
`{"jsonrpc":"2.0","result":[],"id":1}`

Using the same params in the following function in a shell script:

```
trend_get()
{
    JSON='
    {
        "jsonrpc": "2.0",
        "method": "trend.get",
        "params": {
            "output":"extend",
            "history":"3",
            "itemids":["25505"],
            "sortfield":"clock",
            "sortorder":"ASC",
            "time_from":1490022000,
            "time_till":1490043600
        },
        "auth": "'$TOKEN'",
        "id": 1        
    }
    '
    curl -s -X POST -H "$HEADER" -d "$JSON" "$URL" | python -m json.tool
}
```

I get this response:
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": [
        {
            "clock": "1490022000",
            "itemid": "25505",
            "num": "60",
            "value_avg": "48174",
            "value_max": "80368",
            "value_min": "36288"
        },
        {
            "clock": "1490025600",
            "itemid": "25505",
            "num": "60",
            "value_avg": "49465",
            "value_max": "105528",
            "value_min": "34520"
        },
        {
            "clock": "1490029200",
            "itemid": "25505",
            "num": "60",
            "value_avg": "51550",
            "value_max": "97672",
            "value_min": "38928"
        },
        {
            "clock": "1490032800",
            "itemid": "25505",
            "num": "60",
            "value_avg": "56855",
            "value_max": "118656",
            "value_min": "39136"
        },
        {
            "clock": "1490036400",
            "itemid": "25505",
            "num": "60",
            "value_avg": "59401",
            "value_max": "138752",
            "value_min": "40360"
        },
        {
            "clock": "1490040000",
            "itemid": "25505",
            "num": "60",
            "value_avg": "118754",
            "value_max": "2854440",
            "value_min": "37216"
        },
        {
            "clock": "1490043600",
            "itemid": "25505",
            "num": "60",
            "value_avg": "40358",
            "value_max": "50112",
            "value_min": "26352"
        }
    ]
}
```

**Comment by alexanderzobnin** [comment]
@MossmannInc seems, problem in data source, because it should send `trend.get`,not `history.get` request. Do you have clean install or upgraded Zabbix plugin?

**Comment by alexanderzobnin** [comment]
Can you also show me your data source config?

**Comment by MossmannInc** [comment]
This is a clean installation from last moth:
`Mar 10 14:32 alexanderzobnin-zabbix-app`
No updates ever since.

I've tested, on my home server, removing the datasource and the plugin, then reinstalling using the source code from the Github repository, same thing. It sends a `history.get`, but none `trend.get`.

This is the datasource configuration from the server at work:
![zabbix_datasource](https://cloud.githubusercontent.com/assets/1223711/24771412/e706261e-1ae3-11e7-9a00-b794ef1a2669.PNG)

This is from my home server:
![image](https://cloud.githubusercontent.com/assets/1223711/24771480/203f4cc6-1ae4-11e7-93eb-bdceac2b6363.png)

**Comment by alexanderzobnin** [comment]
Try to use lower interval, `5d`, for instance. Retrieving history for more than one week isn't a good idea (it should be very slow or even impossible for zabbix api).

**Comment by alexanderzobnin** [comment]
@ruslan-k do you have the same bug? I mean if you're using `7d` interval and retrieve data for 7 or more days, data source uses `history.get` instead `trend.get`?

**Comment by MossmannInc** [comment]
@alexanderzobnin I've also checked an older server, which is using the plugin version 3.1.1.
It works as expected, by sending `trend.get` instead of `history.get`, as it's happening on 3.3.0.

**Comment by alexanderzobnin** [comment]
@MossmannInc that's really strange, there was no changes in trend/history selection mechanism.

**Comment by MossmannInc** [comment]
@alexanderzobnin Using '5d' it works.
So, I guess this field means how far grafana will query "history" instead of "trends".
Weird.

**Comment by alexanderzobnin** [comment]
Can you debug it? Try to find this lines in `dist/datasource-zabbix/datasource.js` and add console.log() for getting details:
```js
var useTrendsFrom = Math.ceil(dateMath.parse('now-' + this.trendsFrom) / 1000);
var useTrends = timeFrom <= useTrendsFrom && this.trends;

// Add this line
console.log("useTrends: ", useTrends, useTrendsFrom, this.trendsFrom);
```

**Comment by alexanderzobnin** [comment]
@MossmannInc it works for 3.3.0, right?

**Comment by MossmannInc** [comment]
@alexanderzobnin Yup, after reducing to 5d, it works.

**Comment by alexanderzobnin** [comment]
I want to add one more option for trends, for more flexible configuration. Seems, I should add a tips for setting this up.

**Comment by MossmannInc** [comment]
Maybe renaming "Use from" to "Use after" would the better.
I didn't look at the code, but it seems it uses Trends "after" the time configured in the "Use from" field.
Correct if I'm wrong.

**Comment by alexanderzobnin** [comment]
Yea, seems this name cause misunderstanding.

**Comment by ruslan-k** [comment]
trend.get returns nothing for me
{"method": "trend.get", "id": 1, "jsonrpc": "2.0", "auth": "deleted", "params": {"limit": "1", "itemids": ["32573"], "output": ["itemid", "clock", "num", "value_min", "value_avg", "value_max"]}}
{'jsonrpc': '2.0', 'result': [], 'id': 1}
history.get works

**Comment by ruslan-k** [comment]
Same if i set 5d interval I get "No datapoits" for >=5 days period.

**Comment by alexanderzobnin** [comment]
@ruslan-k seems, you have another kind of problem

**Comment by alexanderzobnin** [comment]
Looks like zabbix api bug. Not sure.

**Comment by alexanderzobnin** [comment]
Do you see graphs with trends in Zabbix? Use 7 day interval to force trends using by Zabbix.
