### ISSUE TITLE
OK event color under -> Customize triggers severity and colors does not have "show button"

### ISSUE THREAD

**Issue by yatishg17** [alexanderzobnin/grafana-zabbix#374]
#### I'm submitting a ...
- [ ] Bug report
- [ x] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
Version 4.2.0 
- What Zabbix version are you using?
3.0
- What zabbix plugin version are you using?
3.3.0
- What OS are you running grafana on?
redhat 6.6
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Yes, because this behavior is configured by _Show events_ option (_Options_ section):

![image](https://cloud.githubusercontent.com/assets/4932851/24827955/463931f2-1c5c-11e7-9421-1bf068c1c8f8.png)
