### ISSUE TITLE
Low Level Discover values in Templating

### ISSUE THREAD

**Issue by adamobr** [alexanderzobnin/grafana-zabbix#375]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
 v4.2.0
- What Zabbix version are you using? 
3.0
- What zabbix plugin version are you using? 
3.3.0
- What OS are you running grafana on? 
CentOS7
- What did you do? 
I have a few auto discover roles and I want to create a template with its values.
- What was the expected result?
Get the auto-discovered values ( i think something like ad-hoc query) 
- What happened instead?
 I don't have any option to read the databases names to use as a filter in my graphs

I have a MongoDB running, sending data to zabbix then it is integrated to the grafana, working fine.

I'm trying to filter graphs per database in a different dashboard but I'm unable to get the database names to use as a template in the filters.
I have a few keys like dbsize[dbname], indexescount[dbname] and I want to be able to use a variable to replace the dbname

In my example below I wrote manually the database names but in real life it can be difficult to do.

Is there some way to get the values that a Low level discovery got?

It would be great if I can use its result to create a menu item to filter.

Expectation:
![image](https://cloud.githubusercontent.com/assets/5470767/24763860/a224a17e-1ac0-11e7-89d8-2312bd04b588.png)

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by ad-m** [comment]
There is no sense to access LLD values without LLD items. 

Do you can provide screenshot of Configuration->Templates->…-> Discovery rules-> … -> Item prototype?

**Comment by adamobr** [comment]
I do have items configured.

But once I have 10 databases I will have 10 x number of items in this case 20.

dbSize[1]
dbSize[2] ..

I want to be able to filter by 'database name' to only have (in this case 2 graphs with single lines) using templating in the item name

![image](https://cloud.githubusercontent.com/assets/5470767/24766176/51d0849c-1ac8-11e7-8c6b-9fb7a2a6d7fe.png)

**Comment by ad-m** [comment]
See at that example:
![zaznaczenie_0484](https://cloud.githubusercontent.com/assets/3618479/24766482/c620cb58-1afb-11e7-98db-3528d70fb852.png)

Query: ``*.*.*.*``
Regexp: ``/NumExtends (.*)$/``

Set up application name for item to optimize  query.

**Comment by adamobr** [comment]
Thank you I will try that.

**Comment by adamobr** [comment]
It worked absolutly fine. Thank you ad-m

**Comment by alexanderzobnin** [comment]
Yea, @ad-m right - use this way to extract part of metric and use it as variable value (interface, disk, database name, etc)
