### ISSUE TITLE
New aggregate function "sum" for groupBy/aggregateBy

### ISSUE THREAD

**Issue by joriws** [alexanderzobnin/grafana-zabbix#378]
#### I'm submitting a ...
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request

I am storing in Zabbix 30min intervals interface counter value as delta (not speed per second). So I have items like:
0-30min: 400bytes
30-60min: 600bytes
...

Now I want to aggregate all day's values to single number with aggregateby(1d) but I cannot calculate all days values together to see total bytes transferred per day. With example 2-point data I would get out 1000bytes, not 500bytes(avg) or 400bytes(min) or 600bytes(max).

So feature request is to allow instead of AVG just calculate things together by sum. And maybe close relation to it to allow multiply or substract or something. But sum would be important on aggregation.

**Comment by joriws** [comment]
If Zabbix API is directly returning the aggregated functions then I am asking wrong place. And question is that if grafana-zabbix could have it's own aggregation layer for data received?

**Comment by kompa3** [comment]
You need to add `consolidateBy(sum)` to the metrics (under Functions->Special) in addition to selecting `total` as Stat under Options. Without consolidateBy definition, Zabbix datasource gets the downsampled _average_ values from the database, and then sums the average values up as the total stat.

**Comment by alexanderzobnin** [comment]
Seems, that was implemented (both groupBy and aggregateBy have sum function)
