### ISSUE TITLE
Automatically create graphs for trends data (max & min values)

### ISSUE THREAD

**Issue by xiaoxue999** [alexanderzobnin/grafana-zabbix#379]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [√] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
4.2.0
- What Zabbix version are you using?
3.2.4
- What zabbix plugin version are you using?
none
- What OS are you running grafana on?
centos 6.7
- What did you do?
Graph with cpu,select Time range  from 2017-02-05 to 2017-02-07
- What was the expected result?
Show maximum and minimum values at that point in time.
- What happened instead?
The graph and values was difference with zabbix graph. 
I found some description in official website like this:
https://www.zabbix.com/documentation/3.2/manual/config/visualisation/graphs/simple
> Recent data vs longer periods
> For very recent data a single line is drawn connecting each received value. The single line is drawn as long as there is at least one horizontal pixel available for one value.
> For data that show a longer period three lines are drawn - a dark green one shows the average, while a light pink and a light green line shows the maximum and minimum values at that point in time. The space between the highs and the lows is filled with yellow background.

![1](https://cloud.githubusercontent.com/assets/22721577/24950047/3cb70444-1fa2-11e7-8d31-2320f169e4a0.png)
![2](https://cloud.githubusercontent.com/assets/22721577/24950154/a04956ec-1fa2-11e7-9bcc-f87f16259828.png)

**Comment by alexanderzobnin** [comment]
Just look at this example:
http://play.grafana-zabbix.org/dashboard/db/trends

**Comment by fpaternot** [comment]
Can we do that min/max automatically when we are collecting from trends, and not when we are using history?

That would help a lot when debugging and creating/managing dashboards.

**Comment by alexanderzobnin** [comment]
@fpaternot I'm not sure, may be it requires some tricks. Flow of this looks like:
1. Add two additional series (with min and max values)
2. Create series override rule.
