### ISSUE TITLE
Units from zabbix and value maps

### ISSUE THREAD

**Issue by v-zhuravlev** [alexanderzobnin/grafana-zabbix#381]
Hello, please consider getting units item attribute from the zabbix API source using item.get. Using it, we can achieve one click graph creation by automatically assigning Y-Axis type in Grafana similar to simple graph feature in the zabbix itself. 

Value maps can also be collected for status-like metrics , so we do not need to redefine mapping once again in single stat panels.

Thanks for your great work !

**Comment by alexanderzobnin** [comment]
Looks like this is already implemented, so closing this.
