### ISSUE TITLE
Advanced Tables

### ISSUE THREAD

**Issue by y34gagarin** [alexanderzobnin/grafana-zabbix#384]
Hi!

At first I'd like to thank you for the product! Thank you a lot for the great job!

I am asking for the advanced tables feature. I would like to be able to add a list of hosts into the table, where each row corresponds to the particular host with its items text data located in different columns.
(Just like the NewRelic server list table) Correct me if I am wrong and it is already possible to make this kind of a table.

Kind regards!

**Comment by alexanderzobnin** [comment]
Hi, thanks! Yes, it's useful feature. There's #240 issue already opened. I should implement special table mode (format zabbix response as grafana table object). I'll try to do that soon.
