### ISSUE TITLE
System status dashboard

### ISSUE THREAD

**Issue by kelaun** [alexanderzobnin/grafana-zabbix#385]
I would like to be able to visualize the results of /zabbix.php?action=widget.system.view in Grafana.
I can not add this url directly as data source and am wondering how this could be solved.
The goal is to recreate a dashboard looking like the system status dashboard from Zabbix.
![screenshot from 2017-04-24 13-37-18](https://cloud.githubusercontent.com/assets/11407575/25335417/377666dc-28f3-11e7-9e0e-3c95ca3f2f77.png)

The resulting data from the php request is as follow:
`{"header":"System status","body":"<div><table class=\"list-table\" id=\"t58fde3c0c3f2c\"><thead><tr><th>Host group<\/th><th>Critical<\/th><th>High<\/th><th>Normal<\/th><th>Low<\/th><th>Information<\/th><th>Not classified<\/th><\/tr><\/thead><tbody><tr><td><a href=\"tr_status.php?filter_set=1&groupid=11&hostid=0&show_triggers=1\">Cognos 10 Servers<\/a><\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><\/tr><tr><td><a href=\"tr_status.php?filter_set=1&groupid=10&hostid=0&show_triggers=1\">Cognos 11 Servers<\/a><\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><\/tr><tr><td><a href=\"tr_status.php?filter_set=1&groupid=7&hostid=0&show_triggers=1\">Hypervisors<\/a><\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><\/tr><tr><td><a href=\"tr_status.php?filter_set=1&groupid=2&hostid=0&show_triggers=1\">Linux servers<\/a><\/td><td class=\"normal-bg\">0<\/td><td class=\"high-bg\"><span class=\"link-action\" onmouseover=\"hintBox.HintWraper(event, this, jQuery(&quot;#hintbox_58fde3c0c3b80&quot;).html(), &quot;&quot;, &quot;&quot;);\" onclick=\"hintBox.showStaticHint(event, this, jQuery(&quot;#hintbox_58fde3c0c3b80&quot;).html(), &quot;&quot;, false, &quot;&quot;);\">1<span style=\"display: none;\"><span id=\"hintbox_58fde3c0c3b80\"><table class=\"list-table\" id=\"t58fde3c0c3bc5\"><thead><tr><th>Host<\/th><th>Issue<\/th><th>Age<\/th><th>Info<\/th><th>Ack<\/th><th>Actions<\/th><\/tr><\/thead><tbody><tr><td>dapsshaccess01.dap<\/td><td class=\"high-bg\">Lack of available memory on server dapsshaccess01.dap<\/td><td>19m 28s<\/td><td><\/td><td><a class=\"link-alt red\" href=\"zabbix.php?action=acknowledge.edit&eventids[]=69042&backurl=zabbix.php%3Faction%3Ddashboard.view\">No<\/a><\/td><td class=\"nowrap\"><ul class=\"list-hor-min-width\"><li><span class=\"link-action green\" onmouseover=\"hintBox.HintWraper(event, this, jQuery(&quot;#hintbox_58fde3c0c0e9e&quot;).html(), &quot;&quot;, &quot;&quot;);\" onclick=\"hintBox.showStaticHint(event, this, jQuery(&quot;#hintbox_58fde3c0c0e9e&quot;).html(), &quot;&quot;, false, &quot;&quot;);\">1<span style=\"display: none;\"><span id=\"hintbox_58fde3c0c0e9e\"><table class=\"list-table\" id=\"t58fde3c0c0eea\"><thead><tr><th>Time<\/th><th>User<\/th><th>Details<\/th><th>Status<\/th><th>Info<\/th><\/tr><\/thead><tbody><tr><td>2017-04-24 13:19:12<\/td><td>Admin (Zabbix Administrator)<\/td><td>Email<\/td><td><span class=\"green\">Sent<\/span><\/td><td><\/td><\/tr><\/tbody><\/table><\/span><\/span><\/span><\/li><li><\/li><li><span class=\"link-action red\" onmouseover=\"hintBox.HintWraper(event, this, jQuery(&quot;#hintbox_58fde3c0c11d4&quot;).html(), &quot;&quot;, &quot;&quot;);\" onclick=\"hintBox.showStaticHint(event, this, jQuery(&quot;#hintbox_58fde3c0c11d4&quot;).html(), &quot;&quot;, false, &quot;&quot;);\">1<span style=\"display: none;\"><span id=\"hintbox_58fde3c0c11d4\"><table class=\"list-table\" id=\"t58fde3c0c1219\"><thead><tr><th>Time<\/th><th>User<\/th><th>Details<\/th><th>Status<\/th><th>Info<\/th><\/tr><\/thead><tbody><tr><td>2017-04-24 13:19:12<\/td><td>dj (Tim Verhoeven)<\/td><td><\/td><td><span class=\"red\">Not sent<\/span><\/td><td><span class=\"status-red cursor-pointer\" onmouseover=\"hintBox.HintWraper(event, this, jQuery(&quot;#hintbox_58fde3c0c110c&quot;).html(), &quot;red&quot;, &quot;&quot;);\" onclick=\"hintBox.showStaticHint(event, this, jQuery(&quot;#hintbox_58fde3c0c110c&quot;).html(), &quot;red&quot;, false, &quot;&quot;);\"><b>&times;<\/b><span style=\"display: none;\"><span id=\"hintbox_58fde3c0c110c\">No media defined for user &quot;Tim Verhoeven (dj)&quot;<\/span><\/span><\/span><\/td><\/tr><\/tbody><\/table><\/span><\/span><\/span><\/li><\/ul><\/td><\/tr><\/tbody><\/table><\/span><\/span><\/span><\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><\/tr><tr><td><a href=\"tr_status.php?filter_set=1&groupid=8&hostid=0&show_triggers=1\">PostgreSQL servers<\/a><\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><\/tr><tr><td><a href=\"tr_status.php?filter_set=1&groupid=12&hostid=0&show_triggers=1\">Windows servers<\/a><\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><\/tr><tr><td><a href=\"tr_status.php?filter_set=1&groupid=4&hostid=0&show_triggers=1\">Zabbix servers<\/a><\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><td class=\"normal-bg\">0<\/td><\/tr><\/tbody><\/table><\/div>","footer":"<li>Updated: 13:38:40<\/li>"}`

**Comment by alexanderzobnin** [comment]
I think this should be done with #141
