### ISSUE TITLE
Arithmetic function feature request

### ISSUE THREAD

**Issue by Laakso** [alexanderzobnin/grafana-zabbix#387]
[x ] Feature request

Would be nice to have some sort of function which can do basic arithmetic calculations such as subtraction. Use case for my need is: I'm querying CPU Idle % from Zabbix to Grafana. I would like to graph actual CPU utilization like (100 - CPU Idle %). What do you think?

**Comment by alexanderzobnin** [comment]
I also have multiply operation (`scale` function), so it makes sense I think.

**Comment by gelonsoft** [comment]
+1

**Comment by RedHat93** [comment]
+1 will be really useful

**Comment by drakosha** [comment]
What functions are needed except shift, that i already added in #637?
