### ISSUE TITLE
null as zero

### ISSUE THREAD

**Issue by Artemka100** [alexanderzobnin/grafana-zabbix#388]
Здравствуйте!
Подскажите, пожалуйста, вопрос аналогичен этому: https://github.com/alexanderzobnin/grafana-zabbix/issues/55
Графики при отсутствии данных разрываются, но как только появляется информация, то они соединяются, без отображения downtime.
Datasource: Zabbix
![image](https://cloud.githubusercontent.com/assets/28025941/25410624/a0559140-2a20-11e7-8495-a4fbe9043e24.png)
![image](https://cloud.githubusercontent.com/assets/28025941/25410653/c9ccb2f6-2a20-11e7-84fd-41d11926b5a3.png)
Пробовал null value ставить в разных вариациях, но всё никак не отображается график вниз, к нулю.
![image](https://cloud.githubusercontent.com/assets/28025941/25410746/549f87be-2a21-11e7-81e0-d9ba8d50cadf.png)
Zabbix 3.0.8 (debian)
Grafana cli version 4.2.0 (debian)
Элемент данных используется такой: "Response time for step"

**Comment by alexanderzobnin** [comment]
Да, есть такая проблема. Zabbix API не возвращает информацию о том, что в заданном интервале нет данных, поэтому узнать это не так просто. Я могу добавить такую возможность в функции агрегации. Это работает так: серия разбивается на набор окон, и для всех точек в окне вычисляется единственное значение (например, среднее). Если окно пустое, можно добавить `null`, тогда будет работать переключатель _Null value_.

**Comment by Artemka100** [comment]
Буду очень рад данной фиче :) 👍

**Comment by tjmaru** [comment]
Можно я уточню.
У меня следующие данные:
Grafana v5.1.0 (в докере)
Zabbix Plugin Config  3.9.1
zabbix_server (Zabbix) 3.0.9 (на хосте)

и у меня не работает эта функция:(
как  не выставляй `Null value` никак не показывает график в нуле:(

**Comment by borjasueiro** [comment]
Grouping the data by average represents values ​​that are not real. Grouping the data by other functions would lead to losing values.
If we group the values ​​with a time equal to the `Update Interval` of Zabbix, erroneous gaps may appear. The `Update Interval` does not always fit what is defined. Example:

> if it is defined like 1 minute, Zabbix can take 1,01 minutes or more, and the grouping function would show erroneous gaps.

If grouped by `2x Update Interval` accuracy is lost.
Is there another fix that does not imply loss of accuracy?

**Comment by Artemka100** [comment]
30 августа 2019, 13:16:14, от "borjasueiro" < notifications@github.com >:

Grouping the data by average represents values ​​that are not real. Grouping the data by other functions would lead to losing values.
If we group the values ​​with a time equal to the Update Interval of Zabbix, erroneous gaps may appear. The Update Interval does not always fit what is defined. Example:

if it is defined like 1 minute, Zabbix can take 1,01 minutes or more, and the grouping function would show erroneous gaps.

If grouped by 2x Update Interval accuracy is lost.
Is there another fix that does not imply loss of accuracy?

**Comment by alexanderzobnin** [comment]
Unfortunately, Zabbix doesn't collect null values, so there's no 100% accurate way to do this. I strongly believe this a problem that TSDB should solve, not a plugin.
