### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by xiaoxue999** [alexanderzobnin/grafana-zabbix#389]
#### I'm submitting a ...
- [√] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
4.2.1
- What Zabbix version are you using?
3.2.4
- What zabbix plugin version are you using?
3.3.0
- What OS are you running grafana on?
CentOS 6.7 x64
- What did you do?
To show the ok events on Zabbix Triggers panel ,the page was returned a 500 error code, but only show the problems events was ok.
![1](https://cloud.githubusercontent.com/assets/22721577/25426904/54a6bc28-2aa3-11e7-8800-9e5deb690afb.jpg)
![2](https://cloud.githubusercontent.com/assets/22721577/25426937/7cf0e014-2aa3-11e7-9ab9-525332aae5fb.jpg)

**Comment by alexanderzobnin** [comment]
This is probably http server problem (may be lack of memory). Try to check http server logs.

**Comment by xiaoxue999** [comment]
Thanks alex, through nginx log I discover the reason might be php return timeout, it appears normal after adding parameter fastcgi_read_timeout =300 and waiting for 3 minutes, with only 10 records presents.
When I trace in the database, there is no condition refer to time, only to select all the records and use the filter to present the result.

**Comment by alexanderzobnin** [comment]
Ok, closing this.
