### ISSUE TITLE
History/trends data

### ISSUE THREAD

**Issue by koto137** [alexanderzobnin/grafana-zabbix#39]
Dear Alex,

Today I've updated to newest files,(not sure if it was working before, did not try it) but now I get red exclamation mark on left near row. It is only when using "last 30 days" option... In zabbix I use to keep data for 7 days and trends/history after that.. 7 Days are shown OK, but when i do more than that I get this, so has to do something with trends/history data in zabbix.

Here is screenshot of the issue when I open the red exclamation mark:

![image](https://cloud.githubusercontent.com/assets/11044793/8429169/6e045076-1f25-11e5-8dbc-e6e226745cdb.png)

**Comment by alexanderzobnin** [comment]
Are you use trend api patch? Zabbix don't work with trends in api without patch now.
