### ISSUE TITLE
No values ​​when importing templates

### ISSUE THREAD

**Issue by franklinleandro** [alexanderzobnin/grafana-zabbix#390]
#### I'm submitting a ...
- [ ] Bug report
No values ​​when importing templates
- [ ] Feature request
- [ ] Question / Support request

When trying to import the template, it does not load any value in the Dashboard.
This applies to all imported templates, an example is: https://grafana.com/dashboards/1323/revisions

Can you help me?

#### For bug report please include this information:
- What Grafana version are you using?
2.4.2
- What Zabbix version are you using?
3.2
- What zabbix plugin version are you using?
- What OS are you running grafana on?
Debian 8
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

Imagens
![grafana1](https://cloud.githubusercontent.com/assets/17831134/25629282/5e4af8e8-2f3f-11e7-9d0a-7a120a426519.JPG)
![grafana2](https://cloud.githubusercontent.com/assets/17831134/25629302/738b56e4-2f3f-11e7-99b7-7adf4adb2c6d.JPG)
![grafana3](https://cloud.githubusercontent.com/assets/17831134/25629311/7e4a0f30-2f3f-11e7-8a11-70222ac6b3d3.JPG)
![grafana4](https://cloud.githubusercontent.com/assets/17831134/25629314/81970878-2f3f-11e7-9598-544a86a587d7.JPG)
![grafana5](https://cloud.githubusercontent.com/assets/17831134/25629323/88fe1e80-2f3f-11e7-9431-c657d3a3bb6a.JPG)

**Comment by franklinleandro** [comment]
When trying to import the template, it does not load any value in the Dashboard.
This applies to all imported templates, an example is: https://grafana.com/dashboards/1323/revisions

**Comment by franklinleandro** [comment]
I also installed the **grafana-clock-panel** plugin, but it is not working.

**Comment by alexanderzobnin** [comment]
@franklinleandro try to check data source in imported dashboard.

**Comment by jl1994** [comment]
The same happens to me when importing a nginx integration template, the values ​​arrive at the zabbix without problems, but when reading them from grafana graphics it throws me an error of N / A
