### ISSUE TITLE
[ Can't access api by localhost ] Question / Support request

### ISSUE THREAD

**Issue by conexaoinfraestrutura** [alexanderzobnin/grafana-zabbix#391]
#### For bug report please include this information:
- What Grafana version are you using?
grafana-4.2.0-1.x86_64
- What Zabbix version are you using?
2.4.8
- What zabbix plugin version are you using?
3.3.0
- What OS are you running grafana on?
AWS AMI - centos 6 like
- What did you do?
Access zabbix jsonrpc under localhost
- What was the expected result?
connect and work
- What happened instead?
![screenshot from 2017-05-02 14-22-10](https://cloud.githubusercontent.com/assets/19329445/25630257/df926280-2f42-11e7-826d-2f1633dee97d.png)

The apache's vhost works fine i have tested with elinks and it goes fine

**Comment by alexanderzobnin** [comment]
@conexaoinfraestrutura usually url is like `http://myhost:myport/zabbix/api_jsonrpc.php`

**Comment by conexaoinfraestrutura** [comment]
i know but my vhost on apache is configured for pointing to root. So, my zabbix is accessible by path of url without the subdirectory

Same problem with this url: http://127.0.0.1:8085/zabbix/api_jsonrpc.php

**Comment by alexanderzobnin** [comment]
Try to look at browser dev tools (network tab) and check error code.

**Comment by conexaoinfraestrutura** [comment]
curl -i -X POST -d '{"jsonrpc": "2.0","method":"user.login","params": "user":"Admin","password":"*******"}, "auth": null,"id":0}' http://127.0.0.1:8085/api_jsonrpc.php

HTTP/1.0 412 Precondition Failed
Date: Mon, 08 May 2017 14:30:43 GMT
Server: Apache/2.4.25 (Amazon) OpenSSL/1.0.1k-fips PHP/5.6.30
X-Powered-By: PHP/5.6.30
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8
![screenshot from 2017-05-08 11-39-39](https://cloud.githubusercontent.com/assets/19329445/25809527/a3f5958a-33e3-11e7-8ad6-55b3258f7682.png)

**Comment by alexanderzobnin** [comment]
@conexaoinfraestrutura seems it's CORS-like issue. See here http://docs.grafana-zabbix.org/installation/configuration/#note-about-zabbix-22-or-less
