### ISSUE TITLE
[Bug report] Acknowledges user undefined

### ISSUE THREAD

**Issue by w-HA** [alexanderzobnin/grafana-zabbix#393]
Alexander ,

I note this issue .

When i acknowledge a trigger side zabbix . The user is undefined size grafana-zabbix .

![acknomledgement_undefined_user](https://cloud.githubusercontent.com/assets/18736461/25738134/b9fe49cc-317b-11e7-8305-5eed8dc1a4b2.jpg)

Is it a bug ? 

Thanks

Benoit

**Comment by alexanderzobnin** [comment]
Hi, @w-HA Which Grafana version do you use?

**Comment by w-HA** [comment]
Hi Alexander

zabbix server 3.2.5
grafana Version 3.1.1
grafana-zabbix app 3.3.0

Benoit

**Comment by alexanderzobnin** [comment]
Ok, I will try to check it.

**Comment by losintox** [comment]
Hi
I have the same problem.
zabbix 3.4.2
grafana 4.2.0
grafana-zabbix app 3.7.0

![image](https://user-images.githubusercontent.com/17594670/33065819-ecb972da-cea9-11e7-82c2-b25b426511ad.png)

Nicolas

**Comment by alexanderzobnin** [comment]
Now builds empty string if no username was provided.
