### ISSUE TITLE
Unable to Enable Zabbix, Permission Denied

### ISSUE THREAD

**Issue by Emmanueldlams** [alexanderzobnin/grafana-zabbix#395]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
Grafana cli version 4.2.0
- What Zabbix version are you using?
2.2.16-1.el6
- What zabbix plugin version are you using?
3.3.0
- What OS are you running grafana on?
CentOS release 6.9 (Final)
- What did you do?
Installed grafana suing command "then went to the front-end, logged in, but unable to enable the zabbix pluggin"
- What was the expected result?
Zabbix enable
- What happened instead?
Permission Denied

![image](https://cloud.githubusercontent.com/assets/21104732/26053084/c334220c-3967-11e7-9be5-6e815236e72e.png)

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by Emmanueldlams** [comment]
I would appreciate your assistance, thank you.

**Comment by alexanderzobnin** [comment]
Do you have admin permissions in grafana?
