### ISSUE TITLE
Extracting Zabbix Availability-Report Data

### ISSUE THREAD

**Issue by ascott58** [alexanderzobnin/grafana-zabbix#397]
#### I'm submitting a ...
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

Is there a way we can pull availability-report data from Zabbix? For instance., if I go to 'Reports' > 'Availability Report', I want to extract data from this screen. The data is present in the Zabbix trigger template, and I simply want to display it in Grafana.

This is another closed issue which asks for the exact same thing:
https://github.com/alexanderzobnin/grafana-zabbix/issues/246

**Comment by alexanderzobnin** [comment]
Unfortunately, there isn't API method for getting Availability Report, so I can't do this now.

**Comment by ascott58** [comment]
Hi, is there any chance you can add regular expression support for IT Services so that we can select multiple machines? Currently, when selecting an 'IT Service' Grafana will show (via a drop-down menu) every single machine added in Zabbix' IT Services page to select from. What if I want to select all machines of a particular IT Services parent and show each of those machines separately in a graph?

Cheers.

**Comment by alexanderzobnin** [comment]
@ascott58 please, open issue for that and attach some screenshots.

**Comment by alexanderzobnin** [comment]
@severinsimko I don't know actually.

**Comment by severinsimko** [comment]
@alexanderzobnin I was thinking about getting all the history data for Ping service for past let's say 1 month and just calculate it on my own, have you tried something like that?

**Comment by alexanderzobnin** [comment]
I think you could use SQL for that.

**Comment by severinsimko** [comment]
@alexanderzobnin could you please share the SQL Query that you used to get the Availability Report for a particulat host?

**Comment by alexanderzobnin** [comment]
You can try to find a query with debug mode on zabbix frontend.

**Comment by pbesra** [comment]
@ascott58 did you find the solution to pull availability-report data from Zabbix?

**Comment by eniocc** [comment]
Anyone find the solution? Only with a crawler I get the value but it isn't has a good performance.
