### ISSUE TITLE
[Help, Thanks a lot.] How can I enable this plugin without UI page

### ISSUE THREAD

**Issue by wenglixiang1990** [alexanderzobnin/grafana-zabbix#398]
Hi everybody:
  recently, I use python script to install  this plugin and add zabbix datasource by using the datasource API, but the way to get this plugin enabled is to log into the web ui and to click the "Enable" button (because I do not find information about the plugin API). It's bothering me. 
  I want to enable this plugin by script, but I do not know how to do it. Please help me, thank you very much.

**Comment by alexanderzobnin** [comment]
Seems, there isn't a way to enable app by using Grafana HTTP API.

**Comment by mikef-nl** [comment]
what is triggered when the Enable button is clicked?

**Comment by mikef-nl** [comment]
https://github.com/grafana/grafana/issues/8515#issuecomment-305736201
So the Grafana folk seem to think the Enable button makes an API call?

**Comment by mikef-nl** [comment]
Ok so a POST request to the <base grafana url>/api/plugins/alexanderzobnin-zabbix-app/settings/ with basic auth and body of id="alexanderzobnin-zabbix-app" and enabled=true seems to work.

**Comment by alexanderzobnin** [comment]
Yes, for Zabbix it's ok. It may not work for all apps, because sometimes enable requires some additional work, but not in zabbix case.

**Comment by acbox** [comment]
This worked for me on 4.3.2:

``curl -v --basic -XPOST 'username:password@localhost:3000/api/plugins/alexanderzobnin-zabbix-app/settings?enabled=true' -d ''``

**Comment by alexanderzobnin** [comment]
I think I can add this to _Installation _ section of docs.

**Comment by talsaiag** [comment]
may need to have &pinned=true appended as well (for application plugins that have pages bundled with them that should be pinned)

**Comment by mr-t-nl** [comment]
Would be incredibly useful to enable the plugin trough CLI / CURL.

Sadly it's not working for me, so little help would be appreciated.
`curl -v --basic -XPOST 'admin:<PW>@localhost:3000/api/plugins/alexanderzobnin-zabbix-app/settings?enabled=true' -d ''

* About to connect() to localhost port 3000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
* Server auth using Basic with user 'admin'
> POST /api/plugins/alexanderzobnin-zabbix-app/settings?enabled=true HTTP/1.1
> Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxx=
> User-Agent: curl/7.29.0
> Host: localhost:3000
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
* Connection #0 to host localhost left intact
`

Grafana: 5.4.3
Plugin: 3.9.1

Thanks in advance
