### ISSUE TITLE
Alert list filtering

### ISSUE THREAD

**Issue by andreioss** [alexanderzobnin/grafana-zabbix#400]
#### I'm submitting a ...
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

Hi!
It would be really useful feature, if you implement custom and dynamic filtering for alert list!
For instance I have long list alerts and want to quickly filter it by certain host, or alert name, or any other column (exclude or include).
Is this possible, what do you think?

**Comment by alexanderzobnin** [comment]
Do you mean Grafana alert list panel? Zabbix plugin doesn't support it now.

**Comment by andreioss** [comment]
Alexander, I mean exactly your trigger panel for zabbix. I know there is no support yet, that's why asking this feature :)

**Comment by alexanderzobnin** [comment]
But you can. You can filter by Group, Host, App and Trigger name.

![screenshot from 2017-05-26 10 09 39](https://cloud.githubusercontent.com/assets/4932851/26484554/72afa2a6-41fb-11e7-9dd4-14d535a434b0.png)

**Comment by andreioss** [comment]
Actually you're right, I meant a little different functionality, but this is also ok.
PS
In this case I should edit trigger panel to filter it, but common user doesn't have rights for it. It would be awesome if there was something like grafana 'templating' and variables in Select fields.
For now it's possible to choose only host from zabbix with this feature.

**Comment by alexanderzobnin** [comment]
Sure, template variables are supported. You can, for example, create $host variable and filter by host only.

**Comment by andreioss** [comment]
But the most important variable - trigger name, I couldn't set, right? Only a host.

**Comment by alexanderzobnin** [comment]
You can create a predefined variable with some names or regexes for filtering triggers by name.

**Comment by andreioss** [comment]
Oh, I see, thanks!

**Comment by dejnekas** [comment]
Hi, 
Any chances to have this feature for Prometheus data source? Or something different which gives me alerts from all my dashboards - this will allow me to quickly investigate issue!

**Comment by alexanderzobnin** [comment]
@dejnekas it's zabbix-only panel, so for prometheus, you should open issue in grafana repo.
