### ISSUE TITLE
How do i add all Items without creating multiple rows for each item.

### ISSUE THREAD

**Issue by macadminrohit** [alexanderzobnin/grafana-zabbix#401]
Hi,

I am using this plugin to get the data from Zabbix. I noticed that we can templatize the hosts and host group to get all the hosts data together. My scenario is : I have a dummy host which is created for URL monitors, this hosts have many web configurations for few URLs. So i want to display all the data for each URL like (Download speed, Error, Failed step) without creating multiple items. Is there anyway i can do this?

**Comment by alexanderzobnin** [comment]
Not sure, but maybe you should use regex?
http://docs.grafana-zabbix.org/guides/gettingstarted/
