### ISSUE TITLE
grafana 4.3.1 + zabbix plug-in 3.4.0 do not show zabbix 3.2.5 data

### ISSUE THREAD

**Issue by gbonazzoli** [alexanderzobnin/grafana-zabbix#402]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [X ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using? grafana_4.3.1_amd64.deb
- What Zabbix version are you using? zabbix-server-mysql_3.2.5-1+xenial_amd64.deb
- What zabbix plugin version are you using? 3.4.0
- What OS are you running grafana on? Ubuntu 14.04.5 LTS
- What did you do? I've installed and configured zabbix plugin. And everuthing was fine (green OK writings at the bottomo of the screen with zabbix version detected.
- What was the expected result? I was aspecting that the twho default dashboard show something regarding my Zabbix instllation
- What happened instead? The 2 dashboard do not show any data.

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by gonzalo-** [comment]
Oh, I just  come here to report the same, the Zabbix plugin is missing.
