### ISSUE TITLE
Is latest plugins support Grafana 4.2 + zabbix 3.0.1 ?

### ISSUE THREAD

**Issue by bg1szd** [alexanderzobnin/grafana-zabbix#403]
#### I'm submitting a ...
- [ ] Bug report
- [ ] Feature request
- [x] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using? Grafana 4.2
- What Zabbix version are you using? zabbix 3.0.1
- What zabbix plugin version are you using? 4.2
- What OS are you running grafana on? RHEL 7 64bit
- What did you do?
- What was the expected result?
- What happened instead?

**IMPORTANT** If it relates to metric data visualization would be great to get:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

Hi alexanderzobnin,
It seems the latest plugin 3.4 depends on the Grafana 3.x.x. As I am planning to use the Grafana 4.2, I am not sure whether the latest plugin is still compatible with Grafana 4.2. I went through the issues list, seems there was known compatibility issues between the plugin and grafana 4.3.1. Thanks!

**Comment by alexanderzobnin** [comment]
Yes, it just means 3.x.x+, it works with 4.x.x also without issues.
