### ISSUE TITLE
Alerts doesn't works with plugin 3.4

### ISSUE THREAD

**Issue by neodani** [alexanderzobnin/grafana-zabbix#405]
#### I'm submitting a ...
- [ X] Bug report

#### For bug report please include this information:
- What Grafana version are you using? Version 4.3.2 (commit: ed4d170)
- What Zabbix version are you using? 3.2.4
- What zabbix plugin version are you using? 3.4
- What OS are you running grafana on? Centos 7
- What did you do? Remove and install new zabbix plugin 3.4
- What was the expected result? 
- What happened instead?

I clicked on all check in Zabbix datasource however when I try configure an alert I receive this error when I test alert. And I don't know why. Should be works right?...

 result
    firing true
    state alerting
    conditionEvals = true
    timeMs 7.225ms
    error tsdb.HandleRequest() error Could not find executor for data source type: alexanderzobnin-zabbix-datasource

Thank you

**Comment by neodani** [comment]
![captura de pantalla de 2017-06-08 16 31 48](https://user-images.githubusercontent.com/511566/26934004-6c0ade30-4c68-11e7-8ff1-80a6297edc2f.png)

**Comment by alexanderzobnin** [comment]
It shouldn't work. http://docs.grafana-zabbix.org/reference/alerting/
