### ISSUE TITLE
Trends enabled causes odd drawing of Graph panel

### ISSUE THREAD

**Issue by TheQueasle** [alexanderzobnin/grafana-zabbix#406]
#### I'm submitting a ...
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request

#### For bug report please include this information:
- What Grafana version are you using?
  - `Version 4.3.2`
- What Zabbix version are you using?
  - `3.0.9`
- What zabbix plugin version are you using?
  - `3.4.0`
- What OS are you running grafana on?
  - `CentOS Linux release 7.3.1611`
- What did you do?
  - Enabled Trends on the grafana-zabbix datasource (using default values for `After`,`Range`, and `Cache TTL`
- What was the expected result?
  - The graph panel to display values in 'correct' manner.
- What happened instead?
  - The graph panel draws values in an odd manner.

Without Trends Enabled:
![2017-06-12-152350_1428x340_scrot](https://user-images.githubusercontent.com/13701545/27053518-3967ea0e-4f83-11e7-86e1-be60e57f3f49.png)

With Trends Enabled:
![2017-06-12-152408_1427x335_scrot](https://user-images.githubusercontent.com/13701545/27053534-45a2640c-4f83-11e7-9c67-96f81c448ab5.png)

I searched current and past issues, but was not able to locate any issues similar to this one.

Once I figure out how to do the following, I will update this issue.  
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Seems, the root cause is the same as for #202

**Comment by TheQueasle** [comment]
@alexanderzobnin Ugh...sorry I missed that issue.  I'll do the tweaks mentioned on #202 

Thanks for your time and thanks for your work on this Grafana Plugin/Datasource!!
