### ISSUE TITLE
Zabbix+Grafana+400 hosts=Connection error

### ISSUE THREAD

**Issue by artiatoisa** [alexanderzobnin/grafana-zabbix#407]
Hello. I'm using Grafana 4.3.2, Zabbix plugin 3.4.0, Zabbix 3.2.2, nginx+php-fpm, RHEL.
I am trying to draw graph with several specific metrics from 400 hosts to aggregate all timeserieses for 3 hours. But I got error "Zabbix API Error. Connection error.".
What reason could be?

**Comment by alexanderzobnin** [comment]
Seems, not enough memory for php at Zabbix frontend server. Try to check web server logs (php logs).
