### ISSUE TITLE
IT services dashboard templating

### ISSUE THREAD

**Issue by vzabauski** [alexanderzobnin/grafana-zabbix#408]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

Could you please add templating for IT services?
Templating works like a charm for metrics query
![image](https://user-images.githubusercontent.com/17778043/27334013-8b298016-55d0-11e7-973f-d0a3da2f595f.png)
IT services query has just a drop-down list.
![image](https://user-images.githubusercontent.com/17778043/27334141-01e18cd0-55d1-11e7-8fbf-fff3c24c02d3.png)
Thanks in advance. :)

**Comment by Gmatoy** [comment]
+1 Vote!

**Comment by daianmartinho** [comment]
+1 !!!!!! I came here looking for this

**Comment by ascott58** [comment]
Yes this would be great! I've also requested in a separate issue for regular expression support: https://github.com/alexanderzobnin/grafana-zabbix/issues/415

**Comment by vasekch** [comment]
+1

**Comment by snezhkov** [comment]
+1
It will be great to see the it services dependences with templating support

**Comment by nuclearburn** [comment]
+1

**Comment by alexanderzobnin** [comment]
That was implemented in 3.6.0 (see 70f34db385d10ac3842caf7c25648afd8db45af4). Sorry, forgot to mention that.
http://play.grafana-zabbix.org/dashboard/db/it-services?orgId=2
