### ISSUE TITLE
How to create custom legend labels for Items?

### ISSUE THREAD

**Issue by bwerst** [alexanderzobnin/grafana-zabbix#409]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

Is there a way to change the "item" labels that show in the legend?  I'm graphing the same item from multiple hosts and it would be helpful if the Legend could include the Hostname.  Without hostname I have no way of correlating the different lines to actual devices.

Hopefully it will be obvious looking at the legend in the attached picture.

Thanks,

Bill

![grafana item labels](https://user-images.githubusercontent.com/10964207/27348709-9baab812-55ba-11e7-97e7-d4e3145a88ca.PNG)

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.3.2  | 3.0.9  | 3.4.0                 |

**Comment by alexanderzobnin** [comment]
First, try to use one query with regex in host field, like this:
```js
/Core UPS 13[1-2]/
```
Then use [replaceAlias()](http://docs.grafana-zabbix.org/reference/functions/#replacealias) function and rewrite item alias.

**Comment by bwerst** [comment]
So finally got back to this.  Your suggestion worked great.  I changed host to /Core UPS*/ and its showing exactly what I'm looking for.

Thank You!
