### ISSUE TITLE
Data source configuration

### ISSUE THREAD

**Issue by SebastianPereiro** [alexanderzobnin/grafana-zabbix#41]
Grafana 2.0.2 + latest grafana-zabbix
Http settings and zabbix api details are not available for configuration then adding data source with "zabbix" type.
![grafanatrouble](https://cloud.githubusercontent.com/assets/13137011/8457541/a3600968-201a-11e5-9c9c-6d7f1ab19ce8.PNG)

**Comment by alexanderzobnin** [comment]
Can you look at browser console (F12) - is there some errors?

**Comment by alexanderzobnin** [comment]
Where your grafana plugins directory located?

**Comment by SebastianPereiro** [comment]
Thanks. Fixed!

**Comment by alexanderzobnin** [comment]
@SebastianPereiro what's problem? Paths?

**Comment by SebastianPereiro** [comment]
@alexanderzobnin exactly :)
