### ISSUE TITLE
Issue messages are cropped on Zabbix Triggers panel

### ISSUE THREAD

**Issue by banzayats** [alexanderzobnin/grafana-zabbix#411]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.2.0   | 3.2.4  | 3.4.0                 |

#### Problem description
We use the **Zabbix Triggers** panel to display triggers on our TV panels.
Some entries in the **Issue** column are truncated.  This occurs when the string length exceeds 50 characters.

![image](https://user-images.githubusercontent.com/477161/27369204-986f6d14-565f-11e7-9d28-70d6609a7458.png)

But this does not always happen. Here you can see a message longer than 50 characters and which is not cropped:
![image](https://user-images.githubusercontent.com/477161/27369446-9cd558ea-5660-11e7-83f2-d6941fcb0912.png)

I found only one place where the substr method is used to cut string to the 50 characters:
```
          if (settingsLinkText.length > 50) {
	            settingsLinkText = settingsLinkText.substr(0, 50) + "...";
	          }
	          settingsLinkText = 'Filter Queries (' + settings.filters.length + ')';
```
It is located in file `grafana/public/app/plugins/datasource/elasticsearch/bucket_agg.js`

Can you fix this behavior or add option to setup the length of the messages?

**Comment by banzayats** [comment]
I've found the same issue in Zabbix **Problems** dashboard:
![image](https://user-images.githubusercontent.com/477161/27370230-550392c6-5664-11e7-8494-9b35de31ca4c.png)

So, it's not Grafana but Zabbix cuts the lines. Is it possible to change this behavior in grafana-zabbix?

**Comment by alexanderzobnin** [comment]
@banzayats Code you point is from elasticsearch plugin, not from Zabbix. I just use a result from Zabbix API. I not sure is there a bug or feature 😃 , so try to ask Zabbix developers.

**Comment by volter** [comment]
It depends on the use of value/lastvalue macros and the item type. See https://support.zabbix.com/browse/ZBXNEXT-1016
