### ISSUE TITLE
Last Change filed showing the year 1969.

### ISSUE THREAD

**Issue by incoquinita** [alexanderzobnin/grafana-zabbix#412]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

#### What did you do?
I am using the Zabbix Triggers Row, and configuring to show All triggers, and are showing triggers that are never be "activated" with Last Change field as " 1969-12-31T22:00:00-02:00 ".

#### What was the expected result?
In this case, the Last Change Field must be blank.

#### What happened instead?
_Describe here_

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
![image](https://user-images.githubusercontent.com/29259509/27485431-0921591a-5803-11e7-810f-d73656ae7b97.png)

**Comment by alexanderzobnin** [comment]
What is a raw value of that time? Something about 0 I think.

**Comment by incoquinita** [comment]
I will se Alexander and return ASAP.
Thanks for your reply!

**Comment by incoquinita** [comment]
Yes Alexander, the raw value it's 0:

![image](https://user-images.githubusercontent.com/29259509/27550218-4351c8a8-5a75-11e7-9725-2c1e0b571b8b.png)

**Comment by alexanderzobnin** [comment]
Ok, seems, I should check it. What does Zabbix show for this trigger in Last 20 issues?

**Comment by incoquinita** [comment]
Sorry for my late Alexander.
These triggers are not showed in Last 20 Issues, because they was not "activated", they did not happen.

**Comment by Sdude1991** [comment]
Alexander,
I am experiencing this issue as well, but only with triggers that's status is 'OK'. 

Date works fine if it is a active trigger.
Robert 
![banners_and_alerts_and_grafana_-_gd_high_level_view](https://user-images.githubusercontent.com/20248021/30866100-57214e70-a2a6-11e7-8c79-2bd15802d48a.jpg)
