### ISSUE TITLE
Feature request: "Last value" field in Zabbix Triggers table

### ISSUE THREAD

**Issue by banzayats** [alexanderzobnin/grafana-zabbix#414]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature requestdd
- [ ] Question / Support request

Currently the **Zabbix Triggers** view shows the following fields:
* Issue 
* Host name/technical name
* Status
* Severity
* Last change
* Age
* Info

Please add the "**Last value**" field. This will be useful, since the trigger does not always include this value, and when it is long - it is truncated #411.

**Comment by alexanderzobnin** [comment]
Trigger expression may contain more than 1 value. How to handle this case?

**Comment by banzayats** [comment]
You are right.
Also trigger may use the average value so the latest one would not be descriptive.

I'm sorry that I created a ticket without analyzing all the variants. Closing it.
