### ISSUE TITLE
Adding more functionality to IT Services feature (e.g. regex support)

### ISSUE THREAD

**Issue by ascott58** [alexanderzobnin/grafana-zabbix#415]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature requestd
- [ ] Question / Support request

We are using Zabbix as our datasource and one of the things we need to present in our dashboard is the **availability** of multiple servers. We are using a trigger in Zabbix to monitor server availability, and so the SLA of each machine is automatically calculated in Zabbix as the percentage of a time period that the server was online. All the machines have been added to Zabbix' IT Services feature. So by visiting Zabbix' IT Services page we can see each added machine's OK time, PROBLEM time, and SLA, etc..

We want to show the availability (i.e. SLA) data of all servers on a graph of some sort in Grafana. For example, below is a memory utilization graph (using Zabbix metrics). We want something similar for SLA, that is, a line for each server all on 1 graph. That way, when a user selects a server under the graph only that server's line is displayed.
![image](https://user-images.githubusercontent.com/26335953/27561446-6b4bfb80-5b0b-11e7-90ea-e734be7c6ecf.png)

However, in Grafana, when I select Zabbix as my datasource and select **IT Services** as the query mode, I cannot select multiple servers using a regex such as /.*/ (like I can in the Metrics query mode). Therefore, I'd have to manually duplicate and add each server manually, as shown below.
![image](https://user-images.githubusercontent.com/26335953/27561848-2b5603a2-5b0d-11e7-844c-9bac99ff69cf.png)

If you look at the graph below (a memory utilization graph using metrics as the query mode) the machines have their own line on the graph, and all these machines were selected using a regex. We want to be able to do the same thing for IT Services. That way, if a server is added in Zabbix (under IT Services), the Grafana dashboard will automatically update when refreshed since the regex will capture the newly added servers.
![image](https://user-images.githubusercontent.com/26335953/27561654-4d03c1b6-5b0c-11e7-8796-adf744baabcd.png)

Can you please add this? Otherwise, can you suggest me a technique for what I want to achieve? If you need any further information, please ask, we really really need an efficient method to present availability data for our servers, and Grafana is an excellent product we want to stick with.

Thank you!

**Comment by daianmartinho** [comment]
+1

**Comment by Gmatoy** [comment]
It would be great if you add functions too, exemple: able to turn a single stat hour format to receive a division function, like 4.43 hours, fuction of *.xxx/60 to turn to time format instead of decimal format

**Comment by daianmartinho** [comment]
is this included at 3.5 update? i updated but don't see that feature

**Comment by alexanderzobnin** [comment]
Sorry, but no, I should move it to next release.

**Comment by ascott58** [comment]
Hi, please let us know when there is a new release for us to download with this feature included. Thank you very much :D

**Comment by alexanderzobnin** [comment]
@ascott58 Implemented, will be in 3.6 release, probably this week.

**Comment by Gmatoy** [comment]
Nice!!! TY U a lot

**Comment by daianmartinho** [comment]
still the same here =/

**Comment by alexanderzobnin** [comment]
@daianmartinho Look at this screenshot. Or maybe you mean something different?

![screenshot from 2017-07-27 08 57 18](https://user-images.githubusercontent.com/4932851/28656691-0ba2b558-72ac-11e7-9614-6687e68da7c5.png)

**Comment by daianmartinho** [comment]
singlestat panel still dropdown query.

Em 27 de jul de 2017 3:16 AM, Alexander Zobnin <notifications@github.com> escreveu:

@daianmartinho<https://github.com/daianmartinho> Look at this screenshot. Or maybe you mean something different?

[screenshot from 2017-07-27 08 57 18]<https://user-images.githubusercontent.com/4932851/28656691-0ba2b558-72ac-11e7-9614-6687e68da7c5.png>

**Comment by alexanderzobnin** [comment]
@ascott58 is this implementation solves your issue? @daianmartinho what the expected result? Please, describe your case in details.

**Comment by ascott58** [comment]
@alexanderzobnin my issue has been solved, thank you for the updated release :)
