### ISSUE TITLE
Division function

### ISSUE THREAD

**Issue by artiatoisa** [alexanderzobnin/grafana-zabbix#416]
Hello. I'm using Grafana 4.3.2, Zabbix plugin 3.4.0, Zabbix 3.2.2, nginx+php-fpm, RHEL.
How can I use division in queries?
How can I sum some queries to each other?
Is it possible?

**Comment by alexanderzobnin** [comment]
Hi! Now you can apply functions only to the metrics from the same query. Use `scale()` and `sumSeries()`.
