### ISSUE TITLE
Enable query for item value at templates

### ISSUE THREAD

**Issue by daianmartinho** [alexanderzobnin/grafana-zabbix#417]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request

Can we query for item value at templates? I need to use the value of an item A for query an item B.

**Comment by alexanderzobnin** [comment]
Sometimes it may be useful. I should find a good way for this type of query.

**Comment by jason913** [comment]
This would be very very useful for correlation data.

**Comment by jpowers-j2** [comment]
This has a valuable use case in conjunction with other plugins, the grafana-cloudwatch plugin can look things up by instance-id but presently there are cases where it can't look up the instance-id itself, for example "a list of the instance-ids attached to this elb or autoscaling group". I'd like to be able to push that info back into zabbix from the host itself, and then use the string data in template variables to query things in aws with repeat graphs and such. 

being able to query item values right into template variables would be great for this

**Comment by thechile** [comment]
@alexanderzobnin any chance this will get worked on soon ? I have service that is made up of 20 individual microservices that are duplicated on multiple servers and scale horizontally as needed. 

I wanted to have a graph panel per process showing its memory usage that we collect using Beats.

To avoid manually configuring this i wanted to template it and 'Repeat for each value'

So I have added the variable using a query to auto generate the list but when i try to use the variable in the Item field of the panel it does nothing.

**Comment by alexanderzobnin** [comment]
I think it's possible with new Grafana variable query editor feature. So I'll try to implement this in next minor version.
Example of variable query editor:
https://github.com/grafana/grafana/issues/13561
https://github.com/grafana/grafana/pull/14007

**Comment by alexanderzobnin** [comment]
Created #705 as well
