### ISSUE TITLE
Add option to display group and proxy on Zabbix Triggers panel

### ISSUE THREAD

**Issue by ghost** [alexanderzobnin/grafana-zabbix#418]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature requestdd
- [ ] Question / Support request

Hello, 

It would be nice to have options to display Zabbix group names and proxies as table columns on "Zabbix Triggers" panel and an option to filter out values using regex. I use Zabbix to monitor several tenants and having the possibility to relate tenant to asset in one view would be fantastic.

**Comment by alexanderzobnin** [comment]
Not sure how is better to implement this, so moving it to next milestone.

**Comment by alexanderzobnin** [comment]
Now it's possible to filter triggers by proxy and show proxy name before the host:

![screenshot from 2018-11-15 10-54-17](https://user-images.githubusercontent.com/4932851/48538220-ebacbb00-e8c4-11e8-92f3-25d2114ba1a6.png)
