### ISSUE TITLE
Problem populating HP procurve switches

### ISSUE THREAD

**Issue by putteg** [alexanderzobnin/grafana-zabbix#419]
### I'm submitting a ...
- [] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Grafana v4.3.2 (commit: ed4d170)   | Zabbix 3.2  |3.4.0         |

#### What did you do?
Im trying to get network traffic in/out from out HP Procurve switches
But I only get "Admin Status of interface x.y"
#### What was the expected result?
Inbound/outgoing/errors on interface (I get that from a local netgear switch)

#### What happened instead?
But I only get "Admin Status of interface x.y"

If it relates to metric data visualization would be great to get
![screenshot_20170704_095034](https://user-images.githubusercontent.com/29883094/27820723-fa96275e-609f-11e7-96a4-ee06565e7902.png)

**Comment by alexanderzobnin** [comment]
List of metrics is too long, so just start to type name of metric and it will be filtered. If you don't see it anyway, check discovery and items in Zabbix.

**Comment by putteg** [comment]
Thnx, it worked :D
