### ISSUE TITLE
Two Zabbix servers as datasource

### ISSUE THREAD

**Issue by kadern0** [alexanderzobnin/grafana-zabbix#42]
I'm trying to create a single dashboard with Grafana to monitor two different Zabbix servers. I can't get the two servers working at the same time, whenever one of them appears, the other disappears. Is it a known issue? Any fix for this?

Thank you.

**Comment by alexanderzobnin** [comment]
Now Grafana don't support custom parameters in datasourse configuration. For this reason username and password now sets in `plugin.json` file. If your servers have different accounts you will have some troubles with configuration. Once solution is copy datasource directory and change parameters in `plugin.json` file:
```
{
  "pluginType": "datasource",
  "name": "Zabbix 2",

  "type": "zabbix_2",
  "serviceName": "ZabbixAPIDatasource",

  "module": "plugins/datasource/zabbix_2/datasource",

  "partials": {
    "config": "app/plugins/datasource/zabbix_2/partials/config.html",
    "query": "app/plugins/datasource/zabbix_2/partials/query.editor.html",
    "annotations": "app/plugins/datasource/zabbix_2/partials/annotations.editor.html"
  },

  "username": "user2",
  "password": "password2",
```
This problem will be fixed at Grafana 2.1.

**Comment by kadern0** [comment]
Hi Alexander,
first of all thank you for your answer. I've tried this approach but with no much luck. Both servers seem to interfere with each other. I have a dashboard with graphs from both servers and whenever one of them works, the other one doesn't. Any plan C?
Do you know when Grafana 2.1 is expected to be released?

Thank you very much.

**Comment by nucleusv** [comment]
@kadern0, this configuration is tested and works. So please show you plugins directory structure and and plugin.json of both. And screenshots of datasource settings in Grafana

**Comment by kadern0** [comment]
Installed Packages
grafana.x86_64     2.0.2-1
``` pwd
/usr/share/grafana/public/app/plugins/datasource
ls -lh
total 36K
drwxr-xr-x 3 root root 4.0K Jul  1 11:45 elasticsearch
drwxr-xr-x 3 root root 4.0K Jul  1 11:45 grafana
drwxr-xr-x 3 root root 4.0K Jul  1 11:45 graphite
drwxr-xr-x 3 root root 4.0K Jul  1 11:45 influxdb
drwxr-xr-x 3 root root 4.0K Jul  1 11:45 influxdb_08
drwxr-xr-x 3 root root 4.0K Jul  1 11:45 opentsdb
drwxr-xr-x 3 root root 4.0K Jul  1 11:45 sql
drwxr-xr-x 3 root root 4.0K Jul  1 15:54 zabbix
drwxr-xr-x 3 root root 4.0K Jul  2 09:05 zabbix_2`
cat zabbix/plugin.json
{
  "pluginType": "datasource",
  "name": "Zabbix",

  "type": "zabbix",
  "serviceName": "ZabbixAPIDatasource",

  "module": "plugins/datasource/zabbix/datasource",

  "partials": {
    "config": "app/plugins/datasource/zabbix/partials/config.html",
    "query": "app/plugins/datasource/zabbix/partials/query.editor.html",
    "annotations": "app/plugins/datasource/zabbix/partials/annotations.editor.html"
  },

  "username": "********",
  "password": "********",

  "trends": true,
  "trendsFrom": "7d",

  "limitmetrics": 50,

  "metrics": true,
  "annotations": true
}
cat zabbix_2/plugin.json
{
  "pluginType": "datasource",
  "name": "Zabbix 2",

  "type": "zabbix_2",
  "serviceName": "ZabbixAPIDatasource",

  "module": "plugins/datasource/zabbix_2/datasource",

  "partials": {
    "config": "app/plugins/datasource/zabbix_2/partials/config.html",
    "query": "app/plugins/datasource/zabbix_2/partials/query.editor.html",
    "annotations": "app/plugins/datasource/zabbix_2/partials/annotations.editor.html"
  },

  "username": "********",
  "password": "*******",

  "trends": true,
  "trendsFrom": "7d",

  "limitmetrics": 50,

  "metrics": true,
  "annotations": true
}

Screenshots:

![screen shot 2015-07-02 at 10 51 38](https://cloud.githubusercontent.com/assets/13137996/8474571/f61b5728-20a8-11e5-9b20-103459fb3bfd.png)
![screen shot 2015-07-02 at 10 51 50](https://cloud.githubusercontent.com/assets/13137996/8474573/f8cd78fc-20a8-11e5-9066-322854ac9f14.png)
![screen shot 2015-07-02 at 10 52 06](https://cloud.githubusercontent.com/assets/13137996/8474576/fb4489fe-20a8-11e5-89d1-c0db9f970e00.png)

As remark, I can get data from both servers (so connection/password  problems are out the way), but not at the same time.

**Comment by nucleusv** [comment]
If I've understood you right, you CAN get graphs of the same datasource on one dashboard BUT you can not both datasources on the same dashboard?

**Comment by kadern0** [comment]
Yes. Take a look what happens (each of this graphs uses a different datasource):
![screen shot 2015-07-02 at 13 40 16](https://cloud.githubusercontent.com/assets/13137996/8477181/27b883e8-20c0-11e5-892b-ed24d906865e.png)
![screen shot 2015-07-02 at 13 39 41](https://cloud.githubusercontent.com/assets/13137996/8477185/2a62b9ba-20c0-11e5-831f-447ddc1644f1.png)

If I change the default datasource and I start switching between dashboards one of them will have data and the other one will stop reporting (without changing any configuration).

**Comment by alexanderzobnin** [comment]
I test this case and got the same result. I will try to find solution.

**Comment by alexanderzobnin** [comment]
@kadern0 seems this problem fixed. Try to test it. Get code from release branch (https://github.com/alexanderzobnin/grafana-zabbix/tree/release-2.0.0)
