### ISSUE TITLE
Singlestat Showing N/A for a file size data

### ISSUE THREAD

**Issue by PauloVasques** [alexanderzobnin/grafana-zabbix#421]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.3.2   | 3.2.6  | 3.4.0                 |

#### What did you do?
Add a Singlestat grafic to show the Size of a .MDF file. Zabbix is showing correct info, with the key:
vfs.file.size["C:\Program Files\Microsoft SQL Server\MSSQL11.SRVDBSAP\MSSQL\DATA\#######.mdf"]

#### What was the expected result?
Last Data on Zabbix is showing correct result: 42,99GB

#### What happened instead?
Grafana returns only "N/A"

If it relates to metric data visualization would be great to get
![image](https://user-images.githubusercontent.com/29922127/27868402-fbf5619a-6172-11e7-8641-452984cc4a49.png)

**Comment by alexanderzobnin** [comment]
Which time range did you set? And what is a value update time in Zabbix latest data?

**Comment by PauloVasques** [comment]
I left the Grafana default time range:
![image](https://user-images.githubusercontent.com/29922127/27871295-a261243a-617b-11e7-8013-74df3e8fa1bc.png)
Zabbix update time for the item is 43200segs (12 hours)

**Comment by alexanderzobnin** [comment]
Just increase time range - there isn't data for this period.

**Comment by PauloVasques** [comment]
Zabbix update time was 30sec before (already N/A), then I increase it to 43200sec.
I tried to increase Grafana Time Range but no change at the data displayed.

**Comment by alexanderzobnin** [comment]
Try to look at network request. What does zabbix return?
