### ISSUE TITLE
Singlestat IT Service - Cannot read property '4664' of null

### ISSUE THREAD

**Issue by daianmartinho** [alexanderzobnin/grafana-zabbix#423]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.3.2 | 3.2.0  | 3.5.0                 |

#### What did you do?
IT Service Singlestat panel

This error leaves when refresh dashboard data.

#### What was the expected result?
![image](https://user-images.githubusercontent.com/8451484/27890008-9dfed7d4-61c6-11e7-8f07-67363df0efa7.png)

#### What happened instead?
![image](https://user-images.githubusercontent.com/8451484/27890045-cff02432-61c6-11e7-81c5-a55b7c000d62.png)
![image](https://user-images.githubusercontent.com/8451484/27890217-a4c85ba2-61c7-11e7-9725-ed7cb36b6611.png)

**Comment by alexanderzobnin** [comment]
Probably not relevant anymore.
