### ISSUE TITLE
grafana-server 5.0.0 zabbix 3.2.6 Plugun 3.5.0 no data points

### ISSUE THREAD

**Issue by ALittleStudent** [alexanderzobnin/grafana-zabbix#426]
### I'm submitting a ...
- [x] Bug report

### For bug report please include this information:

**Software Versions**

| Grafana-server | Zabbix | Grafana-Zabbix Plugin |
| Version 5.0.0-pre1 | 3.2.6 | 3.5.0 |

#### What did you do?
I add the data source, and it can see the green "success \n Zabbix API version: 3.2.6". In the zabbix web i can see the data, such as CPU load.

#### What was the expected result?
i try to use the " Zabbix Server Dashboard" and edit the Zabbix Data Source as myzabbix, but the Graph show " no data point" .

**Comment by alexanderzobnin** [comment]
Do you see any data if you add it by hand? Did you check zabbix user permissions?

**Comment by ALittleStudent** [comment]
Sorry, my problem.
