### ISSUE TITLE
Annotations with template variable, trigger field bug

### ISSUE THREAD

**Issue by h1tman23** [alexanderzobnin/grafana-zabbix#428]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.3.1   | 3.0.9  | 3.5.1                 |

#### What did you do?
Annotations with template variable.

#### What was the expected result?
When I create Annotations with template variable and put that variable in Trigger field it does not work properly (no results found), but with Group, Host or Application fields everything is OK variable work.

#### What happened instead?
No results found when I put variable in Trigger field.

**Comment by alexanderzobnin** [comment]
Do you use multi-value variables? Try to wrap variable in regex: `/$myvar/`.

**Comment by h1tman23** [comment]
Nothing helps. Simple example:
I create custom variable in Templating: Name - myvar, Values separated by comma - Errors. Then I put that variable in Application field in regex /.\*$myvar.\*/ everything is OK.
![annotation](https://user-images.githubusercontent.com/30226571/28313108-4920e782-6bbe-11e7-9e50-ee40feb74954.png)

If put the save variable in Trigger field in regex /.\*$myvar.\*/ annotations disappear.
![no_annotations](https://user-images.githubusercontent.com/30226571/28313239-d06db206-6bbe-11e7-8da4-a88ca0e21bb6.png)

If I put Errors instead of $myvar ---> /.\*Errors.\*/ then annotations appear again. So in my situation variables does not work in Trigger field.

**Comment by alexanderzobnin** [comment]
Yes, confirmed.
