### ISSUE TITLE
Zabbix API connection Error when reqesting older data

### ISSUE THREAD

**Issue by wonderphil** [alexanderzobnin/grafana-zabbix#429]
### I'm submitting a ...
- [ ] Bug report

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|  4.4.1  | 2.2.1  | 3.5.1                 |

#### What did you do?
If i have set the time range to be now-4d then i get errors,
If i select just one days data from last week I also get the error.

#### What was the expected result?
I would expect to get the data for that date range you select

#### What happened instead?
When you set time range to anything longer then 4 days you get a error:
"Zabbix API error"
"Connection Error"

If it relates to metric data visualization would be great to get
No logs found on Zabbix Server

Logs from Grafana at the time of request: the logs show no errors

**Comment by alexanderzobnin** [comment]
See #407 #389
