### ISSUE TITLE
No value from time to time 

### ISSUE THREAD

**Issue by neomh** [alexanderzobnin/grafana-zabbix#430]
### I'm submitting a ...
- [*] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.4.1   |  3.2.6  | 3.5.1                 |

#### What did you do?
We created a zabbix dashboard on grafana. From time to time we get no value or N/A on text field that are items pulled every 1 sec in zabbix.

I couldn't find any errors in grafana/zabbix logs.
Please advise.

![image](https://user-images.githubusercontent.com/4259382/28371070-3b2eb5b2-6c9c-11e7-9b59-c85ce27958c6.png)

Thank you for your help

**Comment by alexanderzobnin** [comment]
Can you check zabbix response in browser dev tools? What does zabbix return?

**Comment by sesom42** [comment]
I have very often the same error. I have created a playlist with many dashboards. After a run, almost all dashboards have missing values or they are completely empty. Can somewhere a debug output of the Zabbix plugins set?

**Comment by alexanderzobnin** [comment]
@sesom42 did you notice errors, for example, "Zabbix API Error" in grafana? This may be caused by php limits on Zabbix server.

**Comment by sesom42** [comment]
@alexanderzobnin no API error messages are displayed. The server is dimensioned to suit PHP needs. I've looked at it more closely. Grafana first requests '/api/dashboards/db/<dashboard-name>'. Then it retrieves for every widget '/api/datasources/proxy/2'. The answer to this request is sometimes only '{"jsonrpc": "2.0", "result": [], "id": 1}'. Sometimes '/api/datasources/proxy/2' is not even requested. It looks like more as an bug in Grafana itself.

**Comment by alexanderzobnin** [comment]
@sesom42 yes, you should check history/trend api queries. Some requests are cached (items, hosts, but not history).

**Comment by neomh** [comment]
Hello

Sorry for not following back on this issue.. I must have forgotten.

I think that the issue originated from the browser. @David-SpreenICT , try to add the zabbix api url into exceptions, deactivate any adblocker etc... Verify that Grafana can connect without restrictions to Zabbix's API URL (FW rules etc...)

**Comment by David-SpreenICT** [comment]
Hello Neomh,

The "No Value" shows up on just a couple of the gauge's.
When the CPU gauge (for example) shows a nice value, the memory could go in to "No value" and after a 15 seconds refresh both could work fine...  Then for about 4 of 5 refreshes the CPU gauge could go in to "No value" and the following refresh (15 seconds) will show a value again.

There is no add-blocker active, this would mess up all of the gauges and grafana has data so no FW issue's.

My collegue and I are thinking it should have something to do with the refresh time of the pages / gauge's.

Could you guy's give me an example of your refresh timers or the settings of your "Override relative time" for each gauge?

Many thanks for the effords,
Sincerely, David

**Comment by alexanderzobnin** [comment]
Hm... Try to upgrade to latest version, it seems that was fixed.

**Comment by alexanderzobnin** [comment]
Ah, sorry. That was fixed, but not released yet.
https://github.com/alexanderzobnin/grafana-zabbix/issues/571
