### ISSUE TITLE
Zabbix Multiple Datasources Zabbix Triggers page.

### ISSUE THREAD

**Issue by Prophecy67** [alexanderzobnin/grafana-zabbix#431]
### I'm submitting a ...
- [ ] Bug report
- [X/Maybe] Feature requestdd
- [X] Question / Support request

###

As Zabbix does not support Concatenation / Distributed Monitoring anymore in an updated fashion.. We moved to Grafana to aggregate these alerts. These Datasources have been attached and work on the "Zabbix Triggers" panel. However, this panel doesn't seem to be able to repeat in a templated fashion (Or even nicer would be to concatenate everything in to one panel). Am I doing something wrong?

In the templating I've added $zbxsrc as a name. Type Datasource, Data source options: Type: Zabbix. No Instance Filter.

On the Zabbix Triggers Dashboard I've enabled $zbxsrc as a Repeat Panel. Now I can use this Dropdown Template to switch "Datasources".. But It doesn't repeat for every additional datasource in the list.

**Comment by alexanderzobnin** [comment]
Yes, it's a good idea to mix multiple zabbix instances in one triggers panel. Now it's impossible.

**Comment by q1x** [comment]
What would be needed to implement this feature? We also would like to use Grafana as a a means of aggregating alerts from multiple Zabbix servers.

**Comment by alexanderzobnin** [comment]
Implemented in 53d795d259d64508c9f11caf7593dc2966648e6b
Going to release this feature in next version this month

![screenshot from 2017-12-03 12-57-35](https://user-images.githubusercontent.com/4932851/33524238-a602e428-d829-11e7-85ce-1458bbc29d23.png)

![screenshot from 2017-12-03 12-57-20](https://user-images.githubusercontent.com/4932851/33524239-a62191c0-d829-11e7-9db9-372d623f7579.png)

**Comment by q1x** [comment]
Very awesome! Can't wait to try this :)
