### ISSUE TITLE
datasource's trigger field never gets populated

### ISSUE THREAD

**Issue by ignaqui** [alexanderzobnin/grafana-zabbix#433]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.4.1 | 3.2.4 | 3.5.1 |

#### What did you do?

Datasource's trigger field in triggers panel never gets populated. I need to use regex to circumvent this limitation. However, this field works fine with other panels (alarmbox etc.)

![zabbix-grafana_02](https://user-images.githubusercontent.com/12226984/28593515-8cb6ca42-715a-11e7-81f1-32ce99406601.PNG)

#### What was the expected result?

For different plugin this works:
![image](https://user-images.githubusercontent.com/12226984/28593188-789a8888-7159-11e7-9f7b-1faad26aa6ac.png)

#### What happened instead?
Trigger field never populates with trigger names
![zabbix-grafana_01](https://user-images.githubusercontent.com/12226984/28593050-0f2fee60-7159-11e7-90e0-72fe4456cb95.PNG)

**Comment by alexanderzobnin** [comment]
You should use the full name of trigger, for example `UPS01 UPS On Battery` or regex. So it isn't a bug. Sorry, this should be more clear in docs.

**Comment by ignaqui** [comment]
Just to be more clear: in alarmbox I can select the item from drop-down list; in triggers panel for trigger field this feature is not implemented (obviously because the item doesn't selected)?

**Comment by alexanderzobnin** [comment]
Trigger panel uses its own editor, so it has a bit different behaviour. If you want, you can open feature request for this.
