### ISSUE TITLE
Strange behavior in graphics

### ISSUE THREAD

**Issue by tammytankian** [alexanderzobnin/grafana-zabbix#434]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [x] Question / Support request

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v4.4.1   | 3.2.7  | 3.5.1                 |

Greetings
I find this odd behaviour only when showing CPU data.
As shown in the image, the data is displayed ok, but the graph is displayed as 100%, or sometimes well beyond that.
Has anyone ever had this kind of experience or know what's going on?
Thanks for the help.

![image](https://user-images.githubusercontent.com/27218076/28622034-6ab25d3c-71e9-11e7-82ec-3287382b6eb9.png)
![image](https://user-images.githubusercontent.com/27218076/28622299-6fc1fa20-71ea-11e7-922c-0dcd24e1231a.png)
![image](https://user-images.githubusercontent.com/27218076/28622503-11ec0be2-71eb-11e7-879f-c04baf3b028b.png)
![image](https://user-images.githubusercontent.com/27218076/28622541-36d2fb6e-71eb-11e7-8deb-a67790dcd096.png)

**Comment by alexanderzobnin** [comment]
Haven't seen any odd behaviour. What exactly is wrong?

**Comment by tammytankian** [comment]
@alexanderzobnin The data says 58%, for instance, and the graph shows like its is above 100% ._.

**Comment by alexanderzobnin** [comment]
@tammytankian it's due you use stacked graph I think

**Comment by tammytankian** [comment]
Sorry for the thread, was exactly this
Thank you very much :flushed:
