### ISSUE TITLE
Expand macros in the trigger expression

### ISSUE THREAD

**Issue by ignaqui** [alexanderzobnin/grafana-zabbix#435]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature requested
- [ ] Question / Support request

Hi Alex,

Sometimes I need to show additional information from zabbix macros for host's extra fields (i.e. {HOST.DESCRIPTION}, {INVENTORY.ASSET.TAG} etc). However, it's not possible unless you send flags "expandExpression": 1 in trigger.get's payload.

Can you please enable this triggers by default?

Best regards,
ignaqui

**Comment by alexanderzobnin** [comment]
How do you want to show it? Docs say this flag expands trigger expression, but I don't use it in the triggers panel.

**Comment by ignaqui** [comment]
My plan is to add macro into zabbix template's trigger field, say {TRIGGER.URL}. Say, the macro I'm going to use is {HOST.DESCRIPTION}. I hope it will expand into value from host's description, say "my host description".

Right now in JSON return it shows:
{
...
  "url":"{HOST.DESCRIPTION}",
...
}

I looking forward after enabling expansion to see:
{
...
  "url":"my host description",
...
}

**Comment by alexanderzobnin** [comment]
Have you checked `expandExpression` flag already? You can try to edit `zabbixAPI.service.js` in the `dist/` folder and check result.

**Comment by ignaqui** [comment]
Thank you for hint, Alex. That's exactly what I need, but the thing is that after each release I need to fix the code manually

**Comment by ignaqui** [comment]
After series of tests it looks like I can expand only these macros:
`{HOST.CONN}`
`{HOST.DNS}`
`{HOST.HOST}`
`{HOST.IP}`
`{HOST.NAME}`
`{HOST.PORT}`
None of them really works for me
