### ISSUE TITLE
How can I show Text value in dashboard Graph ?

### ISSUE THREAD

**Issue by cristianodba** [alexanderzobnin/grafana-zabbix#438]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [ x] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.4.1   | 3.2.6  | 3.5.0                 |

#### What did you do?
_Describe here_

I created Item below in my zabbix server.

![image](https://user-images.githubusercontent.com/30476447/28636159-a7c10e10-7213-11e7-94e0-3e839a18698e.png)

This result text when this item was enabled.

![image](https://user-images.githubusercontent.com/30476447/28636254-fd8f0dce-7213-11e7-8efe-7805235beb98.png)

My question is !

How can I show this result text in my graph at Grafa dashboard ?

![image](https://user-images.githubusercontent.com/30476447/28636466-9c40d722-7214-11e7-8f3b-67a4df4679c6.png)

I expected result, but no show nothing in my dashboard.

**Comment by h1tman23** [comment]
You cannot do graph from text information. Choose table instead.

**Comment by alexanderzobnin** [comment]
@cristianodba yes, @h1tman23 right, graph panel is only for numeric timeseries data.
