### ISSUE TITLE
Regex usage

### ISSUE THREAD

**Issue by skyfish69** [alexanderzobnin/grafana-zabbix#44]
Is there any doc about regex description usage ?  Appreciate for any advice and thanks you very much to offer so great plugin .

**Comment by nucleusv** [comment]
Use usual regex in filter fields, for example: ^(srv1|srv2)

**Comment by alexanderzobnin** [comment]
See https://github.com/alexanderzobnin/grafana-zabbix/wiki/Usage#filters.

![regex](https://cloud.githubusercontent.com/assets/4932851/8271774/6b862482-1831-11e5-9e7d-befd3075a5ee.gif)
