### ISSUE TITLE
AggregateBy and Alerting

### ISSUE THREAD

**Issue by guhuajun** [alexanderzobnin/grafana-zabbix#440]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

Greetings,

Thanks for composing this awsome grafana plugin!

I am using Grafana 4.4.1 and grafana-zabbix 3.4.0. After reading the docs, I understand the implementation choice you have made.
But please clearify the alerting behavior when using aggregateBy function. Is it possible to setup alerting in this scenario?

![default](https://user-images.githubusercontent.com/14121694/28706045-19cb8bce-73a5-11e7-8af3-e8b8812d39e8.png)

Thanks,
Greg

**Comment by alexanderzobnin** [comment]
Hi! Alerting feature uses only triggers data from Zabbix. This means you'll see alert only if the related trigger is fired in Zabbix. So alerts don't depend on changes you've made with data in Grafana. Alerts should be defined in Zabbix if you want to see it in Grafana.

**Comment by guhuajun** [comment]
@alexanderzobnin Thanks for clarification. Now I should consider to wirte my own prometheus collector to achive my goal.
