### ISSUE TITLE
Zabbix Grafana - No data returned for Temperature query.

### ISSUE THREAD

**Issue by LaurentDumont** [alexanderzobnin/grafana-zabbix#441]
### I'm submitting a ...
- [ X ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Grafana v4.4.1  | 3.2.7 | 3.6.1 |

#### What did you do?
Trying to display temperature data using a key name of Temperature value of SW#1, Sensor#1, GREEN

#### What was the expected result?
Grafana displays the data from Zabbix.

#### What happened instead?
Grafana displays a "No data to show" error
Temperature value of SW#1, Sensor#1, GREEN

The data itself is displayed fine in Zabbix. Key name is ciscoEnvMonTemperatureStatusValue["SW#1, Sensor#1, GREEN "]

The query from the Chrome network tools looks like this

`{"jsonrpc":"2.0","result":[{"itemid":"29230","name":"$1 state","key_":"ciscoEnvMonFanState[\"Switch#1, Fan#1\"]","value_type":"3","hostid":"10116","status":"0","state":"0","hosts":[{"hostid":"10116","name":"d1.event.dhmtl.ca"}]},{"itemid":"29232","name":"$1 state","key_":"ciscoEnvMonSupplyState[\"Sw1, PS1 Normal, RPS NotExist\"]","value_type":"3","hostid":"10116","status":"0","state":"0","hosts":[{"hostid":"10116","name":"d1.event.dhmtl.ca"}]},{"itemid":"29234","name":"Temperature state of $1","key_":"ciscoEnvMonTemperatureState[\"SW#1, Sensor#1, GREEN \"]","value_type":"3","hostid":"10116","status":"0","state":"0","hosts":[{"hostid":"10116","name":"d1.event.dhmtl.ca"}]},{"itemid":"29236","name":"Temperature value of $1","key_":"ciscoEnvMonTemperatureStatusValue[\"SW#1, Sensor#1, GREEN \"]","value_type":"3","hostid":"10116","status":"0","state":"0","hosts":[{"hostid":"10116","name":"d1.event.dhmtl.ca"}]},{"itemid":"29218","name":"Unused memory for the last 5 minutes","key_":"ciscoMemoryPoolFree","value_type":"3","hostid":"10116","status":"0","state":"0","hosts":[{"hostid":"10116","name":"d1.event.dhmtl.ca"}]},{"itemid":"29216","name":"Used CPU for the last 5 minutes","key_":"ciscoCpmCPUTotal5minRev","value_type":"3","hostid":"10116","status":"0","state":"0","hosts":[{"hostid":"10116","name":"d1.event.dhmtl.ca"}]},{"itemid":"29219","name":"Used memory for the last 5 minutes","key_":"ciscoMemoryPoolUsed","value_type":"3","hostid":"10116","status":"0","state":"0","hosts":[{"hostid":"10116","name":"d1.event.dhmtl.ca"}]}],"id":1}`

Let me know if I can provide anything else!

**Comment by alexanderzobnin** [comment]
I see that query returns this item name: `Temperature value of $1`, so item should be `Temperature value of SW#1`. Try to use it instead of `Temperature value of SW#1, Sensor#1, GREEN`.

**Comment by LaurentDumont** [comment]
Unfortunately, I still get the "No Data to Show" message. I was using "Temperature value of SW#1, Sensor#1, GREEN" as it's the autocomplete value provided through the interface.

Could it be the special characters,  # and , in the key name?

**Comment by alexanderzobnin** [comment]
Ah, sorry, didn't notice the quotes. I'll check this case.

**Comment by LaurentDumont** [comment]
Hey Alexander,

Sorry no quotes on the actual metric name. It's just shown as Temperature value of SW#1, Sensor#1, GREEN

**Comment by alexanderzobnin** [comment]
No, I mean quotes in the items' key. Because I thought this metric has 3 params (SW, Sensor, Green), but all these values is a single param in quotes.
