### ISSUE TITLE
Host Group Matching/Filtering

### ISSUE THREAD

**Issue by reecewebb** [alexanderzobnin/grafana-zabbix#442]
### I'm submitting a ...
- [X ] Question / Support request

We place hosts in location (Boston, SF, Chicago) and department (Finance,HR,Support) host groups.

Is it possible to match/filter on two host groups? For instance, if I only wanted to see hosts that are in BOTH "Finance" AND "Boston"?

Thanks!
Reece

**Comment by alexanderzobnin** [comment]
No, this is impossible right now.

**Comment by secure12** [comment]
@alexanderzobnin Why?
Can't he just use a regex?:
`/Finanace|Boston/`

**Comment by volter** [comment]
You can't substitue a logical AND with a logical OR.

**Comment by secure12** [comment]
Opps sorry. I missed the "BOTH".
Maybe he can declare 2 template variables:
`$finance: {Finance}{*}` and `$boston: {Boston}{*}`

then he can query for hosts:
/(?=$finance)(?=$boston)/
to get hosts that are in both `Finance` and `Boston`

To make it even more interactive he may even declare 2 more template variables `v1` and `v2` to replace `Finance` and `Boston`.
