### ISSUE TITLE
Missing trends in Zabbix Plugin 3.3

### ISSUE THREAD

**Issue by penguin02007** [alexanderzobnin/grafana-zabbix#443]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.2.0  | 3.2   |3.3                 |

#### What did you do?
We have certain hosts that are missing trend data. History is fine on all hosts but some of the hosts have trends missing.

#### What was the expected result?
Trends should be available the host.

#### What happened instead?
Observation:
Hosts with missing data are only doing 'history.get' but not 'trend.get'
```
{jsonrpc: "2.0", method: "history.get", params: {output: "extend", history: "3",…}, id: 1,…}
auth
:
"66c7f5c86c2ff9b31e2f0812a8f34e73"
id
:
1
jsonrpc
:
"2.0"
method
:
"history.get"
```

Hosts with complete data are doing 'trend.get'
```
{jsonrpc: "2.0", method: "trend.get", params: {output: "extend", trend: "0",…}, id: 1,…}
auth
:
"d8cab655311b59be6ee8b5445b16db6c"
id
:
1
jsonrpc
:
"2.0"
method
:
"trend.get"
params
:
{output: "extend", trend: "0",…}
```
Trend data are available in Zabbix UI

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Hi! Try to upgrade plugin to recent version - here're some trend-related changes.

**Comment by penguin02007** [comment]
Same issue (partial data) after updating to 3.6.1. I see response on the request and but the value is zero... would this be an issue?
```8588
:
{itemid: "3841305", clock: "1503943157", value: "0.0000", ns: "563014722"}
8589
:
{itemid: "3841305", clock: "1503943239", value: "0.0000", ns: "701741030"}
8590
:
{itemid: "3841305", clock: "1503943378", value: "0.0000", ns: "824335835"}
8591
:
{itemid: "3841305", clock: "1503943510", value: "0.0000", ns: "465243626"}
8592
:
{itemid: "3841305", clock: "1503943601", value: "0.0000", ns: "50088090"}
8593
:
{itemid: "3841305", clock: "1503943780", value: "0.0000", ns: "844996723"}
8594
:
{itemid: "3841305", clock: "1503943962", value: "0.0000", ns: "543954208"}
8595
:
{itemid: "3841305", clock: "1503944131", value: "0.0000", ns: "445571883"}
```

**Comment by alexanderzobnin** [comment]
I can't do anything - that's correct Zabbix response. Seems, problem is on the Zabbix side.
