### ISSUE TITLE
Direct DB connection does not work with ONLY_FULL_GROUP_BY option enabled

### ISSUE THREAD

**Issue by inkonthebrink** [alexanderzobnin/grafana-zabbix#445]
If `ONLY_FULL_GROUP_BY` MySQL option enabled, queries fail. This option is enabled by default since MySQL 5.7.5.

>Reject queries for which the select list, HAVING condition, or ORDER BY list refer to nonaggregated columns that are neither named in the GROUP BY clause nor are functionally dependent on (uniquely determined by) GROUP BY columns.

**Comment by alexanderzobnin** [comment]
Can you describe an error you get?

**Comment by inkonthebrink** [comment]
no error as such. I just don't see any data on the default zabbix demo dashboard when the direct DB connection is enabled.

**Comment by nayra123** [comment]
SQL queries generated by grafana-zabbix plugin fails if you have ONLY_FULL_GROUP_BY sql mode enabled on your db. https://stackoverflow.com/questions/23921117/disable-only-full-group-by

**Comment by inkonthebrink** [comment]
Sweet. Thanks for that, I tired it and it worked! Thank you so much.

**Comment by inkonthebrink** [comment]
Thanks guys for the help.

**Comment by alexanderzobnin** [comment]
@inkonthebrink @nayra123 reopened it with new description.

**Comment by alexanderzobnin** [comment]
`ONLY_FULL_GROUP_BY` description: 
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

**Comment by alexanderzobnin** [comment]
Fixed in 35f89bf97ac7b3fddb485978adea8b44b83641ee
