### ISSUE TITLE
Grafana can not get all zabbix host groups

### ISSUE THREAD

**Issue by wangdongsong** [alexanderzobnin/grafana-zabbix#446]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [x] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.2.0  | 2.4.5  | 3.0.1                 |

In Grafana, can not get all host groups, only 9(pic 1)

. But zabbix have 18.

Query: {*}

Why?
Pic1
![1](https://user-images.githubusercontent.com/3016317/29401230-f9d5da0e-8362-11e7-819d-e5075b4cfeb9.jpg)

Pic2
![2](https://user-images.githubusercontent.com/3016317/29401304-407c4132-8363-11e7-8c28-c10a81100a28.JPG)

**Comment by alexanderzobnin** [comment]
@wangdongsong I don't know, maybe it's a permission-related issue?

**Comment by wangdongsong** [comment]
you are right, it's a permission-related.
