### ISSUE TITLE
Sort Timeseries by Name

### ISSUE THREAD

**Issue by mdorenkamp** [alexanderzobnin/grafana-zabbix#447]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.4.3   | 3.2.6  | 3.6.1                 |

#### Description
It would be nice to have a Metric Function that sorts timeseries by Name. this would make graphs much more readable when having multiple series within the same graph

**Comment by mdorenkamp** [comment]
No further work required - i already implemented this.
ill release it within the next few days.

**Comment by mdorenkamp** [comment]
Feature is included in #465

**Comment by mdorenkamp** [comment]
Feature has been merged.

**Comment by alexanderzobnin** [comment]
Thanks for the contribution!
