### ISSUE TITLE
Wrong results for Aggregations using sumSeries and Avg.

### ISSUE THREAD

**Issue by mottistartapp** [alexanderzobnin/grafana-zabbix#448]
### I'm submitting a ...
- [x ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions** 

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 3.6.1  | 2.4.7  | 4.2.0                  |

#### What did you do?
I upgraded Zabbix plugin to latest version 3.6.1 

#### What was the expected result?
Expectation no changes on existing graphs

#### What happened instead?
Singlestat with aggregation sumSeries() are incorrect.
I have sumSeries singlestat which sum all "UP" processes on several nodes. so let's sya I have 12 nodes running that process and each reports "1" as UP. when using sumSeries() I got value of 12 as expected.
After the upgrade I get different values lower than 12.

Another issue is with a graph of servers load average where I use Aggregation by Avg.(1m). the value is much lower than the minimum. the avg. is about 5 and it shows less than 1.

**Comment by alexanderzobnin** [comment]
@mottistartapp can you attach screenshots of graphs for both cases (build graph with the same metric as for singlestat)?

**Comment by mottistartapp** [comment]
Servers Load Avg. with and without Avg Aggregation:

![image](https://user-images.githubusercontent.com/9656975/29748110-6810c19e-8b17-11e7-91c0-48baddde3bad.png)


![image](https://user-images.githubusercontent.com/9656975/29748113-6efe42ec-8b17-11e7-8d33-c49ef4af532e.png)

**Comment by mottistartapp** [comment]
Graph shows 21 processes with value 1:
![image](https://user-images.githubusercontent.com/9656975/29748134-f5c4f5be-8b17-11e7-9394-983b389f12e0.png)

Single stat with sumSeries() of the same metrics shows random numbers:
![image](https://user-images.githubusercontent.com/9656975/29748135-22bcd226-8b18-11e7-8fbb-e490eb18ff84.png)

**Comment by alexanderzobnin** [comment]
For singlestat try to use groupBy() before sumSeries(), maybe there's a problem with point time stamps. Or maybe you can show _Graph shows 21 processes with value 1_ with applied sumSeries() for better problem representation?

**Comment by mottistartapp** [comment]
This is a graph of the same process with sumSeries() and indeed the last sum series are lower than the rest of the time.
I tried groupBy 1m, Max but the result is the same. only with groupBy 5m, max was good.
It wasn't like this in the previous plugin version.

![image](https://user-images.githubusercontent.com/9656975/29773245-217b7014-8c05-11e7-97d9-d2615256c44c.png)

**Comment by mottistartapp** [comment]
unfortunately when I tried it in single stat groupBy and sumSeries I didn't get the expected value even with groupBy 10m, max

**Comment by alexei-matveev** [comment]
Hi! I think aggregateBy() is buggy. It seems to rely on groupBy_perf() introduced as an optimization not so long ago. The groupBy_perf() itself appears to assume that the flattened series is ordered by the timestamp. That seems to explain the observation that only the first series seems to be processed making aggregateBy(..., max) ~= aggregateBy(..., min)

**Comment by alexei-matveev** [comment]
Well I am on 3.5.1 but look at the source of the master now:
<pre>
  for (let i=0; i < datapoints.length; i++) {
    point = datapoints[i];
    point_frame_ts = getPointTimeFrame(point[POINT_TIMESTAMP], ms_interval);
    if (point_frame_ts === frame_ts) {
      frame_values.push(point[POINT_VALUE]);
    } else if (point_frame_ts > frame_ts) {
      frame_value = groupByCallback(frame_values);
      grouped_series.push([frame_value, frame_ts]);

      // Move frame window to next non-empty interval and fill empty by null
      frame_ts += ms_interval;
      while (frame_ts < point_frame_ts) {
        grouped_series.push([null, frame_ts]);
        frame_ts += ms_interval;
      }
      frame_values = [point[POINT_VALUE]];
    }
  }
</pre>

**Comment by alexei-matveev** [comment]
I seem to be able to fix the behavior of v3.5 by this change:

https://github.com/alexei-matveev/grafana-zabbix/commit/58238216a1d531c708e34c280aee7f942dadbd3f

**Comment by alexanderzobnin** [comment]
@alexei-matveev good job! I really frustrated by Zabbix api behavior at this point. There's a problem with unsorted trend points but seems, history also affected.

**Comment by alexanderzobnin** [comment]
Fixed by 63a2594cf3acec37bfc82a7df9f195128285fae5
