### ISSUE TITLE
The group-host-item hierarchy does not work

### ISSUE THREAD

**Issue by banzayats** [alexanderzobnin/grafana-zabbix#45]
I've installed Grafana 2.0.2 and Grafana-Zabbix datasource on my Zabbix host. I'm using Zabbix 2.0.9 on Centos 6.5
When I'm trying to add a new graph I see all my groups and hosts. But when I select one of them only one option ("all")  is available to me in the following lists. It does not allow me to select any host items.

How can I debug this?

![scren](https://cloud.githubusercontent.com/assets/477161/8499654/aef70a36-219d-11e5-9af5-6b4a3996a623.png)

**Comment by nucleusv** [comment]
Select All in group and application all

**Comment by alexanderzobnin** [comment]
@banzayats Is this problem solved?

**Comment by banzayats** [comment]
@nucleusv It didn't help
![screen](https://cloud.githubusercontent.com/assets/477161/8717284/88dced20-2ba2-11e5-9d01-8bd539a1eeab.png)

**Comment by alexanderzobnin** [comment]
Try to use code from [develop](https://github.com/alexanderzobnin/grafana-zabbix/tree/develop) branch.

**Comment by alexanderzobnin** [comment]
@banzayats problem with `All` applications fixed - try to use code from [develop](https://github.com/alexanderzobnin/grafana-zabbix/tree/develop) branch.

**Comment by banzayats** [comment]
@alexanderzobnin 
Thank you. I've used the code from development branch and now hierarchy works fine.
