### ISSUE TITLE
If Grafana is unable to connect to the datasource and has public mode enabled, zabbix credentials are viewable in plain text

### ISSUE THREAD

**Issue by Just-Insane** [alexanderzobnin/grafana-zabbix#450]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.2.0   | 3.2.7  | 3.3.0                 |

#### What did you do?
If Grafana is available in public mode (auth.anonymous) and Zabbix is unable to be reached, there will be an error message (red flag in top left corner of panels that use Zabbix. If you click on this panel, and go to the request tab, it is possible to see the output of the request to the zabbix API, which contains cleartext usernames and passwords for the zabbix instance.

#### What was the expected result?
Cleartext usernames and passwords should not be visible, even during a fault.

#### What happened instead?
Cleartext usernames and passwords, as well as API URIs are available in cleartext during an error.

![screen shot 2017-08-27 at 11 30 53 pm](https://user-images.githubusercontent.com/15903884/29759304-7174b896-8b88-11e7-97d2-7611f756a71f.png)

**Comment by alexanderzobnin** [comment]
That's how Zabbix api works, unfortunately. See #380 for details. Good solution is moving auth-related queries to backend, but I can't do it until we implement backend plugins in Grafana.
