### ISSUE TITLE
Feature request: offset function

### ISSUE THREAD

**Issue by sandersaares** [alexanderzobnin/grafana-zabbix#451]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

I request an "offset" function to be added to the queries. This would be a simple addition of a numeric value.

Use case: I have an "CPU idle %". I want to get "CPU used %" from this. To do this, I want to apply a `1-x` formula. Right now, the plugin enables me to get the `-x` by scaling by -1 but I cannot add or subtract anything.

**Comment by gelonsoft** [comment]
+1

**Comment by alexanderzobnin** [comment]
I think this duplicates #387, so I'm closing this.
