### ISSUE TITLE
zabbix-dashboard is showing nothing in grafana.

### ISSUE THREAD

**Issue by saeedkm** [alexanderzobnin/grafana-zabbix#454]
<img width="1920" alt="screen shot 2017-09-01 at 6 35 48 am" src="https://user-images.githubusercontent.com/5578038/29951406-20f64276-8ee0-11e7-8336-ac3eba41fe76.png">
I have installed zabbix plugin for grafana and configured it. but it is not showing in grafana.

Zabbix 2.4 

<img width="1148" alt="screen shot 2017-09-01 at 6 36 50 am" src="https://user-images.githubusercontent.com/5578038/29951402-191c8f1a-8ee0-11e7-90b8-777300721de7.png">

**Comment by saeedkm** [comment]
<img width="1031" alt="screen shot 2017-09-01 at 6 46 06 am" src="https://user-images.githubusercontent.com/5578038/29951577-42272784-8ee1-11e7-9aa4-9565fd84c262.png">

**Comment by echel0n** [comment]
I am having the same issue, running Zabbix 3.4

**Comment by alexanderzobnin** [comment]
Related to #445

**Comment by machytkafitanalytics** [comment]
Hi, I have the same issue with Zabbix 3.4 - data source (with direct db connection) during "save & test" shows green but gives me message "Zabbix API version: undefined"
