### ISSUE TITLE
About using templating variables in the matrics item

### ISSUE THREAD

**Issue by answer99** [alexanderzobnin/grafana-zabbix#455]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

I would like to know...  as title,
When adding a query, I can use the variables in Group, Host and Application, in this form( $var), but when I put it into a text of the item, the data did not return anything as a result. For example like below:
Item: myItem[[var1]]
I don't know is that a bug or maybe not support yet, so I just ask a question here. (have looked previous issues)
Thanks in advance.

**Comment by answer99** [comment]
I got it, thanks!

**Comment by prokopenkopn** [comment]
I've got similar problem. Query with 'Item:p_ts[_TEST_pctfree]' works, 
but if I try to use a variable in "Item:p_ts[_[[tablespace]]_pctfree]",
the query does not work (returns "no value"). What may be the problem?
