### ISSUE TITLE
No data: Message: momentInterval is null

### ISSUE THREAD

**Issue by krzychu135** [alexanderzobnin/grafana-zabbix#458]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.4.3   | 3.0.9  | 3.6.1                 |

#### What did you do?
I have configured new datasource for my zabbix server. Got green OK.

#### What was the expected result?
Zabbix Server Dashboard showing data.

#### What happened instead?
Zabbix Server Dashboard is not getting any data from zabbix.
Inspector shows 
Message:
momentInterval is null
Stack trace:
parseInterval@http://localhost:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/utils.js?bust=1504692239535:178:5
isUseTrends@http://localhost:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1504692239535:790:44
query/promises<@http://localhost:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1504692239535:316:31
l@http://localhost:3000/public/app/boot.07485e0c.js:62:25196
Sg@http://localhost:3000/public/app/boot.07485e0c.js:63:25883
query@http://localhost:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js?bust=1504692239535:290:28
execute/k</b.prototype.issueQueries@http://localhost:3000/public/app/boot.07485e0c.js:56:14693
i@http://localhost:3000/public/app/boot.07485e0c.js:52:15288
l/<@http://localhost:3000/public/app/boot.07485e0c.js:52:15710
$eval@http://localhost:3000/public/app/boot.07485e0c.js:52:22861
$digest@http://localhost:3000/public/app/boot.07485e0c.js:52:21330
$apply@http://localhost:3000/public/app/boot.07485e0c.js:52:23146
f/j<@http://localhost:3000/public/app/boot.07485e0c.js:52:30504
f@http://localhost:3000/public/app/boot.07485e0c.js:51:1419
pb/k.defer/c<@http://localhost:3000/public/app/boot.07485e0c.js:51:2882

**Comment by alexanderzobnin** [comment]
What is the _Range_ parameter in your config?

**Comment by krzychu135** [comment]
Thanks
That was the problem. I had just 30 without suffix.
Changed to 7d and works fine.
