### ISSUE TITLE
Названия элиментов в шаблоне

### ISSUE THREAD

**Issue by logicall** [alexanderzobnin/grafana-zabbix#46]
Александр, день добрый!

Я настроил получение данных из zabbix через шаблоны и столкнулся с проблемой. А именно - если выбоать отображение всех элиментов (All), то в подписи графика они передаются списком и не понятно к какому элементу это относится (скрин приложил)
![graph](https://cloud.githubusercontent.com/assets/222279/8516077/f622ddce-23b7-11e5-9d6f-247cd9029b6b.JPG)
Сам шаблон выглядит так
![template](https://cloud.githubusercontent.com/assets/222279/8516080/0006bf4a-23b8-11e5-8974-b9ebf2423be3.JPG)

Скажите, есть ли какой способ отображения при выборе всех элементов, чтобы они отображались  не списком, а поэлементно?
Спасибо!

**Comment by nucleusv** [comment]
Это скорее баг, раньше было все ОК.

**Comment by logicall** [comment]
У меня grafana версии 
Grafana version: 2.1.0-pre1, commit: v2.0.2+421-g20d5d0e, build date: 2015-06-26 20:42:33
А ваш плагин последния commit от 29 июля

А можно как-то понять это баг плагина или grafana?

**Comment by logicall** [comment]
И еще... Если выбирать по одному элементу - то все нормально отображается
![graph1](https://cloud.githubusercontent.com/assets/222279/8516347/cfe12b80-23bb-11e5-8c21-c1650ed079cb.JPG)

**Comment by nucleusv** [comment]
К самой графане это не относится, Саша просто делал правки, это момент наверно не учел, это баг плагина. Ждите вечера :) Ответит

**Comment by alexanderzobnin** [comment]
Да, это, действительно, баг. Исправлю в ближайшее время.

**Comment by logicall** [comment]
Спасибо!
Буду ждать....

**Comment by alexanderzobnin** [comment]
Исправлено - можете скачать из [release](https://github.com/alexanderzobnin/grafana-zabbix/tree/release-2.0.0)-ветки или дождаться релиза через пару дней.

**Comment by logicall** [comment]
Спасибо!
Щас попробую

**Comment by logicall** [comment]
Все великолепно работает теперь!
Думаю можно закрывать.
Спасибо!

**Comment by alexanderzobnin** [comment]
Не за что. Я сослался в коммите на этот тикет, так что он закроется автоматически, когда я в master-ветку залью.
