### ISSUE TITLE
Grafana displays no data, HTTP status code 500

### ISSUE THREAD

**Issue by echel0n** [alexanderzobnin/grafana-zabbix#460]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.4.3   | 3.4.1  | 3.6.1                 |

#### What did you do?
Loaded Zabbix Server Dashboard

#### What was the expected result?
Data to be shown

#### What happened instead?
No data points
![bb97f9539bd47ebc7e46a50d9cb292e0](https://user-images.githubusercontent.com/1128022/30258033-053981be-9684-11e7-8f3f-a31916879386.png)

/var/log/grafana/grafana.log shows the following HTTP status 500 codes:
```
t=2017-09-11T03:49:21+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.203 time_ms=11 size=797 referer="http://nms.local:3000/dashboard/db/zabbix-server-dashboard?orgId=1"
t=2017-09-11T03:49:21+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.203 time_ms=14 size=951 referer="http://nms.local:3000/dashboard/db/zabbix-server-dashboard?orgId=1"
t=2017-09-11T03:49:21+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.203 time_ms=6 size=812 referer="http://nms.local:3000/dashboard/db/zabbix-server-dashboard?orgId=1"
t=2017-09-11T03:49:21+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.203 time_ms=25 size=812 referer="http://nms.local:3000/dashboard/db/zabbix-server-dashboard?orgId=1"
t=2017-09-11T03:49:21+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.203 time_ms=90 size=839 referer="http://nms.local:3000/dashboard/db/zabbix-server-dashboard?orgId=1"
t=2017-09-11T03:49:21+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.203 time_ms=119 size=951 referer="http://nms.local:3000/dashboard/db/zabbix-server-dashboard?orgId=1"
```

**Comment by echel0n** [comment]
OK I was able to resolve this issue by disabling "ONLY_FULL_GROUP_BY" for MySQL by adding the following like to the end of /etc/mysql/mysql.conf.d/mysqld.cnf

```
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

**Comment by alexanderzobnin** [comment]
Related to #445

**Comment by cuongnguyenvan** [comment]
Hi alexanderzobnin,
I'm using grafana and zabbix. But when i showed "Last 12 hours" or "Last 24 hours", i accidentally Zabbix API Error, Connection error. When i showed "Last 6 hours, Last 3 hours, Last 1 hours is OK.
This i my log:
Sep 20 17:05:09 bd-controller-backup grafana-server: t=2017-09-20T17:05:09+0700 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/zabbix/api_jsonrpc.php status=500 remote_addr=113.190.252.218 time_ms=7343 size=0 referer="http://210.211.120.203:3000/dashboard/db/report-vms?orgId=1&from=now-24h&to=now"
Sep 20 17:05:09 bd-controller-backup grafana-server: t=2017-09-20T17:05:09+0700 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/zabbix/api_jsonrpc.php status=500 remote_addr=113.190.252.218 time_ms=7349 size=0 referer="http://210.211.120.203:3000/dashboard/db/report-vms?orgId=1&from=now-24h&to=now"
I disabled ONLY_FULL_GROUP_ONLY but not ok. 
Please help me fix this error.
Thanks.
