### ISSUE TITLE
Edit data source  warning error

### ISSUE THREAD

**Issue by mh011160** [alexanderzobnin/grafana-zabbix#461]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [1 ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.4.3  |3.2.6  | 3.6.1                 |

#### What did you do?
hello,
Now that I am configuring the data source on the grafana page, the mysql data source has been added successfully, and when I add zabbix data, I am prompted to connect the error. Do I need to change the configuration file?

![error](https://user-images.githubusercontent.com/31916610/30365088-42ab566e-9899-11e7-93c4-dc7a7e53d5f0.png)

Please help me, thanks

**Comment by alexanderzobnin** [comment]
Try to use Proxy mode instead of Direct.
