### ISSUE TITLE
The value obtained from Zabbix by Direct DB Connection and API respectively differs.

### ISSUE THREAD

**Issue by GoodLights** [alexanderzobnin/grafana-zabbix#464]
### I'm submitting a ...
- [ 1] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin | 
| ------- | ------ | --------------------- |
| 4.5.2   | 3.4.0  | 3.6.1                 | 

#### What did you do?
Hello.
We set avg (1h), min (1h), max (1h) in Functions at Grafana 's Metrics.
Also, Trends' check is turned off with Zabbix API details.
Also, the data selection period will be the previous month.
All items on Zabbix side become Zabbix Trapper,
The retention period of History is 90 days, and the retention period of Trends is 365 days.
I found it when comparing values displayed via Direct DB Connection and API.

#### What was the expected result?
Since the selection period is the previous month, values from History are displayed for both API and Direct DB Connection.

#### What happened instead?
In the case of Direct DB Connection, the value of Trends is displayed even though it is within the period of History in Zabbix.
On the other hand, in the case of via the API, the value of History is displayed correctly.

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Can you post your plugin's config (trends section)?

**Comment by GoodLights** [comment]
config is as follows.
Also, because xxxxxx is an IP address, user name, password, DB name,
Disclosure is not possible.

The Zabbix Host groups' Group name, Hosts' Visible name, Items' Name are all multibyte notation.

-------------------------------------------------------------

Edit data source
 Name : zabbix
 Type : Zabbix

 http settings
  Url : https://xxxxxx/zabbix/api_jsonrpc.php
  Access : direct

 Http Auth
  Basic Auth : No
  With Credentials : No

Zabbix API details
  Username : xxxxxxx
  Password : xxxxxxx
  Trends : No
  Cache TTL : Default(1h)

Direct DB Connection
  Enable : Yes
  SQL Data Source : xxxxxxx

Alerting
  Enable alerting : No

-------------------------------------------------------------

Graph Metrics
  Data Source : zabbix
  Query Mode : Metrics
  Group : hostgroup(multibyte)
  Host : hostname(multibyte)
  Application : Default(Null)
  Item : itemname(multibyte)
  Functions
   #1 : average(1h)
   #2 : setAlias(itemname(multibyte))

**Comment by alexanderzobnin** [comment]
That's strange. Can you check network request in browser dev tools and ensure there was trends query?
