### ISSUE TITLE
got triggers data but not values from any items

### ISSUE THREAD

**Issue by TheFausap** [alexanderzobnin/grafana-zabbix#466]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

Hello,

I have a lot of host groups configured on zabbix and never got a problem with them, but with just one, I am not able to gather any data from the metric items, only the triggers panel works.

The data are present on zabbix and I did not receive any error from grafana plugin.

Anyone got this issue before ? 

thanks,
Fausto

**Comment by alexanderzobnin** [comment]
check permissions for the zabbix user set in data source config
