### ISSUE TITLE
Missing dependency:  tether-drop  

### ISSUE THREAD

**Issue by Spindel** [alexanderzobnin/grafana-zabbix#467]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.0-beta2   | 3.0.x  | 3.5.1                |

#### What did you do?
Load my old configuration that uses the zabbix trigger panel

#### What was the expected result?
Loaded panel

#### What happened instead?
404 error for sub part

This is a default docker container grafana/grafana. 
Apparantley this is fixed in master, but not quite easily available yet. Can we get a release of grafana-zabbix rolled out so a default grafana install stays working?

**Comment by alexanderzobnin** [comment]
That fixed in 630dd176595f824535a1bc299245ff2b531d4a18 and will be in next release soon.
