### ISSUE TITLE
Cannot add a function to query from typeahead

### ISSUE THREAD

**Issue by zaben903** [alexanderzobnin/grafana-zabbix#468]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.5.2   | 3.2.3  | 3.6.1                 |

#### What did you do?
Attempt to add a function to a dashboard

#### What was the expected result?
function (eg rate() ) is added to query mode for an item

#### What happened instead?
The function removes itself and the following error is created:

```
TypeError: $scope.addFunction is not a function
    at eval (add-metric-function.directive.js:48)
    at o.$eval (boot.e4836696.js:61)
    at o.$apply (boot.e4836696.js:61)
    at b.updater (add-metric-function.directive.js:47)
    at b.select (boot.e4836696.js:8)
    at b.click (boot.e4836696.js:8)
    at HTMLUListElement.e (boot.e4836696.js:56)
    at HTMLUListElement.dispatch (boot.e4836696.js:57)
    at HTMLUListElement.q.handle (boot.e4836696.js:57)
(anonymous) @ boot.e4836696.js:60
```

#### Conditions where it was created:
B - Query Mode: Metrics
Group: someGroup
Host: someHost
Application: someApplication
Item: SomeItem
Functions: (ATTEMPTING TO PUT rate() FUNCTION HERE)

**Comment by alexanderzobnin** [comment]
Looks strange. How did you install plugin? Try to clear browser cache.

**Comment by zaben903** [comment]
The plugin was installed following the cli install step (In the README). Tested with cache disabled (including different devices) and problem still persists.

Update to the issue:
Grafana version: 4.6.2
Grafana-zabbix plugin: 3.7.0

**Comment by zaben903** [comment]
The specific method to reproduce is to start to type for a function (such as rate) and select from the drop-down. This fails.

The method I have tried which I am using as a workaround is to not type but to go through the drop-down menu manually to select the function to use.

This is checked again using grafana-zabbix plugin version 3.8.1

**Comment by alexanderzobnin** [comment]
Yes, confirmed. Thanks for the clarification.

**Comment by chriskuipers** [comment]
Hi! Any updates on this bug? We're having the same issues. We're running Grafana 6.1.6, Zabbix 3.0.22 and the 3.10.2 plugin version.
