### ISSUE TITLE
System Dashboard error

### ISSUE THREAD

**Issue by xdexter** [alexanderzobnin/grafana-zabbix#472]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Grafana v4.6.0-beta2 (commit: fff4cfd)   | 2.4.8  | 3.7.0 |

#### What did you do?
I imported the "Zabbix System Dashboard" (https://github.com/alexanderzobnin/grafana-zabbix/blob/e2fd7d895c1ff5b1062a1ff98ffb76bae3282de3/dist/datasource-zabbix/plugin.json) and openned the Dashboard.

#### What was the expected result?
See dashboard correctly

#### What happened instead?
Errors in all panels

![zabbix_system_status](https://user-images.githubusercontent.com/10849509/31966538-c6c72e08-b8e9-11e7-94ae-28dbd1853202.png)

**Comment by alexanderzobnin** [comment]
Did you import it through the data source config page?

**Comment by xdexter** [comment]
Hi,

Perfect, now all works, thank you!

Regards
