### ISSUE TITLE
When I configured the zabbbix plugin in grafana, an error occurred

### ISSUE THREAD

**Issue by mervinxue** [alexanderzobnin/grafana-zabbix#474]
### I'm submitting a ...
- [x] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.5.1   | 3.4.1  | 3.7.0                 |

#### What did you do?
![2017-10-26_zabbix-plugin issue](https://user-images.githubusercontent.com/20356700/32046318-514870f0-ba75-11e7-8fe1-761c2b30d97f.png)
![2017-10-26_174704](https://user-images.githubusercontent.com/20356700/32046463-b6c8693a-ba75-11e7-8bb2-30f726881e79.png)

#### What was the expected result?
connect successfully

#### What happened instead?
None

**Comment by alexanderzobnin** [comment]
you have a typo in the address. Correct is `api_jsonrpc.php`.

**Comment by mervinxue** [comment]
thx.
