### ISSUE TITLE
socks5 proxy support for zabbix datasource in proxy mode

### ISSUE THREAD

**Issue by Raghvendra77** [alexanderzobnin/grafana-zabbix#476]
### I'm submitting a ...
- [ ] Bug report
- [x ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0.0  |3.0.10  | 3.6.1              |

We have Zabbix server running behind socks5 proxy.  Grafana can connect to zabbix datasource in "direct " mode  when we have socks5 proxy configured in browser. 
But it will be great if  Grafana can connect to Zabbix running behind socks proxy in "proxy" mode. 
This way every user who is accessing  Grafana dashboard (With Zabbix as datasource) doesn't have to modify his/her browser proxy setting.

How does  this Grafana Zabbix plugin connects to zabbix datasource in proxy mode ? what system call its uses ? Does it uses curl or what ? If we know this then for time being we can have a work around via proxychain

**Comment by alexanderzobnin** [comment]
In _proxy_ mode all queries are sent by grafana server, not by the plugin.
