### ISSUE TITLE
Zabbix Triggers panels throw error and do not appear after Grafana 4.6.1 migration

### ISSUE THREAD

**Issue by louzadod** [alexanderzobnin/grafana-zabbix#477]
### I'm submitting a ...
- [X ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.1 | 3.0.5 |   3.7.0                |

#### What did you do?
I migrated my Grafana from 4.5.2 to 4.6.1.

#### What was the expected result?
Open existing Zabbix Trigger panels normally

#### What happened instead?
The following error message from Grafana was shown:

"Plugin Error
Fetch error: 404 Not Found Instantiating http://myserver:3000/public/tether-drop Loading http://myserver:3000/public/plugins/alexanderzobnin-zabbix-app/panel-triggers/ack-tooltip.directive.js Loading plugins/alexanderzobnin-zabbix-app/panel-triggers/module"

If it relates to metric data visualization would be great to get
![error-zabbix-01](https://user-images.githubusercontent.com/704784/32374321-41e7a47c-c084-11e7-9b50-ee57dda840e9.png)

**Comment by alexanderzobnin** [comment]
Duplicated #475
