### ISSUE TITLE
getting _.IndexBy is not a function error in Grafana 4.6.1

### ISSUE THREAD

**Issue by Pyroman1985** [alexanderzobnin/grafana-zabbix#479]
### I'm submitting a ...
- [ X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.1  | 3.4.3  | 3.7.0                 |

#### What did you do?
Tried to view hosts metric

#### What was the expected result?
retrieve host metric data and display in graph 

#### What happened instead?
For every time of metric i'm getting the below:
_.IndexBy is not a function
![image](https://user-images.githubusercontent.com/17449648/32522574-80e82364-c420-11e7-9426-1d7eb9e8a2de.png)

QueryInspector seems to retrieve the data but yet not able to display in the graph:
![image](https://user-images.githubusercontent.com/17449648/32522614-af1002de-c420-11e7-8e17-d915ece5651f.png)

Appreciate your help with this, if i'm reaching to far and need to downgrade to a previous version don't mind doing so.

Thanks!

**Comment by alexanderzobnin** [comment]
@Pyroman1985 can't replicate this. From which grafana version did you update?

**Comment by Pyroman1985** [comment]
Thanks for your fast reply, i was updated from Grafana 2.0.4.

I have reverted back to that version and will try to update first to 3.X version and then to 4.X.

hoping this will resolve the issue, will update later today.

Thanks again!

**Comment by Pyroman1985** [comment]
Hi,

So, i was on 3.0.4 and not 2.0.4 as i wrote above.
I have updated to the latest of 3.X version, checked to verify it is working and it did,
Then i have updated to the 4.6.0 and it was also working, and final step was to update to the latest version 4.6.1 and appears this was fixed the problem.

Thank you!

**Comment by alexanderzobnin** [comment]
Maybe that was a cache-related problem.
