### ISSUE TITLE
unix time format support

### ISSUE THREAD

**Issue by skyfish69** [alexanderzobnin/grafana-zabbix#48]
Hi ,

Just want to show the time of host on the dashboard template ,but find that there is no unit the metrics which can be used to handle the unixtime format from zabbix monitoring item(host local time).It will be nice if added in next version.

**Comment by alexanderzobnin** [comment]
Hello! Which type of panel you mean? Singlestat?

**Comment by nucleusv** [comment]
Datasource is responsible for series export only to Grafana, it doesn't deal with units. You should create issue to Grafana repo.
