### ISSUE TITLE
[Feature] Zabbix Triggers panel - Add disable acknowledgement option

### ISSUE THREAD

**Issue by dodikvt** [alexanderzobnin/grafana-zabbix#481]
It would be nice to have option to disable acknowledge event in Zabbix trigger panel.

I need to disable acknowledgement option for user with viewer roles. Maybe it would be great if acknowledgement option could follow user role.

Disabled acknowledgement for role Viewer
Enable acknowledgement for role Editor, Admin

**Comment by alexanderzobnin** [comment]
![screenshot from 2018-03-23 19-15-03](https://user-images.githubusercontent.com/4932851/37840571-82c177b2-2ece-11e8-8637-a6f410d730fb.png

**Comment by TheNetworkGuy** [comment]
Hi,

Can  this feature be a bit more polished out in the new trigger "table" view? As a read-only user i can press the acknowledge button and type some text. When i send / submit the data it doesn't actually get forwarded to Zabbix but for read only users its just another button that "doesn't do anything". Graying it out for example with the list view would be great :)

**Comment by alexanderzobnin** [comment]
@TheNetworkGuy Yes, that makes sense.
