### ISSUE TITLE
min_severity setting ignored for annotations

### ISSUE THREAD

**Issue by volter** [alexanderzobnin/grafana-zabbix#482]
### I'm submitting a ...
- [x ] Bug report

The annotations configuration allows to choose a minimum severity. Looking at the requests and results, it is apparent that min_severity is not actually used. My assumption is, that min_severity is not actually set in getTriggers().

**Software Versions**

Grafana 4.6.1, Zabbix 3.0, Plugin 3.7

#### What did you do?

Set a minimum severity

#### What was the expected result?

Only request triggers matching that minimum severity

#### What happened instead?

All of them were requested

**Comment by alexanderzobnin** [comment]
Hm, can't replicate - can you show your zabbix api request?
