### ISSUE TITLE
[Feature Request] Trigger Pannel option to don't collapse trigger description 

### ISSUE THREAD

**Issue by Eleazarus** [alexanderzobnin/grafana-zabbix#483]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request

I have to use trigger names that are somehow hard to read because of the way I fill my Zabbix inventory with API. 

Example :  trigger.systemInformation.app.filemanipulationerror.warning

The description field is used as a more user friendly readable trigger name (Let's say "File Manipulation Error". Right now, I only have the possibility to click on the trigger to show the description.

Is it possible to add an option to show the trigger description instead of the trigger name, or an option to chose which we wanna show?

**Comment by Eleazarus** [comment]
Hello. If all of this doesn't seem reasonable to do (considering this feature request was ignored), a show description by default option, without clicking, could at least do part of the job.

**Comment by alexanderzobnin** [comment]
Ok, I renamed it.

**Comment by alexanderzobnin** [comment]
Implemented

![screenshot from 2017-12-14 19-42-09](https://user-images.githubusercontent.com/4932851/34004143-29d8003a-e108-11e7-802e-888b6e4ef825.png)
