### ISSUE TITLE
ZABBIX API ERROR 

### ISSUE THREAD

**Issue by PablloSoares** [alexanderzobnin/grafana-zabbix#484]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 4.6.1 | 3.4.3 | 3.7.0 |
    

#### What did you do?

Recently without any explanation started to appear this error message in the Grafana interface, I already checked the log and it contains nothing there, can anyone help me?

![002](https://user-images.githubusercontent.com/33694758/32852843-5d386e1e-ca20-11e7-9a94-7056713d0fc5.jpg)

![001](https://user-images.githubusercontent.com/33694758/32852826-500b3438-ca20-11e7-8deb-c239c6569b53.jpg)

#### What was the expected result?
_Describe here_

#### What happened instead?
_Describe here_

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Check web server's logs. Looks like memory limitation.

**Comment by PablloSoares** [comment]
Can you explain how to do this?

**Comment by alexanderzobnin** [comment]
Explain how to check web server's log? Just log in to zabbix server and check apache log. See also #389, #407.
