### ISSUE TITLE
Handle newlines in trigger descriptions

### ISSUE THREAD

**Issue by vzabauski** [alexanderzobnin/grafana-zabbix#485]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request

I'm not sure, if this or bug or not, but anyway, it would be nice if Grafana-Zabbix plugin was able to handle newlines in trigger description.

Zabbix handles newlines in trigger descriptions:

![2](https://user-images.githubusercontent.com/17778043/32953879-94b1a31c-cbc2-11e7-8670-d4164ab04747.JPG)

Grafana skips newlines

![1](https://user-images.githubusercontent.com/17778043/32953891-a08d4a42-cbc2-11e7-9a14-44739387fab0.JPG)

I've checked Zabbix API response and determined that newlines are being skipped on Grafana side, response JSON contains newlines.

Maybe it would be nice if Grafana-Zabbix plugin was able to handle other special characters but it's completely up to you.
Thanks in advance.

**Comment by alexanderzobnin** [comment]
Yes, I should convert newlines to HTML tags.
