### ISSUE TITLE
Query does not fetch all hostgroups

### ISSUE THREAD

**Issue by Colgaton** [alexanderzobnin/grafana-zabbix#486]
### I'm submitting a ...
- [ x] Bug report

### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| grafana-4.1.2-1486989747   | zabbix-2.2  | 3.7.0             |

#### What did you do?
Trying to  create a template. When selecting the Zabbix Datasource, and running the query: * I only get about half of the Hostgroups from Zabbix, the others are missing. If I reference them in the query: "API Servers.*", I got nothing.

#### What was the expected result?
I should get all the hostgroups

#### What happened instead?
Getting less than half

**Comment by alexanderzobnin** [comment]
How many groups do you get? Grafana limits visible result to 20 values in template variable editor.

**Comment by Colgaton** [comment]
I have less than 20. But in the template editor I get less than 10.

If I try the following query: Amazon.* it bring's me the servers inside Amazon hostgroup.

If I try the same query for a hostgroup that is not showing up, I get None.

**Comment by hamsjelv** [comment]
Hi, 

zbx 3.4.8
Grafana 5.3.1
grafana-plugin 3.9.1

We have 466+ host groups and 4500+ hosts in Zabbix.

When i want to create a graph / singlestat for a host item i Zabbix, i start by locating the host group.
the host groups name starts with "RSD -" but Grafana can only list a specific number of host groups - so i cant find host-group "RSD - Something". 
Grafana only returns host groups from "RSD -" from a-i... thats as far as it will go... like its a static number of host groups like 115.

If i search for "RSD -" in zabbix i get 263.

I had to add my server to a host group within the list of 115 host groups, to be able to use it in grafana.

Hope this makes sense to you and thank you for the good work you have done here.

Regards

/Martin

**Comment by jedd** [comment]
Hi Martin,

This *might* be related to a bug we've seen with some version permutations where permissions weren't being automatically updated on the Zabbix side.

On your Zabbix sever can you check the group permissions for the account you're using to share to Grafana?  You probably want 'all : read'  - and if you see various hostgroups as deny, then this may explain the discrepancy.
