### ISSUE TITLE
Cannot acknowledge problem: event is not in PROBLEM state.

### ISSUE THREAD

**Issue by arbalet1985** [alexanderzobnin/grafana-zabbix#488]
Cant acknowledge resolved problem in status "OK" (Zabbix 3.4.4, plugin 3.7.0) This worked for zabbix 3.0
![error](https://user-images.githubusercontent.com/5121906/33001319-f649ec20-cdce-11e7-92f6-dbffc62da058.gif)

**Comment by alexanderzobnin** [comment]
This is Zabbix API limitation, I can't do anything to solve this problem.
