### ISSUE TITLE
Invalid params. \ Incorrect API "trend".

### ISSUE THREAD

**Issue by whiteud** [alexanderzobnin/grafana-zabbix#489]
**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.2   | 2.4.8  | 3.7.0                 |

#### What did you do?
Nothing

#### What was the expected result?
I see in query editor this error:

xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/1"
data:Object
jsonrpc:"2.0"
method:"trend.get"
params:Object
output:"extend"
trend:"3"
itemids:Array[1]
0:"77166"
sortfield:"clock"
sortorder:"ASC"
time_from:1509608259
time_till:1509615770
id:1
auth:"826cc76e309121645ef5bc98d958b08c"
response:Object
jsonrpc:"2.0"
error:Object
code:-32602
message:"Invalid params."
data:"Incorrect API "trend"."
id:1

#### What happened instead?
Graph not working

But nothing to change

**Comment by alexanderzobnin** [comment]
You should install a patch for trends for zabbix versions before 3.0
http://docs.grafana-zabbix.org/installation/configuration/
