### ISSUE TITLE
Не видит текстовых метрик Zabbix 

### ISSUE THREAD

**Issue by JKeySZR** [alexanderzobnin/grafana-zabbix#49]
Здравствуйте!

При добавлении метрик , в списке отсутствуют метрики у которых "Тип информации" в ZABBIX
Текст или журнал.

Как их можно добавить в "Single Stat" ?

**Comment by alexanderzobnin** [comment]
А вы используете новую версию Grafana (2.1)?

**Comment by alexanderzobnin** [comment]
Дело в том, что в Grafana 2.0 текстовые метрики в singlestat-панели не поддерживаются. Их поддержка добавлена в 2.1, но она еще не вышла. Поэтому на данный момент в редакторе фильтруются все нечисловые метрики. После выхода Grafana 2.1 я планирую добавить их поддержку в singlestat.

**Comment by JKeySZR** [comment]
Использую Grafana
 Version: 2.0.2, Commit: v2.0.2, Build date: 2015-04-22 18:51:50 +0300 MSK

Ясно, будем ждать. Спасибо, за быстрый ответ!

**Comment by alexanderzobnin** [comment]
Перемещено в #71
