### ISSUE TITLE
Query editor not visible

### ISSUE THREAD

**Issue by lalinsky** [alexanderzobnin/grafana-zabbix#490]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.2   | 3.0.3  | 3.7.0                 |

#### What did you do?

I just upgraded my Grafana to 4.6.2 and the Grafana-Zabbix plugin to 3.7.0 and I'm not longer able to edit Zabbix queries.

#### What was the expected result?

I open a create a new graph, select then Zabbix data source and then I'm able to edit the query.

#### What happened instead?

The query is not visible. Old dashboards still work in view mode, but the editor is broken.

You can see what it looks like at https://imgur.com/a/giMRW 

It works fine in 3.6.1.

**Comment by alexanderzobnin** [comment]
Try to clear browser cache.

**Comment by lalinsky** [comment]
I'm very sorry. I tried refreshing the page a few times before, but I guess some cached files survived even that. I now cleared the entire cache and it works.
