### ISSUE TITLE
regression: text data is empty for timeseries aggregation

### ISSUE THREAD

**Issue by ptempier** [alexanderzobnin/grafana-zabbix#492]
### I'm submitting a ...
- [x ] Bug report
- [ ] Feature request
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v4.6.2    |3.2.6  | 3.7.0            |

#### What did you do?
try to show text data in time serie aggregation
example , various services report their versions via a string
we display a table with a time serie aggregation to show the last version for each service

#### What was the expected result?
correct text/version displayed

#### What happened instead?
the table cell is empty

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

query inspector result , so the data is there, but the cell is empty
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/1"
data:Object
jsonrpc:"2.0"
method:"history.get"
params:Object
id:1
auth:"0xxxd"
response:Object
jsonrpc:"2.0"
result:Array[2]
0:Object
itemid:"2300301"
clock:"1512125512"
value:"7.8-354"
ns:"801251797"
1:Object
itemid:"2300301"
clock:"1512125633"
value:"7.8-354"
ns:"569943520"
id:1

**Comment by alexanderzobnin** [comment]
Have you noticed, does it work with previous Grafana versions? It's grafana-related issue, because zabbix plugin just returns series with string values and then table panel tries to aggregate it.

**Comment by ptempier** [comment]
Hello

Yes, it was working before grafana update.
Can t remember if i updated the plugin at the same time than grafana.

**Comment by ptempier** [comment]
:/ Updated both grafana and the plugin, still got the same issue.

**Comment by alexanderzobnin** [comment]
Yes, working on the feature which can fix this (table format support).

**Comment by ptempier** [comment]
Haa cool, thanks a lot :)

**Comment by alexanderzobnin** [comment]
Fixed by 60017618f1a5128255e1d8feecf63be143a79670
