### ISSUE TITLE
Zabbix Triggers Info not interpreting macro in URL in trigger

### ISSUE THREAD

**Issue by jgerry2002** [alexanderzobnin/grafana-zabbix#494]
### I'm submitting a ...
- [X ] Bug report
- [ ] Feature requested
- [X ] Question / Support request

The info button in the Trigger Panel in Grafana is not interpreting macro properly in a trigger. Perhaps it can't do this? 

I have http://{HOST.IP} in the URL section of the trigger, which in Zabbix will properly translate to the URL of the device for easy troubleshooting. Example http://192.168.0.125

In Grafana I get "http://%7Bhost.ip%7D/" for each URL. It appears the translation for the device is lost when using the Trigger Panel.

Is this a bug or is there a way to actually do this so it shows the host.ip of the device for each trigger?

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.2-1   | 3.4.4-2 | 3.7.0           |

**Comment by alexanderzobnin** [comment]
Sorry, but Zabbix API doesn't expand it. So it's tricky to implement this on the plugins' side.

**Comment by jgerry2002** [comment]
Understood. I was guessing it was some sort of limitation based on an API issue. If there is another way to work around this let me know. If I can request this functionality in another way officially let me know as well. Thank you for your efforts as the plugin gives me 95% of what I need already.

**Comment by alexanderzobnin** [comment]
@jgerry2002 you can request features through Grafana support subscription.
