### ISSUE TITLE
Add support to show problems

### ISSUE THREAD

**Issue by fpaternot-zz** [alexanderzobnin/grafana-zabbix#495]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature requestdd
- [ ] Question / Support request

Currently it seems that trigger.get is the only way to retrieve trigger information.

If the trigger uses the PROBLEM event generation in **multi** mode (https://www.zabbix.com/documentation/3.4/manual/config/triggers/trigger#configuration), events are omitted and not shown. This mimics the behavior of Monitoring->Triggers.

However, it would be great to add the possibility to show the same of Monitoring->Problems as well.   I realize this feature is not a very popular one, but for large environments it is used quite a bit.

**Comment by LeHigh75** [comment]
+1 on this one, it would be very useful for us

**Comment by bcarlsson** [comment]
+1 Please add this

**Comment by partosXP** [comment]
+1
It's the main reason for not using Grafana with this plugin as main dashboard of zabbix data instead of zabbix interface... its impossible to ignore history of problems.

**Comment by jsenicourt-adeo** [comment]
+1
We use IT services to calculate SLA.
We have to know which trigger affect SLA rate in history
thx for your work

**Comment by mjtrangoni** [comment]
+1
