### ISSUE TITLE
Change disabled items to value

### ISSUE THREAD

**Issue by 13huntington** [alexanderzobnin/grafana-zabbix#496]
- [ ] Bug report
- [ ] Feature requestdd
- [x ] Question / Support request

**Software Versions**

Grafana= v4.6.2 
Zabbix =  3.2.5
Zabbix Plugin= 3.7.0        
    |

#### What did you do?
I'm trying to show the available hosts
#### What was the expected result?
when making the query, when it is available I get a pore because it is not available I can not obtain and color the cell to inform.
i have: 

![subir1](https://user-images.githubusercontent.com/22553944/34162720-759f961e-e4b3-11e7-8b1f-daae90ca5bf8.png)

i need:

![subir2](https://user-images.githubusercontent.com/22553944/34162722-75d623a0-e4b3-11e7-9229-76697b23fe4d.png)

thanks.

**Comment by alexanderzobnin** [comment]
But `0` is not the same as `item disabled`. So it's hard to determine is value really 0 or is there no value.
