### ISSUE TITLE
about regex or aggregate 

### ISSUE THREAD

**Issue by zfbfoxlly123** [alexanderzobnin/grafana-zabbix#498]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 4.6.3     | 3.0.8    | 3.7.0     |

#### What did you do?
I want to put 12 hosts aggregations on the graph to display.
Host field use regex "/.*/"
Item field use "CPU Load"

#### What was the expected result?
used function "aggregateBy(2m,avg)"  to  aggregate "CPU Load" in one line

#### What happened instead?
![grafana1](https://user-images.githubusercontent.com/17916697/34192520-625db9ec-e589-11e7-94aa-44a6f97c0b48.jpg)
![grafana](https://user-images.githubusercontent.com/17916697/34192348-6ed18628-e588-11e7-86d4-bd1ce88404ce.jpg)
I should have 2 lines one of them is aggregated by 12 hosts and the another one is only displayed one host But these two lines overlap.
It looks like the regex "/.*/" don't work.
I don't know it's a bug or something else make this happened

**Comment by alexanderzobnin** [comment]
Yes, looks like a bug.
