### ISSUE TITLE
no data points

### ISSUE THREAD

**Issue by Simy88** [alexanderzobnin/grafana-zabbix#499]
I am new for zabbix and grafana, and is making some test for this, all my zabbix server， mysql and grafana is on the same server.
### I'm submitting a ...
- [x] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.3.1   | 3.4.4  | 3.8.1                |

#### What did you do?
add zabbix data source successed
url: http://x.x.x.x/zabbix/api_jsonrpc.php
access:proxy
api details: username api
save &test get zabbix api version 3.4.4

the api user has granted the read permission of all groups.

#### What was the expected result?
all the dashboard shows "No data points"
and i edit one graph, from the metrics table, i can get the groups, host, application,and item by double click the blank. after i choose one item which i am sure that the zabbix server has already get the data, is shows no data points too.

#### What happened instead?
data

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by Simy88** [comment]
I found it seems to be work for a while ,and then turns to be "no data points"

**Comment by alexanderzobnin** [comment]
Try to increase PHP memory.

**Comment by Gmatoy** [comment]
Where is the file for this php config? i changed it on "/etc/httpd/conf.d/zabbix.conf" and restarted the apache server. 
There is other file to configure this?
Ty for your time.
