### ISSUE TITLE
Zabbix Data Sources integration with grafana 1.9

### ISSUE THREAD

**Issue by Diwahars** [alexanderzobnin/grafana-zabbix#5]
Hi,

Could you please help me in configuring zabbix with grafana 1.9??

How to run grafana 1.9?

**Comment by nucleusv** [comment]
@Diwahars, do you have problems with this manual http://docs.grafana.org/v1.9/installation/?

**Comment by nucleusv** [comment]
After grafana installation take this branch https://github.com/alexanderzobnin/grafana-zabbix/tree/release-1.0 and read instructions

If you have problems with zabbix let me know

**Comment by Diwahars** [comment]
@nucleusv Thanks will look into it..
