### ISSUE TITLE
Не подключается Zabbix API datasource

### ISSUE THREAD

**Issue by mikhailov** [alexanderzobnin/grafana-zabbix#50]
Александр, отличный плагин написал, собирался попробовать и наткнулся на неприятность, Grafana ругается примерно так:

```
Stack trace:

kb/<@https://monitoring.test.com/grafana/app/app.6e379bdb.js:10:15701
v@https://monitoring.test.com/grafana/app/app.6e379bdb.js:10:14241
o/j@https://monitoring.test.com/grafana/app/app.6e379bdb.js:10:12812
i@https://monitoring.test.com/grafana/app/app.6e379bdb.js:10:29774
j/<@https://monitoring.test.com/grafana/app/app.6e379bdb.js:10:29946
Rb/this.$get</l.prototype.$eval@https://monitoring.test.com/grafana/app/app.6e379bdb.js:12:5064
Rb/this.$get</l.prototype.$digest@https://monitoring.test.com/grafana/app/app.6e379bdb.js:12:3578
Rb/this.$get</l.prototype.$apply@https://monitoring.test.com/grafana/app/app.6e379bdb.js:12:5322
k@https://monitoring.test.com/grafana/app/app.6e379bdb.js:14:3970
_.event.dispatch@https://monitoring.test.com/grafana/app/app.6e379bdb.js:6:1535
_.event.add/q.handle@https://monitoring.test.com/grafana/app/app.6e379bdb.js:5:30407
```

Исходные данные: свежая Grafana, последний стабильный Zabbix, юзер для доступа настроен и прописан с настройках, логи httpd на Zabbix пустые, так как Grafana даже не может достучаться, спотыкается на JS error, Рекомендации?

**Comment by nucleusv** [comment]
Девелопер тулс откройте ф12 и скрин запросов и лог консоли покажите

**Comment by mikhailov** [comment]
@nucleusv похоже, дурацкий вопрос у меня, в отсутствии заголовков CORS проблема, хотя Zabbix свежайший:

<img width="889" alt="screen shot 2015-07-10 at 5 05 37 pm" src="https://cloud.githubusercontent.com/assets/14601/8622915/01a652a4-2726-11e5-9658-4d3a95848a00.png">

**Comment by nucleusv** [comment]
у вас странное имя страницы АПИ -  jsrpc.php

**Comment by nucleusv** [comment]
Zabbix API (api_jsonrpc.php) before zabbix 2.4 don't allow cross-domain requests (CORS). And you can get HTTP error 412 (Precondition Failed). To fix it add this code to api_jsonrpc.php immediately after the copyright

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Max-Age: 1000');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    return;
}
before

require_once dirname(__FILE__).'/include/func.inc.php';
require_once dirname(__FILE__).'/include/classes/core/CHttpRequest.php';

**Comment by mikhailov** [comment]
спасибо, закрываю тикет

**Comment by alexanderzobnin** [comment]
@mikhailov Проблема была в CORS?

**Comment by mikhailov** [comment]
@alexanderzobnin нет, в самоподписанном сертификате и в том, что Grafana не умела это сразу показать
