### ISSUE TITLE
404 on Zabbix Triggers panel in 3.8.1

### ISSUE THREAD

**Issue by stellasawicki** [alexanderzobnin/grafana-zabbix#500]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.3   | 3.2.4  | 3.8.1                 |

#### What did you do?
Upgraded zabbix plugin from 4.6.1 to 4.6.3

#### What was the expected result?
Dashboards should work like they used to.

#### What happened instead?
Zabbix Triggers panel is not showing up. Instead there is 404 error:
![image](https://user-images.githubusercontent.com/30984108/34387807-8c3b5088-eb30-11e7-8925-d3c6cf677081.png)
The same error show up when trying to create a new Zabix Triggers panel in a new dashboard. 
There are no errors related to this one in Grafana log files.

**Comment by fredprod** [comment]
I got same issue, but after emptied cache browser, all is ok.

**Comment by stellasawicki** [comment]
Thanks for the hint. After cleaning cache, the panel appeared.
