### ISSUE TITLE
"Cannot read property '1' of null" on new Zabbix/Grafana install

### ISSUE THREAD

**Issue by miggyb** [alexanderzobnin/grafana-zabbix#501]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [x] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Grafana v4.6.3 (commit: 7a06a47) | Zabbix 3.4.5  | 3.8.1 |

#### What did you do?

Installed fresh copy of Debian Stretch (4.9.0), nginx (1.10.3), PostgreSQL (9.6.6), Grafana, Zabbix, and the Grafana-Zabbix plugin on a laptop (Lenovo T510). Zabbix is using the PostgreSQL database, and a Grafana user has been added to PostgreSQL and Zabbix for access to the 'zabbix' database and the Zabbix API. Zabbix is just monitoring itself for now, but I can see it's collecting data and generating graphs (in Zabbix).

I added PostgreSQL as a data source and it looks like the database access is working as I can generate raw SQL queries from Grafana. The Zabbix data source seems to be set up correctly, as I can Save & Test the settings without issues.

#### What was the expected result?

The default "Zabbix Server Dashboard" should work out-of-the-box (after setting up the data source) as far as I can tell.

#### What happened instead?

None of the items in the "Zabbix Server Dashboard" work. They all fail with the same error:    
`Cannot read property '1' of null`

Here is the Stack trace for the "Host name" item on the top left:

```
TypeError: Cannot read property '1' of null
    at Object.parseInterval (http://192.168.20.116:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/utils.js:178:49)
    at ZabbixAPIDatasource.isUseTrends (http://192.168.20.116:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:836:50)
    at eval (http://192.168.20.116:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:318:37)
    at m (http://192.168.20.116:3000/public/build/vendor.2305a8e1d478628b1297.js:1:52736)
    at Function.pa [as map] (http://192.168.20.116:3000/public/build/vendor.2305a8e1d478628b1297.js:1:93893)
    at ZabbixAPIDatasource.query (http://192.168.20.116:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/datasource.js:292:30)
    at e.issueQueries (http://192.168.20.116:3000/public/build/0.be20b78823b4c9d93a84.js:7:19548)
    at u (http://192.168.20.116:3000/public/build/vendor.2305a8e1d478628b1297.js:43:68722)
    at http://192.168.20.116:3000/public/build/vendor.2305a8e1d478628b1297.js:43:69127
    at f.$digest (http://192.168.20.116:3000/public/build/vendor.2305a8e1d478628b1297.js:43:74824)
```

The Zabbix API seems to be working, as I did a basic test out from the terminal:

```
miggyb@zima:~$ curl -i -X POST -H "Content-Type: application/json-rpc" http://localhost/zabbix/api_jsonrpc.php -d '{"jsonrpc":"2.0","method":"apiin
fo.version","id":1,"auth":null,"params":{}}'
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Thu, 28 Dec 2017 03:24:38 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Cache-Control: no-cache

{"jsonrpc":"2.0","result":"3.4.5","id":1}
```
Let me know if you want any config files or anything like that.

Thanks!

**Comment by alexanderzobnin** [comment]
Please, show your Zabbix datasource config. Seems, you set wrong trends or cache interval (i.e. `1` instead of `1m`, `1d` or so).

**Comment by miggyb** [comment]
Looks like that was it. After a reboot I started getting the same error as #458 and it started working changing those settings.

**Comment by kamal18sharma** [comment]
trying to add zabbix plugin for grafana.
The following Error Occured
Cannot read property 'FormField' of undefined Evaluating http://172.16.31.51:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module
Please Suggest
