### ISSUE TITLE
Cant put different colors on graph panel for different queries ; Same itens but different hosts.

### ISSUE THREAD

**Issue by Gmatoy** [alexanderzobnin/grafana-zabbix#504]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

| Grafana | Zabbix | Grafana-Zabbix Plugin |
|    4.6.3   | 3.2.10  |               3.8.1                |

#### What did you do?
Added 4 equal itens of 4 different hosts as a metric on a graph panel. And tried to give different colors to each one.

#### What was the expected result?
4 "lines" with different colors, to distinguish the hosts and metrics, one of another 

#### What happened instead?
Can't use the color picker right, every time i change color of one query, all of them changes to the same color that i picked to that one.
Resuming, cant pick different colors to same itens query but different hosts. 
And i have a old dashboard (before the lasts updates) where this function worked at the time. (i am afraid to test on it, because its on production).

The image says it all:
![image](https://user-images.githubusercontent.com/29662882/34422882-96850a3c-ebff-11e7-9007-ede3b3c96be0.png)
_________________________
edit:
detail, if i don't choose the colors it works perfectly, but if i change one, all of them changes to that one i choose

**Comment by Gmatoy** [comment]
detail, if i dont choose the colors it works perfectly, but if i change one, all of them changes to that on i choosed

**Comment by alexanderzobnin** [comment]
Grafana changes series color by using series name. So you should use unique series names.
