### ISSUE TITLE
Gap on graph with long interval

### ISSUE THREAD

**Issue by alamsyahho** [alexanderzobnin/grafana-zabbix#513]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [x] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.3   | 3.0.14  | 3.8.1                 |

#### What did you do?
Created graph for memory monitoring based on the metrics from zabbix as mentioned below:
- Total memory with interval of 1 hour
- Used memory with interval of 5 mins
This screenshot attached with the last 3 hour graph shown. The gap not really visible if it is showing on last 24 hours or above

#### What was the expected result?
Normal memory usage graph without any gap in the graph

#### What happened instead?
Found some gap on the graph. But it seems the gap on the graph will only exist until the next "total memory" polling which is running every 1 hour.

![capture](https://user-images.githubusercontent.com/8612075/35027439-b7fbce94-fb8b-11e7-9b1b-5a6aea6b61ad.PNG)

**Comment by alexanderzobnin** [comment]
It's caused due to _total memory_ collecting interval (1 hour or so). So you have only 3 points on graph (10:50, 11:50, 12:50). But _memory used_ have 1min collecting interval and you see line without gaps.
