### ISSUE TITLE
Zabbix triggers panel > Space after last item ?

### ISSUE THREAD

**Issue by LeDistordu** [alexanderzobnin/grafana-zabbix#516]
I have space after last item when there is no page : 

![grafana-zabbix](https://user-images.githubusercontent.com/7805145/35093650-409e7ca8-fc43-11e7-9983-f5c548224071.jpg)

Thank you for your work

**Comment by alexanderzobnin** [comment]
It depends on panel size. In Grafana v5 panels have fixed size.
