### ISSUE TITLE
Trigger Panel - Wrong visualization

### ISSUE THREAD

**Issue by stewie83** [alexanderzobnin/grafana-zabbix#517]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.4.3   | 3.4.4  | 3.8.1                 |

Hi, after installing the last version of the plugin, my trigger panel view show different than the one on the documentation and on the one present at http://play.grafana-zabbix.org/dashboard/db/triggers?orgId=2. I attach an image as example. The icon of the hearth is in the top left angle while should be in the left and every trigger is 4-5 line while it should be in 2 lines. I try to remove the plugin and install again with no result.
Any advice?
![Screenshot trigger panel](https://user-images.githubusercontent.com/8362273/35279647-ec736634-004d-11e8-8f00-9b7dd5f47f47.png)

**Comment by alexanderzobnin** [comment]
Try to reset browser cache. What browser do you use?

**Comment by stewie83** [comment]
Everything's fine after upgrading Grafana to 4.6. If I have the chance i'll test again with 4.4.3 and let you know if the problem is related to Grafana version or it's my browser issue. Thanks

**Comment by alexanderzobnin** [comment]
This version works well only with Grafana 4.6+

**Comment by xdexter** [comment]
Hello, 

I have the same problem, is there any estimate for this issue to be fixed to works in grafana 5?

Regards

**Comment by alexanderzobnin** [comment]
Not sure, maybe few weeks or so, trying to find a time for this.

**Comment by xdexter** [comment]
Hm ok, i got it, thank you for your attention.

Regards
