### ISSUE TITLE
No data on Zabbix Server Dashboard?

### ISSUE THREAD

**Issue by mcblum** [alexanderzobnin/grafana-zabbix#518]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [ x ] Question / Support request

Thanks for the awesome plugin! I've configured everything as documented and for the most part everything is working great. We have a series of linux VMs which are showing up and everything is working. However, when I navigate to the Zabbix Server dashboard everything is blank. When I try to use the query inspector to see what's going on, it basically just hangs. 

Currently, everything is pretty much preconfigured so I would assume that since the plugin has connected successfully to Zabbix I should be all set, but no data is being transmitted/received.

I'm sure this is something I did wrong but if anyone has any idea why some hosts are visualizing just fine whereas the server and some others are not, I'd really appreciate the guidance!

**Comment by alexanderzobnin** [comment]
This is just an example dashboard. Maybe your Zabbix host has a different name.
