### ISSUE TITLE
Wrong data from current and 

### ISSUE THREAD

**Issue by kamulchik** [alexanderzobnin/grafana-zabbix#519]
### I'm submitting a ...
- [X ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.0  | 3.4.5  | 3.8.1                 |

#### What did you do?
I added singlestat panel with stat: current and added graf with legent: current

#### What was the expected result?
Current value from single stat = current value graf 
#### What happened instead?
Current value from graf no equivalent current value from single stat
![2018-01-30_17h48_24](https://user-images.githubusercontent.com/13658089/35665769-86781c5c-0738-11e8-80ca-eccd976110a6.png)

**Comment by sumitgoelpw** [comment]
We have the same issue.

**Comment by alexanderzobnin** [comment]
I think it's due to series downsampling. Use the same interval for singlestat. I recommend you to set time override value to short interval in singlestat if you want to use _current_ value in order to avoid downsampling.

**Comment by kamulchik** [comment]
Thank you! It helped for me, but i need more time for test.

**Comment by alexanderzobnin** [comment]
@kamulchik Ok, let me know if all goes right and I can close this issue.
