### ISSUE TITLE
Text panel doesn't show text metric.

### ISSUE THREAD

**Issue by artiatoisa** [alexanderzobnin/grafana-zabbix#521]
### I'm submitting a ...
- [ *] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.3   | 3.4.6  | 3.8.1                 |

#### What did you do?
I try adding a text panel with text metric and settings of table transform with Time series aggrigations and only one column Curent

#### What was the expected result?
I expect to see metrics with last value.
<img width="586" alt="2018-02-06 9 32 07" src="https://user-images.githubusercontent.com/29421604/35839153-5e339716-0b21-11e8-884e-3fddc43e84e8.png">

#### What happened instead?
Instead it I see dash.
<img width="586" alt="2018-02-06 9 32 07" src="https://user-images.githubusercontent.com/29421604/35839264-13a25b50-0b22-11e8-8347-2acdc82f8192.png">

**Comment by w0lfmast3r** [comment]
I have the same issue, post upgrade to grafana 4.6.3 and plugin 3.8.1, the time time series aggregation don's show text field.
On zabbix the values are correct.

**Comment by alexanderzobnin** [comment]
Duplicates #492
