### ISSUE TITLE
zabbix trigger 当所有的主机都是正常的情况，默认的背景色为黑色，有没有好的办法进行修改。

### ISSUE THREAD

**Issue by msrsldks** [alexanderzobnin/grafana-zabbix#523]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| x.x.x   | x.x.x  | x.x.x                 |

#### What did you do?
_Describe here_

#### What was the expected result?
_Describe here_

#### What happened instead?
_Describe here_

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Use English, please.
