### ISSUE TITLE
Problems with Zabbix/Grafana behind reverse proxy

### ISSUE THREAD

**Issue by tammytankian** [alexanderzobnin/grafana-zabbix#525]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 4.6.1 | 3.4.6. | 3.8.1 |

From time to time, the graphs that use Zabbix as datasource just get No Data 
![image](https://user-images.githubusercontent.com/27218076/35938870-3e769992-0c29-11e8-85da-cc601be308d4.png)

And after updating the page, the data is back

![image](https://user-images.githubusercontent.com/27218076/35938905-526ce6cc-0c29-11e8-8e1b-b79f158288c7.png)

I am kinda lost in what to do. Grafana and Zabbix are in the same server and using an Apache reverse proxy.
Oh, and I am using the latest Apache version

Help? What am I doing wrong?

**Comment by alexanderzobnin** [comment]
Could you take a look at Grafana network requests? Does it return data? Is zabbix api request the same?

**Comment by tammytankian** [comment]
Hello there! Sorry it took so long to answer...

> Could you take a look at Grafana network requests? Does it return data?

It happens at random times, and when it happens is as there is no datasource, so the only thing requested is the graphic icons and items of grafana

Is zabbix api request the same?
As it is random, I cannot really analize that, but when is working the api request is the same, and is fine

Analizing the apache logs, I got even more lost about where is the problem tbh, because I noticed this:

 - - [14/Mar/2018:11:39:49 -0300] "POST /zabbix/api_jsonrpc.php HTTP/1.1" 301 539 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
 - - [14/Mar/2018:11:39:49 -0300] "POST /zabbix/api_jsonrpc.php HTTP/1.1" 301 539 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
::1 - - [14/Mar/2018:11:39:49 -0300] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2l (internal dummy connection)"
 - - [14/Mar/2018:11:39:50 -0300] "GET /zabbix/api_jsonrpc.php HTTP/1.1" 404 11477 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
 - - [14/Mar/2018:11:39:50 -0300] "GET /zabbix/api_jsonrpc.php HTTP/1.1" 404 5322 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"

Maybe is nothing, maybe is related... ?

**Comment by alexanderzobnin** [comment]
Hm... I'm not sure what may be a problem.

**Comment by tammytankian** [comment]
o.o @torkelo ?

My Apache configuration, just in case the fault is in some mistake i did in there

<VirtualHost *:80>
        ServerName grafana.link.here
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        Redirect permanent / https://grafana.link.here/

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        ErrorDocument 404 /index.html
        ErrorDocument 500 /500.html
        ErrorDocument 502 /500.html
        ErrorDocument 503 /500.html
        ErrorDocument 504 /500.html
</VirtualHost>

<VirtualHost *:80>
        ServerName zabbix.link.here

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
#       Redirect / https://zabbix.link.here/

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        ErrorDocument 404 /index.html
        ErrorDocument 500 /500.html
        ErrorDocument 502 /500.html
        ErrorDocument 503 /500.html
        ErrorDocument 504 /500.html
</VirtualHost>

<VirtualHost *:443>
        ServerName grafana.link.here

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        SSLEngine on
        SSLCertificateFile /path/to/ .crt
        SSLCertificateKeyFile /path/to/ .key
        SSLCertificateChainFile /path/to/ .crt

        ErrorLog ${APACHE_LOG_DIR}/error.log
       CustomLog ${APACHE_LOG_DIR}/access.log combined

        ErrorDocument 404 /index.html
        ErrorDocument 500 /500.html
        ErrorDocument 502 /500.html
        ErrorDocument 503 /500.html
        ErrorDocument 504 /500.html

  ProxyPass / http://localhost:3000/
  ProxyPassReverse / http://localhost:3000/
ProxyPreserveHost On

</VirtualHost>

<VirtualHost *:443>
        ServerName zabbix.link.here
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        SSLEngine on
        SSLCertificateFile /path/to/ .crt
        SSLCertificateKeyFile /path/to/ .key
        SSLCertificateChainFile /path/to/ .crt

        ErrorLog ${APACHE_LOG_DIR}/error.log
       CustomLog ${APACHE_LOG_DIR}/access.log combined

        ErrorDocument 404 /index.html
        ErrorDocument 500 /500.html
        ErrorDocument 502 /500.html
        ErrorDocument 503 /500.html
        ErrorDocument 504 /500.html

        ProxyPass / http://localhost/zabbix/
        ProxyPassReverse / http://localhost/zabbix/
        ProxyPreserveHost On

</VirtualHost>

Help? :(
