### ISSUE TITLE
Zabbix v3.0.3 does not show any information

### ISSUE THREAD

**Issue by oktysh** [alexanderzobnin/grafana-zabbix#527]
![zabbix api](https://user-images.githubusercontent.com/32997006/36427052-b86cce1c-1654-11e8-8fcd-67406884cd44.png)
![zabbix dash](https://user-images.githubusercontent.com/32997006/36427053-b887f4e4-1654-11e8-9fb2-d0e118dd646b.jpg)

grafana-server v4.6.3
zabbix plugin v3.8.1
zabbix-server v3.0.3

**Comment by alexanderzobnin** [comment]
Duplicated #518 #507
