### ISSUE TITLE
Calculation of Metrics

### ISSUE THREAD

**Issue by R-Studio** [alexanderzobnin/grafana-zabbix#528]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature request
- [ ] Question / Support request

#### What did you do?
I have to 2 "Metrics" (Singlestat) (Number of CPU-Cores and Number of vCPU-Cores)
I would like to divide these two values, to show the P2V-Ratio in a SingleStat-Panel.

P2V = The ratio of physical Cores to virtual Cores

#### What was the expected result?
Feature: Calculation of multiple Metrics in a Singlestat-Panel

**Example:**
Number of CPU-Cores = 28
Number of vCPU-Cores = 150
A Singlestat-Panel that calculate: 150/28 = **5.35**
The Singlestat-Panel show only the Value "5.35"

#### What happened instead?
I didn't found a function to take this calculation.

**Comment by rg-fine** [comment]
+1

**Comment by grimm514** [comment]
+1

**Comment by andiexer** [comment]
+1

**Comment by silviok** [comment]
+1

**Comment by rterrettaz** [comment]
+1

**Comment by disaster123** [comment]
+1

**Comment by alexanderzobnin** [comment]
Yes, this makes sense, but you should understand a limitation - this function can divide only last value of one series to last value of another and result will be series containing one point:
```js
[[val_1, ts_1], [val_2, ts_2]] / [[val_3, ts_3], [val_4, ts_4]] => [[val_2 / val_4, ts_2]]
```
it useful for singlestat only.

**Comment by disaster123** [comment]
That's a good start. What's the reason we can't do math with each point at the same ts? To archieve this i would use something like
avg(1m) (to have constant points) and than apply the math

**Comment by alexanderzobnin** [comment]
@disaster123 yes, but what if series have different collection interval, like 1 min vs 1 hour? That will be tricky to divide them.

**Comment by alexanderzobnin** [comment]
Solution may be in the interpolation of metric with the longest interval, but I'm not sure how to handle division by `0`.

**Comment by disaster123** [comment]
@alexanderzobnin Yes that's another problem i have in general see here: https://github.com/alexanderzobnin/grafana-zabbix/issues/543

I think 0 sould be skipped / replaced by 1.

**Comment by R-Studio** [comment]
Any updates on this?

**Comment by satels** [comment]
+1

**Comment by alexanderzobnin** [comment]
I haven't worked on this yet.

**Comment by mjtrangoni** [comment]
+1

**Comment by alexanderzobnin** [comment]
I think we started to work on a similar feature in Grafana. Not sure when it will be implemented and would it be in open source or in the enterprise version. But it definitely would be possible in Grafana in future.

**Comment by R-Studio** [comment]
In my opinion we can close the issue, because following plugin has this feature:
[Singlestat Math](https://grafana.com/grafana/plugins/blackmirror1-singlestat-math-panel)
