### ISSUE TITLE
sumSeries + other aggregation function doesn't work

### ISSUE THREAD

**Issue by kuPyxa** [alexanderzobnin/grafana-zabbix#530]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support  #request

Hi. Percentile doesn't properly work when use SumSeries function.

**Comment by Harrisoned** [comment]
I'm having trouble with that as well. Any update?

**Comment by alexanderzobnin** [comment]
Looks like more than 1 function from Aggregation category can't be applied correctly.

**Comment by Harrisoned** [comment]
Many thanks!
