### ISSUE TITLE
Additional time ranges in functions

### ISSUE THREAD

**Issue by kuPyxa** [alexanderzobnin/grafana-zabbix#531]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature requestdd
- [ ] Question / Support request

Hi. Please add support time range like "now/M" for use with function, for example Percentile.

**Comment by alexanderzobnin** [comment]
Some updates:
Interval should be the same as a panel time range. So the function will return only one value for the given range. Resulting time series will look like this:
```
[[value, range_from], [value, range_to]]
```

**Comment by alexanderzobnin** [comment]
Now special `$__range_series` variable allows calculating aggregation over the whole series.
CC @kuPyxa
