### ISSUE TITLE
Graphs with broken lines

### ISSUE THREAD

**Issue by divanikus** [alexanderzobnin/grafana-zabbix#533]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.3   | 3.4.7  | 3.8.1                 |

#### What did you do?
I'm collecting metrics from an external service using zabbix-agent. Not all metrics have exact 1 minute interval, they might be something like 03:29:00, 03:29:59, 03:30:59, 03:32:00. 
When viewing using Zabbix or Grafana with short time range graphs are ok. But on larger ranges graphs are broken with many missing points.
The result can be fixed by using Display null value as Connected, but it doesn't sound good to me.

#### What was the expected result?
![bb147b502c2fe60ceef268952d0e0c31](https://user-images.githubusercontent.com/3438036/36816190-22912852-1cee-11e8-86e9-2613200e6d9b.png)

#### What happened instead?
![97943a6a5135c687cd38bc2d6c91feeb](https://user-images.githubusercontent.com/3438036/36816194-282f202a-1cee-11e8-86df-545380e028c6.png)

![6693b972670a32e9eddc2dd08c7c552d](https://user-images.githubusercontent.com/3438036/36816437-d60c3e08-1cee-11e8-974a-33186f7caadd.png)

**Comment by alexanderzobnin** [comment]
Try to increase maxDataPoints (options menu in the top right corner of query editor) or set Null value 
to connected instead of null.

**Comment by divanikus** [comment]
I have mentioned above, that "connected" helps.
Setting maxDataPoints also helps, but with some strange side effect. If I use exact value, say 1000 - graph is ok. If I type "auto", graph is also ok. But if I just delete the value - graph becomes broken again.

**Comment by alexanderzobnin** [comment]
I should check this (auto/blank max data points), maybe it's a bug. Anyway, gaps on the graph is not a bug, that how downsampling works (if no points in time interval, value should be `null`).
