### ISSUE TITLE
Doesn't work with grafana 5.0.0 stable

### ISSUE THREAD

**Issue by homelessnessbo** [alexanderzobnin/grafana-zabbix#535]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0.0  | nevermind  | 3.8.1                 |

#### What did you do?
Upgraded grafana to latest 5.0.0 stable release

#### What was the expected result?
Zabbix available as data sourece

#### What happened instead?
Grafana was unable to load plugin 

There is errors in log:
```
t=2018-03-01T16:10:28+0000 lvl=eror msg="Could not find plugin definition for data source: alexanderzobnin-zabbix-datasource"
```
And error in web-interface: 
```
Plugin not found, no installed plugin with that id
```

**Comment by alexanderzobnin** [comment]
Hm... I should check it, looks bad.

**Comment by agauthier51** [comment]
Zabbix datasources are OK here, connecting to both Zabbix 3.4.7 & 2.4.8. Only triggers panel have a bad display.

**Comment by homelessnessbo** [comment]
btw, I tried to reinstall it several times with cli utility, but it didn't unzip it, so I did it manually. Probably it's the problem.

**Comment by alexanderzobnin** [comment]
I also can't repeat this. If problem solved, please, close an issue.

**Comment by alionur07** [comment]
hi,

i just upgraded the zabbix plugin. The datasource is not working right now. :) 

I got the error message "Plugin not found, no installed plugin with that id"

**Comment by alexanderzobnin** [comment]
Plugin is not compatible with grafana 5.x

**Comment by alionur07** [comment]
thanks for your return. i saw that. :)

Alexander Zobnin <notifications@github.com>, 14 Eki 2020 Çar, 16:17
tarihinde şunu yazdı:
