### ISSUE TITLE
Trends missing in Zabbix 2.0.15 Grafana 4.2.0 and Zabbix Plugin 3.4.0

### ISSUE THREAD

**Issue by andgustmp** [alexanderzobnin/grafana-zabbix#539]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.2.0   | 2.0.15  | 3.4.0                 |

#### What did you do?
When we try to see informations above 7 days, is shown a message "Zabbix API Error. Connection Error". 

#### What was the expected result?
The trends information should be shown on Grafana dashboards.

#### What happened instead?
The response of the Zabbix API is the same after and before the patch (ZBXNEXT-1193). It always says "Resource (trend) does not exist".

Request

> {"jsonrpc":"2.0","method":"trend.get","params":{"output":"extend","trend":"3","itemids":["30604"],"sortfield":"clock","sortorder":"ASC","time_from":1519749617,"time_till":1520354417},"id":1,"auth":"a96527ee220d741feca0feacd2e96548"}

Response
> {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params.","data":"Resource (trend) does not exist"},"id":1}

Plugin Configuration
![image](https://user-images.githubusercontent.com/36933376/37046773-e3e27c92-2147-11e8-993e-141760c8e226.png)

**Comment by alexanderzobnin** [comment]
@andgustmp did you install trend patch for zabbix? See http://docs.grafana-zabbix.org/installation/configuration/#configure-zabbix-data-source and https://support.zabbix.com/browse/ZBXNEXT-1193
