### ISSUE TITLE
Value missing or incorrect between Grafana and Zabbix

### ISSUE THREAD

**Issue by tiyab** [alexanderzobnin/grafana-zabbix#542]
### I'm submitting a ...
- [ X ] Bug report
- [  ] Feature requestdd
- [  ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0.1   | 3.4.7  | 3.8.1                 |

#### What did you do?
Configuring custom items in Zabbix to fetch Postgresql information.
Trying to get these information display in Grafana

#### What was the expected result?
Finding the Value/Item to be displayed
Value/Item matches between Zabbix and Grafana

#### What happened instead?
Value/Item is not detected by Grafana

List of items in Zabbix:
• Available memory:
![screen shot 2018-03-14 at 6 35 23 pm](https://user-images.githubusercontent.com/6996938/37397899-c3491e70-27b7-11e8-8082-5ba755691d39.png)
• Differents items for Postgresql database:
![screen shot 2018-03-14 at 6 35 34 pm](https://user-images.githubusercontent.com/6996938/37397900-c3795374-27b7-11e8-81d8-8ac1cc831197.png)

In Grafana:
• Available memory does not match Zabbix at all (Option - Stat set at Current )
![screen shot 2018-03-14 at 6 35 01 pm](https://user-images.githubusercontent.com/6996938/37397921-d607c624-27b7-11e8-924b-45075f5deafb.png)
• Version and uptime not displayed because not detected by Grafana (see last screenshot)
• Database size value doesn't match the one in Zabbix
![screen shot 2018-03-14 at 6 35 09 pm](https://user-images.githubusercontent.com/6996938/37397922-d6330be0-27b7-11e8-94a5-cb98357951d7.png)
• Only replication delay and size are detected by Grafana
![screen shot 2018-03-14 at 6 43 45 pm](https://user-images.githubusercontent.com/6996938/37397924-d65edb76-27b7-11e8-8ad9-051d88b80f76.png)

**Comment by tiyab** [comment]
Ok I've found that I need to switch from Metrics to Text to have "Version" and "Uptime"available to be selected.

**Comment by alexanderzobnin** [comment]
Try to change Unit in grafana from `data (Metric)` to `data (IEC)`.
