### ISSUE TITLE
Are we able to control the new lines on tiggers pannel

### ISSUE THREAD

**Issue by wonderphil** [alexanderzobnin/grafana-zabbix#544]
### I'm submitting a ...
- [x] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0.1   | 3.2.7  | 3.8.1                 |

#### What did you do?
when creating tiggers dashboard it puts everything on a new line, when that dashboard is for a tv, having 4 lines is takes to much space.
![new lines for everything](https://user-images.githubusercontent.com/1829205/37539670-3f4a88d4-294c-11e8-8cf9-d61b71907229.png)

#### What was the expected result?
that you can have multiple things on one line, like the demo dashboard, 
![screen shot 2018-03-16 at 7 01 23 pm](https://user-images.githubusercontent.com/1829205/37539751-7ebf7704-294c-11e8-8dd0-03643bf68823.png)

or be able to go back to the old way of displaying
![screen shot 2018-03-16 at 7 02 36 pm](https://user-images.githubusercontent.com/1829205/37539792-a2aab66a-294c-11e8-95d9-a614c0929380.png)

#### What happened instead?
getting no option to control the wasted space

**Comment by alexanderzobnin** [comment]
It's a bug when you use it with Grafana 5.x #522
