### ISSUE TITLE
Вернуть старый вид таблицы с триггерами

### ISSUE THREAD

**Issue by flashick** [alexanderzobnin/grafana-zabbix#545]
Здравствуйте. Можно ли как-то вернуть старый вид таблицы с триггерами? Как на этом скриншоте:
![image](https://user-images.githubusercontent.com/4356395/37719133-62be20fe-2d35-11e8-9736-c41df5b29cf3.png)
Она была очень удобной для выведения на телевизоры. 
Версия графаны 5.0.0, версия плагина 3.8.1

Спасибо

**Comment by alexanderzobnin** [comment]
Duplicates #532
