### ISSUE TITLE
zabbix-api:Connection failed Could not connect to given url

### ISSUE THREAD

**Issue by Omega-ZhangH** [alexanderzobnin/grafana-zabbix#547]
I'm submitting a Support request

**Software Versions**

| Linux  version   | Grafana             | Zabbix | Grafana-Zabbix Plugin |
| centOS 7.0 X64| 4.2.0-1.x86_64 | 3.2.6    |                 3.8.1               |

#### What did you do?
I was Edit data source of zabbix
#### What was the expected result?
it should be succes like this
![image](https://user-images.githubusercontent.com/37653686/37759859-d722e546-2def-11e8-9c79-d21f6d83cfa8.png)

#### What happened instead?
![image](https://user-images.githubusercontent.com/37653686/37759873-e6e54dca-2def-11e8-8e50-b4d68ff65439.png)

i thought may be my url was wrong。so i test it on linux and it succsed.
what should i do can fix it?
![image](https://user-images.githubusercontent.com/37653686/37760105-a666dfa6-2df0-11e8-8f14-3b28228e07af.png)

![image](https://user-images.githubusercontent.com/37653686/37760003-5b8d0c08-2df0-11e8-816d-fa6dfdcc2013.png)

---------------------------------------------------------------------------
others:
the grafana-cli command always feedback
Failed to send requesterrorGet https://grafana.net/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.net/api/plugins/repo: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
![image](https://user-images.githubusercontent.com/37653686/37760321-411e0b0a-2df1-11e8-8744-f3c717cc3176.png)

but i use the curl test.my network is avilable.
![image](https://user-images.githubusercontent.com/37653686/37760400-829cc13e-2df1-11e8-8f09-7faf670debf5.png)

**Comment by alexanderzobnin** [comment]
Try to use Proxy instead of Direct first.

**Comment by Omega-ZhangH** [comment]
I try  to use Proxy and success！ Thanks a lot！but i still have a question，why  the commond grafana-cli not available?

**Comment by alexanderzobnin** [comment]
I don't know, it depends on your network environment.

**Comment by Omega-ZhangH** [comment]
thank you so much

**Comment by albomo** [comment]
Hello, just have the same problem. But direct or proxy pass do not success.
I heard,  that there is some way to change grafana.ini and put there my Zabbix address, but still have no idea what is the problem.  Search the same topics and still no idea.

**Comment by Omega-ZhangH** [comment]
hi albomo:
    there are  may be some problems with your network environment. so you can try use a VPS to connect.
