### ISSUE TITLE
sum(1M) is grouping by 30days instead of by single month

### ISSUE THREAD

**Issue by plrunner** [alexanderzobnin/grafana-zabbix#548]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0.3   | 3.4.7-1+stretch  | 3.8.1                 |

#### What did you do? / What was the expected result?
I collect my printers counters in Zabbix and store them as delta so I get the exact number of prints made in every interval.
In grafana I want to graph the prints grouped by month for the current year. 

to achieve this I set the following time range.
![image](https://user-images.githubusercontent.com/5763008/37766802-5551ed86-2dc8-11e8-9efc-31e71e45fff0.png)

... and I set the consolidateBy to sum() and summed prints counter by 1M as follows:
![image](https://user-images.githubusercontent.com/5763008/37767239-b1375518-2dc9-11e8-9089-3815a23b8385.png)

#### What happened instead?
The prints made after 20 of the month are grouped and assigned to the next month:
![screenshot_2018-03-22_11-56-39](https://user-images.githubusercontent.com/5763008/37767141-5454a15c-2dc9-11e8-8fef-b734973d81fc.png)

Looks like sum(1M) is somehow summing by 30days instead of month by month.

PL

PS: thank you for this amazing plugin!

**Comment by alexanderzobnin** [comment]
Duplicates #413
