### ISSUE TITLE
TypeError: Cannot read property 'thresholds' of undefined

### ISSUE THREAD

**Issue by deepminimal** [alexanderzobnin/grafana-zabbix#549]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

### For bug report please include this information:

**Software Versions**

| Grafana                                | Zabbix       | Grafana-Zabbix Plugin |
| ------------------------------ | ------------| ------------------------- |
| v 5.0.0 (commit: af6e283)  | 3.4.6           | 3.9.0                             |

**#### What did you do?**
Installed grafana, installed Zabbix plugin. Im use standart dashboard "Zabbix System Status", open and i cant see "thresholds" like this:

![image](https://user-images.githubusercontent.com/18044597/37847565-43d17d04-2ee2-11e8-80ff-fca56e17ddeb.png)

i get this error:

![image](https://user-images.githubusercontent.com/18044597/37847767-ff3a7816-2ee2-11e8-93ae-6cff43f0d8f3.png)

![image](https://user-images.githubusercontent.com/18044597/37847753-f355d072-2ee2-11e8-95cf-05fa54014985.png)

Is this a plugin bug or my mistake?

![image](https://user-images.githubusercontent.com/18044597/37847861-53df8ca8-2ee3-11e8-860d-b2a1c3877773.png)

**Comment by alexanderzobnin** [comment]
Yes, seems, this is caused by new panel format in Grafana 5.

**Comment by alexanderzobnin** [comment]
Seems, it's related to #556. After update to version 3.9.1 this should work.
