### ISSUE TITLE
Отсутствие данных

### ISSUE THREAD

**Issue by lpkOne** [alexanderzobnin/grafana-zabbix#55]
Можно ли реализовать разрыв графиков при отсутствии данных?

![screenshot from 2015-07-14 11 32 48](https://cloud.githubusercontent.com/assets/2459162/8669314/251d905a-2a1c-11e5-9b2b-1646913fb08c.png)

**Comment by alexanderzobnin** [comment]
Попробуйте изменить параметр `Null point mode` на вкладке `Display Styles`:

![2015-07-14 13-24-17](https://cloud.githubusercontent.com/assets/4932851/8671199/d9dbcd18-2a2b-11e5-9f40-60f85f60c355.png)

**Comment by lpkOne** [comment]
Пробовал, ничего не меняется.

**Comment by nucleusv** [comment]
И даже если выбрать null as zero ?)

**Comment by lpkOne** [comment]
`"nullPointMode": "null as zero"`
![screenshot from 2015-07-14 15 27 07](https://cloud.githubusercontent.com/assets/2459162/8673151/ee45d74c-2a3c-11e5-9a27-f50f6cc9338c.png)

**Comment by alexanderzobnin** [comment]
Попробуйте еще [Max data points](https://github.com/alexanderzobnin/grafana-zabbix/wiki/Usage#max-data-points) уменьшить - должно помочь.

**Comment by lpkOne** [comment]
Спасибо, помогло.
![screenshot from 2015-07-14 17 49 57](https://cloud.githubusercontent.com/assets/2459162/8676217/cbb99a56-2a50-11e5-9211-f8a3ffc65704.png)
