### ISSUE TITLE
Trigger panel: show only in specified time frame

### ISSUE THREAD

**Issue by disaster123** [alexanderzobnin/grafana-zabbix#550]
### I'm submitting a ...
- [ ] Bug report
- [ X ] Feature requestdd
- [ ] Question / Support request

Currently the trigger panal just displays all event zabbix knows about. But it would make sense to use the same timeframe as defined in grafana for the graphs.

Also the current format is very space consuming. A all in one line per trigger would be great.

**Comment by alexanderzobnin** [comment]
Yes, this definitely makes sense.

**Comment by alexanderzobnin** [comment]
About triggers format: I'm just trying to make this panel more native-looking. But the high-priority thing is a clear view, so I think about how to make it better.

**Comment by disaster123** [comment]
If you have a lot of trigger it is currently not useable as a single trigger needs about 5-6 lines.

**Comment by alexanderzobnin** [comment]
@disaster123 not sure about 5-6 lines. Look at this issue, maybe you just faced a bug.

**Comment by disaster123** [comment]
@alexanderzobnin i'm running latest plugin version and grafana 4.2 and each trigger uses 5 lines. Each div creates a new block.

**Comment by alexanderzobnin** [comment]
@disaster123 unfortunately, new version is not compatible with grafana 4.x, only with 5.x.

**Comment by disaster123** [comment]
@alexanderzobnin oh that's bad any chance to provide backward compatiblity by just using two css files?

**Comment by alexanderzobnin** [comment]
@disaster123 yes, but it requires some work. Could you open an issue for this task?

**Comment by disaster123** [comment]
Thanks done here: https://github.com/alexanderzobnin/grafana-zabbix/issues/551

**Comment by alexanderzobnin** [comment]
Fixed in new Problems panel.
