### ISSUE TITLE
provide backward compatiblity with grafana 4.X

### ISSUE THREAD

**Issue by disaster123** [alexanderzobnin/grafana-zabbix#551]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [ X ] Question / Support request

Please still provide grafan 4.X support in latest releases. I'm willing to test them ;-)

**Comment by alexanderzobnin** [comment]
Not sure I have enough time for this, sorry.

**Comment by disaster123** [comment]
Already upgraded to 5.2 ;-)
