### ISSUE TITLE
Possibility to filter hostgroup with regex

### ISSUE THREAD

**Issue by LeDistordu** [alexanderzobnin/grafana-zabbix#553]
Sometimes a machine can be in several groups:

- myrealgroup
- groupdiscover

> Only 3GB Free [Total 50G] on /var   Hostname   [myrealgroup, groupdiscover]

which can distort the table a little in width, maybe an option to exclude hostgroup

**Comment by alexanderzobnin** [comment]
Do you want to exclude only one hostgroup or don't show all of them?
