### ISSUE TITLE
Show only 1 trigger on magic info screen / browser on pc is good

### ISSUE THREAD

**Issue by erwinbentelo** [alexanderzobnin/grafana-zabbix#554]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| V3.9.0 | 3.4.7 | | 3.9.0 plugin

We have problem to load trigger webpage in us Magic Info screen. Show only 1 trigger and not more. 
Also when i test the demo link from grafana. Same issue.

What is there different with earlier? before version without heart as trigger we had no problem to load in the screen. Maybe there is simple solution to load the page other.. 

Kind regards,
Erwin

**Comment by alexanderzobnin** [comment]
@erwinbentelo what is a "Magic Info screen"?
