### ISSUE TITLE
create query templating in Services IT ?

### ISSUE THREAD

**Issue by diegoarioza** [alexanderzobnin/grafana-zabbix#555]
- [X ] Feature requestdd
- [ ] Question / Support request

I would like to know if it is possible to add the functionality of creating querys in templating to create menus in dropdown dynamically in zabbix, currently I can only create with the smabicas of zabbix, I would like to create with services it too

**Comment by alexanderzobnin** [comment]
Not sure this is possible now. Zabbix doesn't have any query language, so it's tricky to implement this.
