### ISSUE TITLE
Timeshift sign inverted

### ISSUE THREAD

**Issue by xdexter** [alexanderzobnin/grafana-zabbix#557]
### I'm submitting a ...
- [ X ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v5.0.0   | 2.4.8  | 3.9.0  |

#### What did you do?
Use timeshift function

#### What was the expected result?
The function display correct values.

#### What happened instead?
The signal is inverted: If a minus sign ( - ) is used the shift metric forward in time (timeshift_-24.png). 
![timeshift_-24](https://user-images.githubusercontent.com/10849509/38641355-2318e82a-3dad-11e8-8004-b8d235d9e77b.png)

If a plus sign ( + ) is given, the metric back in time (timeshift_+24.png
![timeshift_ 24](https://user-images.githubusercontent.com/10849509/38641357-23386e02-3dad-11e8-8602-68ec7b309d1c.png)

**Comment by alexanderzobnin** [comment]
It's not a bug. Behaviour is described in docs http://docs.grafana-zabbix.org/reference/functions/#time
