### ISSUE TITLE
Able to get node's macroses

### ISSUE THREAD

**Issue by denser** [alexanderzobnin/grafana-zabbix#558]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature requestdd
- [ ] Question / Support request

Здравствуйте, так понимаю разработчик русскоговорящий?
Есть одна потребность в выгрузке макросов для узла сети(наследуемые и т.п.)

Это необходимо тогда, когда триггер формируется из нескольких условий и он не очевиден на графике сразу.

**Comment by alexanderzobnin** [comment]
Здравствуйте! Да, с макросами есть проблемы - API не все макросы раскрывает, для нормальной их поддержки фактически надо всю логику по работе с ними добавлять в плагин - это требует много времени.

**Comment by alexanderzobnin** [comment]
Без разницы - из базы берутся только исторические данные.
