### ISSUE TITLE
Group is missing

### ISSUE THREAD

**Issue by yarons** [alexanderzobnin/grafana-zabbix#559]
**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0.4   | 3.4.7  | 3.9.0                 |

#### What did you do?
Tried adding servers inside a group called "Services"

#### What was the expected result?
To be able to select a machine and a related item from this group

#### What happened instead?
It does not appear

I can see all the other groups I created but this one was there originally when I installed Zabbix, does it have anything to do with it?

**Comment by alexanderzobnin** [comment]
Maybe you should check permissions for this group.
