### ISSUE TITLE
Cannot read property 'itemid' of undefined

### ISSUE THREAD

**Issue by koto137** [alexanderzobnin/grafana-zabbix#56]
Hi again,

Two days ago, I've added new OID to my Printer Zabbix template, for counting papers printed. When I tried to "Graph/Single stat" in dashboard it shows error. I've restarted both Grafana and Zabbix services several times. I am helpless myself. Could you please help me out ?

Here is screen of the error, respose tab is empty.

![image](https://cloud.githubusercontent.com/assets/11044793/8743352/52e044c0-2c6e-11e5-833d-4af81e9dd59b.png)

Thank you.

**Comment by alexanderzobnin** [comment]
Are you use trend patch?

**Comment by koto137** [comment]
No I have not heard of it

**Comment by alexanderzobnin** [comment]
Try to disable trends in plugin.json file.

**Comment by koto137** [comment]
Works now, I will try to find the trend patch and will let know how it went. Thank for support so far.

**Comment by alexanderzobnin** [comment]
There is link to patch in [installation docs](https://github.com/alexanderzobnin/grafana-zabbix/wiki/Installation#trends-support)

**Comment by koto137** [comment]
Will try that on Monday :+1:

**Comment by clems94** [comment]
Hi, i have the same problem. I installed the patch on my 2.2.8 zabbix server but i can not get the trends. Could you help me
