### ISSUE TITLE
Feature request: Implement removeAboveValue, removeBelowValue and transformNull to filter/transform the data

### ISSUE THREAD

**Issue by gelonsoft** [alexanderzobnin/grafana-zabbix#562]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature requestdd
- [ ] Question / Support request

Implement removeAboveValue, removeBelowValue and transformNull functions like in Graphite ( http://graphite.readthedocs.io/en/latest/functions.html )

removeAboveValue - replace value with NULL if value > N
removeBelowValue - replace value with NULL if value < N;
transformNull  - replace null values with N

Example of removeAboveValue(N): 
  - Input series (";" as separator): 0;1;2;3;4;5;6
  - Function definition: "removeAboveValue(3)"
  - Output series: 0;1;2;3;null;null;null

Example of removeBelowValue(N)
  - Input series (";" as separator): 0;1;2;3;4;5;6
  - Function definition: "removeBelowValue(3)"
  - Output series: null;null;null;3;4;5;6

Example of transformNull(N):
  - Input series (";" as separator): 0;null;2;null;4;null;6
  - Function definition: "transformNull(3)"
  - Output series: 0;3;2;3;4;3;6

**Comment by danielkucera** [comment]
Hi @alexanderzobnin , are you planning to tag a new release with these features any soon?

**Comment by alexanderzobnin** [comment]
Yes, I'm going to release new version in next few days.
