### ISSUE TITLE
[Feature request] Add "Value mapping" support

### ISSUE THREAD

**Issue by frogour** [alexanderzobnin/grafana-zabbix#567]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature requestdd
- [ ] Question / Support request

Hello can you add value mapping support?
I have in one "valuemap" 800 values and 240 values in other. I just import their to zabbix from *.xml, but grafana does not have import functionality, and creating 800 values manually is difficult.

**Comment by alexanderzobnin** [comment]
@frogour which panel do you want to use with value mapping? Singlestat, Table?

**Comment by frogour** [comment]
yes, singlestat and table.

**Comment by alexanderzobnin** [comment]
It's not a plugin feature.
