### ISSUE TITLE
Permission to see only a group of hosts

### ISSUE THREAD

**Issue by julianoromani** [alexanderzobnin/grafana-zabbix#568]
### I'm submitting a ...
- [ ] Bug report
- [X ] Feature requestdd
- [ ] Question / Support request

When configure a datasource, an option to select 1 or more groups. With this option, I can create Organization to my clients, and its possible let then create new dashboads and their not have access to others groups that not have permissions.

**Comment by alexanderzobnin** [comment]
It's not a plugin feature, this may be implemented in Grafana only.
