### ISSUE TITLE
After upgrade grafana to 5.X and zabbix pluggin to 3.9, zabbix triggers panel is not working

### ISSUE THREAD

**Issue by ufoloko** [alexanderzobnin/grafana-zabbix#574]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.1.2   | 3.2.6  | 3.9.1                 |

#### What did you do?
I upgraded Grafana to 5.1.2 and Zabbix plugin to 3.9.1

#### What was the expected result?
All dashboards to work 

#### What happened instead?
Zabbix Triggers Panel is not working, I receive error in next image. All other dashboards are working normally

![image](https://user-images.githubusercontent.com/1165122/40125289-2cd42236-58f0-11e8-96d4-fd123ec7c1e4.png)

**Comment by alexanderzobnin** [comment]
Looks like a cache issue? Can you reset browser cache and try again?

**Comment by krptg** [comment]
Issue cleared by clearing browser cache.

**Comment by ceinmart** [comment]
Hi , 
I just install the grafana 5 , instaled the zabbix plugin using the grafana-cli , configured successfully my zabbix datasource and then import a zabbix template where get this same error:

> Plugin Error
> Fetch error: 404 Not Found Instantiating http://jdivm04:3000/public/react Loading http://jdivm04:3000/public/plugins/alexanderzobnin-zabbix-app/panel-triggers/module.js Loading plugins/alexanderzobnin-zabbix-app/panel-triggers/module
> 

I check the plugin path and doesn't match with the error message where the folder panel-triggers are into the folder dist .
```
root@jdivm04:/var/lib/grafana/plugins
# find . -name panel-triggers
./alexanderzobnin-zabbix-app/src/panel-triggers
./alexanderzobnin-zabbix-app/dist/panel-triggers

```

There is a quick fix for this ? 
I tried to create a symbolic link but the error keep occurring .
Then I tried to trick the server where I mount using bind the folder and still not recognizing it. 
I enable at grafana.ini the parameters below but the log files doesn't change when I refresh the dashboard and they show the error.
(between all theses steps I restarted the server)
```
[log]
mode = console file
level = error

```

**Comment by ceinmart** [comment]
Hi @alexanderzobnin , 
I just install the grafana 5 , instaled the zabbix plugin using the grafana-cli , configured successfully my zabbix datasource and then import a zabbix template where get this same error:
I tried clear the browser cache or opening it in private mode (firefox), the error still occuring. 

> Plugin Error
> Fetch error: 404 Not Found Instantiating http://jdivm04:3000/public/react Loading http://jdivm04:3000/public/plugins/alexanderzobnin-zabbix-app/panel-triggers/module.js Loading plugins/alexanderzobnin-zabbix-app/panel-triggers/module
> 

I check the plugin path and doesn't match with the error message where the folder panel-triggers are into the folder dist .
Not sure if this could be relationed
```
root@jdivm04:/var/lib/grafana/plugins
# find . -name panel-triggers
./alexanderzobnin-zabbix-app/src/panel-triggers
./alexanderzobnin-zabbix-app/dist/panel-triggers

```

I enable at grafana.ini the parameters below but no useful data appear at the log files .
```
[log]
mode = console file
level = debug

-----

t=2019-03-15T14:28:54-0300 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/react status=404 remote_addr=101.0.0.53 time_ms=3 size=7210 referer="http://jdivm04:3000/d/IjsnQZqmz/linux-zabbix-server?orgId=1"
t=2019-03-15T14:28:54-0300 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/react-dom status=404 remote_addr=101.0.0.53 time_ms=4 size=7210 referer="http://jdivm04:3000/d/IjsnQZqmz/linux-zabbix-server?orgId=1"

```

Also, when I create a new dashboard when I tried to include the "Zabbix Problem" panel, give the same error.

How can I collect more information to try understand what is happen ?

Ps.: I'm new to grafana, no experience with it yet.

**Comment by alexanderzobnin** [comment]
@ceinmart Plugin should work with Grafana 5.4.3. Ensure you have latest 5.x version.

**Comment by ceinmart** [comment]
I installed v5.0 from the openSuse repository. 
Removed it and installed the last version tarball , 6.0.2 , it's working now!
Thank you!

**Comment by qianxiaodewo** [comment]
![PXPAQ{B$T8X0D$CV(4`5JDW](https://user-images.githubusercontent.com/25760013/64223142-4e7b4b80-cf05-11e9-9f0d-326ffb89c379.png)

**Comment by qianxiaodewo** [comment]
my use grafana-cli plugins install alexanderzobnin-zabbix-app
install fils 
![image](https://user-images.githubusercontent.com/25760013/64223194-82ef0780-cf05-11e9-9df2-71aa22ea9374.png)
