### ISSUE TITLE
Ability to show a host name for one host in graph 

### ISSUE THREAD

**Issue by Semiadmin** [alexanderzobnin/grafana-zabbix#575]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| x.x.x   | x.x.x  | x.x.x                 |

#### What did you do?
_Describe here_

#### What was the expected result?
_Describe here_

#### What happened instead?
_Describe here_

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by Semiadmin** [comment]
Hi, Alexander.
There isn't the hostname in the graph if all charts belong to a single host. It's good in most cases, but I'd like to be able to alter this behavior.
For example, I'm using the variable $host, selected "All", and got the charts of only one host. Maybe, other hosts don't have such values or the "top" filter used and a single host won all prises.
In this case, the hostname is unclear.

**Comment by thanhtuan** [comment]
![image](https://user-images.githubusercontent.com/43368493/46998761-b68a3d00-d14d-11e8-8ca7-dde09c5dcdf4.png)
Hello @alexanderzobnin How to show a host name only in graph. Sorry my english.

**Comment by alexanderzobnin** [comment]
@thanhtuan use `replaceAlias()` function.

**Comment by Firxiao** [comment]
Hi Guys.  Is there any update? 
I have the same issue when creating a dashboard which contains multiple zabbix datasource.  
If there is only one host in that zabbix, it won't show the hostname.

**Comment by alexanderzobnin** [comment]
Added in 6729de0e489c99358fe2dc6e55e0542c85f572aa
It's possible now with `setAlias($__zbx_host_name: $__zbx_item)`

**Comment by fabianfasserIX** [comment]
The problem isn't solved. Because i've got the same problem with Version 5.4.3 of Grafana. I have a overview of different VMs and their Volume usage. Now for Volume M: There is only one entry. And this entry only shows the item name and not the name of the virtual machine. All the other ones whrere there are more than one machines with the same item shows it in the right way.

Any Idea?

**Comment by alexanderzobnin** [comment]
@fabianfasserIX Did you try to use `setAlias($__zbx_host_name: $__zbx_item)`?

**Comment by fabianfasserIX** [comment]
Yes but it only works for one specific host. If I use the Filer "All" it takes every single host into it.

**Comment by vldbel** [comment]
@alexanderzobnin 
$__zbx_host_name may contain dozens of hosts, so it is not possible to make this kind of aliasing.
It is especially annoying for mixed datasource graph connected to several zabbix instances. 
Suddenly it becomes a mix of named and unnamed hosts:
![image](https://user-images.githubusercontent.com/13711403/87956458-bd2eac80-cab7-11ea-8525-1ba86dee76cb.png)

**Comment by vldbel** [comment]
Sorry, setAlias($__zbx_host_name: $__zbx_item) works. But it requires to edit all the graphs in all dashboards. Not pretty easy task. 
Is there a chance to fix that on plugin level?

**Comment by ssantrosyan** [comment]
Hello,

I have the same issue in my grafana after upgrading it to a new 8.1.1 version. How can I solve the issue without updating the all dashboards with the setAlias($__zbx_host_name: $__zbx_item) solution ?

Thanks.
