### ISSUE TITLE
Error value

### ISSUE THREAD

**Issue by bob69xxx** [alexanderzobnin/grafana-zabbix#578]
![screenshot from 2018-05-24 08-00-46](https://user-images.githubusercontent.com/999269/40481757-bb5ec3ec-5f28-11e8-8f27-81398476bbb1.png)
![screenshot from 2018-05-24 08-01-01](https://user-images.githubusercontent.com/999269/40481759-bbba3308-5f28-11e8-9629-d7a5a8e5b8a2.png)

### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 4.6.2   | 3.4.6 | 3.9.1                |

#### What did you do?
nothing

#### What was the expected result?
-----

#### What happened instead?
-----
![screenshot from 2018-05-24 07-35-01](https://user-images.githubusercontent.com/999269/40481509-0a5fe8aa-5f28-11e8-8e6f-f76eae84d9c0.png)

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Could you describe what you do?

**Comment by nayfeng** [comment]
I have the same problem when I add the zabbix data sources

**Comment by alexanderzobnin** [comment]
Why do you enable basic auth? It's Zabbix API error, but not sure what's a reason.
