### ISSUE TITLE
Trim : for tag without value

### ISSUE THREAD

**Issue by rerime** [alexanderzobnin/grafana-zabbix#579]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.1.3   | 3.4.9  | 3.9.1                 |

![image](https://user-images.githubusercontent.com/7099570/40658865-3679e6c6-6355-11e8-8b64-4bb378ec2b7f.png)

**Comment by alexanderzobnin** [comment]
Why doesn't that tag have a value?

**Comment by rerime** [comment]
I need a tag for filtering purpose. Example trigger based on server location.
