### ISSUE TITLE
Custom Json Query

### ISSUE THREAD

**Issue by gustavoyanes** [alexanderzobnin/grafana-zabbix#581]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [ x] Question / Support request

Hi is there a way to pass to zabbix a custom json request so we can get data not on the predefined requests?

thanks

**Comment by alexanderzobnin** [comment]
It's not possible now, but I think about it sometimes. It's tricky to handle response, because it's just an arbitrary JSON. Do you have any thoughts on this? What exactly do you want to get?

**Comment by gustavoyanes** [comment]
I was trying to get a host count to put basically what zabbix dashboard shows, but with a pie chart, lets say host with problems and hosts with out problems from a group....

Thanks
