### ISSUE TITLE
Fetch error: 404 Not Found Instantiating

### ISSUE THREAD

**Issue by wangsz05** [alexanderzobnin/grafana-zabbix#582]
hi，I hava a install problem,   I  am put the the all source in the path "/grafana-5.1.3/public/app/plugins/app"  with the name "alexanderzobnin-zabbix-app"
 but  when I restart grafana service , 
 hava the Plugin Error :
Fetch error: 404 Not Found Instantiating http://hostIP:3000/public/app/plugins/app/alexanderzobnin-zabbix-app/module Loading app/plugins/app/alexanderzobnin-zabbix-app/module

**Comment by alexanderzobnin** [comment]
You shouldn't put it into `public/app/plugins/app`, use `/var/lib/grafana/plugins` instead.

**Comment by jimmeychen14** [comment]
@wangsz05 I think you install the grafana on the windows right? cuz I met the same problem as you. Did you find anyway to solve it?

@alexanderzobnin Did you have any Idea about this problem on windows environment? Thx.

**Comment by alexanderzobnin** [comment]
In windows plugins should be in `./data/plugins` I think.

**Comment by wangsz05** [comment]
@jimmeychen14  Maybe the Version is not support the grafana . I solved the problem with grafana-4.5.2-1.x86_64 version  and grafana-zabbix 3.70 version
