### ISSUE TITLE
Display Zabbix Dashboards and group status

### ISSUE THREAD

**Issue by ortizleo** [alexanderzobnin/grafana-zabbix#583]
Hello.

Really good work with this project, is amazing! I have some questions, can you help me?
¹How i can display a Dashboard from zabbix (tried text panel with html but display black screen)?
²How i can display host group status (without IT Services)? I can't get all hosts groups using Table, im testing with zabbix Admin user for API auth....
³There is another way to display zabbix triggers (table)?

**Comment by alexanderzobnin** [comment]
Take a look at this example http://play.grafana-zabbix.org/d/000000088/system-status-dashboard?orgId=2
