### ISSUE TITLE
Zabbix host name instead of visible name variable query. 

### ISSUE THREAD

**Issue by adyakin** [alexanderzobnin/grafana-zabbix#585]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [X] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0  | 3.4.8  | 3.8.1                 |

If there any way to use host name in template queries? Currently query return only Visible name from zabbix. 
Sometimes we have long visible names which can break panel layout and it is difficult to use them for variables with "custom" type as visible name ofter changes, while host name is constant.

In zabbix:
<img width="580" alt="zabbix_hostname" src="https://user-images.githubusercontent.com/2997369/41106971-ee4a6714-6a79-11e8-847f-6ff5aee50296.png">

Grafana variable:
query:
<img width="1038" alt="grafana_query" src="https://user-images.githubusercontent.com/2997369/41107038-1a4024da-6a7a-11e8-9bc0-292c2d9616b8.png">

preview:
<img width="546" alt="grafana_preview" src="https://user-images.githubusercontent.com/2997369/41107061-27a4caa4-6a7a-11e8-851f-062cb35898b9.png">

Also if in panel metrics query I manually set "Host" field to host name no data available, while setting to visible name work perfectly

<img width="724" alt="grafana_metrics" src="https://user-images.githubusercontent.com/2997369/41107168-69862eea-6a7a-11e8-93d3-6f79614b8e54.png">

Currently query return only Visible name from zabbix

**Comment by alexanderzobnin** [comment]
Query editor designed for work with visible names only. So changes in variable query make no sense without changing editor.

**Comment by alexanderzobnin** [comment]
opened new issue for query editor #606
