### ISSUE TITLE
 Could not connect to given url Grafana v5.1.3 (087143285) Integration Zabbix 3.9.1

### ISSUE THREAD

**Issue by leoswats** [alexanderzobnin/grafana-zabbix#586]
### I'm submitting a ...
- [X ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Grafana v5.1.3 | Zabbix 3.9.1 | XXXXX  |

#### What did you do?
Hello actually I'm new with zabbix and I'm trying integrate Zabbix with Grafana, and when I start to create a new Data Source ( the plugin zabbix is enabled)  doesn't show the direct and Proxy options ( only the options: Browser (default) and Browser )

after create the connection, the message  Could not connect to given url appears.

#### What was the expected result?
_Describe here_
![capturar](https://user-images.githubusercontent.com/40067395/41167281-d78ff710-6b18-11e8-8b0a-496436b2dfde.PNG)
![capturar1](https://user-images.githubusercontent.com/40067395/41167282-d7b2bc50-6b18-11e8-84ee-b650afc9ed0b.PNG)

RETURN:

curl -X POST -d '{"jsonrpc":"2.0","method":"apiinfo.version","params":[],"id":1}' -H "Content-Type:application/json" http://IP/zabbix/api_jsonrpc.php

{"jsonrpc":"2.0","result":"3.4.9","id":1}

curl -X POST -d '{"user":"admin","password":"admin"},"id":1}' -H "Content-Type:application/json" http://IP/zabbix/api_jsonrpc.php
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error","data":"Invalid JSON. An error occurred on the server while parsing the JSON text."},"id":null}

#### What happened instead?

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by alexanderzobnin** [comment]
Hi! The second request looks wrong:
```
curl -X POST -d '{"user":"admin","password":"admin"},"id":1}' -H "Content-Type:application/json" http://IP/zabbix/api_jsonrpc.php
```
Data should be like
```
{"jsonrpc":"2.0","method":"user.login","params":{"user":"admin","password":"admin"},"id":1}
```
Are you sure that request is made from plugin?

**Comment by roberdaniel** [comment]
I resolved it using Invoke-RestMethod instead of Invoke-WebRequest, and now api "understand" my json. (powershell code)
Curl never worked for me. is equivalen to to Invoke-WebRequest.
(I'm in Zabbix 4.2)

**Comment by MacroJG** [comment]
I met the same problem, I add a Zabbix datasource on remote host,  then click the "Save & Test" button , show "Could not connect to given url", but I already added a local host zabbix datasource successfuly.
My grafana and zabbix info:
grafana: 10.0.35.19:3000 v6.2.5
zabbix plugin:  3.10.2
zabbix datasource1: 10.0.35.19:8000  v4.2  (OK)
zabbix datasource2: 10.0.35.143:8010  v3.2  (NOK)
![图片](https://user-images.githubusercontent.com/14899667/61015510-814e0b00-a3be-11e9-8b54-5ff9adea3dec.png)
![图片](https://user-images.githubusercontent.com/14899667/61015546-a6427e00-a3be-11e9-8dbe-4735a146ed69.png)

**Comment by MacroJG** [comment]
Add Zabbix datasource like this:
![图片](https://user-images.githubusercontent.com/14899667/61015611-de49c100-a3be-11e9-8150-ceca06ae065e.png)
![图片](https://user-images.githubusercontent.com/14899667/61015624-eb66b000-a3be-11e9-80ab-d7799faa91a3.png)

**Comment by MacroJG** [comment]
Add zabbix datasource like this:
![图片](https://user-images.githubusercontent.com/14899667/61015663-22d55c80-a3bf-11e9-9ddc-f25754a4154d.png)
![图片](https://user-images.githubusercontent.com/14899667/61015673-32ed3c00-a3bf-11e9-8fb0-9b7d22d57861.png)

**Comment by MacroJG** [comment]
Problem resolved !
Just change the HTTP URL from
"http://10.0.35.143:8010/zabbix/api_jsonrpc.php"
to "http://10.0.35.143:8010/api_jsonrpc.php"
