### ISSUE TITLE
Some graph show problem

### ISSUE THREAD

**Issue by linahoo** [alexanderzobnin/grafana-zabbix#587]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [*] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.1.3   | 3.2.6 | 3.9.1            |

#### What did you do?
I want show [Available memory] item graph, but they just show only value? 

#### What was the expected result?
if I select other some item graph，they
can normal display.
#### What happened instead?
_Describe here_

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by linahoo** [comment]
![image](https://user-images.githubusercontent.com/9640208/41225607-c0c03e74-6da1-11e8-9557-59772e3bcbef.png)

**Comment by linahoo** [comment]
compare other item
![image](https://user-images.githubusercontent.com/9640208/41225745-1da07eec-6da2-11e8-8417-f53d2b50fbeb.png)

**Comment by alexanderzobnin** [comment]
Could you post your network query (history.get)?
