### ISSUE TITLE
Error creating alert

### ISSUE THREAD

**Issue by julianoduarte1983** [alexanderzobnin/grafana-zabbix#589]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [x] Question / Support request

Hello Alexander!

   I am trying create an alert on Grafana and I receive the message:

   error:"tsdb.HandleRequest() error Could not find executor for data source type: alexanderzobnin-zabbix-datasource"

   PS: I am using Grafana 5 and Zabbix Plugin 3.9.1

Thankyou!

**Comment by alexanderzobnin** [comment]
Zabbix plugin doesn't support Grafana alerting yet.

**Comment by R-Studio** [comment]
> Zabbix plugin doesn't support Grafana alerting yet.

Is this planned for the future?

**Comment by alexanderzobnin** [comment]
@R-Studio yes, work in progress in the `backend` branch.
