### ISSUE TITLE
Иногда не определяются единицы измерений

### ISSUE THREAD

**Issue by flashick** [alexanderzobnin/grafana-zabbix#59]
Здравствуйте!

Почему-то с некоторых графиков почему-то неправильно снимаются единицы измерения:
![image](https://cloud.githubusercontent.com/assets/4356395/8905613/723484a8-3470-11e5-843d-56a17c881ff3.png)
На верхнем графике - миллионы-биллионы, а на нижнем нужные гигабайты.

В обоих шаблонах единица измерения - B:
![image](https://cloud.githubusercontent.com/assets/4356395/8905639/9d484c1a-3470-11e5-894e-fcaa05c8dc71.png)

![image](https://cloud.githubusercontent.com/assets/4356395/8905651/addaf42e-3470-11e5-811f-e2a150a620ee.png)

**Comment by nucleusv** [comment]
А почему они должны определяться?
Вы сами ручками их должны проставлять на в кладке Axes&Grid

**Comment by flashick** [comment]
каюсь Т_Т
