### ISSUE TITLE
Fetch error:404 Not Found Instantiating

### ISSUE THREAD

**Issue by inuyashafff** [alexanderzobnin/grafana-zabbix#591]
### I'm submitting a ...
- [! ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**
both the latest
| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| x.x.x   | x.x.x  | x.x.x                 |
5.0| not install | 3.9.1
#### What did you do?
_Describe here_
I want to create the data source of zabbix and configure it.
#### What was the expected result?
_Describe here_
I can configure all the parameters in the config page, but it only have "Name" and "Type" and the 404 error
#### What happened instead?
_Describe here_
the configure page can not show up but the error appeared. But the readme and dashboards pages is normal
If it relates to metric data visualization would be great to get
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

I tried to clear the browser cache, but it still didn't work. 
![wechatimg2](https://user-images.githubusercontent.com/33760037/41493893-c8cbfc70-713e-11e8-9a3d-14065b1d0df3.jpeg)
![wechatimg1](https://user-images.githubusercontent.com/33760037/41493894-c94aae12-713e-11e8-9d0e-29e973729ec1.jpeg)
At first, I put the plugin in /var/lib/grafana/plugins, but I can't even see this plugin in the menu. Then I put this in /usr/share/public/app/plugins/datasource, the zabbix appears with the 404 error in config page

My system is Linux SUSE.

**Comment by alexanderzobnin** [comment]
You shouldn't use that repo for grafana 5. Use main repo instead or use `grafana-cli` to install.

**Comment by yileye** [comment]
how to fix this problem?
