### ISSUE TITLE
Status table or single panel with actual triggers

### ISSUE THREAD

**Issue by ortizleo** [alexanderzobnin/grafana-zabbix#597]
Hello.
Sorry for don't use the "form", its because i have some questions and not a problem...

1. How I can display hosts with triggers that are still active? 
With single state i can display only triggers on the time that is triggered, exemple:
-> Host A triggered yesterday and the trigger is still active, if I create a status table or single pannel with Today filter it will show 0 triggers (but have active trigger yet)...

2. Anyway to use the older trigger panel style? Like this https://github.com/alexanderzobnin/grafana-zabbix/issues/72
The "new" style ins't cool for use in a company environment...

**Comment by alexanderzobnin** [comment]
@ortizleo could you explain 1. in details? Screenshots would be helpful.

**Comment by ortizleo** [comment]
Yes. Follow attached.
![grafana-zabbix just display trigger on time that is generated](https://user-images.githubusercontent.com/17042298/43729611-3ed8190e-997f-11e8-9f5d-94467e515a7d.png)
![grafana-zabbix not show old active triggers](https://user-images.githubusercontent.com/17042298/43729612-3eff1536-997f-11e8-9a34-f5e7aa6d605f.png)

Look that when I filter "today" it not show the trigger, but when I filter a time before the trigger as generated, it works. The plugin don't works like zabbix dashboard that show all active triggers, just triggers that are generated at the filter time that we select.

**Comment by maskacola** [comment]
Any news about ch. 1?
Есть какие-либо новости по пункту 1?

**Comment by alexanderzobnin** [comment]
I think 1. is possible with SQL query. Take a look at this example:
http://play.grafana-zabbix.org/d/000000083/zabbix-db-mysql?panelId=4&orgId=2
