### ISSUE TITLE
Aggregate functions

### ISSUE THREAD

**Issue by menardorama** [alexanderzobnin/grafana-zabbix#60]
First of all your plugin is just great, this was something I was looking for.

I wonder if it would be possible for you to implement wildcards in item name.

For example, I monitor device mapper disks, the number and the name of the decives can change.

Ideally I would like to be abble to specify an item name like "dm-*" for example.

I really don't know if zabbix API support it.

Thanks

**Comment by alexanderzobnin** [comment]
Hello! I am thought about a similar feature. I think, will be useful to extract part of item's name by regex and use it as part of alias. I need some details about your case - what is the item names and what is the resulted alias?

**Comment by alexanderzobnin** [comment]
Hmm... Or may be you looking for regex [filters](https://github.com/alexanderzobnin/grafana-zabbix/wiki/Usage#filters)?

**Comment by menardorama** [comment]
Well regex filters can work (I use it already) but idealy aggregate functions could help me.

Do you plan to implement it ?

**Comment by alexanderzobnin** [comment]
What you mean by aggregate functions?

**Comment by menardorama** [comment]
I mean instead of using regex to select a subset of items and display them, I would need aggregate functions like avg, median, max...

And it would only display one value.

But I don't know if Grafana can handle it or if it's the backend data source that manage that (like in influxdb)

**Comment by alexanderzobnin** [comment]
Ok, I understand. Indeed, Graphite and InfluxDB provides these functions on server side. Zabbix don't have similar functional, but it's possible to realize aggregation on client side (in Grafana).  	
I plan to do it soon.

**Comment by menardorama** [comment]
Great thanks

**Comment by seuf** [comment]
Hi, You can create aggregate item in Zabbix with calculated items. Maybe it can help...

**Comment by olfway** [comment]
I've just created PR for this issue https://github.com/alexanderzobnin/grafana-zabbix/pull/118

**Comment by alexanderzobnin** [comment]
Fixed by 0680f653709eaf790737f4bf6c28857e208d0ce7
