### ISSUE TITLE
CircleCI 1.0 is being closed

### ISSUE THREAD

**Issue by g-goessel** [alexanderzobnin/grafana-zabbix#601]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

Have you seen [https://circleci.com/sunset1-0/](https://circleci.com/sunset1-0/) ?
The CI will fail at the end of next month.

**Comment by alexanderzobnin** [comment]
Yes, I see. I should migrate to 2.0.
