### ISSUE TITLE
consolidateBy on one metric affects other metrics in a panel

### ISSUE THREAD

**Issue by jedd** [alexanderzobnin/grafana-zabbix#602]
### I'm submitting a ...
- [X ] Bug report

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.1.3   | 3.4.5  | 3.9.0                 |

#### What did you do?
I have 14 hosts providing CPU utilisation numbers.   I'm investigating ways to resolve the problem of short-time zoom (eg. 2d) showing 100% peaks, but these peaks being hidden on longer time-ranges (eg. 7d).

Using 'consolidateBy()' function on the data, I get accurate graphs - showing the 100% peak.

I set up a two metric queries over a 7d period - this shows raw (showing lower-averages) for the 14 hosts, and I set up a similar query with two functions - top(x, max) and consolidateBy(max) to show both the broader averages along with one or more outliers (via the top()).

#### What was the expected result?
I expected the 14 hosts results from the first metric to appear the same in the graph - showing the lower overall averages for the period.

And a single additional item on the graph showing the one host with the highest maximum peaks during that same period

#### What happened instead?
All hosts appear to 'adjust upwards', as though affected by the consolidateBy(max) function on the second query.

I added a 'consolidateBy(avg)' on the first metric to try to force that back down, but this had no effect.

If I relocate the metrics (consolidateBy(max) moves to first location) then all values remain 'lower overall average', so the last consolidateBy() used on a panel seems to affect all metrics pulled in from each query.

I have not yet experimented with pulling metrics from different application / items and using consolidateBy() against these, but it's the feature of using the same source metrics that is needed here.

Two attachments showing lower-overall averages, with second metric hidden, and in second image all values are lifted up to local maxima values.

![2018-07-26 - grafana zabbix issue - 1 of 2 - main set of metrics shown](https://user-images.githubusercontent.com/114736/43292943-1d0537be-917b-11e8-85e5-fba1945cca1b.png)

![2018-07-26 - grafana zabbix issue - 2 of 2 - both set of metrics shown with heightened maxs](https://user-images.githubusercontent.com/114736/43292949-237d185a-917b-11e8-8bdb-9a041e2f3922.png)

**Comment by alexanderzobnin** [comment]
@jedd Do you use direct db connection? Can you confirm this bug still present in plugin version `3.9.1`?

**Comment by alexanderzobnin** [comment]
It seems, it was fixed by 16861ad
