### ISSUE TITLE
Triggers Pannel direct link rendered image bug

### ISSUE THREAD

**Issue by dimitribellini** [alexanderzobnin/grafana-zabbix#605]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [x] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.1.4   | 3.4.9  | 3.9.1                 |

#### What did you do?
I'm testing a very cool tool for Grafana, Grafana Reporter (https://github.com/IzakMarais/reporter), this tool is able to create a PDF based on Grafana API and the panels inside a dashboard.
With every Grafana stock panels and Grafana Zabbix plugins i could create the PDF without problems but if i use "Triggers panel" inside my dashboard the PDF is created but on the place of "Triggeers Panel" i can only see a black image.
To create this PDF the Grafana Reporter download every panels using this API: http://xxx.xxx.xxx.xxx:3000/render/d-solo/7dhxGBKik/_?from=now-1h&height=150&panelId=5&theme=light&to=now&var-datasource=default&width=300

For Trigger Panel is the same: http://xxx.xxx.xxx.xxx:3000/render/d-solo/7dhxGBKik/_?from=now-1h&height=500&panelId=9&theme=light&to=now&var-datasource=default&width=1000

But in that case i can only see a blank image with the name of panel and the loading circle but not the line with triggers. 
Please check below image:
![triggers_panel](https://user-images.githubusercontent.com/16684861/43361110-fc448802-92c6-11e8-9d0e-f0d570683527.png)

For what i could understand seems not a problem of "Grafana Reporter" but something related on how Trigger Panel is made.

Could you check it?
Thanks very much for your great work!

**Comment by dimitribellini** [comment]
I have also found a discussion on the "issue" tracker of Grafana Repoter https://github.com/IzakMarais/reporter/issues/29
The last comment ask to open a case in Zabbix Plugin.
Thanks for any help

**Comment by alexanderzobnin** [comment]
Yes, looks like a bug during panel rendering.

**Comment by dimitribellini** [comment]
@alexanderzobnin Did you think you could fix it? :-)
Thanks very much!

**Comment by alexanderzobnin** [comment]
Yes, sure, I'll try to fix it in next patch release.

**Comment by alexanderzobnin** [comment]
That was a trouble with phantomjs again (it renders panel as image on backend side). It doesn't handle `display: flex` blocks properly, so we have to add special hacks for CSS styles. Now it looks better:

![triggers-redesign](https://user-images.githubusercontent.com/4932851/45567457-8d327480-b862-11e8-95a9-1ffcadd8af8e.png)
