### ISSUE TITLE
Graph with 2 servers, I want the server name in the Legend

### ISSUE THREAD

**Issue by jensolsson** [alexanderzobnin/grafana-zabbix#607]
### I'm submitting a ...
- [ ] Bug report
- [ ] Feature requestdd
- [x] Question / Support request

Thanks for a great plugin!

I have a graph where I include a metric from 2 servers. Since it is the same metric they get the same name and I do not know which line in the graph belong to which server. Is it possible to prefix the name with the host name etc?

**Comment by g-goessel** [comment]
Absolutely, I think you want to use `Functions > setAlias` or `setAliasByRegex`.
You will find these options just below the query.
![image](https://user-images.githubusercontent.com/1839013/44900106-029b3280-ad04-11e8-9534-664c558ea18e.png)

**Comment by alexanderzobnin** [comment]
Related to #575

**Comment by alexanderzobnin** [comment]
Added in 6729de0e489c99358fe2dc6e55e0542c85f572aa
It's possible now with `setAlias($__zbx_host_name)`

**Comment by trwtsn** [comment]
This doesn't seem to be working in v9.3.6 with $__zbx_host

![Screen Shot 2023-03-10 at 10 46 45 AM](https://user-images.githubusercontent.com/96088814/224387478-ac94a7d3-ad4d-45ac-8f4c-cd8044d75606.png)
![Screen Shot 2023-03-10 at 10 46 35 AM](https://user-images.githubusercontent.com/96088814/224387482-992d82b6-37b3-40e0-9a46-c7d7818acc24.png)
