### ISSUE TITLE
Annotation don't filter on the host

### ISSUE THREAD

**Issue by menardorama** [alexanderzobnin/grafana-zabbix#61]
Hi,

I don't know if I'm going wrong but I setup a dashoard using templating and trying to add anotation (to add the triggers raised for a specific host (the one choosen with templating)).

I'm trying to add my variable in the filter but it doesn't seem to work.

For example I add a $Server to list all the servers, I then add an annotation where I want all the trigger for this host.

If I just put a "*" in the filter it brings me all the triggers but not only my host selectec with the templating....

Maybe I am doing wrong ?

**Comment by alexanderzobnin** [comment]
Hello! Now I have some troubles with annotations. I will improve this feature.

**Comment by menardorama** [comment]
OK thanks

**Comment by menardorama** [comment]
but let me tell you your plugin is great !

Compared to the ugly zabbix interface

**Comment by alexanderzobnin** [comment]
Hope, my plugin helps many people to use powerful Grafana features.

**Comment by alexanderzobnin** [comment]
See also my issue about Zabbix datasource in grafana: https://github.com/grafana/grafana/issues/2332

**Comment by alexanderzobnin** [comment]
@menardorama Try to use code from develop branch. Now you able to use templated variables for filter triggers which belong to selected host. See [Annotations](http://play.grafana-zabbix.org/dashboard/db/annotations) dashboard example.

**Comment by volter** [comment]
Should you run Zabbix 2.2, you are probably bitten by ZBX-6834!  All you need to do, is do the equivalent to how they fixed it for 2.4: http://geofrogger.net/review/ZBX-6834.patch
