### ISSUE TITLE
Don't display negative threshold

### ISSUE THREAD

**Issue by poisonedPawn** [alexanderzobnin/grafana-zabbix#611]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.2.2   | 3.4.12  | 3.9.1                 |

#### What did you do?
I created a trigger prototype in Zabbix. The trigger evaluate if the last value is less than -30.
I enable the alerting and the threshold adding in the configuration of Zabbix datasource in grafana.

#### What was the expected result?
I expected to view the line of the threshold drawn in the grafana graph.

#### What happened instead?
The query inspector looks like it shows the correct information
![issue_3](https://user-images.githubusercontent.com/25950905/44335585-3f019f80-a475-11e8-85f9-c52b29d59558.png)

but Grafana doesn't show the threshold in the graph and in the configuration of display the threshold, the value doesn't appear
![issue_2](https://user-images.githubusercontent.com/25950905/44335403-a408c580-a474-11e8-968c-8cbcd3c8f829.png)

**Comment by alexanderzobnin** [comment]
It's possible, but if your data is greater than -30 you have to set Y min in axis tab:

![screenshot from 2018-09-14 18-28-12](https://user-images.githubusercontent.com/4932851/45559805-20ac7b00-b84c-11e8-94c1-18ea61a04e49.png)

![screenshot from 2018-09-14 18-27-58](https://user-images.githubusercontent.com/4932851/45559806-20ac7b00-b84c-11e8-9a46-0c826ec734c2.png)

**Comment by alexanderzobnin** [comment]
It seems, it's related to #623
