### ISSUE TITLE
alexanderzobnin vulnerability

### ISSUE THREAD

**Issue by wobushou** [alexanderzobnin/grafana-zabbix#616]
#######
use viewer user login 
  Access  http://xxx.com/org/users/ link 
 use Burpsuite  View packet 
 i found clear password in packet .
 wobushou1@gmail.com

**Comment by v-zhuravlev** [comment]
See https://github.com/alexanderzobnin/grafana-zabbix/issues/312

**Comment by alexanderzobnin** [comment]
This duplicates #380
