### ISSUE TITLE
Zabbix Triggers with multiple Groups

### ISSUE THREAD

**Issue by dimasmir** [alexanderzobnin/grafana-zabbix#617]
### I'm submitting a ...
- [x] Feature requestdd
- [x] Question / Support request

#### What did you do?
Add Zabbix Triggers panel and try to indicate multiple Groups.

#### What was the expected result?
Expect to be able to specify multiple groups as on zabbix web frontend.

#### What happened instead?
I can specify only one group

If it relates to metric data visualization would be great to get

![image](https://user-images.githubusercontent.com/8957403/45476053-a7773000-b746-11e8-8e50-3c9e6fceca02.png)
![image](https://user-images.githubusercontent.com/8957403/45476113-cecdfd00-b746-11e8-88eb-0740d5e886a3.png)
![image](https://user-images.githubusercontent.com/8957403/45476134-d8effb80-b746-11e8-9e4e-219e3d55545c.png)

**Comment by alexanderzobnin** [comment]
Use regex for this purpose:
```
/(Backend)|(Database servers)|(Frontend)/
```
http://play.grafana-zabbix.org/d/000000024/triggers?panelId=6&fullscreen&edit&orgId=2
