### ISSUE TITLE
Template Variable: Host having Application

### ISSUE THREAD

**Issue by jchmielniak** [alexanderzobnin/grafana-zabbix#618]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature requestdd
- [x] Question / Support request

I would like to get a template variable with hosts having some application.
We have a group with production linux host, but I would like use some host with items belonging to a specified application:
{my-big-group}{VARIABLE}{my-application}
Is it possible? Otherwise it would be nice to have.

Regards.

**Comment by alexanderzobnin** [comment]
Hm, it requires changing of variable query language. Not sure it's possible right now. I'll try to implement more flexible QL in backend plugin version.
