### ISSUE TITLE
Expose host, item, app and other info for alias functions

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#619]
It would be helpful to have information about each metric like hostname, item name, key, app, etc in `scopedVars` for alias functions. This will allow to use it like:
```
setAlias('$zbx_host: $zbx_item (app: $zbx_app)')
=>
server01: CPU load (app: performance)
```

**Comment by analogfire2** [comment]
+1 - it would be very useful to pass additional meta data on hosts to grafana (e.g. hostname in addition to the 'visible name', IP, description, etc)

**Comment by meyerder** [comment]
Will this include additional tags?

**Comment by alexanderzobnin** [comment]
@meyerder If host or item objects include tags, it's possible.

**Comment by alexanderzobnin** [comment]
Implemented:

Following template variables available for using in `setAlias()` and `replaceAlias()` functions:

- `$__zbx_item`, `$__zbx_item_name` - item name
- `$__zbx_item_key` - item key
- `$__zbx_host_name` - visible name of the host
- `$__zbx_host` - technical name of the host

Examples:
```
setAlias($__zbx_host_name: $__zbx_item) -> backend01: CPU user time
setAlias(Item key: $__zbx_item_key) -> Item key: system.cpu.load[percpu,avg1]
setAlias($__zbx_host_name) -> backend01
```
