### ISSUE TITLE
возврат страницы авторизации при попытке получить метрики

### ISSUE THREAD

**Issue by prudnitskiy** [alexanderzobnin/grafana-zabbix#62]
Установлено по документации, версии:
- zabbix 2.4.5
- grafana 2.0.2
- grafana-zabbix 2.0.1

Пришлось изрядно попрыгать с CORS, но после его настройки получил интересный эффект - при попытке запроса данных с zabbix - нет попытки авторизации, сразу производится запрос. Заббикс в ответ выдает стандартную страницу авторизации (форму с логином и паролем). Куда можно копать?

**Comment by alexanderzobnin** [comment]
А у вас правильно указан адрес API (api_jsonrpc.php)? Не совсем понял, как Заббикс АПИ может это выдать.

**Comment by prudnitskiy** [comment]
Да, ошибка оказалась в том, что путь data_source надо прописывать целиком (включая .php в названии). Наверное, будет разумным прописать это в документации, ибо для меня это было совсем не очевидно.

**Comment by alexanderzobnin** [comment]
Спасибо, я внесу изменения в документацию.
