### ISSUE TITLE
Can't Change Metric Alias in Grafana Using a Zabbix Plugin

### ISSUE THREAD

**Issue by farinaznz** [alexanderzobnin/grafana-zabbix#624]
I'm submitting a Question / Support request

I want to show multiple CPU Usage from different hosts in one graph but they all end up with the same name and I can't tell which line represents which host: 

![image](https://user-images.githubusercontent.com/43567034/46000763-5ce6a380-c0b6-11e8-99ef-0d4faa524281.png)

I'm using Grafana 5.2.4 with a Zabbix plugin 3.9.1. My Zabbix version is 3.0.12. I've tried overriding legends in Grafana but there's no such option. Also, Zabbix plugin doesn't allow connecting directly to DB, so I can't use the ALIAS BY option either. I've tried using macros in Zabbix to include host name in item name, but {HOST.NAME} just ends up as is in the item name (and not replaced by the actual values).

**Comment by jedd** [comment]
Hi farinaznz,

Could you share a screen shot of the metrics selection with Group / Host / Application / Item ?

I'm using API plugin as well, and have had good success with the ReplaceAlias function.

**Comment by alexanderzobnin** [comment]
@farinaznz You should use alias functions http://docs.grafana-zabbix.org/reference/functions/#alias
