### ISSUE TITLE
Zabbix 4.0 support

### ISSUE THREAD

**Issue by b1nary1** [alexanderzobnin/grafana-zabbix#625]
### I'm submitting a ...
- Question / Support request

Hi! Is it safe to upgrade Zabbix to 4.0 already now, while using version 3.9.1 of the plugin?

**Comment by julienleboeuf** [comment]
Hi,
I'm been using grafana-zabbix 3.9.x with zabbix 4.0 alpha since months ago without any problems.
And of course, it's working fine with new stable release

**Comment by b1nary1** [comment]
Thanks! I upgraded successfully to 4.0 just now and can confirm that plugin is working just fine.
