### ISSUE TITLE
Grafana dashboard is inconsistent after Zabbix server failure

### ISSUE THREAD

**Issue by herbertdeborba** [alexanderzobnin/grafana-zabbix#626]
### I'm submitting a ...
- [x] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|5.2.4   | 3.4.14  | 3.9.1                 |

#### What did you do?

When Zabbix server suffers a failure and stays out for a couple of hours, Grafana fails to get the actual data values after the issue with Zabbix server is solved, It randomly shows "N/A" for the panels of a certain dashboard. If we leave it quiet for, like, 4+ hours, Grafana behavior seems to get back to normal. 

#### What was the expected result?

Grafana dashboard should show the correct data values immediately after we solve the issue with the Zabbix server. Data are ok when we check it at the Zabbix web interface.

#### What happened instead?

Grafana throws "API Error" for the dashboard, and some panels are randomly shown as N/A. 

If it relates to metric data visualization would be great to get
- An image or text representation of your metric query

### Zabbix web manager is showing the correct data as expected:

![image](https://user-images.githubusercontent.com/34314852/46429733-97d38180-c71d-11e8-9fef-b8258629b682.png)

### Grafana displays "API Error", randomly showing "N/A" for some of it's panels:

For instance, in the screen below, it fails to get the data for Eproc1g DMZ:

![image](https://user-images.githubusercontent.com/34314852/46429693-75416880-c71d-11e8-92cb-d96c97fc2908.png)

When we hit refresh, the data for the former appears ok, and now is Eproc1gSrv01 that is shown as "N/A":

![image](https://user-images.githubusercontent.com/34314852/46429913-fac51880-c71d-11e8-9c9e-1aaba4551762.png)

- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

![image](https://user-images.githubusercontent.com/34314852/46431291-cb180f80-c721-11e8-9a9e-83ebd388b973.png)

![image](https://user-images.githubusercontent.com/34314852/46431771-1121a300-c723-11e8-8186-96b9bdd4959a.png)

![image](https://user-images.githubusercontent.com/34314852/46431893-58a82f00-c723-11e8-9c52-889f4028718a.png)

{"jsonrpc":"2.0","result":[{"itemid":"55860","name":"Available memory","key_":"vm.memory.size[available]","value_type":"3","hostid":"10326","status":"0","state":"0","hosts":[{"hostid":"10326","name":"Eproc1gSrv01"}]},{"itemid":"55853","name":"Free swap space","key_":"system.swap.size[,free]","value_type":"3","hostid":"10326","status":"0","state":"0","hosts":[{"hostid":"10326","name":"Eproc1gSrv01"}]},{"itemid":"55854","name":"Free swap space in %","key_":"system.swap.size[,pfree]","value_type":"0","hostid":"10326","status":"0","state":"0","hosts":[{"hostid":"10326","name":"Eproc1gSrv01"}]},{"itemid":"55861","name":"Total memory","key_":"vm.memory.size[total]","value_type":"3","hostid":"10326","status":"0","state":"0","hosts":[{"hostid":"10326","name":"Eproc1gSrv01"}]},{"itemid":"55855","name":"Total swap space","key_":"system.swap.size[,total]","value_type":"3","hostid":"10326","status":"0","state":"0","hosts":[{"hostid":"10326","name":"Eproc1gSrv01"}]}],"id":1}

**Comment by alexanderzobnin** [comment]
Do you have any errors in JS console when panel shows N/A? Could you log what `history.get` call returns for panel with N/A?
