### ISSUE TITLE
zabbix plugin upgrade plans for zabbix 4.0

### ISSUE THREAD

**Issue by klavik** [alexanderzobnin/grafana-zabbix#627]
### I'm submitting a ...
- [ ] Bug report
- [ *] Feature requestdd
- [ ] Question / Support request

Hi, Alexander
Thanx again for your work!
Could You share your plans about upgrade plans for plug-in? Zabbix 4.0 is already LTS. And we itching to upgrade.

**Comment by alexanderzobnin** [comment]
Hi! I just back from vacation, so going to work on this. I have to fix some 4.0-related issues and add support for Elastic as a direct DB connection source.
