### ISSUE TITLE
Error when attempting to acknowledge problems in Zabbix 4.0

### ISSUE THREAD

**Issue by rmudingay** [alexanderzobnin/grafana-zabbix#629]
### I'm submitting a ...
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request

_If you don't send bug report, remove sections below_
### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.2.4    |  4.0.0  |  3.9.1                            |

#### What did you do?
Upgrade Zabbix from version 3.4 to version 4.0.0. Previously able to acknowledge problems in Grafana. This is no longer the case. When attempting to acknowledge a problem, Grafana spews out 

"Zabbix API Error
Incorrect arguments passed to function."

#### What was the expected result?
The expected result is for the acknowledgement text to be sent to Zabbix.

#### What happened instead?
Encountered rrror message 
"Zabbix API Error
Incorrect arguments passed to function."

Javascript error console
![screen shot 2018-10-08 at 19 38 35](https://user-images.githubusercontent.com/26298040/46624886-56ced900-cb32-11e8-923a-0a9620a1094e.png)

Encountered the following error message
![screen shot 2018-10-08 at 19 41 09](https://user-images.githubusercontent.com/26298040/46624887-56ced900-cb32-11e8-85bf-7c101da70f51.png)

**Comment by alexanderzobnin** [comment]
Yes, in Zabbix API 4.0 _action_ became a required field, so I have to pass it in all cases.

**Comment by glardz** [comment]
hello Alexander,

i have the same problem, i have the error 

Zabbix API Error
Incorrect arguments passed to function.

i tried to close 

![image](https://user-images.githubusercontent.com/20502721/47216581-b97f6a80-d3a5-11e8-8295-bdc4ae1a4e1f.png)

but i have this message 

![image](https://user-images.githubusercontent.com/20502721/47216626-dddb4700-d3a5-11e8-85ba-74112e6afe5d.png)

**Comment by alexanderzobnin** [comment]
Fixed. To get this working you have to update datasource config and set proper Zabbix version (plugin will try to autodetect it, so just ensure that set to your version and save datasource):

![screenshot from 2018-10-21 12-15-13](https://user-images.githubusercontent.com/4932851/47265083-2a9c5a80-d52b-11e8-806d-d849d33ccb23.png)

**Comment by rmudingay** [comment]
@alexanderzobnin thank you for the fix and your reactivity, much appreciated.

**Comment by glardz** [comment]
hello Alexander,

thanks for reply, i don't have Zabbix version section for put the version.

![image](https://user-images.githubusercontent.com/20502721/47281875-4eb87400-d5dd-11e8-95f9-9df2e638faeb.png)

![image](https://user-images.githubusercontent.com/20502721/47281929-80313f80-d5dd-11e8-8bd4-8bf372bb3600.png)

**Comment by glardz** [comment]
i have a problem too with the sharing dashboard : 
![image](https://user-images.githubusercontent.com/20502721/47284702-9b557c80-d5e8-11e8-8d8d-ed2888a73d60.png)

**Comment by glardz** [comment]
hello Alexander,

i have an issue with sharing dashboard :+1: 
![image](https://user-images.githubusercontent.com/20502721/47284771-d8217380-d5e8-11e8-888a-f1b270f4c1fe.png)

**Comment by glardz** [comment]
and this message when i put last 30 days in the sharing dashboard

![image](https://user-images.githubusercontent.com/20502721/47284962-85948700-d5e9-11e8-9357-63fba97bf1ba.png)

**Comment by alexanderzobnin** [comment]
@glardz this change is not released yet. In order to try this, you should run plugin from master branch.

**Comment by glardz** [comment]
thanks Alexander for reply, can you give me the instruction for install with yarn please.

**Comment by alexanderzobnin** [comment]
You can find instructions in the docs I linked for.

**Comment by glardz** [comment]
yes i saw the instruction, but when i do yarn watch that freezing

![image](https://user-images.githubusercontent.com/20502721/47348750-6dd50580-d6b2-11e8-9fff-71105a8eba48.png)

**Comment by alexanderzobnin** [comment]
@glardz use `yarn build` instead. `yarn watch` is waiting for file changes.

**Comment by glardz** [comment]
i have this message 

![image](https://user-images.githubusercontent.com/20502721/47357812-1cd00c00-d6c8-11e8-8f52-096be3aad67a.png)

**Comment by glardz** [comment]
with command yarn test 

![image](https://user-images.githubusercontent.com/20502721/47357887-59036c80-d6c8-11e8-8332-b7527613f965.png)

**Comment by glardz** [comment]
and with command yarn jest

![image](https://user-images.githubusercontent.com/20502721/47357923-7f290c80-d6c8-11e8-8a41-fdeda4538a21.png)

**Comment by alexanderzobnin** [comment]
Plugin was successfully built, you don't need `test` and `jest` commands in this case.

**Comment by glardz** [comment]
hello Alexander,
what command i need to run the plugin, thanks

**Comment by glardz** [comment]
hello Alexander,

what command i need to implement the new version of grafana zabbix plugin, for now i am here

![image](https://user-images.githubusercontent.com/20502721/47499505-6c494000-d860-11e8-8562-36cf2cf0df34.png)

**Comment by glardz** [comment]
i updated with command grafana-cli plugins update grafana-zabbix-c73078d1fbc524aa2773560e42b9e73d9302b3a7   and this command grafana-cli plugins install alexanderzobnin-zabbix-app after i restart but i see this 

![image](https://user-images.githubusercontent.com/20502721/47556382-7aee3080-d90e-11e8-9459-af964d92fa90.png)

and not your window with zabbix version 

![image](https://user-images.githubusercontent.com/20502721/47556450-9bb68600-d90e-11e8-9d01-6801e93da43f.png)

**Comment by glardz** [comment]
and direct DB connection don't work 

![image](https://user-images.githubusercontent.com/20502721/47794154-2ab50b00-dd20-11e8-95cb-e026613a2e16.png)
