### ISSUE TITLE
Error with mapping and last value

### ISSUE THREAD

**Issue by yuriandradd** [alexanderzobnin/grafana-zabbix#63]
Hello
First congratulations for the plugin is very useful.
I'm having trouble with the mapping for some text items and does not receive the correct current value.
I tried to grafana 2.0 and 2.1 and versions 2.0.0 and 2.0.1 plugin
Since already grateful for your attention
![grafana](https://cloud.githubusercontent.com/assets/13698738/9143942/d8ec0254-3d1f-11e5-8e40-0c9a9c0c73c8.jpg)
![last value zabbix](https://cloud.githubusercontent.com/assets/13698738/9143943/d8ee5680-3d1f-11e5-84a7-6318ea2ab5e1.jpg)

**Comment by alexanderzobnin** [comment]
Hello! Check Max data points parameter. By default It sets to 100 in Singlestat panel (it's Grafana-specified behavior). And if you sets time period which returns more than 100 points downsampling will be used. Try to increase this parameter.

**Comment by yuriandradd** [comment]
Did not work. I decreases the range time to match the recent zabbix data but also there was no change.

![adjust](https://cloud.githubusercontent.com/assets/13698738/9144495/c1b0e6b4-3d23-11e5-9849-cf3c78d29b6a.jpg)
![time range](https://cloud.githubusercontent.com/assets/13698738/9144494/c1ae5714-3d23-11e5-9ea3-748811c9443a.jpg)

**Comment by alexanderzobnin** [comment]
Which value you expect? Is it integer or float?

**Comment by yuriandradd** [comment]
float (1.98), as in the second image of the first comment

**Comment by alexanderzobnin** [comment]
Try to sets Decimals parameter from `auto` to 2.

**Comment by yuriandradd** [comment]
It works! However the mapping to text does not work with thresholds, right? But it's good. As a suggestion for the future the mapping could encompass such case or perhaps in some cases work as coloring. Thank you my friend, your plugin is the best!

**Comment by alexanderzobnin** [comment]
Text mapping and coloring is Grafana features, not my plugin. I think thresholds must works with text mapping. Try to look at Grafana documentation. Thanks for feedback!
