### ISSUE TITLE
 setAlias to get only hostname without item name

### ISSUE THREAD

**Issue by thanhtuan** [alexanderzobnin/grafana-zabbix#630]
Hello all, Please help me
i wanted was setAlias to get only hostname without item name

![image](https://user-images.githubusercontent.com/43368493/47004059-eb50c100-d15a-11e8-8ce5-f77eca39b32c.png)

**Comment by jedd** [comment]
Do you mean replaceAlias() ?

You're showing IP addresses rather than hostnames, so you'll need to resolve that separately, but you can try:

replaceAlias(/(.*): SQLServer:General Statistics: User Connections/, $1)

**Comment by thanhtuan** [comment]
I'm used IP addresses for Hostname 
I dont see replaceAlias on my grafana. I use data source zabbix

![untitled](https://user-images.githubusercontent.com/43368493/47005842-d5dd9600-d15e-11e8-9f05-7c54ec750942.png)
My english so bad. sorry

**Comment by thanhtuan** [comment]
> Do you mean replaceAlias() ?
> 
> You're showing IP addresses rather than hostnames, so you'll need to resolve that separately, but you can try:
> 
> replaceAlias(/(.*): SQLServer:General Statistics: User Connections/, $1)

I'm used IP addresses for Hostname 
I dont see replaceAlias on my grafana. I use data source zabbix

![untitled](https://user-images.githubusercontent.com/43368493/47005842-d5dd9600-d15e-11e8-9f05-7c54ec750942.png)
My english so bad. sorry

**Comment by jedd** [comment]
Your english is just fine.  : )

Under Alias you're missing a couple of items.  This is what I see:

![image](https://user-images.githubusercontent.com/114736/47009700-e145b700-d188-11e8-9fbb-59fdc9db15f6.png)

What versions of Grafana, and the Zabbix-Grafana plugin, are you using?

**Comment by jedd** [comment]
Can you upgrade to a later version - say 3.9.1 - of the zabbix-grafana plugin?

**Comment by thanhtuan** [comment]
> Can you upgrade to a later version - say 3.9.1 - of the zabbix-grafana plugin?

Yes. Thanks bro so much :)
