### ISSUE TITLE
Map singlestat color to most the severe trigger 

### ISSUE THREAD

**Issue by becker** [alexanderzobnin/grafana-zabbix#631]
### I'm submitting a ...
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request

Hi!

Is possible to map singlestat colors to the most severe trigger in a group?

Example: I have a singlestat panel with the query mode set to "Triggers", then getting all the hosts of a group. If the most severe trigger in this group is "Warning", so the panel should be yellow. If is "Average", then orange, and so on.

Thanks!

**Comment by alexanderzobnin** [comment]
Since Triggers query returns only a number of triggers, it's not possible to determine severity for singlestat (it maps visible value to color).
