### ISSUE TITLE
zabbix grafana, plugin 4.0

### ISSUE THREAD

**Issue by glardz** [alexanderzobnin/grafana-zabbix#635]
i updated with command grafana-cli plugins update grafana-zabbix-c73078d1fbc524aa2773560e42b9e73d9302b3a7 and this command grafana-cli plugins install alexanderzobnin-zabbix-app after i restart but i see this

![image](https://user-images.githubusercontent.com/20502721/47556382-7aee3080-d90e-11e8-9459-af964d92fa90.png)

and not your window with zabbix version 

![image](https://user-images.githubusercontent.com/20502721/47556450-9bb68600-d90e-11e8-9d01-6801e93da43f.png)

_Originally posted by @glardz in https://github.com/alexanderzobnin/grafana-zabbix/issues/629#issuecomment-433339666_

**Comment by alexanderzobnin** [comment]
Now plugin repo does not contain built plugin, so after installation from sources you should build it as described in docs.

**Comment by glardz** [comment]
i have this message when i put yarn build

![image](https://user-images.githubusercontent.com/20502721/47790404-5c75a400-dd17-11e8-8e2a-477eeddb543b.png)
 after i run this command grafana-cli plugins update grafana-zabbix-c73078d1fbc524aa2773560e42b9e73d9302b3a7
![image](https://user-images.githubusercontent.com/20502721/47790660-09e8b780-dd18-11e8-8b3e-a2bc06feeab1.png)

but i don't have zabbix version

![image](https://user-images.githubusercontent.com/20502721/47790719-2f75c100-dd18-11e8-8af3-35dfae27731f.png)

**Comment by glardz** [comment]
and direct DB connection don't work

![image](https://user-images.githubusercontent.com/20502721/47796896-8a61e500-dd25-11e8-967f-66c1c82da4a7.png)

**Comment by alexanderzobnin** [comment]
@glardz just try to read the docs first.
