### ISSUE TITLE
Singlestat panel and current value return avg

### ISSUE THREAD

**Issue by angeldestroyer** [alexanderzobnin/grafana-zabbix#636]
**Describe the bug**
Singlestat panel and "Stat: Current" return avg, when a large number of values/large time interval are requested.

**Expected behavior**
The current value does not depend on the time scale. Must be the **current** value.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.2.4 | 3.4.4  | 3.9.1                 |

**Screenshots**
Value changed from "1" to "2". If time interval is more than three hours (in my case, one check per minute in zabbix) = wrong value, avg. But must be the last value = "2"

![1](https://user-images.githubusercontent.com/9303266/47702085-4becfd00-dc35-11e8-939a-65bf7ca926c3.png)
![2](https://user-images.githubusercontent.com/9303266/47702091-4ee7ed80-dc35-11e8-9945-107b92ce1a6e.png)
![3](https://user-images.githubusercontent.com/9303266/47702093-50b1b100-dc35-11e8-9cce-df75bb4544ae.png)

I checked it on "Grafana TestData - datasource" with the following string "1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,1,1,1,2" and the problem did not repeat.

![4](https://user-images.githubusercontent.com/9303266/47702359-1e548380-dc36-11e8-96c7-391fe8f65fe2.PNG)

Singlestat Oprions:
![5](https://user-images.githubusercontent.com/9303266/47702387-2ca29f80-dc36-11e8-81fa-0e19bb149aba.png)

**Comment by alexanderzobnin** [comment]
Does problem happen for the short time intervals, like 5 min? Does it happen if you set maxDataPoints to value more than number of received points, like `10000`?

**Comment by Roman1us** [comment]
+1. Appears in more than 4 days interval for me. Max data points not change values. Also in query inspector aggregation function is AVG
`SELECT CAST(itemid AS CHAR) AS metric, clock DIV 30 * 30 AS time_sec, AVG(value_avg) AS value FROM trends WHERE itemid IN (32110, 32111, 32112, 32113) AND clock > 1547456049 AND clock < 1547801649 GROUP BY clock DIV 30 * 30, metric ORDER BY time_sec ASC`

**Comment by alexanderzobnin** [comment]
@Roman1us problem is caused by aggregation in the query. If you want to get the latest point you could use panel's Relative time set to short interval, like 10 min or 1 hour.

**Comment by StaelensJarne** [comment]
I have the same issue.
If I set the Relative time it doesn't change anything, I still get more than the current value.
But from where does the query get the time settings? If I look to the Query Inspector the values `time_from` and `time_till` does not represent the 1 minutes in Relative time settings.
![Relative Time](https://user-images.githubusercontent.com/26405591/82895167-11079400-9f54-11ea-81da-299f4602ce0a.png)
![Query Inspector](https://user-images.githubusercontent.com/26405591/82895180-15cc4800-9f54-11ea-97fa-290379b2689a.png)
