### ISSUE TITLE
grafana does not show data zabbix

### ISSUE THREAD

**Issue by chronno4** [alexanderzobnin/grafana-zabbix#642]
grafana does not show data zabbix

Where do I find information in the log?

My zabbix 4.0.1
zabbix api 3.9.1
![grafana1](https://user-images.githubusercontent.com/42448381/47791171-d26a1300-dcf7-11e8-8caf-c31c04b23457.png)
![grafana2](https://user-images.githubusercontent.com/42448381/47791172-d302a980-dcf7-11e8-88e4-0f9c59532942.png)
![grafana3](https://user-images.githubusercontent.com/42448381/47791173-d302a980-dcf7-11e8-8d90-7a16be71bb3d.png)
![grafana4](https://user-images.githubusercontent.com/42448381/47791174-d302a980-dcf7-11e8-9d35-8ca3f80ec1c5.png)
![grafana5](https://user-images.githubusercontent.com/42448381/47791175-d302a980-dcf7-11e8-8ea8-75b139e30be5.png)

**Comment by alexanderzobnin** [comment]
Try to search through the closed issues - there're dozens of reports with the same problem.
