### ISSUE TITLE
zabbix graffana database with mariadb

### ISSUE THREAD

**Issue by glardz** [alexanderzobnin/grafana-zabbix#643]
**Describe the bug**
i want to connect zabbix databaze with graffana, i configurated Data Sources  but i have this 

**Screenshots**
![image](https://user-images.githubusercontent.com/20502721/47801994-a66a8400-dd2f-11e8-9de8-d28032bd5e3f.png)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.2.4   | 4.0  | 3.9.7                |

**Comment by alexanderzobnin** [comment]
It's not a bug - you should configure access to zabbix database from host where grafana running. It's described in docs, actually
https://alexanderzobnin.github.io/grafana-zabbix/configuration/sql_datasource/
