### ISSUE TITLE
zabbix graffana database with mariadb 

### ISSUE THREAD

**Issue by glardz** [alexanderzobnin/grafana-zabbix#644]
Describe the bug
i  connected zabbix databaze with graffana, i configurated Data Sources but i have this message when i share dashboard

![image](https://user-images.githubusercontent.com/20502721/47902001-95318c80-de81-11e8-9a4a-5f74a74c9aac.png)

![image](https://user-images.githubusercontent.com/20502721/47901975-88149d80-de81-11e8-9fad-9c008671a31f.png)

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
5.2.4 | 4.0 | 3.9.7

**Comment by alexanderzobnin** [comment]
`Unauthorized` error probably related to https://github.com/grafana/grafana/issues/11006
At the second screen you should set proper datasource for the panel.
