### ISSUE TITLE
update grafana plugin with yarn

### ISSUE THREAD

**Issue by glardz** [alexanderzobnin/grafana-zabbix#645]
hello,

i use your latest plugin of grafana zabbix, i have some difficult to update.

i put the new plugin version on  /var/lib/grafana/plugins/ and i run yarn build ihave this message

![image](https://user-images.githubusercontent.com/20502721/47905281-058edc80-de87-11e8-9a11-3ceda52c8627.png)

after i run this command grafana-cli plugins update grafana-zabbix-c73078d1fbc524aa2773560e42b9e73d9302b3a7

![image](https://user-images.githubusercontent.com/20502721/47906093-ccf00280-de88-11e8-83d9-dda532e6a597.png)

i restart but i see this

![image](https://user-images.githubusercontent.com/20502721/47906145-eabd6780-de88-11e8-8392-e51c4315e687.png)

and not your window with zabbix version

![image](https://user-images.githubusercontent.com/20502721/47906167-f315a280-de88-11e8-876c-108bd26b2661.png)

can you give me a tutorial for update step by step please.

**Comment by alexanderzobnin** [comment]
@glardz Why do you create duplicated issues? If you can't build it, just wait for the release.
