### ISSUE TITLE
Allow disabling/customizing of side menu Zabbix button

### ISSUE THREAD

**Issue by howsTricks** [alexanderzobnin/grafana-zabbix#647]
Not sure if a feature or an issue, but when I have this plugin enabled it adds a Zabbix button to the side menu with a link to one dashboard called "Zabbix Server Dashboard". Is there a way to disable this button? It seems like alot of UI tied to one dashboard link. Or if no way to disable, a way to add other dashboards to this menu button?

**Comment by alexanderzobnin** [comment]
Now it's disabled.

**Comment by howsTricks** [comment]
Thanks!

**Comment by i3laze** [comment]
Actually, I like this particular button to be customized with some dashboards containing a particular Tag.
I got lot's of dashboards in Grafana, only few of them are Zabbix-related and they are in separate folder.

It would be nice for all of them to be under this Z button.

**Comment by alexanderzobnin** [comment]
@i3laze it's only possible to place pre-defined dashboards under the plugin side menu. You can't move dashboard you created to the menu.

**Comment by i3laze** [comment]
Pity,

Where can I:
1. Disable this red button from appearing (as it is currently useless).
or
2. Populate pre-defined dashboards in the plug-ins folders/code?
