### ISSUE TITLE
Ability to hide trigger description in Trigger panel

### ISSUE THREAD

**Issue by rrz** [alexanderzobnin/grafana-zabbix#648]
There can be a long trigger description in Zabbix, so when trigger shows up in Trigger Panel it takes a lot of space and it can't be hidden just with button.
![trigger_panel](https://user-images.githubusercontent.com/424308/48408894-4545a600-e75c-11e8-9663-7b267b53e4f5.PNG)

**Comment by alexanderzobnin** [comment]
Fixed in updated Problems panel.
