### ISSUE TITLE
Metric names are not loaded when using dev version of plugin from master.

### ISSUE THREAD

**Issue by iprok** [alexanderzobnin/grafana-zabbix#649]
**Describe the bug**
Metric names are not loaded when using dev version of plugin from master. See screenshot.

**Expected behavior**
Metrics should be displayed normally.

**Screenshots**
![clipboard - 15 2018 13-49](https://user-images.githubusercontent.com/9906715/48549812-e6aa3480-e8e1-11e8-93ef-65f0ed3ce1cf.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|5.3.4   | 4.0.1  | dev from master cloned at 13.11.2018      |

**Comment by alexanderzobnin** [comment]
@iprok have you built a plugin? https://alexanderzobnin.github.io/grafana-zabbix/installation/run_from_master/

**Comment by iprok** [comment]
> @iprok have you built a plugin? https://alexanderzobnin.github.io/grafana-zabbix/installation/run_from_master/

Yes, of course. Old graphics work normal

**Comment by iprok** [comment]
Excuse me. Tried to recompile and it starts to work.
