### ISSUE TITLE
Can't find host, no data

### ISSUE THREAD

**Issue by Phlogi** [alexanderzobnin/grafana-zabbix#65]
Installed the plugin from master branch and connected to zabbix 2.4.5. The connection test in grafana shows success, however when creating a dashboard my hosts don't show up in the selection. So it seems that there is no data. The log file of grafana doesn't show any error. 

```

2015/08/09 17:00:36 [I] Starting Grafana
2015/08/09 17:00:36 [I] Version: 2.1.0, Commit: v2.1.0, Build date: 2015-08-04 16:19:48 +0200 CEST
2015/08/09 17:00:36 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/08/09 17:00:36 [I] Database: sqlite3, ConnectionString: file:/var/lib/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/08/09 17:00:36 [I] Migrator: Starting DB migration
2015/08/09 17:00:36 [I] Listen: http://0.0.0.0:3000
2015/08/09 17:11:56 [I] Completed /logout 302 Found in 416.132µs
2015/08/09 17:11:59 [I] Completed /dashboard/db/new-dashboard 302 Found in 235.304µs

```

**Comment by nucleusv** [comment]
Hi!
Is group All selected?
Have the api user rights to see hosts what you are looking for?
Don't look at grafana server logs, you need to look in developer tools in your browser...

**Comment by Phlogi** [comment]
Thanks, the reason was the zabbix user had nothing configured. I used another new user (on purpose) :)

Thanks!
