### ISSUE TITLE
Zabbix Triggers top 100

### ISSUE THREAD

**Issue by sigurdurfbjarnason** [alexanderzobnin/grafana-zabbix#650]
Hi!

Is it possible today to list up the top triggers for Severity like in the "Triggers top 100" in Zabbix reports? If not,  is it possible anyhow to do so in the Current Grafana-Zabbix with some tricks?

It would be nice to be able for example to count host restarts over time period etc

-Siggi

**Comment by alexanderzobnin** [comment]
It's not possible now.
