### ISSUE TITLE
trendValue(*) function is ignored when using Zabbix Datasource with Direct DB Connection

### ISSUE THREAD

**Issue by neothematrix** [alexanderzobnin/grafana-zabbix#654]
Hello,
I'm using Grafana 5.3.4 and your grafana-zabbix plugin version 3.9.1.
I configured a Zabbix Datasource pointing it to my Zabbix 3.4.13 server and also enabling the Direct DB connection to the PostgreSQL Zabbix database for faster queries.
Everything works properly, except that when I create a metric and specify the function "trendValue(max)", the query inspector shows that the trend value gathered from the database is always "avg" no matter what I select as function parameter:

`
url:"api/tsdb/query"
data:Object
queries:Array[1]
0:Object
refId:"A"
format:"time_series"
datasourceId:10
rawSql:" SELECT to_char(itemid, 'FM99999999999999999999') AS metric, clock / 600 * 600 AS time, AVG(value_avg) AS value FROM trends_uint WHERE itemid IN (874460, 874458, 874459, 874457) AND clock > 1536603160 AND clock < 1537261678 GROUP BY 1, 2 ORDER BY time ASC "
maxDataPoints:10000
`

If I disable the Direct DB Connection, then the query properly returns the trend value I specify in the trendValue function parameter, of course this time using Zabbix API instead of database query.

Let me know if I need to provide you any additional information.

thanks!

**Comment by alexanderzobnin** [comment]
With Direct DB Connection sql datasource returns ready-to-use series. So in order to select trend value you should use `consolidateBy(max)` function.

**Comment by neothematrix** [comment]
hello @alexanderzobnin ,
thanks a lot for your reply, it's kind of hidden, but it works perfectly, the used column is now value_max.

thanks again!

**Comment by alexanderzobnin** [comment]
That's described in [direct-db-connection](https://alexanderzobnin.github.io/grafana-zabbix/reference/direct-db-connection/#functions-usage-with-direct-db-connection) docs, but maybe I should add it to `trendValue()` function docs as well.
