### ISSUE TITLE
Empty Dashboard in Grafana 5.4.0

### ISSUE THREAD

**Issue by iliesh** [alexanderzobnin/grafana-zabbix#655]
Hi,

I'm not receiving any data in the default dashboard "Zabbix Server Dashboard". 
I checked the Group/Host - is the same as in Zabbix (Zabbix server).  By pressing on the Query Inspector - I cannot see the query - just loading. Is this plugin compatible with Grafana 5.4 and Zabbix 4.0?

Grafana Plugin: 3.9.1
Grafana Version: 5.4.0
Zabbix Server: 4.0 LTS

Thank You.

**Comment by myusufe** [comment]
the same issue also

**Comment by myusufe** [comment]
Sorry, it was PC time drift problem. After fixed the time on pc and server, everything is good now.

**Comment by iliesh** [comment]
Sorry, the problem was in wrong user rights.
