### ISSUE TITLE
zabbix system status template does not show anything higher then warnings

### ISSUE THREAD

**Issue by bhakimi** [alexanderzobnin/grafana-zabbix#657]
the system status table does not display any higher alerts other than warnings.

**Expected behavior**
the column Disaster, high and average is there but the count on them is 0 and i currently have a average alert.

**Screenshots**

**Network data**
i checked the query result and it does not return any average alerts in the json object, not sure why zabbix is not returning any average or higher alerts.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 5.X         | 3.2.3    | 3.9.1 |

**Comment by bhakimi** [comment]
looks like this was due to the time selection, is there a way to show all current active triggers even if they are in the past but still active? i like to display data like the last X issues zabbix displays on its default dashboard

**Comment by alexanderzobnin** [comment]
See https://github.com/alexanderzobnin/grafana-zabbix/issues/659#issuecomment-465467103
