### ISSUE TITLE
How to get the lastest data?

### ISSUE THREAD

**Issue by veezhang** [alexanderzobnin/grafana-zabbix#658]
Is there a way to get the lastest data?
In some cases, I do not care about the history data, and I just wanna to get the  lastest data.

**Comment by alexanderzobnin** [comment]
For the singlestat panel you can use last value and set panel time range to short interval (5 min, for instance) in order to reduce history data pulled from server.

**Comment by ceinmart** [comment]
@alexanderzobnin , 

Is there a way to do that using the Table Panel ? 
What I need is show the last data for multiple items (in columns)  grouped by the alias set (in row). 
Something like the "overview" page in the zabbix (with host location = left)  . 
But I need to do that over the items . 
I'm able to set the alias using the the function ReplaceAlias() , but there is no function to get the last data only , with or without the timestamp.
(the option without timestamp could be useful for panels who do not work with timeseries , like the multistat panel)

The final result should be something very like the group servers trigger panel in the Zabbix dashboard template, but considering the columns as separated items.

**Comment by alexanderzobnin** [comment]
@ceinmart for the table you can use Table transform - Time series aggregation and Columns - current:

![Screenshot from 2019-07-02 10-13-04](https://user-images.githubusercontent.com/4932851/60491744-23307200-9cb2-11e9-933e-d181f25011ea.png)

**Comment by saramoz** [comment]
Is there a way to do that using the map? Time range set to 2 min, but updating on server set to 1 min.
