### ISSUE TITLE
'System status' table shows "No data"

### ISSUE THREAD

**Issue by Nita100** [alexanderzobnin/grafana-zabbix#659]
Hi everyone.

**Is your feature request related to a problem? Please describe.**
I have a warning that triggered 7 days ago and it is shown in the "Zabbix Triggers" panel.
Unfortunately, I cannot see that trigger in the "System status" table, as it shows no data at all if the time range is not properly set.
In fact, the query only returns data if the triggers have been generated in the time range set.
As you can see from the first screenshot, if the time range is set on "today", the panel doesn't show the table.
If I change the range and set "Last 30 days", the table appears with my warning, as you can see from the 2nd screenshot.

**Describe the solution you'd like**
I would love to be able to see the triggers that are actually active in the time range that I set, even though they have been generated before, as I draw in the 3rd image.

**Describe alternatives you've considered**
If that could not be possible, it would be nice to have at least the table with null values, as I draw in the 4th image.

**Additional context**
![zabbix-grafana-status](https://user-images.githubusercontent.com/44372919/50643732-2bac2800-0f6f-11e9-81a0-31dbfcf17bf2.png)

Thank you so much in advance for paying attention, 
Nita

**Comment by alexanderzobnin** [comment]
It's not a bug, problems are filtered by time range. You can set panel time range (Panel -> Time range -> Override relative time) to the desired interval (30d, 1y, etc).
