### ISSUE TITLE
Issues with Grafana 2.1.1

### ISSUE THREAD

**Issue by jbfavre** [alexanderzobnin/grafana-zabbix#66]
Hello,
I've upgraded Grafana in version 2.1.1.
I want to use [Repeating Rows and Panels](http://docs.grafana.org/guides/whats-new-in-v2-1/#repeating-rows-and-panels) feature, amongst others.

But I got some issues (data points not found, panel size, etc...) and wonder if it can come from grafana-zabbix.
Is grafana-zabbix 100% compatbile with grafana 2.1.1 ?
If not, I'm sorry for the noise and will open an issue against grafana.

Thanks,

**Comment by alexanderzobnin** [comment]
Hello. Yes, Grafana-Zabbix 2.0.1 is compatible with Grafana 2.1. I am use Grafana-Zabbix from develop branch with Grafana 2.1.0 at http://play.grafana-zabbix.org. You can check your bugs here.

**Comment by alexanderzobnin** [comment]
Can you give more details about these bugs?

**Comment by jbfavre** [comment]
hmmm... I think I start to understand what happen.
My dashboard is templated with 3 variables:
$group which is static
$POP which extract part of server FQDN. Multi format set to glob
$scenario which is part of items. Multi format set to glob

I then created a graph with a filter in host (dashboard variable called $POP) and another filter on item (dashboard variable called $scenario).
Graph use Repeat Panel based on $scenario.
Row use Repeat Row based on $POP

When I have only one $POP or $scenario selected, that's OK. As soon as I select 2 of each (either $POP or $scenario), I loose data.

I just changed Multi format from "glob" to "regexp value". now it have all my data.
But all data from all POP are on the same graph :(

Comments welcome

**Comment by jbfavre** [comment]
For the "panel size" issue, even if I force panel size with `span 4`, it somewhat looses this value.
So when panel get repeated, new panels get default size which is 12 :-/

**Comment by alexanderzobnin** [comment]
About panel size - it seems like a Grafana bug.

**Comment by alexanderzobnin** [comment]
Templated variables in hosts and item filters works very simply:
```
// Use templated variables in filter
var host_pattern = new RegExp(templateSrv.replace(target.hostFilter));
```
If you use multiple values, templated variable will be transform to something like this:

*glob*
```
{Discovered hosts,Hypervisors,Linux servers,Templates,Virtual machines,Zabbix servers}
```

*regexp value*
```
(Discovered\ hosts|Hypervisors|Linux\ servers|Templates|Virtual\ machines|Zabbix\ servers)
```
These values will be used like regex for filtering hosts and items. For this reason you get all hosts and items in each panel.

**Comment by jbfavre** [comment]
Yes I understood that after a while.
But the example from http://docs.grafana.org/guides/whats-new-in-v2-1/#repeating-rows-and-panels looks pretty close to my $POP filter.

Is there any way to get a sort of list with only one value per panel/row ?

**Comment by alexanderzobnin** [comment]
May be you need to use Repeat Panel based on $POP variable?

**Comment by alexanderzobnin** [comment]
I haven' tried this functional. I need more experience with it.

**Comment by jbfavre** [comment]
I already tried to switch between $scenario & $POP. But I still get all data on the same graph or no data at all.

By the way, I figure out that using $POP in row title just show one item from the glob. Same goes for Graph title, so, I guess filters do not handle them nicealy :-/

**Comment by jbfavre** [comment]
@alexanderzobnin looks like also occured with InfluxDB datasource: https://github.com/grafana/grafana/issues/1888#issuecomment-114087222

Trying to understand what it does and fix it into zabbix datasource, but not sure I'll get any result :-/

**Comment by jbfavre** [comment]
@alexanderzobnin I think I found something.
I made a PR #67 which seems to solve the problem for me
