### ISSUE TITLE
t.replace is not a function

### ISSUE THREAD

**Issue by janeunbi** [alexanderzobnin/grafana-zabbix#661]
I used well zabbix in Grafana, I needed to add some more graphs.
I tried to add a Zabbix datasource but it didn't work
Another datasources still work, also if I add the same zabbix datasource in the other Grafana server that works well as a datasource.
What's the problem?

I tried but t.replace is not a function came out
![ss](https://user-images.githubusercontent.com/46011780/50801209-0b8db780-1327-11e9-9b1c-6fb92374db92.PNG)

I tried it as a $datasource but same errors came out
![datasource](https://user-images.githubusercontent.com/46011780/50801212-0d577b00-1327-11e9-8221-7aef8addaa12.PNG)

Error messages
![error](https://user-images.githubusercontent.com/46011780/50801215-0f213e80-1327-11e9-8da9-6f7b621badfa.PNG)

**Software versions**
Zabbix 4.0 
Grafana 5.4.0
plugin 3.9.1

I'll wait for your help.

**Comment by hlyazid** [comment]
Hello,

I have the same problem, all my existing dashboard function correctly, but I can't create neam items.

Regards

**Comment by Stack0verflow** [comment]
I had this issue as well when I went to convert a pre-existing panel from using a MySQL datasource to using a Zabbix API datasource. I was able to delete the panel and create a new one using a Zabbix API datasource from the start and it seemed to work fine.

**Comment by mammuthus** [comment]
**The same issue!**

Moved from: https://github.com/grafana/grafana/issues/15319

### What Grafana version are you using?
It was Grafana v5.4.2 (commit: [d812109](https://github.com/grafana/grafana/commit/d812109ebf3b904c9fcd8bc17f6d9b246232743b)) but updating to Grafana v5.4.3 (commit: [6539180](https://github.com/grafana/grafana/commit/653918056c594d7f56a65771b2c9681bdf8a3b9a)) didn't fix the issue

### What datasource are you using?
Zabbix api (Zabbix plugin by Alexander Zobnin, Version 3.9.1) @alexanderzobnin

### What OS are you running grafana on?
CentOS Linux release 7.6.1810 (Core)
Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
I try to create new dashboard with widget or add new widget (Table for example) in existing board.

### What was the expected result?
Creating new board and adding new widget

### What happened instead?
I get an arror after choosing "zabbix api" in Data Source section: **t.replace is not a function**

Pic 1: normal situation with "Grafana" datasource:
![image](https://user-images.githubusercontent.com/1700286/52476734-a1c82e00-2bb0-11e9-9f56-3da3fddeb50a.png)

Pic 2: error after switching to "zabbix api" source
![image](https://user-images.githubusercontent.com/1700286/52476763-c15f5680-2bb0-11e9-9c27-d5320d120275.png)

Pic 3: try to create Graph widget and getting the same error. Adding more queries after that:
I can create B and C etc queries, but A is broken
Hide and Remove buttons dont' work with A query
![image](https://user-images.githubusercontent.com/1700286/52477292-6af31780-2bb2-11e9-8f43-aec8e279a29b.png)

Pic 4: Open already existing widget with zabbix source, made ~3 mouths ago, all is OK:
New queries creates OK too
![image](https://user-images.githubusercontent.com/1700286/52477701-ec977500-2bb3-11e9-8ae0-3761bd9657a1.png)

Pic 5: Zabbix datasource config:
![image](https://user-images.githubusercontent.com/1700286/52477423-e05ee800-2bb2-11e9-90a2-a70e099f5d8a.png)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
![image](https://user-images.githubusercontent.com/1700286/52477114-da1c3c00-2bb1-11e9-8ba6-326f24578b7f.png)

**Comment by mammuthus** [comment]
As a temporary measure you can goto JSON model, find "group" value of broken widget 
and change `[]` to `{}`

![image](https://user-images.githubusercontent.com/1700286/52638235-96437280-2ee2-11e9-8678-abc29e76da36.png)


![image](https://user-images.githubusercontent.com/1700286/52638256-a0657100-2ee2-11e9-830e-aa72a5d81c19.png)

**Comment by alexanderzobnin** [comment]
Yes, looks like a bug, maybe related to default metric template change in grafana.

**Comment by alexanderzobnin** [comment]
@mammuthus thanks for the detailed report! Unfortunately, I can't replicate this issue doing the same steps. If I change `target.group` to `[]` in panel, I get the same error. But I can't understand why group changes. Could you provide some additional info? For instance, add new panel, get error and paste panel json here.

**Comment by alexanderzobnin** [comment]
Got it. It seems it caused by MySQL and Postgres datasource editor. It sets default `target.group` to `[]`:
https://github.com/grafana/grafana/blob/f348acccf3c178c16cf36cbb30224d6bd7731ba9/public/app/plugins/datasource/mysql/mysql_query.ts#L18
https://github.com/grafana/grafana/blob/f348acccf3c178c16cf36cbb30224d6bd7731ba9/public/app/plugins/datasource/postgres/postgres_query.ts#L18
So I have to take it into account and do some extra check for this field. Until it fixed workaround from @mammuthus (change `[]` to `{}` in panel json) should work.

**Comment by alexanderzobnin** [comment]
Guess, this appears if you have MySQL or Postgres datasource set as default. Can you confirm this?
@hlyazid @janeunbi @Stack0verflow @mammuthus

**Comment by mammuthus** [comment]
Yes, it is
![image](https://user-images.githubusercontent.com/1700286/52689836-a6a02f80-2f6c-11e9-9588-de6356dd7f72.png)

After unchecking it works normally

![image](https://user-images.githubusercontent.com/1700286/52689940-07c80300-2f6d-11e9-95b9-d6e1a6ac46a4.png)

![image](https://user-images.githubusercontent.com/1700286/52689944-0d254d80-2f6d-11e9-9e13-2312fcc7ddb3.png)

JSON is fine too

**Comment by alexanderzobnin** [comment]
Ok, seems, it's a reason.
