### ISSUE TITLE
Can't bring a New Zabbix item in Grafana

### ISSUE THREAD

**Issue by janeunbi** [alexanderzobnin/grafana-zabbix#662]
I made a new item to identify specific one, in zabbix, I can see its value on Zabbix.
However, I can't see the new item, Grafana doesn't bring the new item.
What should I do?
*New item = top process

Here's the new item belonged in Linux Server host group as a Zabbix agent 
![3](https://user-images.githubusercontent.com/46011780/50802422-f0707700-1329-11e9-955e-0e0f5fc2626b.PNG)

I can see its value on Zabbix.
![data](https://user-images.githubusercontent.com/46011780/50802440-f23a3a80-1329-11e9-81d1-6905d9a1205d.PNG)

Grafana doesn't show its whole category.
![x](https://user-images.githubusercontent.com/46011780/50802455-f403fe00-1329-11e9-83df-c2ef16584360.png)

I'll wait for your help.

**Comment by pronichev** [comment]
@janeunbi change "Metric" to "Text" in "Query Mode"
