### ISSUE TITLE
error "Table 'zabbix.trends_uint' doesn't exist" when checking “Direct DB Connection” in grafana

### ISSUE THREAD

**Issue by ilikemiao** [alexanderzobnin/grafana-zabbix#664]
**Describe the bug**
 Configure data sources in grafana. If "Direct DB Connection" unchecked, it works. But If "Direct DB 
 Connection" checked, prompt error. please help, thanks very mush.

error:
Connection failed: Error 1146: Table 'zabbix.trends_uint' doesn't exist

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v5.3.2 | 3.4.3  | 3.9.1              |

**Comment by alexanderzobnin** [comment]
Looks like your SQL data source configured wrong.
