### ISSUE TITLE
Problems with getting data from zabbix api

### ISSUE THREAD

**Issue by denisgolius** [alexanderzobnin/grafana-zabbix#665]
I have 2 different installation of zabbix server 4.0.3 (nginx + php-fpm 7.3 + postgresql)

My grafana server run under NAT and VM thrue linux router.  Grafana is a VM in Hetzner bare metall hypervizor server. 1st zabbix server is in Ukraine -   so it's getting data from 1st zabbix over Internet.

2nd zabbix server is on the same hypervizor as Grafana and in the same network. This internal network don't have any firewall restrictions.

NVPS from 1st server is little bit bigger that 2nd zabbix server, but for 1st server Grafana show graphs well, but for 2nd server - don't. Also for 2nd server PostgreSQL database is also connected as data source...

Here is screenshots:
![screenshot 5](https://user-images.githubusercontent.com/5650611/51031294-c5458c00-15a4-11e9-9fe5-959d90f0c6b0.png)
![screenshot 4](https://user-images.githubusercontent.com/5650611/51031295-c5458c00-15a4-11e9-9ab8-49206f58f28e.png)
![screenshot 3](https://user-images.githubusercontent.com/5650611/51031296-c5de2280-15a4-11e9-8db8-9ffe0b8e2388.png)
![screenshot 2](https://user-images.githubusercontent.com/5650611/51031559-9da2f380-15a5-11e9-8ed0-bff009686b33.png)
![screenshot 1](https://user-images.githubusercontent.com/5650611/51031299-c5de2280-15a4-11e9-8b0c-764f8c113645.png)

What I am doing wrong?

**Comment by alexanderzobnin** [comment]
Can you get any other metric for the first server? Ensure permissions for API user are OK.

**Comment by denisgolius** [comment]
Tge problem solved itself...
