### ISSUE TITLE
zabbix trigger table not showing real data

### ISSUE THREAD

**Issue by iftitutul** [alexanderzobnin/grafana-zabbix#666]
**Describe the bug**
zabbix trigger table not showing the real value. I am using Zabbix 3.4.12 and grafana with latest version.

**Expected behavior**
it shows some value but if I compare to the zabbix then value is not correct

**Screenshots**
Last two days graphs which not matches with zabbix side
![image](https://user-images.githubusercontent.com/19967813/51586943-53a50080-1f09-11e9-82c0-a5fc093c323b.png)
![image](https://user-images.githubusercontent.com/19967813/51586977-720afc00-1f09-11e9-8b0e-692404757472.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 5.4.13 | 3.4.12 | 3.9.1|

**Comment by alexanderzobnin** [comment]
Could you provide Zabbix screenshot? I don't see what's a problem.

**Comment by iftitutul** [comment]
Zabbix trigger table showing only current status?
Actually I am confused about this. If this table can show the all alerts so
daily/weekly/monthy/yearly basis we can show this for reports purposes.

**Comment by alexanderzobnin** [comment]
Problems in this table are filtered by dashboard time range. So different range may return a different result.
