### ISSUE TITLE
zabbix таблицы с несколькими метриками

### ISSUE THREAD

**Issue by 071vvp** [alexanderzobnin/grafana-zabbix#668]
Подскажите, можно ли в Grafana создать таблицу с несколькими метриками  (current)? Например:
Хост / свободно HDD / свободно ОЗУ / загрузка процессора. 

Если да - то как?  у меня не получается.

**Comment by alexanderzobnin** [comment]
Отфильтровать все метрики в одном запросе, например `/disk|memory|cpu/`
