### ISSUE TITLE
Sum series table

### ISSUE THREAD

**Issue by caiocgoliveira** [alexanderzobnin/grafana-zabbix#669]
Sum series table panel

I would like to kwnow, if is it possible,  sum the values metrics A and B, to show the result at the same table.

![image](https://user-images.githubusercontent.com/43866361/51983623-514e2380-2480-11e9-87f2-9d5010308597.png)

![image](https://user-images.githubusercontent.com/43866361/51983676-78a4f080-2480-11e9-8e72-b4348b466401.png)

I wouldlike sum the traffic values above, without using Zabbix items.

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|v5.1.0 | 3.4.6 | 3.9.1                 |

**Comment by arbrk** [comment]
Hello,
you could use sumSeries() http://docs.grafana-zabbix.org/reference/functions/#sumseries
You just create query with regexp in 'Item', that include yours neded items. And use sumSeries()

**Comment by alexanderzobnin** [comment]
It's not possible to sum values from two different queries. You could use `sumSeries()` as suggested above.

**Comment by caiocgoliveira** [comment]
> It's not possible to sum values from two different queries. You could use `sumSeries()` as suggested above.

Thanks alexanderzobbin, I tried this before, but didnt work.
