### ISSUE TITLE
Grafana v5.4.3 (6539180) and Zabbix 4.0.4 acknowledge not working

### ISSUE THREAD

**Issue by RedJohn14** [alexanderzobnin/grafana-zabbix#670]
Hi,
I installed newest Zabbix Version and Grafana v5.4.3 with the grafana-zabbix plugin. I test with some PROBLEMS in Zabbix. Erros are displayed correct in grafana interface.

But I can't acknowledge them in the grafana interface, nothing happend. Look at my screenshot. What is the problem?
<img width="683" alt="bildschirmfoto 2019-02-10 um 17 05 39" src="https://user-images.githubusercontent.com/47501883/52536055-2607e600-2d56-11e9-834d-fa0e983f1e95.png">

**Comment by RedJohn14** [comment]
Hi,

okay I used your document to run from master:

https://github.com/alexanderzobnin/grafana-zabbix/blob/master/docs/sources/installation/run_from_master.md

Is there no other way to install the plugin with working acknowledge? I won't installed some extra on my monitoring server. I tested your document on my test system and acknowledge is working fine.

Is there no other way to use the master plugin?

Regards

**Comment by alexanderzobnin** [comment]
I'm working on the new release, hope, it will be available soon.

**Comment by RedJohn14** [comment]
Hello,

Thanks for fast reply. Okay understand but I have short question. Is it possible to upgrade from the master branch to the next release in the future if you will release it? Because now I installed it via yarn setup. Is that a problem? Or will I have problems with the next release?

**Comment by RedJohn14** [comment]
> I'm working on the new release, hope, it will be available soon.

Hello,

Thanks for fast reply. Okay understand but I have short question. Is it possible to upgrade from the master branch to the next release in the future if you will release it? Because now I installed it via yarn setup. Is that a problem? Or will I have problems with the next release?
