### ISSUE TITLE
grafana and zabbix diasplay alias with variables

### ISSUE THREAD

**Issue by armanzhakypbayev** [alexanderzobnin/grafana-zabbix#671]
Maybe it is solved, if that can anyone help with this issue. I want to display all critical (thresholded) metrics with unique (with variable) alias. There are my dashboard and my problem. Thx!
![1](https://user-images.githubusercontent.com/43331562/52521140-c13c8500-2c9c-11e9-9a88-5a6e1afc23dc.jpg)
![2](https://user-images.githubusercontent.com/43331562/52521141-c13c8500-2c9c-11e9-8a06-2553b862d28f.jpg)
![3](https://user-images.githubusercontent.com/43331562/52521142-c1d51b80-2c9c-11e9-8990-97359dd43892.jpg)
![4](https://user-images.githubusercontent.com/43331562/52521143-c1d51b80-2c9c-11e9-9283-94ab4d1f9542.jpg)
![5](https://user-images.githubusercontent.com/43331562/52521144-c26db200-2c9c-11e9-80ad-ec24d46244a0.jpg)
![6](https://user-images.githubusercontent.com/43331562/52521145-c26db200-2c9c-11e9-8b43-96ce6f3328d3.jpg)
![7](https://user-images.githubusercontent.com/43331562/52521147-c3064880-2c9c-11e9-948e-fd3aae5351db.jpg)

**Comment by armanzhakypbayev** [comment]
Pls help with this! The result that I expect: instead of "Link down" -> display "Interface ge-0/0/0(Description): Operational status"

**Comment by alexanderzobnin** [comment]
Use `replaceAlias()` instead.
