### ISSUE TITLE
Triggers panel: support both alert list and table-like layouts

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#673]
I get a lot of questions and requests related to table-like layout for triggers panel after latest design update. So I decided to revisit a triggers panel and not just add support for old table layout, but totally update it and add new useful features. Layout similar to alert list panel still supported, so now it's possible to choose what you want. Panel was renamed to **Problems panel** as well.
The main goal of new design is to combine compact table layout with extended problem info on demand.

![screenshot from 2019-02-13 20-35-23](https://user-images.githubusercontent.com/4932851/52731561-09c2ae00-2fcf-11e9-9e23-c4ee0b485146.png)
![screenshot from 2019-02-13 20-36-12](https://user-images.githubusercontent.com/4932851/52731559-092a1780-2fcf-11e9-95e7-a83e9c1939d2.png)
![screenshot from 2019-02-13 20-35-55](https://user-images.githubusercontent.com/4932851/52731560-092a1780-2fcf-11e9-9efc-5255464b887b.png)

**Comment by heyrod** [comment]
Hi Aleksandr. Can you include in the documentation what icons in the alert panel mean? I guess they correlate with trigger properties in Zabbix but their explanation for Grafana users (not quite familiar with Zabbix) would be helpful.

**Comment by alexanderzobnin** [comment]
@heyrod Yes, sure. The docs is a part I have to sacrifice sometimes for features :cry:

**Comment by DougHD10** [comment]
Good morning, is it possible to extract the duration of events using this query mode problems?
