### ISSUE TITLE
Acknowledged color isn't working in 3.10 (list view)

### ISSUE THREAD

**Issue by jose150ml** [alexanderzobnin/grafana-zabbix#676]
Hello, I updated the zabbix plugin to version 3.10.0 and noticed that the commented items are not changing the color even with the checked option, I tested it in my environment and http://play.grafana-zabbix.org/d/000000024/triggers-problems?orgId=2, could it help with the resolution?

**Comment by alexanderzobnin** [comment]
Hm... Can't replicate this:

![screenshot from 2019-02-18 20-31-42](https://user-images.githubusercontent.com/4932851/52967793-3bb38600-33bc-11e9-97e4-512a81bb9446.png)

**Comment by jose150ml** [comment]
I apologize, the error occurs in List mode and not in the table

**Comment by alexanderzobnin** [comment]
Yes, confirmed.

**Comment by xiaoxue999** [comment]
great job!
