### ISSUE TITLE
Incorrect threshold from triggers with functions other than last()

### ISSUE THREAD

**Issue by bufo** [alexanderzobnin/grafana-zabbix#677]
Grafana creates incorrect threshold (like "T1 gt 6", which draws line at y=6) from triggers like "{stats:avg_time[10.0.0.1:8000].count(#7,300,"gt")}>6", i.e. it doesn't look at function used in trigger (count() in this example).

Grafana v5.4.3, Zabbix 4.0.2

**Comment by i-ky** [comment]
Zabbix will do the same. I'd suggest to report it at [their bug tracker](http://support.zabbix.com) and see what they say about it.

**Comment by alexanderzobnin** [comment]
Yes, it works in simple cases, but it's really tricky to parse all zabbix functions to get a proper threshold. I don't think I'm going to work on this in the future.

**Comment by bufo** [comment]
Thanks for answers.

**Comment by i-ky** [comment]
There is some information on the topic in [ZBX-15430](https://support.zabbix.com/browse/ZBX-15430), worth watching.
