### ISSUE TITLE
Triggers panel (v. 3.10.0): filter "acknowledged" doesn't work correct

### ISSUE THREAD

**Issue by duntila** [alexanderzobnin/grafana-zabbix#678]
Triggers panel shows all events when use filter "acknowledged"

**Comment by banzayats** [comment]
I have a similar behavior after update to version 3.10:

- I can see only problems. If I select Show elements "ALL" or "OK" - I do not see any data.
- It shows me unacknowledged problems when I select "acknowledged" or "all triggers"

**Comment by LeDistordu** [comment]
on my side, the unacknowledged filter does not work : "No problem found"

**Comment by jiri-bati-novak** [comment]
Same here - trigger panel does not show unacknowledged triggers - plugin version 3.10.0, Grafana 5.4.3 (Grafana-xxl docker container)
