### ISSUE TITLE
XHR error

### ISSUE THREAD

**Issue by yuynagforhacker** [alexanderzobnin/grafana-zabbix#679]
Hello, I have this problem after the plugin update with grafana-cli. The solution found in the closed issue is to update the browser cache, but it is not applicable to my environment. I have not found the js file in the issue in my environment. How can I solve this problem?
Plugin version 3.10.0
Grafana version 4.4.2
Zabbix version 3.2.9
```
Plugin Error
(SystemJS) XHR error (404 Not Found) loading https://grafana.ipaynow.cn/public/react-dom?bust=1550543181435 Error: XHR error (404 Not Found) loading https://grafana.ipaynow.cn/public/react-dom?bust=1550543181435 Error loading https://grafana.ipaynow.cn/public/react-dom as "react-dom" from https://grafana.ipaynow.cn/public/plugins/alexanderzobnin-zabbix-app/panel-triggers/module.js
```
Thanks all.

**Comment by alexanderzobnin** [comment]
I think it's due to outdated grafana version. It should be 5.x, so try to upgrade it. Sorry, I think there's a kind of compatibility table should be available in docs.
