### ISSUE TITLE
Triggers panel (v. 3.10.0): Highlight background is not working correctly for Resolved events in List view

### ISSUE THREAD

**Issue by pronichev** [alexanderzobnin/grafana-zabbix#681]
**Describe the bug**
"Highlight background" feature is not working correctly for Resolved events in List view. In previous version (3.9.1) the color of resolved events was Green.

**Expected behavior**
The color of resolved events in list view must have a color for OK events.

**Screenshots**
![screen shot 2019-02-20 at 12 19 34](https://user-images.githubusercontent.com/26221515/53070592-dec5e600-3509-11e9-996d-7301785e428e.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.3.0   | 3.4.14  | 3.10.0                |

**Comment by alexanderzobnin** [comment]
That's similar to #678 (the same root cause).
