### ISSUE TITLE
Dashboard has deleted after update plugin 3.10.0

### ISSUE THREAD

**Issue by TamKhacNINH** [alexanderzobnin/grafana-zabbix#682]
**Describe the bug**

One dashboard has deleted without any action and error React loading after update plugin.

**Screenshots**

![image](https://user-images.githubusercontent.com/36933570/53198551-3f127000-364f-11e9-8640-1b59a00a4013.png)

"
t=2019-02-16T22:32:59+0700 lvl=info msg="Syncing plugin dashboards to DB" logger=plugins pluginId=alexanderzobnin-zabbix-app
t=2019-02-16T22:32:59+0700 lvl=info msg="Deleting plugin dashboard" logger=plugins pluginId=alexanderzobnin-zabbix-app dashboard=zabbix-server-dashboard
"

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.1.4   | 4.0.4 | 3.10.0             |

**Comment by alexanderzobnin** [comment]
How did you install plugin? Try to clear browser cache as well.
