### ISSUE TITLE
offset function returns NaN in single panel 

### ISSUE THREAD

**Issue by laf-rge** [alexanderzobnin/grafana-zabbix#683]
Offset function returns NaN. I have a metric return 0 for up and 1 for down. If I use the scale(-1) this gives me the proper value. However once I add offset(1) I get NaN. I expect to get the inverted percent value (example: .01 -> .99)

**Comment by laf-rge** [comment]
<img width="951" alt="screen shot 2019-02-22 at 6 57 00 pm" src="https://user-images.githubusercontent.com/4378539/53280846-2a2bf000-36d4-11e9-9fb8-9c75f67fa51d.png">
<img width="959" alt="screen shot 2019-02-22 at 6 57 11 pm" src="https://user-images.githubusercontent.com/4378539/53280847-2a2bf000-36d4-11e9-8bec-0f0d6ef7d0ca.png">

**Comment by alexanderzobnin** [comment]
Yea, interesting, I see that function returns function body itself :)

![screenshot from 2019-02-28 20-48-45](https://user-images.githubusercontent.com/4932851/53586970-55ae4f00-3b9a-11e9-9cbb-ecc40b12242c.png)

I'll try to investigate what's wrong.
