### ISSUE TITLE
Use securejsondata instead of jsonData for storing credentials

### ISSUE THREAD

**Issue by aditya-konarde** [alexanderzobnin/grafana-zabbix#684]
**Describe the bug**

If you query the grafana dashboards api at `http://grafana:3000/api/datasources` with the zabbix plugin added , it will return the following entry for the zabbix datasource (snipped for brevity) : 
```
"jsonData": {
    "password": "password",
    "username": "username",
}
```
This exposes credentials in plaintext to anyone who can access the api, and is an additional attack surface. Even for admin users, you don't necessarily want to display credentials in plaintext.

A better approach would be to set this via secureJsonData
```
"secureJsonData": {
    "username": "username",
    "password": "password"
}
```
Benefit: The server doesn't include the values specified in the secureJsonData field. 

**Expected behavior**

The plugin should use secureJsonData for credentials
```
"jsonData": {
   "insensitive_field": "value"
},
"secureJsonData": {
    "username": "username",
    "password": "password"
},
```

**Network data**
Not applicable, see above. 

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.2.4   | 3.x  | 3.10.0                 |

**Comment by alexanderzobnin** [comment]
Duplicated, #312
Could you move your comment there?
