### ISSUE TITLE
Triggers panel: unable to edit panel in Grafana 6.0

### ISSUE THREAD

**Issue by banzayats** [alexanderzobnin/grafana-zabbix#685]
**Describe the bug**
Cannot edit triggers panel after upgrading Grafana to 6.0.0.

**Screenshots**
Browser shows blank screen:
![image](https://user-images.githubusercontent.com/477161/53396980-8b8ee000-39ae-11e9-91f0-35f41609f574.png)

Browser's console shows the following:
![image](https://user-images.githubusercontent.com/477161/53396922-64381300-39ae-11e9-8b1b-72953e453178.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.0.0   | 4.0.5  | 3.10.0                 |

**Comment by alexanderzobnin** [comment]
Yes, it's due to changes in panel architecture in grafana. I will add a fix in the next plugin release.

**Comment by alexanderzobnin** [comment]
Fixed by adding `"dataFormats": []` into `plugin.json`.
Related to https://github.com/grafana/grafana/issues/15217

**Comment by JonZolot** [comment]
I am working with an older version of Zabbix having the same edit panel issues for the older version of this plugin. Where in plugin.json do you add "dataFormats":[] to fix this?

**Comment by alexanderzobnin** [comment]
@JonZolot see the 18babc8e5f00f21e711c1a7f414ebc1923c2371f
