### ISSUE TITLE
Unable to aggregate hosts in meta data

### ISSUE THREAD

**Issue by fcmxmk** [alexanderzobnin/grafana-zabbix#687]
On the same host, the ports of different ports have different values. I want to accumulate the values of different ports on a single server for display. For example, using regular expressions to automatically group the hosts instead of increasing one by one. Thank you.

e.g. sumSeries(regex)

![image](https://user-images.githubusercontent.com/24162498/53480092-6d5fd780-3ab5-11e9-85ae-aaa938d39aab.png)

**Comment by alexanderzobnin** [comment]
Functions work only inside one query, so it's not possible to sum different queries. Try to put all hosts into one query with regex instead.
