### ISSUE TITLE
acknowledge button don't work 

### ISSUE THREAD

**Issue by lsa1es** [alexanderzobnin/grafana-zabbix#689]
acknowledge does not accept add, can not add one more. The enter and the button do not work

When I click the button to make the ack, it gets stuck on the screen. and does nothing .. does not generate traffic to the browser, it is as if the button did not exist in the backend.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v5.4.3  | 4.0.4   | 3.10.0 |

**Comment by alexanderzobnin** [comment]
Could you post a screenshot? Do you see any errors in browser console?

**Comment by lsa1es** [comment]
the screen is locked and does not function ack

Em qui, 28 de fev de 2019 às 14:38, Alexander Zobnin <
notifications@github.com> escreveu:

**Comment by alexanderzobnin** [comment]
Did you add a message text?

**Comment by lsa1es** [comment]
no. i didn't

Em ter, 19 de mar de 2019 às 04:10, Alexander Zobnin <
notifications@github.com> escreveu:

**Comment by alexanderzobnin** [comment]
You should add a message, otherwise, button won't work.

**Comment by lsa1es** [comment]
I put the message in the field, and click the button, but it gets stuck on
the screen and it does not work.

Em seg, 25 de mar de 2019 às 04:37, Alexander Zobnin <
notifications@github.com> escreveu:

**Comment by alexanderzobnin** [comment]
Please, post a network query and response (after the button click).

**Comment by lsa1es** [comment]
What do you want me to send you? the stack opens several connections

auth a242102680097183015bdd880d337c1e
id 1
jsonrpc 2.0
method event.acknowledge
params {…}
action 0
eventids 2312489
message Luiz Sales (Grafana): teste



jsonrpc 2.0
result {…}
eventids […]
0 2312489
id 1
Response payload

1

{"jsonrpc":"2.0","result":{"eventids":[2312489]},"id":1}




Em seg, 25 de mar de 2019 às 15:15, Alexander Zobnin <
notifications@github.com> escreveu:

**Comment by lsa1es** [comment]
link of the bug video happening with 3 different browsers
http://www.redhate.me/grafana/bug-ack.mov

**Comment by lsa1es** [comment]
in zabbix 4.x the method has changed and has a field that needs to be passed, in the previous zabbix does not need.

https://www.zabbix.com/documentation/4.0/manual/api/reference/event/acknowledge

action (required) | integer | Event update action(s). This is bitmask field, any combination of values are acceptable. Possible values: 1 - close problem; 2 - acknowledge event; 4 - add message; 8 - change severity.
-- | -- | --


"method": "event.acknowledge",
    "params": {
        "eventids": "20427",
        "action": 6,
        "message": "Problem resolved."

**Comment by alexanderzobnin** [comment]
Yes, looks strange.

**Comment by Positronico** [comment]
It seems the code is already prepared to handle the action (running 3.10.1 here), but it still fails. Ack form accept the message but it doesn't get added to the event.

Problem seems to be somewhere else.

  acknowledgeEvent(eventid, message) {
    const action = this.version >= 4 ? ZBX_ACK_ACTION_ACK + ZBX_ACK_ACTION_ADD_MESSAGE : ZBX_ACK_ACTION_NONE;
    const params = {
      eventids: eventid,
      message: message,
      action: action
    };
    return this.request('event.acknowledge', params);
  }

**Comment by Positronico** [comment]
Params requested seem to be ignoring the action.

![Screen Shot 2019-04-19 at 12 03 26 PM](https://user-images.githubusercontent.com/23188958/56439553-565e8a00-629b-11e9-8a61-ddc48a63f9ff.png)

**Comment by alexanderzobnin** [comment]
@Positronico what's a Zabbix version?

**Comment by Positronico** [comment]
4.2.0

**Comment by alexanderzobnin** [comment]
@Positronico try to go to the DS config, set Zabbix version to `4.x` and save data source. Default is `3.x`, so that might be a reason.

**Comment by alexanderzobnin** [comment]
@lsa1es Confirmed - this issue happens when you haven't set Zabbix version to `4.x` in DS config. I'll try to improve user experience and autodetect Zabbix version automatically.

**Comment by alexanderzobnin** [comment]
Created an issue #727
