### ISSUE TITLE
"Zabbix Problems" unacknowledged filtering error

### ISSUE THREAD

**Issue by renanyuu** [alexanderzobnin/grafana-zabbix#691]
**Describe the bug**
When filtering unacknowledged only one problem is shown (a very old one that not exists in zabbix).
When filtering acknowledged problems are shown regardless of acknowledgement but not the problem above.
**Expected behavior**
acknowledged and unacknowledged should show problems that are and are not acknowledged.

**Screenshots**
https://imgur.com/a/27Exr6b

**Network data**
Not sure how to produce this

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.0.0   | 3.4.2  | 3.10.0                 |
This worked before we upgraded the plugin to the latest version yesterday. Not sure what version we had before upgrade.

**Comment by alexanderzobnin** [comment]
Hm, I think it's related to #678 as well.
