### ISSUE TITLE
no autocomplete/select when creating a query to zabbix

### ISSUE THREAD

**Issue by kfirufk** [alexanderzobnin/grafana-zabbix#694]
**Describe the bug**
When I create a new graph and I try to query zabbix, by the tutorials I can see that an auto-complete should be opened for Group, Host, Application and Item fields but it doesn't.

**Expected behavior**
when I click on any of the fields described above a select/autocomplete box should be opened.

**Software versions**
grafana 6.0.0
zabbix 4.0.4 on nginx 1.15.9 with postgresql data source
alexanderzobnin-zabbix-app @ 3.10.0

all installed on gentoo linux.

at first I configured the plugin without direct db connection, but since autocomplete didn't work, I created a postgresql datasource to zabbix database and chose that as direct data source, unfortunately that did not resolve the issue.

any ideas ?

**Comment by alexanderzobnin** [comment]
Hi! Groups autocomplete isn't related to direct db connection. Please, ensure your zabbix user have correct access rights.
