### ISSUE TITLE
[Question] manually close problem

### ISSUE THREAD

**Issue by itsBasti** [alexanderzobnin/grafana-zabbix#698]
I'm submitting a ...
Question / Support request

**Software Version:
Grafana  Zabbix  Grafana-Zabbix Plugin**
5.4.3 --- 4.0.1 --- 3.10.1

**What did you do?**
Trying to manually close a problem from Zabbix in Grafana.
Is it possible to manually close a Zabbix Problem from the Grafana „Zabbix Problems“ panel?
The icon "Manual close problem" in the „Zabbix Problems“ panel isn’t clickable. Am I doing this wrong?
The Trigger in Zabbix is set to "Allow manual close". The "Acknowledge problem" button in Grafana is working fine.

![manual close](https://user-images.githubusercontent.com/19889940/53811637-24e36680-3f5a-11e9-9a14-daefb584fa77.jpg)

**Comment by alexanderzobnin** [comment]
@itsBasti It's not a button, this icon just indicates that problem _can_ be closed manually. I have to check Zabbix docs for user permissions for closing a problem. If it's required write permissions, it's not secure due to auth issue #380

**Comment by alexanderzobnin** [comment]
If it's possible, I will do it in #524
