### ISSUE TITLE
Error: $scope.target.host is null when no host selected

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#7]
"Error: $scope.target.host is null
$scope.selectHost@http://localhost:8090/public/app/plugins/datasource/zabbix/queryCtrl.js?bust=1431450309338:67:9
in browser's console when select "--select host--" (null).

**Comment by nucleusv** [comment]
Is it self talking ? :)  
Alex, whoud you change  this.limitmetrics     = datasource.limitmetrics || 0;
to this.limitMetrics to follow code style?

**Comment by alexanderzobnin** [comment]
Yes, I just made a note for future fixing.
I'll rename limitmetrics.

**Comment by nucleusv** [comment]
Yes, it is a error when you just add new meric to graph, 
error occurs

TypeError: Cannot read property 'hostid' of undefined
    at http://172.17.12.215:8088/plugins/datasource/zabbix/queryCtrl.js?bust=1431520803223:156:52
    at Array.filter (native)
    at http://172.17.12.215:8088/plugins/datasource/zabbix/queryCtrl.js?bust=1431520803223:153:53
    at i (http://172.17.12.215:8088/app/app.496fdc2e.js:9:30874)
    at http://172.17.12.215:8088/app/app.496fdc2e.js:9:31046
    at l.$get.l.$eval (http://172.17.12.215:8088/app/app.496fdc2e.js:10:6196)
    at l.$get.l.$digest (http://172.17.12.215:8088/app/app.496fdc2e.js:10:4714)
    at l.$get.l.$apply (http://172.17.12.215:8088/app/app.496fdc2e.js:10:6452)
    at h (http://172.17.12.215:8088/app/app.496fdc2e.js:9:14682)
    at q (http://172.17.12.215:8088/app/app.496fdc2e.js:9:16489)

**Comment by nucleusv** [comment]
I've deleted previous comment. 
Alex, when I begin to add new metric, and first select host group all lines disappear from graph, I think it is not right, grafana must not query if itemid is not defined.

**Comment by alexanderzobnin** [comment]
Yes, now when item not selected all graph are disappear. I'll fix it in nearest time. Please, open new issue with this problem.

**Comment by alexanderzobnin** [comment]
See bdae2d6e5ec96b4a5ac2d8e92521529c8ce2083a
