### ISSUE TITLE
fail to connect zabbix 2.4 

### ISSUE THREAD

**Issue by uavg** [alexanderzobnin/grafana-zabbix#70]
* Zabbix server v2.4.4 (revision 52341) (23 February 2015)
* Firefox
* grafana-2.1.1-1.x86_64

i try to setup grafana-zabbix according wiki page,
https://github.com/alexanderzobnin/grafana-zabbix/wiki/Installation#note-for-zabbix-22-or-less
but i got this error.

```
Reason: CORS header 'Access-Control-Allow-Origin' missing
```
i am sure my api_jsonrpc.php have correct config like wiki mentioned, what's the reason on it?

thanks

**Comment by uavg** [comment]
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://zabbix***/zabbix/api_jsonrpc.php. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://zabbix.***/zabbix/api_jsonrpc.php. (Reason: CORS request failed).
```

more error log.

**Comment by alexanderzobnin** [comment]
Check your web server config.

**Comment by uavg** [comment]
cool. it works for me. thanks
