### ISSUE TITLE
Show Data Source name in Zabbix Problems Virtualization

### ISSUE THREAD

**Issue by aminvakil** [alexanderzobnin/grafana-zabbix#700]
I have multiple Zabbix Servers which everyone are monitoring the same hosts but with different IPs and from all around the world and some hostname are routed to multiple servers based on their geography, therefore all Zabbix Servers have the same configuration (hosts, host groups, triggers, etc.).

As we didn't want to redundant multiple zabbix nodes on main zabbix server we didn't use zabbix proxies, so it's not an option.

The issue is when I add multiple data sources and I see a problem I can't figure out which zabbix server is giving me this error, therefore I have to check manually again from zabbix servers' dashboard.

It would be so appreciated if there was an option which data source name could be added to dashboard like host name, technical name, host groups, etc.

**Comment by alexanderzobnin** [comment]
You can see data source name in problems panel:
![Screenshot from 2019-03-14 11-57-16](https://user-images.githubusercontent.com/4932851/54343662-62c64600-4650-11e9-92bd-e2357ffca11f.png)
![Screenshot from 2019-03-14 11-56-49](https://user-images.githubusercontent.com/4932851/54343663-62c64600-4650-11e9-8b98-6cb5c5f39631.png)

**Comment by aminvakil** [comment]
I should use list mode then. My grafana is on TV and my coworkers can't press a button for every new issue. I'll go with list mode then.

Thanks

**Comment by alexanderzobnin** [comment]
I think it's possible to add an ability to show data source in table view.

**Comment by memfiz** [comment]
We also need that feature. We have 3 zabbix instances and use table layout. Actually I've change the code a little bit and use that in our environment. I'm going to send the PR as a suggestion...
