### ISSUE TITLE
Zabbix Url not connecting in grafana datastore

### ISSUE THREAD

**Issue by ayush2792** [alexanderzobnin/grafana-zabbix#703]
Hi,

I am trying to connect to zabbix api and fetching details in grafana.

![image](https://user-images.githubusercontent.com/30995806/54180109-ccafe580-44c0-11e9-8d81-d82b301f89e5.png)

**Error**: Could not connect to given url

But we have a proxy in front of zabbix url. Do we have any way to add our proxy here in garfana to connect to URL ?

**Note**: Zabbix url connection is working fine from backend (Linux) server.

Zabbix Version: 3.4
Grafana version: 6.0

Thanks,
Ayush Jain

**Comment by ayush2792** [comment]
Will appreciate if anybody can help in this regard,

**Comment by alexanderzobnin** [comment]
Any information in grafana-server logs?

**Comment by jbfuzier** [comment]
Hi,

Same issue here but without any proxy.
I do not even see any request in tcpdump, error message in the UI while saving is  also "Could not connect to given url"

**Comment by jbfuzier** [comment]
Stupid mistake on my side. 

I needed direct connection but I had a proxy set in /etc/default/grafana-server ...
