### ISSUE TITLE
Improve variable query editor

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#705]
Since Grafana supports new `VariableQueryEditor` component for plugins, it's possible to implement better variable editor for Zabbix. It should support different types of values, like
- groups, hosts, apps and items
- item values
- tags (in future)

Example of variable query editor:
https://github.com/grafana/grafana/issues/13561
https://github.com/grafana/grafana/pull/14007

**Comment by konstantin-kornienko** [comment]
Support to filter hosts by tags is very import feature, that would give much flexibility in selecting hosts for graphing. Looking forward impatiently!
