### ISSUE TITLE
Fetch error: 404 Not Found Instantiating after upgrade to 3.10.1

### ISSUE THREAD

**Issue by Okta43** [alexanderzobnin/grafana-zabbix#707]
**Describe the bug**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.0.4  | 4.0.3  | 3.0.9 -> 3.10.1                 |

I faced an issue with acknowledges action. When I'm trying to acknowledge a trigger I'm receiving the following error: "Incorrect arguments passed to function.". In order to solve that, I`m trying to upgrade the plugin to version 3.10.1 from zip files.

Steps:
- Move the old files into the home directory;
- Unzip the archive and put the folder under /var/lib/grafana/plugins/;
- Change the files owner to grafana with -R option;
- Restart grafana-server;
- Procced an "Empty cache and hard reload" in Chrome.

After the above steps, I`m receiving a new error: "Fetch error: 404 Not Found Instantiating https://link/public/react Loading https://link/public/plugins/alexanderzobnin-zabbix-app/panel-triggers/module.js Loading plugins/alexanderzobnin-zabbix-app/panel-triggers/module"

Do you have a solving hint?
Thanks a lot!

**Comment by alexanderzobnin** [comment]
Use `grafana-cli` or release branches https://github.com/alexanderzobnin/grafana-zabbix/tree/release-3.10.1
