### ISSUE TITLE
Counting the number of same metrics

### ISSUE THREAD

**Issue by Drabbies** [alexanderzobnin/grafana-zabbix#708]
I would like to use grafana to display information about our Cisco Call Manager.  I am using Zabbix to grab information about all of the phones that are on the system.  So for each phone i have a field for "Model of the Phone" and a Metric "26" which Corresponds to a "Cisco 2960".  I have about 20 devices that all report "26" for the field "Model of the Phone" and i would like to figure out how to count the number of phones report "26" as the metric.  Is it possible to do this inside of Grafana? or do i need to learn SQL to write the query?

Thank you very much for this product. It is working great for me and this would just be icing on the cake.

![image](https://user-images.githubusercontent.com/46231454/54260326-d7509600-4525-11e9-9f49-e0922a7ffa6f.png)

**Comment by alexanderzobnin** [comment]
I this SQL is exactly what you need.
