### ISSUE TITLE
Group Status Panel

### ISSUE THREAD

**Issue by moisesreis** [alexanderzobnin/grafana-zabbix#709]
I'm trying to create a group alerts pane, like the example: http://play.grafana-zabbix.org/d/000000088/system-status-dashboard?orgId=2

But just like in the example, I can not select just one group:

![image](https://user-images.githubusercontent.com/9301720/54313387-01eb2f00-45b8-11e9-86ca-6f4845e31dbe.png)

I need (zabbix):
![image](https://user-images.githubusercontent.com/9301720/54313463-2c3cec80-45b8-11e9-8d5d-d835c3242309.png)

Sorry for my bad English.

**Comment by moisesreis** [comment]
> So you want to show exactly one selected group, right? In this case, it looks like a bug in the plugin.

Thanks for the answer! I opened an issue in grafana project. I think it's a bug in the plugin: https://github.com/grafana/grafana/issues/16032

**Comment by moisesreis** [comment]
Reopen: https://github.com/grafana/grafana/issues/16032:
> please open in Zabbix plugin repo: https://github.com/alexanderzobnin/grafana-zabbix

**Comment by alexanderzobnin** [comment]
>In this case, it looks like a bug in the plugin.
I mean the bu is in this plugin, not in grafana :)
I'll take a look.

**Comment by moisesreis** [comment]
Thank you!!

**Comment by manirhel** [comment]
Hi, i've one doubt.. is this system status status (triggers) option only works for zabbix server monitoring? or we can monitor all hosts? pls help me... yesterday, i've updated the plugin from 3.11.0 to 3.12.4 and the triggers option shows "No data to show".. pls help me with this. 

Thanks!
