### ISSUE TITLE
Проблема с работоспособностью acknowledge панели триггеров

### ISSUE THREAD

**Issue by Zipdots** [alexanderzobnin/grafana-zabbix#710]
При попытке подтвердить проблему сработавшего триггера с помощью acknowledge из веб-интерфейса Grafana ни сервер zabbix, ни интерфейс Grafana не отображает какое-либо изменение. При этом используя acknowledge со стороны веб-интерфейса Zabbix изменение в Grafana происходят.
Подскажите, в чем может быть проблема? Нужна какая-то специфичная настройка?

[<a href="https://ibb.co/MPCwpR4"><img src="https://i.ibb.co/MPCwpR4/zabbix-problems.png" alt="zabbix-problems" border="0"></a>](url) [<a href="https://ibb.co/dmWQz80"><img src="https://i.ibb.co/dmWQz80/grafana-problem.png" alt="grafana-problem" border="0"></a>](url)

**Software versions**
| Grafana | Zabbix | Grafana-Zabbix Plugin |
|    6.0.1   |   4.0.5  |             3.10.1                |

**Comment by alexanderzobnin** [comment]
Нужно больше информации - какое действие выполняете, какой результат (полученный и ожидаемый), желательно, ответ от сервера (для `event.ack` запроса).

**Comment by Zipdots** [comment]
Извиняюсь за долгий ответ.
В принципе, всё просто, распишу поэтапно.
1) У сработавшего триггера в таблице Triggers List (Grafana) нажимаем "Acknowledge problem"
<a href="https://ibb.co/J5Lkbtg"><img src="https://i.ibb.co/J5Lkbtg/1.jpg" alt="1" border="0"></a>
2) Пишем текст, нажимаем Acknowledge
<a href="https://ibb.co/qp3fj2c"><img src="https://i.ibb.co/qp3fj2c/2.jpg" alt="2" border="0"></a>
3) Изменений как со стороны интерфейса Grafana, так и со стороны интерфейса Zabbix не происходит
<a href="https://ibb.co/QrnzVK4"><img src="https://i.ibb.co/QrnzVK4/3.jpg" alt="3" border="0"></a> 
4) Делаем тоже самое, только со стороны интерфейса Zabbix. Ждем Ack, пишем описание, ставим Acknowledge, аптейтим триггер
<a href="https://ibb.co/D53pNfg"><img src="https://i.ibb.co/D53pNfg/4.jpg" alt="4" border="0"></a> <a href="https://ibb.co/jDYwjDS"><img src="https://i.ibb.co/jDYwjDS/5.jpg" alt="5" border="0"></a>
5) Изменения происходят как на стороне Zabbix, так и на стороне Grafana
<a href="https://ibb.co/vQ5S6zr"><img src="https://i.ibb.co/vQ5S6zr/6.jpg" alt="6" border="0"></a> <a href="https://ibb.co/rpWb1Fv"><img src="https://i.ibb.co/rpWb1Fv/7.jpg" alt="7" border="0"></a>

Если подскажете, как забрать ответ от сервера, его тоже приложу

**Comment by alexanderzobnin** [comment]
Очень похоже на #689
