### ISSUE TITLE
Install from grafana-cli not working

### ISSUE THREAD

**Issue by linceaerian** [alexanderzobnin/grafana-zabbix#713]
**Describe the bug**
When installing via grafana cli, the installation is not detected.

**Expected behavior**
Plugin appear in grafana installed application.

**Bypass method**

The plugin is installed in the directory of plugins:

cat /etc/grafana/grafana.ini|grep plugin

*Directory where grafana will automatically scan and look for plugins*
plugins = /var/lib/grafana/plugins

But now graphana only expect it to be in dist, so the command
`sudo -u grafana grafana-cli plugins install alexanderzobnin-zabbix-app`

Create it in /var/lib/grafana/plugins/ and is not detected.

The command
`sudo -u grafana grafana-cli --pluginsDir /var/lib/grafana/plugins/dist plugins install alexanderzobnin-zabbix-app`

Create it in /var/lib/grafana/plugins/dist and it's detected correctly.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.0.2   | N/A  | 3.10.1                 |

**Comment by alexanderzobnin** [comment]
I don't understand what you want to get. Any error after `sudo -u grafana grafana-cli plugins install alexanderzobnin-zabbix-app`? What's a result of `cat /etc/grafana/grafana.ini | grep plugin`?

**Comment by sdestivelle** [comment]
I've got the same problem with Grafana version 6.1.4.
The plugin is installed in the /var/lib/grafana/plugins folder, but is not visible in the web interface.

**Comment by alexanderzobnin** [comment]
@sdestivelle does it fail only with Grafana 6.1.4?

**Comment by sdestivelle** [comment]
@alexanderzobnin I see that it is linked to the fact that at the start Grafana wants to contact the plugin repo from grafana.com and our installation is behind a proxy. So I think that it is not related to the new version of your plugin. Sorry. Thanks. Best regards.

**Comment by linceaerian** [comment]
@alexanderzobnin Sorry for the delay, I did not have the access to the host last week to get your answer.

Grafana version: grafana-6.0.2-1.x86_64
Config for plugin:
plugins = /var/lib/grafana/plugins

In fact I got no error/log whatsoever, it's just that the plugin does not appear in the interface and it's installed correctly in the directory "/var/lib/grafana/plugins", but It seems that Grafana expect it in "/var/lib/grafana/plugins/dist" (cause when I change the plugin default dir to the second directory it's detected correctly and appear in the interface).

I thought it was a bug from your side but considering the configuration dir is where the install happens, it should be the normal behavior.
Not sure what happens thought.

I'll close the issue, Thanks 👍 :)

**Comment by alexanderzobnin** [comment]
Ok

**Comment by azzeddine007** [comment]
i have  the a simular probleme can you help me  this is the error 

root@ubuntu:/home/ubuntu# sudo -u grafana grafana-cli --pluginsDir /var/lib/grafana/plugins/dist plugins install alexanderzobnin-zabbix-app
Error: ✗ Failed to send request: Get "https://grafana.com/api/plugins/repo/alexanderzobnin-zabbix-app": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
