### ISSUE TITLE
Trigger state on the panel (heart icon) doesn't work in Grafana 6

### ISSUE THREAD

**Issue by divanikus** [alexanderzobnin/grafana-zabbix#715]
Previous version of Grafana and Zabbix plugin were showing trigger status right on the graph panel. I mean the heart sign and the red glowing if something is wrong. Seems like this feature was removed in 6.x series. 
Eventhough I can create triggers inside the Grafana by itself, they are not the same as Zabbix triggers I have already configured.
Could this be reimplemented?

**Comment by alexanderzobnin** [comment]
It should work still. Do you have any additional information about your problem?

![Screenshot from 2019-04-18 18-55-19](https://user-images.githubusercontent.com/4932851/56374313-8b230080-620b-11e9-9ea7-2eb40a00eb23.png)

**Comment by kris4ever** [comment]
Hi,
I too have the same issue. The plugin looks to be working properly, data is fetched and shown on Grafana, everything looks OK, but Zabbix logo doesn't show on the left bar, and some features are no longer present, such as heats (green/red) and red glowing around the panels.
Please let me know what kind of information you need me to provide. No error found on the logs so far.
Thanks for your help.

Kris.

**Comment by divanikus** [comment]
Yes, no glowing, no broken hearts on panels, etc. Idk which additional info do you need. I'm using Zabbix 4.2, Grafana 6.1.4 and plugin 3.10.2. Zabbix data source and direct DB data source are set. Direct DB user has limited access to Zabbix's tables, idk if it might be the problem.  The setup was made several Grafana version ago (since version 4, I guess) and was working till latest upgrade to 6 series.

**Comment by eertul** [comment]
+1

**Comment by alexanderzobnin** [comment]
Confirmed, it's a bug. CSS in the plugin doesn't fit Grafana 6.

**Comment by bakemonoru** [comment]
It seems that bug returned.
v. 6.7.2 - no heart icon
downgraded to v. 6.7.1 - no heart icon
downgraded to v. 6.7.0 - no heart icon
downgraded to v. 6.6.2 - works!

zabbix server: 4.4.7
plugin: 3.11.0

**Comment by alexanderzobnin** [comment]
Yes, there's an issue #931
