### ISSUE TITLE
Zabbix  Api 4.2.0 not show metrics

### ISSUE THREAD

**Issue by jguida** [alexanderzobnin/grafana-zabbix#718]
Hi i have zabbix 4.2 Grafana 5.2.2 and zabbix-grafana 3.10.1

Correct grafana datasource:
![imagen](https://user-images.githubusercontent.com/15660828/55676956-14097600-58b5-11e9-9ac7-e5bb0ddf9472.png)

Not show  metric:
![imagen](https://user-images.githubusercontent.com/15660828/55676970-71052c00-58b5-11e9-82ba-eaa7f67675e4.png)

**Comment by darrynv** [comment]
Can you paste in what you see under > Query Inspector in the bottom picture

**Comment by jguida** [comment]
Hello, close the issue, grafana server was out of time, and as I tried to see the events of less than 5 minutes did not show anything.

**Comment by leleobhz** [comment]
For zabbix-server-pgsql 4.2 from docker image and grafana from latest docker image, I got this issue too. Please reopen it.

![Captura de tela de 2019-04-23 10-35-08](https://user-images.githubusercontent.com/201189/56585163-a9924e80-65b3-11e9-94cf-0e851822e0d6.png)

(Query inspecto keeps loading and do not changes from this status).

![Captura de tela de 2019-04-23 10-26-40](https://user-images.githubusercontent.com/201189/56585165-a9924e80-65b3-11e9-87f9-a839d4916c3d.png)

**Comment by leleobhz** [comment]
Testing query directly inside grafana image:

```
[root@mon ~]# docker exec -it grafana curl -s -d '{"jsonrpc":"2.0","method":"apiinfo.version","id":1,"auth":null,"params":{}}' -H "Content-Type: application/json-rpc" -X POST -L http://zabbix-web-nginx-pgsql/api_jsonrpc.php ; echo
{"jsonrpc":"2.0","result":"4.2.0","id":1}
[root@mon ~]# 

```
