### ISSUE TITLE
Triggers Panel

### ISSUE THREAD

**Issue by karpath** [alexanderzobnin/grafana-zabbix#72]
Hello, 

Thank you for your plugin, already very usefull here and best zabbix dashboard i have ever seen
We wonder if it is possible to add trigger display in single stat boxes in order to achieve a proper displayable dashboard in our support service.

THanks

**Comment by alexanderzobnin** [comment]
Hello! Thanks for your feedback. Behavior of the panels is specified by Grafana. I don't add this feature in datasource. But I'm going to work on the trigger panel in future.

**Comment by alexanderzobnin** [comment]
intermediate design:

![2015-08-23 13-31-27 grafana - zabbix triggers panel - google chrome](https://cloud.githubusercontent.com/assets/4932851/9427875/7abbc9b6-499b-11e5-84cb-805390dfddf0.png)

**Comment by alexanderzobnin** [comment]
Trigger comments (description) and acknowledges:

![trigger_panel_design](https://cloud.githubusercontent.com/assets/4932851/9429059/6f3aca5c-49cc-11e5-9da2-317a7afa5f14.gif)

**Comment by karpath** [comment]
very nice work, can't wait to test it

**Comment by alexanderzobnin** [comment]
You can download code from [feature-trigger_panel](https://github.com/alexanderzobnin/grafana-zabbix/tree/feature-trigger_panel), copy content to Grafana sources `/public/app` directory and build Grafana from sources.

**Comment by karpath** [comment]
Hi, just tried it on a test server. I have this error when i start a trigger panel
![error_trigger_panel](https://cloud.githubusercontent.com/assets/13885161/9468948/c31d79de-4b44-11e5-8f35-17e8e441acbc.PNG)

datasource is correctly added, the test connection is ok. I had a few warn during the npm install -g grunt-cli but the grunt command ends up successfull without errors.

**Comment by alexanderzobnin** [comment]
Are you added another panels on dashboard?

**Comment by alexanderzobnin** [comment]
Try to add some Zabbix graph. This is needed to initialize datasource.

**Comment by karpath** [comment]
I can't add another graph, nothing happen when i click on query. something went probably wrong during install. 
I will reinstall it tomorrow

**Comment by alexanderzobnin** [comment]
I have a similar problems. Try to use 2.1.3 (2015-08-24) build for grafana-server and rebuild frontend with plugin from appropriate sources (https://github.com/grafana/grafana/tree/v2.1.3).

**Comment by karpath** [comment]
hi, 

rebuild from 2.1.3, nom i can add zabbix graph but i still have the same error when i start a trigger pannel. I'll wait for 2.2.

**Comment by alexanderzobnin** [comment]
Now this feature still in development and I don't have tested at server. Wait for some time.

**Comment by felipinho-lima** [comment]
Hello friend,

First i need says to you NICE WORK in integration Zabbix with Grafana.
It's strange but i don't have in my grafana server the file settings.js (/usr/share/grafana/public/app/components) only require.config.js
I changed all files in this version and the panel of triggers doesn't exist in button add panels.

**Comment by alexanderzobnin** [comment]
settings.js file only present in the sources. Now Grafana don't supports custom panels as plugins and you need first download source code, add new panel in `settings.js` and rebuild frontend. [Support for additional panels](https://github.com/grafana/grafana/issues/2572) will be added in next version of Grafana (2.2).

**Comment by alexanderzobnin** [comment]
So this panel will be available in next Grafana version.

**Comment by felipinho-lima** [comment]
I understand. But how do i proceed to have this panel ? I want implement this full API in my company. You can help me ?

**Comment by alexanderzobnin** [comment]
This panel still in development. But if you want to try it please read [Grafana building from source](http://docs.grafana.org/project/building_from_source/) docs. I also will try to build a package for easy deploying anytime soon.

**Comment by felipinho-lima** [comment]
Ok. No problem. I go read the documentation and try. Thank you for all and congratulation.

**Comment by alexanderzobnin** [comment]
Thanks!

**Comment by slick666** [comment]
+1 for this feature

**Comment by efa2000** [comment]
+1 for this feature

**Comment by zzwangsh** [comment]
+1 for this feature

**Comment by xiaoping378** [comment]
+1

**Comment by karpath** [comment]
Hello, any news on that front?

**Comment by alexanderzobnin** [comment]
@karpath sorry, now a have another work. Hope, I will finish trigger panel during this month.

**Comment by galindro** [comment]
@alexanderzobnin . I've built a dashboard to get zabbix triggers grouped by application. This is my project: https://github.com/galindro/zabbix-dashing. It was built using https://github.com/Shopify/dashing. 

I don't have much experience with grafana nor javascript programing language, so, unfortunatelly, I can't help you to improve your project. But, if you want or have enough time to do it, I suggest you to build a pannel like the ones used in my project. You could filter them not by application, but by host group. 

I've think to change my project a few weeks ago to classify the pannels by host groups, not by application, because some alerts cannot be displayed on the pannels (CPU, disks, etc...). So, instead of modify my project, you could implement this on you project.

I'll talk with my boss about this. Maybe he could help you allocating some developer of our team to make this change more faster.

Do you agree?

**Comment by alexanderzobnin** [comment]
@galindro Thanks for you suggestion! First a want to tell about two major reasons for what I can't finish trigger panel right now. Firstly, this feature is sponsored by some company and I just wait for detailed specifications. One of condition of my work is a fully open sources. Second reason is a Grafana's restrictions - now panels don't supports as plugins and I waiting for this feature. Without this feature I will be forced to provide my own builds for Grafana (with my triggers panel) and it's harder to maintain.

Also I looked at your project - it's interesting idea to use _Shopify/Dashing_ for reach Zabbix dashboard. Can you tell me about your main goals in this project?

**Comment by galindro** [comment]
@alexanderzobnin thanks for return.

The goal of my project is simple: Display a more friendly monitoring dashboard to managers and operators. After see your work, my goal now is to make my project deprecated in flavor of yours, because grafana is very flexible in comparison to dashing.

My project was born after my boss tell me that he wants a dashboard that is capable to provide a simple way to know the status of an application or service. After he had seen the default zabbix web interface, he tell me what kind of dashboard he wants and I built one from scratch for his needs. Just like you, I've put my work in an open source model, so I can help anyone arround the world. Today I'm using it in my other job: [UFSC - Federal University of Santa Catarina] (http://en.ufsc.br/). 

About your first reason: how much time do you think that you will wait for the specs? Maybe you could show my dashboard to them as a new idea...

About your secod reason: is there an issue openned in grafana for make this possible? Could you make a PR to provide this kind of functionallity for grafana project?

As I said before, I'm not familiarized with javascript. I'm not a web developer. I'm a cloud enginner/sysops. But, I know people that maybe could help.

Thanks again for your atention.

**Comment by alexanderzobnin** [comment]
@galindro Yes, I opened [issue](https://github.com/grafana/grafana/issues/2572) in Grafana for custom panels as plugins. I think I will have clear vision of task after few weeks.

**Comment by galindro** [comment]
Ok @alexanderzobnin 
Tks again

**Comment by alexanderzobnin** [comment]
I see that this feature is very popular. :+1:

**Comment by nucleusv** [comment]
No, not popular, we cannot live without it (!) +1: )

+ need to select datasource for trigger panel: to have triggers from different zabbixes
+ filters: host, group, trigger name

**Comment by galindro** [comment]
Agree with @nucleusv 

Another filter: severity

**Comment by galindro** [comment]
@alexanderzobnin do you have any updates about this feature?

**Comment by alexanderzobnin** [comment]
Hi, folks! Because panels as plugins feature is still not implemented in Grafana, I fork Grafana repo and added zabbix triggers panel to [zbx-trigger_panel](https://github.com/alexanderzobnin/grafana/tree/zbx-trigger_panel) branch. If you can't wait for final release, build this version from sources using [Building Grafana from source](http://docs.grafana.org/project/building_from_source/) docs. This version based on Grafana 2.5.0 and contais latest grafana-zabbi plugin version (2.5.1).

**Comment by alexanderzobnin** [comment]
Last builds now available at http://download.grafana-zabbix.org

**Comment by galindro** [comment]
@alexanderzobnin . Thank you very much for your updates. I've installed the package grafana_2.5.1-zbx.pre.3_amd64.deb  and the service is failling to start at this point:

```bash
2015/12/04 17:03:32 [I] Starting Grafana
2015/12/04 17:03:32 [I] Version: 2.5.1-zbx.pre.3, Commit: v2.5.0+13-gd79d8ff, Build date: 2015-12-04 08:59:31 +0000 UTC
2015/12/04 17:03:32 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/12/04 17:03:32 [I] Database: sqlite3
2015/12/04 17:03:32 [I] Migrator: Starting DB migration
2015/12/04 17:03:32 [I] Listen: https://0.0.0.0:3000
2015/12/04 17:03:32 [web.go:93 StartServer()] [E] Fail to start server: open : no such file or directory
```

**Comment by alexanderzobnin** [comment]
@galindro I can't see your last comment. Are you have any problems with packages?

**Comment by alexanderzobnin** [comment]
Triggers panel demo available at http://45.63.116.239:3000/

![triggers_dashboard](https://cloud.githubusercontent.com/assets/4932851/11635859/2f9c440a-9d2a-11e5-9017-bb338dcbd128.png)

**Comment by galindro** [comment]
@alexanderzobnin I've posted a wrong question here... so I've deleted it as soon as I realized... Sorry :)

**Comment by karpath** [comment]
@alexanderzobnin Hello, i have just seen the demo site you made, very nice work. If I install your fork do i have to redo all the graph i made so far?

**Comment by alexanderzobnin** [comment]
@karpath No, it's like Grafana package update - database and configs remains. But do backup just in case :floppy_disk:.

**Comment by karpath** [comment]
@alexanderzobnin :thumbsup: :clap:
working fine here

**Comment by alexanderzobnin** [comment]
Thanks! Let me know if you find any bugs - feature still in testing.

**Comment by johnk3r** [comment]
+1

**Comment by roysbike** [comment]
Thanks! +1

**Comment by pvillarragut** [comment]
I installed the latest deb package from  http://download.grafana-zabbix.org and when I try to add a trigger panel  I get this error  "Cannot read property 'getTriggers' of undefined" . 

Thanks.

**Comment by alexanderzobnin** [comment]
@pvillarragut Can you attach full error trace?

**Comment by pvillarragut** [comment]
This is the full trace ( i replaced the original domain for dummy.com) 

Stack trace:
			TypeError: Cannot read property 'getTriggers' of undefined
    at n.b.refreshData (http://dummy.com:3000/app/app.ba9fd363.js:43:15433)
    at http://dummy.com:3000/app/app.ba9fd363.js:31:5867
    at i (http://dummy.com:3000/app/app.ba9fd363.js:12:3869)
    at http://dummy.com:3000/app/app.ba9fd363.js:12:4041
    at n.$eval (http://dummy.com:3000/app/app.ba9fd363.js:12:11661)
    at n.$digest (http://dummy.com:3000/app/app.ba9fd363.js:12:10092)
    at n.$apply (http://dummy.com:3000/app/app.ba9fd363.js:12:11928)
    at http://dummy.com:3000/app/app.ba9fd363.js:12:19264
    at e (http://dummy.com:3000/app/app.ba9fd363.js:10:26558)
    at http://dummy.com:3000/app/app.ba9fd363.js:10:27987

**Comment by alexanderzobnin** [comment]
Implemented as panel plugin.

**Comment by mdiorio** [comment]
Is there a way to filter the panel by group or host?  I see there's a   "showTriggers": "all triggers".  I'd love to put one of these on each of my group dashboards and one on the overview dashboard.
Thanks.

**Comment by rgadiga** [comment]
Unable to set the alert.
The datasource does not support alerting queries
tsdb.HandleRequest() error Could not find executor for data source type: alexanderzobnin-zabbix-datasource

**Comment by alexanderzobnin** [comment]
@rgadiga  you're right,
> The datasource does not support alerting queries

**Comment by shlomihorev** [comment]
@alexanderzobnin  - Do you plan to add alerting support to your plugin? Thanks for all your hard work. :)

**Comment by alexanderzobnin** [comment]
@shlomihorev yes, but have no estimates.

**Comment by dpotam** [comment]
Hello, Alexander! Nice project. Graphs based on zabbix items working fine. Have trouble with triggers. When i try add trigger then i have message that connect with zabbix api is wrong. I try look what it send and receive and see that zabbix can't sort by 'clock' in my case. Must i edit js and map for more properly json in this case or source of trouble in another place? zabbix api 2.0.5, grafana 4.3.2, grafana-zabbix last version. Anyway thanks for your work.

**Comment by alexanderzobnin** [comment]
@dpotam Can you describe what you do step-by-step?

**Comment by dpotam** [comment]
Hello!

1) add zabbix datasource
2) create dashboard
3) add zabbix trigger panel on it
4) start configure trigger. choose host group from generated dropdown list
5) choose host
6) click on trigger name field. at this moment got red message about error
with zabbix connection

Check what in network sniffer, see that zabbix return message like
"application not support sorting by 'clock'". Look at documentation and see
that this field (got this name from json request) support sort by eventid
and another two. Sorry, i cant remember field name now. Can wrote it at
tuesday. Then i edit js and map files change clock to eventid. Then i have
stuck that next request do not return triggers. I have edit js at filter=1
line. Also i see that in another place this line already commented.

What i want to know. Am i right understand that something go wrong? :-)

10 июн 2017 г. 12:40 пользователь "Alexander Zobnin" <
notifications@github.com> написал:

**Comment by alexanderzobnin** [comment]
@dpotam seems it's a difference between api versions. I'll try to check 2.0 docs for application.get params.

**Comment by dpotam** [comment]
Man, i can do it myself at tuesday and then write result to you. Not spent
your time for this. You was do great job already. Thx for describe
direction for search.

10 июн 2017 г. 20:05 пользователь "Alexander Zobnin" <
notifications@github.com> написал:

**Comment by dpotam** [comment]
Hello! I was edit zabbixAPI.service.js at part

        key: 'getAcknowledges',

        value: function getAcknowledges(eventids) {

          var params = {

            output: 'extend',

            eventids: eventids,

            preservekeys: true,

            select_acknowledges: 'extend',

            sortfield: 'eventid',

            sortorder: 'DESC'

          };


with change "clock" to "eventid". After this i see at network traffic that
json return fine, but in web interface i have not see triggers in drop-down
list. What do next?

**Comment by alexanderzobnin** [comment]
@dpotam Can you make a screenshot?

**Comment by dpotam** [comment]
Yes, of course. Group and Host was get through API. Trigger not displaying.

[image: Встроенное изображение 1]


But in network traffic i see that triggers was received through API:

Request:

{"jsonrpc":"2.0","method":"trigger.get","params":{"output":"extend","groupids":["6"],"hostids":["10088"],"expandDescription":true,"expandData":true,"expandComment":true,"monitored":true,"skipDependent":true,"filter":{"value":"1"},"selectGroups":["name"],"selectHosts":["name","host"],"selectItems":["name","key_","lastvalue"],"selectLastEvent":"extend"},"id":1,"auth":"2cccd1834c84b0220a36fb7e62b94fd0"}

Answer:

{"jsonrpc":"2.0","result":[{"hosts":[{"hostid":"10088","name":"test-esb-adminserver-jmx","host":"test-esb-adminserver-jmx"}],"items":[{"itemid":"23559","name":"Name
of the current
compiler","key_":"jmx[\"java.lang:type=Compilation\",Name]","lastvalue":"HotSpot
64-Bit Tiered
Compilers"}],"triggerid":"13537","expression":"{12984}#1","description":"test-esb-adminserver-jmx
uses suboptimal jit
compiler","url":"","status":"0","value":"1","priority":"1","lastchange":"1486371605","comments":"","error":"","templateid":"13466","type":"0","value_flags":"0","flags":"0","groupid":"6","hostid":"10088","hostname":"test-esb-adminserver-jmx","host":"test-esb-adminserver-jmx"},{"hosts":[{"hostid":"10088","name":"test-esb-adminserver-jmx","host":"test-esb-adminserver-jmx"}],"items":[{"itemid":"23582","name":"mp
Code Cache used","key_":"jmx[\"java.lang:type=MemoryPool,name=Code
Cache\",Usage.used]","lastvalue":"46682176"},{"itemid":"23581","name":"mp
Code Cache max","key_":"jmx[\"java.lang:type=MemoryPool,name=Code
Cache\",Usage.max]","lastvalue":"50331648"}],"triggerid":"13546","expression":"{13001}>({13002}*0.7)","description":"70%
mp Code Cache used on
test-esb-adminserver-jmx","url":"","status":"0","value":"1","priority":"3","lastchange":"1497341465","comments":"","error":"","templateid":"13447","type":"0","value_flags":"0","flags":"0","groupid":"6","hostid":"10088","hostname":"test-esb-adminserver-jmx","host":"test-esb-adminserver-jmx"},{"hosts":[{"hostid":"10088","name":"test-esb-adminserver-jmx","host":"test-esb-adminserver-jmx"}],"items":[{"itemid":"23586","name":"mp
PS Old Gen committed","key_":"jmx[\"java.lang:type=MemoryPool,name=PS Old
Gen\",Usage.committed]","lastvalue":"5726666752"},{"itemid":"23587","name":"mp
PS Old Gen max","key_":"jmx[\"java.lang:type=MemoryPool,name=PS Old
Gen\",Usage.max]","lastvalue":"5726666752"}],"triggerid":"13549","expression":"{13007}={13008}","description":"mp
PS Old Gen fully committed on
test-esb-adminserver-jmx","url":"","status":"0","value":"1","priority":"2","lastchange":"1497517148","comments":"","error":"","templateid":"13462","type":"0","value_flags":"0","flags":"0","groupid":"6","hostid":"10088","hostname":"test-esb-adminserver-jmx","host":"test-esb-adminserver-jmx"},{"hosts":[{"hostid":"10088","name":"test-esb-adminserver-jmx","host":"test-esb-adminserver-jmx"}],"items":[{"itemid":"23587","name":"mp
PS Old Gen max","key_":"jmx[\"java.lang:type=MemoryPool,name=PS Old
Gen\",Usage.max]","lastvalue":"5726666752"},{"itemid":"23588","name":"mp PS
Old Gen used","key_":"jmx[\"java.lang:type=MemoryPool,name=PS Old
Gen\",Usage.used]","lastvalue":"5149910896"}],"triggerid":"13550","expression":"{13009}>({13010}*0.7)","description":"70%
mp PS Old Gen used on
test-esb-adminserver-jmx","url":"","status":"0","value":"1","priority":"3","lastchange":"1497596825","comments":"","error":"","templateid":"13449","type":"0","value_flags":"0","flags":"0","groupid":"6","hostid":"10088","hostname":"test-esb-adminserver-jmx","host":"test-esb-adminserver-jmx"}],"id":1}





2017-06-15 22:03 GMT+03:00 Alexander Zobnin <notifications@github.com>:

**Comment by alexanderzobnin** [comment]
Request:

```js
{
  "jsonrpc":"2.0",
  "method":"trigger.get",
  "params":{
    "output":"extend",
    "groupids":[
      "6"
    ],
    "hostids":[
      "10088"
    ],
    "expandDescription":true,
    "expandData":true,
    "expandComment":true,
    "monitored":true,
    "skipDependent":true,
    "filter":{
      "value":"1"
    },
    "selectGroups":[
      "name"
    ],
    "selectHosts":[
      "name",
      "host"
    ],
    "selectItems":[
      "name",
      "key_",
      "lastvalue"
    ],
    "selectLastEvent":"extend"
  },
  "id":1,
  "auth":"2cccd1834c84b0220a36fb7e62b94fd0"
}
```

Answer:

```js
{
  "jsonrpc":"2.0",
  "result":[
    {
      "hosts":[
        {
          "hostid":"10088",
          "name":"test-esb-adminserver-jmx",
          "host":"test-esb-adminserver-jmx"
        }
      ],
      "items":[
        {
          "itemid":"23559",
          "name":"Name of the current compiler",
          "key_":"jmx[\"java.lang:type=Compilation\",Name]",
          "lastvalue":"HotSpot 64-Bit Tiered Compilers"
        }
      ],
      "triggerid":"13537",
      "expression":"{12984}#1",
      "description":"test-esb-adminserver-jmx uses suboptimal jit compiler",
      "url":"",
      "status":"0",
      "value":"1",
      "priority":"1",
      "lastchange":"1486371605",
      "comments":"",
      "error":"",
      "templateid":"13466",
      "type":"0",
      "value_flags":"0",
      "flags":"0",
      "groupid":"6",
      "hostid":"10088",
      "hostname":"test-esb-adminserver-jmx",
      "host":"test-esb-adminserver-jmx"
    },
    {
      "hosts":[
        {
          "hostid":"10088",
          "name":"test-esb-adminserver-jmx",
          "host":"test-esb-adminserver-jmx"
        }
      ],
      "items":[
        {
          "itemid":"23582",
          "name":"mp Code Cache used",
          "key_":"jmx[\"java.lang:type=MemoryPool,name=Code Cache\",Usage.used]",
          "lastvalue":"46682176"
        },
        {
          "itemid":"23581",
          "name":"mp Code Cache max",
          "key_":"jmx[\"java.lang:type=MemoryPool,name=Code Cache\",Usage.max]",
          "lastvalue":"50331648"
        }
      ],
      "triggerid":"13546",
      "expression":"{13001}>({13002}*0.7)",
      "description":"70% mp Code Cache used on test-esb-adminserver-jmx",
      "url":"",
      "status":"0",
      "value":"1",
      "priority":"3",
      "lastchange":"1497341465",
      "comments":"",
      "error":"",
      "templateid":"13447",
      "type":"0",
      "value_flags":"0",
      "flags":"0",
      "groupid":"6",
      "hostid":"10088",
      "hostname":"test-esb-adminserver-jmx",
      "host":"test-esb-adminserver-jmx"
    },
    {
      "hosts":[
        {
          "hostid":"10088",
          "name":"test-esb-adminserver-jmx",
          "host":"test-esb-adminserver-jmx"
        }
      ],
      "items":[
        {
          "itemid":"23586",
          "name":"mp PS Old Gen committed",
          "key_":"jmx[\"java.lang:type=MemoryPool,name=PS Old Gen\",Usage.committed]",
          "lastvalue":"5726666752"
        },
        {
          "itemid":"23587",
          "name":"mp PS Old Gen max",
          "key_":"jmx[\"java.lang:type=MemoryPool,name=PS Old Gen\",Usage.max]",
          "lastvalue":"5726666752"
        }
      ],
      "triggerid":"13549",
      "expression":"{13007}={13008}",
      "description":"mp PS Old Gen fully committed on test-esb-adminserver-jmx",
      "url":"",
      "status":"0",
      "value":"1",
      "priority":"2",
      "lastchange":"1497517148",
      "comments":"",
      "error":"",
      "templateid":"13462",
      "type":"0",
      "value_flags":"0",
      "flags":"0",
      "groupid":"6",
      "hostid":"10088",
      "hostname":"test-esb-adminserver-jmx",
      "host":"test-esb-adminserver-jmx"
    },
    {
      "hosts":[
        {
          "hostid":"10088",
          "name":"test-esb-adminserver-jmx",
          "host":"test-esb-adminserver-jmx"
        }
      ],
      "items":[
        {
          "itemid":"23587",
          "name":"mp PS Old Gen max",
          "key_":"jmx[\"java.lang:type=MemoryPool,name=PS Old Gen\",Usage.max]",
          "lastvalue":"5726666752"
        },
        {
          "itemid":"23588",
          "name":"mp PS Old Gen used",
          "key_":"jmx[\"java.lang:type=MemoryPool,name=PS Old Gen\",Usage.used]",
          "lastvalue":"5149910896"
        }
      ],
      "triggerid":"13550",
      "expression":"{13009}>({13010}*0.7)",
      "description":"70% mp PS Old Gen used on test-esb-adminserver-jmx",
      "url":"",
      "status":"0",
      "value":"1",
      "priority":"3",
      "lastchange":"1497596825",
      "comments":"",
      "error":"",
      "templateid":"13449",
      "type":"0",
      "value_flags":"0",
      "flags":"0",
      "groupid":"6",
      "hostid":"10088",
      "hostname":"test-esb-adminserver-jmx",
      "host":"test-esb-adminserver-jmx"
    }
  ],
  "id":1
}
```

**Comment by dpotam** [comment]
Yeah, sorry, i was must beatify json.

2017-06-16 22:02 GMT+03:00 Alexander Zobnin <notifications@github.com>:

**Comment by alexanderzobnin** [comment]
The response looks good. Do you see any errors in browser console?

**Comment by dpotam** [comment]
not check it yet. i will check. am i right understand that this answer good
for grafana-zabbix current version and not only json syntax?

16 июн 2017 г. 22:13 пользователь "Alexander Zobnin" <
notifications@github.com> написал:

**Comment by dpotam** [comment]
No errors at console.

2017-06-16 22:42 GMT+03:00 Дмитрий Потамошнев <d.potam@gmail.com>:

**Comment by dpotam** [comment]
Alexander, it seems like i choose wrong way. Now i install new version of
Zabbix (3.2.6) and will connect Grafana-Zabbix to it. Thanks for your work
once again!

2017-06-20 9:49 GMT+03:00 Дмитрий Потамошнев <d.potam@gmail.com>:

**Comment by dpotam** [comment]
Working like beatiful thing.

**Comment by alexanderzobnin** [comment]
So, the problem was in Zabbix, not in the plugin?

**Comment by dpotam** [comment]
Problem was in that i take too old version of Zabbix with too new version of Plugin :-)

**Comment by msrsldks** [comment]
所有主机都正常的时候默认的背景色为黑色的 有没有办法来进行修改

**Comment by latsygin** [comment]
@alexanderzobnin подскажите, почему я не вижу поля Link ? Как его добавить?
![image](https://github.com/alexanderzobnin/grafana-zabbix/assets/32664599/548b6a36-7e1b-4ba2-9665-862e3ac8cc31)
