### ISSUE TITLE
Grafana returning wrong value

### ISSUE THREAD

**Issue by Oberon520** [alexanderzobnin/grafana-zabbix#725]
Zabbix version 3.4.8.
Grafana version 6.1.0
Plugin version 3.10.1
Hello! We are having issue with some metrics. Grafana displays zeros in graphs and tables while zabbix graph have values above zero.
![zabbix](https://user-images.githubusercontent.com/49863474/56495992-61662400-6500-11e9-821e-0b4d485ec9d0.png)
![grafana](https://user-images.githubusercontent.com/49863474/56495999-64611480-6500-11e9-9467-7a6a0cfb1949.png)
![grafana2](https://user-images.githubusercontent.com/49863474/56496001-65924180-6500-11e9-897f-3c44d261ec2f.png)

**Comment by alexanderzobnin** [comment]
What's a decimals config? Which type of stats do you use for the singlestat?
