### ISSUE TITLE
Feature request: SLA graph over time

### ISSUE THREAD

**Issue by mjtrangoni** [alexanderzobnin/grafana-zabbix#728]
Hi @alexanderzobnin,

**Is your feature request related to a problem? Please describe.**
The SLAs are available via [service.getsla](https://www.zabbix.com/documentation/4.2/manual/api/reference/service/getsla), which gives us a Graph with a continuous line from timestamp A to timestamp B.

**Describe the solution you'd like**
I would like to have a variable graph, that change the slope when the SLAs changes inside the timestamp period.

**Describe alternatives you've considered**
I see, there is a **Service availability report** with the option "daily", which would get us at least a daily resolution for this, for example here,
```
https://zabbixurl/zabbix.php?action=report.services&serviceid=1&period=daily&year=2019
```

**Additional context**
I am new to Zabbix, so I don't known the background, why this is not implemented over the time already. I would like to hear your opinion about it, and if this should be directly a change request at the zabbix-side.

A kind of workaround/solution would be, sending more than only one interval with `service.getsla`, so that you would get more values back.

**Comment by flassman** [comment]
Another workaround would be to query the SLA values from zabbix itself (with a web scenario?) to get the usual data which can be nicely displayed like any other graph

**Comment by alexanderzobnin** [comment]
That's tricky and may cause Zabbix server overloading. I strongly believe that if you want to graph something, so a corresponding method for this should exist.

**Comment by SeverinLeonhardt** [comment]
According to the [service.getsla documentation](https://www.zabbix.com/documentation/4.2/manual/api/reference/service/getsla) the `intervals` parameter accepts an array of intervals. This should allow querying multiple SLA values within one API request to generate a graph.

**Comment by alexanderzobnin** [comment]
@SeverinLeonhardt yes, I understand. But how many intervals I can provide without affecting zabbix performance. I see that in reports Zabbix uses weekly intervals only.

**Comment by JeferCatarina** [comment]
Hi @alexanderzobnin how've you been? 

My company was looking for this feature in Grafana and I made some tests with your code and I think that could be useful in general. My idea was keep the same interval as in the Zabbix PHP inside the Grafana plugin, that is 1 day. With this interval I think it wouldn't affect performance and we could summarize data using the functions. E.g: An interval of 7 days will return 7 results. To show the SLA over time, just plot this values in a "Graph" and to show a summarized SLA plot this values using "Single stat" with "avg" or adding the function "aggregateBy" in a "Graph".

What do you thing? Could be a new feature?

I did almost everything, except include the "functions" option.

**Comment by alexanderzobnin** [comment]
@JeferCatarina Thanks for the PR! That's looking good overall.

**Comment by mjtrangoni** [comment]
@alexanderzobnin @JeferCatarina I found a bug/issue in this approach.
I think we should handle this different for *SingleStat* and *Graph* panels. 
With the current state, a *SingleStat* panel has to be configured from `Current` to `Average` Value for a meaningful value, and this result will not be as accurate  as what Zabbix returns for the whole period (minimal difference).
Is it possible to handle *SingleStat* the old way, and other panels the new way?
Thanks!

**Comment by alexanderzobnin** [comment]
@mjtrangoni yes, I think #531 should solve this problem, so keep track it.
