### ISSUE TITLE
Acknowledge button wrongly behaviour

### ISSUE THREAD

**Issue by silveraignacio** [alexanderzobnin/grafana-zabbix#729]
Hello! I have the same issue as reported before on the following bug:https://github.com/alexanderzobnin/grafana-zabbix/issues/706

Actually it's so difficult to click on button, is like the zone to do click is too small and the most part of time is displaying popup.

Software versions:

Grafana : 6.1.4
Zabbix: 4.0.3
Zaabix-Plugin: 3.10.2

**Comment by alexanderzobnin** [comment]
Please, report this in the opened issue. What's a browser?
