### ISSUE TITLE
Query editor don't work in Grafana 2.5

### ISSUE THREAD

**Issue by StefanSa** [alexanderzobnin/grafana-zabbix#73]
Hi Alex
I use your last devel version and the latest grafana git version (v 2.2.0-pre1).
Now if i try to add an query (click on "+ Query"), nothing happens.
It is apparently query.editor.html not open, but i see this on website source code.

--snip--
"query":"app/plugins/datasource/zabbix/partials/query.editor.html
--snap-- 

any idea ?
thx / spasiba.

Stefan

**Comment by alexanderzobnin** [comment]
Hello! Can you try last Grafana 2.1 version (2.1.3)?

**Comment by alexanderzobnin** [comment]
I have similar bug in latest version built from sources.

**Comment by alexanderzobnin** [comment]
@StefanSa try to use [fix-query_editor_in_2.5](https://github.com/alexanderzobnin/grafana-zabbix/tree/fix-query_editor_in_2.5) branch.

**Comment by StefanSa** [comment]
Hi  Alex,
yes this should work.
spasiba
