### ISSUE TITLE
Single stat on zabbix 4.2.1

### ISSUE THREAD

**Issue by PunkSp** [alexanderzobnin/grafana-zabbix#730]
**Describe the bug**
Im trying to get all problems and count them on the single stats

**Expected behavior**
Before the update to zabbix 4.2.1, I could get all triggers together, and hadnt to choose the column. Now we have columns for each severity.
On the previous version the triggers were consoidated, and if I had to choose just one severity, I could do it in metrics.

**Screenshots**
![image](https://user-images.githubusercontent.com/32205091/56659533-c5f5c000-6673-11e9-92cb-27cb3463a1b9.png)

I took a look on http://play.grafana-zabbix.org, and the field column is stat:
![image](https://user-images.githubusercontent.com/32205091/56660439-e6bf1500-6675-11e9-9b21-c6098d1d2e15.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.4.2  | 4.2.1  | 3.10.2               |

**Comment by alexanderzobnin** [comment]
This duplicates #726

**Comment by heshammhafez** [comment]
Hello PunkSp

Did you manage to fix it ? Because I edit responseHandler.js and same issue atill exist 😯
