### ISSUE TITLE
"Direct DB connection" config don't stick on 3.10.2

### ISSUE THREAD

**Issue by fernandolcx** [alexanderzobnin/grafana-zabbix#731]
**Describe the bug**
The datasource validates and saves successfully, but when refreshing the page the "Enable" switch from Direct DB connection appears turned off.

**Screenshots**
![image](https://user-images.githubusercontent.com/38504809/56807585-aee6d780-6805-11e9-8e7f-fc145580c274.png)

saved. 
Then F5:

![image](https://user-images.githubusercontent.com/38504809/56807631-c920b580-6805-11e9-9078-52ef314f1ff0.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.1.4  | 4.2.1  | 3.10.2               |

**Comment by and111016** [comment]
Confirm same issue
Grafana - Grafana v5.4.2 (d812109)
Zabbix - 3.4.15
Grafana-Zabbix Plugin - 3.10.1, 3.10.2

On 3.10.0 work

**Comment by Kaeltis** [comment]
Can confirm the same with MySQL

Grafana - v6.1.6 (cf9cb45)
Zabbix - 4.2.1.
Grafana-Zabbix Plugin - 3.10.2

**Comment by DrKomtur** [comment]
same for PSQL
Grafana - v6.0.2
Zabbix - 4.0.7
Plugin - 3.10.2

**Comment by anthonysomerset** [comment]
same for InfluxDB FYI

**Comment by silvermoon-h** [comment]
Yes, some issue.
Grafana - v6.1.6
Zabbix - 4.2.1
grafana-zabbix - 3.10.2

**Comment by Positronico** [comment]
Same here. Noticed when trying to add the same DB connection on a second Org. The first one (create a while ago) is still working.

Grafana - v6.1.6
Zabbix - 4.2.1
grafana-zabbix - 3.10.2

**Comment by anthonysomerset** [comment]
so i have a temp workaround that seems to work

manually edit the row in the `data_source` table and edit the `json_data` column

*NOTE*: the zabbix api user/pass is in this field so only amend the `dbConnectionDatasourceName` and 
`dbConnectionRetentionPolicy` fields as required

example (mysql/PGSQL):
```
{"addThresholds":false,"alerting":false,"alertingMinSeverity":3,"dbConnectionDatasourceId":null,"dbConnectionEnable":true, "dbConnectionDatasourceName":"Zabbix-PostgreSQLTSDB", "dbConnectionRetentionPolicy":"","disableReadOnlyUsersAck":true,"keepCookies":[],"oauthPassThru":false,"password":"xxxxxxxxx","trends":true,"trendsFrom":"7d","trendsRange":"4d","username":"xxxxxxxxx","zabbixVersion":4}
```

InfluxDB:
```
{"addThresholds":false,"alerting":false,"alertingMinSeverity":3,"dbConnectionDatasourceId":null,"dbConnectionEnable":true, "dbConnectionDatasourceName":"Zabbix-InfluxDB", "dbConnectionRetentionPolicy":"SomeRetentionPolicy","disableReadOnlyUsersAck":true,"keepCookies":[],"oauthPassThru":false,"password":"xxxxxxxxx","trends":true,"trendsFrom":"7d","trendsRange":"4d","username":"xxxxxxxxx","zabbixVersion":4}
```

Then you can view the data source in the GUI to verify the change worked just don't save it again via the GUI

**Comment by tiago-cruz-movile** [comment]
Same thing here, env:

- zabbix-server-mysql-4.0.5-1.el7.x86_64
- grafana-6.2.0-1.x86_64
- zabbix plugin for grafana version 3.10.2

**Comment by Rikbiz** [comment]
Same while testing with InfluxDB (with Effluence):
Zabbix 4.0
Grafana 5.4.2
Plugin 3.10.2

**Comment by tolsadus** [comment]
What the feature broken, or just the UI? Thanks for the quick fix! 👍
