### ISSUE TITLE
Grafana 6.2 beta panels unable to access Zabbix server

### ISSUE THREAD

**Issue by jedd** [alexanderzobnin/grafana-zabbix#741]
**Describe the bug**
Grafana 6.2 BETA fails to obtain metrics from Zabbix 

This was after upgrading Grafana server from 6.1.0-beta1 (working fine) to 6.2.0 beta1 (released 2019-05-08)

Red alert pop-ups whenever page loads, or when generating a new panel using a Zabbix datasource.

Text of error message:

> zabbix_mtm_dev plugin failed
> Error: Fetch error: 404 Not Found Instantiating http://internal-host-name/public/app/core/utils/datemath
> Loading http://internal-host-name/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js
> Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.2.0-beta1   | 3.4.7  | 3.10.2                 |

**Comment by sboyd67** [comment]
jedd - We have the same issue.  We have Grafana 5.1.3, Zabbix 3.4.15 and Plugin 3.10.3.  We've tried clearing the cache and we made sure that we used the grafana-cli to install.  Not sure where to look.

**Comment by jedd** [comment]
I ended up reverting, waited for the non-beta released, and then did an upgrade that had no such issues -- I'm now running:  Zabbix 3.4.7  with  Grafana  6.2.4

**Comment by jedd** [comment]
Issue resolved by reverting, and subsequently jumping to Grafana 7 / Zabbix 5 / Plugin 4.0
