### ISSUE TITLE
Show events OK in trigger panel doesn't work (v.3.10.2)

### ISSUE THREAD

**Issue by pikaniou** [alexanderzobnin/grafana-zabbix#742]
**Describe the bug**

If I select Show elements "ALL" or "OK" in trigger panel, i don't have any data in this panel.

**Describe the solution you'd like**

If I select Show "All" or "OK" in the trigger panel, it shows all events (Ok or no ok)

**Screenshots**
if select show "all" or "OK"

![image](https://user-images.githubusercontent.com/50659391/57767164-07283f80-7709-11e9-9c42-128345c5dd55.png)

if select show "problem"

![image](https://user-images.githubusercontent.com/50659391/57767414-93d2fd80-7709-11e9-806c-3645fc55622d.png)

plugin version 3.10.2, Grafana 6.1.6

**Comment by xiaoxue999** [comment]
Same as me,see the screen
![1](https://user-images.githubusercontent.com/22721577/58605598-efd18080-82ca-11e9-9fd9-48bf3ef30563.png)
![2](https://user-images.githubusercontent.com/22721577/58605605-f4963480-82ca-11e9-98c9-327661ebce5b.png)

**Comment by fluffy-fox** [comment]
+1

**Comment by atroxix** [comment]
The same here with v3.10.3 and Grafana 6.2.5.

**Comment by atroxix** [comment]
I now upgraded Zabbix to 4.2.5, but "OK" events are still not shown.

**Comment by atroxix** [comment]
I replaced the plugin with version 3.9.1 in Grafana 6.2.5 and now the statuses show up OK. The problem with the old plugin version is though that dashboards cannot be configured.

It seems I'll need to stick with the old plugin and old Grafana for now :(

**Comment by atroxix** [comment]
I've upgraded Grafana to 6.3.2 and the plugin to 3.10.4 on my test system. I managed to see "OK" status for one of my applications, but that was only for a brief period of time.

I've tried all kinds of configurations, importing, creating from scratch etc. Does not work still.

**Comment by bingo-the-pyro** [comment]
I'll add my +1 to this:
OK shows Resolved
Problem shows Problems
All shows less Problems than problems does and no Resolved
Zabbix 4.2.1 / Grafana 6.4.3 / Plugin 3.10.4

**Comment by pikaniou** [comment]
problem still present in version of Grafana 6.7.1, Zabbix 4.4.6 and Plugins 3.11.0.

**Comment by alexanderzobnin** [comment]
@pikaniou Did you try different time ranges?

**Comment by pikaniou** [comment]
@alexanderzobnin it's OK with different time ranges. Sorry i hadn't tried that. 
Thanks for your help. I close the post.
