### ISSUE TITLE
Cannot read property 'groupid' of undefined

### ISSUE THREAD

**Issue by mikhailov** [alexanderzobnin/grafana-zabbix#75]
Once we migrated from Apache HTTPD to Nginx, the response time reduced dramatically but it provided a side effect probably because of data comes over too fast now. Another reason it may happen due to certain number of rows 10+ (this issues is not happening for 5-10 rows).

![screen shot 2015-08-28 at 10 46 22 am](https://cloud.githubusercontent.com/assets/14601/9543814/c82c69cc-4d73-11e5-8964-1a47e278b86d.png)
![screen shot 2015-08-28 at 10 46 37 am](https://cloud.githubusercontent.com/assets/14601/9543815/ca3167d6-4d73-11e5-9492-305ac68c852d.png)

**Comment by alexanderzobnin** [comment]
Looks like a bug.

**Comment by mikhailov** [comment]
it's funny that to make it work we returned back to Apache for a while...

**Comment by alexanderzobnin** [comment]
Can you show api responses from nginx?

**Comment by mikhailov** [comment]
Sorry, it was **Error connecting to database: Too many connections** issue, Nginx is too fast!!!

**Comment by alexanderzobnin** [comment]
Ok. I also want to try to migrate Zabbix frontend to nginx.
