### ISSUE TITLE
Acknowledge button doesn't actually add an ACK

### ISSUE THREAD

**Issue by hluaces** [alexanderzobnin/grafana-zabbix#750]
**Describe the bug**

Adding an ACK to any opened Zabbix alert is not adding the ACK.

Clicking the ACK button shows a dialog box to enter the ACK message. After typing it and clicking 'Acknowledge' the dialog is hidden but nothing happens.

**Expected behavior**
Adding an ACK on the plugin should add an ACK with the same message on Zabbix.

**Network data**

Request headers:

```
POST /api/datasources/proxy/1 HTTP/1.1
Host: my.redacted.domain.example.com:3000
Connection: keep-alive
Content-Length: 186
Accept: application/json, text/plain, */*
Origin: https://my.redacted.domain.example.com:3000
X-Grafana-Org-Id: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Content-Type: application/json
Referer: https://my.redacted.domain.example.com:3000/d/2BbYiHkWz/dashboard-correo-vps?orgId=1
Accept-Encoding: gzip, deflate, br
Accept-Language: es-ES,es;q=0.9,en;q=0.8
```

Request body:

```
{"jsonrpc":"2.0","method":"event.acknowledge","params":{"eventids":"4530885","message":"Héctor Luaces (Grafana): TEST ACK.","action":0},"id":1,"auth":"3f03f394ce8139bcc0e44289648b4ee9"}
```

Response headers:

```
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 1000
Content-Length: 56
Content-Type: application/json
Date: Wed, 05 Jun 2019 11:11:06 GMT
Server: Apache
```

Response body:

```{"jsonrpc":"2.0","result":{"eventids":[4530885]},"id":1}```

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.4.2   | 4.0.8  | 3.10.2                 |

Tested on Mac, Linux and Windows machines on several browsers.

**Comment by PavelMikhailouski** [comment]
Think I figured the problem.

It is related to Zabbix API change between 3.x and 4.x versions. 
Once I press the Acknowledge button - the following request is being generated:
![image](https://user-images.githubusercontent.com/13793226/59179877-0c43a780-8b6c-11e9-82cc-0c30cfd83186.png)

And it would work for Zabbix 3.x:
https://www.zabbix.com/documentation/3.4/manual/api/reference/event/acknowledge
action
Possible values:
0 - (default) none;
1 - close problem.

But not for 4.x:
https://www.zabbix.com/documentation/4.2/manual/api/reference/event/acknowledge
action
Possible values:
1 - close problem;
2 - acknowledge event;
4 - add message;
8 - change severity. 

For some reason plugin picks the wrong value.
I believe this is the string responsible:
https://github.com/alexanderzobnin/grafana-zabbix/blob/bc889ffe30df7b2600eff058c32661408b840dfe/src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.js#L95

**Comment by PavelMikhailouski** [comment]
### SOLUTION THAT WORKED FOR ME

On the plugin upgrade, all datasources have been updated automatically to use 4.x version by default. However, their config remained 'unapplied' or something. So I end up just 'applying' their config manually.

**Go to Datasources > your Zabbix datasource > Press 'Save & Test'**
This did the trick, acknowledges started to work.


Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
6.2.1 | 4.2.3 | 3.10.2

**Comment by hluaces** [comment]
Wow, that was it. Worked perfectly, which is weird because I toggled the API version from 3.x to 4.x to do tests before opening this issue.

Nevertheless, it is fixed. A user of mine had to refresh the browser caché for it to work.

Thanks @PavelMikhailouski . I'm closing this.
