### ISSUE TITLE
Max Data Points setting not available ?

### ISSUE THREAD

**Issue by Sean1e** [alexanderzobnin/grafana-zabbix#76]
Hi - We are using Grafana version 2.1.3 and do not see the 'Max Data Points' setting - Was this feature removed or is it incompatible with Grafana v 2.1.3 ?
![screen shot 2015-08-28 at 13 17 16](https://cloud.githubusercontent.com/assets/8726676/9546075/7aee8816-4d87-11e5-8fa7-526a7f0a3433.png)

**Comment by alexanderzobnin** [comment]
Hello! No, this feature present in this version. Try to clear browser cache.

**Comment by Sean1e** [comment]
Hi - I see the setting for Max Data Points when I use Graphite as a datasource but not when the datasource for a graph is set to Zabbix.

**Comment by alexanderzobnin** [comment]
This feature depend of datasource. Are you see Max Data Points parameter at [Grafana-Zabbix demo site](http://play.grafana-zabbix.org/)?

**Comment by Sean1e** [comment]
Hello - I see the setting for Max Data Points when I use Graphite as a datasource on my server - I don't know a signon at Grafana-Zabbix that allows me to 'edit' a graph so can't confirm whether I see it there.
Your reply "This feature depend of datasource" answers my question so don't spend more time on this.

Thanks !

**Comment by alexanderzobnin** [comment]
@Sean1e Grafana-Zabbix also have Max Data Points settings:

![2015-09-07 14-12-06 grafana - max data points - google chrome](https://cloud.githubusercontent.com/assets/4932851/9715602/902cc734-556a-11e5-9d04-a1da860a6c9f.png)

**Comment by Sean1e** [comment]
Just saw your response above re. Max Data Points when using Grafana-Zabbix - Then the question is why do I not see Max Data Points when I use the grafana-zabbix plugin ?  Do you see Max Data Points when you use the plugin ?

The reason I'm asking is that MySQL seems to be the the main culprit in slowing Zabbix down & I'm hoping being able to set Max Data Points would speed things up.

Thanks & Thanks for your plugin !
Séan

**Comment by mikhailov** [comment]
I have got the same problem, I tried both of sources: Graphite and Zabbix, see the HTML source please:

**Graphite**

![screen shot 2015-09-10 at 5 34 40 pm](https://cloud.githubusercontent.com/assets/14601/9794323/6426064e-57e2-11e5-9feb-a8723e5988b6.png)

**Zabbix**

![screen shot 2015-09-10 at 5 35 05 pm](https://cloud.githubusercontent.com/assets/14601/9794325/66f33752-57e2-11e5-9633-df07428e8162.png)

**Comment by mikhailov** [comment]
we tried latest **grafana-zabbix** from master branch, sorry, the same...

**Comment by alexanderzobnin** [comment]
Which Grafana version are you use?

**Comment by Sean1e** [comment]
Hi Alexander,

We changed the value of "limitmetrics" in plugin.json and restarted grafana-server and "Max Data Points" was displayed in Grafana for a Zabbix datasource !

As far as I remember we changed "limitmetrics" to 50 before the restart.

So - I looks as if "Max Data Points" became available after we changed the default value for "limitmetrics" in plugin.json.

Thanks for your efforts & the plugin - This issue can be closed as far as I'm concerned.

Séan

**Comment by alexanderzobnin** [comment]
@Sean1e It's a strange behavior. I need make some tests with it.

**Comment by mikhailov** [comment]
Within a bit strange behavior we noticed unexpected CPU spike on Zabbix machine where we host its MySQL database as well. I guess that may happen due to large API response from Zabbix API (several megabytes in size) if we query metrics for 7 days period instead of 2-4 hours. I wonder is that possible to perform downsampling on Zabbix API server side instead? 

This feature incorporated with [Graphite 0.9.13](http://docs.grafana.org/installation/performance/):


> Graphite 0.9.13 adds a much needed feature to the JSON rendering API that is very important for Grafana. If you are experiencing slow load & rendering times for large time ranges then it is most likely caused by running Graphite 0.9.12 or lower.

> The latest version of Graphite adds a maxDataPoints parameter to the JSON render API. Without this feature Graphite can return hundreds of thousands of data points per graph, which can hang your browser. Be sure to upgrade to 0.9.13.

Grafana's author has started the project because figured out the performance issue, see [the issue](https://github.com/grafana/grafana/issues/738):

> The performance in Grafana even over very large timespans can be as good over even better than Graphite server side rendered PNG. This was a critical thing that I made sure was solved even before I started working on Grafana last December.

> The reason client side rendering for graphite has been severely crippled with slow performance and browser crashes for large timespans was solved last summer, via this issue #170 . The reason client side rendering was slow was not because client sider rendering was slow but **because the graphite json api returned every datapoint to the browser** (which could be many many megs of datapoints when viewing large time spans). The maxDataPoints feature make sure that the same consolidation that happens for the PNG rendering happen for the json rendering, that is that only points that are drawn in the graph are returned.

**Comment by nucleusv** [comment]
@mikhailov, why don't you use trends for such large interval, zabbix web frontend always use trends to visualize data more than 3-4 days?

**Comment by alexanderzobnin** [comment]
Indeed, Graphite have a very useful feature which allows reduce data size coming from server using points consolidation by time period (1 hour, 1 day, etc). Unfortunately, Zabbix hasn't nothing like this feature. But I think it is possible to create API patch for this. Also try to use Trend API Patch for long periods, it's very helpful and reduces load to Zabbix database and Grafana.

**Comment by mikhailov** [comment]
Alex, that's great to know! Is that possible to use grafana-zabbix plugin with Trend API source?

**Comment by alexanderzobnin** [comment]
See https://github.com/alexanderzobnin/grafana-zabbix/wiki/Installation#trends-support
