### ISSUE TITLE
Datasource Direct DB Connection not staying enabled

### ISSUE THREAD

**Issue by jacobs817** [alexanderzobnin/grafana-zabbix#768]
**Describe the bug**
When modifying the datasource to enable Direct DB Connection, I can select the MySQL database, and when saving it shows successful, but when going back into the settings, it shows the Direct DB is not enabled.

**Expected behavior**
Direct DB Connection showing enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/22901376/60926381-e80edf80-a26b-11e9-9cdb-d5668a429cfb.png)
![image](https://user-images.githubusercontent.com/22901376/60926392-f230de00-a26b-11e9-892d-8ea26b286f9b.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.2.5   | 4.2.3  | 3.10.2                 |

**Comment by LukyGregor** [comment]
I have the same problem.

**Comment by tolsadus** [comment]
Same here.

**Comment by alexanderzobnin** [comment]
Duplicated #731
