### ISSUE TITLE
Singlestat and triggers not working after update Zabbix server

### ISSUE THREAD

**Issue by Nekit9991** [alexanderzobnin/grafana-zabbix#769]
**Describe the bug**
After update my Zabbix server from 4.0.6 to 4.0.10 all singlestat and different elments on dashboard do not return any value

**Screenshots**

![Zabbix Server Dashboard - Grafana - Google Chrome 2019-07-11 15 55 44](https://user-images.githubusercontent.com/49268371/61052923-1b30aa80-a3f5-11e9-9656-844aa106237c.png)
![Main - Grafana - Google Chrome 2019-07-11 16 01 59](https://user-images.githubusercontent.com/49268371/61053053-69de4480-a3f5-11e9-97ae-7e5c820443d2.png)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 6.2.5   | 4.0.10  | 3.10.2               |

**Comment by silveraignacio** [comment]
Please, check this topic: https://github.com/alexanderzobnin/grafana-zabbix/issues/733 and this other one:https://github.com/alexanderzobnin/grafana-zabbix/issues/726

Another user has a similar issue with previous plugin version. In version  3.10.3 it seems to be fixed

**Comment by Nekit9991** [comment]
version 3.10.3 fix it)
