### ISSUE TITLE
HTTP settings and Zabbix API details don`t display in Grafana 2.1.3

### ISSUE THREAD

**Issue by alyan2008** [alexanderzobnin/grafana-zabbix#77]
Hello 

I have installed grafana 2.1.3 and was trying to add new source, but currently I can`t see additional settings for Zabbix (HTTP settings and Zabbix API). Screen has been attached.
![screen1](https://cloud.githubusercontent.com/assets/7196207/9578348/aa0197ee-4ff1-11e5-9671-dd40b50939b7.JPG)
![version](https://cloud.githubusercontent.com/assets/7196207/9578362/c57dd104-4ff1-11e5-8f90-807b745a9816.JPG)

**Comment by alexanderzobnin** [comment]
Hello! Please, check "partials" paths in the `plugin.json` file:
```
"partials": {
    "config": "app/plugins/datasource/zabbix/partials/config.html",
    "query": "app/plugins/datasource/zabbix/partials/query.editor.html",
    "annotations": "app/plugins/datasource/zabbix/partials/annotations.editor.html"
  },
```

**Comment by alyan2008** [comment]
Thanks a lot, it works.
