### ISSUE TITLE
Fetch error: 404 Not Found Instantiating

### ISSUE THREAD

**Issue by sboyd67** [alexanderzobnin/grafana-zabbix#775]
I've looked at the resolutions for the similar issues and we've cleared the cache and updated the pulgin using the CLI.  

**Describe the bug**
We've just started getting an error when we click on add a data source, type in the name and select Zabbix as the Data Source type.  

**Expected behavior**
Should be able to complete the form to create a new Zabbix data source.  

**Screenshots**

![Plugin error](https://user-images.githubusercontent.com/3776462/62486483-6c7e5080-b78d-11e9-82dc-71d748c269f8.PNG)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 5.1.3   | 3.4.15 | 3.10.3                 |

**Comment by jeffhirsch** [comment]
Seeing the same behavior on the same plugin version.

 Versions:
Grafana | Zabbix | Grafana-Zabbix Plugin
------------ | ------------- |  -------------
5.2.2 | 3.0.4 | 3.10.3

**Comment by sboyd67** [comment]
I just wound up upgrading Grafana to 6.x  That fixed the issue.

**Comment by jeffhirsch** [comment]
Yeah that seems to be what is reccomended on some older tickets like #574. This ticket can probably be closed.

**Comment by wuyanming** [comment]
我也遇到了这个问题

**Comment by TiagoTT** [comment]
I have the same problem with Grafana version 5.4.4 and Grafana-Zabbix Plugin version 3.10.3.
I found that downgrading to Grafana-Zabbix Plugin version 3.10.2 would "fix" this problem.
The issue seems related to the usage of `@grafana/ui` introduced in https://github.com/alexanderzobnin/grafana-zabbix/commit/4346e133652ff809d1b3856bab2a8d487272724a
The browser console shows the following error message:
```
Error: Fetch error: 404 Not Found
  Instantiating https://metrics.example.com/public/@grafana/ui
  Loading https://metrics.example.com/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js
  Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module
Stack trace:
rt</<@https://metrics.example.com/public/build/vendor.469095018b321ef1da7c.js:52:59982
```

**Comment by nguyenan122** [comment]
> I have the same problem with Grafana version 5.4.4 and Grafana-Zabbix Plugin version 3.10.3.
> I found that downgrading to Grafana-Zabbix Plugin version 3.10.2 would "fix" this problem.
> The issue seems related to the usage of `@grafana/ui` introduced in [4346e13](https://github.com/alexanderzobnin/grafana-zabbix/commit/4346e133652ff809d1b3856bab2a8d487272724a)
> The browser console shows the following error message:
> 
> ```
> Error: Fetch error: 404 Not Found
>   Instantiating https://metrics.example.com/public/@grafana/ui
>   Loading https://metrics.example.com/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js
>   Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module
> Stack trace:
> rt</<@https://metrics.example.com/public/build/vendor.469095018b321ef1da7c.js:52:59982
> ```

Thanks. Use 5.4.4 with plugin_version 3.10.2 fine. I run on evn docker.

**Comment by wardhus** [comment]
`Zabbix plugin failed
Error: Fetch error: 404 Not Found Instantiating http://myhost/grafana/public/@grafana/runtime Loading http://myhost/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module`

Downgrading to 3.10.2 also worked for me.

CentOS 8.1
Grafana 6.2.2
Zabbix 5.0

**Comment by alexanderzobnin** [comment]
Recent plugin versions isn't compatible with old grafana unfortunately.
