### ISSUE TITLE
Problems panel editor broken in Grafana 6.3

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#778]
When trying to edit Problems panel, only a blank screen appears. JS console shows error `n.targets.map is not a function`.

This happened after switching from `dataFormats` property to `skipDataQuery` flag in `plugin.json`.
https://github.com/grafana/grafana/pull/16984

**Comment by Nastradamus** [comment]
Hi! same issue on grafana 6.5 with Zabbix plugin 3.10.4

**Comment by ywj198** [comment]
Hi! same issue on grafana 6.5 with Zabbix plugin 3.10.4

**Comment by eertul** [comment]
Hello Dear Alex, 
We can not upgrade Grafana because of this issue. Is there any update about this problem? 
Or if there is another blocker issue to solve this, we can try to make some noise about it if needed. :)
