### ISSUE TITLE
Zabbix Problems show events "All" displayes less events than "Problems"

### ISSUE THREAD

**Issue by ehusakovic1** [alexanderzobnin/grafana-zabbix#779]
**Describe the bug**
Zabbix problems panel, the Show events "All" option shows less events than Show events "Problems" option. It also doesn't show "OK" events.

**Expected behavior**
The Show events "All" should display more (probably "OK" evetns too) than Show events "Problems".

**Screenshots**

Show events "Problems":
<img width="927" alt="1 1" src="https://user-images.githubusercontent.com/54024796/62859581-db175d00-bcfd-11e9-99d8-8df4667295b0.png">

Show events "All"
<img width="930" alt="2 1" src="https://user-images.githubusercontent.com/54024796/62859637-f97d5880-bcfd-11e9-88b2-aa3e01c6ee34.png">

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.2.5   | 4.2  | 3.10.4                 |

**Comment by heyrod** [comment]
I guess the problem is somehow related to Time Picker of the dashboard. It should not override the Triggers Panel settings but it does.
