### ISSUE TITLE
Problems with periods with more than 7 days.

### ISSUE THREAD

**Issue by lsilvatux** [alexanderzobnin/grafana-zabbix#78]
Hi Alexander,

I have installed the plugin with my Zabbix 2.4.5 without trends Patch and Grafana 2.1.2. If I set a period with more than 7 days the graphs show only the first 7 days with no data on other days (see graph below)

![captura de tela 2015-09-02 22 32 23](https://cloud.githubusercontent.com/assets/6163327/9649017/708796f0-51c5-11e5-890a-5ed0ceafd54f.png)

Is the trends Patch mandatory for graphs with more than 7 days?

P.S. My history data has only 7 days and I don't change this value due performance issues on my Zabbix

**Comment by alexanderzobnin** [comment]
Hello! By default zabbix api can't work with trends data. For this reason you see data only for the 7 days. If you want to use large time periods, I reccomend to use trend patch. It also increase Grafana performans because trends contains less data then history and more situable for long periods.

**Comment by lsilvatux** [comment]
Thanks Alexander.

I put the trends patch and all worked well. The trends patch is mandatory for longer graphs.
