### ISSUE TITLE
Singlestat "no value" color

### ISSUE THREAD

**Issue by victorbcredidio** [alexanderzobnin/grafana-zabbix#781]
**Describe the bug**
Ok, I'll try to be really clear here: 
When I configure a singlestat panel to display informations on my Zabbix "Agent Ping" status it shows "1" or "no value". It was supposed to display 0. I can improvise that with Map Value (null -> 0), but while the status "1" appears GREEN, the 0 (or "no value") displays the default white color.

I tried to use the function "transformNull(0)" but it doesn't work. The value displayed is still "no value" (or 0, when using Map Value).

**Expected behavior**
While using the "transformNull(0)" function, it should change the value of "null" to "0", but it doesn't works. If that happened, I believe I could color the "0" value as "red" on my threshold.

**Screenshots**
**transformNull(0) not working**
![Screenshot from 2019-08-13 09-47-09](https://user-images.githubusercontent.com/50584783/62942993-d4e1b900-bdaf-11e9-84d0-4c5fc1b908d4.png)

**Threshold expected to display as Red**
![Screenshot from 2019-08-13 09-46-34](https://user-images.githubusercontent.com/50584783/62942994-d4e1b900-bdaf-11e9-8c99-660635730b7a.png)

**"null" value map to "DOWN"**
![Screenshot from 2019-08-13 09-46-23](https://user-images.githubusercontent.com/50584783/62942995-d4e1b900-bdaf-11e9-87b6-0af79d044326.png)

**Display of both status, from the same machine. 
I hoped that by using "transformeNull(0)", the value would be equal to "0", and the text would display "DOWN" with the color RED (as defined on the threshold above)**

![Screenshot from 2019-08-13 09-45-41](https://user-images.githubusercontent.com/50584783/62942996-d4e1b900-bdaf-11e9-8a7a-9afce276f6d2.png) ![Screenshot from 2019-08-13 09-45-31](https://user-images.githubusercontent.com/50584783/62942997-d57a4f80-bdaf-11e9-976c-357646686af0.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.2.5  | 4.2.5  |  3.10.3     |

**Comment by alexanderzobnin** [comment]
That's because zabbix returns empty array, so there's no 0 value. Not sure how to solve this.
