### ISSUE TITLE
Warning message when adding Alert

### ISSUE THREAD

**Issue by DonRichards** [alexanderzobnin/grafana-zabbix#782]
**Describe the bug**
The datasource does not support alerting queries

**Expected behavior**
Allows for alerts to be triggered.

**Screenshots**
![Screen Shot 2019-08-15 at 2 19 31 PM](https://user-images.githubusercontent.com/2738244/63116596-0a310700-bf68-11e9-9d81-ffc29aad7382.jpg)

**Network data**
N/A

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.3.2   | 4.2.5  | 3.10.2                 |

**Comment by t-moriyama** [comment]
I have the same issue.

#### Software versions

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
6.5.2 | 3.0.9 | 3.10.4

**Comment by alexanderzobnin** [comment]
It's not supported yet.
