### ISSUE TITLE
ZABBIX PROBLEM panel, time picker is not reflected

### ISSUE THREAD

**Issue by PCChew** [alexanderzobnin/grafana-zabbix#784]
I created a new Zabbix PROBLEM panel, when I try to filter the last 6hours only PROBLEM, instead it still shows old problems like 1 month, 2 months old. The time picker doesnt seem to filter properly. Screenshot as example.
![PROBLEM](https://user-images.githubusercontent.com/53600849/63312374-f4d72680-c333-11e9-91d2-4fd0f1b7f44f.png)

**Comment by alexanderzobnin** [comment]
It does work only if `Show events: All` selected.
