### ISSUE TITLE
sortSeries can't choose value to sort by

### ISSUE THREAD

**Issue by Zyzto** [alexanderzobnin/grafana-zabbix#786]
**Describe the bug**
+ sortSeries is sorting by name not by item value and there's no option to change

**Expected behavior**
+ ability to change sort value
+ there's nothing in wiki on sortSeries.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.2.5   | 4.2  | 3.10.4                 |

**Comment by alexanderzobnin** [comment]
It's by design. There's feature request for sorting by value #96
