### ISSUE TITLE
I can not install in zabbix for open-nti

### ISSUE THREAD

**Issue by tacip** [alexanderzobnin/grafana-zabbix#788]
Please help me. I can not install Plugin zabbix in Open-nti.
Please advise how to install it for me.

Thank you very much
Best regards James
![1](https://user-images.githubusercontent.com/53928128/64053560-1eeadd00-cbad-11e9-82b0-881ce34029bd.JPG)
![2](https://user-images.githubusercontent.com/53928128/64053561-1f837380-cbad-11e9-99d6-a5a21e6f2cb7.JPG)

**Comment by alexanderzobnin** [comment]
I don't know what is Open-nti and how to install plugin there.

**Comment by tacip** [comment]
Thank you very much
