### ISSUE TITLE
no graph show , it  hints "no datapoints "

### ISSUE THREAD

**Issue by R1hug0** [alexanderzobnin/grafana-zabbix#79]
zabbix 2.4.6
grafana  2.1.3
I choose a project to show ， it  show "no datapoints returned from metric query"。
I have been configured it  with User’s Guide ,and  test datasource it show successful.
can u help me .

**Comment by alexanderzobnin** [comment]
Can you attach screenshot of query editor?

**Comment by R1hug0** [comment]
pls see the attachment 
![nodata](https://cloud.githubusercontent.com/assets/8827342/9754310/51bc0e4c-56fa-11e5-9a04-203dc83bed90.png)
![datasource](https://cloud.githubusercontent.com/assets/8827342/9754314/5af53452-56fa-11e5-8c52-ebdbc0ffc0b7.png)

**Comment by alexanderzobnin** [comment]
Sorry. Change `Use trends from` parameter for default `7d`.

**Comment by alexanderzobnin** [comment]
Are you update a plugin or have a new installation?

**Comment by R1hug0** [comment]
This is the first time I've installed and I set the parameters like this.
  "trends": true,
  "trendsFrom": "7d",

**Comment by alexanderzobnin** [comment]
In Grafana 2.1 I realize plugin configuration via configuration page. In master branch it has this bug. You can also use code from develop branch for more features and bug fixes. Or just set `Use trends from` at configuration page to 7d.

**Comment by alexanderzobnin** [comment]
But better way is use [develop](https://github.com/alexanderzobnin/grafana-zabbix/tree/develop) branch where this bug was fixed.

**Comment by R1hug0** [comment]
I'll try to follow your advice,tks!

**Comment by alexanderzobnin** [comment]
This is bug from issue #68. I published new [release](https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v2.1.0-rc1) (2.1 RC1) where this bug was fixed.

**Comment by R1hug0** [comment]
Nice, thank  you for your help  ,I have solved the problem and now it looks good.
