### ISSUE TITLE
 Look at my mistake.

### ISSUE THREAD

**Issue by qianxiaodewo** [alexanderzobnin/grafana-zabbix#791]
The way I install it is:
grafana-cli plugins install alexanderzobnin-zabbix-app
Configure the front-end page display after installation:
![image](https://user-images.githubusercontent.com/25760013/64223345-1e807800-cf06-11e9-8b5a-67c7cf7220db.png)

The installation catalogue of my equipment is as follows:
![image](https://user-images.githubusercontent.com/25760013/64223363-3f48cd80-cf06-11e9-901d-2d1ff9d8ebb6.png)

**Comment by isaqueprofeta** [comment]
`chown -R grafana:grafana /var/lib/grafana/plugins`

**Comment by alexanderzobnin** [comment]
This is because of version incompatibility.
