### ISSUE TITLE
[Question] Question with backend plugin for grafana

### ISSUE THREAD

**Issue by maxlehot1234** [alexanderzobnin/grafana-zabbix#792]
Hi,

I just want to know if you have an ETA or where I can download  the backend plugin for grafana so I can use the alert thing of grafana.
It looks much better than Zabbix and really easy to find everything with the correct dashboard.

Thanks again for everything and have a nice day/night

**Comment by alexanderzobnin** [comment]
Hi! Not sure yet, haven't started to work on the backend plugins. Keep tracking issues, I'll create some for the backend work.
