### ISSUE TITLE
Add data source error

### ISSUE THREAD

**Issue by zemanoel** [alexanderzobnin/grafana-zabbix#795]
Good Morning!
I have a problem adding zabbix database, the following error message appears:

****
![image](https://user-images.githubusercontent.com/50956353/65045712-ae2a1b80-d935-11e9-861e-19221439d6be.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 4.1.1      | 4.0.12  | 3.10.4 |

If anyone can help me, thank you.

Thanks.

**Comment by alexanderzobnin** [comment]
Upgrage your Grafana please.
