### ISSUE TITLE
Execlude Host Groups in "Zabbix Problems" Panel

### ISSUE THREAD

**Issue by Unbr8kable** [alexanderzobnin/grafana-zabbix#796]
**Is your feature request related to a problem? Please describe.**
I want to execlude Host Groups in the Zabbix Problems Panel like on the original Zabbix Dashboard "Problems" Widget. 

![image](https://user-images.githubusercontent.com/34042223/65251308-6521c500-daf7-11e9-9556-bab2f127466e.png)

Is this option already implemented? When yes how can I execlude Host Groups?

**Comment by Unbr8kable** [comment]
So I´ve tested it now with regex (I did not think about it before). 

This is my regex pattern:

`/^((?!Discovered hosts)(?!HostGroup_1)(?!Host Group 2).)*$/`

These 3 Hostgroups i want that these aren´t shown. 
But it does not work. 

Does not support the plugin this function?

**Comment by alexanderzobnin** [comment]
I don't know what's a reason. I tested your regex and in works pretty good to me:
```regex
/^((?!Linux servers)(?!Backend).)*$/
```
returns all hosts belong any group except Backend or Linux servers.
