### ISSUE TITLE
Zabbix text items

### ISSUE THREAD

**Issue by grantemsley** [alexanderzobnin/grafana-zabbix#80]
Along the same line as #72, I would love to see a custom panel added for text based zabbix items, so I can show them on my dashboards.

**Comment by grantemsley** [comment]
Nevermind, this was recently added, I just had a slightly outdated version!

**Comment by xiaoping378** [comment]
where are they? can you show the link ?
thanks

**Comment by alexanderzobnin** [comment]
@xiaoping378 Download latest release. And then it will be available in query editor.

![2015-09-16 21-55-22 grafana - text metrics - google chrome](https://cloud.githubusercontent.com/assets/4932851/9915092/c220e248-5cbd-11e5-95b5-d3737b22f3ea.png)

**Comment by xiaoping378** [comment]
Thanks， Got it.
