### ISSUE TITLE
Query with variable in Item returns no values

### ISSUE THREAD

**Issue by prokopenkopn** [alexanderzobnin/grafana-zabbix#805]
Grafana version 6.0. Zabbix plugin version 3.10.4
The Item I try to query from Zabbix has the following name: `p_ts[_TEST_pctfree]`.
Query with `Item: p_ts[_TEST_pctfree]` works OK.
But if I try to use a variable $tablespace in `Item: p_ts[_[[tablespace]]_pctfree]`,
the query does not work (returns "no value"). The variable has correct value "TEST". I can see it in the panel Title (Tablespace $tablespace %free). 
What may be the problem? Please, give some hint to troubleshoot this problem.

**Comment by alexanderzobnin** [comment]
Not sure what's a problem, maybe space in the value or something like this.

**Comment by prokopenkopn** [comment]
Could you, please, confirm that Zabbix plugin supports template variables in the middle of the item name? 
And is there any way to trace the problem? 
Query Inspector just hangs in this example.

**Comment by alexanderzobnin** [comment]
Yes, it does support it. It seems, I've found a reason. If query contains variable, plugin wraps it into the regex:
https://github.com/alexanderzobnin/grafana-zabbix/blob/916c570664b2752b8c5de8a43449299b9a97ec53/src/datasource-zabbix/datasource.js#L705-L716

So the problem is `[` and `]` signs. Try to convert your query to regex and escape theese characters:
```regex
/^p_ts\[_[[tablespace]]_pctfree\]$/
```

**Comment by prokopenkopn** [comment]
Yes! Thank you very much! 
This query /^p_ts\[_[[tablespace]]_pctfree\]$/  works fine.
Now I have fixed some panels.... But one still does not work.
This one (with no variable): /^inst\[test_uptime\]$/ - works. "test" is and db instance name.
But if I replace it with variable inst (and inst has value 'test'): /^inst\[[[inst]]_uptime\]$/ - does not work.
