### ISSUE TITLE
zabbix authentication is HTTP

### ISSUE THREAD

**Issue by yki001** [alexanderzobnin/grafana-zabbix#81]
can you help me solve this problem?thank you.
![grafana](https://cloud.githubusercontent.com/assets/4189302/9897442/047b3f1e-5c7b-11e5-9a95-ba02536cf025.png)

**Comment by alexanderzobnin** [comment]
Ok, I will try to resolve it.

**Comment by alexanderzobnin** [comment]
Are you enabled basic auth in datasource configuration? 

![2015-09-16 14-57-43 grafana - grafana-zabbix demo - google chrome](https://cloud.githubusercontent.com/assets/4932851/9904032/7835fa40-5c83-11e5-8cc3-1e6c243952e9.png)

**Comment by yki001** [comment]
I've tried this, but the report still does not have permission

**Comment by yki001** [comment]
My understanding is that this feature is used to make a certification nginx front-end, but by my zabbix http authentication, not a case.

**Comment by alexanderzobnin** [comment]
I read Zabbix API docs and it says:
> When using HTTP authentication, the user name in the API request must match the one used in the Authorization header. The password will not be validated and can be omitted.

But I use this header if Basic Auth enabled:
```
if (this.basicAuth) {
    options.headers.Authorization = this.basicAuth;
}
```
I will try to configure my Zabbix development server and get more details.

**Comment by yki001** [comment]
I have a script writed by python,looks like this:
        self.auth = 'Basic ' + string.strip(base64.encodestring("Admin"+ ':' + "zabbix"))
        self.header = {'Content-Type':'application/json-rpc','Authorization':self.auth}
It works good.May be can help you.

**Comment by alexanderzobnin** [comment]
Is this script working with Zabbix API?

**Comment by yki001** [comment]
Yep

**Comment by yki001** [comment]
This script use Authorization's auth is base64 encrypted user name and password,can you try it.

**Comment by alexanderzobnin** [comment]
Also try to use `direct` Access insted `proxy`. May be problem in backend.

**Comment by yki001** [comment]
![qq 20150921095014](https://cloud.githubusercontent.com/assets/4189302/9984222/7ea62d3e-6046-11e5-8a84-7145b06cfe8d.png)
![qq 20150921095052](https://cloud.githubusercontent.com/assets/4189302/9984223/7f5d1b34-6046-11e5-9a94-950a12c3fd52.png)
![qq 20150921095324](https://cloud.githubusercontent.com/assets/4189302/9984244/c914e446-6046-11e5-91e5-1b21d3036d1b.png)

**Comment by nucleusv** [comment]
@yki001, 
https://github.com/alexanderzobnin/grafana-zabbix/wiki/Installation

read note for zabbix 2.2 or less

**Comment by yki001** [comment]
my zabbix is 2.4.6,I will try it again,thank you for you help

**Comment by nucleusv** [comment]
@yki001 
show  first 20 lines of  api_jsonrpc.php

**Comment by yki001** [comment]
if ($_SERVER["PHP_AUTH_USER"] != "Admin" || $_SERVER["PHP_AUTH_PW"] != "zabbix") {
        header('HTTP/1.0 403: Permission denied');
        return;
}

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Max-Age: 1000');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
        return;
}


require_once dirname(__FILE__).'/include/func.inc.php';
require_once dirname(__FILE__).'/include/classes/core/CHttpRequest.php';

$allowed_content = array(
        'application/json-rpc' => 'json-rpc',
        'application/json' => 'json-rpc',
        'application/jsonrequest' => 'json-rpc',
);
$http_request = new CHttpRequest();
$content_type = $http_request->header('Content-Type');
$content_type = explode(';', $content_type);
$content_type = $content_type[0];

**Comment by nucleusv** [comment]
First of all, how these lines
if ($_SERVER["PHP_AUTH_USER"] != "Admin" || $_SERVER["PHP_AUTH_PW"] != "zabbix") {
header('HTTP/1.0 403: Permission denied');
return;
}

have get into your code?

There is no such code in version 2.4.6 from rpm.

**Comment by xiaoping378** [comment]
I  met the similar issue, But .... due of my wrong user/passwd.

**Comment by yki001** [comment]
Okay, I'll test it again.Thank you.I'll tell you the latest developments.
