### ISSUE TITLE
function editor is not working

### ISSUE THREAD

**Issue by dataniard** [alexanderzobnin/grafana-zabbix#810]
Function editor is not working in 6.4.1. Nor Function Label neither buttons appears.

grafana 6.4.1
plugin 3.10.4
![imagen](https://user-images.githubusercontent.com/49927034/66247090-9d411e80-e719-11e9-95dc-509ecdc44f88.png)

It worked on previous versions
grafana 6.3.5
plugin 3.10.4
![imagen](https://user-images.githubusercontent.com/49927034/66247127-fe68f200-e719-11e9-80e5-cc68a35e0229.png)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.4.1   | 4.0.1  | 3.10.4                  |

**Comment by loganobrien** [comment]
Experiencing the same issue on Grafana v6.4.2 (commit: 443a0ba) with Plugin v3.10.4.

**Comment by alexanderzobnin** [comment]
Yes, this is Grafana 6.4-related only thing. Investigating and preparing a fix.

**Comment by guyhom** [comment]
Hello, Thank you for having this bug fixed ! 
Do you think you can release the 2 debugs (this one, #810, and also #813 about annotations) in a hotfix release before 3.11 ? 
It would be very helpful in my case, we use extensively these functions in our Grafana instances, and I must admit not being able to edit them is quite uncomfortable at the moment.

**Comment by alexanderzobnin** [comment]
@guyhom I will try to prepare release in next few weeks. I won't make patch release because I have few features implemented, but I will rather rearrange milestone.

**Comment by maxlehot1234** [comment]
Anything on this? @alexanderzobnin  Almost 3 weeks now ;P :)

**Comment by mammuthus** [comment]
Still looking forward to it :)

**Comment by filipenanclarez** [comment]
Still problem here. I have Grafana v6.6.0 and this problema realy uncomfortable in panel with lot of functions.
