### ISSUE TITLE
no data error ??!!

### ISSUE THREAD

**Issue by majid-darvishfard** [alexanderzobnin/grafana-zabbix#811]
**Describe the bug**
why i get NO DATA message in grafana  dashboards??

![image](https://user-images.githubusercontent.com/46423765/66258170-a5976900-e7ae-11e9-974c-9a5346174444.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.4.1  | 4.2  | 3.10.4                |

**Comment by majid-darvishfard** [comment]
i test with zabbix versiom 3 , it's okay !!!

why zabbix version 4.2 is NOT OKAY ?????

**Comment by alexanderzobnin** [comment]
I don't know, it's probably Zabbix API issue.
