### ISSUE TITLE
Trigger with more then 6 hours duration not appear in Query Mode Triggers Count

### ISSUE THREAD

**Issue by FlavioTelecall** [alexanderzobnin/grafana-zabbix#818]
**Describe the bug**
The Query for Trigger count only cound trigger that has duration lower than 6 hours.
I just did the test, if I remove the trigger on zabbix and create again, it count on grafana, and after the trigger hit the duration of 6 hours grafana not count it any more.

**Expected behavior**
We would like to count all the trigger that is selected.

**Screenshots**
![Bug grafana](https://user-images.githubusercontent.com/56412977/66646675-40ec6c00-ebfd-11e9-87d3-bb8070f8ac6f.PNG)
![Bug grafana2](https://user-images.githubusercontent.com/56412977/66646688-48ac1080-ebfd-11e9-9bd9-2045ef151be3.PNG)
![Bug grafana3](https://user-images.githubusercontent.com/56412977/66646691-4ba70100-ebfd-11e9-9abc-7f81a7846a99.PNG)
![Bug grafana4](https://user-images.githubusercontent.com/56412977/66646795-8dd04280-ebfd-11e9-87a2-728c7cc23584.PNG)
![Bug grafana5](https://user-images.githubusercontent.com/56412977/66646839-ab9da780-ebfd-11e9-9166-20c475b77d28.PNG)
![Bug grafana6](https://user-images.githubusercontent.com/56412977/66646894-d982ec00-ebfd-11e9-9c5f-e5690b07dcbd.PNG)

**Network data**
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/1",
    "data": {
      "jsonrpc": "2.0",
      "method": "trigger.get",
      "params": {
        "output": "extend",
        "hostids": [
          "10307",
          "10263",
          "10266",
          "10325",
          "10294",
          "10306",
          "10297",
          "10317",
          "10367"
        ],
        "min_severity": 3,
        "filter": {
          "value": 1
        },
        "expandDescription": true,
        "expandData": true,
        "expandComment": true,
        "monitored": true,
        "skipDependent": true,
        "selectLastEvent": "extend",
        "selectGroups": "extend",
        "selectHosts": [
          "host",
          "name"
        ],
        "countOutput": true,
        "lastChangeSince": 1570770331,
        "lastChangeTill": 1570791931
      },
      "id": 1,
      "auth": "aed5c6dcb33590a4464670a35f3cee80"
    }
  },
  "response": {
    "jsonrpc": "2.0",
    "result": "0",
    "id": 1
  }
}

{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/1",
    "data": {
      "jsonrpc": "2.0",
      "method": "trigger.get",
      "params": {
        "output": "extend",
        "hostids": [
          "10307",
          "10263",
          "10266",
          "10325",
          "10294",
          "10306",
          "10297",
          "10317",
          "10367"
        ],
        "min_severity": 1,
        "filter": {
          "value": 1
        },
        "expandDescription": true,
        "expandData": true,
        "expandComment": true,
        "monitored": true,
        "skipDependent": true,
        "selectLastEvent": "extend",
        "selectGroups": "extend",
        "selectHosts": [
          "host",
          "name"
        ],
        "countOutput": true,
        "lastChangeSince": 1570770365,
        "lastChangeTill": 1570791965
      },
      "id": 1,
      "auth": "aed5c6dcb33590a4464670a35f3cee80"
    }
  },
  "response": {
    "jsonrpc": "2.0",
    "result": "1",
    "id": 1
  }
}

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.3.2   | 4.2.5 and 4.4.0  | 3.10.4 |

**Comment by alexanderzobnin** [comment]
Try to increase panel time range. It returns only problems within selected time range.

**Comment by FlavioTelecall** [comment]
@alexanderzobnin could you put a button or checkbox to count the current trigguers alarms, don`t matter the time range?
Because It`s not good for us the need of stay with the dashbord with a long time range, but we want to see all the current alarms all the time.
Normaly we use the time range on dashbord of 1 hour.

![image](https://user-images.githubusercontent.com/56412977/78896195-77892f00-7a46-11ea-9f70-9f6bd111ced7.png)

![image](https://user-images.githubusercontent.com/56412977/78896287-9f789280-7a46-11ea-829a-838efb5f5330.png)

**Comment by FlavioTelecall** [comment]
> Try to increase panel time range. It returns only problems within selected time range.

@alexanderzobnin could you put a button or checkbox to count the current trigguers alarms, dont matter the time range? Because Its not good for us the need of stay with the dashbord with a long time range, but we want to see all the current alarms all the time.
Normaly we use the time range on dashbord of 1 hour.

![image](https://user-images.githubusercontent.com/56412977/78896733-51b05a00-7a47-11ea-86d8-4150c212e772.png)

![image](https://user-images.githubusercontent.com/56412977/78896742-583ed180-7a47-11ea-84ec-4e85b9e0b7c1.png)
