### ISSUE TITLE
Trigger Colours

### ISSUE THREAD

**Issue by beerygaz** [alexanderzobnin/grafana-zabbix#820]
There is no way to set trigger colours when pulling Triggers from the API.  

Fore example if I have Disk utilisation  trigger for 80% (Warning)  and 90% (Disaster) - both lines appear on the Grafana Line/Bar graph as red. 

The lines should at least appear as the same colours in Zabbix.

**Comment by alexanderzobnin** [comment]
I don't think this is a feature I will implement. Alerting feature is quite confusing so I'm going to make it deprecated in the future.
