### ISSUE TITLE
"Functions" bug

### ISSUE THREAD

**Issue by Akabell95** [alexanderzobnin/grafana-zabbix#821]
**Describe the bug**
I can choose a function for my graph but I can't remove it when I don't need it anymore. Also, I can't see what function do I use without looking into Panel JSON.

**Expected behavior**
When I choose a function I can:
- See what function I choose
- Remove a function when I don't need it

**Screenshots**
On the screenshots below I choose movingAverage function for my graph with a factor "6".
I can only change it, but I can't delete it

![image](https://user-images.githubusercontent.com/30271548/66831994-990ad180-ef61-11e9-8395-6dfd4b4b2d2c.png)
![image](https://user-images.githubusercontent.com/30271548/66832014-a627c080-ef61-11e9-82a4-198c0a02610e.png)
![image](https://user-images.githubusercontent.com/30271548/66832040-b2ac1900-ef61-11e9-8543-2617e84ce4be.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.4.2   | 4.2.1  | 3.10.4                 |

**Comment by Q-nu** [comment]
A fix has been delivered here: [#810](https://github.com/alexanderzobnin/grafana-zabbix/issues/810).

**Comment by Akabell95** [comment]
@Q-nu, but [here](https://github.com/alexanderzobnin/grafana-zabbix/commit/a652eafc46bb4e25c034243d506f2513c08f1f41) you've said that the fix "seems to not work" :)

**Comment by Akabell95** [comment]
So... any updates here?

**Comment by Akabell95** [comment]
@alexanderzobnin ?

**Comment by turbatus** [comment]
I have the same problem since upgrading to Grafana v6.5.1 (1763a0f) from Grafana 6.4.0
Plugin (version 3.10.04) not changed.
Capture below is for setAliasByRegex:
![image](https://user-images.githubusercontent.com/8330709/69814642-efbc2a00-11f4-11ea-974c-926fb6b9353d.png)

Any ETA for a fix? 
Thank you.

**Comment by tmroberts-tableau** [comment]
I have the same issue using v6.5.2 and plugin version 3.10.4

**Comment by daria-maslovskaya** [comment]
The same situation. This bug is still alive :(
Grafana v6.5.2
Plugin v3.10.4

**Comment by alexanderzobnin** [comment]
This fix delivered in 3.10.5
