### ISSUE TITLE
Issue with React plugins and zabbix source

### ISSUE THREAD

**Issue by maxlehot1234** [alexanderzobnin/grafana-zabbix#823]
Hi everyone,

I post something on the grafana github, but ticket was closed since I am the only one with that issue.
I copy-paste base information here so you can get an idea of the issue instead of using the link below.

**What happened**: 
BarGauge plugin stop working. No reason why...
Everything works if I enable/disable the Transparent option into grafana, but directly when page reload, datas disappear, but that was not a fix of course.

**What you expected to happen**:
I want the bar gauge to work on every host. No idea which things I need to put here

**How to reproduce it (as minimally and precisely as possible)**:
I setup groups on Zabbix.
I setup a dashboard where I can choose the zabbix group and zabbix host from the selected group.
I have a host that have low disk space and it crash the bar gauge plugin for this host only.
I need to choose another host and refresh the page to get the bar gauge work for the other host.
Example:
![image](https://user-images.githubusercontent.com/5159244/65177096-08a1a580-da24-11e9-9636-45b4c0e22c86.png)

Like you can see, we see the thing that allow us to resize the plugin (bar gauge), but no data in it, cause it crash for the host.

For the other hosts, it looks like this:
![image](https://user-images.githubusercontent.com/5159244/65177157-2969fb00-da24-11e9-9481-374c830c946d.png)

**Environment**:
- Grafana version: Grafana v6.4.2 (443a0ba)
- Data source type & version: Zabbix
- OS Grafana is installed on: CentOS6
- User OS & Browser: Win10 1903 + chrome 76.0.3809.132 

I got console error in Chrome when I load Bar Gauge into grafana:
![image](https://user-images.githubusercontent.com/5159244/67234496-4888ed80-f413-11e9-8c24-392ae2970736.png)

I check with @ryantxu:  https://github.com/ryantxu and he remote my computer to see everything and he realize that something was wrong with how zabbix works with React which is used by Bar Gauge and Gauge plugin into Grafana. (I send him this ticket link, so he can reply and add more informations if needed)

You can get lot more informations here if you want:
https://github.com/grafana/grafana/issues/19213

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.4.3    | 4.2.6  | 3.10.4                      |

EDIT: Update to 6.4.3 of grafana and same issue.

Thanks again for everything and hope we can see this working, since we use it a lot here and Bar gauge seems to "crash" when a trugger goes under 15% in zabbix.

**Comment by maxlehot1234** [comment]
Everything works if I enable/disable the Transparent option into grafana, but directly when page reload, datas disappear.

**Comment by ryantxu** [comment]
I dug into this a bit.... the issue is with setting alert state on the panel breaks any react based panels in grafana.  Setting the classes directly with:

https://github.com/alexanderzobnin/grafana-zabbix/blob/ca082c98a16afc231cd05e3c83c44a969d6434a5/src/datasource-zabbix/zabbixAlerting.service.js#L16

changes the style so it is width+height == 0

**Comment by maxlehot1234** [comment]
@alexanderzobnin Tag me if you need me to test something since it seems that I am the only one with this issue.
I can test a version in advance if you want. just let me know.

This bug prevent our company to have a nice preview of our servers disk space left.

Thanks again and have a nice day

**Comment by alexanderzobnin** [comment]
Fix will be included in the upcoming release.

**Comment by maxlehot1234** [comment]
I try to add the change in the file and restart Grafana, but still get the same problem :(

Lets see with 3.11 when it will release to see if everything was fix :)

Thanks in advanced

**Comment by maxlehot1234** [comment]
@alexanderzobnin Any way to help to fix this instead of need to wait for an update that can be release in few weeks?

Thanks in advance and have a nice day/night
