### ISSUE TITLE
Editing trigger failed

### ISSUE THREAD

**Issue by vyidanov** [alexanderzobnin/grafana-zabbix#824]
**Describe the bug**
when i start editing a previously saved or newly created zabbix trigger list, an error occurs as on the screen

**Software versions**
Grafana version: v6.4.3 (commit: 3a2bfb7)
Data source plugin : zabbix 3.10.4
google Chrome ver 77.xx    the same in  IE 11

![err1](https://user-images.githubusercontent.com/31054236/67252891-a9fa9c00-f4a7-11e9-9998-5f9d3b31d3f5.png)
![err2](https://user-images.githubusercontent.com/31054236/67252896-ae26b980-f4a7-11e9-88e4-d4f67dd453cf.png)

**Comment by maxlehot1234** [comment]
#817

**Comment by alexanderzobnin** [comment]
Duplicates #817
