### ISSUE TITLE
Metrics fields not populated

### ISSUE THREAD

**Issue by nagylzs** [alexanderzobnin/grafana-zabbix#825]
I have configured grafana-zabbix with direct SQL. I have tried to create my first panel but none of the fields are populated. The example "getting started" tutorial shows that the available values (for example: host groups, item names etc.) should be showing up after I type in a few letters. But nothing happens!

![kép](https://user-images.githubusercontent.com/15814836/67424047-afee9b00-f5d5-11e9-9ac6-6ba3492e7bf6.png)

**Software versions**

Grafana 6.4.3
Zabbix 3.4.15
Grafana zabbix plugin 3.10.4

Actually, I cannot display any data, even when I type in the exact names by hand. There is no error message. Just simply there is no data. The zabbix user used for the connection is a Zabbix administrator.

**Comment by alexanderzobnin** [comment]
What zabbix queries return? Looks like Zabbix API issue.

**Comment by julienmary** [comment]
It's likely that your api user doesn't have enough permissions. Try to put it in super admin group to see if it's changing something. If it works, you can then create an API group where you will give read permissions for all groups of machines.
