### ISSUE TITLE
No Data Points Found - Grafana dashboard for Kafka Topics

### ISSUE THREAD

**Issue by akkihegde** [alexanderzobnin/grafana-zabbix#826]
I have grafana dashboard for kafka topic, i am not able see the data in dashboard. There are thousands of records in kafka topic, which is continuously streamed into it. I am able to see data in consumer console. But there is no luck in getting data points in grafana

Attached screenshot of the same:
<img width="1485" alt="Screenshot 2019-10-30 at 3 46 52 PM" src="https://user-images.githubusercontent.com/43107993/67849549-c001ff80-fb2c-11e9-91a1-245e93970d65.png">

**Comment by alexanderzobnin** [comment]
Try to ask author/maintainer of that dashboard, I have no idea what goes wrong.
