### ISSUE TITLE
SingleStat AVeraging when Current is Selected

### ISSUE THREAD

**Issue by bingo-the-pyro** [alexanderzobnin/grafana-zabbix#827]
This is for numerical values coming in solely as 1 or 0. When it changes state, you will get an averaged value such as 0.21, which will change over time until it reaches the correct number.
Value > Show is set to Current.
Max Data Points is set to Auto (Manually setting just alters the rate at which the averaging gets to the correct value and 1 data point is bad, it almost never gets to the correct value)
I created a direct sql query in another singlestat instead of using the zabbix plugin datasource and it changes immediatley. (Just found the itemid and id this:
select * from history_uint
where itemid = '91972'
order by clock desc limit 1
)
Running Zabbix 4.2.1 / Grafana 6.4.3 / Plugin 3.10.4

**Comment by jocms** [comment]
I have the same problem. Is it a bug?

**Comment by alexanderzobnin** [comment]
It's because of downsampling. If you need last value, use short time range or increase max data points.
