### ISSUE TITLE
Show non-suppressed problems from maintenance hosts even when "Show Maintenance Hosts" is not selected

### ISSUE THREAD

**Issue by TomasManzano** [alexanderzobnin/grafana-zabbix#830]
The ability to set maintenance periods to triggers matching tags instead of the whole host is a great step forward for Zabbix.

When a non-suppressed trigger of a maintenance host fires up the Problems tab in Zabbix shows this problem as the logic has been updated and now allows to hide "suppressed problems" instead of "maintenance hosts"

In grafana-zabbix if "Show hosts in maintenance" is not selected, unsuppressed problems from maintenance hosts won't appear on the dashboard. A workaround is to select "Show hosts in maintenance" but that fills the dashboard with a bunch of no use problems that make the approach unfeasible.  IE if you have stopped a complete environment for some reasons and you have also got some services in scheduled maintenance.  That situation happens a lot over here.

**Comment by cristianoness** [comment]
@alexanderzobnin We have the same problem here, some solution in mind?

**Comment by hudnall-s** [comment]
for anyone else looking for this, I rebuilt the plugin to use the maintenance mode on a problem level instead of a host level.

current as of 2/9/2022 can be found here https://github.com/hudnall-s/Grafana-Zabbix-Plugin
