### ISSUE TITLE
Could not connect to given url using self signed SSL certificate on zabbix server

### ISSUE THREAD

**Issue by SomeAverageDev** [alexanderzobnin/grafana-zabbix#832]
hello,
I configured grafana to use zabbix api URL with HTTP and it worked fined.

Then I configured a self signed certificate on my zabbix server, and then the grafana plugin does not work anymore and connection fails with the error below :

Could not connect to given url

using url 
`https://192.168.26.134/zabbix/api_jsonrpc.php`
Access : `server`

using access : browser, it works (not suitable for my needs)

command to generate SSL certificate
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt

I found this in syslog which confirm the failed ssl check, it looks like it is manage by grafana, and not the plugin itself:
`Nov 15 19:25:30 zabbix grafana-server[18022]: 2019/11/15 19:25:30 http: proxy error: x509: certificate signed by unknown authority`

I think I need to disable certificate check but could not find how to solve this so far... 
thanks!

**Comment by alexanderzobnin** [comment]
It's self-signed cert, so nothing wrong here. There's an option `Skip TLS Verify` in datasource config.
