### ISSUE TITLE
[Question] Any 3.11 ETA?

### ISSUE THREAD

**Issue by maxlehot1234** [alexanderzobnin/grafana-zabbix#834]
Hi,

I just want to know if you have an ETA for 3.11 milestone?

It will probably include a lot of bugfix, but we need it ;)

Thanks for your time and your work @alexanderzobnin

**Comment by maxlehot1234** [comment]
One month later, still nothing :( No reply, no updates, nothing...

Thats really sad....

**Comment by maxlehot1234** [comment]
@alexanderzobnin 
Hi, how are you?? No updates, no reply, nothing from you which is really sad :( Too many issues with. ALL OF US really need updates to fix all issues we have.


Thank you and please reply and check the actual tickets ;)

**Comment by alexanderzobnin** [comment]
Working on patch release now.
