### ISSUE TITLE
System status panel does not show all host groups

### ISSUE THREAD

**Issue by StaelensJarne** [alexanderzobnin/grafana-zabbix#841]
I have just quick a question about the Zabbix System Status dashboard.
Is there a possibility to show all Host groups in the System Status panel?
In my dashboard it shows only 3 Host groups, but on my Zabbix server I have much more. (see pictures).

How can I show all Host groups in the System status panel?
Or is this not possible because this panel uses the "trigger.get" method?
![System Status Panel](https://user-images.githubusercontent.com/26405591/69798665-a1456600-11c9-11ea-88dd-eb7a4b639b52.png)
![Host groups](https://user-images.githubusercontent.com/26405591/69798673-a6a2b080-11c9-11ea-8ecf-18a5c1f99d5e.png)

**Comment by alexanderzobnin** [comment]
I think it's time-range issue. Try to increase or rewrite panel time range (set 1 year, for instance, and look at the result).

**Comment by alexanderzobnin** [comment]
That might be a problem with groups with no active problems, try to search in open issues.

**Comment by StaelensJarne** [comment]
Yes its a time range issue.

The problem is that the dashboards is Grafana have a time range, while these in Zabbix haven't. Is there a way to disable the time range in Grafana (or to set a time range in Zabbix). Because sometimes I also see closed problems in Grafana.
