### ISSUE TITLE
Problem editing zabbix problem panel in grafana

### ISSUE THREAD

**Issue by elsopapa** [alexanderzobnin/grafana-zabbix#842]
**Describe the bug**
I cant edit zabbix problem panel, after update grafana 6.4.4

**Screenshots**

![image](https://user-images.githubusercontent.com/9828829/69815050-4402e200-11d4-11ea-8a52-46c400ce125b.png)

**Software versions**

| Grafana  | Zabbix  | Grafana-Zabbix Plugin  |
| ------- | ------ | --------------------- |
| 6.4.4  | 4.4.0 | 3.10.4                 |

**Comment by tantra35** [comment]
We have the same issue

**Comment by tiagoalmeida10** [comment]
I have the same problem.
Grafana: 6.5.1
Zabbix: 4.0.10
Zabbix Plugin: 3.10.4

**Comment by maxlehot1234** [comment]
This is related to: #817 

No reply from the zabbix plugin dev for more than a month... We need to wait

**Comment by ansiblepull** [comment]
We have the same issue too. Up+

**Comment by fabjal** [comment]
Same issue

**Comment by heyrod** [comment]
The same issue in Grafana 6.5

**Comment by elinxs** [comment]
Same issue.
Grafana 6.4.1 and Zabbix Plugin 3.10.4.

**Comment by dfabiao** [comment]
Same issue.

**Grafana** | **Zabbix** | **Grafana-Zabbix Plugin**
:----:        |      :----:     |                 :----:
6.4.4       |     4.0.4      |         3.10.4

**Comment by yoke88** [comment]
the same issue
* grafana 6.5.2 
* zabbix 3.0 LTS 
* grafana-zabbix-plugin 3.10.4

**Comment by alexanderzobnin** [comment]
duplicates #817
