### ISSUE TITLE
PROBLEME GRAFANA N/A

### ISSUE THREAD

**Issue by barto95100** [alexanderzobnin/grafana-zabbix#843]
Hi,

My problem is when I get request on grafana with Zabbix data source and mysql (mariadb) to view your dahboard template for many graph a received N/A 

![2019-11-29_16-33-43](https://user-images.githubusercontent.com/17863254/69878742-14340700-12c6-11ea-849f-02c360b4bc19.png)

version zabbix : 4.2.3
Version Grafna: 6.5.1

**Comment by alexanderzobnin** [comment]
Check if corresponding items exist on the Zabbix host. Also, check the name of host.
