### ISSUE TITLE
Cannot read property 'group' of undefined

### ISSUE THREAD

**Issue by ksycoltd** [alexanderzobnin/grafana-zabbix#846]
**Describe the bug**
Problems panel doesn't work. It shows "Cannot read property 'group' of undefined".

** Log **
TypeError: Cannot read property 'group' of undefined
    at eval (triggers_panel_ctrl.js:253)
    at angular.js:17169
    at angular.js:17217
    at c.$digest (angular.js:18351)
    at c.$apply (angular.js:18649)
    at angular.js:20574
    at p (angular.js:6428)
    at angular.js:6707 "Possibly unhandled rejection: {}"

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.5.1   | 4.4.3  | 3.10.4                 |

![이미지 446](https://user-images.githubusercontent.com/19255464/71244804-b2137280-2356-11ea-87c6-a54c74e5f1e6.jpg)

**Comment by alexanderzobnin** [comment]
duplicates #817
