### ISSUE TITLE
Problem with plugin Gauge in crash state Dashboard 

### ISSUE THREAD

**Issue by Andorash** [alexanderzobnin/grafana-zabbix#848]
Problem with plugin Gauge in crash state Dashboard 

![image](https://user-images.githubusercontent.com/35136951/71335804-aef2cf00-256e-11ea-9594-3591fd30ab20.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Grafana v6.3.2 (commit: 4832460)  |3.10.4  | x.x.x                 |

**Comment by alexanderzobnin** [comment]
Duplicates #823
