### ISSUE TITLE
TypeError: t.queries.map is not a function

### ISSUE THREAD

**Issue by naigamo** [alexanderzobnin/grafana-zabbix#849]
Dir sir

I found error "TypeError: t.queries.map is not a function" after edit on grafana 6.5.2 pleas advice for zabbix plugin 

Thank

**Comment by TrickUK** [comment]
+1

I am also using Grafana 6.5.2 and seeing this error when trying to edit a Zabbix Problems panel.

Steps to replicate: add panel, navigate back to dashboard, try and edit panel.

Stack trace as follows:

`An unexpected error happened
Details
TypeError: t.queries.map is not a function

    in t
    in div
    in r
    in c
    in div
    in div
    in div
    in e
    in t
    in div
    in t
    in t
    in div
    in div
    in t
    in d
    in div
    in t
    in div
    in e
    in DraggableCore
    in e
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in e
    in div
    in div
    in div
    in e
    in t
    in div
    in div
    in e
    in d
    in n
    in Unknown
    in p
    in Unknown
    in Unknown
    in t
    in t
    in d`

**Comment by alexanderzobnin** [comment]
duplicates #817

**Comment by kerneltravel** [comment]
@TrickUK  this maybe caused by using  IE based  browser. After changed to chrome, the Error disappeared  for me.
