### ISSUE TITLE
Percentile function.

### ISSUE THREAD

**Issue by glaubway** [alexanderzobnin/grafana-zabbix#850]
Hi, i want create graphs with 95% percentile for traffic accounting (such as I can found in cacti or zabbix internal function), but founded some question, how i can do that, whats time interval at that function(if I want 95% for 30d, that interval must be 30d, or something different)? And if I want use percentile function with aggr by sum function(or sum series), how i need use all this functions together?

**Comment by alexanderzobnin** [comment]
There's new percentile function for series, but it's not released yet (#868). Take a look at updated docs:
https://github.com/alexanderzobnin/grafana-zabbix/commit/5b211d80a90a8ef170c6f3967afc7444ef0c6f7b
