### ISSUE TITLE
Cannot retrieve more than 7 days of data

### ISSUE THREAD

**Issue by apinzari** [alexanderzobnin/grafana-zabbix#86]
Using Grafana 2.1.3 with grafana-zabbix 2.1.0-rc1 (previously 2.0.0 plugin with same issue). 

Selecting more than 7 days of data for time range does not work. Data is only displayed up to 7 days before. This is the case when only 1 graph is displayed, or on an entire dashboard. 

Thank you

**Comment by alexanderzobnin** [comment]
Are you use trends? See also #78.

**Comment by simple-snow** [comment]
I also have 90 days history data but cannot retrive more than 7 days.
Trends off. Software version are the same as @apinzari specified

**Comment by alexanderzobnin** [comment]
@simple-snow  Can you attach screenshot of datasource config and content of plugin.json file?

**Comment by simple-snow** [comment]
plugin.json
```
{
  "pluginType": "datasource",
  "name": "Zabbix",

  "type": "zabbix",
  "serviceName": "ZabbixAPIDatasource",

  "module": "plugins/datasource/zabbix/datasource",

  "partials": {
    "config": "app/plugins/datasource/zabbix/partials/config.html",
    "query": "app/plugins/datasource/zabbix/partials/query.editor.html",
    "annotations": "app/plugins/datasource/zabbix/partials/annotations.editor.html"
  },

  "username": "api",
  "password": "api",

  "trends": true,
  "trendsFrom": "7d",

  "limitmetrics": 100,

  "metrics": true,
  "annotations": true
}
```
datasource
![datasource](https://cloud.githubusercontent.com/assets/3039558/10127048/9d1406d2-65b5-11e5-964e-7e27168d2ecb.png)
graph
![graph](https://cloud.githubusercontent.com/assets/3039558/10127055/bba97a28-65b5-11e5-8dbf-bac9c19fdd67.png)

**Comment by alexanderzobnin** [comment]
Just remove trends section from plugin.json. In Grafana 2.1 you can config plugin via datasource config page only:
```
{
  "pluginType": "datasource",
  "name": "Zabbix",

  "type": "zabbix",
  "serviceName": "ZabbixAPIDatasource",

  "module": "plugins/datasource/zabbix/datasource",

  "partials": {
    "config": "app/plugins/datasource/zabbix/partials/config.html",
    "query": "app/plugins/datasource/zabbix/partials/query.editor.html",
    "annotations": "app/plugins/datasource/zabbix/partials/annotations.editor.html"
  },

  "metrics": true,
  "annotations": true
}
```

**Comment by karpath** [comment]
Hello alexanderzobnin, 

same here, i tried removing trends section from plugin.json, but doesn't seem to resolve the issue.

**Comment by alexanderzobnin** [comment]
@karpath Which version of plugin are you use?

**Comment by karpath** [comment]
like apinzari, grafana 2.1.3 with grafana-zabbix 2.1.0-rc1

plugin.json
```
{
  "pluginType": "datasource",
  "name": "Zabbix",

  "type": "zabbix",
  "serviceName": "ZabbixAPIDatasource",

  "module": "plugins/datasource/zabbix/datasource",

  "partials": {
    "config": "app/plugins/datasource/zabbix/partials/config.html",
    "query": "app/plugins/datasource/zabbix/partials/query.editor.html",
    "annotations": "app/plugins/datasource/zabbix/partials/annotations.editor.html"
  },


  "metrics": true,
  "annotations": true
}
```

datasource
![datasource](https://cloud.githubusercontent.com/assets/13885161/10508612/6c3afff4-7328-11e5-9449-b79ebc7cbe56.PNG)

and this is what happen when i try to display 30days

![255](https://cloud.githubusercontent.com/assets/13885161/10508994/9ded46ea-732a-11e5-8321-e55cdd0294c8.PNG)
![255-2](https://cloud.githubusercontent.com/assets/13885161/10508996/a0d48d78-732a-11e5-948d-dc6489e43528.PNG)

Did i miss something?

**Comment by nucleusv** [comment]
Look at https://github.com/alexanderzobnin/grafana-zabbix/wiki/Installation 
Trends support section.

**Comment by karpath** [comment]
my bad, sorry

@nucleusv it's working fine now, thank you

**Comment by apinzari** [comment]
Can confirm that applying the Zabbix trends patch resolved issues.

**Comment by alexanderzobnin** [comment]
@apinzari How long you store data at Zabbix history db?

**Comment by apinzari** [comment]
@alexanderzobnin 

We are storing 7 days of history and 365 as trends for most items. Some will have 30 or 90 day history storage item retention but those were not tested when the issue was reported.

**Comment by alexanderzobnin** [comment]
Zabbix API in current version don't support trends. For this reason you must use patch if you want to work with data older than 7 days (in your case).

**Comment by nucleusv** [comment]
Trends API will be in upcoming Zabbix 3.0

**Comment by simple-snow** [comment]
@alexanderzobnin  
i set plugin.json like you suggested, but nothing. In grafana i see only 7 days history insteed of 90 day history stored in zabbix

**Comment by net592** [comment]
Thanks @simple-snow @alexanderzobnin 
I played on the patch, can view the data more than 7 days
https://support.zabbix.com/browse/ZBXNEXT-1193
grafana 2.5.0.1 zabbix 2.4.6
