### ISSUE TITLE
Function editor broken for Grafana < 6.4

### ISSUE THREAD

**Issue by alecxvs** [alexanderzobnin/grafana-zabbix#860]
**Describe the bug**
Related to #810 and the fix delivered in 3.10.5
The fix for the function editor in Grafana 6.4 appears to have conversely broken the function editor in versions prior to 6.4.

**Expected behavior**
Function editor renders

**Screenshots**
![image](https://user-images.githubusercontent.com/513932/72020596-ba621d80-3231-11ea-8a18-6a5fc4180dca.png)

**Network data**
`angular.js:14700 Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.3.5   | n/a  | 3.10.5                |

**Comment by alexanderzobnin** [comment]
There's no backward compatibility for this fix, unfortunately, because of changes in grafana.
