### ISSUE TITLE
Graph panel appear random loss of itemid data  when using itemid query mode

### ISSUE THREAD

**Issue by JoyQAQ** [alexanderzobnin/grafana-zabbix#861]
**Describe the bug**
I created hundreds of graph panels on a dashboard. And when I using itemid query mode, Graph panel appears the random loss of itemid data. But when I in single graph panel, web post itemid, zabbix API response and graph display works well. For this issue I can't see any errors from Chrome dev tools. And api.php response data didn't return the missing itemid's response data. So I guess maybe one dashboard has hundreds of graph panels grafana browser didn't post all of itemids to Zabbix API when using itemid query mode. Anyone can help check this issue?

**Expected behavior**
When using Itemid query mode, Graph panel display works well when using aggregate by function or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/29222117/72041660-1c308f00-32e7-11ea-865a-4b6f2a622cc3.png)

**Network data**
no error log

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Grafana v6.5.2 (742d165)  | Zabbix 4.0.3  | 3.10.5                 |

**Comment by alexanderzobnin** [comment]
Yes, something goes wrong with proxifying requests.

**Comment by alexanderzobnin** [comment]
It seems first few queries fail because of authentication is still in progress.

**Comment by JoyQAQ** [comment]
> It seems first few queries fail because of authentication is still in progress.

Hi, is this issue any update now?

**Comment by alexanderzobnin** [comment]
Fixed! Issue was caused by improper auth flow.
