### ISSUE TITLE
Pull long time data display problem

### ISSUE THREAD

**Issue by junly917** [alexanderzobnin/grafana-zabbix#864]
Requirements: I would like to see historical data for 7 days or just 30 days.
Problem description:
1. There are 30 graphs for each monitor indicator of my server.
2. I have about 100 host servers.
3. Now to view 30 days of historical data,
4. My granafa is based on the drawing made by the host, so the bread in the page depends on 100 (stations) *30 (monitoring items) *30 (days).
This kind of query can lead to too much data pulling and can cause problems with the performance of the zabbix database. Is there any historical trend data of zabbix that can be used to display data based on how many days after the query?
Or is there a better way to display requirements?

**Comment by alexanderzobnin** [comment]
You can enable trends in datasource config to fetch trends instead of history from certain period.
