### ISSUE TITLE
Vizualization Zabbix problems - severity 

### ISSUE THREAD

**Issue by bessome** [alexanderzobnin/grafana-zabbix#866]
Changed manualy severity in zabbix stay unchanged in Grafana in Zabbix problems

![image](https://user-images.githubusercontent.com/37050975/72132957-f2c83f80-3388-11ea-91ce-1eb53c5be24e.png)

![image](https://user-images.githubusercontent.com/37050975/72133035-2c994600-3389-11ea-94d8-e49e94157653.png)

**Comment by alexanderzobnin** [comment]
#870
