### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by Trois-Six** [alexanderzobnin/grafana-zabbix#87]
Hi,

When I change the grafana server protocol of a working setup from http to https I can't load my graphs anymore. Do I have to add a parameter to plugin.json ?

Best regards,

Trois-Six

**Comment by darrynv** [comment]
Do you use chrome?

**Comment by Trois-Six** [comment]
yes !

**Comment by alexanderzobnin** [comment]
@darrynv Is this issue in chrome only?

**Comment by slick666** [comment]
Would putting Grafana behind a reverse proxy like nginx solve this for you?

**Comment by Trois-Six** [comment]
Hi,

I didn't find time to try it back with another browser, but I am going to.
@slick666 : yes, it could be a solution.

Trois Six

**Comment by trevorx** [comment]
I have exactly the same but upon further investigation it's the datasource that appears to break rather than just the graphing.  The test connection doesn't even work.

**Comment by alexanderzobnin** [comment]
Can anyone provide log of network requests from development tools?

**Comment by trevorx** [comment]
I've just handed my instance over for some other colleagues to trial (using http). I'll try to provide some logs when they've finished but may well be a week or two.

**Comment by jmaitrehenry** [comment]
I currently use grafana-zabbix with grafana and zabbix on HTTPS without issue.
I had an issue when I add Elasticsearch as a datasource and this one is not on https for now. I change the connection type to proxy and it works.

**Comment by nvtkaszpir** [comment]
No issues with graphana 2.6 + zabbix 2.2 over https and grafan connecting to it in proxy mode.
