### ISSUE TITLE
sumseries not working?

### ISSUE THREAD

**Issue by gralech** [alexanderzobnin/grafana-zabbix#874]
sumSeries shows value lower than individual values
tried sum instead of avg in groupBy function
$val is dashboard variable, used to set grouping interval: 1m, 5m, 15m, 1h etc..
trends not used (selected dashboard time interval less than zabbix datasource setting: zabbix api-trends-after)

![image](https://user-images.githubusercontent.com/5354169/72358607-e54ee480-36fd-11ea-8773-fd923628ed30.png)

grafana 6.3.2
grafana-zabbix 3.10.2

**Comment by alexanderzobnin** [comment]
Do you have stack option enabled on graph?

**Comment by gralech** [comment]
> Do you have stack option enabled on graph?

no, stacks not used

**Comment by alexanderzobnin** [comment]
@gralech could you share your panel JSON?

**Comment by gralech** [comment]
> @gralech could you share your panel JSON?

`{
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "fill": 0,
  "fillGradient": 0,
  "gridPos": {
    "h": 5,
    "w": 5,
    "x": 19,
    "y": 3
  },
  "id": 11,
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "max": true,
    "min": true,
    "rightSide": true,
    "show": false,
    "sort": "avg",
    "sortDesc": true,
    "total": false,
    "values": true
  },
  "lines": true,
  "linewidth": 1,
  "nullPointMode": "null",
  "options": {
    "dataLinks": []
  },
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [
    {
      "alias": "/summary/",
      "fill": 3,
      "linewidth": 0,
      "yaxis": 2,
      "zindex": -3
    }
  ],
  "spaceLength": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "application": {
        "filter": "custom - redis"
      },
      "functions": [
        {
          "def": {
            "category": "Transform",
            "defaultParams": [
              "1m",
              "avg"
            ],
            "name": "groupBy",
            "params": [
              {
                "name": "interval",
                "type": "string"
              },
              {
                "name": "function",
                "options": [
                  "avg",
                  "min",
                  "max",
                  "sum",
                  "count",
                  "median"
                ],
                "type": "string"
              }
            ]
          },
          "params": [
            "$val",
            "avg"
          ],
          "text": "groupBy($val, avg)"
        },
        {
          "def": {
            "category": "Aggregate",
            "defaultParams": [],
            "name": "sumSeries",
            "params": []
          },
          "params": [],
          "text": "sumSeries()"
        },
        {
          "def": {
            "category": "Alias",
            "defaultParams": [],
            "name": "setAlias",
            "params": [
              {
                "name": "alias",
                "type": "string"
              }
            ]
          },
          "params": [
            "summary"
          ],
          "text": "setAlias(summary)"
        }
      ],
      "group": {
        "filter": "/.*/"
      },
      "host": {
        "filter": "/deac-generic-redis.*/"
      },
      "item": {
        "filter": "/commands_processed.*/"
      },
      "mode": 0,
      "options": {
        "showDisabledItems": false
      },
      "refId": "A",
      "resultFormat": "time_series",
      "table": {
        "skipEmptyValues": false
      },
      "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
      }
    },
    {
      "application": {
        "filter": "custom - redis"
      },
      "functions": [
        {
          "def": {
            "category": "Transform",
            "defaultParams": [
              "1m",
              "avg"
            ],
            "name": "groupBy",
            "params": [
              {
                "name": "interval",
                "type": "string"
              },
              {
                "name": "function",
                "options": [
                  "avg",
                  "min",
                  "max",
                  "sum",
                  "count",
                  "median"
                ],
                "type": "string"
              }
            ]
          },
          "params": [
            "$val",
            "avg"
          ],
          "text": "groupBy($val, avg)"
        }
      ],
      "group": {
        "filter": "/.*/"
      },
      "host": {
        "filter": "/deac-generic-redis.*/"
      },
      "item": {
        "filter": "/commands_processed.*/"
      },
      "mode": 0,
      "options": {
        "showDisabledItems": false
      },
      "refId": "B",
      "resultFormat": "time_series",
      "table": {
        "skipEmptyValues": false
      },
      "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
      }
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeRegions": [],
  "timeShift": null,
  "title": "Redis Cmds, rps",
  "tooltip": {
    "shared": true,
    "sort": 2,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": "",
      "logBase": 1,
      "max": null,
      "min": "0",
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}`

**Comment by alexanderzobnin** [comment]
Ok, got it. This is not a bug. Graph displayed properly, but you see wrong values because some of returned series are incomplete. Pay your attention to the circles on the graph that indicate which point displayed at the tooltip. Try to set `Null value` option to `zero` to fix this issue.
