### ISSUE TITLE
Internal Server Error when trying to display 2+ days history of 10+ hosts

### ISSUE THREAD

**Issue by thefoodleagues** [alexanderzobnin/grafana-zabbix#878]
I'm trying to work out if this is a bug with the plugin/Grafana, or it's simply a limitation of how much data I'm trying to pull.

Let's say I want a table showing average CPU utilization of a server over the past 7 days.
- No problem, I'm able to select the select a single host, a relevant application and item, set the table to time series aggregation,  and set the time range to 7 days. I have my data;
![1 - Does work](https://user-images.githubusercontent.com/39812579/72998372-5740c100-3dc3-11ea-8210-bd48736a16ac.png)

Now let's say I want to do the same for a small group of servers.
- Again, no problem, I choose a group with, say 8 servers in it, keep the rest of the settings the same as previous, and I have my data;
![2 - Does work](https://user-images.githubusercontent.com/39812579/72998373-5740c100-3dc3-11ea-8376-4cce1734b71d.png)

Now let's say I want to display the same data for all of my servers, or a larger group.
This is where my problem lies.
- I make the change to target a larger group, or  I use /.*/ for group and hosts, to target everything
- I get 'No data to show', along with a red 'internal server error' at the top left of the widget
- If I go ahead and change the time picker to 'Last 12 hours', it works, my data appears
- If I then go ahead and change the time picker to 'Last 24 hours', or above, it bombs out;
![3 - Does not work](https://user-images.githubusercontent.com/39812579/72998371-56a82a80-3dc3-11ea-8c3b-edbf49c19620.png)

Does this sound familiar to anyone? Is there a way around it?

Because Zabbix doesn't really have a reporting facility, I want to use Grafana to produce monthly over/undersubscription reports - but as it stands, it's only really going to be useful for live dashboards of recent data.

 Thanks for your help! I love your plugin. I would not have been able to sell the Grafana/Zabbix idea without it!

Grafana Version: 6.5.2
Zabbix Version: 4.4.4
Zabbix-Grafana Plugin Version: 3.10.5

**Comment by alexanderzobnin** [comment]
Looks like you PHP is out of memory. Try to increase server resource limits and make sure you enabled trends for large time intervals (7 days+).

**Comment by WojciechKuk** [comment]
I have similar issue, but zabbix is working stable (I have plenty of memory allocated for PHP).
I have OOM errors on alexanderzobnin-zabbix-app plugin. Memory usage incdeasing to ~500MB when asking for 20-30 hosts - if time picker is set to > 12h.
