### ISSUE TITLE
 Plugin Error Fetch error: 404 Not Found Instantiating 

### ISSUE THREAD

**Issue by ranzlumia** [alexanderzobnin/grafana-zabbix#879]
HI ,
I am getting an error while creating data source in Grafana.
am using Grafana v5.0.1, I have tried installing various version of Zabbix plugins
-- cleared browser cache,etc..

I have tried the same with another Grafana which is v6.5.1works fine.
i suspect that its version compatibility issue. if yes Please tell me right version for grafana v5.0.1
since am already using PRTG with Grafana v5, i cannot go for higher version of Grafana

"Plugin Error
Fetch error: 404 Not Found Instantiating https://192.168.56.103/public/react Loading https://192.168.56.103/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module"

**Comment by alexanderzobnin** [comment]
Yea, lates versions are not compatible with old Grafana. For Grafana 5.x try to install `3.9.1` or `3.9.0` plugin version.
