### ISSUE TITLE
Colour Thresholds not working with decimals

### ISSUE THREAD

**Issue by stephenh1991** [alexanderzobnin/grafana-zabbix#88]
Hi,

I've been trying to add colour background changes using thresholds but it doesn't change when the threshold is reached.

Is this because I'm using decimal values?

Thanks,
Steve
![grafana](https://cloud.githubusercontent.com/assets/12548107/10219402/9117c110-6836-11e5-98c6-59923fc658d7.PNG)

**Comment by alexanderzobnin** [comment]
@stephenh1991 My plugin don't manage this part of metric editor. Please, search for Grafana issues or open new.
