### ISSUE TITLE
Grafana - Simple check dashboard using different colors for different severity.

### ISSUE THREAD

**Issue by deathtopigss** [alexanderzobnin/grafana-zabbix#884]
Hi, im trying to make a simple check dashboard using different colors for the boxes depending on the severity of the zbx trigger.
Anyone already try it? 
Now im using one I made it using singlestat visualization and customizing value per regex, but only obtaine RED or GREEN according to the count of triggers for that host.

**Comment by deathtopigss** [comment]
![Uploading Captura.PNG…]()

**Comment by alexanderzobnin** [comment]
Please, ask questions on Grafana community site https://community.grafana.com/
