### ISSUE TITLE
Explore doesn't work with Zabbix datasource

### ISSUE THREAD

**Issue by jooola** [alexanderzobnin/grafana-zabbix#888]
**Describe the bug**
Grafana Explore don't work with zabbix datasource

**Expected behavior**
Expect to query and graph some zabbix data in the explore panel.
By making a query by hand or by using the visualization explore function.

The main goal for this is to explore both metrics and loki logs to debug some infrastructure issues.

**Screenshots**
Dashboards visualization works great:
![image](https://user-images.githubusercontent.com/19195485/73944756-66f7f380-48f3-11ea-9e9d-2a2b33c3bb6b.png)
But not on the explore panel:
![image](https://user-images.githubusercontent.com/19195485/73944832-868f1c00-48f3-11ea-9220-0a7dc3ce54a8.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Version 6.6.0 (5c11bbdfb4)   | 4.4.5  | 3.10.5 |

**Comment by alexanderzobnin** [comment]
Yes, confirmed. Looks strange, I'll try to figure it out.

**Comment by jooola** [comment]
Neat ! :beers:
