### ISSUE TITLE
ITEM.VALUE acts like ITEM.LASTVALUE in annotations

### ISSUE THREAD

**Issue by Akint** [alexanderzobnin/grafana-zabbix#891]
**Describe the bug**
When {ITEM.VALUE} macros is used in a trigger name and annotations of this trigger occurs multiple times on a single graph, the macros is resolved like `{ITEM.LASTVALUE}` on every occurrence.
As you can see on the screenshot below, annotation text is always `too large: 5` for a trigger with condition `item.last() > 1` and title `too large: {ITEM.VALUE}`.
![old](https://user-images.githubusercontent.com/2721104/74419156-0d0ba680-4e7c-11ea-8f8c-90a2953cdc87.png)

**Expected behavior**
When possible, the historical (at-the-time-of-event) value should be seen in annotation text.
The screenshot below is a spoiler of how it works after my fix.
![expected](https://user-images.githubusercontent.com/2721104/74419200-1e54b300-4e7c-11ea-8c3e-0f0bfcb61839.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.6.1   | 4.0.17 | 3.10.5                |

P.S. May be a duplicate of #396, but the latter was never resolved.

**Comment by alexanderzobnin** [comment]
Hi! Yes, it's better to use event name for annotations, like you did in your commit, good work!
