### ISSUE TITLE
[Question] Showing the top x event log entries as a bar gauge

### ISSUE THREAD

**Issue by inquisitortano** [alexanderzobnin/grafana-zabbix#893]
Hi,

I'm trying to visualize the most recurring Windows event log entries. I'm using Zabbix as my data source and I've run into several problems. 
For instance I am unable to query metrics for the Eventlog Application and a query for triggers returns Nothing. A text query is successful and returns all that I need.

Example:
jsonrpc:"2.0"
result:Array[111]
0:Object
itemid:"125614"
clock:"1581655477"
timestamp:"1581655445"
source:"Service Control Manager"
severity:"1"
value:"The Client License Service (ClipSVC) service entered the stopped state."
logeventid:"7036"
ns:"61294150"

Is it possible a) that I can somehow make another query to retrieve data from these strings (eg. logeventid) and b) can I then group them by their ID to display as a bar gauge?

Any help would be highly appreciated.

**Comment by alexanderzobnin** [comment]
Hi! This is not possible. For this task it's better to use something that can extract information from logs, like Elasticsearch.
