### ISSUE TITLE
Error: u is undefined

### ISSUE THREAD

**Issue by kolopaa** [alexanderzobnin/grafana-zabbix#896]
When I choose a period of 7 days and more I receive a message that u is undefined. The data comes from Zabbix and I know there is data from that period.

```
Object
state:"Error"
series:Array[0]
request:Object
requestId:"Q141"
timezone:""
panelId:4
dashboardId:8
range:Object
timeInfo:undefined
interval:"1h"
intervalMs:3600000
targets:Array[4]
maxDataPoints:1920
scopedVars:Object
cacheTimeout:undefined
startTime:1582552043093
rangeRaw:Object
valueType:"avg"
consolidateBy:"avg"
timeRange:Object
from:p
to:p
raw:Object
error:TypeError

```
I noticed that this problem appears when I choose over 4 days.

**Comment by alexanderzobnin** [comment]
It looks like general grafana bug (appears when returned data is empty). Should be fixed soon I guess.
