### ISSUE TITLE
Feature Request: Take alias name from zabbix item name

### ISSUE THREAD

**Issue by nucleusv** [alexanderzobnin/grafana-zabbix#9]
Would be nice, if alias is taken from zabbix item name.
Needed chekpoint (fill alias from zabbix) if it is set, grafana must take it from zabbix api, not from alias field

**Comment by alexanderzobnin** [comment]
Implemented. See 2b2f9979335f1fffa42a831d20ceb39eadd5edd3 ([develop-1.9](https://github.com/alexanderzobnin/grafana-zabbix/tree/develop-1.9) branch for now).
Just add new metric and alias sets by default or delete existing alias.

**Comment by nucleusv** [comment]
I'll test it tomorrow. but from your description I think it is not perfect logic, sometimes item name from zabbix can be too long, and some one would want to rename it i grafana not in zabbix, I think it must be a option

**Comment by alexanderzobnin** [comment]
You may edit alias as you want. It will remain. Very simple logic ))

**Comment by nucleusv** [comment]
Cool it works

**Comment by alexanderzobnin** [comment]
Yes, new features will be added in release 1.1.0 (see [milestones](https://github.com/alexanderzobnin/grafana-zabbix/milestones/)). This is rule of [semantic versioning](http://semver.org/).
