### ISSUE TITLE
public/react 404 not found after upgrading plugin

### ISSUE THREAD

**Issue by mattymo** [alexanderzobnin/grafana-zabbix#903]
**Describe the bug**
Widgets show as black and spinning in Firefox after upgrading from v3.9.1 to v3.10.3. For some reason, it renders okay in Chrome.

In javascript console this message is seen:
Uncaught (in promise) TypeError: Cannot read property '$rootScope' of undefined at datasource_srv.ts:103
index.js:20 GET https://grafana.mycompany/public/@grafana/ui 404 (Not Found)

**Expected behavior**
Triggers wigdets show normally.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|v5.1.3   | 3.4.8  | v3.9.1            |
|v5.1.3   | 3.4.8  | v3.10.3          |

Any suggestions? Perhaps my Grafana version is too old

**Comment by alexanderzobnin** [comment]
Hi! Plugin v3.10.3 is not compatible with Grafana 5.x. Try to use latest Grafana and plugin versions.
