### ISSUE TITLE
Not bug, not a feature, Just need help to make FlowCharting compatible with zabbix datasource

### ISSUE THREAD

**Issue by algenty** [alexanderzobnin/grafana-zabbix#904]
Hi Alexander,

My name is Arnaud, i am the author of plugin Flowcharting for grafana.
Some user of flowcharting and Zabbix plugin have the problem with identical same name for metrics.
https://github.com/algenty/grafana-flowcharting/issues/106
But i don't know zabbix, do you know a free online server zabbix to add a zabbix datasource and debug Flowcharting ?
I tried http://zabbix.grafana-zabbix.org/api_jsonrpc.php without success.
I see in doc the user API in screenshot but i don't know password.

Thx for you help
BR

Arnaud

**Comment by alexanderzobnin** [comment]
Hi! Try to use my bootstraped docker env (I use the same for play.grafana-zabbix.org)
https://github.com/alexanderzobnin/grafana-zabbix-demo-docker
