### ISSUE TITLE
Comparing/Operating on multiple queried values

### ISSUE THREAD

**Issue by derpydo** [alexanderzobnin/grafana-zabbix#905]
For various visualizations, such as the Gauge plugin, I would like to be able to query two values and, for instance, display a percentile.

So, for instance -- 

Received bits query gets:  26943368 
Provisioned bits is:  2500000000

I don't see a way to compare these values and create a percentile.  The act of choosing both of these in a Query generates two Gauge graphs.

I do know that I can provide a new data element from Zabbix that takes both of these and calculates a percentage.   Given the sheer number of these instances, I'm trying to keep my items and nvps as low as possible, so it would be great if this could dynamically be generated in Grafana.

Cheers.

**Comment by alexanderzobnin** [comment]
It's not possible now.
