### ISSUE TITLE
DataSources : Could not connect to given url

### ISSUE THREAD

**Issue by pikaniou** [alexanderzobnin/grafana-zabbix#908]
After updating to grafana version 6.7 and zabbix version 4.4.6, the data sources stopped working.

![1](https://user-images.githubusercontent.com/50659391/77165224-2b377880-6ab2-11ea-84b5-675142fe5d37.PNG)

![2](https://user-images.githubusercontent.com/50659391/77165417-86696b00-6ab2-11ea-96b0-ecc5ddce07ef.PNG)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.7.0   | 4.4.6  | 3.10.5                 |

**Comment by Positronico** [comment]
Same here!

**Comment by kampfflunder** [comment]
`apt-get install grafana=6.6.2` was my workaround

**Comment by corgan2222** [comment]
I hade the same problem!
For me, it helped to disable the direct DB Conection, which is strange, because the DB conection works without Problems.

**Comment by corgan2222** [comment]
ah, i think its allread fixed in  https://github.com/alexanderzobnin/grafana-zabbix/commit/dad0fd965deb11d817e7369dab2a0a03f9d13401
i will try the github version

**Comment by asalam05** [comment]
@corgan2222  Any luck ?

**Comment by jamiew0w** [comment]
Is there a way for us to test the fix or temp downgrade until the fix is available?

Appreciate the work on this plugin by the way, immensely useful - thanks!

**Comment by pikaniou** [comment]
it's ok for me with upgrade 3.11.0
