### ISSUE TITLE
Resolved problems color and severity set to Not classified

### ISSUE THREAD

**Issue by mkyrianov** [alexanderzobnin/grafana-zabbix#909]
**Describe the bug**
In Zabbix Problems panel Severity changes to Not classified if Status is Resolved.

**Expected behavior**
Severity value does not depend on Status.

**Screenshots**
![image](https://user-images.githubusercontent.com/62099369/77434455-91d9d080-6de9-11ea-989a-4a187a36b835.png)

**Software versions**
https://play.grafana-zabbix.org 24.03.2020 4:10 PM EET

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.6.0  | x.x.x  | 3.11.0                 |

**Comment by okorolov** [comment]
+1
I cannot find a way how to keep severity level for Resolved cases.

**Comment by alexanderzobnin** [comment]
Seems it duplicates #870

**Comment by mkyrianov** [comment]
Is #870 fixed in 3.11? Because this #909 problem is seen in 3.11.

**Comment by alexanderzobnin** [comment]
@mkyrianov Yes, see it now, it's a bug.
