### ISSUE TITLE
Item Description over ride

### ISSUE THREAD

**Issue by meyerder** [alexanderzobnin/grafana-zabbix#915]
**Is your feature request related to a problem? Please describe.**
Yes... To long of a item in the legend

**Describe the solution you'd like**
would like a "override" on the description when leveraging metrics mode and selecting all hosts.. The Item should have the ability to make a item show in the legend as a shorter description

Currently it lists Host:Item in my case the Item is pretty long..

![image](https://user-images.githubusercontent.com/28714840/78623960-29114000-784e-11ea-9ef2-8a286fe45943.png)

**Comment by alexanderzobnin** [comment]
You can use [`replaceAlias()`](https://alexanderzobnin.github.io/grafana-zabbix/reference/functions/#replacealias) function. See example dashboard [Legend overrides](https://play.grafana-zabbix.org/d/tRrKOfjZk/legend-overrides?orgId=2&fullscreen&edit&panelId=2).

**Comment by alexanderzobnin** [comment]
Also, there's related feature request #619
