### ISSUE TITLE
Problem when Upgrade plugin to 3.11.0

### ISSUE THREAD

**Issue by edsontadeuas** [alexanderzobnin/grafana-zabbix#916]
Hi!

I tried to update my plugin to 3.11.0 now, and i have some issues.

1 - When i update plugin from 3.60 to 3.11.0 The plugin stopped to work and i got an 404 error.
     I did as i read here and cleared my cache, restart browser, etc.
     I had to come back to version 3.10.0 and then, everything come back to "work".

2 - Now, i'm experiencing another problem with "Zabbix Problem Visualization"
     I can add an this componente and configure it at first time. but, when
    i come back to main painel, go to "Zabbix problem visualization" menu and click in EDIT,
    i can't see nothing on my scree. Everything is black.

I don't  known if anyone have experienced this, but i'm having this problem today.

Thank you.

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.2.5x   | 3.4.15  | 3.11.0                 |

**Comment by alexanderzobnin** [comment]
Hi! Latest version of plugin (3.11) is working only with Grafana > 6.7. So in order to use latest plugin, upgrade grafana.

**Reminder for myself**: add compatibility matrix
