### ISSUE TITLE
Explore don`t work 

### ISSUE THREAD

**Issue by Tepew** [alexanderzobnin/grafana-zabbix#919]
Explore don`t work 

![zabbix_plugin_3 11 0_explore](https://user-images.githubusercontent.com/42611903/79118558-efcd5880-7d96-11ea-83e9-14903401d0ba.JPG)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.7.2  | 4.0.18  | 3.11.0  |

**Comment by alexanderzobnin** [comment]
Duplicate #888
