### ISSUE TITLE
Grafana on Apache2 Server

### ISSUE THREAD

**Issue by JulianDeb12** [alexanderzobnin/grafana-zabbix#92]
Hi

I installed Grafana on my Apache2 Server under usr/share/grafana.

Now I want to get to the Login Page but I cant find the correct URL. Local it would be localhost:3000
but now it is on the server and im totally new to linux. Can anyone help me?

**Comment by alexanderzobnin** [comment]
@JulianDeb12 
1. Do yo can connect to grafana via http://localhost:3000 locally from yor server?
2. Which address are you want to use to connect to grafana remotely? For example grafana.yourserver.com?

**Comment by alexanderzobnin** [comment]
It seems, you want to use Apache as a proxy for grafana. In this case you can use mod_proxy and config like this:
```
<VirtualHost *:80>
    ServerName grafana.yourserver.com
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www

    ProxyPass           /    http://localhost:3000
    ProxyPassReverse    /    http://localhost:3000    
</VirtualHost>
```

**Comment by JulianDeb12** [comment]
I fixed it now I had to do it with proxy the url is now serverip.ch/grafana

Now I made this Dashboard. I have a lot of servers so i had to set the datasource value higher (above 100). There are now plenty graphs and when i hover them I always get the Info of each Graph instead of the hovered one. Can I change that?

![unbenannt](https://cloud.githubusercontent.com/assets/8762716/10338727/e2e72c3a-6d07-11e5-9cbd-14501dcf0b62.PNG)

**Comment by alexanderzobnin** [comment]
Open panel editor and go to Display styles tab. Uncheck `All series` in Tooltip section.

**Comment by JulianDeb12** [comment]
Thanks for the fast answer it worked. Is there also an option to display the server names on the graph?
(sorry for asking so much)

**Comment by alexanderzobnin** [comment]
You can display serever names in graph legend (if graphs from multiple servers are selected).
