### ISSUE TITLE
Erro #200 ao criar um gráfico de reconhecimento de incidentes do zabbix

### ISSUE THREAD

**Issue by carllosedu** [alexanderzobnin/grafana-zabbix#920]
Já procurei em toda a internet e não achei nenhuma solução, também fiz vários testes para solucionar mas não consegui. Toda vez não importa o que faça quando vou colocar o visual zabbix problems dá esse problema na hora de salvar.
![image](https://user-images.githubusercontent.com/63604746/79140183-f60b0700-7d8d-11ea-84f8-e281048680fb.png)

**Comment by rauhmaru** [comment]
Se quiser respostas, recomendo postar em inglês. (In english, please :) )

**Comment by alexanderzobnin** [comment]
In English, please.
