### ISSUE TITLE
Problems: sorting by severity doesn't work

### ISSUE THREAD

**Issue by akiparuk** [alexanderzobnin/grafana-zabbix#921]
I have a lot of sources in a single dashboard. 
if to sort by severity it sorts by severity per source. It doesn't sort the whole list of events.
So it doesn't look like it sorted at all.

<img width="148" alt="image" src="https://user-images.githubusercontent.com/17548131/79154164-54cf8100-7d8c-11ea-9da3-4f5f29208435.png">

**Comment by alexanderzobnin** [comment]
How did you sort it? Could you show panel config?

**Comment by akiparuk** [comment]
`{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 2,
  "links": [],
  "panels": [
    {
      "ackEventColor": "rgb(56, 219, 156)",
      "ageField": true,
      "customLastChangeFormat": false,
      "datasource": null,
      "descriptionAtNewLine": false,
      "descriptionField": true,
      "fontSize": "100%",
      "gridPos": {
        "h": 23,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "highlightBackground": false,
      "highlightNewEvents": false,
      "highlightNewerThan": "1h",
      "hostField": true,
      "hostGroups": false,
      "hostProxy": false,
      "hostTechNameField": false,
      "hostsInMaintenance": true,
      "id": 2,
      "lastChangeFormat": "",
      "layout": "table",
      "limit": 1000,
      "markAckEvents": false,
      "okEventColor": "rgb(56, 189, 113)",
      "pageSize": 1000,
      "problemTimeline": true,
      "resizedColumns": [],
      "schemaVersion": 7,
      "severityField": true,
      "showEvents": {
        "text": "Problems",
        "value": 1
      },
      "showTags": false,
      "showTriggers": "all triggers",
      "sortTriggersBy": {
        "text": "severity",
        "value": "priority"
      },
      "statusField": true,
      "statusIcon": false,
      "targets": [
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-Boulder",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "A",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-gomel",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "B",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-Grodno",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "C",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-HQ",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "D",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-Kharkiv",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "E",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-Minsk",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "F",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-nl",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "G",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-nl2",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "H",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-vitebsk",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "I",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": "Zabbix-VN",
          "group": {
            "filter": ""
          },
          "host": {
            "filter": ""
          },
          "proxy": {
            "filter": ""
          },
          "refId": "J",
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          }
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "All Zabbix problems",
      "triggerSeverity": [
        {
          "color": "rgb(108, 108, 108)",
          "priority": 0,
          "severity": "Not classified",
          "show": true
        },
        {
          "color": "rgb(120, 158, 183)",
          "priority": 1,
          "severity": "Information",
          "show": true
        },
        {
          "color": "rgb(175, 180, 36)",
          "priority": 2,
          "severity": "Warning",
          "show": true
        },
        {
          "color": "rgb(255, 137, 30)",
          "priority": 3,
          "severity": "Average",
          "show": true
        },
        {
          "color": "rgb(255, 101, 72)",
          "priority": 4,
          "severity": "High",
          "show": true
        },
        {
          "color": "rgb(215, 0, 0)",
          "priority": 5,
          "severity": "Disaster",
          "show": true
        }
      ],
      "type": "alexanderzobnin-zabbix-triggers-panel"
    }
  ],
  "schemaVersion": 22,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "All Zabbix problems",
  "uid": "Md2TRZpWk",
  "variables": {
    "list": []
  },
  "version": 1
}`

**Comment by akiparuk** [comment]
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/17548131/79240019-797c3500-7e2e-11ea-8bcf-0bd36c278ac3.png">

**Comment by alexanderzobnin** [comment]
Anyway, I'm working on panel updates and sorting will be rewritten, so I believe it should be fixed in next plugin version.

**Comment by alexanderzobnin** [comment]
I can't replicate this. What plugin version do you use?

**Comment by akiparuk** [comment]
Version

3.11.0

**Comment by akiparuk** [comment]
I have 12 data sources in one dashboard.

**Comment by brfrugis** [comment]
Hey, I´m facing the same issue here on my env.
I have only one data source and when I try to sort by severity it cames sorting by age  or so.... as it show bellow

![image](https://user-images.githubusercontent.com/56682618/83519563-9807bf80-a4b2-11ea-92b1-87ea74140091.png)

we try to query some different result but not success...
Plugin Version 3.12.2

**Comment by jonathanlo55** [comment]
I'm also with the plugin version 3.12.2 with sorting these sorting issues.

**Comment by brfrugis** [comment]
Hey @alexanderzobnin any leads on that? That view is really important for the usage of our env...
there is a release date for the new version?

**Comment by polak785** [comment]
Hello, 

Any update on this? We facing this issue too with plugin 3.12.2 and Zabbix 5.0.1

**Comment by pliniosampaio** [comment]
Hello,
Grafana v7.0.3
Plugin 3.12.4
Zabbix 5.0

I try to sort by severity, doesn't work, if I try to click in the title of column, not sorting by other column
 
<img width="1175" alt="Capture" src="https://user-images.githubusercontent.com/63920930/88941677-ecc77c80-d24e-11ea-8d7d-996d94568dd7.PNG">

<img width="1235" alt="Capture02" src="https://user-images.githubusercontent.com/63920930/88941676-ecc77c80-d24e-11ea-89fa-89c27f1218e0.PNG">
