### ISSUE TITLE
Error # 200 when creating a zabbix incident recognition graph

### ISSUE THREAD

**Issue by carllosedu** [alexanderzobnin/grafana-zabbix#922]
I searched all over the internet and found no solution, I also did several tests to solve it but it was not possible. When I save this error:
![image](https://user-images.githubusercontent.com/63604746/79219519-ceb54800-7e28-11ea-8f2f-9efe21cd1e01.png)

Does anyone know how I can fix this?

**Comment by carllosedu** [comment]
I already found out it is because zabbix problems does not work in the new version of graphana so I went back to 6.0. It would be nice if you updated the plugin to work in the new version

**Comment by alexanderzobnin** [comment]
That's probably the same issue #907
