### ISSUE TITLE
Is the zabbix plugin supposed to work for Grafana instances that are behind SSO/SAML?

### ISSUE THREAD

**Issue by zacharystokes** [alexanderzobnin/grafana-zabbix#923]
We're getting the familiar error that others have run into:

Zabbix plugin error:
Error: fetch error:  404 Not Found Instantiating

I used the grafana-cli to install the plugin.  We're running grafana 6.5.2 in prod.

The relevant section of the ini file is:

[auth.generic_oauth]
enabled = true

We're using our own internal Okta instance for this purpose.  Is this supposed to work?

**Comment by alexanderzobnin** [comment]
Hi! `auth.generic_oauth` is OAuth, not a SAML. I can't realize, are you trying to install plugin and get an error?

**Comment by Masih1432** [comment]
@zacharystokes , is there any update coming on zabbix SAML Auth Integration with Grafana? Thanks.
