### ISSUE TITLE
Problem with grafana adding zabbix data source

### ISSUE THREAD

**Issue by cscowx** [alexanderzobnin/grafana-zabbix#925]
Hi,

One physical machine, IP address: 10.18.240.8

Zabbix（Version 4.4.7）, mysql8（Version 8.0.19）, grafana（Version 6.7.2 OSS） are all deployed on this physical machine

The zabbix web access link is: http://10.18.240.8:8080（I have normal access）

Grafana WEB access link: http://10.18.240.8:3000（I have normal access）

I created the data source for zabbix in grafana，

HTTP：

URL：http://10.18.240.8/api_jsonrpc.php   or  http://10.18.240.8/zabbix/api_jsonrpc.php
Access：Server(default)

Zabbix API details:

Username: 
Password:
Trends:

Other parameters default

Finally, click Save & Test

prompt: Could not connect to given url

How can I solve this problem

**Comment by Tepew** [comment]
In URL use port
8080
you strarted web service on 8080, but in Grafana use 80
http://10.18.240.8:8080/api_jsonrpc.php
http://10.18.240.8:8080/zabbix/api_jsonrpc.php

**Comment by alexanderzobnin** [comment]
@Tepew is right - you should use full URL with port.
