### ISSUE TITLE
Omit certain results

### ISSUE THREAD

**Issue by mpopovi** [alexanderzobnin/grafana-zabbix#926]
**Is your feature request related to a problem? Please describe.**
First of all, thank you so much for all your hard work on this! Its very appreciated! As for the issue, I would like to pull all my routers in a location and display all the interface Utilization (I got this far). However I dont want to include any interface that has the word "Vlan" in it. Is there a good way to exclude those?

**Describe the solution you'd like**
It would be great to have an regex exclude section so that we can omit some of the items.

**Describe alternatives you've considered**
 I tried to do some regex work in the "Application" field, but to no avail.

**Additional context**

![image](https://user-images.githubusercontent.com/2784404/79510613-82b5ff00-7ff2-11ea-8d87-3e3a0b0b2ef6.png)

**Comment by alexanderzobnin** [comment]
Hi! If you have interface items like
```
if0 utilization
if1 utilization
vlan0 utilization
```
you can use regex like `/^(?!vlan).* utilization/` to exclude `vlan` item. Anyway, it's possible with regex in Item field.

**Comment by mpopovi** [comment]
great! that worked. That you for all your hard work and efforts on this.
you're awesome!

On Fri, Apr 17, 2020 at 1:33 AM Alexander Zobnin <notifications@github.com>
wrote:

> Hi! If you have interface items like
>
> if0 utilization
> if1 utilization
> vlan0 utilization
>
> you can use regex like /^(?!vlan).* utilization/ to exclude vlan item.
> Anyway, it's possible with regex in Item field.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_alexanderzobnin_grafana-2Dzabbix_issues_926-23issuecomment-2D615118478&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=cOfBeGmKPNxysVQw5XCg-ekmKg7AFt5RtcFGxL_S22MdIuoDWVPrNtSfvq0aJH6z&m=p0jXeLoH1vN-93zuCxAwuislzM6pj-qE2FozNNNN45U&s=y7D4pWmE5Xp00ibSxnjUURQjwP-TYYqfeuD9zVXP6TA&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAVHZFDTXB5474PEENQUE5LRNAH5RANCNFSM4MKG7F7A&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=cOfBeGmKPNxysVQw5XCg-ekmKg7AFt5RtcFGxL_S22MdIuoDWVPrNtSfvq0aJH6z&m=p0jXeLoH1vN-93zuCxAwuislzM6pj-qE2FozNNNN45U&s=L7bUJ11yp9Poq_vMEO4Sn2ECaioCJNVeeDo8Q0AzAFY&e=>
> .
>


-- 

Thank you,
Marko Popovich
949-286-8580
