### ISSUE TITLE
Didn`t work timeshift

### ISSUE THREAD

**Issue by Tepew** [alexanderzobnin/grafana-zabbix#928]
Didn`t work timeshift.

![zabbix_plugin_3 11 0_timeshift](https://user-images.githubusercontent.com/42611903/79534525-82b20f80-8083-11ea-8e3c-af3a7a861df3.JPG)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.7.2/6.4.3   | 4.0.15/4.0.18  | 3.11                 |

**Comment by alexanderzobnin** [comment]
Looks like it works as expected. Probably a reason is in the returned values. Also, it's not a plugin feature, but Grafana one.
