### ISSUE TITLE
Severity changes to "Not Classified" when problem is resolved on Zabbix problem dashboard

### ISSUE THREAD

**Issue by kris4ever** [alexanderzobnin/grafana-zabbix#929]
**Describe the bug**
When a problem appears on the Zabbix problem dashboard, the severity is the same as in Zabbix (Warning, high, info, etc...) as long as the problem remains. But once the problem has a status "Resolved", the severity changes to "Not Classified" while Zabbix shows the correct severity at the moment when the problem rised.

**Expected behavior**
The Zabbix problem dashboard should display the same severity during the problem, and once the status has change to resolved.

**Screenshots**
Please find screenshot below that demonstrate the problem:
Zabbix screenshot:
![Zabbix](https://user-images.githubusercontent.com/25671795/79553564-f6ace180-809c-11ea-9279-5ca69a3d0ee3.png)
Grafana screenshot
![Grafana](https://user-images.githubusercontent.com/25671795/79553567-f7457800-809c-11ea-98d1-6e328921730d.png)

**Network data**
jsonrpc: "2.0", result: {,…}, id: 1}
jsonrpc: "2.0"
result: {,…}
2913168: {eventid: "2913168", source: "0", object: "0", objectid: "38927", clock: "1587104876", value: "0",…}
eventid: "2913168"
source: "0"
object: "0"
objectid: "38927"
clock: "1587104876"
value: "0"
acknowledged: "0"
ns: "828296359"
name: "Too many connections to **** !"
severity: "0"
r_eventid: "0"
c_eventid: "0"
correlationid: "0"
userid: "0"
acknowledges: []
suppressed: "0"
tags: []
2913202: {eventid: "2913202", source: "0", object: "0", objectid: "18560", clock: "1587105225", value: "0",…}
eventid: "2913202"
source: "0"
object: "0"
objectid: "18560"
clock: "1587105225"
value: "0"
acknowledged: "0"
ns: "261499948"
name: "Processor load is too high on **** (Load = 4.41)"
severity: "0"
r_eventid: "0"
c_eventid: "0"
correlationid: "0"
userid: "0"
acknowledges: []
suppressed: "0"
tags: []
id: 1

**Software versions**
| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | -------- | ---------------------- |
| 6.7.1      | 4.0.19    | 3.11.0                              |

Please let me know if you have any questions.
Thanks,

Kris.

**Comment by alexanderzobnin** [comment]
Duplicates #909
