### ISSUE TITLE
No datapoint

### ISSUE THREAD

**Issue by atavius** [alexanderzobnin/grafana-zabbix#93]
Hi,
I am currently trying to run grafana-zabbix with Zabbix 3.0. I managed to get it working on my virtual lab fine, but when I tried to set it up today on real machine I encountered strange behavior when I can get data from zabbix like group, hostname, apllication and items, but they do not populate graphs - it hangs on no datapoint.

I tried to look to developer tools in firefox but there are no errors. 

I am not sure if it is relevant, but in my virtual lab I used Centos 7 x64 for Zabbix and real machine is running Zabbix on Centos 6.7 x32. Any idea what might be causing this?

![dashboard](https://cloud.githubusercontent.com/assets/15019223/10345867/92966f6e-6d2c-11e5-9c72-93dc4922cfdc.jpg)
![datasource](https://cloud.githubusercontent.com/assets/15019223/10345866/929242d6-6d2c-11e5-93bd-de30c94d05ab.jpg)

**Comment by alexanderzobnin** [comment]
Can you try to select single item?

**Comment by atavius** [comment]
Well, I just came home and was ready to setup 32bit Centos 6.7 in virtual lab to give it another try. Interestingly once I got to install page which asked me to setup timezone I got an idea to check time and date on real machine and of course it was not set correctly. :sweat_smile:
Once I fixed that graphs in grafana started working :smirk:

So yeah... Now I feel stupid, but maybe this info will help someone in future with same problem.

**Comment by rauhmaru** [comment]
I also had this problem.
But let collecting from one day to the other, and then the data showed.
Probably has something to do with this problem in the timezone.

Raul Libório
http://rauhmaru.blogspot.com/
openSUSE Member | Linux User #4444581
