### ISSUE TITLE
 sumseries() inconsistent results 

### ISSUE THREAD

**Issue by LunaticZorr** [alexanderzobnin/grafana-zabbix#932]
**Describe the bug**
Trying to get a panel to show the SUM of multiple values/metrics. But the panel keeps updating and showing inconsistent values. If I expect "3", it shows 3 for a while, then goes to "0", "1", "0", "3" again sometimes and so on.

(this is one panel, but I'm having the same issue with all panels using `sumseries()`)

**Expected behavior**
The panel should always show a consisent SUM of the values.

**Screenshots**
![buffered_all](https://user-images.githubusercontent.com/19307263/79747279-4ab8ff80-8303-11ea-987c-c80916fd4270.JPG)

![buffering_total_query](https://user-images.githubusercontent.com/19307263/79747294-4ee51d00-8303-11ea-98cf-cf7f8fa28a07.JPG)

![buffering_stat_visualization](https://user-images.githubusercontent.com/19307263/79747307-53113a80-8303-11ea-81f7-1dcd3764b54b.JPG)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.7.2   | 4.4.4  | 3.1.1                |

**Comment by alexanderzobnin** [comment]
Hi! The reason why it happens described in #320. A possible solution is #887, so I'm closing this in favor of `last` aggregation which can solve this issue too.
