### ISSUE TITLE
IT Service Problem to calculate

### ISSUE THREAD

**Issue by lbigui** [alexanderzobnin/grafana-zabbix#933]
**Describe the bug**
The problem is occurring when I get the service IT time "OK" and "Problem". The total isn't hitting

As shown in the image below, I am showing the last 6 hours on dashboard, but in the table "Backend performance Down time" the total time "OK" and "Problem" is not 6 hours.

**Screenshots**
![image](https://user-images.githubusercontent.com/58707313/79796318-bd3dd580-832b-11ea-8c02-3b738e22b01f.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.7.2  | 4.4.7  | 3.11.0               |

**Comment by mbuyukkarakas** [comment]
I have the same problem too.

**Comment by alexanderzobnin** [comment]
Hi! It's the same root cause as #885 has. I'm going to fix it in next release.
