### ISSUE TITLE
Grafana v6.7.2 Explore Function with Zabbix Plugin 3.11.0 Not Working

### ISSUE THREAD

**Issue by lizhisen** [alexanderzobnin/grafana-zabbix#934]
Version: Grafana v6.7.2 with Zabbix Plugin 3.11.0
Zabbix: 4.4.0

Everything works fine (dashboard with zabbix data), but Explore function to query zabbix Metrics is not working.

In chrome and firfox，**it didn't send "history.get" request, only "trigger.get" request is sent** with following:
request:
{"jsonrpc":"2.0","method":"trigger.get","params":{"output":"extend","itemids":["42155"],"expandDescription":true,"expandData":true,"expandComment":true,"monitored":true,"skipDependent":true,"selectLastEvent":"extend"},"id":1,"auth":"65bd1e2f5073696dfd4d0f1e7fdf2f29"}

respond:
{"jsonrpc":"2.0","result":[],"id":1}

Not sure whether this is the key point to this question.

![a](https://user-images.githubusercontent.com/41671222/79817102-3e8e7a00-83b7-11ea-8d05-98b3084fee66.JPG)

**Comment by lizhisen** [comment]
@alexanderzobnin

**Comment by alexanderzobnin** [comment]
Duplicates #888
