### ISSUE TITLE
trendsValue(sum) is not working

### ISSUE THREAD

**Issue by v-zhuravlev** [alexanderzobnin/grafana-zabbix#935]
Hi Alexander, thanks for your fantastic project again. 

**Describe the bug**
It is possible to use `trendsValue(sum)` function in Grafana zabbix datasource but it is not working.
(ALL SCREENS ARE LAST 7D)
![image](https://user-images.githubusercontent.com/14870891/80131302-b10f7d80-85a2-11ea-9914-9b3fcc4f7934.png)
`count` is also not working
![image](https://user-images.githubusercontent.com/14870891/80131385-d56b5a00-85a2-11ea-9c27-751ddb6ccd12.png)

Others options like `avg`, `min` or `max` are working.
![image](https://user-images.githubusercontent.com/14870891/80131252-9e954400-85a2-11ea-9c78-48a7ca1646bf.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.7.2   | 4.4.7  | 3.11.0                |

**Comment by alexanderzobnin** [comment]
Hi! Got it. At least `sum` is working with Direct DB Connection, but I can make it working with API as well by returning `value_avg * num` value.
