### ISSUE TITLE
Grafana shows “Templating init failed Cannot read property 'result' of undefined”

### ISSUE THREAD

**Issue by zlbkkk** [alexanderzobnin/grafana-zabbix#937]
1、The grafana I used is grafana-6.4.0-1.x86_64.rpm；
2、The Prometheus I used is “prometheus-2.0.0.linux-amd64”；
3、The node_exporter I used is “node_exporter-0.18.1.linux-amd64”；
4、The Dashboards template I use is "Node Exporter v0.16--0.18" and its ID is: 10262

But what I see on the granfana interface is "Templating init failed Cannot read property 'result' of undefined"

![1](https://user-images.githubusercontent.com/33144389/80295826-8262f400-87a8-11ea-9db3-469c8c325a70.png)
![grafana_template](https://user-images.githubusercontent.com/33144389/80295827-8727a800-87a8-11ea-8a1e-053a807e69a4.png)

**Comment by alexanderzobnin** [comment]
That's not related to this plugin at all.

**Comment by zlbkkk** [comment]
Prometheus status：





The data source is also open







But when viewing the monitoring data, this error is displayed





Hope to receive your reply！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alexander Zobnin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 凌晨0:39
收件人:&nbsp;"alexanderzobnin/grafana-zabbix"<grafana-zabbix@noreply.github.com&gt;;
抄送:&nbsp;"1315392407@qq.com"<1315392407@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alexanderzobnin/grafana-zabbix] Grafana shows “Templating init failed Cannot read property 'result' of undefined” (#937)





 
That's not related to this plugin at all.
