### ISSUE TITLE
IT Services not shown

### ISSUE THREAD

**Issue by JulianDoebbeling** [alexanderzobnin/grafana-zabbix#94]
I can't see the IT Services in the Metrics even though I got the last release. Is there anything I forgot?

**Comment by alexanderzobnin** [comment]
Can you add a screenshot of query editor menu?

**Comment by JulianDoebbeling** [comment]
Sure here it is: 
![unbenannt](https://cloud.githubusercontent.com/assets/8762716/10394323/ada98cd0-6e96-11e5-8e39-c0688b028569.PNG)

**Comment by alexanderzobnin** [comment]
I'm interested in menu screenshot:

![](https://cloud.githubusercontent.com/assets/4932851/8911308/433ff262-3494-11e5-8145-b4eb250d777a.png)

**Comment by JulianDoebbeling** [comment]
It looks the same as yours just without IT services, thats why I'm asking..

**Comment by alexanderzobnin** [comment]
Can you check this feature at http://play.grafana-zabbix.org?
http://play.grafana-zabbix.org/dashboard/db/it-services?panelId=1&fullscreen&edit

**Comment by JulianDoebbeling** [comment]
yes
![unbenannt](https://cloud.githubusercontent.com/assets/8762716/10394602/953face0-6e98-11e5-8c08-44f507bc6c83.PNG)

**Comment by alexanderzobnin** [comment]
Try to clear browser cache. What plugin version are you use?

**Comment by JulianDoebbeling** [comment]
I always clear the browser cache. I use version 2.0.0

**Comment by alexanderzobnin** [comment]
This features available in 2.1 RC1 release.
https://github.com/alexanderzobnin/grafana-zabbix/releases

**Comment by JulianDoebbeling** [comment]
Okay my bad. I updated everything now it is showing up thanks!
