### ISSUE TITLE
Grafana no data to display

### ISSUE THREAD

**Issue by aniln67** [alexanderzobnin/grafana-zabbix#940]
Hi Alexander,
 
I've integrated zabbix 4.0.2 with Grafana 6.3.5 and zabbix plugin version is 3.10.4.

I'm unable get data from zabbix to display on grafana, though I see my server group and hostname populating correctly from drop down. None of the graphs work , only working panel is porblem panel.

I tried creating new dashboard and result is same. Could you please help me with this config.

![grafana](https://user-images.githubusercontent.com/65146169/81521149-064ddc00-9364-11ea-8531-10e423e7e3a8.PNG)

**Comment by i-ky** [comment]
Maybe you've configured plugin to use [direct database connection](https://alexanderzobnin.github.io/grafana-zabbix/configuration/direct_db_datasource/) and it's not working properly? In this case you would see data that plugin gets from Zabbix API, but you can't anything (like item values for graphs) for which direct connection to Zabbix DB is used.

**Comment by aniln67** [comment]
I'm not using direct database config, below is my config.

![image](https://user-images.githubusercontent.com/65146169/81536596-76bb2400-9389-11ea-8cb3-8032885116ab.png)

**Comment by aniln67** [comment]
![image](https://user-images.githubusercontent.com/65146169/81536829-ca2d7200-9389-11ea-9f49-708a8a358d6d.png)

**Comment by Kawabountou** [comment]
the dashboard come empty. i should configure it if you want to see some value

**Comment by alexanderzobnin** [comment]
I'm not sure it's a bug. Try to edit panel and make sure you query metrics you actually have in your Zabbix.

**Comment by cabrizio** [comment]
Hi there, I'm experiencing the same issue, I am able to explore groups and hosts, but no data are displaying when I run a simple query.
I have not configured the directed, shall I?
Anything else that I can check?
Thanks

**Comment by Nehemoth** [comment]
Check these

$Group
$Hosts


Sadly with the latest version of Zabbix a lot of things don't work anymore. Bellow you can find all the changes that must be done so it works under Zabbix 4.4.7.
Certain panels won't work at all.



Change the Datastore name from DS_ZABBIX to Zabbix (or your correct DS name and remember it's case Sentitive)

Panel: Available
Application: Zabbix agent to Monitoring agent
Agent ping to Zabbix agent ping

Panel: Uptime
Application: General to Status
Item: System Uptime to Uptime

Panel: hostname?
Format as: Table
Application: Zabbix agent to Monitoring agent
Item: System Name to Host name of Zabbix agent running

Panel: Memory Utilization
Item: Used memory in % to Memory utilization

Panel: Total CPU
Item: Number of CPUs to Don't exist but...
...You can create one.
In Zabbix go to the desired Template used in your servers
Select Items
Choose one from the CPU options and clone it
Name: CPU Threads Quantity
Type: Zabbix Agent
Key: system.cpu.num
Type of Information: Numeric (unsigned)
Unit: Blank
Update Interval: 1m
Application: CPU

Then the query should be
Query Mode: Metrics
Group: $Group
Host: $Hosts
Application: CPU
Item: CPU Threads Quantity (or any other name that you assigned to your item)



Panel: Memory/CPU
Query A
Application: Performance to CPU

Query B
Item: Used memory in % to Memory utilization

Panel: CPU Utilization
Application: Performance to CPU

Panel: Average disk queue length
Query A:
Application: Filesystems to Disk 0 C:

Query B
Application: Performance to CPU
Item: CPU iowait time to CPU interrupt time(?) [or should be CPU queue length?]


Panel: Free disk space
Application: Filesystems to Filesystem C:
Item: /^Free disk((?!%).)*$/ to C:: Total space

Add another query
Query Mode: Metrics
Group: Your associated Template Group
Host: /.*/
Application: Filesystems
Item: C:: Used space

On Zabbix create an Item Called "C:: Free space"
Type: Zabbix Agent
Key: "vfs.fs.size[c:,free]"
Type of Information: " Numeric (Unsigned)
Units: G
Update Interval: 1m
History Storage Period: 90d
Trend Storage Period: 365d
Show value: as is
Applications: Filesystems
Populates host inventory: None
Enabled: checked

Panel: File writes bytes/s
Application: Filesystems to Disk 0 C:
Item: File write bytes per second to 0 C:: Disk write rate

Panel: File read/write bytes/s
Query A
Application: Filesystems to Disk 0 C:
Item: File read bytes per second to 0 C:: Disk read rate

Query B
Application: Filesystems to Disk 0 C:
Item: File write bytes per second to 0 C:: Disk write rate

Panel: File read bytes/s 
Application: Filesystems to Disk 0 C:
Item: File read bytes per second to 0 0 C:: Disk read rate

Panel: Outgoing Traffic
Application: Network interfaces to The name of you server interface
Item: /.*Outgoing/ to Interface NAME: Bits sent

Panel: Incoming Traffic 
Application: Network interfaces to The name of you server interface
Item: /.*Incoming/ to Interface NAME: Bits received

Panel: Network Traffic
Query A
Application: Network interfaces to The name of you server interface
Item: /.*Incoming/ to Interface NAME: Bits received

Query B
Application: Network interfaces to The name of you server interface
Item: /.*Outgoing/ to 0 Interface NAME: Bits sent

Panel: Problems 
Group: Your Server Groups
Host: /.*/

Monitoring agent General

Zabbix raw items

**Comment by Tokiro74** [comment]
Hi there,

I'm experiencing the same issue, i'm using grafana 7.2.0, zabbix 4.4.10 and zabbix plugin 4.0.1.
I don't have direct db connection configured.
I'm also able to exploe zabbix group, host, application and items through the datasource in my dashboard.
I checked if my user have access to this items, he has.

I tried to run the sql query from query inspector on my db 
`SELECT to_char(itemid, 'FM99999999999999999999') AS metric, clock / 20 * 20 AS time, AVG(value) AS value FROM history WHERE itemid IN (37669) AND clock > 1603784632 AND clock < 1603806232 GROUP BY 1, 2 ORDER BY time ASC`

![image](https://user-images.githubusercontent.com/73527674/97310552-a42a5a00-1863-11eb-9e39-ee507c906171.png)
![image](https://user-images.githubusercontent.com/73527674/97311667-e43e0c80-1864-11eb-95ff-3b2d511e06c2.png)

And it prompt me this error:
`ERROR 1305 (42000): FUNCTION zabbix.to_char does not exist`

This query work without to_char function.
`SELECT itemid FROM history_uint WHERE itemid IN (38461) AND clock > 1603272942 AND clock < 1603294542; `
I'm working on mariadb 10.4.13

Is there a compatibility issue between zabbix plugins datasource and mariadb ?

**Comment by alexanderzobnin** [comment]
@Tokiro74 looks like DB compatibility issue.

**Comment by Tokiro74** [comment]
@alexanderzobnin i found the solution, i had to recreate a new datasource.
Something probably went wrong during the update to 4.1.0.
Now it detect the DB correctly.

**Comment by cristianolinux** [comment]
Good morning @alexanderzobnin  



How do I query the return of the icmp item via the database? I'm using grafana with zabbix. I want to use geomap.
My problem if query via interface table, everything comes with 0
