### ISSUE TITLE
Not working with zabbix 5 version

### ISSUE THREAD

**Issue by SkirmantasK** [alexanderzobnin/grafana-zabbix#941]
Plugin is not working with the new zabbix 5 version.

**Comment by Kawabountou** [comment]
like me.

I think we are too speed for the update ^^

**Comment by zensqlmonitor** [comment]
what's the issue? I don't see any changes in the Zabbix API.

**Comment by Kawabountou** [comment]
the solution will coming soon, just wait that the edveloppper release a new version

**Comment by alexanderzobnin** [comment]
Hi! What's an exact Zabbix version you're using? What's an error you get?

**Comment by SkirmantasK** [comment]
Here is the version:
rpm -qa | grep zabbix
zabbix-apache-conf-5.0.0-0.7rc1.el8.noarch
zabbix-release-4.5-2.el8.noarch
zabbix-web-5.0.0-0.7rc1.el8.noarch
zabbix-server-mysql-5.0.0-0.7rc1.el8.x86_64
zabbix-web-mysql-5.0.0-0.7rc1.el8.noarch
zabbix-agent-5.0.0-0.7rc1.el8.x86_64

While adding zabbix server as source there is no option to select 5 version, only 4 and with version 4 it adds successfully and I get message: "Zabbix API version: undefined" and I can not retrieve any info from zabbix server.

**Comment by alexanderzobnin** [comment]
I'll try to check it out.

**Comment by alexanderzobnin** [comment]
I tested it against zabbix 5.0 (docker image `zabbix-server-pgsql:alpine-5.0-latest`, Zabbix 5.0.0) and it works well for me. So please, make sure you configured it in the right way.

**Comment by SkirmantasK** [comment]
But did you tried to create dashboard and retrieve data from zabbix?

**Comment by alexanderzobnin** [comment]
@SkirmantasK Sure, I can do it both with 4.x and 5.0.

**Comment by SkirmantasK** [comment]
I havent added api_jsonrpc.php that why it was not working, sorry. Working now fine! We can close this.
