### ISSUE TITLE
Can't edit variables in Grafana 7.0.0

### ISSUE THREAD

**Issue by LeHigh75** [alexanderzobnin/grafana-zabbix#949]
**Describe the bug**
With Grafana 7 i can t edit / add a new variable anymore, instead a form, it s just blank
![Capture](https://user-images.githubusercontent.com/5429958/82327934-718c5380-99df-11ea-8701-d26bb187d1f1.PNG)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.0   | 4.4.4  | 3.11.0                |

**Comment by Liandora** [comment]
Same issue here. Other variables work just fine, but for Zabbix datasources, I just get the blank screen.

Grafana: 7.0.0
Zabbix: 5.0.0
Grafana-Zabbix Plugin: 3.11.0

**Comment by carllosedu** [comment]
I had the same problem, but with the zabbix problems. The screen is clean, as if there was no incident.

Grafana: 7.0.0;
zabbix: 4.0.20
Plugin: 3.11.0

**Comment by alexanderzobnin** [comment]
Fixed in fde56d24e93425132cc11abf5152aa5f681bdf02

**Comment by dufaustoitu** [comment]
Hi everyone!

I do this Fixed in fde56d2 but is not working. Do you have the other alternative?

Zabbix 4.2
Grafana 7.0

With zabbix 4.4 I have de same problem to that zabbix 4.2 in grafana variable.


Thanks!

**Comment by tomSDL** [comment]
@dufaustoitu Clear the browser cache :)
