### ISSUE TITLE
SLA is wrong

### ISSUE THREAD

**Issue by JulianDoebbeling** [alexanderzobnin/grafana-zabbix#95]
I'm displaying the SLA with the new feature but the SLA of every single IT Service equals 100%.
The SLA directly in Zabbix is correct but as soon as I pull it into Grafana it is 100%. I don't know if this is a bug or if I have some wrong settings. I've got everything in the editor as it is on the live demo website.

**Comment by alexanderzobnin** [comment]
@JulianDoebbeling Sorry, I have no time now to write docs for all new features. But I think yor problem is a time interval. SLA was calculate for some time range. You must specify this time for whole dashboard or use `Override relative time` options in `Time range` section of panel editor. See [It Services](http://play.grafana-zabbix.org/dashboard/db/it-services) dashboard for more details.

**Comment by JulianDoebbeling** [comment]
Yes I understand that. But as I said i did everything as it is in your example dashboard and the SLA is still
wrong doesn't matter which time range.

**Comment by alexanderzobnin** [comment]
Can you provide more info (screenshots of zabbix SLA and Grafana)

**Comment by alexanderzobnin** [comment]
@JulianDoebbeling also check `decimals` and `value` parameters at `Options` page in panel editor.
At my dashboard
```
decimals = 4
value = current
```
![screenshot 2015-10-12 20 20 57](https://cloud.githubusercontent.com/assets/4932851/10433953/d6eaf086-711e-11e5-83e4-43ede90594ad.png)

**Comment by JulianDoebbeling** [comment]
finally it worked after i restarted everything new tomorrow...
