### ISSUE TITLE
Variables won't work on fresh install with Grafana 7 and Zabbix 5

### ISSUE THREAD

**Issue by egorky** [alexanderzobnin/grafana-zabbix#952]
**Describe the bug**
On a fresh install with Grafana 7.0.0-1, Centos 7.8.2003 and Zabbix 5.0 (Revision 9665d62db0) I installed the latest grafana-zabbix plugin the dashboards work as usual but the variables.
![image](https://user-images.githubusercontent.com/54412925/82524192-efda1a00-9af3-11ea-8dce-16524426ed28.png)
As soon as you select the zabbix data source, the screen just became completely black. The browser console reports the fail of a component.
![image](https://user-images.githubusercontent.com/54412925/82524358-595a2880-9af4-11ea-9674-3e8a1c36b651.png)
I have tried on two different servers and the behavior is the same. If I downgrade Grafana to the 6.7.3 version, everything, including variables, works.

**Expected behavior**
One should be able to use variables onto the dashboards.

**Screenshots**
Here you can see the same setup but with Grafana 6.7.3 and the variables are fine
![image](https://user-images.githubusercontent.com/54412925/82524632-10ef3a80-9af5-11ea-9dec-6daf7eaef02f.png)

**Software versions**
Grafana 7.0.0-1, Centos 7.8.2003, Zabbix 5.0 (Revision 9665d62db0) and Grafana-zabbix plugin v 3.11.0

**Comment by alexanderzobnin** [comment]
Duplicates #949
