### ISSUE TITLE
Problems list - Cannot read property 'description' of undefined

### ISSUE THREAD

**Issue by roman-tiukh** [alexanderzobnin/grafana-zabbix#956]
**Screenshots**
![image](https://user-images.githubusercontent.com/38906004/82636359-1dfe4d80-9c0b-11ea-8c62-8291bc2c6f7c.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.0   | 4.4  | 3.12.0                 |

**Comment by alexanderzobnin** [comment]
duplicates #954
