### ISSUE TITLE
Problems list - query editor scrolling

### ISSUE THREAD

**Issue by roman-tiukh** [alexanderzobnin/grafana-zabbix#957]
**Describe the bug**
When i scroll query in query editor - query disappears.

**Expected behavior**
Query scroll correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/38906004/82636654-c0b6cc00-9c0b-11ea-8481-8d948be52bb3.png)
Scroll in red area
![image](https://user-images.githubusercontent.com/38906004/82636784-14c1b080-9c0c-11ea-8272-422c725871f2.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.0  | 4.4  | 3.12.0                |

**Comment by alexanderzobnin** [comment]
I can't replicate this. Could you provide more details, like errors in browser JS console? Can you reproduce this bug on https://play.grafana-zabbix.org/d/000000024/problems?orgId=2 ?

**Comment by roman-tiukh** [comment]
Maybe the problem is related to #954. Because I saw them at the same time.
And maybe its uncleared cache after upgrade grafana to 7.0.0.

After an unsuccessful update, I rolled back the operating system to prev version so cant repeat bug.

**Comment by joachim-vertommen** [comment]
Hello,

I'm seeing the same problem.
When the query disappears and I refresh the page I get following error: 

![Screenshot_2020-05-25 TV Zabbix - Grafana](https://user-images.githubusercontent.com/65894416/82798247-8d2ca980-9e78-11ea-8394-6193b652d949.png)

I haven't been able to reproduce it yet in grafanalabs.

**Comment by roman-tiukh** [comment]
After update i need recreate query in all problem panels. Recreate/update query solve problem,i think its related to upgrade grafana.

**Comment by joachim-vertommen** [comment]
Indeed: saving the dashboard without making any changes seems to have solved the problem.
Thanks.
