### ISSUE TITLE
No data in graphs, query inspector keeps loading into infinity

### ISSUE THREAD

**Issue by kwoot** [alexanderzobnin/grafana-zabbix#958]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.0   | 5.0.0  | 3.12.0                 |

Hi,

I just started using Grafana (latest version) and your Zabbix plugin (also latest version).
I follow the installation and both the plugin access and the direct db connection to MariaDB say all is ok.
But the graphs remain empty.
When I want to debug one of the queries it says "Loading query inspector... "  and stays that way.
Logging is set to debug level but does not tell me anything.

Any and all clues are very welcome.

Regards, Jeroen.

**Comment by alexanderzobnin** [comment]
Hi! Are you sure your api user has access to the groups you want to query? When you create a user in Zabbix it has no access rights by default.

**Comment by kwoot** [comment]
user grafana has read rights on all groups.

**Comment by borjasueiro** [comment]
Hi!
I have the same problem with stat panels. With an item with an update interval of 1d in zabbix, I change the interval in graph to 2d (for example) it returns a no data.
Zabbix 5.0.0
Grafana 7.0.0
Plugin Zabbix-grafana 3.12.0

**Comment by alexanderzobnin** [comment]
@borjasueiro could you show your query that failed?

**Comment by borjasueiro** [comment]
@alexanderzobnin when the item is not numerical, it doesn't go into trends. I had configured the datasource to obtain trend values from 1d, that's why it came out that there was no data.

It also happened that in an item that measures the uptime, the value changed when the time interval changed, due to the same thing, when the datasource takes the information of trends, it brings the last value that appears in that table.

Thank you very much for answering so quickly!

**Comment by kwoot** [comment]
For some yet unknown reason the query inspector started working.
Graphs are still empty but now at least I can see something:

For example: the cpu graph shows: What strikes me here is the url: "api/tsdb/query"
I only know of zabbix "zabbix/api_jsonrpc.php" api url.
I guess this is only supported by Postgresql with the timescaledb extension.
This means it will not work on MySQL/MariaDB.

Maybe therein lies the source of this issue?

request:Object
url:"api/tsdb/query"
method:"POST"
data:Object
queries:Array[1]
0:Object
refId:"A"
format:"time_series"
datasourceId:3
rawSql:"SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (18471, 18472, 18474, 18473) AND clock > 1590219258 AND clock < 1590240858 GROUP BY (clock-1590219258) DIV 20, metric ORDER BY time_sec ASC"
maxDataPoints:10000
response:Object
results:Object
A:Object
refId:"A"
meta:Object
rowCount:0
sql:"SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history WHERE itemid IN (18471, 18472, 18474, 18473) AND clock > 1590219258 AND clock < 1590240858 GROUP BY (clock-1590219258) DIV 20, metric ORDER BY time_sec ASC"
series:null
tables:null
dataframes:null

**Comment by kwoot** [comment]
So, more info. The "Zabbix Template Linux Server" gives me some graphs if I make sensible selections. So at least something is working. I think I have seen enough now of what Grafana can do. Thanks for your efforts on this plugin. I do appreciate it.
