### ISSUE TITLE
Can't add or modify variable

### ISSUE THREAD

**Issue by pbrissaud** [alexanderzobnin/grafana-zabbix#959]
**Describe the bug**
After selecting Zabbix in datasource of query options in variable creation screen, all the form disappears.  Same issue when I try to modify an existing varaible.

**Expected behavior**
I see the form to add or modify the variable

**Screenshots**
Screen after selecting Zabbix in datasource
![Capture du 2020-05-22 11-42-01](https://user-images.githubusercontent.com/27202456/82654657-5c9f0280-9c21-11ea-8af0-b06a6de0c64d.png)

Errors from browser console
![Capture du 2020-05-22 11-43-54](https://user-images.githubusercontent.com/27202456/82654806-9112be80-9c21-11ea-942f-c7c67696ef22.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v7.0.0 (aee1438ff2)   | 5.0.0 (revision 9665d62)  | 3.12.0               |

I think it's a bug between the lastest version of Grafana and the plugin because it worked for me in version 6.3

**Comment by alexanderzobnin** [comment]
That's probably a Grafana bug. Try to search for the open issues in grafana repo.

**Comment by pbrissaud** [comment]
Maybe but I can add or modify varaible with other datasource

**Comment by pbrissaud** [comment]
Works now fine on v3.12.1. I was on 3.11 before... sorry !
