### ISSUE TITLE
Calculated values bases on zabbix datasource

### ISSUE THREAD

**Issue by beremour** [alexanderzobnin/grafana-zabbix#966]
Some storage device reports "% Free space" to Zabbix, but we need to Graph "% Used space" in Grafana from Zabbix datasource. So we need "100-%Free space" operation. Is it a way to do it ?

**Comment by alexanderzobnin** [comment]
Yes, use `scale(-1)` and `offset(100)`:
https://play.grafana-zabbix.org/d/q3XQ0OzMz/functions-examples?editPanel=2&orgId=2
