### ISSUE TITLE
Memory panel not getting any data

### ISSUE THREAD

**Issue by cabrizio** [alexanderzobnin/grafana-zabbix#967]
Hi, I just installed the Zabbix plugin on my grafana, and created some simple dashboard.
I was trying to add some panel as usual, and the only function that does not get any data is the Memory one.

![image](https://user-images.githubusercontent.com/25394408/82879959-0215e700-9f3e-11ea-9e95-cfec4cae7c82.png)

If I remove `Used memory %` then I get data, but I dunno how to convert it in %.

Any help on this?
Thanks

**Comment by alexanderzobnin** [comment]
Probably, you input a wrong metric name.
