### ISSUE TITLE
Querying non monitored hosts

### ISSUE THREAD

**Issue by trevorx** [alexanderzobnin/grafana-zabbix#97]
Hi,

I see in the zabbix api there is a specific flag for monitored hosts.

[https://www.zabbix.com/documentation/2.0/manual/appendix/api/host/get]
monitored_hosts flag    Return only monitored hosts

Is there a way to override the default usage of this so my dashboard query retrieves all hosts ?

Cheers,
Trev.

**Comment by alexanderzobnin** [comment]
@trevorx Yes, I think I can realise this feature like a option in query editor.

**Comment by galindro** [comment]
@alexanderzobnin are you planning to put this feature on Grafana-Zabbix 3.0 right? When did you are planning to launch this release?

**Comment by alexanderzobnin** [comment]
@galindro Yes, but it depend of my free time.

**Comment by galindro** [comment]
Did you have any forecast?

**Comment by galindro** [comment]
@alexanderzobnin any return about grafana-zabbix 3.0?

**Comment by pmelse** [comment]
Grafana 3.0 has been merged into develop.

Drop the two folders (I renamed datasource-zabbix to zabbix) into their respective plugin folders, and you should be good to add your data source.

Happy graphing,

Peter Melse

**Comment by alexanderzobnin** [comment]
Guys, can you clarify this issue? Do you need to show disabled hosts? Or only monitored?

**Comment by galindro** [comment]
Booth enabled and disabled hosts

**Comment by alexanderzobnin** [comment]
Hm, by default zabbix returns all hosts (I use Zabbix 2.4).

**Comment by trevorx** [comment]
I'll give this a go next week when I'm back in office.

On 19 June 2016 at 19:44, Alexander Zobnin <notifications@github.com> wrote:

> Hm, by default zabbix returns all hosts (I use Zabbix 2.4).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/alexanderzobnin/grafana-zabbix/issues/97#issuecomment-227013356>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHLyDK9qEHlDhg1Wc7SLZgIYgcV6TKs7ks5qNY4WgaJpZM4GN4Bp>
> .
>



-- 
-----------------------------------------------
[image: Mail]
Trevor Smith
Open Answers Ltd
http://www.openanswers.co.uk/
Email: trevor@openanswers.co.uk
Mobile: +44 (0) 7978 481428

**Comment by alexanderzobnin** [comment]
Ok, sure.

**Comment by trevorx** [comment]
Hi just tried a regexp and it pulled back the 'not monitored' hosts too so I think thats a good enough test.

Cheers,
Trev.

**Comment by incoquinita** [comment]
Is there a way to filter and suppress the not monitored hosts?

**Comment by alexanderzobnin** [comment]
@incoquinita you could open a new issue for this feature.
