### ISSUE TITLE
Zabbix data sync issue on grafana

### ISSUE THREAD

**Issue by djigs** [alexanderzobnin/grafana-zabbix#970]
Hello,

First thank you for all of your good work.
I am having synchronization issue between my zabbix and grafana data. Indeed when a metric changes in zabbix, it takes more than 30mn to be update in grafana. Zabbix and grafana are installed on the same server so I don't think it's a timezone problem.
Thanks for your help.

Zabbix version: 5.0.1
Grafana version: Grafana v7.0.1 (ef5b586d7d)
Zabbix plugin version: 3.12.2

![Screenshot](https://user-images.githubusercontent.com/50701107/83407117-50c8f280-a410-11ea-8c2b-92bb4bdcdeb8.png)

**Comment by petersonbasso** [comment]
By default, plugins cache some data that is little changed, such as item names.
Try changing the `Cache TTL` parameter to a value that is compatible with your scenario.

**Comment by djigs** [comment]
Thanks a lot for your reply.
Testing right now. I will let you know

**Comment by djigs** [comment]
I manually put the cache TTL to 2mn. Same issue. 
To give you more context I have for exemple my server status down in Zabbix but Up in grafana and  it take more than 30mn to be updated in grafana.

**Comment by djigs** [comment]
Hi, 

![giphy](https://user-images.githubusercontent.com/50701107/83546270-b5fc1100-a500-11ea-8c32-9be6a88ceb49.gif)

**Comment by petersonbasso** [comment]
> I manually put the cache TTL to 2mn. Same issue.
> To give you more context I have for exemple my server status down in Zabbix but Up in grafana and it take more than 30mn to be updated in grafana.

Did you use the suffix mn? Try using the suffix m for minutes

**Comment by djigs** [comment]
Oh yes I used the suffix m not mn(sorry mn is the french suffix)

**Comment by silveraignacio** [comment]
I Always fix this, “refreshing” the data source. I just go to data source config and click on save and test.
After that I can see newly created hosts or host groups

**Comment by djigs** [comment]
Finally, I completely reinstall the server. Everything is fine now.
