### ISSUE TITLE
Transformations

### ISSUE THREAD

**Issue by havedill** [alexanderzobnin/grafana-zabbix#971]
Are there any plans on getting the beta grafana feature "Transformations" to integrate with the zabbix plugin?

I have a zabbix item with text values. I'd like to use transformations with Regex to show only item values that contain a certain phrase. Right now when i go to use it, nothing happens, and eventually it throws an exception in the page

Example:  I collect failed logon events. I'd like to be able to filter and only show events that contain a specific users name

**Comment by alexanderzobnin** [comment]
There's nothing I can do with transformations, it's a Grafana feature, not the plugin one.
