### ISSUE TITLE
Problems: wrong sorting order

### ISSUE THREAD

**Issue by mplm17** [alexanderzobnin/grafana-zabbix#973]
Hi,

In the previous version of this plugin, we had the ability to have problems sorted by time, from the most recents problems to the older onces. It seems that the lasts versions did change that, because we now have the most recents problems in the bottom of the panel.

I didn't find a way to change that. Do you think it's possible to add the ability to choose the sorting we want?

Grafana v7.0.1
Plugin 3.12.2
Zabbix 5.0.0

Thanks

**Comment by pliniosampaio** [comment]
I tested version 3.12.4, here didn't sort by Severity, and when I clicked on the title of columns didn't work, only sorted by Time
