### ISSUE TITLE
Zabbix Problems - Problems Order/Sort

### ISSUE THREAD

**Issue by asm19** [alexanderzobnin/grafana-zabbix#974]
I have a problem with "Zabbix Problems", in Google Chrome the problems appear from the most recent to the oldest. In firefox it appears from the oldest to the most recent.
I detected this problem when I put it as a playlist on my LG TV with webOS.
In conclusion, I can't see the most recent ones because the ones that appear first are the oldest.
Is this a bug?

**Grafana**: 7.01
**Zabbix**: 4.4.7
**Grafana-Zabbix Plugin**: 3.12.2

**Google Chrome**:
![image](https://user-images.githubusercontent.com/1648981/83569700-cd48f780-a51c-11ea-9465-3a5c434bb548.png)

**Firefox**:
![image](https://user-images.githubusercontent.com/1648981/83569760-e8b40280-a51c-11ea-9b6e-69e5ca697b1b.png)

**Configuration**:
![image](https://user-images.githubusercontent.com/1648981/83569844-0d0fdf00-a51d-11ea-9fc1-52cdd03fd29f.png)

**Comment by mplm17** [comment]
Hi,

My thoughs are this is the same problem I related here : #973 

IMO the problem appears on all kind of browsers... Your Chrome may have cached old code. Ctrl+F5 should bring back the same behaviour than Firefox.

**Comment by asm19** [comment]
I checked the problem again and in Chrome the problem doesn't happen. I forced it with CTRL + F5 and it's ok.
I just have this problem on firefox and playlist in webOS.

**Comment by mplm17** [comment]
Really strange...

I've got the same on Chrome, Firefox, Edge. I don't think there is browser specific code. But maybe @alexanderzobnin can confirm that?

**Comment by garbled1** [comment]
I recently updated my plugin, and now the sorting of my triggers is completely backwards, and nothing I do fixes it.  I used to have a simple display of my 10 most recent triggers, but now all I can do is show all, and they are sorted by oldest first.  None of the options seem to do anything to change the sort order.

**Comment by asm19** [comment]
Yes, it's my problem... I have a dashboard with the latest problems to show in TV on my office, so the plugin is not useful because it always shows the older ones first.
I still haven't found a solution.

**Comment by hnyktn** [comment]
I got the same problem.

**Comment by jaylik** [comment]
We have this problem too - sorting by last change with multiple Zabbix instances is just a mess. With 3.10.1 everything works just fine.

**Comment by asm19** [comment]
> We have this problem too - sorting by last change with multiple Zabbix instances is just a mess. With 3.10.1 everything works just fine.

I tested with version 3.11.0 and it works but since this version it stopped working.

**Comment by alexanderzobnin** [comment]
Duplicates #973
