### ISSUE TITLE
"Zabbix Problems Panel" dont display problems

### ISSUE THREAD

**Issue by CastroBolt** [alexanderzobnin/grafana-zabbix#976]
**Describe the bug**
"Zabbix problem panel" don't display Zabbix problems

**Expected behavior**
this feature works  on version 3.11.0

**Screenshots**

![image](https://user-images.githubusercontent.com/29714199/83692667-d42e4380-a5ca-11ea-8ec5-f73820ca82b7.png)

**Network data**

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Grafana v7.0.0 (aee1438ff2)   | 3.4.15  |  Grafana v7.0.0 (aee1438ff2)  |

**Comment by mplm17** [comment]
Hi,

Did you try something like that?

![image](https://user-images.githubusercontent.com/39955446/83753378-72bdb180-a66a-11ea-9881-ce0fb59e40dc.png)

**Comment by cabrizio** [comment]
The issue is whit "Zabiix problems" visualizations if you change it as a table you are able to see the events, could not find a solution.

**Comment by CastroBolt** [comment]
> The issue is whit "Zabiix problems" visualizations if you change it as a table you are able to see the events, could not find a solution.



> Hi,
> 
> Did you try something like that?
> 
> ![image](https://user-images.githubusercontent.com/39955446/83753378-72bdb180-a66a-11ea-9881-ce0fb59e40dc.png)

Yep! Using Table panel works well. Only in "Zabbix problems" it don't display any data.

![image](https://user-images.githubusercontent.com/29714199/83816015-d5797200-a697-11ea-9787-40fa3b5fbf95.png)

**Comment by alexanderzobnin** [comment]
That's really strange. I use 2 queries for showing problems. First - `problem.get` to fetch problems. Then, I invoke `trigger.get` with trigger ids (got from `problem.get` result) to get triggers. But looks like Zabbix API does not return proper list of triggers, I can't find triggers with ids got from problem.get in the list. 
I have to figure this out.

**Comment by alexanderzobnin** [comment]
Ah, sorry, just noticed you're using Zabbix 3.4. It's not supported anymore, so either upgrade Zabbix or roll back to previous plugin version.

**Comment by Estevaoaaguiar** [comment]
good morning everyone, i wanted to know how do i add more than one app inside the zabbix problems plugin in grafana, for example i can only put it to appear or memory, or cpu, or else all found. But I wanted to filter just a few
