### ISSUE TITLE
Zabbix & Grafana v7

### ISSUE THREAD

**Issue by davdhillon** [alexanderzobnin/grafana-zabbix#977]
Hi,

Ive updated Grafana to version 7 and im having problems with the plug in.

Examples of behavior now are;

Slow dashboard loads - was much quicker before.
Dashboards which use variables to get different data - a lot slower.
Seeing time out error on dashboards pulling Zabbix data.
Zabbix Problems dash does not load history of problems correctly.

There has been no change to Zabbix, just an upgrade of Grafana from 6.6.7 to 7.0.2

Thanks.

**Comment by DieWeb21** [comment]
Hello,
Did you update your zabbix plugin on grafana ?

**Comment by davdhillon** [comment]
Hi,
I updated the plugin to the latest available at the time. 
My config is;
Grafana = 7.0.1
Grafana/Zabbix plugin = 3.12.2
Zabbix = 4.4.8
As I mentioned before, this worked a dream with Grafana 6. No errors and page loads were alot quicker.
Another odd behavior I have noticed, when I make changes to a query to pull info from Zabbix, some of the extra function options change after I have saved. 
Its just not working as well as it used to unfortunately.
Thanks.

**Comment by mjtrangoni** [comment]
@davdhillon there are some needed fixes also in grafana 7.0.3, which makes transformations to work properly.

**Comment by davdhillon** [comment]
@mjtrangoni are you using 7.0.3 successfully with the plugin?
I know there is a v4 of the plugin, but I dont want to make the jump just yet incase it makes things worse.
We use Grafana-Zabbix in a big way so i'm nervous to make the experience worse.

**Comment by mjtrangoni** [comment]
@davdhillon I am using grafana 7.0.3, grafana-zabbix plugin 3.12.2, and zabbix 4.2.8.

**Comment by StaelensJarne** [comment]
@mjtrangoni How did you install the plugin on Grafana 7.0.3?
I could not load the plugin config in the Grafana fronted as I was testing it in a separate environment.
Is there some additional configuration needed?

**Comment by davdhillon** [comment]
@StaelensJarne  its unsigned, so it blocked by Grafana in v7. You need to allow unsigned plugins. 
see this - https://grafana.com/docs/grafana/latest/installation/configuration/#allow-loading-unsigned-plugins

**Comment by StaelensJarne** [comment]
@davdhillon I did that:
![name](https://user-images.githubusercontent.com/26405591/84904510-aad3e400-b0af-11ea-99ab-b69a2edd4c6f.png)
But what exactly is the plugin name that you have to use?

**Comment by davdhillon** [comment]
@StaelensJarne use "grafana-cli plugins ls" to list installed plugins.
This will give you the plugin name, as its installed.
Something like "alexanderzobnin-zabbix-app".
Not committing to exact name as I think it can change for diff versions.

**Comment by davdhillon** [comment]
@StaelensJarne  so in my grafana.ini config I have;
"allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app"
remember to remove the semi colon at the front of the line to uncomment.
Save and restart your grafana services.

**Comment by StaelensJarne** [comment]
@davdhillon The output of my ls command:
`sudo grafana-cli plugins ls`
`installed plugins:`
`alexanderzobnin-zabbix-app @ 3.12.2`
and I have tried `allow_loading_unsigned_plugins = "alexanderzobnin-zabbix-app"`  and `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app` and
 `allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app@3.12.2`
In the frontend I still can't load the options for the plugin? I get this screen every time I put update:
![Options](https://user-images.githubusercontent.com/26405591/84908801-3bf98980-b0b5-11ea-9f6a-6f5cf8a9d824.png)

**Comment by davdhillon** [comment]
@StaelensJarne my screen looks the same. I dont remember what it looked like, or if it even looked different before I went to version 7.
Does this now look like this?
![image](https://user-images.githubusercontent.com/66413716/84911652-5846f780-b0b0-11ea-8175-22ce1a9210d3.png)
I think before you unblock it it says blocked, or something along those lines.
Have you tried to create a dashboard and test the plugin with queries etc?

**Comment by StaelensJarne** [comment]
@davdhillon Normally this was the page where you can configure your datasource: (this is from 6.0.0 production environment)
![Config6 0](https://user-images.githubusercontent.com/26405591/84912820-1fac1b80-b0ba-11ea-8e26-1b93dc2426f5.png)
If I create a new dashboard I don't have the Zabbix datasource anymore.
Normally you have to enable the datasource, restart grafana-server and than configure your zabbix url in this page. But this page is empty now.

**Comment by davdhillon** [comment]
Im on 7.0.1 and the Zabbix sources are listed under datasources. Mmmm. If this is a DEV enviroment, maybe take a punt with v4 of the plugin?

**Comment by alexanderzobnin** [comment]
I have Grafana 7.0.3 on my demo site (https://play.grafana-zabbix.org/) and plugin version `4.0.0-alpha1`. This is my config that ables to run unsigned plugins.

```ini
[plugins]
enable_alpha = true
allow_loading_unsigned_plugins = grafana-strava-datasource,alexanderzobnin-zabbix-datasource
```

**Comment by alexanderzobnin** [comment]
To be honest, this is described on the release page https://github.com/alexanderzobnin/grafana-zabbix/releases/tag/v4.0.0-alpha1

**Comment by davdhillon** [comment]
@alexanderzobnin ive just downloaded and unpacked alpha2, but its not loaded into grafana, its showing the older version.
If I compare the contents of the downloaded plugin and the installed one, its different.
Does this need to be installed with the grafana-cli? 
If you have a moment, could you provide steps to do this manually? 
Thank you sir.
BTW, upgraded Grafana to 7.0.3 but still seeing odd behaviour. I see with the alpha2 update there is a fix listed as saving settings in panels, which is one of the problems i currently have with v3.12.
Thanks - again

**Comment by StaelensJarne** [comment]
You need to manually download and unpack it in the plugins directory. You can't download it with the grafana-cli since it is an alpha plugin. It's working perfectly if you follow the steps. 
The only thing that I don't understand is why the parameter is named `alexanderzobnin-zabbix-datasource` and not `alexanderzobnin-zabbix-app`? In the plugin.json file the id is `alexanderzobnin-zabbix-app`, why you need then to write `alexanderzobnin-zabbix-datasource`?

**Comment by davdhillon** [comment]
Im using *app and it works.

**Comment by davdhillon** [comment]
@alexanderzobnin  v4 upacked into plugin folder, now I have two versions.
installed plugins:
alexanderzobnin-zabbix-app @ 3.12.2
alexanderzobnin-zabbix-app @ 4.0.0-alpha2
Restart the grafana service, it still shows 3.12.
Ive enabled alpha plugins in the config.

**Comment by gustavoghpf** [comment]
@alexanderzobnin 
When i unpack v4 I get the following permission error:

> pluginId=alexanderzobnin-zabbix-datasource error="fork/exec /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64: permission denied"

and after fix the permissions:

> lvl=eror msg="could not read environment variable" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource GFX_ZABBIX_DATA_PATH=unknown

plugins is as follows:

> [plugins]
> enable_alpha = true
> allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource

**Comment by HalissonHalisson** [comment]
Hi, I same this problem.


> @alexanderzobnin v4 upacked into plugin folder, now I have two versions.
> installed plugins:
> alexanderzobnin-zabbix-app @ 3.12.2
> alexanderzobnin-zabbix-app @ 4.0.0-alpha2
> Restart the grafana service, it still shows 3.12.
> Ive enabled alpha plugins in the config.

Problems History " No Alerts" 
![problemas](https://user-images.githubusercontent.com/67904396/86817734-ccdfd700-c05b-11ea-805a-40f9a04ae226.jpg)

Details of my environment : 
grafana-cli -v
Grafana CLI version 7.0.4

Default directory
/var/lib/grafana/plugins/

init.d - grafana-server 
PLUGIN_DIR=/var/lib/grafana/plug-ins

/etc/grafana/grafana.ini
[plugins]
enable_alpha = true
app_tls_skip_verify_insecure = false
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app or allow_loading_unsigned_plugins = alexanderzobnin-zabbix-database , no sucess. 
 
Please check on image show version installed "**3.10.5**" and CLI show **3.12.2** 

grafana-cli plugins ls
installed plugins:
alexanderzobnin-zabbix-app @ 3.12.2

![grafana](https://user-images.githubusercontent.com/67904396/86817096-f51b0600-c05a-11ea-96c2-a300d0e07ee9.jpg)

I appreciate any help.

**Comment by StaelensJarne** [comment]
As as I am aware there are no problems with version 3.12.2.
@HalissonHalisson and @davdhillon If you have 2 different versions installed try to uninstall the old version and reinstall the new version.
How can you know if the errors from the plugin are effectively from the new version (4.0.0-alpha2) if you have 2 versions installed?

In my environment version 4.0.0-alpha2 works perfectly fine.

**Comment by davdhillon** [comment]
Think i'll wait for 4 to go live in PROD, then use the native grafana client to install.

**Comment by davdhillon** [comment]
@alexanderzobnin  when is 4.x going live into Grafana downloads? Thanks.
