### ISSUE TITLE
Zabbix problems panel is too slow when you filter per tag and have more than 5000 triggers in PROBLEM

### ISSUE THREAD

**Issue by lucasperticarari** [alexanderzobnin/grafana-zabbix#979]
Hello, I use a dashboard with zabbix problems panel.
This is filter per tag and It is too slow to show lists of problems. Around 30 seconds or more.
I tested it using Direct DB connection on Zabbix Data Source, but this  change not succeded.
At this moment, in zabbix has 114 problems with this tag.
Does it exist any posibility that to reduce this time or something fix?

Zabbix: 4.0
Grafana: 6.6.2
Grafana plugins: alexanderzobnin-zabbix-app @ 3.12.2
![ticket_problemspanel_1](https://user-images.githubusercontent.com/50338289/83770490-83b0f780-a657-11ea-846b-50f000769965.png)
![ticket_problemspanel2](https://user-images.githubusercontent.com/50338289/83770496-84e22480-a657-11ea-8fed-ed0bba0357c9.png)

**Comment by lucasperticarari** [comment]
Hi @alexanderzobnin , sorry but have any updates or any suggestions to this?
Thank you.

**Comment by alexanderzobnin** [comment]
@lucasperticarari Hi! I've made some changes related to the tags filtering in 4.0.0-alpha. Could you try it out and left some feedback?
