### ISSUE TITLE
Plugin performance degradation

### ISSUE THREAD

**Issue by akares** [alexanderzobnin/grafana-zabbix#98]
I've upgraded plugin to new version (with filters and other new useful features) and definitely noticed up to 5x performance drop comparing old one.

Old plugin version:
- 49.08 ms Loading
- 1.82 s Scripting
- 183.17 ms Rendering
- 74.24 ms Painting

New:
- **73.99 ms** Loading
- **8.45 s** Scripting
- **237.08 ms** Rendering
- 74.07 ms Painting

For my setup (lots of heavy dashboards hosted on limited in resources Raspberry Pi-based monitors) it's too slow to be upgraded.

**Comment by alexanderzobnin** [comment]
@akares Which "Old" version you mean? 2.0.x?

**Comment by akares** [comment]
Yes
