### ISSUE TITLE
Grafana not getting any data

### ISSUE THREAD

**Issue by csfoppa** [alexanderzobnin/grafana-zabbix#982]
**Describe the bug**
There are some problem using Grafana 7.0 and Zabbix 4.4.9. After Data Source successfully created I can get any data from data source. 
The plug-in version is the last avaliable. 

![image](https://user-images.githubusercontent.com/43412127/83981368-8cbdf500-a8f3-11ea-815c-6cc991f62a08.png)

![image](https://user-images.githubusercontent.com/43412127/83981381-a52e0f80-a8f3-11ea-92db-db62e3bfdbef.png)

![image](https://user-images.githubusercontent.com/43412127/83981395-b7a84900-a8f3-11ea-9610-5fb0642e7c3f.png)
![image](https://user-images.githubusercontent.com/43412127/83981404-d1499080-a8f3-11ea-9f2c-69128332452a.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.3    | 4.4.9  | Version 3.12.2         |

**Comment by alexanderzobnin** [comment]
Hi! Check API permissions.
