### ISSUE TITLE
Installation of two versions of plugins

### ISSUE THREAD

**Issue by danidosreis** [alexanderzobnin/grafana-zabbix#984]
Is it possible to install two different versions plugins grafana-zabbix on Grafana?

**Comment by silveraignacio** [comment]
I tried it a few months ago and I couldn’t. I think it is not possible by grafana

**Comment by alexanderzobnin** [comment]
No, this is not possible. The only way you can do it on single Grafana instance is changing plugin id in `plugin.json` files:
https://github.com/alexanderzobnin/grafana-zabbix/blob/46c92ced92b00c97947ece8a85cec43ab9ce52a0/src/plugin.json#L4

https://github.com/alexanderzobnin/grafana-zabbix/blob/46c92ced92b00c97947ece8a85cec43ab9ce52a0/src/datasource-zabbix/plugin.json#L4

https://github.com/alexanderzobnin/grafana-zabbix/blob/46c92ced92b00c97947ece8a85cec43ab9ce52a0/src/panel-triggers/plugin.json#L4

But in this case you can't easy reuse dashboards and datasources, grafana will consider it like a different plugins.

**Comment by danidosreis** [comment]
I really had problems using the dashboards and datasources. Is it impossible to use or possible but difficult?

**Comment by danidosreis** [comment]
Thanks @silveraignacio @alexanderzobnin 

I changed the files that @alexanderzobnin informed and some more looking for the word alexanderzobnin-zabbix in each file

### changed files
./dist/dashboards/template_linux_server.json
./dist/dashboards/zabbix_server_dashboard.json
./dist/dashboards/zabbix_system_status.json
./dist/datasource-zabbix/module.js
./dist/datasource-zabbix/module.js.map
./dist/datasource-zabbix/plugin.json
./dist/module.js
./dist/panel-triggers/module.js
./dist/panel-triggers/module.js.map
./dist/panel-triggers/plugin.json
./dist/plugin.json
./docs/sources/configuration/provisioning.md
./src/dashboards/template_linux_server.json
./src/dashboards/zabbix_server_dashboard.json
./src/dashboards/zabbix_system_status.json
./src/datasource-zabbix/plugin.json
./src/datasource-zabbix/module.ts
./src/module.js
./src/panel-triggers/specs/migrations.spec.ts
./src/panel-triggers/specs/panel_ctrl.spec.ts
./src/panel-triggers/module.js
./src/panel-triggers/options_tab.js
./src/panel-triggers/plugin.json
./src/panel-triggers/triggers_tab.js
./src/panel-triggers/triggers_panel_ctrl.js
./src/plugin.json

### pwd
/var/lib/grafana/plugins/alexanderzobnin-zabbix-app-3111

### ls -l
![image](https://user-images.githubusercontent.com/39527066/84190821-e813f280-aa6d-11ea-9276-abeb0398835b.png)

### plugin
![image](https://user-images.githubusercontent.com/39527066/84190321-1c3ae380-aa6d-11ea-948c-e40c4bcb0e3e.png)

### datasource
![image](https://user-images.githubusercontent.com/39527066/84190353-2957d280-aa6d-11ea-9498-bcd40313ef69.png)

### dashboards 
![image](https://user-images.githubusercontent.com/39527066/84190377-370d5800-aa6d-11ea-9239-89ec15ae175a.png)
