### ISSUE TITLE
"Limit triggers" with regex is not showing the correct number of triggers

### ISSUE THREAD

**Issue by hluaces** [alexanderzobnin/grafana-zabbix#986]
**Describe the bug**

The "_Limit triggers_" limit on the "_Zabbix Problems_" panel is applying the limit before filtering the triggers, causing the panel to display a number of alerts below the specified limit, even when there's more actual alerts that fit the criteria.

**Expected behavior**

The specified amount of Zabbix triggers should be shown, even when there's filtering happening.

**Screenshots**

![image](https://user-images.githubusercontent.com/3204332/84364270-288b8180-abd0-11ea-9e25-558e4a3cb420.png)

Please note the following on the screenshot:

1. There's a "_Limit triggers_" of 13.
2. There's a "_Problems_" regex to filter out triggers.
3. There's only 3 triggers shown while even when there are more than 80 that could fit the current filter.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| Grafana v7.0.3 (00ee734baf)   | 4.0-2  | 3.12.2                 |

**Comment by alexanderzobnin** [comment]
That's because limit is an option for API query, but problem regex filter works after data returs from Zabbix.
