### ISSUE TITLE
Datas not showing in Zabbix Problems Screen

### ISSUE THREAD

**Issue by DieWeb21** [alexanderzobnin/grafana-zabbix#987]
Hi guys !

I've an issue with my grafana v7.0.3 and the last version of the plugin on some zabbix problems datas.

I've a screen with several "Zabbix problems" panel from different Zabbix data source and some of them just don't display alerts:

![image](https://user-images.githubusercontent.com/6052864/84413450-ea628200-ac10-11ea-9b8a-5bb8c28eca3c.png)

But when you want to display Data by inspect them it shows that you have some:

![test](https://user-images.githubusercontent.com/6052864/84413614-2d245a00-ac11-11ea-9977-113634e9ec86.png)
![image](https://user-images.githubusercontent.com/6052864/84413724-50e7a000-ac11-11ea-913f-ffd711634d78.png)
![image](https://user-images.githubusercontent.com/6052864/84414052-bb004500-ac11-11ea-8fc8-36d8eea3f8d2.png)

I've tested new dashboard with new panels, tried to displays every trigger, one specific in particular and it doesn't show. 

The only things I see different is the zabbix version which is 3.0 / 3.2 / 3.4 for all panels with this problem.

Thanks for your help.

**Comment by rawsGit** [comment]
Verified plugin is working.  Have you tried this setup?
Zabbix 3.4.13.
Grafana v7.0.3
plugin 3.11.0

**Comment by Skunnyk** [comment]
It looks like the plugin from 3.12 does not work anymore with zabbix-server 3.x. I have the same problem so I rolled back to 3.11 with grafana 7.
It's hidden in 3.12 release notes: https://github.com/alexanderzobnin/grafana-zabbix/commit/b41a407d702d31191c40614d845c0ab0e5ef1a45#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR27

```
- Problems panel uses new `problem.get` API which is not compatible with Zabbix 3.x, [#495](https://github.com/alexanderzobnin/grafana-zabbix/issues/495)
```
