### ISSUE TITLE
Problems panel query editor issues

### ISSUE THREAD

**Issue by heyrod** [alexanderzobnin/grafana-zabbix#988]
**Bug description**
When I open the query editor of a Problems panel and try to scroll down to see all details of the query, the query window disappears. This issue is being reproduced constantly in our DEV environment where we installed Grafana 7.0.3 and the latest version 3.12.2 of your plugin. In another environment with Grafana 6.7.4 and the same version of the plugin, the query editor works fine.

**How to reproduce**
1. Open the query editor of the Problems panel. The query window and the query details are in place.
![The query in place](https://user-images.githubusercontent.com/39294778/84500809-f1939980-acbd-11ea-9bb1-3403a11afaa2.png)
2. Try to scroll down to the bottom of the screen. The query disappears.
![The query disappeared](https://user-images.githubusercontent.com/39294778/84500844-0112e280-acbe-11ea-86d7-d7755d8dbb57.png)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.3   | 4.4.2 | 3.12.2                |

**Comment by SkovorodkinE** [comment]
We have same issue with Grafana - 6.7.4 , Zabbix - 4.4.5 , Plugin - 3.12.2

**Comment by alexanderzobnin** [comment]
Hi! Could you provide some error details from the JS console?

**Comment by heyrod** [comment]
It's also reproduced in 4.0.0
![image](https://user-images.githubusercontent.com/39294778/91436203-5055c180-e870-11ea-8ef2-07b7c9c5a281.png)

**Comment by rozniak** [comment]
This is happening for me as well, except I don't have to scroll and nothing is output into the console. Just open the panel editor and after a few seconds the queries are deleted. If you close the editor and reopen it, the queries will come back after a few seconds (like the reverse of the initial problem).

This also affects the acknowledgement window - if you try to type in a message it will be deleted on the exact same interval. I don't know if it's tied to the refresh rate of the dashboard (ours is 10s). This is annoying - the only workaround is to write your message in another window and quickly copy-paste it in before it is automatically deleted from the text box.

The only error I can get is if I open the editor and refresh the page, I get this screen:
![image](https://user-images.githubusercontent.com/13258281/91963058-449d4b80-ed05-11ea-8d03-fe7ff08f24d9.png)

**Comment by alexanderzobnin** [comment]
Could someone confirm the problem still exists in the latest plugin version (4.0.1)?

**Comment by sirbavo** [comment]
Yes, I can confirm it.

Scenario 1:
1. Add new panel. (Default data source: "Zabbix".)
1. Change "Visualization" from the default "Graph" to "Zabbix Problems".
1. Scroll down in the Query Editor.
**Result**: Query 'A' disappears.
1. Bonus step _in case if you feel completely lost and do not know what to do_:
Change back to something else e.g. "Graph", then "Zabbix Problems", then something else e.g. "Graph" again.
**Result**: An unexpected error happened: TypeError: Cannot read property 'length' of undefined.

Scenario 2 (I know it is not a normal use case, but maybe related to the base problem.):
1. Add new panel.
1. Change "Visualization" from the default "Graph" to "Zabbix Problems".
1. Change to "Graph".
1. Change to "Zabbix Problems".
1. Scroll down in the Query Editor.
**Result**: NOT OK: An unexpected error happened: TypeError: Cannot read property 'map' of undefined.

---

**Software versions**
Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
7.0.6 | 4.0.26 | 4.0.1
7.1.5 | 4.0.26 | 4.0.1
7.2.2 | 4.0.26 | 4.0.1
7.3.1 | 4.0.26 | 4.0.1

**Comment by alexanderzobnin** [comment]
Found a root cause - the panel migrations. Since grafana allows to switch between visualizations, I should change logic a bit to adjust to the new state of things.
