### ISSUE TITLE
Unable to execute the sum() function in zabbix plugin

### ISSUE THREAD

**Issue by ygk12345** [alexanderzobnin/grafana-zabbix#989]
**Describe the bug**
We have setup grafana with zabbix plugin. We are trying to collect single stat metric from four servers.

The zabbix data is being gathered from the four servers and is getting updated and shown in the single stat panel in the form of four figures.  We have applied sum() function as well to the four data values being returned. But whenever there is a change in the data, the four individual metrics are getting updated, but, the sum() function is not getting updated. It is remaining at the old value and sometimes it is showing wrong sum of the four values.

Can you suggest how to apply this function whenever there is a change in the four data values ?

**Expected behavior**
The sum () function should be updated along with the data changes

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7        | 5      |            3.12.2   |

**Comment by ygk12345** [comment]
It seems that whenever  the dashboard refreshes, the sum() function is reiterating the function over and over again from the beginning. For example, say , that we have the following four values from the four server metrics: 
server1- 10
server2- 20
server3- 30
server4- 40

Tha sum() values should return 100 as the single stat. But whenever the dashboard refreshes, the 
sum() function goes back to 10, then to 30, then to 60 and then to 100. This cycle is repeating and the sum() keeps oscillating from 10 to 100.  The expected behaviour should always take the last latest value of the metric from all the four servers and should return completed total sum . Whenever there is a change in one of the metric values, it should consider that latest value for the sum() of all the four values.

**Comment by alexanderzobnin** [comment]
Looks like you're doing it wrong. Could you show your query?

**Comment by ygk12345** [comment]
![Screenshot from 2020-06-15 18-18-33](https://user-images.githubusercontent.com/66954573/84880888-c1c40780-b0aa-11ea-8a66-c8af0b425d8f.png)
![Screenshot from 2020-06-15 18-18-47](https://user-images.githubusercontent.com/66954573/84880952-d86a5e80-b0aa-11ea-81e0-5f6878e747df.png)
![Screenshot from 2020-06-17 14-49-53](https://user-images.githubusercontent.com/66954573/84880964-dd2f1280-b0aa-11ea-8e6c-b0cfb41e90cc.png)
--------------------------------- 

I have attached the screen shots for your reference, showing the query and the individual server metrics and the single stat sum as well which is not  correct.......

**Comment by alexanderzobnin** [comment]
Ok, this is an issue related to how sum() works. Try to use panel Time shift option as a workaround (set it to the item collection interval, like `1m`).

**Comment by ygk12345** [comment]
So, do you mean that I should use the sum() function along with time shift option ? Also where can I find the panel time shift option ? Any screen shots would help.

Appreciate your time........

**Comment by ygk12345** [comment]
Also, the sum() value is changing every minute even though there is no change in the individual values. That is the problem here

**Comment by ygk12345** [comment]
Let me make it clear for you again on whats happening......

Assume the last (latest) individual values for the four servers are 10, 3, 13, 30

Now after applying the sum() function, it shows the total single stat value as 56 which is correct.
But after a few minutes, it is going back to the cumulative sum of these values from the beginning. like, 10 + 3 =13 (it shows this value in the single stat for few minutes)
then
it goes for 10 + 3 + 13 = 26(it shows this value in the single stat for few minutes)
then
it goes to 10 + 3 + 13 + 30 = 56(it shows this value in the single stat for few minutes)

So it goes on like this again andm again, instead of showing the sum of the last four values.(56)

**Comment by ygk12345** [comment]
Any idea about this behaviour ?

**Comment by alexanderzobnin** [comment]
This is because of reason described in #320

**Comment by ygk12345** [comment]
Thanks for the response. Can you suggest a workaround as we have a demo coming up shortly on Grafana. Appreciate your time and effort..............

**Comment by ygk12345** [comment]
Any idea ?

**Comment by ygk12345** [comment]
We are still waiting for a workaround................ Any update ?

**Comment by ygk12345** [comment]
Any update so far ?

**Comment by alexanderzobnin** [comment]
Workaround is a panel time shift option (1m to 5m should be ok) to make sure you're invoke function over the existing data.

![Screenshot from 2020-07-13 14-28-05](https://user-images.githubusercontent.com/4932851/87299748-47559e80-c515-11ea-8a94-f03c146a70ac.png)

**Comment by ygk12345** [comment]
I have set this
-----------
![Screenshot from 2020-07-13 17-34-11](https://user-images.githubusercontent.com/66954573/87302644-695c1a80-c52f-11ea-9f6e-a4acfdc60731.png)
---------

But still the value is looping as I indicated earlier......... The final count should be 70 .

**Comment by alexanderzobnin** [comment]
Leave only time shift, not a relative time.

**Comment by ygk12345** [comment]
Hi,

I have removed the relative time, retaining only timeshift of 1 minute. But the value is looping the sum in cumulatively.

**Comment by ygk12345** [comment]
Hi,

Nevermind, now it seems to be stable. Thanks a lot for your help. Appreciate your time..........

**Comment by ygk12345** [comment]
Hi,

Sorry to bother you again, the value is still fluctuating...........
