### ISSUE TITLE
Plugin not pulling custom metrics (userparameters)

### ISSUE THREAD

**Issue by elnoxgdl** [alexanderzobnin/grafana-zabbix#99]
Hi I've been using your plugin with grafana for a few days and I decided to add a user parameter in zabbix.

I went to grafana, tried to add a new graph and I found out the user parameter is not being pulled/shown by your plugin, I made a manual call to the zabbix api and I can see is being pulled properly. So do you know why is this happening?

I'm using Grafana 2.1.3 / Grafana-Zabbix 2.1 RC1

Thanks!

**Comment by alexanderzobnin** [comment]
@elnoxgdl can you provide your api request for pulling user parameters?

**Comment by elnoxgdl** [comment]
I'm doing a simple json rpc request to get all the items associated to a host_id
```
{"jsonrpc":"2.0","id":4,"auth":"e108c38b93600fdfd8185e976a5a0ee8","method":"item.get","params":{"extendoutput":true,"limit":1000,"hostids":"10105","user":"Admin","password":"zabbix"}}

**Comment by alexanderzobnin** [comment]
Which Zabbix version are you use?

**Comment by elnoxgdl** [comment]
Here is when I'm trying to configure the item, it jus say all even if I select ALL and filter by regex is not able to find the item.

![image](https://cloud.githubusercontent.com/assets/7197997/10527350/8b477f4e-7355-11e5-8882-03a7a6cb2758.png)

My zabbix version is 2.4.6

**Comment by elnoxgdl** [comment]
Wait a minute.... you can close this issue seems to be I was missing the part that says "text metric" instead of numeric metric.

Sorry for the trouble...
