### ISSUE TITLE
Failedexec: \"zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%"

### ISSUE THREAD

**Issue by preethamsathyamurthy** [alexanderzobnin/grafana-zabbix#991]
**Describe the bug**
Grafana plugin not installed properly
[31mEROR[0m[06-22|08:12:35] Failed to start plugin                   [31mlogger[0m=plugins.backend [31mpluginId[0m=alexanderzobnin-zabbix-datasource **[31merror[0m="exec: \"zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%"**

**Software versions**
| Grafana | Grafana-Zabbix Plugin |
Grafana 7.0.3 |Grafana-Zabbix 4.0.0-alpha2
OS - Windows

**Comment by alexanderzobnin** [comment]
Hi! Are you sure plugin installed properly? See instructions from the release page.

**Comment by myckallan** [comment]
Just add to system environments where did you put your plugin folder

1) Follow this instructions to open Environment Variables https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

2) Path Variable include plugin path, like: C:\Program Files\GrafanaLabs\grafana\data\plugins\alexanderzobnin-zabbix-app

**Comment by taner91xp** [comment]
Hello Alexander,

I am faced with issue with Windows Based latest version of Grafana and the latest version of zabbix plugin.

Please could you help me?
I tried Linux based version and it works perfectly.
But in Windows 10 and in Windows Server Datacenter 2019 I see the same log:

t=2021-01-30T22:00:50+0200 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="exec: \"zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%"


t=2021-01-30T22:00:50+0200 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource error="exec: \"zabbix-plugin_windows_amd64.exe\": executable file not found in %PATH%"
t=2021-01-30T22:02:36+0200 lvl=eror msg="Plugin unavailable" logger=context userId=1 orgId=1 uname=admin error="Plugin unavailable"
t=2021-01-30T22:02:36+0200 lvl=eror msg="Plugin unavailable" logger=context userId=1 orgId=1 uname=admin error="Plugin unavailable"
t=2021-01-30T22:02:36+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/1/resources/zabbix-api status=503 remote_addr=10.10.60.32 time_ms=24 size=32 referer=http://10.10.10.34:3000/datasources/edit/1/
t=2021-01-30T22:02:36+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/1/resources/zabbix-api status=503 remote_addr=10.10.60.32 time_ms=3 size=32 referer=http://10.10.10.34:3000/datasources/edit/1/

**Comment by taner91xp** [comment]
> Just add to system environments where did you put your plugin folder
> 
> 1. Follow this instructions to open Environment Variables https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0
> 2. Path Variable include plugin path, like: C:\Program Files\GrafanaLabs\grafana\data\plugins\alexanderzobnin-zabbix-app

I didn't understand your solution,  could you explain with details in your words?

I don't understand this what do you mean?
 1. Follow this instructions to open Environment Variables https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0
 
 Yes, the path is the same:
 2. Path Variable include plugin path, like: C:\Program Files\GrafanaLabs\grafana\data\plugins\alexanderzobnin-zabbix-app

**Comment by myckallan** [comment]
Hello @taner91xp

I took a look in the link I've posted from Oracle but now it's pointing to other subject, sorry. But I just added the path in Environment Variables just like in the imagem below and it worked.
I'm using Windows Server 2016, but i think it won't be different in 2019.

![image](https://user-images.githubusercontent.com/71901934/106397646-43279a80-63ed-11eb-990d-2c5ca777726e.png)

**Comment by taner91xp** [comment]
> Hello @taner91xp
> 
> I took a look in the link I've posted from Oracle but now it's pointing to other subject, sorry. But I just added the path in Environment Variables just like in the imagem below and it worked.
> I'm using Windows Server 2016, but i think it won't be different in 2019.
> 
> ![image](https://user-images.githubusercontent.com/71901934/106397646-43279a80-63ed-11eb-990d-2c5ca777726e.png)

Hello.

Thank you, yes I figured out it few hours ago and everything is work like expected.

**Comment by taner91xp** [comment]
> Hello @taner91xp
> 
> I took a look in the link I've posted from Oracle but now it's pointing to other subject, sorry. But I just added the path in Environment Variables just like in the imagem below and it worked.
> I'm using Windows Server 2016, but i think it won't be different in 2019.
> 
> ![image](https://user-images.githubusercontent.com/71901934/106397646-43279a80-63ed-11eb-990d-2c5ca777726e.png)


Hello myckallan,

Could I ask you something?
How did you set the alert value in the email notification? 
For example, when the traffic is above 100 Mb/s  the current value is  150000000  and in the email notification is showed 150000000, is it possible to correct it to the true data rate?  150 Mb/s?

**Comment by myckallan** [comment]
Sorry for late,
I'm not using email notification yet. I just made a bit of tests so I can't help you right now.
I hope in a few days I could start working with alerts and maybe have a lit bit of more information.

But reading your doubt... I think you need to set the value to the specific unit to it work correctly.

Regards

**Comment by taner91xp** [comment]
> Sorry for late,
> I'm not using email notification yet. I just made a bit of tests so I can't help you right now.
> I hope in a few days I could start working with alerts and maybe have a lit bit of more information.
> 
> But reading your doubt... I think you need to set the value to the specific unit to it work correctly.
> 
> Regards

Hello  myckallan , thank you for your answer,
I want to ask you and for LDAPS and HTTPS, certificates with Grafana under Windows Server, but I can't find you.
Please could you write me at  taner_rasim@taner-bg.com.

Thank you for your attention.
I remain at your disposal.
Best Regards.
