### ISSUE TITLE
 Error loading on Zabbix Problems

### ISSUE THREAD

**Issue by paydaycay** [alexanderzobnin/grafana-zabbix#995]
**Describe the bug**
On Zabbix Problems Panel, I get an error "Error loading: alexanderzobnin-zabbix-triggers-panel"

**Expected behavior**
I expect to see all problems from my Zabbix server.

**Screenshots**
![image](https://user-images.githubusercontent.com/8417078/86572624-77c89600-bf73-11ea-98c3-2691b41f0701.png)

**Network data**
When I check the response in Query Inspector, I can see I correctly retrieve my 2 Zabbix problems:

![image](https://user-images.githubusercontent.com/8417078/86572800-b8c0aa80-bf73-11ea-83ab-80a22b16f57e.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.4.2   | 4.4.1  | 3.12.2                 |

**Comment by alexanderzobnin** [comment]
Latest plugin version is not compatible with grafana 6.x.
