### ISSUE TITLE
Zabbix Problems didn`t work with Zabbix 3.0.15

### ISSUE THREAD

**Issue by Tepew** [alexanderzobnin/grafana-zabbix#998]
Zabbix Problems didn`t work with Zabbix 3.0.15

![image](https://user-images.githubusercontent.com/42611903/87518058-704a7080-c688-11ea-9bcf-7ae985c8d43d.png)

code:-32602
name:"Invalid params."
data:"Incorrect API "problem"."
message:"Zabbix API Error: Invalid params. Incorrect API "problem"."

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.0.3   | 3.0.15  | 3.12.2                 |

**Comment by johnseekins** [comment]
Plugin >= 3.12.0 no longer properly supports Zabbix < 4.0.

**Comment by alexanderzobnin** [comment]
https://github.com/alexanderzobnin/grafana-zabbix/blob/master/CHANGELOG.md#changed
