### ISSUE TITLE
Unable to config a zabbix datasource

### ISSUE THREAD

**Issue by msaf1980** [alexanderzobnin/grafana-zabbix#999]
Unable to configure zabbix datasource

Unable to find /public/emotion and some other url

Versions
grafana-6.2.5-1.x86_64 (from rpm)
alexanderzobnin-zabbix-app @ 3.12.2
![zabbix_datasource](https://user-images.githubusercontent.com/20159464/87905861-eaa93500-ca7a-11ea-9d0c-fde8d3458a7a.png)

**Comment by ericcontainer** [comment]
I'm having the same problem.
Grafana v6.2.4 (from rpm)

Erro after upgrade from: 3.10.2

Zabbix plugin failed
Error: Fetch error: 404 Not Found Instantiating https://mywebmon.foo/public/emotion Loading https://mywebmon.foo/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module

**Comment by alexanderzobnin** [comment]
Hi! Latest plugin is not compatible with Grafana 6. Try to use Grafana 7 or downgrade plugin.
